/* Deutsch Master - B1 expansion pack (ADDITIVE, lazy-loadable). Same format as curr-a2.js. */
"use strict";
window.CURR_B1B = {
level: "B1",
kapitel: [],
categories: [],
words: [
["Arbeitsvertrag", "der", "عقد العمل", "work contract", "أربايتز-فيرتراج", "اسم", "Career", "K9", "die Arbeitsverträge", "Lies den Arbeitsvertrag genau.", "اقرأ عقد العمل بدقة.", "Read the work contract carefully."],
["Einarbeitungszeit", "die", "فترة التأهيل", "onboarding period", "آين-أربايتسونجز-تسايت", "اسم", "Career", "K9", "die Einarbeitungszeiten", "Die Einarbeitungszeit endet bald.", "فترة التأهيل تنتهي قريبًا.", "Onboarding ends soon."],
["Überstunden", "die", "العمل الإضافي", "overtime", "أوبِر-شتوندِن", "اسم", "Career", "K9", "", "Überstunden werden extra bezahlt.", "الإضافي يُدفع منفصلًا.", "Overtime is paid extra."],
["Schicht", "die", "الوردية", "shift", "شِشت", "اسم", "Career", "K9", "die Schichten", "Ich arbeite in der Nachtschicht.", "أعمل في وردية الليل.", "I work the night shift."],
["Schichtwechsel", "der", "تبديل الوردية", "shift change", "شِشت-فِكْسِل", "اسم", "Career", "K9", "die Schichtwechsel", "Der Schichtwechsel ist um sechs.", "تبديل الوردية في السادسة.", "Shift change is at six."],
["Pausenraum", "der", "غرفة الاستراحة", "break room", "باوزِن-راوم", "اسم", "Career", "K9", "die Pausenräume", "Der Pausenraum ist neu gestrichen.", "غرفة الاستراحة مدهونة حديثًا.", "The break room is newly painted."],
["Betriebsrestaurant", "das", "مطعم الشركة", "staff restaurant", "بِتريبز-رِستوران", "اسم", "Career", "K9", "die Betriebsrestaurants", "Das Betriebsrestaurant kocht frisch.", "مطعم الشركة يطبخ طازجًا.", "The staff restaurant cooks fresh."],
["Dienstreise", "die", "رحلة العمل", "business trip", "دينست-رايزَه", "اسم", "Career", "K9", "die Dienstreisen", "Die Dienstreise dauert eine Woche.", "رحلة العمل أسبوع.", "The business trip lasts a week."],
["Spesen", "die", "مصاريف العمل", "expenses", "شبيزِن", "اسم", "Career", "K9", "", "Reiche die Spesen bitte ein.", "قدّم المصاريف من فضلك.", "Submit the expenses please."],
["einreichen", "-", "يقدّم (أوراقًا)", "to submit", "آين-رايشِن", "فعل", "Career", "K9", "", "Reiche den Antrag bald ein.", "قدّم الطلب قريبًا.", "Submit the application soon."],
["Antrag", "der", "الطلب الرسمي", "application", "أن-تراج", "اسم", "Career", "K9", "die Anträge", "Der Antrag liegt schon vor.", "الطلب موجود بالفعل.", "The application is already there."],
["Genehmigung", "die", "الموافقة", "approval", "جِنِيمِجونج", "اسم", "Career", "K9", "die Genehmigungen", "Ohne Genehmigung geht nichts.", "بدون موافقة لا شيء.", "Nothing works without approval."],
["genehmigen", "-", "يوافق رسميًا", "to approve", "جِنِيمِجِن", "فعل", "Career", "K9", "", "Der Chef genehmigt den Urlaub.", "المدير يوافق على الإجازة.", "The boss approves the holiday."],
["widersprechen", "-", "يعترض", "to object", "فيدِر-شبرِخِن", "فعل", "Career", "K9", "", "Er widerspricht dem Vorschlag höflich.", "هو يعترض على الاقتراح بأدب.", "He politely objects to the proposal."],
["Ausschuss", "der", "اللجنة", "committee", "أوز-شوس", "اسم", "Society", "K11", "die Ausschüsse", "Der Ausschuss tagt jeden Montag.", "اللجنة تجتمع كل اثنين.", "The committee meets every Monday."],
["tagen", "-", "يجتمع (لجنة)", "to convene", "تاجِن", "فعل", "Society", "K11", "", "Das Parlament tagt heute.", "البرلمان يجتمع اليوم.", "Parliament convenes today."],
["Geschäftsordnung", "die", "اللائحة الداخلية", "rules of procedure", "جِشِفتس-أوردنونج", "اسم", "Career", "K9", "die Geschäftsordnungen", "Die Geschäftsordnung regelt den Ablauf.", "اللائحة تنظّم سير العمل.", "The rules govern the procedure."] ,
["Protokoll", "das", "المحضر", "minutes", "بروتوكول", "اسم", "Career", "K9", "die Protokolle", "Wer schreibt das Protokoll?", "من يكتب المحضر؟", "Who writes the minutes?"],
["protokollieren", "-", "يدوّن المحضر", "to minute", "بروتوكوليرِن", "فعل", "Career", "K9", "", "Sie protokolliert jede Sitzung.", "هي تدوّن كل جلسة.", "She minutes every session."],
["Sitzung", "die", "الجلسة", "session", "زِتسونج", "اسم", "Career", "K9", "die Sitzungen", "Die Sitzung endet um elf.", "الجلسة تنتهي الحادية عشرة.", "The session ends at eleven."],
["Anwesenheit", "die", "الحضور", "presence", "أن-فيزِنهايت", "اسم", "Career", "K9", "", "Bitte bestätigen Sie die Anwesenheit.", "أكّد الحضور من فضلك.", "Please confirm presence."],
["Abwesenheit", "die", "الغياب", "absence", "أب-فيزِنهايت", "اسم", "Career", "K9", "", "Bei Abwesenheit bitte melden.", "عند الغياب أبلغ من فضلك.", "Report absence please."],
["Vertretung", "die", "الإنابة", "cover", "فيرترِيتونج", "اسم", "Career", "K9", "die Vertretungen", "Meine Vertretung kennt den Fall.", "من ينوب عني يعرف القضية.", "My cover knows the case."],
["vertreten", "-", "ينوب عن", "to represent", "فيرترِيتِن", "فعل", "Career", "K9", "", "Sie vertritt die Abteilung allein.", "هي تمثّل القسم وحدها.", "She represents the department alone."],
["Zuständigkeit", "die", "الاختصاص", "remit", "تسو-شتِندِشْكايت", "اسم", "Career", "K9", "", "Das fällt in meine Zuständigkeit.", "هذا ضمن اختصاصي.", "That falls in my remit."],
["zuständig", "-", "مختصّ", "in charge", "تسو-شتِندِش", "صفة", "Career", "K9", "", "Wer ist hierfür zuständig?", "من المختصّ بهذا؟", "Who is in charge here?"],
["Weisung", "die", "التعليمات", "instruction", "فايزونج", "اسم", "Career", "K9", "die Weisungen", "Folge der Weisung des Chefs.", "اتبع تعليمات المدير.", "Follow the boss's instruction."],
["anweisen", "-", "يوجّه", "to instruct", "أن-فايزِن", "فعل", "Career", "K9", "", "Der Chef weist uns genau an.", "المدير يوجّهنا بدقة.", "The boss instructs us precisely."],
["Befugnis", "die", "الصلاحية", "authority", "بِفوجنِس", "اسم", "Career", "K9", "die Befugnisse", "Ohne Befugnis darfst du nicht unterschreiben.", "بدون صلاحية لا توقّع.", "Without authority you may not sign."],
["befugt", "-", "مخوّل", "authorised", "بِفوجت", "صفة", "Career", "K9", "", "Nur Befugte betreten das Archiv.", "المخوّلون فقط يدخلون الأرشيف.", "Only authorised enter the archive."],
["Archiv", "das", "الأرشيف", "archive", "أرشيف", "اسم", "Career", "K9", "die Archive", "Das Archiv liegt im Keller.", "الأرشيف في القبو.", "The archive is in the basement."],
["archivieren", "-", "يؤرشف", "to archive", "أرشيفيرِن", "فعل", "Career", "K9", "", "Archiviere die alten Rechnungen.", "أرشف الفواتير القديمة.", "Archive the old invoices."],
["Schlussrechnung", "die", "الفاتورة النهائية", "final invoice", "شلوس-رِشنونج", "اسم", "Career", "K9", "die Schlussrechnungen", "Die Schlussrechnung folgt bald.", "النهائية تلي قريبًا.", "The final invoice follows soon."],
["Mahnung", "die", "التذكير بالدفع", "reminder", "مانونج", "اسم", "Career", "K9", "die Mahnungen", "Nach der Mahnung zahle ich sofort.", "بعد التذكير أدفع فورًا.", "After the reminder I pay at once."],
["mahnen", "-", "يطالب بالدفع", "to dun", "مانِن", "فعل", "Career", "K9", "", "Die Firma mahnt zweimal.", "الشركة تطالب مرتين.", "The firm duns twice."],
["Zahlungsfrist", "die", "مهلة الدفع", "payment deadline", "تسالونجز-فريست", "اسم", "Career", "K9", "die Zahlungsfristen", "Die Frist endet am Freitag.", "المهلة تنتهي الجمعة.", "The deadline ends Friday."],
["Skonto", "das", "خصم الدفع المبكر", "cash discount", "سكونتو", "اسم", "Career", "K9", "die Skonti", "Bei Vorkasse gibt es Skonto.", "عند الدفع المقدّم يوجد خصم.", "Advance payment earns discount."],
["Vorkasse", "die", "الدفع المقدّم", "advance payment", "فور-كاسَّه", "اسم", "Career", "K9", "", "Wir liefern nur gegen Vorkasse.", "نورّد مقابل دفع مقدّم فقط.", "We deliver against advance only."],
["liefern", "-", "يورّد", "to deliver", "ليفِرن", "فعل", "Career", "K9", "", "Die Firma liefert pünktlich.", "الشركة تورّد في الموعد.", "The firm delivers on time."],
["Lieferung", "die", "التوريد", "delivery", "ليفِرونج", "اسم", "Career", "K9", "die Lieferungen", "Die Lieferung trifft morgen ein.", "التوريد يصل غدًا.", "Delivery arrives tomorrow."],
["Lieferant", "der", "المورّد", "supplier", "ليفِرانت", "اسم", "Career", "K9", "die Lieferanten", "Der Lieferant meldet Verzug.", "المورّد يبلّغ عن تأخير.", "The supplier reports delay."],
["Verzug", "der", "التأخير", "delay", "فيرتسوج", "اسم", "Career", "K9", "", "Der Verzug kostet uns Geld.", "التأخير يكلّفنا مالًا.", "Delay costs us money."],
["Mängel", "die", "العيوب", "defects", "مِنجِل", "اسم", "Career", "K9", "", "Die Ware weist Mängel auf.", "البضاعة بها عيوب.", "The goods show defects."],
["mangelhaft", "-", "معيب", "defective", "مانجِل-هافت", "صفة", "Career", "K9", "", "Die Lieferung war mangelhaft.", "التوريد كان معيبًا.", "Delivery was defective."],
["Reklamation", "die", "الشكوى", "complaint", "رِكلاماتْسيون", "اسم", "Career", "K9", "die Reklamationen", "Ihre Reklamation prüfen wir sofort.", "شكواك نفحصها فورًا.", "We check your complaint at once."],
["reklamieren", "-", "يشتكي", "to complain", "رِكلاميرِن", "فعل", "Career", "K9", "", "Der Kunde reklamiert die Rechnung.", "العميل يشتكي من الفاتورة.", "The customer complains about invoice."],
["Gutschrift", "die", "الإشعار الدائن", "credit note", "جوت-شرِفت", "اسم", "Career", "K9", "die Gutschriften", "Sie erhalten eine Gutschrift.", "ستحصل على إشعار دائن.", "You receive a credit note."],
["gutschreiben", "-", "يضيف رصيدًا", "to credit", "جوت-شرايبِن", "فعل", "Career", "K9", "", "Wir schreiben den Betrag gut.", "نضيف المبلغ لرصيدك.", "We credit the amount."],
["Kontoauszug", "der", "كشف الحساب", "statement", "كونتو-أوزتسوج", "اسم", "Career", "K9", "die Kontoauszüge", "Der Kontoauszug kommt monatlich.", "الكشف يصل شهريًا.", "The statement arrives monthly."],
["Dauerauftrag", "der", "الأمر المستديم", "standing order", "داوِر-أوفت راج", "اسم", "Career", "K9", "die Daueraufträge", "Die Miete läuft per Dauerauftrag.", "الإيجار بأمر مستديم.", "Rent runs by standing order."],
["Lastschrift", "die", "الخصم المباشر", "direct debit", "لاست-شرِفت", "اسم", "Career", "K9", "die Lastschriften", "Die Lastschrift platzt mangels Deckung.", "الخصم يرتدّ لنقص الرصيد.", "Debit bounces for lack of funds."],
["Deckung", "die", "التغطية (رصيد)", "cover", "دِكونج", "اسم", "Career", "K9", "", "Ohne Deckung keine Abbuchung.", "بدون تغطية لا خصم.", "No debit without cover."],
["abbuchen", "-", "يخصم", "to debit", "أب-بوخِن", "فعل", "Career", "K9", "", "Die Bank bucht monatlich ab.", "البنك يخصم شهريًا.", "The bank debits monthly."],
["überweisen", "-", "يحوّل (مالًا)", "to transfer", "أوبِر-فايزِن", "فعل", "Career", "K9", "", "Überweise den Betrag bis Montag.", "حوّل المبلغ قبل الاثنين.", "Transfer the amount by Monday."],
["Echtzeitüberweisung", "die", "التحويل الفوري", "instant transfer", "إشت-تسايت-أوبِر-فايزونج", "اسم", "Career", "K9", "die Echtzeitüberweisungen", "Die Echtzeitüberweisung dauert Sekunden.", "الفوري يستغرق ثوانٍ.", "Instant transfer takes seconds."],
["Verwendungszweck", "der", "الغرض من التحويل", "reference", "فيرفِندونجز-تسفِك", "اسم", "Career", "K9", "die Verwendungszwecke", "Gib den Zweck genau an.", "اذكر الغرض بدقة.", "State the reference precisely."],
["IBAN", "die", "الآيبان", "IBAN", "إيبان", "اسم", "Career", "K9", "", "Die IBAN steht auf der Karte.", "الآيبان على البطاقة.", "The IBAN is on the card."],
["BIC", "der", "الرمز البنكي", "BIC", "بي-آي-تسي", "اسم", "Career", "K9", "", "BIC und IBAN gehören zusammen.", "الرمز والآيبان معًا.", "BIC and IBAN belong together."],
["Effektivzins", "der", "الفائدة الفعلية", "effective rate", "إفِكتيف-تْسِينس", "اسم", "Career", "K9", "die Effektivzinsen", "Der Effektivzins liegt bei drei Prozent.", "الفائدة الفعلية ثلاثة بالمئة.", "The effective rate is three percent."],
["Tilgung", "die", "السداد", "repayment", "تِيلجونج", "اسم", "Career", "K9", "die Tilgungen", "Die Tilgung läuft über zehn Jahre.", "السداد على عشر سنوات.", "Repayment runs ten years."],
["tilgen", "-", "يسدّد", "to repay", "تِيلجِن", "فعل", "Career", "K9", "", "Er tilgt den Kredit pünktlich.", "يسدّد القرض في موعده.", "He repays the loan on time."],
["Kredit", "der", "القرض", "loan", "كرِديت", "اسم", "Career", "K9", "die Kredite", "Der Kredit finanziert das Haus.", "القرض يموّل البيت.", "The loan finances the house."],
["Schulden", "die", "الديون", "debts", "شولدِن", "اسم", "Career", "K9", "", "Schulden drücken die Stimmung.", "الديون تكئب المزاج.", "Debts depress the mood."],
["verschuldet", "-", "مَدين", "indebted", "فيرشولدِت", "صفة", "Career", "K9", "", "Die Firma ist hoch verschuldet.", "الشركة مدينة جدًا.", "The firm is heavily indebted."],
["Insolvenz", "die", "الإفلاس", "insolvency", "إنزولفِنتس", "اسم", "Career", "K9", "die Insolvenzen", "Nach der Insolvenz beginnt er neu.", "بعد الإفلاس يبدأ من جديد.", "After insolvency he restarts."],
["Gläubiger", "der", "الدائن", "creditor", "جلويبِجِر", "اسم", "Career", "K9", "die Gläubiger", "Die Gläubiger warten auf Geld.", "الدائنون ينتظرون المال.", "Creditors await money."],
["Schuldner", "der", "المَدين", "debtor", "شولدنِر", "اسم", "Career", "K9", "die Schuldner", "Der Schuldner zahlt in Raten.", "المَدين يدفع أقساطًا.", "The debtor pays in instalments."],
["Rate", "die", "القسط", "instalment", "راتَه", "اسم", "Career", "K9", "die Raten", "Die Rate beträgt hundert Euro.", "القسط مئة يورو.", "The instalment is one hundred euros."],
["Anzahlung", "die", "الدفعة المقدّمة", "down payment", "أن-تسالونج", "اسم", "Career", "K9", "die Anzahlungen", "Die Anzahlung sichert den Auftrag.", "المقدّم يؤمّن الطلب.", "Down payment secures the order."],
["anzahlen", "-", "يدفع مقدّمًا", "to pay down", "أن-تسالِن", "فعل", "Career", "K9", "", "Wir zahlen zehn Prozent an.", "ندفع عشرة بالمئة مقدّمًا.", "We pay ten percent down."],
["Vorlesungsverzeichnis", "das", "دليل المحاضرات", "course catalogue", "فور-ليزونجز-فيرتسايشنِس", "اسم", "Education", "K9", "die Vorlesungsverzeichnisse", "Das Verzeichnis erscheint jedes Semester.", "الدليل يصدر كل فصل.", "The catalogue appears each semester."],
["Sprechzeit", "die", "وقت الاستقبال", "consultation time", "شبرِخ-تسايت", "اسم", "Education", "K9", "die Sprechzeiten", "Die Sprechzeit endet um zwölf.", "الاستقبال ينتهي الثانية عشرة.", "Consultation ends at twelve."],
["abhalten", "-", "يعقد", "to hold", "أب-هالتِن", "فعل", "Education", "K9", "", "Wir halten die Prüfung bald ab.", "نعقد الامتحان قريبًا.", "We hold the exam soon."],
["Prüfungsamt", "das", "مكتب الامتحانات", "examinations office", "بروفونجز-أمت", "اسم", "Education", "K9", "die Prüfungsämter", "Das Prüfungsamt meldet die Termine.", "المكتب يعلن المواعيد.", "The office announces dates."],
["Rücktritt", "der", "الانسحاب", "withdrawal", "روك-ترِت", "اسم", "Education", "K9", "die Rücktritte", "Der Rücktritt ist noch möglich.", "الانسحاب ما زال ممكنًا.", "Withdrawal is still possible."],
["zurücktreten", "-", "ينسحب", "to withdraw", "تسوروك-ترِيتِن", "فعل", "Education", "K9", "", "Tritt rechtzeitig von der Prüfung zurück.", "انسحب من الامتحان في الوقت.", "Withdraw from the exam in time."],
["Nachprüfung", "die", "امتحان الإعادة", "resit", "ناخ-بروفونج", "اسم", "Education", "K9", "die Nachprüfungen", "Die Nachprüfung findet im Herbst statt.", "الإعادة في الخريف.", "The resit takes place in autumn."],
["wiederholen", "-", "يعيد / يكرّر", "to repeat", "فيدِر-هولِن", "فعل", "Education", "K9", "", "Wiederhole die Vokabeln täglich.", "كرّر المفردات يوميًا.", "Repeat the vocabulary daily."],
["Wiederholung", "die", "التكرار", "repetition", "فيدِر-هولونج", "اسم", "Education", "K9", "die Wiederholungen", "Wiederholung festigt das Wissen.", "التكرار يثبّت المعرفة.", "Repetition consolidates knowledge."],
["Lernkartei", "die", "بطاقات التعلّم", "flashcards", "لِرن-كارتاي", "اسم", "Education", "K9", "die Lernkarteien", "Mit der Kartei lernst du schneller.", "بالبطاقات تتعلّم أسرع.", "With cards you learn faster."],
["Eselsbrücke", "die", "حيلة الحفظ", "mnemonic", "إيزِلز-بروكَّه", "اسم", "Education", "K9", "die Eselsbrücken", "Eine Eselsbrücke hilft dem Gedächtnis.", "الحيلة تساعد الذاكرة.", "A mnemonic helps memory."],
["Gedächtnis", "das", "الذاكرة", "memory", "جِدِختنِس", "اسم", "Education", "K9", "", "Regelmaßiges Üben stärkt das Gedächtnis.", "التدريب المنتظم يقوّي الذاكرة.", "Regular practice strengthens memory."],
["Konzentration", "die", "التركيز", "concentration", "كونتسِنتراتْسيون", "اسم", "Education", "K9", "", "Volle Konzentration bringt Erfolg.", "التركيز الكامل يجلب النجاح.", "Full concentration brings success."],
["konzentrieren", "-", "يركّز", "to concentrate", "كونتسِنتريرِن", "فعل", "Education", "K9", "", "Konzentrier dich auf die Aufgabe.", "ركّز على المهمة.", "Concentrate on the task."],
["Ablenkung", "die", "التشتيت", "distraction", "أب-لِنكونج", "اسم", "Education", "K9", "die Ablenkungen", "Das Handy ist die größte Ablenkung.", "الهاتف أكبر مشتّت.", "The phone is the biggest distraction."],
["ablenken", "-", "يشتّت", "to distract", "أب-لِنكِن", "فعل", "Education", "K9", "", "Lärm lenkt mich beim Lernen ab.", "الضجيج يشتّتني أثناء المذاكرة.", "Noise distracts me while studying."],
["Lernplan", "der", "خطة المذاكرة", "study plan", "لِرن-بلان", "اسم", "Education", "K9", "die Lernpläne", "Ein Lernplan strukturiert die Woche.", "خطة تنظّم الأسبوع.", "A plan structures the week."],
["Stoff", "der", "المنهج", "syllabus", "شتوف", "اسم", "Education", "K9", "die Stoffe", "Der Stoff ist umfangreich, aber machbar.", "المنهج واسع لكن ممكن.", "The syllabus is vast but doable."],
["Lücke", "die", "الفجوة", "gap", "لوكَّه", "اسم", "Education", "K9", "die Lücken", "Schließe deine Lücken gezielt.", "سدّ فجواتك باستهداف.", "Close your gaps purposefully."],
["schließen", "-", "يسدّ / يغلق", "to close", "شليسِن", "فعل", "Education", "K9", "", "Die Bibliothek schließt um acht.", "المكتبة تغلق الثامنة.", "The library closes at eight."],
["Stadtbibliothek", "die", "مكتبة المدينة", "city library", "شتات-بيبليوتيك", "اسم", "Education", "K9", "die Stadtbibliotheken", "Die Stadtbibliothek öffnet sonntags.", "مكتبة المدينة تفتح الأحد.", "The city library opens Sundays."],
["ausleihen", "-", "يستعير", "to borrow", "أوز-لايِن", "فعل", "Education", "K9", "", "Leih dir ein Wörterbuch aus.", "استعر قاموسًا.", "Borrow a dictionary."],
["verlängern", "-", "يمدّد", "to extend", "فيرلِنجِرن", "فعل", "Education", "K9", "", "Verlängere die Leihfrist online.", "مدّد الاستعارة أونلاين.", "Extend the loan online."],
["Leihfrist", "die", "مهلة الاستعارة", "loan period", "لاي-فريست", "اسم", "Education", "K9", "die Leihfristen", "Die Frist beträgt vier Wochen.", "المهلة أربعة أسابيع.", "The period is four weeks."],
["Mahngebühr", "die", "غرامة التأخير", "late fee", "مان-جِبور", "اسم", "Education", "K9", "die Mahngebühren", "Die Gebühr wächst täglich.", "الغرامة تكبر يوميًا.", "The fee grows daily."],
["Fachwörterbuch", "das", "القاموس المتخصّص", "specialist dictionary", "فاخ-فورتِر-بوخ", "اسم", "Education", "K9", "die Fachwörterbücher", "Das Fachwörterbuch hilft enorm.", "المتخصّص يساعد جدًا.", "The specialist dictionary helps hugely."],
["nachschlagen", "-", "يبحث (في مرجع)", "to look up", "ناخ-شلاجِن", "فعل", "Education", "K9", "", "Schlage unbekannte Wörter sofort nach.", "ابحث الكلمات الجديدة فورًا.", "Look up unknown words at once."],
["Fachbegriff", "der", "المصطلح", "technical term", "فاخ-بِجْرِف", "اسم", "Education", "K9", "die Fachbegriffe", "Jedes Fach hat eigene Begriffe.", "كل تخصص له مصطلحاته.", "Each field has its terms."],
["Glossar", "das", "المسرد", "glossary", "جلوسار", "اسم", "Education", "K9", "die Glossare", "Das Glossar erklärt die Begriffe.", "المسرد يشرح المصطلحات.", "The glossary explains terms."],
["Fußnote", "die", "الحاشية", "footnote", "فوز-نوتَه", "اسم", "Education", "K9", "die Fußnoten", "Die Fußnote klärt die Quelle.", "الحاشية توضّح المصدر.", "The footnote clarifies the source."],
["Quellenangabe", "die", "توثيق المصدر", "citation", "كْفِلِن-أنجابَه", "اسم", "Education", "K9", "die Quellenangaben", "Ohne Angabe droht Plagiat.", "بدون توثيق يوجد انتحال.", "Without citation threatens plagiarism."],
["Plagiat", "das", "الانتحال", "plagiarism", "بلاجيات", "اسم", "Education", "K9", "die Plagiate", "Plagiat führt zum Ausschluss.", "الانتحال يؤدي للفصل.", "Plagiarism leads to expulsion."],
["Ausschluss", "der", "الفصل", "expulsion", "أوز-شلوس", "اسم", "Education", "K9", "die Ausschlüsse", "Der Ausschluss gilt ein Semester.", "الفصل فصلًا واحدًا.", "Expulsion lasts one semester."],
["Zitat", "das", "الاقتباس", "quotation", "تْسيتات", "اسم", "Education", "K9", "die Zitate", "Das Zitat stammt von Goethe.", "الاقتباس من جوته.", "The quotation is from Goethe."],
["Beamer", "der", "البروجكتور", "projector", "بيمِر", "اسم", "Tech", "K10", "die Beamer", "Der Beamer zeigt die Folien.", "البروجكتور يعرض الشرائح.", "The projector shows the slides."],
["Folie", "die", "الشريحة", "slide", "فولْيَه", "اسم", "Tech", "K10", "die Folien", "Die nächste Folie folgt gleich.", "الشريحة التالية حالًا.", "The next slide follows shortly."],
["Flipchart", "das", "لوحة العرض", "flip chart", "فلِب-تشارت", "اسم", "Tech", "K10", "die Flipcharts", "Skizziere die Idee am Flipchart.", "ارسم الفكرة على اللوحة.", "Sketch the idea on the chart."],
["skizzieren", "-", "يرسم تخطيطيًا", "to sketch", "سكِتسيرِن", "فعل", "Tech", "K10", "", "Skizziere den Ablauf kurz.", "ارسم التسلسل باختصار.", "Sketch the sequence briefly."],
["Ablauf", "der", "التسلسل", "sequence", "أب-لاوف", "اسم", "Tech", "K10", "die Abläufe", "Der Ablauf steht im Plan.", "التسلسل في الخطة.", "The sequence is in the plan."],
["Zeitplan", "der", "الجدول الزمني", "timeline", "تسايت-بلان", "اسم", "Tech", "K10", "die Zeitpläne", "Der Zeitplan bleibt eng.", "الجدول ضيّق.", "The timeline stays tight."],
["Meilenstein", "der", "المعلم الرئيسي", "milestone", "مايلِن-شتاين", "اسم", "Tech", "K10", "die Meilensteine", "Jeder Meilenstein zählt.", "كل معلم مهم.", "Every milestone counts."],
["Priorität", "die", "الأولوية", "priority", "بريوريتِيت", "اسم", "Tech", "K10", "die Prioritäten", "Setze klare Prioritäten.", "ضع أولويات واضحة.", "Set clear priorities."],
["Dringlichkeit", "die", "الاستعجال", "urgency", "درِنجلِشْكايت", "اسم", "Tech", "K10", "", "Die Dringlichkeit steigt täglich.", "الاستعجال يزداد يوميًا.", "Urgency rises daily."],
["Aufwand", "der", "الجهد المبذول", "effort", "أوف-فانت", "اسم", "Tech", "K10", "", "Der Aufwand lohnt sich.", "الجهد يستحق.", "The effort pays off."],
["Nutzen", "der", "الفائدة", "benefit", "نوتسِن", "اسم", "Tech", "K10", "", "Der Nutzen überwiegt die Kosten.", "الفائدة تفوق التكلفة.", "Benefit outweighs cost."],
["Kosten-Nutzen", "das", "التكلفة مقابل الفائدة", "cost-benefit", "كوستِن-نوتسِن", "اسم", "Tech", "K10", "", "Das Verhältnis stimmt.", "النسبة مضبوطة.", "The ratio is right."],
["Verhältnis", "das", "النسبة", "ratio", "فيرهِلتْنِس", "اسم", "Tech", "K10", "die Verhältnisse", "Das Verhältnis beträgt zwei zu eins.", "النسبة اثنان لواحد.", "The ratio is two to one."],
["Schätzung", "die", "التقدير", "estimate", "شِتسونج", "اسم", "Tech", "K10", "die Schätzungen", "Die Schätzung liegt bei tausend.", "التقدير حوالي ألف.", "The estimate is about a thousand."],
["schätzen", "-", "يقدّر", "to estimate", "شِتسِن", "فعل", "Tech", "K10", "", "Schätze die Dauer realistisch.", "قدّر المدة بواقعية.", "Estimate the duration realistically."],
["Puffer", "der", "الاحتياطي", "buffer", "بوفِر", "اسم", "Tech", "K10", "die Puffer", "Plane einen Puffer ein.", "ضع احتياطيًا في الخطة.", "Plan in a buffer."],
["einplanen", "-", "يدرج في الخطة", "to schedule", "آين-بلانِن", "فعل", "Tech", "K10", "", "Plane die Pause fest ein.", "أدرج الاستراحة في الخطة.", "Schedule the break firmly."],
["Risiko", "das", "الخطر", "risk", "ريزيكو", "اسم", "Tech", "K10", "die Risiken", "Jedes Risiko braucht einen Plan.", "كل خطر يحتاج خطة.", "Every risk needs a plan."],
["riskant", "-", "محفوف بالمخاطر", "risky", "ريسكانت", "صفة", "Tech", "K10", "", "Der Plan klingt riskant.", "الخطة تبدو محفوفة بالمخاطر.", "The plan sounds risky."],
["minimieren", "-", "يقلّل", "to minimise", "مينيميرِن", "فعل", "Tech", "K10", "", "Minimiere das Risiko früh.", "قلّل الخطر مبكرًا.", "Minimise risk early."],
["maximieren", "-", "يعظّم", "to maximise", "ماكسيميرِن", "فعل", "Tech", "K10", "", "Maximiere den Nutzen des Tages.", "عظّم فائدة اليوم.", "Maximise the day's benefit."],
["optimieren", "-", "يحسّن", "to optimise", "أوبتيميرِن", "فعل", "Tech", "K10", "", "Optimiere den Ablauf ständig.", "حسّن التسلسل باستمرار.", "Optimise the sequence constantly."],
["Effizienz", "die", "الكفاءة", "efficiency", "إفيتْسيِنتس", "اسم", "Tech", "K10", "", "Effizienz spart Zeit und Geld.", "الكفاءة توفّر الوقت والمال.", "Efficiency saves time and money."],
["effizient", "-", "كفء", "efficient", "إفيتْسيِنت", "صفة", "Tech", "K10", "", "Arbeite effizient, nicht lange.", "اعمل بكفاءة لا بطول.", "Work efficiently, not long."],
["Verschwendung", "die", "الهدر", "waste", "فيرشْفِندونج", "اسم", "Nature", "K10", "", "Verschwendung schadet allen.", "الهدر يضرّ الجميع.", "Waste harms everyone."],
["Nachhaltigkeit", "die", "الاستدامة", "sustainability", "ناخ-هالتِشْكايت", "اسم", "Nature", "K10", "", "Nachhaltigkeit beginnt im Kleinen.", "الاستدامة تبدأ من الصغير.", "Sustainability starts small."],
["nachhaltig", "-", "مستدام", "sustainable", "ناخ-هالتِش", "صفة", "Nature", "K10", "", "Kaufe bewusst und nachhaltig.", "اشترِ بوعي واستدامة.", "Buy consciously and sustainably."],
["bewusst", "-", "واعٍ", "conscious", "بِفوست", "صفة", "Nature", "K10", "", "Lebe bewusst und sparsam.", "عِش بوعي واقتصاد.", "Live consciously and thriftily."],
["sparsam", "-", "مقتصد", "thrifty", "شبارزام", "صفة", "Nature", "K10", "", "Fahre sparsam und ruhig.", "قُد باقتصاد وهدوء.", "Drive thriftily and calmly."],
["Wasserverbrauch", "der", "استهلاك الماء", "water use", "فاسِّر-فيربراوخ", "اسم", "Nature", "K10", "", "Senke deinen Wasserverbrauch.", "خفّض استهلاكك للماء.", "Lower your water use."],
["einsparen", "-", "يوفّر", "to save", "آين-شبارِن", "فعل", "Nature", "K10", "", "Spare jeden Tag Energie.", "وفّر الطاقة كل يوم.", "Save energy every day."],
["Stromverbrauch", "der", "استهلاك الكهرباء", "power use", "شتروم-فيربراوخ", "اسم", "Nature", "K10", "", "Der Stromverbrauch sinkt.", "استهلاك الكهرباء ينخفض.", "Power use falls."],
["sinken", "-", "ينخفض", "to sink", "زِينكِن", "فعل", "Nature", "K10", "", "Die Kosten sinken stetig.", "التكاليف تنخفض باطراد.", "Costs sink steadily."],
["steigen", "-", "يرتفع", "to rise", "شتايجِن", "فعل", "Nature", "K10", "", "Die Preise steigen weiter.", "الأسعار تواصل الارتفاع.", "Prices keep rising."],
["CO2-Ausstoß", "der", "انبعاث الكربون", "carbon emissions", "تسي-أو-تسفاي-أوز-شتوز", "اسم", "Nature", "K10", "", "Der Ausstoß muss sinken.", "الانبعاث يجب أن ينخفض.", "Emissions must fall."],
["Ausstoß", "der", "الانبعاث", "emission", "أوز-شتوز", "اسم", "Nature", "K10", "", "Weniger Ausstoß schützt das Klima.", "انبعاث أقل يحمي المناخ.", "Less emission protects climate."],
["Feinstaub", "der", "الغبار الدقيق", "fine dust", "فاين-شتاوب", "اسم", "Nature", "K10", "", "Feinstaub belastet die Lunge.", "الغبار يثقل الرئة.", "Fine dust burdens lungs."],
["belasten", "-", "يثقل / يلوّث", "to burden", "بِلاستِن", "فعل", "Nature", "K10", "", "Lärm belastet die Nerven.", "الضجيج يثقل الأعصاب.", "Noise burdens nerves."],
["Belastung", "die", "العبء", "burden", "بِلاستونج", "اسم", "Nature", "K10", "die Belastungen", "Die Belastung wächst stetig.", "العبء يكبر باطراد.", "The burden grows steadily."],
["Lärmbelästigung", "die", "الإزعاج الضوضائي", "noise nuisance", "لِرم-بِلِستِجونج", "اسم", "Nature", "K10", "", "Nachts gilt Lärmschutz.", "ليلًا تسري حماية الضجيج.", "Noise protection applies nights."],
["Lärmschutz", "der", "حماية الضجيج", "noise protection", "لِرم-شوتس", "اسم", "Nature", "K10", "", "Neue Fenster dämmen den Lärm.", "النوافذ الجديدة تعزل الضجيج.", "New windows insulate noise."],
["dämmen", "-", "يعزل", "to insulate", "دِمِن", "فعل", "Nature", "K10", "", "Dämme das Dach vor dem Winter.", "اعزل السقف قبل الشتاء.", "Insulate the roof before winter."],
["Dämmung", "die", "العزل", "insulation", "دِمونج", "اسم", "Nature", "K10", "die Dämmungen", "Gute Dämmung spart Heizkosten.", "العزل الجيد يوفّر التدفئة.", "Good insulation saves heating."],
["Heizkosten", "die", "تكاليف التدفئة", "heating costs", "هايتس-كوستِن", "اسم", "Nature", "K10", "", "Die Heizkosten steigen jährlich.", "تكاليف التدفئة ترتفع سنويًا.", "Heating costs rise yearly."],
["Solaranlage", "die", "منظومة الطاقة الشمسية", "solar plant", "زولار-أن-لاجَه", "اسم", "Nature", "K10", "die Solaranlagen", "Die Anlage deckt das Dach.", "المنظومة تغطّي السقف.", "The plant covers the roof."],
["Wärmepumpe", "die", "المضخة الحرارية", "heat pump", "فِرمَه-بومبَه", "اسم", "Nature", "K10", "die Wärmepumpen", "Die Pumpe ersetzt die Heizung.", "المضخة تستبدل التدفئة.", "The pump replaces heating."],
["ersetzen", "-", "يستبدل", "to replace", "إيرزِتسِن", "فعل", "Nature", "K10", "", "Gas ersetzt langsam Kohle.", "الغاز يستبدل الفحم تدريجيًا.", "Gas slowly replaces coal."],
["Ersatz", "der", "البديل", "replacement", "إيرزاتس", "اسم", "Nature", "K10", "", "Ein Ersatz liegt bereit.", "بديل جاهز.", "A replacement lies ready."],
["Kohleausstieg", "der", "التخلّي عن الفحم", "coal exit", "كولَه-أوز-شتيج", "اسم", "Nature", "K10", "", "Der Ausstieg läuft bis 2030.", "التخلّي يستمر حتى 2030.", "The exit runs till 2030."],
["Atomausstieg", "der", "التخلّي النووي", "nuclear exit", "أتوم-أوز-شتيج", "اسم", "Nature", "K10", "", "Der Ausstieg prägt die Debatte.", "التخلّي يشكّل النقاش.", "The exit shapes debate."],
["prägen", "-", "يشكّل / يطبع", "to shape", "برِيجِن", "فعل", "Society", "K11", "", "Medien prägen die Meinung.", "الإعلام يشكّل الرأي.", "Media shape opinion."],
["Meinungsfreiheit", "die", "حرية الرأي", "free speech", "ماينونجز-فرايهايت", "اسم", "Society", "K11", "", "Freiheit schützt jede Meinung.", "الحرية تحمي كل رأي.", "Freedom protects every opinion."],
["Pressefreiheit", "die", "حرية الصحافة", "press freedom", "بْرِسِّه-فرايهايت", "اسم", "Society", "K11", "", "Ohne Presse keine Kontrolle.", "بدون صحافة لا رقابة.", "Without press no control."],
["Zensur", "die", "الرقابة", "censorship", "تسِنزور", "اسم", "Media", "K10", "", "Zensur verzerrt die Wahrheit.", "الرقابة تشوّه الحقيقة.", "Censorship distorts truth."],
["verzerren", "-", "يشوّه", "to distort", "فيرتسِرِن", "فعل", "Media", "K10", "", "Gerüchte verzerren die Fakten.", "الشائعات تشوّه الحقائق.", "Rumours distort facts."],
["Gerücht", "das", "الشائعة", "rumour", "جِروخت", "اسم", "Media", "K10", "die Gerüchte", "Das Gerücht verbreitet sich schnell.", "الشائعة تنتشر بسرعة.", "The rumour spreads fast."],
["verbreiten", "-", "ينشر", "to spread", "فيربرايتِن", "فعل", "Media", "K10", "", "Verbreite keine falschen Meldungen.", "لا تنشر أخبارًا كاذبة.", "Don't spread false news."],
["Faktencheck", "der", "التحقق من الحقائق", "fact check", "فاكتِن-تشِك", "اسم", "Media", "K10", "die Faktenchecks", "Ein Check klärt die Lage.", "تحقّق يوضّح الوضع.", "A check clarifies things."],
["Primärquelle", "die", "المصدر الأول", "primary source", "بريمِير-كْفِلَّه", "اسم", "Media", "K10", "die Primärquellen", "Zitiere stets die Primärquelle.", "استشهد بالمصدر الأول دائمًا.", "Always cite the primary source."],
["Beleg", "der", "الدليل", "evidence", "بِليج", "اسم", "Media", "K10", "die Belege", "Ohne Beleg bleibt es Behauptung.", "بدون دليل يبقى ادّعاءً.", "Without evidence stays claim."],
["belegen", "-", "يثبت بدليل", "to prove", "بِليجِن", "فعل", "Media", "K10", "", "Belege deine These mit Zahlen.", "أثبت أطروحتك بالأرقام.", "Prove your thesis with numbers."],
["These", "die", "الأطروحة", "thesis", "تيزَه", "اسم", "Education", "K9", "die Thesen", "Die These braucht Belege.", "الأطروحة تحتاج أدلة.", "The thesis needs evidence."],
["Antithese", "die", "النقيض", "antithesis", "أنتي-تيزَه", "اسم", "Education", "K9", "die Antithesen", "Jede These hat eine Antithese.", "لكل أطروحة نقيض.", "Every thesis has antithesis."],
["Synthese", "die", "التركيب", "synthesis", "زونتِيزَه", "اسم", "Education", "K9", "die Synthesen", "Die Synthese verbindet beide.", "التركيب يجمع الاثنين.", "Synthesis combines both."],
["Argument", "das", "الحجّة", "argument", "أرجومِنت", "اسم", "Society", "K11", "die Argumente", "Dein Argument überzeugt mich.", "حجّتك تقنعني.", "Your argument convinces me."],
["argumentieren", "-", "يحاجج", "to argue", "أرجومِنتيرِن", "فعل", "Society", "K11", "", "Argumentiere sachlich und ruhig.", "حاجج بموضوعية وهدوء.", "Argue factually and calmly."],
["Gegenargument", "das", "الحجّة المضادة", "counterargument", "جيجِن-أرجومِنت", "اسم", "Society", "K11", "die Gegenargumente", "Das Gegenargument wiegt schwer.", "المضادة ثقيلة الوزن.", "The counter weighs heavy."],
["Beweisführung", "die", "سوق الأدلّة", "reasoning", "بِفايز-فورونج", "اسم", "Society", "K11", "", "Deine Führung ist lückenhaft.", "سوقك فيه ثغرات.", "Your reasoning has gaps."],
["lückenhaft", "-", "ناقص", "incomplete", "لوكِن-هافت", "صفة", "Society", "K11", "", "Der Bericht bleibt lückenhaft.", "التقرير يبقى ناقصًا.", "The report stays incomplete."],
["Wissenslücke", "die", "فجوة معرفية", "knowledge gap", "فِسِنز-لوكَّه", "اسم", "Society", "K11", "die Wissenslücken", "Schließe jede Wissenslücke.", "سدّ كل فجوة معرفية.", "Close every knowledge gap."],
["Strohmann", "der", "حجّة القشّ", "strawman", "شترو-مان", "اسم", "Society", "K11", "die Strohmänner", "Das ist ein reiner Strohmann.", "هذه حجّة قشّ خالصة.", "That is a pure strawman."],
["Scheinargument", "das", "الحجّة الزائفة", "fallacy", "شاين-أرجومِنت", "اسم", "Society", "K11", "die Scheinargumente", "Erkenne jedes Scheinargument.", "اكشف كل حجّة زائفة.", "Spot every fallacy."],
["Sophismus", "der", "المغالطة", "sophism", "زوفِسموس", "اسم", "Society", "K11", "die Sophismen", "Der Sophismus klingt klug.", "المغالطة تبدو ذكية.", "The sophism sounds clever."],
["Doppelmoral", "die", "ازدواجية المعايير", "double standards", "دوبِل-مورال", "اسم", "Society", "K11", "", "Doppelmoral zerstört Vertrauen.", "الازدواجية تدمّر الثقة.", "Double standards destroy trust."],
["Vorwand", "der", "الذريعة", "pretext", "فور-فانت", "اسم", "Society", "K11", "die Vorwände", "Das war nur ein Vorwand.", "كانت مجرد ذريعة.", "That was just a pretext."],
["Ausrede", "die", "العذر", "excuse", "أوز-ريدَه", "اسم", "Society", "K11", "die Ausreden", "Keine Ausreden mehr, bitte.", "لا أعذار بعد، من فضلك.", "No more excuses please."],
["ausreden", "-", "يختلق عذرًا", "to excuse", "أوز-ريدِن", "فعل", "Society", "K11", "", "Rede dich nicht ständig aus.", "لا تختلق الأعذار دائمًا.", "Don't keep making excuses."],
["zugeben", "-", "يعترف", "to admit", "تسو-جيبِن", "فعل", "Society", "K11", "", "Gib den Fehler endlich zu.", "اعترف بالخطأ أخيرًا.", "Admit the mistake finally."],
["leugnen", "-", "ينكر", "to deny", "لويجنِن", "فعل", "Society", "K11", "", "Er leugnet jede Beteiligung.", "هو ينكر أي مشاركة.", "He denies any involvement."],
["Beteiligung", "die", "المشاركة", "involvement", "بِتايلِجونج", "اسم", "Society", "K11", "die Beteiligungen", "Hohe Beteiligung stärkt die Wahl.", "مشاركة عالية تقوّي الانتخاب.", "High turnout strengthens voting."],
["Wahlbeteiligung", "die", "نسبة المشاركة", "turnout", "فال-بِتايلِجونج", "اسم", "Society", "K11", "", "Die Beteiligung sinkt leider.", "المشاركة تنخفض للأسف.", "Turnout unfortunately falls."],
["Stimmenthaltung", "die", "الامتناع عن التصويت", "abstention", "شتِم-إنت-هالتونج", "اسم", "Society", "K11", "", "Enthaltung zählt nicht mit.", "الامتناع لا يُحتسب.", "Abstention doesn't count."],
["sich enthalten", "-", "يمتنع", "to abstain", "زِش إنت-هالتِن", "فعل", "Society", "K11", "", "Zwei Mitglieder enthalten sich.", "عضوان يمتنعان.", "Two members abstain."],
["Mehrheit", "die", "الأغلبية", "majority", "مِيرهايت", "اسم", "Society", "K11", "die Mehrheiten", "Die Mehrheit stimmt dafür.", "الأغلبية تصوّت مع.", "The majority votes for."],
["Minderheit", "die", "الأقلية", "minority", "مِندِرهايت", "اسم", "Society", "K11", "die Minderheiten", "Schütze jede Minderheit.", "احمِ كل أقلية.", "Protect every minority."],
["Einstimmigkeit", "die", "الإجماع", "unanimity", "آين-شتِمِشْكايت", "اسم", "Society", "K11", "", "Der Beschluss fällt einstimmig.", "القرار يصدر بالإجماع.", "The decision passes unanimously."],
["einstimmig", "-", "بالإجماع", "unanimous", "آين-شتِمِش", "صفة", "Society", "K11", "", "Alle stimmen einstimmig zu.", "الجميع يوافق بالإجماع.", "All agree unanimously."],
["Stimmenmehrheit", "die", "أغلبية الأصوات", "vote majority", "شتِمِن-مِيرهايت", "اسم", "Society", "K11", "", "Es reicht die einfache Mehrheit.", "تكفي الأغلبية البسيطة.", "Simple majority suffices."],
["Stimmzettel", "der", "ورقة الاقتراع", "ballot", "شتِم-تسِتِل", "اسم", "Society", "K11", "die Stimmzettel", "Der Zettel bleibt geheim.", "الورقة تبقى سرّية.", "The ballot stays secret."],
["Wahlurne", "die", "صندوق الاقتراع", "ballot box", "فال-أورنَه", "اسم", "Society", "K11", "die Wahlurnen", "Die Urne schließt um sechs.", "الصندوق يغلق السادسة.", "The box closes at six."],
["auszählen", "-", "يفرز الأصوات", "to count votes", "أوز-تسِيلِن", "فعل", "Society", "K11", "", "Die Helfer zählen nachts aus.", "المتطوعون يفرزون ليلًا.", "Helpers count at night."],
["Auszählung", "die", "الفرز", "count", "أوز-تسِيلونج", "اسم", "Society", "K11", "die Auszählungen", "Die Auszählung dauert Stunden.", "الفرز يستغرق ساعات.", "The count takes hours."],
["Wahlsieg", "der", "الفوز الانتخابي", "election win", "فال-زيج", "اسم", "Society", "K11", "die Wahlsiege", "Der Wahlsieg überrascht alle.", "الفوز يفاجئ الجميع.", "The win surprises all."],
["Wahlniederlage", "die", "الهزيمة الانتخابية", "election loss", "فال-نيدِر-لاجَه", "اسم", "Society", "K11", "die Wahlniederlagen", "Die Niederlage schmerzt tief.", "الهزيمة تؤلم بعمق.", "The loss hurts deeply."],
["Koalition", "die", "الائتلاف", "coalition", "كواليتْسيون", "اسم", "Society", "K11", "die Koalitionen", "Die Koalition hält vorerst.", "الائتلاف صامد مؤقتًا.", "The coalition holds for now."],
["koalieren", "-", "يتحالف", "to coalesce", "كواليِرِن", "فعل", "Society", "K11", "", "Zwei Parteien koalieren.", "حزبان يتحالفان.", "Two parties coalesce."],
["Oppositionsführer", "der", "زعيم المعارضة", "opposition leader", "أوبّوزيتْسيونز-فورِر", "اسم", "Society", "K11", "die Oppositionsführer", "Der Führer fordert Neuwahlen.", "الزعيم يطالب بانتخابات جديدة.", "The leader demands new elections."],
["Neuwahlen", "die", "انتخابات جديدة", "new elections", "نوي-فالِن", "اسم", "Society", "K11", "", "Neuwahlen kosten Millionen.", "الجديدة تكلّف الملايين.", "New elections cost millions."],
],
grammar: [
["Relativsätze im Dativ", "K11", "الوصف في حالة الجرّ: der Mann, dem ich helfe / die Frau, der ich danke. الضمير dem/der/denen.", "Der Freund, dem ich helfe, dankt mir.|الصديق الذي أساعده يشكرني.", "Die Frau, der ich schreibe, antwortet bald.|المرأة التي أكتب لها تردّ قريبًا.", "Die Leute, denen wir trauen, helfen uns.|الناس الذين نثق بهم يساعدوننا.", "أكمل: Der Mann, ___ ich helfe.", "dem|den|der", "0", "helfen + Dativ: dem Mann."],
["um...zu, ohne...zu, anstatt...zu", "K10", "الغرض والنفي والبديل: Ich lerne, um zu bestehen. / Er geht, ohne zu grüßen. / Anstatt zu warten, rufe ich an.", "Ich übe, um zu bestehen.|أتدرّب لأنجح.", "Sie geht, ohne sich zu verabschieden.|تذهب دون أن تودّع.", "Anstatt zu jammern, handle ich.|بدل التذمّر أتصرّف.", "أكمل: Ich lerne, ___ zu bestehen.", "um|ohne|anstatt", "0", "الغرض = um...zu."],
["Passiv im Präteritum", "K9", "المجهول الماضي: wurde + Partizip II. Das Haus wurde gebaut. / Die Briefe wurden geschickt.", "Das Haus wurde 1900 gebaut.|بُني البيت 1900.", "Die Tests wurden korrigiert.|صُحّحت الاختبارات.", "Er wurde zum Chef gewählt.|انتُخب مديرًا.", "اختر: Das Haus ___ gebaut.", "wurde|wird|worden", "0", "الماضي = wurde + Partizip."],
["Konjunktiv II – Ratschläge", "K11", "النصيحة بالتخيّل: Du solltest mehr üben. / An deiner Stelle würde ich fragen.", "Du solltest früher schlafen.|ينبغي أن تنام مبكرًا.", "An deiner Stelle würde ich absagen.|مكانك كنت سألغي.", "Du könntest den Arzt fragen.|يمكنك سؤال الطبيب.", "انصح: Du ___ mehr lesen.", "solltest|sollst|solltest du", "0", "النصيحة = solltest + مصدر."],
["Tekamolo – Wortstellung", "K10", "ترتيب الظروف: Temporal (متى) قبل Kausal (لماذا) قبل Modal (كيف) قبل Lokal (أين).", "Ich lerne morgens wegen der Prüfung fleißig daheim.|أذاكر صباحًا للامتحان بجدّ في البيت.", "Er arbeitet heute wegen des Projekts lange im Büro.|يعمل اليوم للمشروع طويلًا في المكتب.", "Wir treffen uns morgen trotz des Regens kurz draußen.|نلتقي غدًا رغم المطر briefly خارجًا.", "ما الترتيب الصحيح؟", "متى-لماذا-كيف-أين|أين-كيف-لماذا-متى|كيف-متى-أين-لماذا", "0", "Tekamolo: زمان-سبب-كيفية-مكان."],
["Indirekte Rede im Präsens", "K10", "النقل اليومي البسيط: Er sagt, er ist müde. / Sie meint, sie hat Zeit. (الرسمي بـ sei في B2).", "Er sagt, er kommt später.|يقول إنه سيأتي متأخرًا.", "Sie meint, sie schafft das.|تقول إنها تستطيع.", "Der Arzt sagt, ich bin gesund.|الطبيب يقول إنني سليم.", "حوّل: Ich bin da. → Er sagt, er ___ da.", "ist|sei|war", "0", "اليومي يبقي الحاضر: ist."]
],
explain: {
gx0: {level: "B1", goals: ["أستخدم وصف Dativ.", "أطابق الضمير."], what: "بعد أفعال Dativ يأتي الضمير dem/der/denen.", why: "الوصف الدقيق.", examples: [["Dem ich helfe.", "الذي أساعده.", ""]], when: ["وصف مع helfen/danken."], how: ["1- حدّد الفعل.", "2- ضمير Dativ."], daily: [["Der ich schreibe.", "التي أكتب لها.", ""]], compare: "Akk: den/die.", notes: ["denen للجمع.", "الفعل أخيرًا."], mistakes: [{w: "den ich helfe", r: "dem ich helfe", why: "Dativ."}], summary: "وصف Dativ.", review: {rule: "Relativ Dativ", words: "helfen, danken", example: "Dem ich helfe.", mistake: "den.", q: "ضمير helfen؟"}},
gx1: {level: "B1", goals: ["أعبّر عن الغرض.", "أفرّق um/ohne/anstatt."], what: "ثلاثة تراكيب zu موسّعة.", why: "التعبير الدقيق.", examples: [["Um zu bestehen.", "لأنجح.", ""]], when: ["غرض/نفي/بديل."], how: ["1- اختر البداية.", "2- zu أخيرًا."], daily: [["Ohne zu grüßen.", "دون تحية.", ""]], compare: "zu وحده أبسط.", notes: ["الفاصلة.", "الفاعل واحد."], mistakes: [{w: "Um bestehen.", r: "Um zu bestehen.", why: "zu إجبارية."}], summary: "غرض موسّع.", review: {rule: "um/ohne/anstatt", words: "lernen, üben", example: "Um zu bestehen.", mistake: "نسيان zu.", q: "اختر للغرض."}},
gx2: {level: "B1", goals: ["أبني مجهول الماضي.", "أحكي تاريخًا."], what: "wurde + Partizip II.", why: "التاريخ والتقارير.", examples: [["Wurde gebaut.", "بُني.", ""]], when: ["ماضٍ مجهول."], how: ["1- wurde.", "2- Partizip."], daily: [["Wurde gewählt.", "انتُخب.", ""]], compare: "الحاضر wird.", notes: ["wurden للجمع.", "worden للكامل."], mistakes: [{w: "wird gebaut (ماضٍ)", r: "wurde gebaut", why: "wurde للماضي."}], summary: "مجهول ماضٍ.", review: {rule: "Passiv Präteritum", words: "bauen, wählen", example: "Wurde gebaut.", mistake: "wird.", q: "ابنِ ماضي يُبنى."}},
gx3: {level: "B1", goals: ["أنصح بلطف.", "أستخدم solltest."], what: "النصيحة = solltest/würde.", why: "النصيحة اليومية.", examples: [["Du solltest üben.", "ينبغي أن تتدرّب.", ""]], when: ["النصح."], how: ["1- solltest.", "2- مصدر."], daily: [["Würde ich fragen.", "كنت سأسأل.", ""]], compare: "الأمر مباشر.", notes: ["solltest لا sollst.", "An deiner Stelle."], mistakes: [{w: "Du sollst üben (نصيحة)", r: "Du solltest üben", why: "solltest ألطف."}], summary: "نصيحة لطيفة.", review: {rule: "Ratschläge", words: "sollen, üben", example: "Du solltest üben.", mistake: "sollst.", q: "انصح بالمذاكرة."}},
gx4: {level: "B1", goals: ["أرتّب الظروف.", "أتحدث بسلاسة."], what: "زمان-سبب-كيفية-مكان.", why: "الجملة الألمانية.", examples: [["Morgens fleißig daheim.", "صباحًا بجدّ في البيت.", ""]], when: ["ظروف متعددة."], how: ["1- رتّب.", "2- تدرّب."], daily: [["Heute lange im Büro.", "اليوم طويلًا في المكتب.", ""]], compare: "العربي حرّ.", notes: ["احفظ tekamolo.", "المكان أخيرًا."], mistakes: [{w: "Daheim morgens.", r: "Morgens daheim.", why: "الزمان أولًا."}], summary: "رتّب الظروف.", review: {rule: "Tekamolo", words: "morgens, daheim", example: "Morgens daheim.", mistake: "عكس الترتيب.", q: "أين المكان؟"}},
gx5: {level: "B1", goals: ["أنقل الكلام يوميًا.", "أفرّق عن الرسمي."], what: "النقل بالحاضر.", why: "حكاية الكلام.", examples: [["Er ist müde.", "إنه متعب.", ""]], when: ["النقل اليومي."], how: ["1- انقل.", "2- أبقِ الزمن."], daily: [["Sie hat Zeit.", "لديها وقت.", ""]], compare: "الرسمي sei.", notes: ["dass اختيارية.", "الفعل أخيرًا مع dass."], mistakes: [{w: "Er sagt, er sei (يومي)", r: "Er sagt, er ist", why: "اليومي ist."}], summary: "انقل ببساطة.", review: {rule: "Indirekte Rede", words: "sagen, meinen", example: "Er ist müde.", mistake: "sei.", q: "انقل: Ich habe Zeit."}}
},
sentences: [
["Lies den Arbeitsvertrag vor dem Unterschreiben.", "اقرأ العقد قبل التوقيع.", "", "K9"],
["Die Probezeit endet nach drei Monaten.", "فترة التجربة تنتهي بعد ثلاثة أشهر.", "", "K9"],
["Reiche die Spesen bis Freitag ein.", "قدّم المصاريف قبل الجمعة.", "", "K9"],
["Ohne Genehmigung läuft hier nichts.", "بدون موافقة لا شيء هنا.", "", "K9"],
["Wer schreibt heute das Protokoll?", "من يكتب المحضر اليوم؟", "", "K9"],
["Die Miete läuft bequem per Dauerauftrag.", "الإيجار بأمر مستديم مريح.", "", "K9"],
["Überweise den Betrag bis Montag früh.", "حوّل المبلغ قبل صباح الاثنين.", "", "K9"],
["Der Kredit finanziert unser neues Haus.", "القرض يموّل بيتنا الجديد.", "", "K9"],
["Die Rate beträgt monatlich hundert Euro.", "القسط شهريًا مئة يورو.", "", "K9"],
["Das Verzeichnis erscheint jedes Semester neu.", "الدليل يصدر كل فصل جديدًا.", "", "K9"],
["Wiederhole schwierige Vokabeln jeden Abend.", "كرّر المفردات الصعبة كل مساء.", "", "K9"],
["Die Bibliothek leiht Bücher gratis aus.", "المكتبة تعير الكتب مجانًا.", "", "K9"],
["Schlage jede unbekannte Vokabel sofort nach.", "ابحث كل مفردة جديدة فورًا.", "", "K9"],
["Der Beamer zeigt die nächste Folie.", "البروجكتور يعرض الشريحة التالية.", "", "K10"],
["Setze deine Prioritäten für die Woche.", "ضع أولوياتك للأسبوع.", "", "K10"],
["Minimiere Risiken, bevor du startest.", "قلّل المخاطر قبل أن تبدأ.", "", "K10"],
["Effizienz spart täglich Zeit und Geld.", "الكفاءة توفّر يوميًا وقتًا ومالًا.", "", "K10"],
["Nachhaltigkeit beginnt bei jedem Einkauf.", "الاستدامة تبدأ مع كل تسوّق.", "", "K10"],
["Senke bewusst deinen Stromverbrauch.", "خفّض بوعي استهلاكك للكهرباء.", "", "K10"],
["Gute Dämmung halbiert die Heizkosten.", "العزل الجيد ينصّف التدفئة.", "", "K10"],
["Medien prägen unsere Meinung täglich.", "الإعلام يشكّل رأينا يوميًا.", "", "K11"],
["Verbreite keine Gerüchte ohne Beleg.", "لا تنشر شائعات بدون دليل.", "", "K10"],
["Belege deine These mit zwei Zahlen.", "أثبت أطروحتك برقمين.", "", "K9"],
["Dein Gegenargument wiegt wirklich schwer.", "حجّتك المضادة ثقيلة فعلًا.", "", "K11"],
["Gib einen Fehler lieber sofort zu.", "اعترف بالخطأ فورًا أفضل.", "", "K11"],
["Die Mehrheit stimmt für den Vorschlag.", "الأغلبية تصوّت للاقتراح.", "", "K11"],
["Der Beschluss fällt heute einstimmig.", "القرار يصدر اليوم بالإجماع.", "", "K11"],
["Die Koalition verhandelt die ganze Nacht.", "الائتلاف يتفاوض طوال الليل.", "", "K11"],
["Zähle die Stimmzettel sorgfältig aus.", "افرِز الأوراق بعناية.", "", "K11"],
["Ohne Beleg bleibt alles nur Behauptung.", "بدون دليل كل شيء مجرد ادّعاء.", "", "K10"]
],
reading: [
{kap: "K9", title: "Der erste Arbeitstag – أول يوم عمل", de: "Lena beginnt heute ihre Ausbildung im Büro.\nDer Chef zeigt ihr den Pausenraum und die Kantine.\nSie liest den Arbeitsvertrag und unterschreibt ihn.\nDie Kollegen begrüßen sie herzlich und helfen ihr.\nAm Abend erzählt sie stolz von ihrem Tag.", ar: "تبدأ لينا اليوم تدريبها في المكتب. يريها المدير غرفة الاستراحة والكانتين. تقرأ عقد العمل وتوقّعه. الزملاء يرحّبون بحرارة ويساعدونها. مساءً تحكي بفخر عن يومها.", qs: [{q: "أين تتدرب لينا؟", opts: ["المصنع", "المكتب", "المدرسة"], correct: 1}, {q: "ماذا تقرأ؟", opts: ["رسالة", "عقد العمل", "صحيفة"], correct: 1}, {q: "كيف الزملاء؟", opts: ["باردون", "مرحّبون", "غائبون"], correct: 1}]},
{kap: "K10", title: "Faktencheck – تحقّق", de: "Im Internet verbreiten sich Gerüchte schnell.\nOft fehlt die Quelle und niemand prüft die Fakten.\nLena liest die Schlagzeile, aber öffnet den Artikel.\nSie vergleicht zwei Quellen und findet die Wahrheit.\nTeile nur Meldungen mit Beleg, rät der Lehrer.", ar: "تنتشر الشائعات سريعًا على الإنترنت. غالبًا ينقص المصدر ولا أحد يتحقق. تقرأ لينا العنوان لكن تفتح المقال. تقارن مصدرين وتجد الحقيقة. شارك فقط الأخبار بدليل، ينصح المعلّم.", qs: [{q: "ما مشكلة الإنترنت؟", opts: ["البطء", "الشائعات السريعة", "الإعلانات"], correct: 1}, {q: "ماذا تفعل لينا؟", opts: ["تشارك فورًا", "تقارن مصدرين", "تتجاهل"], correct: 1}, {q: "بماذا ينصح المعلّم؟", opts: ["السرعة", "المشاركة بدليل", "الصمت"], "correct": 1}]},
{kap: "K11", title: "Die Abstimmung – التصويت", de: "Der Verein stimmt über den Ausflug ab.\nDie Mehrheit will an den See fahren.\nZwei Mitglieder enthalten sich der Stimme.\nDie Auszählung dauert nur zehn Minuten.\nEinstimmig plant man den Samstag.", ar: "النادي يصوّت على الرحلة. الأغلبية تريد الذهاب للبحيرة. عضوان يمتنعان. الفرز يستغرق عشر دقائق فقط. بالإجماع يُخطَّط للسبت.", qs: [{q: "عن ماذا التصويت؟", opts: ["الرحلة", "الرئيس", "المال"], correct: 0}, {q: "ماذا تريد الأغلبية؟", opts: ["الجبال", "البحيرة", "المدينة"], correct: 1}, {q: "كم يستغرق الفرز؟", opts: ["ساعة", "عشر دقائق", "يوم"], correct: 1}]}
],
listen: [
{level: "B1", kap: "K9", title: "Gehaltsgespräch – حديث الراتب", lines: [["Ich bitte um eine Gehaltserhöhung.", "أطلب زيادة راتب."], ["Ihre Leistung war dieses Jahr stark.", "أداؤك كان قويًا هذا العام."], ["Wir erhöhen um fünf Prozent.", "نزيد خمسة بالمئة."], ["Vielen Dank für das Vertrauen.", "شكرًا على الثقة."]], qs: [{q: "ماذا يطلب؟", opts: ["إجازة", "زيادة راتب", "ترقية"], correct: 1}, {q: "كم الزيادة؟", opts: ["3%", "5%", "10%"], correct: 1}]},
{level: "B1", kap: "K10", title: "Online-Betrug – الاحتيال", lines: [["Achtung vor falschen Mails!", "احذر الرسائل المزيّفة!"], ["Nenne nie dein Passwort.", "لا تذكر كلمتك أبدًا."], ["Prüfe immer die Quelle.", "تحقّق دائمًا من المصدر."], ["Melde den Betrug sofort.", "أبلغ عن الاحتيال فورًا."]], qs: [{q: "ماذا لا تذكر؟", opts: ["اسمك", "كلمة المرور", "عنوانك"], correct: 1}, {q: "ماذا تفعل عند الشكّ؟", opts: ["تتجاهل", "تتحقّق وتبلّغ", "تحذف كل شيء"], correct: 1}]}
],
speak: [
{level: "B1", kap: "K11", topic: "دافع عن رأيك", de: "Ich halte Nachhaltigkeit für wichtig, weil unsere Zukunft davon abhängt.", ar: "تحدث: رأيك + حجّتان + ردّ على اعتراض.", hints: ["Ich halte ... für ...", "Ein Argument ist ...", "Zwar ..., aber ..."]},
{level: "B1", kap: "K9", topic: "اشرح مشكلة عمل", de: "Die Lieferung verspätet sich, deshalb brauchen wir einen neuen Plan.", ar: "اشرح: ما المشكلة؟ ما السبب؟ ما الحلّ؟", hints: ["Das Problem ist ...", "Die Ursache ist ...", "Mein Vorschlag ist ..."]}
],
real: [
{id: "r-vorstellung", level: "B1", kap: "K9", title: "Vorstellungsgespräch – مقابلة", phrases: [["Erzählen Sie von sich.", "حدّثنا عن نفسك."], ["Was sind Ihre Stärken?", "ما نقاط قوّتك؟"], ["Haben Sie Fragen an uns?", "هل لديك أسئلة لنا؟"]], dialogue: [["Warum bewerben Sie sich bei uns?", "لماذا تتقدّم عندنا؟"], ["Ihre Projekte überzeugen mich fachlich.", "مشاريعكم تقنعني مهنيًا."], ["Wo sehen Sie sich in fünf Jahren?", "أين ترى نفسك بعد خمس سنوات؟"], ["In Verantwortung mit eigenem Team.", "في مسؤولية مع فريقي الخاص."]]},
{id: "r-bibliothek", level: "B1", kap: "K9", title: "Bibliothek – المكتبة", phrases: [["Ich möchte ein Buch ausleihen.", "أريد استعارة كتاب."], ["Wie lange ist die Leihfrist?", "كم مهلة الاستعارة؟"], ["Kann ich online verlängern?", "هل يمكنني التمديد أونلاين؟"]], dialogue: [["Guten Tag! Ich suche ein Wörterbuch.", "طاب يومك! أبحث عن قاموس."], ["Dort im Regal, vier Wochen Frist.", "هناك على الرفّ، المهلة أربعة أسابيع."], ["Kann ich zweimal verlängern?", "هل يمكنني التمديد مرتين؟"], ["Einmal geht problemlos.", "مرة واحدة بلا مشكلة."]]}
]
};