/* Deutsch Master - A2 expansion pack (ADDITIVE, lazy-loadable). Same format as curr-a2.js. */
"use strict";
window.CURR_A2B = {
level: "A2",
kapitel: [],
categories: [],
words: [
["Bäcker", "der", "الخبّاز", "baker", "بِكَّر", "اسم", "Work", "K7", "die Bäcker", "Der Bäcker backt frische Brötchen.", "الخبّاز يخبز خبزًا طازجًا.", "The baker bakes fresh rolls."],
["Friseurin", "die", "الحلّاقة", "hairdresser (f)", "فريزورِن", "اسم", "Work", "K7", "die Friseurinnen", "Die Friseurin arbeitet samstags.", "الحلّاقة تعمل السبت.", "The hairdresser works Saturdays."],
["Briefträger", "der", "ساعي البريد", "postman", "بريف-ترِيجِر", "اسم", "Work", "K7", "die Briefträger", "Der Briefträger bringt ein Paket.", "الساعي يجلب طردًا.", "The postman brings a parcel."],
["Kassierer", "der", "الكاشير", "cashier", "كاسيرِر", "اسم", "Work", "K7", "die Kassierer", "Der Kassierer gibt das Wechselgeld.", "الكاشير يعيد الباقي.", "The cashier gives the change."],
["Wechselgeld", "das", "الباقي (نقود)", "change", "فِكْسِل-جِلت", "اسم", "Shopping", "K8", "", "Das Wechselgeld stimmt genau.", "الباقي مضبوط تمامًا.", "The change is exactly right."],
["Installateur", "der", "السبّاك", "plumber", "إنستالاتور", "اسم", "Work", "K7", "die Installateure", "Der Installateur kommt morgen.", "السبّاك يأتي غدًا.", "The plumber comes tomorrow."],
["Werkzeug", "das", "الأداة", "tool", "فيرك-تسويج", "اسم", "Work", "K7", "die Werkzeuge", "Das Werkzeug liegt in der Kiste.", "الأداة في الصندوق.", "The tool is in the box."],
["Hammer", "der", "المطرقة", "hammer", "هامِر", "اسم", "Work", "K7", "die Hämmer", "Der Hammer ist zu schwer.", "المطرقة ثقيلة جدًا.", "The hammer is too heavy."],
["Nagel", "der", "المسمار", "nail", "ناجِل", "اسم", "Work", "K7", "die Nägel", "Der Nagel steckt in der Wand.", "المسمار في الحائط.", "The nail is in the wall."],
["Schraube", "die", "البرغي", "screw", "شراوبَه", "اسم", "Work", "K7", "die Schrauben", "Die Schraube sitzt fest.", "البرغي ثابت.", "The screw sits tight."],
["bohren", "-", "يثقب", "to drill", "بورِن", "فعل", "Work", "K7", "", "Er bohrt ein Loch in die Wand.", "هو يثقب حفرة في الحائط.", "He drills a hole in the wall."],
["sägen", "-", "ينشر (خشب)", "to saw", "زِيجِن", "فعل", "Work", "K7", "", "Wir sägen das Brett kürzer.", "ننشر اللوح ليقصر.", "We saw the board shorter."],
["messen", "-", "يقيس", "to measure", "مِسِن", "فعل", "Work", "K7", "", "Miss bitte die Länge des Zimmers.", "قِس طول الغرفة من فضلك.", "Measure the room's length please."],
["wiegen", "-", "يزن", "to weigh", "فيجِن", "فعل", "Shopping", "K8", "", "Die Äpfel wiegen zwei Kilo.", "التفاح يزن كيلوين.", "The apples weigh two kilos."],
["Backofen", "der", "الفرن", "oven", "باك-أوفِن", "اسم", "Housing", "K6", "die Backöfen", "Der Backofen heizt schon vor.", "الفرن يسخن مسبقًا.", "The oven is preheating."],
["Geschirrspüler", "der", "غسالة الأطباق", "dishwasher", "جِشير-شبولِر", "اسم", "Housing", "K6", "die Geschirrspüler", "Der Geschirrspüler läuft noch.", "غسالة الأطباق ما زالت تعمل.", "The dishwasher still runs."],
["Staubsauger", "der", "المكنسة الكهربائية", "vacuum cleaner", "شتاوب-زاوجِر", "اسم", "Housing", "K6", "die Staubsauger", "Der Staubsauger ist sehr laut.", "المكنسة صاخبة جدًا.", "The vacuum is very loud."],
["Bügelbrett", "das", "طاولة الكيّ", "ironing board", "بوجِل-بْرِت", "اسم", "Housing", "K6", "die Bügelbretter", "Das Bügelbrett steht im Schlafzimmer.", "طاولة الكيّ في غرفة النوم.", "The ironing board is in the bedroom."],
["Wäscheständer", "der", "منشر الغسيل", "drying rack", "فِشَه-شتِندِر", "اسم", "Housing", "K6", "die Wäscheständer", "Die Wäsche hängt auf dem Ständer.", "الغسيل معلّق على المنشر.", "The laundry hangs on the rack."],
["tropfen", "-", "يقطُر", "to drip", "تروبفِن", "فعل", "Housing", "K6", "", "Der Wasserhahn tropft die ganze Nacht.", "الصنبور يقطُر طوال الليل.", "The tap drips all night."],
["Wasserhahn", "der", "الصنبور", "tap", "فاسِّر-هان", "اسم", "Housing", "K6", "die Wasserhähne", "Dreh den Wasserhahn fest zu.", "أغلق الصنبور بإحكام.", "Turn the tap tightly off."],
["verstopft", "-", "مسدود", "clogged", "فيرشتوبفت", "صفة", "Housing", "K6", "", "Der Abfluss ist leider verstopft.", "البالوعة مسدودة للأسف.", "The drain is unfortunately clogged."],
["Abfluss", "der", "البالوعة", "drain", "أب-فلوس", "اسم", "Housing", "K6", "die Abflüsse", "Heißes Wasser hilft dem Abfluss.", "الماء الساخن يساعد البالوعة.", "Hot water helps the drain."],
["LED-Lampe", "die", "مصباح ليد", "LED lamp", "إل-إي-دي-لامبَه", "اسم", "Housing", "K6", "die LED-Lampen", "Die LED-Lampe spart Strom.", "مصباح الليد يوفّر الكهرباء.", "The LED lamp saves power."],
["Sicherung", "die", "المصهر (فيوز)", "fuse", "زِشِرونج", "اسم", "Housing", "K6", "die Sicherungen", "Die Sicherung springt oft raus.", "الفيوز يفصل كثيرًا.", "The fuse often blows."],
["Stromausfall", "der", "انقطاع الكهرباء", "power cut", "شتروم-أوزفال", "اسم", "Housing", "K6", "die Stromausfälle", "Beim Stromausfall helfen Kerzen.", "عند انقطاع الكهرباء تساعد الشموع.", "Candles help during a power cut."],
["Kerze", "die", "الشمعة", "candle", "كِرتسَه", "اسم", "Housing", "K6", "die Kerzen", "Zünde bitte eine Kerze an.", "أشعل شمعة من فضلك.", "Light a candle please."],
["Streichholz", "das", "عود الثقاب", "match", "شترايش-هولتس", "اسم", "Housing", "K6", "die Streichhölzer", "Ein Streichholz genügt.", "عود واحد يكفي.", "One match is enough."],
["Vorsicht", "die", "الحذر", "caution", "فور-زِشت", "اسم", "Daily", "K6", "", "Vorsicht, die Treppe ist nass!", "احذر، السلّم مبلّل!", "Careful, the stairs are wet!"],
["rutschig", "-", "زلِق", "slippery", "روتشِش", "صفة", "Daily", "K6", "", "Der Boden ist heute rutschig.", "الأرض زلقة اليوم.", "The floor is slippery today."],
["stolpern", "-", "يتعثّر", "to stumble", "شتولبِرن", "فعل", "Daily", "K6", "", "Pass auf, sonst stolperst du.", "انتبه وإلا ستتعثّر.", "Watch out or you'll stumble."],
["sich verletzen", "-", "يُصاب", "to get hurt", "زِش فيرلِتسِن", "فعل", "Health", "K8", "", "Er verletzt sich beim Fußball.", "يُصاب أثناء كرة القدم.", "He gets hurt playing football."],
["Verletzung", "die", "الإصابة", "injury", "فيرلِتسونج", "اسم", "Health", "K8", "die Verletzungen", "Die Verletzung heilt langsam.", "الإصابة تشفى ببطء.", "The injury heals slowly."],
["Pflaster", "das", "البلاستر", "plaster", "بفلاستِر", "اسم", "Health", "K8", "die Pflaster", "Ein Pflaster stoppt das Blut.", "بلاستر يوقف الدم.", "A plaster stops the blood."],
["bluten", "-", "ينزف", "to bleed", "بلوتِن", "فعل", "Health", "K8", "", "Der Finger blutet stark.", "الإصبع ينزف بشدة.", "The finger bleeds heavily."],
["schwindlig", "-", "دايخ", "dizzy", "شفِندلِش", "صفة", "Health", "K8", "", "Mir ist plötzlich schwindlig.", "أشعر بدوخة فجأة.", "I suddenly feel dizzy."],
["übel", "-", "غثيان", "nauseous", "أوبِل", "صفة", "Health", "K8", "", "Nach der Fahrt ist mir übel.", "بعد الرحلة أشعر بغثيان.", "After the ride I feel nauseous."],
["Durchfall", "der", "الإسهال", "diarrhoea", "دورْش-فال", "اسم", "Health", "K8", "", "Bei Durchfall hilft viel Tee.", "عند الإسهال يساعد الكثير من الشاي.", "Lots of tea helps with diarrhoea."],
["Verstopfung", "die", "الإمساك", "constipation", "فيرشتوبفونج", "اسم", "Health", "K8", "", "Ballaststoffe helfen gegen Verstopfung.", "الألياف تساعد ضد الإمساك.", "Fibre helps against constipation."],
["Allergie", "die", "الحساسية", "allergy", "ألِرجِي", "اسم", "Health", "K8", "die Allergien", "Ich habe eine Allergie gegen Nüsse.", "عندي حساسية من المكسرات.", "I have a nut allergy."],
["niesen", "-", "يعطس", "to sneeze", "نيزِن", "فعل", "Health", "K8", "", "Er niest wegen der Pollen.", "هو يعطس بسبب حبوب اللقاح.", "He sneezes because of pollen."],
["husten", "-", "يكحّ", "to cough", "هوستِن", "فعل", "Health", "K8", "", "Sie hustet die ganze Nacht.", "هي تكحّ طوال الليل.", "She coughs all night."],
["Fieber messen", "-", "يقيس الحرارة", "to take temperature", "فيبِر مِسِن", "فعل", "Health", "K8", "", "Miss bitte zweimal täglich Fieber.", "قِس الحرارة مرتين يوميًا.", "Take temperature twice daily."],
["Thermometer", "das", "الترمومتر", "thermometer", "تِرموميتِر", "اسم", "Health", "K8", "die Thermometer", "Das Thermometer zeigt achtunddreißig.", "الترمومتر يظهر ثمانية وثلاثين.", "The thermometer shows thirty-eight."],
["Hausarzt", "der", "طبيب الأسرة", "family doctor", "هاوز-أرتست", "اسم", "Health", "K8", "die Hausärzte", "Mein Hausarzt kennt mich gut.", "طبيب أسرتي يعرفني جيدًا.", "My family doctor knows me well."],
["Überweisung", "die", "التحويلة الطبية", "referral", "أوبِر-فايزونج", "اسم", "Health", "K8", "die Überweisungen", "Brauche ich eine Überweisung?", "هل أحتاج تحويلة؟", "Do I need a referral?"],
["Sprechstunde", "die", "ساعات العيادة", "consultation hours", "شبرِخ-شتوندَه", "اسم", "Health", "K8", "die Sprechstunden", "Die Sprechstunde endet um zwölf.", "العيادة تنتهي الثانية عشرة.", "Consultation ends at twelve."],
["Wartezimmer", "das", "غرفة الانتظار", "waiting room", "فارتَه-تسِمِر", "اسم", "Health", "K8", "die Wartezimmer", "Das Wartezimmer ist heute voll.", "غرفة الانتظار ممتلئة اليوم.", "The waiting room is full today."],
["Rezeption", "die", "الاستقبال", "reception", "رِتْسِبْتْسيون", "اسم", "Health", "K8", "die Rezeptionen", "Melden Sie sich an der Rezeption.", "سجّل في الاستقبال.", "Register at reception."],
["Versichertenkarte", "die", "بطاقة التأمين", "insurance card", "فيرزِشِرتِن-كارتَه", "اسم", "Health", "K8", "die Versichertenkarten", "Bringen Sie Ihre Versichertenkarte mit.", "أحضر بطاقة تأمينك.", "Bring your insurance card."],
["Beipackzettel", "der", "نشرة الدواء", "leaflet", "باي-باك-تسِتِل", "اسم", "Health", "K8", "die Beipackzettel", "Lesen Sie den Beipackzettel genau.", "اقرأ النشرة بدقة.", "Read the leaflet carefully."],
["Dosierung", "die", "الجرعة", "dosage", "دوزيرونج", "اسم", "Health", "K8", "die Dosierungen", "Die Dosierung steht auf der Packung.", "الجرعة على العلبة.", "The dosage is on the pack."],
["Großpackung", "die", "العبوة الكبيرة", "family pack", "جروز-باكونج", "اسم", "Shopping", "K8", "die Großpackungen", "Die Großpackung lohnt sich.", "العبوة الكبيرة تستحق.", "The family pack pays off."],
["Mindesthaltbarkeitsdatum", "das", "تاريخ الصلاحية", "expiry date", "مِندِست-هالت-بار-كايتز-داتوم", "اسم", "Shopping", "K8", "die Mindesthaltbarkeitsdaten", "Achte auf das Haltbarkeitsdatum.", "انتبه لتاريخ الصلاحية.", "Watch the expiry date."],
["Pfand", "das", "الرهن (زجاجات)", "deposit", "بفانت", "اسم", "Shopping", "K8", "", "Für die Flasche gibt es Pfand.", "للزجاجة رهن.", "There's deposit on the bottle."],
["Pfandflasche", "die", "زجاجة الرهن", "returnable bottle", "بفانت-فلاشَه", "اسم", "Shopping", "K8", "die Pfandflaschen", "Bring die Pfandflaschen zurück.", "أعد زجاجات الرهن.", "Bring back the bottles."],
["Leergut", "das", "الفارغ (زجاجات)", "empties", "لِير-جوت", "اسم", "Shopping", "K8", "", "Das Leergut steht neben der Tür.", "الفارغ بجانب الباب.", "The empties stand by the door."],
["Kassenbon", "der", "إيصال الكاشير", "till receipt", "كاسِن-بون", "اسم", "Shopping", "K8", "die Kassenbons", "Der Kassenbon liegt in der Tüte.", "الإيصال في الكيس.", "The receipt is in the bag."],
["Papiertüte", "die", "الكيس الورقي", "paper bag", "بابير-توتَه", "اسم", "Shopping", "K8", "die Papiertüten", "Nimm eine Papiertüte mit.", "خذ كيسًا ورقيًا معك.", "Take a paper bag along."],
["Einkaufskorb", "der", "سلّة التسوّق", "shopping basket", "آين-كاوفز-كورب", "اسم", "Shopping", "K8", "die Einkaufskörbe", "Der Korb reicht für wenig.", "السلّة تكفي للقليل.", "The basket suffices for little."],
["Merkzettel", "der", "ورقة ملاحظات", "memo", "مِرك-تسِتِل", "اسم", "Shopping", "K8", "die Merkzettel", "Schreib alles auf den Merkzettel.", "اكتب كل شيء في الورقة.", "Write everything on the memo."],
["Sonderangebot", "das", "العرض الخاص", "special offer", "زوندِر-أنجِبوت", "اسم", "Shopping", "K8", "die Sonderangebote", "Das Sonderangebot gilt nur heute.", "العرض سارٍ اليوم فقط.", "The offer is valid today only."],
["Probieren", "das", "التذوّق", "tasting", "بروبيرِن", "اسم", "Shopping", "K8", "", "Probieren ist an der Theke erlaubt.", "التذوّق مسموح عند الكاونتر.", "Tasting is allowed at the counter."],
["Theke", "die", "الكاونتر", "counter", "تيكَه", "اسم", "Shopping", "K8", "die Theken", "Fragen Sie bitte an der Theke.", "اسأل عند الكاونتر من فضلك.", "Please ask at the counter."],
["Frischfleisch", "das", "اللحم الطازج", "fresh meat", "فرِش-فلايش", "اسم", "Shopping", "K8", "", "Frischfleisch liegt in der Kühlung.", "اللحم الطازج في التبريد.", "Fresh meat is in the chiller."],
["Kühlung", "die", "التبريد", "chiller", "كولونج", "اسم", "Shopping", "K8", "", "Die Milch steht in der Kühlung.", "اللبن في التبريد.", "The milk is in the chiller."],
["Tiefkühlfach", "das", "الفريزر", "freezer", "تيف-كول-فاخ", "اسم", "Housing", "K6", "die Tiefkühlfächer", "Das Eis liegt im Tiefkühlfach.", "الآيس كريم في الفريزر.", "The ice cream is in the freezer."],
["auftauen", "-", "يذيب المجمّد", "to defrost", "أوف-تاوِن", "فعل", "Housing", "K6", "", "Taue das Hähnchen langsam auf.", "أذب الدجاجة ببطء.", "Defrost the chicken slowly."],
["einfrieren", "-", "يجمّد", "to freeze", "آين-فريرِن", "فعل", "Housing", "K6", "", "Wir frieren Beeren für den Winter ein.", "نجمّد التوت للشتاء.", "We freeze berries for winter."],
["verderben", "-", "يفسد (طعام)", "to spoil", "فيردِربِن", "فعل", "Food", "K8", "", "Milch verdirbt schnell ohne Kühlung.", "اللبن يفسد سريعًا بدون تبريد.", "Milk spoils fast without chilling."],
["riechen", "-", "يشمّ", "to smell", "ريشِن", "فعل", "Food", "K8", "", "Riech mal, das Brot duftet frisch!", "شمّ، الخبز رائحته طازجة!", "Smell, the bread smells fresh!"],
["abschmecken", "-", "يتذوّق ليضبط", "to taste and adjust", "أب-شمِكِن", "فعل", "Food", "K8", "", "Schmecke die Suppe bitte ab.", "تذوّق الشوربة واضبطها.", "Taste the soup and adjust."],
["würzen", "-", "يتّبل", "to season", "فورتسِن", "فعل", "Food", "K8", "", "Würze das Fleisch mit Pfeffer.", "تبّل اللحم بالفلفل.", "Season the meat with pepper."],
["Gewürz", "das", "البهار", "spice", "جِفورتس", "اسم", "Food", "K8", "die Gewürze", "Dieses Gewürz kommt aus Indien.", "هذا البهار من الهند.", "This spice comes from India."],
["Chilipfeffer", "der", "الفلفل الحار", "chilli", "تشيلي-بفِفِر", "اسم", "Food", "K8", "", "Chilipfeffer brennt stark.", "الفلفل الحار يحرق بشدة.", "Chilli burns strongly."],
["Meersalz", "das", "ملح البحر", "sea salt", "مِير-زالتس", "اسم", "Food", "K8", "", "Meersalz schmeckt milder.", "ملح البحر أخفّ طعمًا.", "Sea salt tastes milder."],
["Balsamico", "der", "الخلّ البلسمي", "balsamic", "بالزاميكو", "اسم", "Food", "K8", "", "Balsamico verfeinert den Salat.", "البلسمي يُحسّن السلطة.", "Balsamic refines the salad."],
["Rapsöl", "das", "زيت الكانولا", "rapeseed oil", "رابس-أول", "اسم", "Food", "K8", "", "Rapsöl eignet sich zum Braten.", "زيت الكانولا مناسب للقلي.", "Rapeseed oil suits frying."],
["Mehl", "das", "الدقيق", "flour", "ميل", "اسم", "Food", "K8", "", "Für den Teig brauchst du Mehl.", "للعجين تحتاج دقيقًا.", "You need flour for dough."],
["Teig", "der", "العجين", "dough", "تايج", "اسم", "Food", "K8", "die Teige", "Der Teig muss eine Stunde ruhen.", "العجين يجب أن يرتاح ساعة.", "The dough must rest an hour."],
["kneten", "-", "يعجن", "to knead", "كْنِيتِن", "فعل", "Food", "K8", "", "Knete den Teig kräftig durch.", "اعجن العجين بقوة.", "Knead the dough firmly."],
["entkernen", "-", "ينزع النوى", "to pit", "إنت-كِرنِن", "فعل", "Food", "K8", "", "Entkerne die Äpfel vorher.", "انزع نوى التفاح مسبقًا.", "Pit the apples beforehand."],
["raspeln", "-", "يبشر", "to grate", "راسبِلن", "فعل", "Food", "K8", "", "Rasple den Käse frisch darüber.", "ابشر الجبن طازجًا فوقه.", "Grate fresh cheese over it."],
["umrühren", "-", "يقلّب", "to stir", "أوم-رورِن", "فعل", "Food", "K8", "", "Rühre die Suppe ständig um.", "قلّب الشوربة باستمرار.", "Stir the soup constantly."],
["anbraten", "-", "يحمّر (تشويح)", "to brown", "أن-براتِن", "فعل", "Food", "K8", "", "Brate die Zwiebeln glasig an.", "حمّر البصل حتى الشفافية.", "Brown the onions translucently."],
["köcheln", "-", "يغلي ببطء", "to simmer", "كُخِلن", "فعل", "Food", "K8", "", "Lass die Soße leise köcheln.", "دع الصلصة تغلي بهدوء.", "Let the sauce simmer gently."],
["abdampfen", "-", "يتبخّر", "to steam off", "أب-دامبفِن", "فعل", "Food", "K8", "", "Lass die Kartoffeln kurz abdampfen.", "دع البطاطس تتبخّر قليلًا.", "Let potatoes steam off briefly."],
["servieren", "-", "يقدّم (طعام)", "to serve", "زِرفيرِن", "فعل", "Food", "K8", "", "Wir servieren das Essen um acht.", "نقدّم الطعام في الثامنة.", "We serve food at eight."],
["abräumen", "-", "يرفع الأطباق", "to clear table", "أب-رويمِن", "فعل", "Food", "K8", "", "Räum bitte den Tisch ab.", "ارفع الأطباق من فضلك.", "Clear the table please."],
["abwaschen", "-", "يغسل الأطباق", "to wash up", "أب-فاشِن", "فعل", "Housing", "K6", "", "Wer wäscht heute ab?", "من يغسل الأطباق اليوم؟", "Who washes up today?"],
["abtrocknen", "-", "يجفّف الأطباق", "to dry up", "أب-تروكنِن", "فعل", "Housing", "K6", "", "Trockne die Gläser vorsichtig ab.", "جفّف الأكواب بحذر.", "Dry the glasses carefully."],
["Spülbecken", "das", "حوض الغسيل", "sink", "شبول-بِكِن", "اسم", "Housing", "K6", "die Spülbecken", "Das Spülbecken ist voll.", "الحوض ممتلئ.", "The sink is full."],
["Geschirrtuch", "das", "فوطة الأطباق", "tea towel", "جِشير-توخ", "اسم", "Housing", "K6", "die Geschirrtücher", "Das Geschirrtuch hängt am Haken.", "الفوطة معلّقة على الخطّاف.", "The towel hangs on the hook."],
["Haken", "der", "الخطّاف", "hook", "هاكِن", "اسم", "Housing", "K6", "die Haken", "Häng die Jacke an den Haken.", "علّق السترة على الخطّاف.", "Hang the jacket on the hook."],
["Kleiderbügel", "der", "الشمّاعة", "hanger", "كلايدِر-بوجِل", "اسم", "Housing", "K6", "die Kleiderbügel", "Nimm einen Bügel aus dem Schrank.", "خذ شمّاعة من الدولاب.", "Take a hanger from the closet."],
["Schublade", "die", "الدرج", "drawer", "شوب-لادَه", "اسم", "Housing", "K6", "die Schubladen", "Die Socken liegen in der Schublade.", "الجوارب في الدرج.", "The socks are in the drawer."],
["Regal", "das", "الرفّ", "shelf", "رِجال", "اسم", "Housing", "K6", "die Regale", "Die Bücher stehen im Regal.", "الكتب على الرفّ.", "The books are on the shelf."],
["Vorhang", "der", "الستارة", "curtain", "فور-هانج", "اسم", "Housing", "K6", "die Vorhänge", "Zieh abends die Vorhänge zu.", "أسدل الستائر مساءً.", "Draw the curtains evenings."],
["Jalousie", "die", "الشيش (ستارة)", "blind", "يالوزي", "اسم", "Housing", "K6", "die Jalousien", "Die Jalousie klemmt schon wieder.", "الشيش عالق مجددًا.", "The blind jams again."],
["Rollladen", "der", "الشيش الخارجي", "shutter", "رول-لادِن", "اسم", "Housing", "K6", "die Rollläden", "Lass nachts den Rollladen runter.", "أنزل الشيش ليلًا.", "Lower the shutter at night."],
["Fußmatte", "die", "دوّاسة الباب", "doormat", "فوز-ماتَّه", "اسم", "Housing", "K6", "die Fußmatten", "Wisch die Schuhe an der Matte ab.", "امسح حذاءك في الدوّاسة.", "Wipe shoes on the mat."],
["Schuhschrank", "der", "جزّامة", "shoe cabinet", "شو-شرانك", "اسم", "Housing", "K6", "die Schuhschränke", "Die Schuhe gehören in den Schrank.", "الأحذية مكانها الجزّامة.", "Shoes belong in the cabinet."],
["Schnürsenkel", "der", "رباط الحذاء", "shoelace", "شنور-زِنكِل", "اسم", "Clothes", "K6", "die Schnürsenkel", "Dein Schnürsenkel ist offen.", "رباط حذائك مفكوك.", "Your shoelace is undone."],
["binden", "-", "يربط", "to tie", "بِندِن", "فعل", "Daily", "K6", "", "Binde deine Schuhe vor dem Rennen.", "اربط حذاءك قبل السباق.", "Tie your shoes before racing."],
["Fleck", "der", "البقعة", "stain", "فلِك", "اسم", "Clothes", "K6", "die Flecken", "Der Fleck geht nicht raus.", "البقعة لا تخرج.", "The stain won't come out."],
["Waschmittel", "das", "مسحوق الغسيل", "detergent", "فاش-مِتِّل", "اسم", "Housing", "K6", "die Waschmittel", "Nimm wenig Waschmittel für Wolle.", "خذ قليلًا من المسحوق للصوف.", "Take little detergent for wool."],
["Weichspüler", "der", "منعّم الغسيل", "softener", "فايش-شبولِر", "اسم", "Housing", "K6", "die Weichspüler", "Weichspüler macht Handtücher weich.", "المنعّم يجعل المناشف ناعمة.", "Softener makes towels soft."],
["Bügelfalte", "die", "ثنية الكيّ", "crease", "بوجِل-فالتَه", "اسم", "Housing", "K6", "die Bügelfalten", "Die Falte sitzt genau richtig.", "الثنية مضبوطة تمامًا.", "The crease sits just right."],
["Knopf", "der", "الزرّ", "button", "كْنوبف", "اسم", "Clothes", "K6", "die Knöpfe", "Der Knopf fehlt am Mantel.", "الزرّ ناقص من المعطف.", "The coat misses a button."],
["annähen", "-", "يخيط زرًا", "to sew on", "أن-نِيهِن", "فعل", "Clothes", "K6", "", "Näh den Knopf fest an.", "خِط الزرّ بإحكام.", "Sew the button on firmly."],
["Reißverschluss", "der", "السوستة", "zip", "رايس-فيرشلوس", "اسم", "Clothes", "K6", "die Reißverschlüsse", "Der Reißverschluss klemmt wieder.", "السوستة عالقة مجددًا.", "The zip jams again."],
["Kragen", "der", "الياقة", "collar", "كراجِن", "اسم", "Clothes", "K6", "die Kragen", "Der Kragen drückt am Hals.", "الياقة تضغط على الرقبة.", "The collar presses the neck."],
["Ärmel", "der", "الكمّ", "sleeve", "إِرمِل", "اسم", "Clothes", "K6", "die Ärmel", "Kremple die Ärmel hoch.", "شمّر الأكمام.", "Roll up the sleeves."],
["hochkrämpeln", "-", "يشمّر", "to roll up", "هوخ-كرِمبِلن", "فعل", "Clothes", "K6", "", "Krämple die Ärmel vor der Arbeit hoch.", "شمّر الأكمام قبل العمل.", "Roll sleeves up before work."],
["Taschenlampe", "die", "الكشّاف", "torch", "تاشِن-لامبَه", "اسم", "Housing", "K6", "die Taschenlampen", "Die Taschenlampe liegt in der Schublade.", "الكشّاف في الدرج.", "The torch is in the drawer."],
["Batterie", "die", "البطارية الصغيرة", "battery", "باتِري", "اسم", "Housing", "K6", "die Batterien", "Die Batterie ist leer.", "البطارية فارغة.", "The battery is empty."],
["Kerzenlicht", "das", "ضوء الشموع", "candlelight", "كِرتسِن-لِشت", "اسم", "Housing", "K6", "", "Beim Kerzenlicht essen wir gemütlich.", "على ضوء الشموع نأكل بارتياح.", "We dine cosily by candlelight."],
["wohnlich", "-", "مريح للسكن", "homely", "فونلِش", "صفة", "Housing", "K6", "", "Die Wohnung wirkt hell und wohnlich.", "الشقة تبدو مشرقة ومريحة.", "The flat looks bright and homely."],
["langweilig", "-", "مملّ", "boring", "لانج-فايلِش", "صفة", "Adjectives", "K6", "", "Der Film war leider langweilig.", "الفيلم كان مملًا للأسف.", "The film was unfortunately boring."],
["spannend", "-", "مشوّق", "exciting", "شبانِنت", "صفة", "Adjectives", "K6", "", "Das Buch bleibt bis zum Ende spannend.", "الكتاب مشوّق حتى النهاية.", "The book stays exciting till the end."],
["albern", "-", "عبثي", "silly", "ألبِرن", "صفة", "Adjectives", "K6", "", "Die Kinder kichern albern.", "الأطفال يضحكون بعبث.", "The children giggle sillily."],
["traurig", "-", "حزين", "sad", "تراورِش", "صفة", "Adjectives", "K6", "", "Die Nachricht macht mich traurig.", "الخبر يحزنني.", "The news makes me sad."],
["ärgerlich", "-", "مغضِب", "annoying", "إِرجرلِش", "صفة", "Adjectives", "K6", "", "Der Stau ist wirklich ärgerlich.", "الزحام مغضِب فعلًا.", "The jam is really annoying."],
["peinlich", "-", "محرج", "embarrassing", "باينلِش", "صفة", "Adjectives", "K6", "", "Das war mir sehr peinlich.", "كان ذلك محرجًا جدًا لي.", "That was very embarrassing for me."],
["mutig", "-", "شجاع", "brave", "موتِش", "صفة", "Adjectives", "K6", "", "Der Junge antwortet mutig.", "الولد يجيب بشجاعة.", "The boy answers bravely."],
["schüchtern", "-", "خجول", "shy", "شوختِرن", "صفة", "Adjectives", "K6", "", "Das Mädchen lächelt schüchtern.", "البنت تبتسم بخجل.", "The girl smiles shyly."],
["geduldig", "-", "صبور", "patient", "جِدولدِش", "صفة", "Adjectives", "K6", "", "Bleib geduldig mit den Kindern.", "كن صبورًا مع الأطفال.", "Stay patient with the children."],
["ungeduldig", "-", "غير صبور", "impatient", "أون-جِدولدِش", "صفة", "Adjectives", "K6", "", "Warte nicht ungeduldig an der Kasse.", "لا تنتظر بنفاد صبر عند الكاشير.", "Don't wait impatiently at the till."],
["ehrlich", "-", "صادق", "honest", "إِرلِش", "صفة", "Adjectives", "K6", "", "Sei ehrlich zu deinen Freunden.", "كن صادقًا مع أصدقائك.", "Be honest with your friends."],
["frech", "-", "وقح / شقي", "cheeky", "فرِش", "صفة", "Adjectives", "K6", "", "Der freche Junge lacht laut.", "الولد الشقي يضحك بصوت عالٍ.", "The cheeky boy laughs loudly."],
["faul", "-", "كسول", "lazy", "فاول", "صفة", "Adjectives", "K6", "", "Heute bin ich schrecklich faul.", "اليوم أنا كسول جدًا.", "Today I am terribly lazy."],
["fleißig", "-", "مجتهد", "diligent", "فلايسِش", "صفة", "Adjectives", "K6", "", "Die fleißige Schülerin lernt täglich.", "التلميذة المجتهدة تذاكر يوميًا.", "The diligent pupil studies daily."],
["gewissenhaft", "-", "متقن", "conscientious", "جِفِسِن-هافت", "صفة", "Daily", "K7", "", "Sie arbeitet schnell und gewissenhaft.", "هي تعمل بسرعة وإتقان.", "She works fast and conscientiously."],
["hilfsbereit", "-", "متعاون", "helpful", "هِلفز-بِرايت", "صفة", "Daily", "K7", "", "Die Nachbarn sind sehr hilfsbereit.", "الجيران متعاونون جدًا.", "The neighbours are very helpful."],
["Verlass", "der", "الاعتماد", "reliance", "فيرلاس", "اسم", "Daily", "K7", "", "Auf dich ist wirklich Verlass.", "عليك الاعتماد فعلًا.", "You are truly reliable."],
["Versprechen", "das", "الوعد", "promise", "فيرشبرِخِن", "اسم", "Daily", "K7", "die Versprechen", "Halte bitte dein Versprechen.", "احفظ وعدك من فضلك.", "Keep your promise please."],
["beschwichtigen", "-", "يهدّئ", "to calm down", "بِشفِشتِجِن", "فعل", "Daily", "K7", "", "Er beschwichtigt die Kunden.", "هو يهدّئ العملاء.", "He calms the customers down."],
["enttäuschen", "-", "يخيّب", "to disappoint", "إنت-تويشِن", "فعل", "Daily", "K7", "", "Enttäusche deine Eltern nicht.", "لا تخيّب والديك.", "Don't disappoint your parents."],
["überraschen", "-", "يفاجئ", "to surprise", "أوبِر-راشِن", "فعل", "Daily", "K7", "", "Wir überraschen Oma zum Geburtstag.", "نفاجئ جدتي في عيد ميلادها.", "We surprise granny for her birthday."],
["Überraschung", "die", "المفاجأة", "surprise", "أوبِر-راشونج", "اسم", "Daily", "K7", "die Überraschungen", "Die Überraschung gelingt perfekt.", "المفاجأة تنجح تمامًا.", "The surprise works perfectly."],
["sich freuen", "-", "يفرح", "to rejoice", "زِش فرويِن", "فعل", "Daily", "K7", "", "Wir freuen uns auf das Fest.", "نفرح بالعيد.", "We rejoice at the festival."],
["sich ärgern", "-", "يغضب", "to get angry", "زِش إِرجرن", "فعل", "Daily", "K7", "", "Ärgere dich nicht über Kleinigkeiten.", "لا تغضب من التوافه.", "Don't get angry over trifles."],
["sich sorgen", "-", "يقلق", "to worry", "زِش زورجِن", "فعل", "Daily", "K7", "", "Die Mutter sorgt sich um das Kind.", "الأم تقلق على الطفل.", "The mother worries about the child."],
["Sorge", "die", "القلق", "worry", "زورجَه", "اسم", "Daily", "K7", "die Sorgen", "Mach dir keine Sorgen.", "لا تقلق.", "Don't worry."],
["sich schämen", "-", "يخجل", "to feel ashamed", "زِش شِيمِن", "فعل", "Daily", "K7", "", "Er schämt sich für den Fehler.", "يخجل من الخطأ.", "He feels ashamed of the mistake."],
["sich beeilen", "-", "يسرع", "to hurry", "زِش بِآيلِن", "فعل", "Daily", "K7", "", "Beeil dich, der Bus wartet nicht.", "أسرع، الأتوبيس لا ينتظر.", "Hurry, the bus won't wait."],
["sich ausruhen", "-", "يستريح", "to rest", "زِش أوز-روهِن", "فعل", "Daily", "K7", "", "Nach der Arbeit ruhe ich mich aus.", "بعد العمل أستريح.", "After work I rest."],
["sich erholen", "-", "يستعيد نشاطه", "to recover", "زِش إيرهولِن", "فعل", "Health", "K8", "", "Im Urlaub erhole ich mich gut.", "في الإجازة أستعيد نشاطي.", "On holiday I recover well."],
["sich erkundigen", "-", "يستفسر", "to enquire", "زِش إيركوندِجِن", "فعل", "Daily", "K7", "", "Erkundige dich an der Rezeption.", "استفسر في الاستقبال.", "Enquire at reception."],
["sich verabschieden", "-", "يودّع", "to say goodbye", "زِش فيرأب-شيدِن", "فعل", "Daily", "K7", "", "Wir verabschieden uns herzlich.", "نودّع بحرارة.", "We say a warm goodbye."],
["Begrüßung", "die", "التحية", "greeting", "بِجروسونج", "اسم", "Daily", "K7", "die Begrüßungen", "Die Begrüßung war sehr herzlich.", "التحية كانت حارّة جدًا.", "The greeting was very warm."],
["Verabschiedung", "die", "التوديع", "farewell", "فيرأب-شيدونج", "اسم", "Daily", "K7", "die Verabschiedungen", "Die Verabschiedung dauert lange.", "التوديع يطول.", "The farewell takes long."],
["Tischkarte", "die", "بطاقة الجلوس", "place card", "تِش-كارتَه", "اسم", "Daily", "K7", "die Tischkarten", "Deine Tischkarte liegt bereit.", "بطاقتك جاهزة.", "Your place card lies ready."],
["einladen", "-", "يدعو", "to invite", "آين-لادِن", "فعل", "Daily", "K7", "", "Wir laden die Nachbarn ein.", "ندعو الجيران.", "We invite the neighbours."],
["Zusage", "die", "القبول", "acceptance", "تسو-زاجَه", "اسم", "Daily", "K7", "die Zusagen", "Vielen Dank für Ihre Zusage.", "شكرًا جزيلًا لقبولك.", "Many thanks for your acceptance."],
["zusagen", "-", "يقبل الدعوة", "to accept", "تسو-زاجِن", "فعل", "Daily", "K7", "", "Sag bitte bis Freitag zu.", "اقبل حتى الجمعة من فضلك.", "Please accept by Friday."],
["mitbringen", "-", "يحضر معه", "to bring along", "مِت-برِنجِن", "فعل", "Daily", "K7", "", "Bring bitte einen Salat mit.", "أحضر سلطة معك من فضلك.", "Bring a salad along please."],
["mitnehmen", "-", "يأخذ معه", "to take along", "مِت-نيمِن", "فعل", "Travel", "K8", "", "Nimm die Kamera unbedingt mit.", "خذ الكاميرا معك حتمًا.", "Do take the camera along."],
["vergessen", "-", "ينسى", "to forget", "فيرجِسِن", "فعل", "Daily", "K7", "", "Vergiss die Tickets nicht.", "لا تنسَ التذاكر.", "Don't forget the tickets."],
["erinnern", "-", "يتذكّر", "to remember", "إيرِنِرن", "فعل", "Daily", "K7", "", "Ich erinnere mich an den Tag.", "أتذكّر ذلك اليوم.", "I remember that day."],
["sich erinnern", "-", "يتذكّر", "to recall", "زِش إيرِنِرن", "فعل", "Daily", "K7", "", "Erinnerst du dich an mich?", "هل تتذكّرني؟", "Do you remember me?"],
["nachdenken", "-", "يفكّر مليًا", "to reflect", "ناخ-دِنكِن", "فعل", "Daily", "K7", "", "Denk bitte in Ruhe nach.", "فكّر بهدوء من فضلك.", "Reflect calmly please."],
["durchdenken", "-", "يفكّر بعمق", "to think through", "دورْش-دِنكِن", "فعل", "Daily", "K7", "", "Denke den Plan gut durch.", "فكّر في الخطة بعمق.", "Think the plan through well."],
["entscheiden", "-", "يقرّر", "to decide", "إنت-شايدِن", "فعل", "Daily", "K7", "", "Wir entscheiden uns für den Zug.", "نقرّر السفر بالقطار.", "We decide for the train."],
["sich entscheiden", "-", "يختار", "to opt", "زِش إنت-شايدِن", "فعل", "Daily", "K7", "", "Sie entscheidet sich für Berlin.", "هي تختار برلين.", "She opts for Berlin."],
["bereuen", "-", "يندم", "to regret", "بيرويِن", "فعل", "Daily", "K7", "", "Er bereut die späte Absage.", "هو نادم على الإلغاء المتأخر.", "He regrets the late cancellation."],
["verzeihen", "-", "يسامح", "to forgive", "فيرتسايِن", "فعل", "Daily", "K7", "", "Verzeih mir die Verspätung.", "سامحني على التأخير.", "Forgive me the delay."],
["sich entschuldigen", "-", "يعتذر", "to apologise", "زِش إنت-شولدِجِن", "فعل", "Daily", "K7", "", "Entschuldige dich beim Lehrer.", "اعتذر للمعلّم.", "Apologise to the teacher."],
["Entschuldigungsschreiben", "das", "خطاب اعتذار", "apology letter", "إنت-شولدِجونجز-شرايبِن", "اسم", "Daily", "K7", "die Entschuldigungsschreiben", "Das Schreiben liegt der Mappe bei.", "الخطاب مرفق بالملف.", "The letter is attached to the file."],
["danken", "-", "يشكر", "to thank", "دانكِن", "فعل", "Daily", "K7", "", "Ich danke dir für die Hilfe.", "أشكرك على المساعدة.", "I thank you for the help."],
["Dankbarkeit", "die", "الامتنان", "gratitude", "دانك-بار-كايت", "اسم", "Daily", "K7", "", "Zeige deine Dankbarkeit.", "أظهر امتنانك.", "Show your gratitude."],
["dankbar", "-", "ممتنّ", "grateful", "دانك-بار", "صفة", "Adjectives", "K6", "", "Ich bin dir sehr dankbar.", "أنا ممتنّ لك جدًا.", "I am very grateful to you."],
["bitten", "-", "يطلب / يرجو", "to ask", "بِتِّن", "فعل", "Daily", "K7", "", "Darf ich dich um Hilfe bitten?", "هل يمكنني طلب مساعدتك؟", "May I ask you for help?"],
["Bitte", "die", "الرجاء", "request", "بِتَّه", "اسم", "Daily", "K7", "die Bitten", "Eine Bitte habe ich noch.", "عندي رجاء أخير.", "I have one more request."],
["erlauben", "-", "يسمح", "to allow", "إيرلاوبِن", "فعل", "Daily", "K7", "", "Rauchen ist hier nicht erlaubt.", "التدخين غير مسموح هنا.", "Smoking is not allowed here."],
["verbieten", "-", "يمنع", "to forbid", "فيربيتِن", "فعل", "Daily", "K7", "", "Der Arzt verbietet das Rauchen.", "الطبيب يمنع التدخين.", "The doctor forbids smoking."],
["Verbot", "das", "المنع", "ban", "فيربوت", "اسم", "Daily", "K7", "die Verbote", "Das Verbot gilt ab sofort.", "المنع سارٍ فورًا.", "The ban applies immediately."],
["Erlaubnis", "die", "الإذن", "permission", "إيرلاوبنِس", "اسم", "Daily", "K7", "die Erlaubnisse", "Ohne Erlaubnis geht es nicht.", "بدون إذن لا يمكن.", "Without permission it's impossible."],
["warnen", "-", "يحذّر", "to warn", "فارنِن", "فعل", "Daily", "K7", "", "Ich warne dich vor dem Hund.", "أحذّرك من الكلب.", "I warn you about the dog."],
["Warnung", "die", "التحذير", "warning", "فارنونج", "اسم", "Daily", "K7", "die Warnungen", "Nimm die Warnung bitte ernst.", "خذ التحذير بجدية.", "Take the warning seriously."],
["drohen", "-", "يهدّد", "to threaten", "دروهِن", "فعل", "Daily", "K7", "", "Dunkle Wolken drohen mit Regen.", "الغيوم تهدّد بالمطر.", "Dark clouds threaten rain."],
["versprechen", "-", "يعِد", "to promise", "فيرشبرِخِن", "فعل", "Daily", "K7", "", "Das Wetter verspricht Besserung.", "الطقس يعد بتحسّن.", "The weather promises improvement."],
["lügen", "-", "يكذب", "to lie", "لوجِن", "فعل", "Daily", "K7", "", "Lüg mich bitte nicht an.", "لا تكذب عليّ من فضلك.", "Please don't lie to me."],
["Lüge", "die", "الكذبة", "lie", "لوجَه", "اسم", "Daily", "K7", "die Lügen", "Das war eine dicke Lüge.", "كانت كذبة كبيرة.", "That was a big lie."],
["Wahrheit", "die", "الحقيقة", "truth", "فارهايت", "اسم", "Daily", "K7", "", "Sag mir bitte die Wahrheit.", "قل لي الحقيقة من فضلك.", "Tell me the truth please."],
["wahr", "-", "حقيقي", "true", "فار", "صفة", "Adjectives", "K6", "", "Ist die Geschichte wirklich wahr?", "هل القصة حقيقية فعلًا؟", "Is the story really true?"],
["fehlerhaft", "-", "خاطئ", "faulty", "فِيلِر-هافت", "صفة", "Adjectives", "K6", "", "Die Angabe bleibt fehlerhaft.", "البيان يبقى خاطئًا.", "The entry stays faulty."],
["zutreffend", "-", "منطبق", "accurate", "تسو-ترِفِنت", "صفة", "Adjectives", "K6", "", "Die Aussage ist zutreffend.", "العبارة منطبقة.", "The statement is accurate."],
["bedeutsam", "-", "ذو شأن", "momentous", "بِدويْت-زام", "صفة", "Adjectives", "K6", "", "Der Tag bleibt bedeutsam.", "اليوم يبقى ذا شأن.", "The day stays momentous."],
["unwichtig", "-", "غير مهمّ", "unimportant", "أون-فِشتِش", "صفة", "Adjectives", "K6", "", "Das Detail ist völlig unwichtig.", "التفصيل غير مهمّ تمامًا.", "The detail is quite unimportant."],
["dringend", "-", "عاجل", "urgent", "درِنجِنت", "صفة", "Adjectives", "K7", "", "Der Brief ist dringend und eilig.", "الخطاب عاجل ومستعجل.", "The letter is urgent."],
["hektisch", "-", "محموم", "hectic", "هِكتِش", "صفة", "Adjectives", "K7", "", "Der Morgen vor der Reise war hektisch.", "صباح السفر كان محمومًا.", "The morning before the trip was hectic."],
["frühzeitig", "-", "مبكرًا", "early", "فرو-تسايتِش", "صفة", "Daily", "K7", "", "Komm bitte frühzeitig zum Termin.", "تعالَ مبكرًا للموعد من فضلك.", "Come early to the appointment please."],
],
grammar: [
["Dativ-Verben – helfen, danken, gefallen", "K7", "أفعال تأخذ Dativ دائمًا: helfen, danken, gefallen, gehören, antworten. Ich helfe dem Mann (لا den).", "Ich helfe dem Nachbarn.|أساعد الجار.", "Das Geschenk gefällt meiner Mutter.|الهدية تعجب أمي.", "Das Buch gehört meinem Bruder.|الكتاب لأخي.", "أكمل: Ich helfe ___ Mann.", "dem|den|der", "0", "helfen + Dativ: dem Mann."],
["Präpositionen mit Dativ", "K7", "حروف تأخذ Dativ دائمًا: aus, bei, mit, nach, seit, von, zu. Ich komme aus Ägypten. / Ich fahre mit dem Bus.", "Ich trinke Tee mit Milch.|أشرب الشاي باللبن.", "Nach der Arbeit ruhe ich mich aus.|بعد العمل أستريح.", "Er kommt aus der Türkei.|هو من تركيا.", "أكمل: Ich fahre ___ dem Bus.", "mit|für|ohne", "0", "mit تأخذ Dativ دائمًا."],
["Präpositionen mit Akkusativ", "K7", "حروف تأخذ Akkusativ دائمًا: durch, für, gegen, ohne, um. Ein Geschenk für dich.", "Das Geschenk ist für dich.|الهدية لك.", "Wir gehen ohne Jacke raus.|نخرج بدون سترة.", "Der Weg führt durch den Park.|الطريق يعبر الحديقة.", "أكمل: Das ist ___ dich.", "für|mit|bei", "0", "für تأخذ Akkusativ دائمًا."],
["Temporale Präpositionen – am, im, um", "K6", "الوقت: am Montag (يوم), im Mai (شهر), um acht Uhr (ساعة).", "Am Montag beginnt der Kurs.|الاثنين تبدأ الدورة.", "Im Mai blühen die Blumen.|في مايو تتفتح الزهور.", "Um acht Uhr essen wir.|في الثامنة نأكل.", "أكمل: ___ Mai.", "Im|Am|Um", "0", "الشهور مع im: im Mai."],
["Unregelmäßige Steigerung", "K8", "صفات شاذة: gut→besser→am besten, gern→lieber→am liebsten, viel→mehr→am meisten.", "Ich lerne lieber Deutsch.|أفضّل تعلّم الألمانية.", "Er trinkt am liebsten Tee.|هو يفضّل الشاي.", "Heute gibt es mehr Hausaufgaben.|اليوم واجبات أكثر.", "ما مقارنة viel؟", "mehr|vieler|meist", "0", "viel → mehr → am meisten."],
["Hauptsatz-Konnektoren", "K6", "روابط الجملة الرئيسية: und, aber, denn, oder, sondern. الفعل يبقى ثانيًا بعدها.", "Ich bleibe daheim, denn ich bin müde.|أبقى في البيت لأنني متعب.", "Willst du Tee oder Kaffee?|تريد شايًا أم قهوة؟", "Nicht heute, sondern morgen.|ليس اليوم بل غدًا.", "أكمل: Ich lerne, ___ ich will bestehen.", "denn|weil|dass", "0", "denn رئيسية والفعل ثانيًا."]
],
explain: {
gx0: {level: "A2", goals: ["أستخدم أفعال Dativ.", "لا أخلط الحالات."], what: "أفعال مثل helfen و danken و gefallen تأخذ Dativ.", why: "خطأ شائع جدًا عند العرب.", examples: [["Ich helfe dem Mann.", "أساعد الرجل.", ""]], when: ["مع هذه الأفعال.", "دائمًا Dativ."], how: ["1- احفظ القائمة.", "2- dem/der/den."], daily: [["Gefällt dir das?", "هل يعجبك؟", ""]], compare: "معظم الأفعال Akkusativ.", notes: ["gehören أيضًا.", "antworten أيضًا."], mistakes: [{w: "Ich helfe den Mann.", r: "Ich helfe dem Mann.", why: "helfen + Dativ."}], summary: "قائمة تُحفظ.", review: {rule: "Dativ-Verben", words: "helfen, danken", example: "Ich helfe dem Mann.", mistake: "den.", q: "ما حالة helfen؟"}},
gx1: {level: "A2", goals: ["أستخدم حروف Dativ.", "أبني جملًا صحيحة."], what: "aus, bei, mit, nach, seit, von, zu + Dativ.", why: "تظهر في كل جملة.", examples: [["Mit dem Bus.", "بالأتوبيس.", ""]], when: ["الوسيلة والزمان والمكان."], how: ["1- احفظ السبعة.", "2- طبّق Dativ."], daily: [["Ich komme aus Kairo.", "أنا من القاهرة.", ""]], compare: "مقابل حروف Akkusativ.", notes: ["mit + Dativ.", "von + Dativ."], mistakes: [{w: "mit den Bus", r: "mit dem Bus", why: "mit + Dativ."}], summary: "سبعة حروف.", review: {rule: "Dativ-Präpositionen", words: "mit, aus, von", example: "Mit dem Bus.", mistake: "den.", q: "اذكر ثلاثة."}},
gx2: {level: "A2", goals: ["أستخدم حروف Akkusativ.", "أفرّق المجموعتين."], what: "durch, für, gegen, ohne, um + Akkusativ.", why: "مقابل Dativ.", examples: [["Für dich.", "لك.", ""]], when: ["الغرض والظرف."], how: ["1- احفظ الخمسة.", "2- طبّق Akkusativ."], daily: [["Ohne Zucker, bitte.", "بدون سكر.", ""]], compare: "mit مقابل ohne.", notes: ["für + Akk.", "um + وقت = في."], mistakes: [{w: "für dir", r: "für dich", why: "für + Akk."}], summary: "خمسة حروف.", review: {rule: "Akk-Präpositionen", words: "für, ohne, um", example: "Für dich.", mistake: "dir.", q: "ما حالة für؟"}},
gx3: {level: "A2", goals: ["أقول الوقت صحيحًا.", "أفرّق am/im/um."], what: "يوم am، شهر im، ساعة um.", why: "المواعيد.", examples: [["Am Montag.", "يوم الاثنين.", ""]], when: ["تحديد وقت."], how: ["1- حدّد النوع.", "2- اختر الحرف."], daily: [["Um acht Uhr.", "في الثامنة.", ""]], compare: "am = an dem.", notes: ["im = in dem.", "الفصول im."], mistakes: [{w: "Am Mai.", r: "Im Mai.", why: "الشهر im."}], summary: "يوم/شهر/ساعة.", review: {rule: "Zeit-Präpositionen", words: "am, im, um", example: "Am Montag.", mistake: "Am Mai.", q: "اختر لمايو."}},
gx4: {level: "A2", goals: ["أقارن بالشاذ.", "أستخدم lieber و mehr."], what: "gut, gern, viel شاذة.", why: "الأكثر استخدامًا.", examples: [["Am besten.", "الأفضل.", ""]], when: ["التفضيل اليومي."], how: ["1- احفظ الثلاث.", "2- استخدمها."], daily: [["Ich trinke lieber Tee.", "أفضّل الشاي.", ""]], compare: "منتظمة + er.", notes: ["mehr لا تتغيّر.", "lieber ظرف."], mistakes: [{w: "guter", r: "besser", why: "gut شاذة."}], summary: "ثلاث شاذات.", review: {rule: "Steigerung", words: "gut, gern, viel", example: "Am besten.", mistake: "guter.", q: "قارن gern."}},
gx5: {level: "A2", goals: ["أربط بجمل رئيسية.", "أفرّق denn و weil."], what: "und, aber, denn, oder, sondern + فعل ثانٍ.", why: "الربط الأساسي.", examples: [["Denn ich bin müde.", "لأنني متعب.", ""]], when: ["ربط جملتين."], how: ["1- اختر الرابط.", "2- الفعل ثانيًا."], daily: [["Tee oder Kaffee?", "شاي أم قهوة؟", ""]], compare: "weil فرعية.", notes: ["denn = لأنَّ.", "sondern بعد النفي."], mistakes: [{w: "Denn ich müde bin.", r: "Denn ich bin müde.", why: "الفعل ثانيًا."}], summary: "الفعل ثانيًا.", review: {rule: "Konnektoren", words: "denn, aber, oder", example: "Denn ich bin müde.", mistake: "فعل أخير.", q: "اختر للسبب."}}
},
sentences: [
["Der Bäcker backt jeden Morgen frisch.", "الخبّاز يخبز طازجًا كل صباح.", "", "K7"],
["Miss bitte die Länge des Tisches.", "قِس طول الطاولة من فضلك.", "", "K7"],
["Der Geschirrspüler läuft noch eine Stunde.", "غسالة الأطباق تعمل ساعة أخرى.", "", "K6"],
["Dreh den Wasserhahn bitte fest zu.", "أغلق الصنبور بإحكام من فضلك.", "", "K6"],
["Vorsicht, der Boden ist heute rutschig.", "احذر، الأرض زلقة اليوم.", "", "K6"],
["Das Wartezimmer ist heute sehr voll.", "غرفة الانتظار ممتلئة جدًا اليوم.", "", "K8"],
["Ihre Versichertenkarte liegt schon bereit.", "بطاقة تأمينك جاهزة بالفعل.", "", "K8"],
["Eine Packung Milch kostet zwei Euro.", "علبة لبن باثنين يورو.", "", "K8"],
["Schreib den Einkaufszettel vor dem Markt.", "اكتب القائمة قبل السوق.", "", "K8"],
["Rühre die Suppe beim Kochen ständig um.", "قلّب الشوربة أثناء الطهي باستمرار.", "", "K8"],
["Wer wäscht heute das Geschirr ab?", "من يغسل الأطباق اليوم؟", "", "K6"],
["Die Jacke hängt jetzt am Haken.", "السترة معلّقة الآن على الخطّاف.", "", "K6"],
["Zieh abends immer die Vorhänge zu.", "أسدل الستائر دائمًا مساءً.", "", "K6"],
["Dein Schnürsenkel ist wieder offen.", "رباط حذائك مفكوك مجددًا.", "", "K6"],
["Nimm wenig Waschmittel für die Wolle.", "خذ قليلًا من المسحوق للصوف.", "", "K6"],
["Wir freuen uns schon auf das Fest.", "نفرح بالعيد مسبقًا.", "", "K7"],
["Beeil dich, sonst kommt der Bus nicht.", "أسرع وإلا لن يأتي الأتوبيس.", "", "K7"],
["Bring bitte einen Salat zur Feier mit.", "أحضر سلطة للحفلة من فضلك.", "", "K7"],
["Denk in Ruhe über das Angebot nach.", "فكّر بهدوء في العرض.", "", "K7"],
["Entschuldige dich bitte beim Lehrer.", "اعتذر للمعلّم من فضلك.", "", "K7"],
["Rauchen ist in der Schule nicht erlaubt.", "التدخين ممنوع في المدرسة.", "", "K7"],
["Sag mir endlich die ganze Wahrheit.", "قل لي الحقيقة كاملة أخيرًا.", "", "K7"],
["Deine Antwort war völlig richtig.", "إجابتك صحيحة تمامًا.", "", "K6"],
["Sei bitte pünktlich um acht Uhr.", "كن في الموعد الثامنة من فضلك.", "", "K7"],
["Die Überraschung für Oma gelingt gut.", "مفاجأة جدتي تنجح جيدًا.", "", "K7"],
["Lesen Sie den Beipackzettel vor der Einnahme.", "اقرأ النشرة قبل التناول.", "", "K8"],
["Das Sonderangebot endet heute Abend.", "العرض الخاص ينتهي مساء اليوم.", "", "K8"],
["Taue das Hähnchen langsam im Kühlschrank auf.", "أذب الدجاجة ببطء في الثلاجة.", "", "K6"],
["Die Falte in der Hose sitzt perfekt.", "الثنية في البنطال مضبوطة تمامًا.", "", "K6"],
["Bleib geduldig mit kleinen Kindern.", "كن صبورًا مع الصغار.", "", "K6"]
],
reading: [
{kap: "K7", title: "Der neue Handwerker – الحرفي الجديد", de: "Herr Ali ist Handwerker aus Kairo.\nEr repariert Türen, Fenster und Wasserhähne.\nSein Werkzeug liegt immer ordentlich in der Kiste.\nDie Kunden rufen oft an und danken ihm.\nAm Abend trinkt er Tee und ruht sich aus.", ar: "السيد علي حرفي من القاهرة. يصلّح الأبواب والنوافذ والصنابير. أدواته مرتّبة دائمًا في الصندوق. الزبائن يتصلون كثيرًا ويشكرونه. مساءً يشرب الشاي ويستريح.", qs: [{q: "ماذا يصلّح؟", opts: ["سيارات", "أبواب ونوافذ", "هواتف"], correct: 1}, {q: "كيف أدواته؟", opts: ["مرتّبة", "مبعثرة", "مكسورة"], correct: 0}, {q: "ماذا يفعل مساءً؟", opts: ["يعمل", "يشرب الشاي", "يسافر"], correct: 1}]},
{kap: "K8", title: "Einkaufen mit Zettel – تسوّق بالقائمة", de: "Sara schreibt vor dem Markt einen Zettel.\nSie kauft Milch, Brot, Äpfel und Käse.\nAn der Theke fragt sie nach frischem Fisch.\nDer Kassierer gibt das Wechselgeld genau.\nZu Hause räumt sie alles in den Schrank.", ar: "تكتب سارة قائمة قبل السوق. تشتري لبنًا وخبزًا وتفاحًا وجبنًا. عند الكاونتر تسأل عن سمك طازج. الكاشير يعيد الباقي مضبوطًا. في البيت ترتّب كل شيء في الدولاب.", qs: [{q: "ماذا تكتب قبل السوق؟", opts: ["رسالة", "قائمة", "وصفة"], correct: 1}, {q: "عن ماذا تسأل؟", opts: ["لحم", "سمك طازج", "خبز"], correct: 1}, {q: "أين ترتّب المشتريات؟", opts: ["الثلاجة", "الدولاب", "الشرفة"], correct: 1}]},
{kap: "K6", title: "Vorsicht, rutschig! – احذر، زلِق!", de: "Es regnet seit dem Morgen stark.\nDer Boden vor der Tür ist rutschig.\nMutter stellt die Fußmatte hin.\nVater prüft die Sicherung im Keller.\nAbends sitzen alle gemütlich bei Kerzenlicht.", ar: "تمطر بغزارة منذ الصباح. الأرض أمام الباب زلقة. تضع الأم الدوّاسة. يفحص الأب الفيوز في القبو. مساءً يجلس الجميع بارتياح على ضوء الشموع.", qs: [{q: "كيف الطقس؟", opts: ["مشمس", "ماطر بغزارة", "مثلج"], correct: 1}, {q: "ماذا تفعل الأم؟", opts: ["تطبخ", "تضع الدوّاسة", "تخرج"], correct: 1}, {q: "أين يجلسون مساءً؟", opts: ["الشرفة", "على ضوء الشموع", "الحديقة"], correct: 1}]}
],
listen: [
{level: "A2", kap: "K8", title: "Beim Arzt – عند الطبيب", lines: [["Was fehlt Ihnen?", "ما الذي يؤلمك؟"], ["Mir ist schwindlig und übel.", "أشعر بدوخة وغثيان."], ["Seit wann haben Sie das?", "منذ متى؟"], ["Seit gestern Abend.", "منذ مساء أمس."]], qs: [{q: "ما الأعراض؟", opts: ["دوخة وغثيان", "كحة", "ألم ظهر"], correct: 0}, {q: "منذ متى؟", opts: ["اليوم", "مساء أمس", "أسبوع"], correct: 1}]},
{level: "A2", kap: "K6", title: "Der Klempner – السبّاك", lines: [["Der Wasserhahn tropft ständig.", "الصنبور يقطر باستمرار."], ["Der Abfluss ist leider verstopft.", "البالوعة مسدودة للأسف."], ["Ich komme morgen um acht.", "آتي غدًا الثامنة."], ["Danke, bis morgen!", "شكرًا، إلى الغد!"]], qs: [{q: "ما المشكلة؟", opts: ["كهرباء", "صنبور وبالوعة", "تدفئة"], correct: 1}, {q: "متى يأتي؟", opts: ["اليوم", "غدًا الثامنة", "الأسبوع القادم"], correct: 1}]}
],
speak: [
{level: "A2", kap: "K8", topic: "اشرح أعراضك", de: "Mir ist schwindlig. Ich habe seit gestern Fieber.", ar: "تحدث: ما أعراضك؟ منذ متى؟", hints: ["Mir ist ...", "Seit gestern ...", "Mein ... tut weh."]},
{level: "A2", kap: "K7", topic: "اعتذر واشرح", de: "Entschuldigung! Ich habe mich verspätet, weil der Bus voll war.", ar: "اعتذر: لماذا تأخّرت؟ ماذا ستفعل؟", hints: ["Entschuldigung, ...", "Weil ...", "Nächstes Mal ..."]}
],
real: [
{id: "r-arzt2", level: "A2", kap: "K8", title: "Arzttermin – موعد طبيب", phrases: [["Ich brauche einen Termin.", "أحتاج موعدًا."], ["Haben Sie die Versichertenkarte?", "هل معك بطاقة التأمين؟"], ["Nehmen Sie im Wartezimmer Platz.", "اجلس في غرفة الانتظار."]], dialogue: [["Guten Tag! Ich brauche dringend einen Termin.", "طاب يومك! أحتاج موعدًا عاجلًا."], ["Morgen um zehn ist frei.", "غدًا العاشرة متاحة."], ["Perfekt, danke! Bringe ich etwas mit?", "ممتاز! هل أحضر شيئًا؟"], ["Nur Ihre Versichertenkarte.", "بطاقة تأمينك فقط."]]},
{id: "r-handwerker", level: "A2", kap: "K6", title: "Handwerker – الحرفي", phrases: [["Der Wasserhahn tropft.", "الصنبور يقطر."], ["Wann können Sie kommen?", "متى يمكنك المجيء؟"], ["Was kostet die Reparatur?", "كم تكلف الإصلاح؟"]], dialogue: [["Guten Tag! Der Abfluss ist verstopft.", "طاب يومك! البالوعة مسدودة."], ["Ich komme am Freitag vorbei.", "أمرّ يوم الجمعة."], ["Wie viel kostet das ungefähr?", "كم يكلّف تقريبًا؟"], ["Etwa fünfzig Euro.", "حوالي خمسين يورو."]]}
]
};