/* Grammar Lab banks (ADDITIVE data module).
   Per rule: intro (simplified recap), examples (simple -> varied, DE+AR),
   questions (10+, rule-specific, A1). Types: choice (opts+correct) | order (words=correct order).
   Engine: study.js openGLab. Extensible: add gXX:{...} for new rules. */
"use strict";
var GLAB_BANK = {
g1:{intro:"Der (مذكر) – die (مؤنث) – das (محايد). تُحفظ الأداة مع الاسم دائمًا.",
examples:[["der Tisch","الطاولة"],["die Lampe","المصباح"],["das Buch","الكتاب"],["der Mann und die Frau","الرجل والمرأة"]],
questions:[
{t:"ما أداة Tisch؟",ar:"اختر الأداة الصحيحة",opts:["der","die","das"],correct:0,why:"Tisch مذكر: der Tisch"},
{t:"ما أداة Lampe؟",ar:"اختر الأداة الصحيحة",opts:["der","die","das"],correct:1,why:"Lampe مؤنث: die Lampe"},
{t:"ما أداة Buch؟",ar:"اختر الأداة الصحيحة",opts:["der","die","das"],correct:2,why:"Buch محايد: das Buch"},
{t:"ما أداة Stuhl؟",ar:"اختر الأداة الصحيحة",opts:["die","das","der"],correct:2,why:"Stuhl مذكر: der Stuhl"},
{t:"ما أداة Tür؟",ar:"اختر الأداة الصحيحة",opts:["der","die","das"],correct:1,why:"Tür مؤنث: die Tür"},
{t:"ما أداة Kind؟",ar:"اختر الأداة الصحيحة",opts:["der","die","das"],correct:2,why:"Kind محايد: das Kind"},
{t:"ما أداة Mann؟",ar:"اختر الأداة الصحيحة",opts:["die","der","das"],correct:1,why:"Mann مذكر: der Mann"},
{t:"ما أداة Frau؟",ar:"اختر الأداة الصحيحة",opts:["der","das","die"],correct:2,why:"Frau مؤنث: die Frau"},
{t:"ما أداة Haus؟",ar:"اختر الأداة الصحيحة",opts:["der","die","das"],correct:2,why:"Haus محايد: das Haus"},
{t:"ما أداة Wasser؟",ar:"اختر الأداة الصحيحة",opts:["der","die","das"],correct:2,why:"Wasser محايد: das Wasser"}]},
g2:{intro:"الجمع يُحفظ مع الاسم، وأداة الجمع دائمًا die.",
examples:[["das Land → die Länder","البلد → البلاد"],["das Buch → die Bücher","الكتاب → الكتب"],["der Tisch → die Tische","الطاولة → الطاولات"],["die Frau → die Frauen","المرأة → النساء"]],
questions:[
{t:"ما جمع Land؟",ar:"اختر الجمع الصحيح",opts:["Länder","Lands","Landens"],correct:0,why:"Land → Länder (وأداة الجمع die)"},
{t:"ما جمع Buch؟",ar:"اختر الجمع الصحيح",opts:["Buchs","Bücher","Buchen"],correct:1,why:"Buch → Bücher"},
{t:"ما جمع Kind؟",ar:"اختر الجمع الصحيح",opts:["Kinder","Kinds","Kindes"],correct:0,why:"Kind → Kinder"},
{t:"ما جمع Tisch؟",ar:"اختر الجمع الصحيح",opts:["Tische","Tischs","Tischen"],correct:0,why:"Tisch → Tische"},
{t:"ما جمع Frau؟",ar:"اختر الجمع الصحيح",opts:["Fraus","Frauen","Fräue"],correct:1,why:"Frau → Frauen"},
{t:"ما جمع Mann؟",ar:"اختر الجمع الصحيح",opts:["Männer","Manns","Mannen"],correct:0,why:"Mann → Männer"},
{t:"ما جمع Auto؟",ar:"اختر الجمع الصحيح",opts:["Autos","Autoen","Auton"],correct:0,why:"Auto → Autos"},
{t:"ما جمع Apfel؟",ar:"اختر الجمع الصحيح",opts:["Apfels","Äpfel","Apfelen"],correct:1,why:"Apfel → Äpfel"},
{t:"ما جمع Stuhl؟",ar:"اختر الجمع الصحيح",opts:["Stuhls","Stühle","Stuhle"],correct:1,why:"Stuhl → Stühle"},
{t:"ما جمع Ei؟",ar:"اختر الجمع الصحيح",opts:["Eis","Eier","Eien"],correct:1,why:"Ei → Eier"}]},
g3:{intro:"الحرف الكبير لأول الجملة وكل الأسماء وضمير Sie الرسمي.",
examples:[["Das Buch ist neu.","الكتاب جديد."],["Ich lerne Deutsch.","أتعلم الألمانية."],["Kommen Sie, Herr Ali!","تعال حضرتك يا علي!"],["Montag ist gut.","الاثنين جيد."]],
questions:[
{t:"أي كتابة صحيحة؟",ar:"اختر الكلمة المكتوبة correctly",opts:["Buch","buch","BUCH"],correct:0,why:"الأسماء تبدأ بحرف كبير: Buch"},
{t:"أي كتابة صحيحة؟",ar:"اختر الكلمة المكتوبة correctly",opts:["tisch","Tisch","TISCH"],correct:1,why:"Tisch اسم → حرف كبير"},
{t:"أي بداية جملة صحيحة؟",ar:"اختر الصحيح",opts:["ich lerne.","Ich lerne.","ICH LERNE."],correct:1,why:"أول الجملة حرف كبير: Ich"},
{t:"كيف تخاطب مديرك رسميًا؟",ar:"اختر الصحيح",opts:["Kommen sie!","Kommen Sie!","kommen Sie!"],correct:1,why:"ضمير المخاطب الرسمي Sie كبير دائمًا"},
{t:"أي كتابة صحيحة ليوم الاثنين؟",ar:"اختر الصحيح",opts:["montag","Montag","MonTag"],correct:1,why:"أيام الأسبوع أسماء: Montag"},
{t:"أي كتابة صحيحة؟",ar:"اختر الصحيح",opts:["frau","Frau","fRAu"],correct:1,why:"Frau اسم → حرف كبير"},
{t:"أي كتابة صحيحة؟",ar:"اختر الصحيح",opts:["Wasser","wasser","WASSER"],correct:0,why:"Wasser اسم → حرف كبير"},
{t:"أي كتابة صحيحة؟",ar:"اختر الصحيح",opts:["kind","Kind","kINd"],correct:1,why:"Kind اسم → حرف كبير"},
{t:"أي كتابة صحيحة؟",ar:"اختر الصحيح",opts:["haus","Haus","HAUS"],correct:1,why:"Haus اسم → حرف كبير"},
{t:"أي كتابة صحيحة؟",ar:"اختر الصحيح",opts:["Schule","schule","SCHULE"],correct:0,why:"Schule اسم → حرف كبير"}]},
g4:{intro:"ضمائر الفاعل: ich du er/es/sie wir ihr sie Sie.",
examples:[["Ich bin Ali.","أنا علي."],["Du lernst gut.","أنت تتعلم جيدًا."],["Wir wohnen in Kairo.","نحن نسكن في القاهرة."],["Sprechen Sie Deutsch?","هل تتحدث حضرتك الألمانية؟"]],
questions:[
{t:"ما معنى wir؟",ar:"اختر المعنى",opts:["نحن","أنتم","هم"],correct:0,why:"wir = نحن"},
{t:"ما معنى ihr؟",ar:"اختر المعنى",opts:["نحن","أنتم","هم"],correct:1,why:"ihr = أنتم"},
{t:"ما معنى sie (هم)؟",ar:"اختر المعنى",opts:["هي","هم","حضرتك"],correct:1,why:"sie الصغيرة للجمع = هم"},
{t:"ما معنى Sie؟",ar:"اختر المعنى",opts:["هي","هم","حضرتك"],correct:2,why:"Sie الكبيرة = حضرتك (رسمي)"},
{t:"ما معنى er؟",ar:"اختر المعنى",opts:["هو","هي","أنا"],correct:0,why:"er = هو"},
{t:"ما معنى es؟",ar:"اختر المعنى",opts:["هو/هي للمحايد","نحن","أنت"],correct:0,why:"es للمحايد (das Kind → es)"},
{t:"ما معنى du؟",ar:"اختر المعنى",opts:["أنا","أنت","هو"],correct:1,why:"du = أنت"},
{t:"ما معنى ich؟",ar:"اختر المعنى",opts:["أنا","نحن","هم"],correct:0,why:"ich = أنا"},
{t:"أكمل: ___ bin Ali.",ar:"اختر الضمير",opts:["Ich","Du","Er"],correct:0,why:"المتكلم عن نفسه: Ich bin Ali"},
{t:"أكمل: Kommst ___ morgen?",ar:"اختر الضمير",opts:["ich","du","wir"],correct:1,why:"تخاطب صديقًا: Kommst du؟"}]},
g5:{intro:"الفعل المنتظم: احذف en ثم أضف e/st/t/en/t/en.",
examples:[["ich komme","أنا آتي"],["du kommst","أنت تأتي"],["er kommt","هو يأتي"],["wir lernen","نحن نتعلم"]],
questions:[
{t:"صرف kommen مع ich؟",ar:"اختر التصريف",opts:["ich komme","ich kommst","ich kommt"],correct:0,why:"ich + جذر + e: ich komme"},
{t:"صرف kommen مع du؟",ar:"اختر التصريف",opts:["du komme","du kommst","du kommt"],correct:1,why:"du + جذر + st: du kommst"},
{t:"صرف kommen مع er؟",ar:"اختر التصريف",opts:["er kommen","er kommst","er kommt"],correct:2,why:"er + جذر + t: er kommt"},
{t:"صرف kommen مع wir؟",ar:"اختر التصريف",opts:["wir komme","wir kommen","wir kommt"],correct:1,why:"wir تأخذ المصدر: wir kommen"},
{t:"صرف kommen مع ihr؟",ar:"اختر التصريف",opts:["ihr kommen","ihr kommt","ihr kommst"],correct:1,why:"ihr + جذر + t: ihr kommt"},
{t:"صرف lernen مع du؟",ar:"اختر التصريف",opts:["du lerne","du lernst","du lernt"],correct:1,why:"du lernen → du lernst"},
{t:"صرف machen مع er؟",ar:"اختر التصريف",opts:["er machen","er machst","er macht"],correct:2,why:"er machen → er macht"},
{t:"صرف wohnen مع ihr؟",ar:"اختر التصريف",opts:["ihr wohnen","ihr wohnt","ihr wohnst"],correct:1,why:"ihr wohnen → ihr wohnt"},
{t:"صرف lernen مع sie (هم)؟",ar:"اختر التصريف",opts:["sie lerne","sie lernen","sie lernst"],correct:1,why:"sie الجمع تأخذ المصدر: sie lernen"},
{t:"صرف machen مع ich؟",ar:"اختر التصريف",opts:["ich mache","ich machst","ich macht"],correct:0,why:"ich machen → ich mache"}]},
g6:{intro:"الأفعال الشاذة تغير جذرها: sein/haben/sprechen الأهم.",
examples:[["ich bin","أنا أكون"],["du bist","أنت تكون"],["er ist","هو يكون"],["ich habe","أنا أملك"]],
questions:[
{t:"أكمل: ich ___ (يكون)",ar:"اختر التصريف",opts:["bin","bist","ist"],correct:0,why:"sein مع ich → bin"},
{t:"أكمل: du ___ (يكون)",ar:"اختر التصريف",opts:["bin","bist","ist"],correct:1,why:"sein مع du → bist"},
{t:"أكمل: er ___ (يكون)",ar:"اختر التصريف",opts:["bin","bist","ist"],correct:2,why:"sein مع er → ist"},
{t:"أكمل: ich ___ (يملك)",ar:"اختر التصريف",opts:["habe","hast","hat"],correct:0,why:"haben مع ich → habe"},
{t:"أكمل: du ___ (يملك)",ar:"اختر التصريف",opts:["habe","hast","hat"],correct:1,why:"haben مع du → hast"},
{t:"أكمل: er ___ (يملك)",ar:"اختر التصريف",opts:["habe","hast","hat"],correct:2,why:"haben مع er → hat"},
{t:"أكمل: du ___ Deutsch (يتحدث)",ar:"اختر التصريف",opts:["spreche","sprichst","sprecht"],correct:1,why:"sprechen مع du → sprichst (تغير الجذر)"},
{t:"أكمل: er ___ gut (يتحدث)",ar:"اختر التصريف",opts:["spreche","spricht","sprechen"],correct:1,why:"sprechen مع er → spricht"},
{t:"أكمل: du ___ ein Buch (يقرأ)",ar:"اختر التصريف",opts:["lese","liest","lest"],correct:1,why:"lesen مع du → liest"},
{t:"أكمل: er ___ nach Berlin (يسافر)",ar:"اختر التصريف",opts:["fahre","fährt","fahren"],correct:1,why:"fahren مع er → fährt"}]},
g7:{intro:"رسمي: Guten Morgen / Auf Wiedersehen. غير رسمي: Hallo / Tschüs.",
examples:[["Guten Morgen, Herr Ali!","صباح الخير سيد علي! (رسمي)"],["Hallo, Mona!","أهلًا منى! (غير رسمي)"],["Auf Wiedersehen!","إلى اللقاء! (رسمي)"],["Tschüs! Bis morgen!","مع السلامة! (غير رسمي)"]],
questions:[
{t:"تحية الصباح الرسمية؟",ar:"اختر التحية",opts:["Guten Morgen","Hallo","Tschüs"],correct:0,why:"Guten Morgen رسمية كاملة"},
{t:"تحي صديقك؟",ar:"اختر التحية",opts:["Guten Morgen, Herr","Hallo, Ali","Sehr geehrter"],correct:1,why:"مع الأصدقاء: Hallo"},
{t:"تودع مديرك رسميًا؟",ar:"اختر الوداع",opts:["Tschüs","Auf Wiedersehen","Hallo"],correct:1,why:"Auf Wiedersehen رسمية"},
{t:"تودع صديقك؟",ar:"اختر الوداع",opts:["Auf Wiedersehen, Herr","Tschüs, bis morgen","Guten Tag"],correct:1,why:"مع الأصدقاء: Tschüs"},
{t:"تحية المساء الرسمية؟",ar:"اختر التحية",opts:["Guten Abend","Hallo du","Na"],correct:0,why:"Guten Abend رسمية"},
{t:"أيها غير رسمي؟",ar:"اختر غير الرسمي",opts:["Guten Tag","Morgen!","Auf Wiedersehen"],correct:1,why:"Morgen المختصرة غير رسمية"},
{t:"ترد على الهاتف رسميًا؟",ar:"اختر الأنسب",opts:["Hallo?!","Guten Tag, Schmidt.","Tschüs!"],correct:1,why:"رسمي: Guten Tag + الاسم"},
{t:"صديق يقول Hallo، ترد؟",ar:"اختر الرد",opts:["Hallo!","Guten Morgen, Herr!","Auf Wiedersehen!"],correct:0,why:"رد غير رسمي بمثله: Hallo"},
{t:"أي وداع رسمي؟",ar:"اختر الرسمي",opts:["Tschüs","Bis bald","Auf Wiedersehen"],correct:2,why:"Auf Wiedersehen رسمية"},
{t:"أي تحية لصديق صباحًا؟",ar:"اختر الأنسب",opts:["Guten Morgen, Herr Direktor","Morgen, Ali!","Sehr geehrte Damen"],correct:1,why:"صديق + صباح = Morgen غير رسمية"}]},
g8:{intro:"Wie heißen Sie؟ للاسم – Woher kommen Sie؟ للموطن (+ aus) – Was sprechen Sie؟ للغة.",
examples:[["Wie heißen Sie?","ما اسم حضرتك؟"],["Ich komme aus Ägypten.","أنا من مصر."],["Was sprechen Sie?","ماذا تتحدث؟"],["Ich spreche Deutsch.","أتحدث الألمانية."]],
questions:[
{t:"Woher kommen Sie تسأل عن؟",ar:"اختر الموضوع",opts:["الموطن","الاسم","العمر"],correct:0,why:"Woher = من أين (الموطن)"},
{t:"Wie heißen Sie تسأل عن؟",ar:"اختر الموضوع",opts:["العمر","الاسم","السكن"],correct:1,why:"heißen = يُسمى (الاسم)"},
{t:"Was sprechen Sie تسأل عن؟",ar:"اختر الموضوع",opts:["اللغة","الطعام","العمل"],correct:0,why:"sprechen = يتحدث (اللغة)"},
{t:"أكمل: Ich komme ___ Ägypten.",ar:"اختر الحرف",opts:["aus","in","nach"],correct:0,why:"الموطن مع aus: aus Ägypten"},
{t:"أكمل: ___ heißen Sie?",ar:"اختر الأداة",opts:["Was","Wie","Wo"],correct:1,why:"السؤال عن الاسم بـ Wie"},
{t:"إجابة: Ich heiße Mona. السؤال؟",ar:"اختر السؤال",opts:["Wie heißen Sie?","Woher kommen Sie?","Wie alt sind Sie?"],correct:0,why:"الإجابة اسم → السؤال عن الاسم"},
{t:"إجابة: Aus Spanien. السؤال؟",ar:"اختر السؤال",opts:["Wie heißen Sie?","Woher kommen Sie?","Was sprechen Sie?"],correct:1,why:"الإجابة موطن → Woher"},
{t:"إجابة: Deutsch und Arabisch. السؤال؟",ar:"اختر السؤال",opts:["Was sprechen Sie?","Wo wohnen Sie?","Wie geht's?"],correct:0,why:"الإجابة لغات → Was sprechen Sie"},
{t:"أكمل: Was ___ Sie? (تتحدث)",ar:"اختر الفعل",opts:["sprechen","heißen","kommen"],correct:0,why:"اللغة مع sprechen"},
{t:"أكمل: Woher ___ Sie? (تأتي)",ar:"اختر الفعل",opts:["kommen","heißen","sprechen"],correct:0,why:"الموطن مع kommen"}]},
g9:{intro:"das أداة المحايد، وأيضًا اسم إشارة: Das ist… / Das sind…",
examples:[["Das ist Ali.","هذا علي."],["Das sind Frauen.","هؤلاء نساء."],["Das Buch ist neu.","الكتاب جديد."],["Das Kind spielt.","الطفل يلعب."]],
questions:[
{t:"Das sind Frauen تعني؟",ar:"اختر المعنى",opts:["هؤلاء نساء","هذا رجل","هذه امرأة"],correct:0,why:"Das sind + جمع = هؤلاء"},
{t:"Das ist Ali تعني؟",ar:"اختر المعنى",opts:["هذا علي","هذه علي","هؤلاء علي"],correct:0,why:"Das ist + مفرد = هذا"},
{t:"في Das Buch ist neu كلمة Das هي؟",ar:"اختر الوظيفة",opts:["أداة المحايد","اسم إشارة","فعل"],correct:0,why:"قبل اسم محايد = أداة: das Buch"},
{t:"في Das ist mein Lehrer كلمة Das هي؟",ar:"اختر الوظيفة",opts:["أداة","اسم إشارة (هذا)","جمع"],correct:1,why:"Das ist… = هذا… (إشارة)"},
{t:"أكمل: ___ sind Kinder. (هؤلاء أطفال)",ar:"اختر الكلمة",opts:["Das","Der","Die"],correct:0,why:"الإشارة للجمع: Das sind"},
{t:"أكمل: ___ ist eine Lampe. (هذا مصباح)",ar:"اختر الكلمة",opts:["Das","Der","Den"],correct:0,why:"هذا = Das ist"},
{t:"Das Kind spielt تعني؟",ar:"اختر المعنى",opts:["الطفل يلعب","هذا يلعب","أطفال يلعبون"],correct:0,why:"هنا das أداة للمحايد Kind"},
{t:"أي جملة فيها das كإشارة؟",ar:"اختر الجملة",opts:["Das Auto ist rot.","Das ist gut.","Ich sehe das Auto."],correct:1,why:"Das ist… وحدها = إشارة (هذا)"},
{t:"Das Wasser ist kalt تعني؟",ar:"اختر المعنى",opts:["الماء بارد","هذا بارد","مياه باردة"],correct:0,why:"das أداة للمحايد Wasser"},
{t:"أكمل: ___ ist meine Tasche. (هذه حقيبتي)",ar:"اختر الكلمة",opts:["Das","Die","Der"],correct:0,why:"هذه = Das ist (الإشارة ثابتة)"}]},
g10:{intro:"Was ماذا – Wer من – Wo أين – Woher من أين – Wie كيف – Wann متى. والفعل ثانيًا.",
examples:[["Wo wohnst du?","أين تسكن؟"],["Wer ist das?","من هذا؟"],["Wann kommst du?","متى تأتي؟"],["Wie heißt du?","ما اسمك؟"]],
questions:[
{t:"ما معنى Wo؟",ar:"اختر المعنى",opts:["أين","متى","كيف"],correct:0,why:"Wo = أين (المكان)"},
{t:"ما معنى Wer؟",ar:"اختر المعنى",opts:["ماذا","من (عاقل)","أين"],correct:1,why:"Wer = من للعاقل"},
{t:"ما معنى Was؟",ar:"اختر المعنى",opts:["ماذا","من","كيف"],correct:0,why:"Was = ماذا"},
{t:"ما معنى Woher؟",ar:"اختر المعنى",opts:["أين","من أين","إلى أين"],correct:1,why:"Woher = من أين (الأصل)"},
{t:"ما معنى Wie؟",ar:"اختر المعنى",opts:["كيف","كم","متى"],correct:0,why:"Wie = كيف"},
{t:"ما معنى Wann؟",ar:"اختر المعنى",opts:["أين","متى","لماذا"],correct:1,why:"Wann = متى (الزمان)"},
{t:"أكمل: ___ wohnst du؟ (أين تسكن)",ar:"اختر الأداة",opts:["Wo","Wer","Was"],correct:0,why:"السؤال عن المكان بـ Wo"},
{t:"أكمل: ___ ist das؟ (من هذا)",ar:"اختر الأداة",opts:["Wo","Wer","Wie"],correct:1,why:"السؤال عن العاقل بـ Wer"},
{t:"أكمل: ___ kommst du؟ (متى تأتي)",ar:"اختر الأداة",opts:["Wo","Wann","Wer"],correct:1,why:"السؤال عن الزمان بـ Wann"},
{t:"رتب: wohnst / du / Wo",ar:"رتب الجملة",type:"order",words:["Wo","wohnst","du"],why:"أداة الاستفهام أولًا ثم الفعل ثانيًا: Wo wohnst du؟"}]},
g11:{intro:"معظم البلاد بلا أداة، لكن: die Schweiz – die Türkei – die Ukraine – die USA.",
examples:[["Ich komme aus Spanien.","أنا من إسبانيا."],["Ich bin aus der Türkei.","أنا من تركيا."],["Deutschland ist schön.","ألمانيا جميلة."],["Die Schweiz ist klein.","سويسرا صغيرة."]],
questions:[
{t:"ما أداة Schweiz؟",ar:"اختر الأداة",opts:["die","der","das"],correct:0,why:"die Schweiz مؤنثة"},
{t:"ما أداة Türkei؟",ar:"اختر الأداة",opts:["der","die","das"],correct:1,why:"die Türkei مؤنثة"},
{t:"أكمل: Ich komme aus ___. (ألمانيا)",ar:"اختر الصحيح",opts:["Deutschland","der Deutschland","die Deutschland"],correct:0,why:"Deutschland بلا أداة"},
{t:"أكمل: Ich bin aus ___. (تركيا)",ar:"اختر الصحيح",opts:["Türkei","der Türkei","die Türkei"],correct:2,why:"البلاد المؤنثة تأخذ die (هنا Dativ تبقى die)"},
{t:"ما أداة Ukraine؟",ar:"اختر الأداة",opts:["der","das","die"],correct:2,why:"die Ukraine مؤنثة"},
{t:"أكمل: Ich wohne in ___. (إسبانيا)",ar:"اختر الصحيح",opts:["Spanien","der Spanien","die Spanien"],correct:0,why:"Spanien بلا أداة"},
{t:"ما أداة USA؟",ar:"اختر الأداة",opts:["die","der","das"],correct:0,why:"die USA (جمع) مؤنثة"},
{t:"أكمل: Er kommt aus ___. (إيطاليا)",ar:"اختر الصحيح",opts:["Italien","dem Italien","die Italien"],correct:0,why:"Italien بلا أداة"},
{t:"أكمل: Sie ist aus ___. (سويسرا)",ar:"اختر الصحيح",opts:["Schweiz","der Schweiz","die Schweiz"],correct:2,why:"die Schweiz مؤنثة"},
{t:"أي بلد له أداة؟",ar:"اختر البلد المؤنث",opts:["Frankreich","die Türkei","Japan"],correct:1,why:"تركيا من البلاد المؤنثة القليلة"}]},
g12:{intro:"أيام الأسبوع مذكرة وتأتي مع am: am Montag.",
examples:[["Am Montag lerne ich.","أتعلم يوم الاثنين."],["Heute ist Sonntag.","اليوم الأحد."],["Am Freitag spiele ich.","ألعب يوم الجمعة."],["Der Montag ist gut.","الاثنين جيد."]],
questions:[
{t:"أكمل: ___ Montag. (يوم الاثنين)",ar:"اختر الحرف",opts:["am","im","um"],correct:0,why:"الأيام مع am"},
{t:"ما معنى Montag؟",ar:"اختر اليوم",opts:["الاثنين","الأحد","الجمعة"],correct:0,why:"Montag = الاثنين"},
{t:"ما معنى Sonntag؟",ar:"اختر اليوم",opts:["السبت","الأحد","الاثنين"],correct:1,why:"Sonntag = الأحد"},
{t:"ما معنى Freitag؟",ar:"اختر اليوم",opts:["الجمعة","الخميس","السبت"],correct:0,why:"Freitag = الجمعة"},
{t:"أكمل: ___ Sonntag habe ich frei.",ar:"اختر الحرف",opts:["Am","Im","Um"],correct:0,why:"الأيام مع am (كبيرة أول الجملة)"},
{t:"ما أداة أيام الأسبوع؟",ar:"اختر الأداة",opts:["der","die","das"],correct:0,why:"الأيام مذكرة: der Montag"},
{t:"رتب: Montag / lerne / am / ich",ar:"رتب الجملة",type:"order",words:["Am","Montag","lerne","ich"],why:"Am Montag lerne ich (الفعل ثانيًا)"},
{t:"ما معنى Samstag؟",ar:"اختر اليوم",opts:["الأحد","السبت","الجمعة"],correct:1,why:"Samstag = السبت"},
{t:"أكمل: Heute ist ___. (الأحد)",ar:"اختر اليوم",opts:["Sonntag","Montag","Freitag"],correct:0,why:"Heute ist Sonntag"},
{t:"أي جملة صحيحة؟",ar:"اختر الصحيحة",opts:["Ich lerne am Montag.","Ich lerne im Montag.","Ich lerne um Montag."],correct:0,why:"اليوم مع am فقط"}]},
g13:{intro:"معرفة der/die/das لشيء معروف – نكرة ein/eine لغير المعروف – الجمع بلا أداة.",
examples:[["Das ist der Hafen.","هذا هو الميناء (معروف)."],["Das ist ein Hafen.","هذا ميناء (غير معروف)."],["Das ist eine Lampe.","هذا مصباح."],["Das sind Tische.","هذه طاولات (جمع بلا أداة)."]],
questions:[
{t:"أكمل (معرفة): Das ist ___ Hafen.",ar:"اختر الأداة",opts:["der","ein","kein"],correct:0,why:"Hafen مذكر معروف: der Hafen"},
{t:"أكمل (نكرة): Das ist ___ Hafen.",ar:"اختر الأداة",opts:["der","ein","den"],correct:1,why:"غير معروف مذكر: ein Hafen"},
{t:"أكمل (معرفة): Das ist ___ Lampe.",ar:"اختر الأداة",opts:["die","eine","der"],correct:0,why:"Lampe مؤنثة معروفة: die Lampe"},
{t:"أكمل (نكرة): Das ist ___ Lampe.",ar:"اختر الأداة",opts:["die","eine","ein"],correct:1,why:"غير معروفة مؤنثة: eine Lampe"},
{t:"أكمل (معرفة): Das ist ___ Buch.",ar:"اختر الأداة",opts:["das","ein","der"],correct:0,why:"Buch محايد معروف: das Buch"},
{t:"أكمل (نكرة): Das ist ___ Buch.",ar:"اختر الأداة",opts:["das","eine","ein"],correct:2,why:"غير معروف محايد: ein Buch"},
{t:"أكمل (جمع): Das sind ___ Tische.",ar:"اختر الصحيح",opts:["die","eine","— (بلا أداة)"],correct:2,why:"جمع النكرة بلا أداة: Tische"},
{t:"أي جملة للمعرفة؟",ar:"اختر جملة المعرفة",opts:["Das ist der Mann.","Das ist ein Mann.","Das sind Männer."],correct:0,why:"der = معروف"},
{t:"أي جملة للنكرة؟",ar:"اختر جملة النكرة",opts:["Das ist die Frau.","Das ist eine Frau.","Das ist der Frau."],correct:1,why:"eine = غير معروفة"},
{t:"كلمة Hafen مذكر أم مؤنث؟",ar:"اختر الجنس",opts:["مذكر der","مؤنث die","محايد das"],correct:0,why:"der Hafen مذكر"}]},
g14:{intro:"ننفي النكرة: kein للمذكر والمحايد، keine للمؤنث والجمع.",
examples:[["Ich habe ein Kind.","لدي طفل."],["Ich habe kein Kind.","ليس لدي طفل."],["Ich habe keine Kinder.","ليس لدي أطفال."],["Das ist keine Lampe.","هذا ليس مصباحًا."]],
questions:[
{t:"أكمل: Ich habe ___ Kinder.",ar:"اختر النفي",opts:["keine","kein","nicht"],correct:0,why:"Kinder جمع → keine"},
{t:"أكمل: Ich habe ___ Auto.",ar:"اختر النفي",opts:["keine","kein","nicht"],correct:1,why:"Auto محايد مفرد → kein"},
{t:"أكمل: Das ist ___ Lampe.",ar:"اختر النفي",opts:["kein","keine","nicht"],correct:1,why:"Lampe مؤنثة → keine"},
{t:"أكمل: Ich habe ___ Hund.",ar:"اختر النفي",opts:["keine","kein","nicht"],correct:1,why:"Hund مذكر مفرد → kein"},
{t:"أكمل: Das sind ___ Äpfel.",ar:"اختر النفي",opts:["kein","keine","nicht"],correct:1,why:"Äpfel جمع → keine"},
{t:"أكمل: Er hat ___ Zeit.",ar:"اختر النفي",opts:["kein","keine","nicht"],correct:1,why:"Zeit مؤنثة → keine"},
{t:"أكمل: Wir haben ___ Brot.",ar:"اختر النفي",opts:["keine","nicht","kein"],correct:2,why:"Brot محايد مفرد → kein"},
{t:"أي نفي صحيح لـ eine Frau؟",ar:"اختر النفي",opts:["kein Frau","keine Frau","nicht Frau"],correct:1,why:"مؤنثة → keine Frau"},
{t:"أي نفي صحيح لـ ein Mann؟",ar:"اختر النفي",opts:["kein Mann","keine Mann","nicht Mann"],correct:0,why:"مذكر → kein Mann"},
{t:"Hast du Kinder؟ — Nein, ___ Kinder.",ar:"اختر الرد",opts:["kein","keine","nicht"],correct:1,why:"نفي الجمع: keine"}]},
g15:{intro:"الأمر الرسمي: الفعل بالمصدر أولًا + Sie + علامة تعجب.",
examples:[["Fragen Sie!","اسأل حضرتك!"],["Gehen Sie links!","اذهب حضرتك يسارًا!"],["Kommen Sie bitte!","تعال حضرتك من فضلك!"],["Sprechen Sie langsam!","تحدث حضرتك ببطء!"]],
questions:[
{t:"ما الأمر الرسمي من fragen؟",ar:"اختر الأمر",opts:["Fragen Sie!","Fragst du!","Frage!"],correct:0,why:"رسمي = المصدر + Sie"},
{t:"ما الأمر الرسمي من gehen؟",ar:"اختر الأمر",opts:["Geh!","Gehen Sie!","Du gehst!"],correct:1,why:"Gehen Sie! رسمية"},
{t:"ما الأمر الرسمي من kommen؟",ar:"اختر الأمر",opts:["Komm!","Kommt!","Kommen Sie!"],correct:2,why:"Kommen Sie! رسمية"},
{t:"رتب: Sie / Fragen / !",ar:"رتب الأمر",type:"order",words:["Fragen","Sie"],why:"الفعل أولًا ثم Sie: Fragen Sie!"},
{t:"أي جملة أمر رسمي؟",ar:"اختر الرسمية",opts:["Gehen Sie links!","Geh links!","Du gehst links!"],correct:0,why:"Gehen Sie = رسمي"},
{t:"ما الأمر الرسمي من sprechen؟",ar:"اختر الأمر",opts:["Sprich!","Sprechen Sie!","Du sprichst!"],correct:1,why:"Sprechen Sie! رسمية"},
{t:"صديقك: Geh! مديرك؟",ar:"اختر الرسمي",opts:["Geh!","Gehen Sie!","Gehst du!"],correct:1,why:"مع المدير: Gehen Sie"},
{t:"ما الأمر الرسمي من warten؟",ar:"اختر الأمر",opts:["Warte!","Warten Sie!","Wartest du!"],correct:1,why:"Warten Sie! رسمية"},
{t:"أكمل رسميًا: ___ Sie bitte! (تعال)",ar:"اختر الفعل",opts:["Komm","Kommen","Kommst"],correct:1,why:"المصدر أولًا: Kommen Sie"},
{t:"أي علامة مع الأمر الرسمي؟",ar:"اختر العلامة",opts:["!","?","."],correct:0,why:"الأمر ينتهي بتعجب"}]},
g16:{intro:"القاعدة الذهبية: الفعل المُصرّف في المرتبة الثانية دائمًا.",
examples:[["Ich lerne heute.","أتعلم اليوم."],["Heute lerne ich.","اليوم أتعلم."],["Er kommt morgen.","هو يأتي غدًا."],["Morgen kommt er.","غدًا يأتي هو."]],
questions:[
{t:"أين يأتي الفعل المُصرّف؟",ar:"اختر المرتبة",opts:["الثانية","الأولى","الأخيرة"],correct:0,why:"الفعل دائمًا ثانيًا"},
{t:"رتب: lerne / ich / heute",ar:"رتب الجملة",type:"order",words:["Ich","lerne","heute"],why:"Ich (1) lerne (2) heute (3)"},
{t:"رتب: lerne / Heute / ich",ar:"رتب الجملة",type:"order",words:["Heute","lerne","ich"],correct:0,why:"حتى لو بدأنا بالزمن، الفعل ثانيًا"},
{t:"أي جملة صحيحة؟",ar:"اختر الصحيحة",opts:["Ich lerne heute.","Ich heute lerne.","Lerne ich heute."],correct:0,why:"الفعل ثانيًا: Ich lerne heute"},
{t:"أي جملة صحيحة؟",ar:"اختر الصحيحة",opts:["Heute ich lerne.","Heute lerne ich.","Lerne heute ich."],correct:1,why:"Heute أولًا ثم الفعل ثانيًا"},
{t:"رتب: kommt / Er / morgen",ar:"رتب الجملة",type:"order",words:["Er","kommt","morgen"],why:"Er (1) kommt (2) morgen (3)"},
{t:"أي جملة خاطئة؟",ar:"اختر الخاطئة",opts:["Er kommt morgen.","Morgen kommt er.","Er morgen kommt."],correct:2,why:"Er morgen kommt خطأ — الفعل ليس ثانيًا"},
{t:"رتب: gut / Du / sprichst / Deutsch",ar:"رتب الجملة",type:"order",words:["Du","sprichst","gut","Deutsch"],why:"الفاعل ثم الفعل ثانيًا"},
{t:"في Heute lerne ich ما المرتبة الثانية؟",ar:"اختر الكلمة",opts:["Heute","lerne","ich"],correct:1,why:"lerne هي الثانية"},
{t:"في Ich lerne heute ما المرتبة الثانية؟",ar:"اختر الكلمة",opts:["Ich","lerne","heute"],correct:1,why:"lerne هي الثانية"}]},
g17:{intro:"الشهور والفصول مع im – الأيام مع am – الليل in der Nacht.",
examples:[["Im Sommer ist es heiß.","في الصيف الجو حار."],["Am Freitag spiele ich.","ألعب يوم الجمعة."],["Im Januar ist es kalt.","في يناير الجو بارد."],["In der Nacht schlafe ich.","أنام في الليل."]],
questions:[
{t:"أكمل: ___ Sommer.",ar:"اختر الحرف",opts:["Im","Am","Um"],correct:0,why:"الفصول مع im"},
{t:"أكمل: ___ Freitag.",ar:"اختر الحرف",opts:["Im","Am","Um"],correct:1,why:"الأيام مع am"},
{t:"أكمل: ___ Januar.",ar:"اختر الحرف",opts:["Am","Im","Um"],correct:1,why:"الشهور مع im"},
{t:"أكمل: ___ Nacht schlafe ich.",ar:"اختر الصحيح",opts:["In der","Im","Am"],correct:0,why:"الليل استثناء: in der Nacht"},
{t:"أكمل: ___ Winter ist es kalt.",ar:"اختر الحرف",opts:["Im","Am","Um"],correct:0,why:"Winter فصل → im"},
{t:"أكمل: ___ Montag lerne ich.",ar:"اختر الحرف",opts:["Im","Am","Um"],correct:1,why:"Montag يوم → am"},
{t:"أكمل: ___ März beginnt der Kurs.",ar:"اختر الحرف",opts:["Am","Um","Im"],correct:2,why:"März شهر → im"},
{t:"أي جملة صحيحة؟",ar:"اختر الصحيحة",opts:["Am Sommer.","Im Sommer.","Um Sommer."],correct:1,why:"الصيف مع im"},
{t:"أي جملة صحيحة؟",ar:"اختر الصحيحة",opts:["Im Montag.","Am Montag.","Um Montag."],correct:1,why:"الاثنين مع am"},
{t:"كلمة Nacht تأخذ؟",ar:"اختر الصحيح",opts:["im Nacht","in der Nacht","am Nacht"],correct:1,why:"Nacht مؤنثة واستثناء: in der Nacht"}]},
g18:{intro:"nicht تنفي الفعل والصفة والمعرف – kein تنفي النكرة فقط.",
examples:[["Ich studiere nicht.","أنا لا أدرس."],["Hast du kein Auto?","أليس لديك سيارة؟"],["Der Tee ist nicht heiß.","الشاي ليس ساخنًا."],["Ich habe keine Zeit.","ليس لدي وقت."]],
questions:[
{t:"كيف تنفي الفعل liebe؟",ar:"اختر النفي",opts:["ich liebe nicht","ich kein liebe","ich liebe kein"],correct:0,why:"الفعل يُنفى بـ nicht بعده"},
{t:"كيف تنفي الاسم النكرة Auto؟",ar:"اختر النفي",opts:["nicht Auto","kein Auto","keine Auto"],correct:1,why:"نكرة محايدة → kein"},
{t:"كيف تنفي الصفة gut؟",ar:"اختر النفي",opts:["kein gut","nicht gut","keine gut"],correct:1,why:"الصفة تُنفى بـ nicht"},
{t:"أكمل: Ich studiere ___.",ar:"اختر النفي",opts:["kein","nicht","keine"],correct:1,why:"نفي الفعل: nicht"},
{t:"أكمل: Hast du ___ Auto؟",ar:"اختر النفي",opts:["nicht","kein","keine"],correct:1,why:"نكرة محايدة: kein Auto"},
{t:"أكمل: Der Tee ist ___ heiß.",ar:"اختر النفي",opts:["kein","nicht","keine"],correct:1,why:"نفي الصفة: nicht heiß"},
{t:"أكمل: Ich habe ___ Zeit.",ar:"اختر النفي",opts:["kein","nicht","keine"],correct:2,why:"Zeit مؤنثة نكرة: keine"},
{t:"أي نفي صحيح؟",ar:"اختر الصحيح",opts:["Ich kein studiere.","Ich studiere nicht.","Ich nicht studiere."],correct:1,why:"nicht بعد الفعل"},
{t:"الاسم المعرف (der Mann) يُنفى بـ؟",ar:"اختر الأداة",opts:["kein","nicht","keine"],correct:1,why:"المعرف يُنفى بـ nicht"},
{t:"أكمل: Das ist ___ gut. (ليس جيدًا)",ar:"اختر النفي",opts:["kein","nicht","keine"],correct:1,why:"نفي الصفة: nicht"}]},
g19:{intro:"Wie alt bist du؟ للسؤال – Ich bin … Jahre alt للإجابة.",
examples:[["Wie alt bist du?","كم عمرك؟"],["Ich bin 15 Jahre alt.","عمري 15 سنة."],["Wie alt ist sie?","كم عمرها؟"],["Er ist 20 Jahre alt.","عمره 20 سنة."]],
questions:[
{t:"كيف تسأل عن العمر؟",ar:"اختر السؤال",opts:["Wie alt bist du?","Wie heißt du?","Wo wohnst du?"],correct:0,why:"العمر = Wie alt"},
{t:"كيف تجيب: عمري 15؟",ar:"اختر الإجابة",opts:["Ich bin 15 Jahre alt.","Ich habe 15 Jahre.","Ich bin 15 Jahr."],correct:0,why:"Ich bin … Jahre alt"},
{t:"رتب: alt / Wie / du / bist",ar:"رتب السؤال",type:"order",words:["Wie","alt","bist","du"],why:"Wie alt bist du؟"},
{t:"رتب: bin / Jahre / Ich / alt / 15",ar:"رتب الإجابة",type:"order",words:["Ich","bin","15","Jahre","alt"],why:"Ich bin 15 Jahre alt"},
{t:"تسألها عن عمرها؟",ar:"اختر السؤال",opts:["Wie alt bist du?","Wie alt ist sie?","Wie alt bin ich?"],correct:1,why:"عنها: Wie alt ist sie"},
{t:"عمره 20: Er ___ 20 Jahre alt.",ar:"اختر الفعل",opts:["bin","bist","ist"],correct:2,why:"Er → ist"},
{t:"أي سؤال عن الاسم وليس العمر؟",ar:"اختر سؤال الاسم",opts:["Wie alt bist du?","Wie heißt du?","Woher kommst du?"],correct:1,why:"heißen = الاسم"},
{t:"أكمل: Wie alt ___ du؟",ar:"اختر الفعل",opts:["bin","bist","ist"],correct:1,why:"du → bist"},
{t:"أكمل: Ich ___ 30 Jahre alt.",ar:"اختر الفعل",opts:["bin","bist","ist"],correct:0,why:"Ich → bin"},
{t:"كلمة Jahre تعني؟",ar:"اختر المعنى",opts:["سنة (جمع)","شهر","يوم"],correct:0,why:"Jahr سنة، Jahre سنوات"}]},
g20:{intro:"Akkusativ (المفعول): التغيير في المذكر فقط: der→den / ein→einen / kein→keinen / mein→meinen.",
examples:[["Ich esse einen Apfel.","آكل تفاحة."],["Ich sehe den Mann.","أرى الرجل."],["Sie kauft eine Lampe.","هي تشتري مصباحًا (لا تغيير)."],["Ich habe keinen Bruder.","ليس لدي أخ."]],
questions:[
{t:"أكمل: Ich habe ___ Apfel.",ar:"اختر الكلمة",opts:["einen","ein","einem"],correct:0,why:"Apfel مذكر مفعول: einen"},
{t:"أكمل: Ich sehe ___ Mann.",ar:"اختر الكلمة",opts:["der","den","dem"],correct:1,why:"Mann مذكر مفعول: den"},
{t:"أكمل: Sie kauft ___ Lampe.",ar:"اختر الكلمة",opts:["eine","einen","einer"],correct:0,why:"Lampe مؤنثة: لا تغيير (eine)"},
{t:"أكمل: Ich trinke ___ Wasser.",ar:"اختر الكلمة",opts:["einen","ein","einem"],correct:1,why:"Wasser محايد: لا تغيير (ein)"},
{t:"أكمل: Er besucht ___ Freund.",ar:"اختر الكلمة",opts:["mein","meinen","meinem"],correct:1,why:"Freund مذكر مفعول: meinen"},
{t:"أكمل: Ich habe ___ Bruder.",ar:"اختر النفي",opts:["kein","keinen","keinem"],correct:1,why:"Bruder مذكر مفعول منفي: keinen"},
{t:"أكمل: Wen liebt ___ Sohn؟ (الابن يحب من)",ar:"اختر الكلمة",opts:["der","den","dem"],correct:0,why:"Sohn هنا فاعل: der (لا تغيير)"},
{t:"أي أداة للمذكر المفعول؟",ar:"اختر الأداة",opts:["der","den","dem"],correct:1,why:"المذكر في Akkusativ → den"},
{t:"أكمل: Ich rufe ___ Lehrer an.",ar:"اختر الكلمة",opts:["der","den","dem"],correct:1,why:"Lehrer مذكر مفعول: den"},
{t:"أكمل: Sie liest ___ Buch.",ar:"اختر الكلمة",opts:["einen","ein","einem"],correct:1,why:"Buch محايد: لا تغيير (ein)"}]},
g21:{intro:"sein و werden و bleiben يأتي بعدها Nominativ (بدون تغيير).",
examples:[["Ich bin der Lehrer.","أنا المعلم."],["Er wird mein Mann.","سيصبح زوجي."],["Sie bleibt meine Freundin.","ستبقى صديقتي."],["Das ist ein Problem.","هذه مشكلة."]],
questions:[
{t:"أكمل: Ich bin ___ Lehrer.",ar:"اختر الكلمة",opts:["der","den","dem"],correct:0,why:"بعد sein يبقى Nominativ: der"},
{t:"أكمل: Er wird ___ Mann.",ar:"اختر الكلمة",opts:["mein","meinen","meinem"],correct:0,why:"بعد werden بدون تغيير: mein"},
{t:"أكمل: Sie bleibt ___ Freundin.",ar:"اختر الكلمة",opts:["meine","meinen","meiner"],correct:0,why:"بعد bleiben بدون تغيير: meine"},
{t:"أكمل: Das ist ___ Problem.",ar:"اختر الكلمة",opts:["ein","einen","einem"],correct:0,why:"بعد sein: ein (محايد بلا تغيير)"},
{t:"أي جملة صحيحة؟",ar:"اختر الصحيحة",opts:["Ich bin den Lehrer.","Ich bin der Lehrer.","Ich bin dem Lehrer."],correct:1,why:"sein + Nominativ دائمًا"},
{t:"أكمل: Er ist ___ Arzt.",ar:"اختر الكلمة",opts:["ein","einen","einem"],correct:0,why:"بعد ist: ein"},
{t:"أكمل: Sie wird ___ Ärztin.",ar:"اختر الكلمة",opts:["eine","einen","einer"],correct:0,why:"بعد wird: eine (لا تغيير)"},
{t:"أي فعل يأخذ Nominativ بعده؟",ar:"اختر الفعل",opts:["sehen","bleiben","besuchen"],correct:1,why:"bleiben من أفعال Nominativ"},
{t:"أكمل: Wir bleiben ___. (أصدقاء)",ar:"اختر الكلمة",opts:["Freunde","Freunden","Freundes"],correct:0,why:"بعد bleiben صورة القاموس"},
{t:"أي جملة خاطئة؟",ar:"اختر الخاطئة",opts:["Ich bin der Mann.","Er wird den Arzt.","Sie ist die Frau."],correct:1,why:"بعد wird لا يأتي den أبدًا"}]},
g22:{intro:"ضمائر المفعول: mich dich ihn uns euch (و sie تبقى sie).",
examples:[["Ich liebe dich.","أنا أحبك."],["Der Freund besucht ihn.","الصديق يزوره."],["Er sieht mich.","هو يراني."],["Wir besuchen euch.","نزوركم."]],
questions:[
{t:"أكمل: Ich liebe ___.",ar:"اختر الضمير",opts:["dich","du","dein"],correct:0,why:"مفعول du هو dich"},
{t:"أكمل: Er sieht ___. (أنا)",ar:"اختر الضمير",opts:["ich","mich","mein"],correct:1,why:"مفعول ich هو mich"},
{t:"أكمل: Wir besuchen ___. (هو)",ar:"اختر الضمير",opts:["er","ihn","sein"],correct:1,why:"مفعول er هو ihn"},
{t:"أكمل: Sie liebt ___. (نحن)",ar:"اختر الضمير",opts:["wir","uns","unser"],correct:1,why:"مفعول wir هو uns"},
{t:"أكمل: Ich rufe ___ an. (أنتم)",ar:"اختر الضمير",opts:["ihr","euch","euer"],correct:1,why:"مفعول ihr هو euch"},
{t:"أكمل: Er kennt ___. (هي)",ar:"اختر الضمير",opts:["sie","sien","ihr"],correct:0,why:"sie للمؤنث لا تتغير في المفعول"},
{t:"مفعول du هو؟",ar:"اختر الضمير",opts:["dich","dir","dein"],correct:0,why:"Akkusativ: dich (dir للـ Dativ)"},
{t:"مفعول ich هو؟",ar:"اختر الضمير",opts:["mich","mir","mein"],correct:0,why:"Akkusativ: mich (mir للـ Dativ)"},
{t:"أكمل: Siehst du ___؟ (أنا)",ar:"اختر الضمير",opts:["ich","mich","mir"],correct:1,why:"بعد الفعل مفعول: mich"},
{t:"أكمل: Ich höre ___. (أنتم)",ar:"اختر الضمير",opts:["ihr","euch","euern"],correct:1,why:"مفعول ihr هو euch"}]},
g23:{intro:"wer للفاعل العاقل – wen للمفعول العاقل – was لغير العاقل.",
examples:[["Wer besucht ihn?","من يزوره؟"],["Wen siehst du?","من ترى؟"],["Was isst du?","ماذا تأكل؟"],["Was kostet das?","كم سعر هذا؟"]],
questions:[
{t:"نسأل عن المفعول العاقل بـ؟",ar:"اختر الأداة",opts:["Wen","Wer","Was"],correct:0,why:"المفعول العاقل = wen"},
{t:"نسأل عن الفاعل العاقل بـ؟",ar:"اختر الأداة",opts:["Wen","Wer","Was"],correct:1,why:"الفاعل العاقل = wer"},
{t:"نسأل عن غير العاقل بـ؟",ar:"اختر الأداة",opts:["Wen","Wer","Was"],correct:2,why:"غير العاقل = was"},
{t:"أكمل: ___ besucht ihn؟ (من يزوره)",ar:"اختر الأداة",opts:["Wer","Wen","Was"],correct:0,why:"نسأل عن الفاعل: Wer"},
{t:"أكمل: ___ siehst du؟ (من ترى)",ar:"اختر الأداة",opts:["Wer","Wen","Was"],correct:1,why:"نسأل عن المفعول: Wen"},
{t:"أكمل: ___ isst du؟ (ماذا تأكل)",ar:"اختر الأداة",opts:["Wer","Wen","Was"],correct:2,why:"الأكل غير عاقل: Was"},
{t:"أكمل: ___ liebt er؟ (من يحب)",ar:"اختر الأداة",opts:["Wen","Wer","Was"],correct:1,why:"الفاعل: Wer"},
{t:"أكمل: ___ kostet das؟ (كم سعر)",ar:"اختر الأداة",opts:["Wer","Wen","Was"],correct:2,why:"السعر غير عاقل: Was"},
{t:"إجابتها Ali (فاعل). السؤال؟",ar:"اختر السؤال",opts:["Wen ist das?","Wer ist das?","Was ist das?"],correct:1,why:"عاقل فاعل: Wer"},
{t:"إجابتها Mona (مفعول). السؤال؟",ar:"اختر السؤال",opts:["Wen siehst du?","Wer siehst du?","Was siehst du?"],correct:0,why:"عاقل مفعول: Wen"}]},
g24:{intro:"في المحل: Was kostet das؟ للسعر – Sonst noch etwas؟ لعرض المزيد.",
examples:[["Was kostet das?","كم سعر هذا؟"],["Das kostet 5 Euro.","سعره 5 يورو."],["Sonst noch etwas?","شيء آخر؟"],["Guten Appetit!","بالهناء!"]],
questions:[
{t:"Was kostet das تسأل عن؟",ar:"اختر الموضوع",opts:["السعر","الوقت","الاسم"],correct:0,why:"kosten = يُكلف (السعر)"},
{t:"البائع يعرض المزيد فيقول؟",ar:"اختر الجملة",opts:["Sonst noch etwas?","Wie heißen Sie?","Wo wohnen Sie?"],correct:0,why:"Sonst noch etwas = شيء آخر؟"},
{t:"أكمل: Was ___ das؟ (كم سعر)",ar:"اختر الفعل",opts:["kostet","heißt","wohnt"],correct:0,why:"السعر مع kosten"},
{t:"إجابة السعر تكون مثل؟",ar:"اختر الإجابة",opts:["Das kostet 5 Euro.","Ich heiße Ali.","Heute ist Montag."],correct:0,why:"الإجابة: Das kostet + السعر"},
{t:"زبون يدفع ويشكر، البائع يرد؟",ar:"اختر الرد",opts:["Guten Appetit!","Tschüs!","Was kostet das?"],correct:0,why:"في الطعام: Guten Appetit"},
{t:"أكمل: ___ noch etwas؟",ar:"اختر الكلمة",opts:["Sonst","Wer","Wie"],correct:0,why:"Sonst noch etwas = هل من شيء آخر"},
{t:"تسأل عن سعر الخبز؟",ar:"اختر السؤال",opts:["Was kostet das Brot?","Wo ist das Brot?","Wer isst Brot?"],correct:0,why:"السعر: Was kostet…؟"},
{t:"معنى kostet؟",ar:"اختر المعنى",opts:["يُكلف (سعر)","يسكن","يأكل"],correct:0,why:"kosten = يُكلف"},
{t:"رتب: kostet / das / Was",ar:"رتب السؤال",type:"order",words:["Was","kostet","das"],why:"Was kostet das؟"},
{t:"أي رد مناسب لـ Danke (زبون)؟",ar:"اختر الرد",opts:["Bitte schön!","Was kostet das?","Sonst noch etwas?"],correct:0,why:"الرد على الشكر: Bitte schön"}]},
g25:{intro:"فعل الكيفية ثانيًا مُصرّفًا + الفعل الأساسي مصدرًا في آخر الجملة.",
examples:[["Ich kann Deutsch sprechen.","أستطيع التحدث بالألمانية."],["Ich muss lernen.","يجب أن أتعلم."],["Er will Tee trinken.","هو يريد شرب الشاي."],["Wir müssen früh aufstehen.","يجب أن نستيقظ مبكرًا."]],
questions:[
{t:"أين يأتي الفعل الأساسي مع المساعد؟",ar:"اختر الموضع",opts:["المصدر آخر الجملة","مُصرّف ثانيًا","محذوف"],correct:0,why:"الأساسي مصدرًا في الآخر: sprechen"},
{t:"أكمل: Ich kann Deutsch ___.",ar:"اختر الصيغة",opts:["spreche","sprechen","gesprochen"],correct:1,why:"بعد المساعد: المصدر sprechen"},
{t:"أكمل: Er ___ gut schwimmen. (يستطيع)",ar:"اختر الفعل",opts:["kann","können","kannt"],correct:0,why:"Er + kann (تصريف شاذ)"},
{t:"رتب: sprechen / kann / Deutsch / Ich",ar:"رتب الجملة",type:"order",words:["Ich","kann","Deutsch","sprechen"],why:"المساعد ثانيًا + المصدر آخرًا"},
{t:"أكمل: Wir ___ lernen. (يجب)",ar:"اختر الفعل",opts:["muss","müssen","musst"],correct:1,why:"Wir + müssen"},
{t:"أكمل: Du ___ früh aufstehen. (يجب)",ar:"اختر الفعل",opts:["muss","musst","müssen"],correct:1,why:"Du + musst"},
{t:"أكمل: Ich ___ einen Tee. (أريد)",ar:"اختر الفعل",opts:["will","wille","wollen"],correct:0,why:"Ich + will"},
{t:"أي جملة صحيحة؟",ar:"اختر الصحيحة",opts:["Ich kann spreche Deutsch.","Ich kann Deutsch sprechen.","Ich spreche kann Deutsch."],correct:1,why:"المصدر في الآخر"},
{t:"معنى müssen؟",ar:"اختر المعنى",opts:["يجب","يستطيع","يريد"],correct:0,why:"müssen = يجب (وجوب)"},
{t:"معنى können؟",ar:"اختر المعنى",opts:["يجب","يستطيع","يحب"],correct:1,why:"können = يستطيع (قدرة)"}]},
g26:{intro:"تمامًا: um – من…إلى: von…bis – ونسأل بـ wann / wie lange.",
examples:[["Ich frühstücke um 6 Uhr.","أفطر السادسة."],["Von 6 bis 9 Uhr.","من 6 إلى 9."],["Wann kommst du?","متى تأتي؟"],["Der Kurs ist von Mai bis Juni.","الكورس من مايو إلى يونيو."]],
questions:[
{t:"أكمل: ___ 6 Uhr. (تمام السادسة)",ar:"اختر الحرف",opts:["um","am","im"],correct:0,why:"تمام الساعة مع um"},
{t:"أكمل: Von 6 ___ 9 Uhr.",ar:"اختر الحرف",opts:["bis","nach","zu"],correct:0,why:"من…إلى = von…bis"},
{t:"نسأل عن الموعد بـ؟",ar:"اختر الأداة",opts:["wann","wo","wer"],correct:0,why:"الموعد = wann (متى)"},
{t:"نسأل عن المدة بـ؟",ar:"اختر الأداة",opts:["wie lange","wie viel","wie alt"],correct:0,why:"المدة = wie lange"},
{t:"أكمل: ___ 8 Uhr beginnt der Film.",ar:"اختر الحرف",opts:["Um","Am","Im"],correct:0,why:"تمام الثامنة: um"},
{t:"أكمل: Von Mai ___ Juni.",ar:"اختر الحرف",opts:["bis","nach","aus"],correct:0,why:"von…bis للمدى"},
{t:"أي جملة صحيحة؟",ar:"اختر الصحيحة",opts:["Ich komme am 6 Uhr.","Ich komme um 6 Uhr.","Ich komme im 6 Uhr."],correct:1,why:"الساعة التامة مع um"},
{t:"رتب: Uhr / um / 6 / frühstücke / Ich",ar:"رتب الجملة",type:"order",words:["Ich","frühstücke","um","6","Uhr"],why:"الفعل ثانيًا + um للساعة"},
{t:"Wie lange lernst du؟ تسأل عن؟",ar:"اختر الموضوع",opts:["المدة","الموعد","المكان"],correct:0,why:"wie lange = كم المدة"},
{t:"Wann ist der Test؟ تسأل عن؟",ar:"اختر الموضوع",opts:["الموعد","السعر","الاسم"],correct:0,why:"wann = متى"}]},
g27:{intro:"الملكية: mein/meine + للمذكر المفعول meinen/deinen.",
examples:[["Mein Name ist Ahmed.","اسمي أحمد."],["Wer besucht meinen Bruder?","من يزور أخي؟"],["Das ist meine Tasche.","هذه حقيبتي."],["Ich sehe deine Mutter.","أرى والدتك."]],
questions:[
{t:"أكمل (أمي): ___ Mutter ist nett.",ar:"اختر الكلمة",opts:["Meine","Mein","Meinen"],correct:0,why:"Mutter مؤنثة فاعل: Meine"},
{t:"أكمل (أبي): ___ Vater ist nett.",ar:"اختر الكلمة",opts:["Meine","Mein","Meinen"],correct:1,why:"Vater مذكر فاعل: Mein"},
{t:"أكمل: Wer besucht ___ Bruder؟ (أخي مفعول)",ar:"اختر الكلمة",opts:["mein","meinen","meinem"],correct:1,why:"Bruder مذكر مفعول: meinen"},
{t:"أكمل: Ich sehe ___ Schwester. (أختي)",ar:"اختر الكلمة",opts:["mein","meine","meinen"],correct:1,why:"Schwester مؤنثة: meine (لا تغيير)"},
{t:"أكمل: Das ist ___ Buch. (كتابي)",ar:"اختر الكلمة",opts:["mein","meinen","meine"],correct:0,why:"Buch محايد فاعل: mein"},
{t:"أكمل: Kennst du ___ Lehrer؟ (معلمك)",ar:"اختر الكلمة",opts:["dein","deinen","deinem"],correct:1,why:"Lehrer مذكر مفعول: deinen"},
{t:"أكمل: ___ Name ist Mona. (اسمي)",ar:"اختر الكلمة",opts:["Meine","Mein","Meinen"],correct:1,why:"Name مذكر فاعل: Mein"},
{t:"أي جملة صحيحة؟",ar:"اختر الصحيحة",opts:["Ich sehe meinen Vater.","Ich sehe mein Vater.","Ich sehe meinem Vater."],correct:0,why:"مفعول مذكر: meinen"},
{t:"ملكية المؤنث المفرد؟",ar:"اختر الصيغة",opts:["mein","meine","meinen"],correct:1,why:"المؤنث: meine"},
{t:"ملكية المذكر المفعول؟",ar:"اختر الصيغة",opts:["mein","meine","meinen"],correct:2,why:"المفعول المذكر: meinen"}]},
g28:{intro:"الرسمية ein Uhr – العامية eins – والنصف للساعة القادمة.",
examples:[["Es ist ein Uhr.","الساعة الواحدة (رسمي)."],["Es ist eins.","الساعة واحدة (عامي)."],["Es ist halb vier.","الثالثة والنصف."],["Es ist halb acht.","السابعة والنصف."]],
questions:[
{t:"halb vier تعني؟",ar:"اختر الوقت",opts:["3:30","4:30","4:00"],correct:0,why:"halb + القادمة: halb vier = 3:30"},
{t:"halb acht تعني؟",ar:"اختر الوقت",opts:["8:30","7:30","8:00"],correct:1,why:"halb acht = 7:30"},
{t:"الواحدة رسميًا؟",ar:"اختر الصيغة",opts:["Es ist ein Uhr.","Es ist eins.","Es ist eine Uhr."],correct:0,why:"رسمي: ein Uhr"},
{t:"الواحدة عاميًا؟",ar:"اختر الصيغة",opts:["Es ist ein Uhr.","Es ist eins.","Es ist einer."],correct:1,why:"عامي: eins"},
{t:"halb zwölf تعني؟",ar:"اختر الوقت",opts:["12:30","11:30","12:00"],correct:1,why:"halb zwölf = 11:30"},
{t:"أي صيغة عامية؟",ar:"اختر العامية",opts:["Es ist ein Uhr.","Es ist eins.","Es ist der Uhr."],correct:1,why:"eins بدون Uhr = عامي"},
{t:"Es ist halb drei = ؟",ar:"اختر الوقت",opts:["3:30","2:30","3:00"],correct:1,why:"halb drei = 2:30"},
{t:"أكمل رسميًا: Es ist ___ Uhr. (الواحدة)",ar:"اختر الكلمة",opts:["ein","eins","eine"],correct:0,why:"رسمي مع Uhr: ein"},
{t:"النصف في الألمانية يُحسب؟",ar:"اختر القاعدة",opts:["للساعة الحالية","للساعة القادمة","للساعة السابقة"],correct:1,why:"halb للقادمة دائمًا"},
{t:"Es ist halb zehn = ؟",ar:"اختر الوقت",opts:["10:30","9:30","10:00"],correct:1,why:"halb zehn = 9:30"}]},
g29:{intro:"نعتذر بـ Es tut mir leid / Entschuldigen Sie – ونرد Kein Problem / Macht nichts.",
examples:[["Es tut mir leid.","أنا آسف."],["Kein Problem.","لا مشكلة."],["Entschuldigung!","عذرًا!"],["Macht nichts!","لا بأس! (حرفيًا: لا يفعل شيئًا)"]],
questions:[
{t:"ما الرد على Entschuldigung؟",ar:"اختر الرد",opts:["Kein Problem.","Guten Tag.","Danke."],correct:0,why:"الرد: Kein Problem (لا مشكلة)"},
{t:"كيف تعتذر بقوة؟",ar:"اختر الاعتذار",opts:["Es tut mir leid.","Kein Problem.","Macht nichts."],correct:0,why:"الاعتذار: Es tut mir leid"},
{t:"صديقك تأخر وقال Entschuldigung، ترد؟",ar:"اختر الرد",opts:["Macht nichts!","Wie heißt du?","Tschüs!"],correct:0,why:"Macht nichts = لا بأس"},
{t:"رتب: mir / tut / Es / leid",ar:"رتب الاعتذار",type:"order",words:["Es","tut","mir","leid"],why:"Es tut mir leid"},
{t:"أيها اعتذار؟",ar:"اختر الاعتذار",opts:["Schon gut.","Es tut mir leid.","Kein Problem."],correct:1,why:"الباقي ردود وليس اعتذارًا"},
{t:"أيها رد على اعتذار؟",ar:"اختر الرد",opts:["Es tut mir leid.","Entschuldigung.","Schon gut."],correct:2,why:"Schon gut = خلاص، لا بأس"},
{t:"كسرت كوب صديقك، تقول؟",ar:"اختر الجملة",opts:["Es tut mir leid!","Kein Problem!","Guten Appetit!"],correct:0,why:"المخطئ يعتذر: Es tut mir leid"},
{t:"زميلك اعتذر، تطمئنه؟",ar:"اختر الجملة",opts:["Kein Problem!","Es tut mir leid!","Wie geht's?"],correct:0,why:"تطمئنه: Kein Problem"},
{t:"معنى Macht nichts؟",ar:"اختر المعنى",opts:["لا بأس","مع السلامة","شكرًا"],correct:0,why:"Macht nichts = لا يهم / لا بأس"},
{t:"أي موقف يحتاج اعتذارًا؟",ar:"اختر الموقف",opts:["تأخرت عن الموعد","تناولت الغداء","نمت مبكرًا"],correct:0,why:"التأخر يستحق: Es tut mir leid"}]},
g30:{intro:"حروف mit و bei و aus و von و seit تأخذ Dativ دائمًا.",
examples:[["Ich komme mit dir.","آتي معك."],["Ich bin bei dir.","أنا عندك."],["Ich komme aus Ägypten.","أنا من مصر."],["Der Tee ist von Ali.","الشاي من علي."]],
questions:[
{t:"أي حالة بعد mit؟",ar:"اختر الحالة",opts:["Dativ","Akkusativ","Nominativ"],correct:0,why:"mit تأخذ Dativ دائمًا"},
{t:"أكمل: Ich komme mit ___. (أنت)",ar:"اختر الضمير",opts:["dich","dir","du"],correct:1,why:"بعد mit: Dativ → dir"},
{t:"أكمل: Ich bin bei ___. (أنت)",ar:"اختر الضمير",opts:["dich","dir","du"],correct:1,why:"بعد bei: Dativ → dir"},
{t:"أكمل: Ich komme aus ___. (مصر)",ar:"اختر البلد",opts:["Ägypten","Ägyptens","Ägyptem"],correct:0,why:"أسماء البلاد لا تتغير: aus Ägypten"},
{t:"أي حرف يأخذ Dativ؟",ar:"اختر الحرف",opts:["für","mit","durch"],correct:1,why:"mit من حروف Dativ (für وdurch للأكوزاتيف)"},
{t:"أكمل: Der Tee ist von ___. (علي)",ar:"اختر الاسم",opts:["Ali","Alis","Alim"],correct:0,why:"الأعلام لا تتغير: von Ali"},
{t:"أكمل: Kommst du mit ___؟ (أنا)",ar:"اختر الضمير",opts:["mich","mir","ich"],correct:1,why:"بعد mit: Dativ → mir"},
{t:"أي مجموعة كلها Dativ؟",ar:"اختر المجموعة",opts:["mit – bei – aus","für – durch – gegen","in – an – auf"],correct:0,why:"mit/bei/aus دائمًا Dativ"},
{t:"أكمل: Ich lerne seit ___. (سنة)",ar:"اختر الكلمة",opts:["ein Jahr","einem Jahr","einen Jahr"],correct:1,why:"بعد seit: Dativ → einem Jahr"},
{t:"أي جملة صحيحة؟",ar:"اختر الصحيحة",opts:["Ich komme mit dich.","Ich komme mit dir.","Ich komme mit du."],correct:1,why:"mit + dir (Dativ)"}]},
g31:{intro:"السؤال يبدأ بالفعل المُصرّف ثم الفاعل – والجواب ja أو nein.",
examples:[["Kommst du morgen?","هل تأتي غدًا؟"],["Bist du müde?","هل أنت متعب؟"],["Sprichst du Deutsch?","هل تتحدث الألمانية؟"],["Ja, ich komme.","نعم، آتي."]],
questions:[
{t:"كيف تسأل: هل تتحدث الألمانية؟",ar:"اختر السؤال",opts:["Sprichst du Deutsch?","Du sprichst Deutsch?","Sprechen du Deutsch?"],correct:0,why:"السؤال يبدأ بالفعل: Sprichst du…؟"},
{t:"رتب: du / Kommt / morgen",ar:"رتب السؤال",type:"order",words:["Kommst","du","morgen"],why:"الفعل أولًا: Kommst du morgen؟ (تصريف du)"},
{t:"أي سؤال صحيح؟",ar:"اختر الصحيح",opts:["Bist du müde?","Du bist müde?","Bin du müde?"],correct:0,why:"الفعل المُصرّف أولًا"},
{t:"أي جملة خبرية وليست سؤالًا؟",ar:"اختر الخبرية",opts:["Kommst du?","Du kommst.","Kommen du?"],correct:1,why:"Du kommst. خبرية (الفعل ثانيًا)"},
{t:"تسأل صديقك: هل أنت جائع؟",ar:"اختر السؤال",opts:["Bist du hungrig?","Du bist hungrig?","Bin ich hungrig?"],correct:0,why:"Bist du…؟"},
{t:"إجابة النفي: Nein, ___ komme nicht.",ar:"اختر الضمير",opts:["ich","du","er"],correct:0,why:"المتكلم: Nein, ich komme nicht"},
{t:"أي سؤال خاطئ؟",ar:"اختر الخاطئ",opts:["Sprichst du?","Lernst du?","Du lernst? (كسؤال)"],correct:2,why:"Du lernst? خبرية وليست سؤالًا صحيحًا"},
{t:"رتب: Deutsch / du / Sprichst",ar:"رتب السؤال",type:"order",words:["Sprichst","du","Deutsch"],why:"Sprichst du Deutsch؟"},
{t:"تسألها: هل هي متعبة؟",ar:"اختر السؤال",opts:["Bist du müde?","Ist sie müde?","Bin ich müde?"],correct:1,why:"عنها: Ist sie…؟"},
{t:"جواب Kommt Ali؟ بالإيجاب؟",ar:"اختر الجواب",opts:["Ja, er kommt.","Nein, er kommt.","Ja, ich kommt."],correct:0,why:"Ja + الفاعل + الفعل"}]},
g32:{intro:"Nominativ حالة الفاعل: صورة القاموس der/die/das بدون تغيير.",
examples:[["Der Mann schläft.","الرجل نائم."],["Ein Kind lacht.","طفل يضحك."],["Die Frau kocht.","المرأة تطبخ."],["Das Auto ist rot.","السيارة حمراء."]],
questions:[
{t:"ما حالة الفاعل؟",ar:"اختر الحالة",opts:["Nominativ","Akkusativ","Dativ"],correct:0,why:"الفاعل دائمًا Nominativ"},
{t:"أكمل: ___ Mann schläft.",ar:"اختر الأداة",opts:["Der","Den","Dem"],correct:0,why:"فاعل مذكر: Der"},
{t:"أكمل: ___ Kind lacht.",ar:"اختر الأداة",opts:["Ein","Einen","Einem"],correct:0,why:"فاعل محايد نكرة: Ein"},
{t:"أكمل: ___ Frau kocht.",ar:"اختر الأداة",opts:["Die","Der","Das"],correct:0,why:"فاعل مؤنث: Die"},
{t:"أكمل: ___ Auto ist rot.",ar:"اختر الأداة",opts:["Das","Den","Der"],correct:0,why:"فاعل محايد: Das"},
{t:"أي جملة فاعلها صحيح؟",ar:"اختر الصحيحة",opts:["Den Mann schläft.","Der Mann schläft.","Dem Mann schläft."],correct:1,why:"الفاعل Nominativ: Der"},
{t:"كلمة Bücher في Die Bücher sind neu هي؟",ar:"اختر الحالة",opts:["فاعل Nominativ","مفعول Akkusativ","خطأ"],correct:0,why:"Bücher فاعل الفعل sind"},
{t:"أكمل: ___ Lehrer kommt.",ar:"اختر الأداة",opts:["Der","Den","Dem"],correct:0,why:"فاعل: Der Lehrer"},
{t:"الفرق بين Der Mann و Den Mann؟",ar:"اختر الصحيح",opts:["الأول فاعل والثاني مفعول","كلاهما فاعل","كلاهما مفعول"],correct:0,why:"Der فاعل – Den مفعول"},
{t:"أكمل: ___ Kinder spielen.",ar:"اختر الأداة",opts:["Die","Der","Das"],correct:0,why:"فاعل جمع: Die"}]},
g33:{intro:"أمر الصديق (du): جذر الفعل فقط: Komm! Sprich! Warte!",
examples:[["Komm her!","تعال هنا!"],["Warte kurz!","انتظر قليلًا!"],["Sprich langsam!","تحدث ببطء!"],["Lies das Buch!","اقرأ الكتاب!"]],
questions:[
{t:"آمر صديقًا أن يأتي؟",ar:"اختر الأمر",opts:["Komm!","Kommen Sie!","Du kommst!"],correct:0,why:"أمر du = الجذر: Komm"},
{t:"آمر صديقًا أن ينتظر؟",ar:"اختر الأمر",opts:["Warten Sie!","Warte!","Du wartest!"],correct:1,why:"أمر du: Warte"},
{t:"آمر صديقًا أن يتحدث؟",ar:"اختر الأمر",opts:["Sprich!","Sprechen Sie!","Du sprichst!"],correct:0,why:"sprechen الشاذة: Sprich"},
{t:"آمر صديقًا أن يقرأ؟",ar:"اختر الأمر",opts:["Lesen Sie!","Lies!","Du liest!"],correct:1,why:"lesen الشاذة: Lies"},
{t:"رتب: her / Komm",ar:"رتب الأمر",type:"order",words:["Komm","her"],why:"Komm her! (تعال هنا)"},
{t:"أي أمر لصديق؟",ar:"اختر أمر du",opts:["Kommen Sie!","Mach das Fenster auf!","Du machst das!"],correct:1,why:"Mach = أمر du من machen"},
{t:"آمر صديقًا أن يشرب؟",ar:"اختر الأمر",opts:["Trinken Sie!","Trink!","Du trinkst!"],correct:1,why:"Trink! أمر du"},
{t:"آمر صديقًا أن يذهب؟",ar:"اختر الأمر",opts:["Geh!","Gehen Sie!","Du gehst!"],correct:0,why:"Geh! أمر du من gehen"},
{t:"الفرق بين Komm! و Kommen Sie!؟",ar:"اختر الصحيح",opts:["الأول لصديق والثاني رسمي","كلاهما لصديق","كلاهما رسمي"],correct:0,why:"Komm صديق – Kommen Sie رسمي"},
{t:"آمر صديقًا: خذ الكتاب؟",ar:"اختر الأمر",opts:["Nehmen Sie!","Nimm das Buch!","Du nimmst!"],correct:1,why:"nehmen الشاذة: Nimm"}]},
g34:{intro:"الفعل المنفصل: القطعة تنفصل وتذهب لآخر الجملة.",
examples:[["Ich stehe früh auf.","أستيقظ مبكرًا."],["Ruf mich an!","اتصل بي!"],["Ich kaufe heute ein.","أتسوق اليوم."],["Mach das Fenster auf!","افتح النافذة!"]],
questions:[
{t:"أين تذهب القطعة؟",ar:"اختر الموضع",opts:["آخر الجملة","أول الجملة","تُحذف"],correct:0,why:"القطعة (auf/an/ein) في الآخر"},
{t:"رتب: auf / stehe / Ich / früh",ar:"رتب الجملة",type:"order",words:["Ich","stehe","früh","auf"],why:"الفعل ثانيًا والقطعة آخرًا"},
{t:"أكمل: Ruf mich ___! (اتصل بي)",ar:"اختر القطعة",opts:["an","auf","ein"],correct:0,why:"anrufen تنفصل: ruf…an"},
{t:"أكمل: Ich kaufe heute ___. (أتسوق)",ar:"اختر القطعة",opts:["an","auf","ein"],correct:2,why:"einkaufen تنفصل: kaufe…ein"},
{t:"أكمل: Mach das Fenster ___. (افتح)",ar:"اختر القطعة",opts:["auf","an","ab"],correct:0,why:"aufmachen تنفصل: mach…auf"},
{t:"أي جملة صحيحة؟",ar:"اختر الصحيحة",opts:["Ich aufstehe früh.","Ich stehe früh auf.","Ich stehe auf früh."],correct:1,why:"القطعة في الآخر تمامًا"},
{t:"فعل يتصل anrufen مع ich؟",ar:"اختر التصريف",opts:["Ich rufe an.","Ich anrufe.","Ich ruft an."],correct:0,why:"rufe ثانيًا + an آخرًا (خطأ شائع: anrufe)"},
{t:"رتب: mich / Ruf / an",ar:"رتب الأمر",type:"order",words:["Ruf","mich","an"],why:"Ruf mich an!"},
{t:"أكمل: Steh ___ auf! (استيقظ)",ar:"اختر الكلمة",opts:["früh","früher","frühst"],correct:0,why:"Steh früh auf!"},
{t:"أي فعل منفصل؟",ar:"اختر المنفصل",opts:["lernen","aufstehen","studieren"],correct:1,why:"aufstehen له قطعة auf تنفصل"}]},
g35:{intro:"doch = بلى: رد إيجابي على سؤال منفي.",
examples:[["Du bist nicht müde? — Doch!","ألست متعبًا؟ — بل أنا متعب!"],["Kommst du? — Ja!","هل تأتي؟ — نعم!"],["Lernst du nicht? — Doch!","ألا تتعلم؟ — بل أتعلم!"]],
questions:[
{t:"Du lernst nicht؟ (وأنت تتعلم)",ar:"اختر الرد",opts:["Doch!","Nein!","Tschüs!"],correct:0,why:"تتعلم رغم النفي = Doch (بلى)"},
{t:"Du bist nicht müde؟ (وأنت متعب)",ar:"اختر الرد",opts:["Nein!","Doch!","Vielleicht!"],correct:1,why:"متعب رغم النفي = Doch"},
{t:"Kommst du؟ (وستأتي)",ar:"اختر الرد",opts:["Ja!","Doch!","Nein!"],correct:0,why:"سؤال مثبت → Ja"},
{t:"Kommst du nicht؟ (وستأتي)",ar:"اختر الرد",opts:["Ja!","Nein!","Doch!"],correct:2,why:"سؤال منفي + إيجاب = Doch"},
{t:"Bist du krank؟ (ولست مريضًا)",ar:"اختر الرد",opts:["Ja!","Nein!","Doch!"],correct:1,why:"سؤال مثبت + نفي = Nein"},
{t:"Sprichst du Deutsch؟ (وتتحدث)",ar:"اختر الرد",opts:["Ja!","Doch!","Nein!"],correct:0,why:"مثبت + إيجاب = Ja"},
{t:"معنى Doch؟",ar:"اختر المعنى",opts:["لا","بلى (إيجاب بعد نفي)","ربما"],correct:1,why:"Doch = بلى"},
{t:"Trinkst du keinen Tee؟ (وتشرب)",ar:"اختر الرد",opts:["Nein!","Doch!","Ja!"],correct:1,why:"منفي + إيجاب = Doch"},
{t:"أي رد خاطئ على Lernst du؟ (وأنت تتعلم)",ar:"اختر الخاطئ",opts:["Ja!","Doch!","Nein!"],correct:2,why:"Nein خطأ لأنك تتعلم فعلًا"},
{t:"Gehst du nicht؟ (ولن تذهب)",ar:"اختر الرد",opts:["Doch!","Nein!","Ja!"],correct:1,why:"منفي + نفي = Nein"}]},
g36:{intro:"nach للاتجاه – in للمكان – aus للأصل – mit للصحبة – für للغرض.",
examples:[["Ich fahre nach Berlin.","أسافر إلى برلين."],["Ich wohne in Kairo.","أسكن في القاهرة."],["Ich komme aus Ägypten.","أنا من مصر."],["Ich lerne mit Ali.","أتعلم مع علي."]],
questions:[
{t:"أكمل: Ich fahre ___ Berlin.",ar:"اختر الحرف",opts:["nach","in","aus"],correct:0,why:"الاتجاه لمدينة: nach"},
{t:"أكمل: Ich wohne ___ Kairo.",ar:"اختر الحرف",opts:["nach","in","aus"],correct:1,why:"السكن (مكان): in"},
{t:"أكمل: Ich komme ___ Ägypten.",ar:"اختر الحرف",opts:["nach","in","aus"],correct:2,why:"الأصل: aus"},
{t:"أكمل: Ich lerne ___ Ali.",ar:"اختر الحرف",opts:["mit","nach","für"],correct:0,why:"الصحبة: mit"},
{t:"أكمل: Das ist ___ dich. (من أجلك)",ar:"اختر الحرف",opts:["mit","für","aus"],correct:1,why:"الغرض: für"},
{t:"أي جملة صحيحة؟",ar:"اختر الصحيحة",opts:["Ich fahre in Berlin.","Ich fahre nach Berlin.","Ich fahre aus Berlin."],correct:1,why:"اتجاه: nach Berlin"},
{t:"أي جملة صحيحة؟",ar:"اختر الصحيحة",opts:["Ich wohne nach Kairo.","Ich wohne in Kairo.","Ich wohne aus Kairo."],correct:1,why:"مكان: in Kairo"},
{t:"تسأل عن الوجهة: ___ fährst du؟",ar:"اختر الأداة",opts:["Wohin","Woher","Wo"],correct:0,why:"الاتجاه = Wohin (إلى أين)"},
{t:"تسأل عن الأصل: ___ kommst du؟",ar:"اختر الأداة",opts:["Wohin","Woher","Wo"],correct:1,why:"الأصل = Woher (من أين)"},
{t:"أكمل: Tee ___ Zucker, bitte. (مع سكر)",ar:"اختر الحرف",opts:["mit","nach","für"],correct:0,why:"مع = mit"}]},
g37:{intro:"الساعة بـ um – اليوم بـ am – التاريخ: der + رقم + شهر.",
examples:[["Der Termin ist um 9 Uhr.","الموعد التاسعة."],["Heute ist Montag.","اليوم الاثنين."],["Am Freitag habe ich Zeit.","الجمعة لدي وقت."],["Der Test ist am 3. Mai.","الاختبار 3 مايو."]],
questions:[
{t:"أكمل: ___ Freitag habe ich Zeit.",ar:"اختر الحرف",opts:["Am","Um","Im"],correct:0,why:"اليوم مع am"},
{t:"أكمل: Der Termin ist ___ 9 Uhr.",ar:"اختر الحرف",opts:["am","um","im"],correct:1,why:"الساعة مع um"},
{t:"أكمل: Der Test ist am 3. ___. (مايو)",ar:"اختر الشهر",opts:["Mai","Montag","Morgen"],correct:0,why:"التاريخ: 3. Mai"},
{t:"رتب: 9 / ist / Termin / um / Der / Uhr",ar:"رتب الجملة",type:"order",words:["Der","Termin","ist","um","9","Uhr"],why:"Der Termin ist um 9 Uhr"},
{t:"أي جملة صحيحة؟",ar:"اختر الصحيحة",opts:["Der Termin ist am 9 Uhr.","Der Termin ist um 9 Uhr.","Der Termin ist im 9 Uhr."],correct:1,why:"الساعة مع um"},
{t:"Heute ist ___ . (الاثنين)",ar:"اختر اليوم",opts:["Montag","Mai","Morgen"],correct:0,why:"Heute ist Montag"},
{t:"أكمل: ___ Mai beginnt der Kurs.",ar:"اختر الحرف",opts:["Am","Um","Im"],correct:2,why:"الشهر مع im (ولو في تاريخ يبقى الشهر)"},
{t:"أي تاريخ صحيح؟",ar:"اختر الصحيح",opts:["am 3. Mai","um 3. Mai","im 3. Mai"],correct:0,why:"اليوم-التاريخ مع am"},
{t:"Wann ist der Test؟ الإجابة؟",ar:"اختر الإجابة",opts:["Am Freitag.","Um Freitag.","Im Freitag."],correct:0,why:"اليوم مع am"},
{t:"Um wie viel Uhr؟ تسأل عن؟",ar:"اختر الموضوع",opts:["الساعة","اليوم","الشهر"],correct:0,why:"Uhr = الساعة"}]},
g38:{intro:"الأرقام 0-12 تُحفظ – ثم التركيب معكوسًا: 21 = einundzwanzig.",
examples:[["Ich bin zwanzig Jahre alt.","عمري عشرون."],["Das kostet fünf Euro.","سعره خمسة يورو."],["Er ist einundzwanzig.","عمره 21."],["Wir sind drei Personen.","نحن 3 أشخاص."]],
questions:[
{t:"كيف أقول 24؟",ar:"اختر الرقم",opts:["vierundzwanzig","zwanzigvier","vierzigzwei"],correct:0,why:"الآحاد أولًا: vier-und-zwanzig"},
{t:"كيف أقول 21؟",ar:"اختر الرقم",opts:["zwanzigeins","einundzwanzig","einszwanzig"],correct:1,why:"ein-und-zwanzig"},
{t:"كيف أقول 13؟",ar:"اختر الرقم",opts:["dreizehn","dreiundzehn","zehntdrei"],correct:0,why:"13 = dreizehn (شاذة قليلًا)"},
{t:"كيف أقول 30؟",ar:"اختر الرقم",opts:["dreizig","dreißig","dreizich"],correct:1,why:"30 = dreißig (ß!)"},
{t:"كيف أقول 100؟",ar:"اختر الرقم",opts:["hundert","einhundert","hunderte"],correct:0,why:"100 = (ein)hundert"},
{t:"عمري 15: Ich bin ___ Jahre alt.",ar:"اختر الرقم",opts:["fünfzehn","fünfzig","fünften"],correct:0,why:"15 = fünfzehn"},
{t:"سعره 50 يورو: ___ Euro.",ar:"اختر الرقم",opts:["fünfzehn","fünfzig","fünf"],correct:1,why:"50 = fünfzig"},
{t:"نحن 3 أشخاص: ___ Personen.",ar:"اختر الرقم",opts:["drei","dreier","dritt"],correct:0,why:"3 = drei"},
{t:"كيف أقول 12؟",ar:"اختر الرقم",opts:["zwölf","zwelf","zölf"],correct:0,why:"12 = zwölf"},
{t:"أي تركيب خاطئ؟",ar:"اختر الخاطئ",opts:["vierundzwanzig","einundzwanzig","zwanzigvier"],correct:2,why:"zwanzigvier خطأ — الآحاد أولًا دائمًا"}]},
g39:{intro:"تُنطق كما تُكتب غالبًا: sch = ش – sp = شب – ch بعد a/o/u مفخمة.",
examples:[["Die Schule ist groß.","المدرسة كبيرة."],["Ich buchstabiere meinen Namen.","أتهجى اسمي."],["Er spricht Deutsch.","هو يتحدث الألمانية."],["Das Buch ist dick.","الكتاب سميك."]],
questions:[
{t:"كيف تُنطق sch؟",ar:"اختر النطق",opts:["ش","س","ك"],correct:0,why:"sch = ش (Schule)"},
{t:"كيف تُنطق sp أول الكلمة؟",ar:"اختر النطق",opts:["سب","شب","س"],correct:1,why:"sp = شب (spielt)"},
{t:"كيف تُنطق ch في Buch؟",ar:"اختر النطق",opts:["ش","خ مفخمة","ك"],correct:1,why:"بعد u/o/a مفخمة (خ)"},
{t:"كيف تُنطق ch في ich؟",ar:"اختر النطق",opts:["خ مفخمة","ش خفيفة (كالشين)","ك"],correct:1,why:"بعد i/e مرققة"},
{t:"أي كلمة فيها sch؟",ar:"اختر الكلمة",opts:["Schule","Tisch","Haus"],correct:0,why:"Schule تبدأ بـ sch"},
{t:"رتب حروف: S / c / h / u / l / e",ar:"رتب الكلمة",type:"order",words:["S","c","h","u","l","e"],why:"S-c-h-u-l-e = Schule"},
{t:"كيف تُنطق z في Zeit؟",ar:"اختر النطق",opts:["ز","تس","س"],correct:1,why:"z = تس (Zeit)"},
{t:"كيف تُنطق w في Wasser؟",ar:"اختر النطق",opts:["و","ف (v)","ب"],correct:1,why:"w تُنطق v (Vasser)"},
{t:"كيف تُنطق j في Jahr؟",ar:"اختر النطق",opts:["ج","ي","هـ"],correct:1,why:"j = ي (Yahr)"},
{t:"أي كلمة نطقها يبدأ بـ ش؟",ar:"اختر الكلمة",opts:["Schule","Sprache","Buch"],correct:0,why:"Schule = شوله"}]},
g40:{intro:"können قدرة – müssen وجوب – wollen رغبة – möchten تأدب. المساعد ثانيًا + المصدر آخرًا.",
examples:[["Kannst du mir helfen?","هل يمكنك مساعدتي؟"],["Ich muss morgen arbeiten.","يجب أن أعمل غدًا."],["Ich möchte einen Kaffee.","أريد قهوة (بأدب)."],["Willst du Tee?","هل تريد شايًا؟"]],
questions:[
{t:"أكمل بأدب: Ich ___ einen Kaffee.",ar:"اختر الفعل",opts:["möchte","will","muss"],correct:0,why:"الطلب المهذب بـ möchte"},
{t:"أكمل: ___ du mir helfen؟ (هل تستطيع)",ar:"اختر الفعل",opts:["Kannst","Können","Kannt"],correct:0,why:"du + kannst"},
{t:"أكمل: Ich ___ morgen arbeiten. (يجب)",ar:"اختر الفعل",opts:["muss","musst","müssen"],correct:0,why:"Ich + muss"},
{t:"رتب: Kaffee / Ich / einen / möchte",ar:"رتب الجملة",type:"order",words:["Ich","möchte","einen","Kaffee"],why:"المساعد ثانيًا + المفعول"},
{t:"الفرق بين will و möchte؟",ar:"اختر الصحيح",opts:["will رغبة قوية وmöchte طلب مهذب","كلاهما وجوب","كلاهما ماضٍ"],correct:0,why:"möchte ألطف من will"},
{t:"أكمل: Er ___ gut schwimmen. (يستطيع)",ar:"اختر الفعل",opts:["kann","können","kannt"],correct:0,why:"Er + kann"},
{t:"أكمل: Wir ___ Deutsch lernen. (نريد)",ar:"اختر الفعل",opts:["will","wollen","wollt"],correct:1,why:"Wir + wollen"},
{t:"أكمل: Du ___ nicht rauchen. (يجب ألا)",ar:"اختر الفعل",opts:["muss","musst","darfst"],correct:1,why:"Du + musst (النهي بـ müssen)"},
{t:"أي جملة مهذبة في مطعم؟",ar:"اختر المهذبة",opts:["Ich will Wasser!","Ich möchte Wasser.","Du musst Wasser!"],correct:1,why:"möchte للطلب المهذب"},
{t:"أكمل: ___ Sie mir helfen؟ (رسمي)",ar:"اختر الفعل",opts:["Kann","Können","Kannst"],correct:1,why:"Sie + können (الجمع/الرسمي)"}]}
};
