/* Deutsch Master — Reference data: path E (Adjektive) + path F (Verben). Pure data. */
"use strict";
var REF_E=[
{id:"e-grundlagen",level:"A1",de:"Adjektivgebrauch",ar:"استخدام الصفة",en:"Using adjectives",
 what:"الصفة تصف الاسم. بعد sein/werden تبقى ثابتة (Das Auto ist groß)، وقبل الاسم تأخذ نهاية (ein großes Haus). التصريف الكامل في e-deklination.",
 rule:"Prädikativ (بعد sein): بدون نهاية. Attributiv (قبل الاسم): بنهاية حسب الأداة والجنس والحالة.",
 keywords:["Adjektiv","صفة","groß","gut","schön","attributiv","prädikativ"],
 tables:[{cap:"الصفة بعد sein مقابل قبل الاسم",head:["بعد sein (ثابتة)","قبل الاسم (بنهاية)","مثال"],rows:[["groß","große-","Das Auto ist groß. / das große Auto"],["neu","neue-","Die Tasche ist neu. / eine neue Tasche"],["gut","gute-","Der Kaffee ist gut. / ein guter Kaffee"]]}],
 examples:[["Das Auto ist groß.","السيارة كبيرة."],["Ich habe ein großes Haus.","لديّ بيت كبير."],["Die Suppe ist heiß.","الشوربة ساخنة."]],
 notes:["صفات شائعة: groß, klein, neu, alt, gut, schlecht, schön, schnell, teuer, billig, wichtig.","الصفة قبل الاسم بدون أداة لها نهايات أخرى (B1)."],
 mistakes:[{w:"das große Auto ist groß.",r:"Das große Auto ist groß.",why:"بداية الجملة كبيرة دائما."}],
 related:["e-steigerung","b-nomen-genus","d-nominativ"],
 quiz:[{q:"Das Auto ist ___. (كبير، بعد sein)",opts:["groß","großes","große"],correct:0,why:"بعد sein الصفة ثابتة."},{q:"Ich habe ein ___ Haus. (محايد، نكرة)",opts:["groß","großes","großer"],correct:1,why:"ein + محايد في Nominativ: großes."}]},
{id:"e-steigerung",level:"A2",de:"Steigerung",ar:"درجات المقارنة (Komparativ / Superlativ)",en:"Comparison of adjectives",
 what:"للمقارنة بين شيئين نستخدم Komparativ (أفعل من)، وللتفضيل المطلق Superlativ (الأفعل).",
 rule:"Komparativ = الصفة + er (غالبا مع Umlaut للقصيرة). Superlativ = am + الصفة + sten. كلمات شاذة تُحفظ: gut/besser/am besten.",
 keywords:["Komparativ","Superlativ","Steigerung","besser","größer","مقارنة","als","am besten"],
 tables:[{cap:"Steigerung",head:["Positiv","Komparativ (-er)","Superlativ (am -sten)"],rows:[["schnell","schneller","am schnellsten"],["groß","größer","am größten"],["gut","besser","am besten"],["viel","mehr","am meisten"],["gern","lieber","am liebsten"]]}],
 examples:[["Mein Auto ist schneller als deins.","سيارتي أسرع من سيارتك."],["Er ist der beste Schüler.","هو أفضل تلميذ."],["Ich trinke gern Tee, lieber Kaffee.","أحب الشاي، وأفضل القهوة."]],
 notes:["المقارنة بـ als (وليس wie): größer als.","gern/lieber/am liebsten أفعال تفضيل شائعة جدا."],
 mistakes:[{w:"größer wie",r:"größer als",why:"المقارنة بـ als."}],
 related:["e-grundlagen","k-quantitaet"],
 quiz:[{q:"Komparativ von gut؟",opts:["guter","besser","best"],correct:1,why:"gut → besser (شاذة)."} ,{q:"Mein Auto ist schneller ___ deins.",opts:["wie","als","denn"],correct:1,why:"المقارنة بـ als."}]},
{id:"e-deklination",level:"B1",de:"Adjektivdeklination",ar:"تصريف الصفة (متقدم)",en:"Adjective endings (advanced)",
 what:"نهايات الصفة قبل الاسم حسب الأداة والجنس والحالة. مستوى B1 — للرجوع إليه لاحقا، ويكفي A1 الأساس في e-grundlagen.",
 rule:"بعد der-Wörter: النهاية e/en فقط. بعد ein-Wörter: تمييز الجنس في Nominativ/Akkusativ. بدون أداة: نهايات الأدوات نفسها.",
 keywords:["Deklination","Adjektivendungen","تصريف الصفة","guter","guten"],
 tables:[{cap:"بعد أداة التعريف (der/die/das)",head:["","maskulin","feminin","neutral","Plural"],rows:[["Nominativ","gute","gute","gute","guten"],["Akkusativ","guten","gute","gute","guten"],["Dativ","guten","guten","guten","guten"]]},{cap:"بعد أداة النكرة (ein)",head:["","maskulin","feminin","neutral"],rows:[["Nominativ","guter","gute","gutes"],["Akkusativ","guten","gute","gutes"],["Dativ","guten","guten","guten"]]}],
 examples:[["Der gute Mann hilft mir.","الرجل الطيب يساعدني."],["Ich trinke einen starken Kaffee.","أشرب قهوة قوية."],["Mit guten Freunden lernt man schnell.","مع الأصدقاء الطيبين يتعلم المرء بسرعة."]],
 notes:["القاعدة الذهبية: النهاية المميزة (r/m/n/s) تظهر مرة واحدة فقط في المجموعة.","A1/A2 يكفي: الصفة بعد sein ثابتة + großes/e مع النكرة."],
 mistakes:[{w:"ein guter Kaffee (كمفعول)",r:"einen starken Kaffee",why:"Akkusativ مذكر: en."}],
 related:["e-grundlagen","d-akkusativ","d-dativ"],
 quiz:[{q:"Der ___ Mann hilft. (فاعل، معرفة)",opts:["gute","guter","guten"],correct:0,why:"بعد der في Nominativ: e."},{q:"Mit ___ Freunden. (جمع، Dativ)",opts:["gute","guten","guter"],correct:1,why:"Dativ الجمع: en."}]}
];
var REF_F=[
{id:"f-grundlagen",level:"A1",de:"Konjugation im Präsens",ar:"تصريف الأفعال في الحاضر",en:"Present-tense conjugation",
 what:"الفعل يتكون من الجذر + النهاية: Infinitiv (lernen) = الجذر (lern) + en. كل ضمير له نهاية ثابتة في الأفعال المنتظمة.",
 rule:"النهايات: ich-e, du-st, er-t, wir-en, ihr-t, sie-en. الأفعال الشاذة تغيّر حرف العلة مع du/er (sprechen → du sprichst).",
 keywords:["Präsens","Konjugation","تصريف","Infinitiv","Verbstamm","lernen","sprechen"],
 tables:[{cap:"نهايات Präsens (منتظم)",head:["ich","du","er/sie/es","wir","ihr","sie/Sie"],rows:[["lern-e","lern-st","lern-t","lern-en","lern-t","lern-en"]]},{cap:"شاذ: sprechen",head:["ich","du","er","wir","ihr","sie"],rows:[["spreche","sprichst","spricht","sprechen","sprecht","sprechen"]]}],
 examples:[["Ich lerne Deutsch.","أنا أتعلم الألمانية."],["Du sprichst gut Deutsch.","أنت تتحدث الألمانية جيدًا."],["Wir wohnen in Kairo.","نحن نسكن في القاهرة."]],
 notes:["احفظ مع كل فعل: هل هو منتظم أم شاذ؟","الضمير أساس النهاية (انظر c-personal)."],
 mistakes:[{w:"Du lernt",r:"Du lernst",why:"du تأخذ st."}],
 related:["c-personal","g-praesens","f-arten"],
 quiz:[{q:"du + lernen = ؟",opts:["lernt","lernst","lerne"],correct:1,why:"du + st."},{q:"du + sprechen = ؟",opts:["sprichst","sprechst","spricht"],correct:0,why:"شاذ: e → i مع du."}]},
{id:"f-arten",level:"A2",de:"Verbarten",ar:"أنواع الأفعال",en:"Verb types",
 what:"الأفعال المنتظمة (schwach) تحافظ على جذرها، والقوية (stark) تغيّر حرف العلة، والمختلطة تجمع بينهما.",
 rule:"schwach: spielen → spielte → gespielt. stark: sprechen → sprach → gesprochen (تُحفظ). gemischt: bringen → brachte → gebracht.",
 keywords:["regelmäßig","unregelmäßig","stark","schwach","gemischt","منتظم","شاذ","Partizip"],
 tables:[{cap:"الأنواع الثلاثة",head:["النوع","الحاضر","الماضي","Partizip II"],rows:[["schwach (منتظم)","spielen","spielte","gespielt"],["stark (قوي)","sprechen","sprach","gesprochen"],["gemischt","bringen","brachte","gebracht"]]}],
 examples:[["Er spielt Fußball.","هو يلعب كرة القدم."],["Sie spricht drei Sprachen.","هي تتحدث ثلاث لغات."],["Ich bringe das Buch mit.","أحضر الكتاب معي."]],
 notes:["القاموس يرمز للقوي بـ (spricht, sprach, gesprochen).","الماضي الكامل في g-perfekt و g-partizip2."],
 mistakes:[{w:"gesprecht",r:"gesprochen",why:"sprechen قوي: Partizip II شاذ."}],
 related:["f-grundlagen","g-partizip2","g-praeteritum"],
 quiz:[{q:"Partizip II من sprechen؟",opts:["gesprecht","gesprochen","gespracht"],correct:1,why:"فعل قوي شاذ."},{q:"spielen فعل…",opts:["قوي","ضعيف (منتظم)","مختلط"],correct:1,why:"spielte/gespielt بلا تغيير علة."}]},
{id:"f-modal",level:"A1",de:"Modalverben",ar:"الأفعال الناقصة",en:"Modal verbs",
 what:"أفعال تغيّر معنى الفعل الرئيسي: القدرة، الوجوب، الرغبة. الفعل الناقص مُصرَّف في المرتبة الثانية + المصدر في نهاية الجملة.",
 rule:"können, müssen, wollen, sollen, dürfen, mögen + möchten (صيغة خاصة من mögen للطلب المهذب).",
 keywords:["Modalverben","können","müssen","wollen","sollen","dürfen","mögen","möchten","ناقصة"],
 tables:[{cap:"Modalverben — ich/er (الأهم)",head:["الفعل","ich","er","المعنى"],rows:[["können","kann","kann","يستطيع"],["müssen","muss","muss","يجب"],["wollen","will","will","يريد"],["sollen","soll","soll","ينبغي"],["dürfen","darf","darf","يُسمح"],["mögen","mag","mag","يحب"],["möchten","möchte","möchte","يريد (مهذب)"]]}],
 examples:[["Ich muss lernen.","يجب أن أتعلم."],["Kannst du mir helfen?","هل يمكنك مساعدتي؟"],["Ich möchte einen Kaffee.","أريد قهوة (بتهذيب)."]],
 notes:["möchten تُستخدم أكثر من wollen في الطلبات اليومية.","الفعل الرئيسي في النهاية بصيغة المصدر."],
 mistakes:[{w:"Ich muss lerne.",r:"Ich muss lernen.",why:"الفعل الرئيسي في المصدر."}],
 related:["m-verbstellung","i-fragen","o-situationen"],
 quiz:[{q:"Ich ___ lernen. (يجب)",opts:["muss","müsse","musst"],correct:0,why:"ich muss (شاذة بلا نهاية)."} ,{q:"أين الفعل الرئيسي مع الناقص؟",opts:["المرتبة 2","نهاية الجملة (مصدر)","البداية"],correct:1,why:"الناقص في 2 + المصدر في النهاية."}]},
{id:"f-trennbar",level:"A1",de:"Trennbare Verben",ar:"الأفعال المنفصلة",en:"Separable verbs",
 what:"أفعال بمقطع أمامي ينفصل في الجملة الرئيسية ويذهب لنهايتها: aufstehen → Ich stehe früh auf.",
 rule:"Hauptsatz: المقطع في النهاية. Nebensatz وInfinitiv: يلتصق (aufzustehen). Partizip II: المقطع + ge بينهما (aufgestanden).",
 keywords:["trennbar","منفصلة","aufstehen","einkaufen","anrufen","Präfix"],
 tables:[{cap:"أفعال منفصلة شائعة",head:["الفعل","المعنى","مثال"],rows:[["aufstehen","يستيقظ","Ich stehe früh auf."],["einkaufen","يتسوق","Ich kaufe heute ein."],["anrufen","يتصل","Ruf mich an!"],["mitkommen","يأتي مع","Kommst du mit?"]]}],
 examples:[["Ich stehe um 6 Uhr auf.","أستيقظ السادسة."],["Wir kaufen am Samstag ein.","نتسوق يوم السبت."]],
 notes:["مقاطع شائعة: auf, an, ein, mit, zu, vor, nach.","عكسها تماما في f-untrennbar."],
 mistakes:[{w:"Ich aufstehe früh.",r:"Ich stehe früh auf.",why:"المقطع ينفصل لنهاية الجملة."}],
 related:["f-untrennbar","g-partizip2","m-verbstellung"],
 quiz:[{q:"Ich ___ früh ___. (aufstehen)",opts:["stehe … auf","aufstehe … —","auf … stehe"],correct:0,why:"الجذر في 2 + المقطع في النهاية."}]},
{id:"f-untrennbar",level:"A2",de:"Untrennbare Verben",ar:"الأفعال غير المنفصلة",en:"Inseparable verbs",
 what:"مقاطع لا تنفصل أبدا: be, ge, emp, ent, er, ver, zer. وفي Partizip II لا تأخذ ge: verstehen → verstanden.",
 rule:"إذا بدأ الفعل بأحد هذه المقاطع فهو ملتصق دائما والنبرة على الجذر.",
 keywords:["untrennbar","verstehen","besuchen","bekommen","erzählen","ge-"],
 tables:[{cap:"أفعال غير منفصلة شائعة",head:["الفعل","المعنى","Partizip II"],rows:[["besuchen","يزور","besucht"],["verstehen","يفهم","verstanden"],["bekommen","يحصل على","bekommen"],["erzählen","يحكي","erzählt"]]}],
 examples:[["Ich besuche meine Oma.","أزور جدتي."],["Ich verstehe das nicht.","لا أفهم هذا."]],
 notes:["bekommen = يحصل على (وليس become الإنجليزية!).","durch/über/um قد تكون منفصلة أو لا حسب المعنى (B1)."],
 mistakes:[{w:"gebesucht",r:"besucht",why:"غير المنفصل لا يأخذ ge."}],
 related:["f-trennbar","g-partizip2"],
 quiz:[{q:"Partizip II من verstehen؟",opts:["geverstanden","verstanden","versteht"],correct:1,why:"بلا ge."},{q:"bekommen تعني…",opts:["يصبح","يحصل على","يأتي"],correct:1,why:"false friend شهير."}]},
{id:"f-shw",level:"A1",de:"sein / haben / werden",ar:"الأفعال الثلاثة الكبرى",en:"sein, haben, werden",
 what:"أهم ثلاثة أفعال: sein للهوية والمكان والحالة، haben للملكية، werden للمستقبل والتغير (والمبني للمجهول B1).",
 rule:"تصريفها شاذ ويُحفظ. sein + الصفة/الاسم، haben + Akkusativ.",
 keywords:["sein","haben","werden","bin","bist","ist","habe","hast","hat","werde","يكون","يمتلك"],
 tables:[{cap:"sein — يكون",head:["ich","du","er","wir","ihr","sie"],rows:[["bin","bist","ist","sind","seid","sind"]]},{cap:"haben — يمتلك",head:["ich","du","er","wir","ihr","sie"],rows:[["habe","hast","hat","haben","habt","haben"]]},{cap:"werden — يصبح/سوف",head:["ich","du","er","wir","ihr","sie"],rows:[["werde","wirst","wird","werden","werdet","werden"]]}],
 examples:[["Ich bin Schüler.","أنا تلميذ."],["Er hat ein Auto.","لديه سيارة."],["Es wird kalt.","الجو يبرد."]],
 notes:["haben + Akkusativ: Ich habe einen Hund.","werden + Infinitiv = المستقبل (g-futur1)."],
 mistakes:[{w:"Ich bin ein Auto.",r:"Ich habe ein Auto.",why:"الملكية مع haben لا sein."}],
 related:["f-grundlagen","g-futur1","g-perfekt"],
 quiz:[{q:"du + sein = ؟",opts:["bist","bin","seid"],correct:0,why:"du bist."},{q:"Er ___ ein Auto. (ملكية)",opts:["ist","hat","wird"],correct:1,why:"الملكية haben."}]},
{id:"f-dativ-verben",level:"A1",de:"Verben mit Dativ",ar:"أفعال تأخذ Dativ",en:"Verbs with dative",
 what:"أفعال مفعولها في Dativ وليس Akkusativ — أشهرها helfen. تُحفظ مع الفعل.",
 rule:"helfen, danken, gehören, gefallen, antworten, gratulieren + Dativ دائما.",
 keywords:["helfen","danken","gehören","gefallen","Dativ","أفعال"],
 tables:[{cap:"أفعال Dativ",head:["الفعل","المعنى","مثال"],rows:[["helfen","يساعد","Er hilft mir."],["danken","يشكر","Ich danke dir."],["gefallen","يعجب","Das gefällt mir."],["gehören","يخص/يملك","Das gehört mir."]]}],
 examples:[["Er hilft mir jeden Tag.","يساعدني كل يوم."],["Das Kleid gefällt mir.","الفستان يعجبني."]],
 notes:["gefallen عكس المنطق العربي: الشيء فاعل وأنت Dativ.","القائمة الكاملة تُحفظ تدريجيًا مع القراءة."],
 mistakes:[{w:"Das gefällt mich.",r:"Das gefällt mir.",why:"gefallen + Dativ."}],
 related:["d-dativ","f-akkusativ-verben"],
 quiz:[{q:"Sie hilft ___. (لي)",opts:["mich","mir","mein"],correct:1,why:"helfen + Dativ."},{q:"Das gehört ___. (لي)",opts:["mich","mir","mein"],correct:1,why:"gehören + Dativ."}]},
{id:"f-akkusativ-verben",level:"A1",de:"Verben mit Akkusativ",ar:"أفعال تأخذ Akkusativ",en:"Verbs with accusative",
 what:"معظم الأفعال المتعدية مفعولها Akkusativ: sehen, haben, brauchen, kaufen, lesen, besuchen.",
 rule:"اسأل Wen/Was؟ بعد الفعل. القاعدة الافتراضية ما لم يُذكر أن الفعل Dativ.",
 keywords:["Akkusativ","sehen","brauchen","kaufen","lesen","مفعول"],
 tables:[{cap:"أفعال Akkusativ",head:["الفعل","المعنى","مثال"],rows:[["sehen","يرى","Ich sehe dich."],["brauchen","يحتاج","Ich brauche Hilfe."],["besuchen","يزور","Wir besuchen Oma."],["kennen","يعرف","Ich kenne ihn."]]}],
 examples:[["Ich brauche deine Hilfe.","أحتاج مساعدتك."],["Kennst du diesen Film?","هل تعرف هذا الفيلم؟"]],
 notes:["kennen (يعرف شخصًا/شيئًا) ≠ wissen (يعرف معلومة) — انظر p-fehler.","besuchen للأشخاص والأماكن، لا تخلط مع sehen."],
 mistakes:[{w:"Ich besuche dir.",r:"Ich besuche dich.",why:"besuchen + Akkusativ."}],
 related:["d-akkusativ","f-dativ-verben"],
 quiz:[{q:"Ich besuche ___. (أنت)",opts:["dir","dich","du"],correct:1,why:"besuchen + Akkusativ."}]}
];
