/* Deutsch Master — Reference data: path B (Nomen & Artikel) + path C (Pronomen).
   Pure data. Schema: {id,level,de,ar,en,what,rule,keywords,tables,examples,notes,mistakes,related,explain,quiz}.
   Quiz gate enforced at render (refValidQuiz) + tools/check-reference.js. */
"use strict";
var REF_B=[
{id:"b-nomen-genus",level:"A1",de:"Genus des Nomens",ar:"جنس الاسم (مذكر / مؤنث / محايد)",en:"Grammatical gender",
 what:"كل اسم ألماني له جنس ثابت: مذكر يأخذ der، مؤنث يأخذ die، محايد يأخذ das. الأداة جزء من الكلمة وتحفظ معها دائما.",
 rule:"لا توجد قاعدة منطقية شاملة، لكن النهايات تساعد: ung/heit/keit/schaft ← die غالبا، chen/lein ← das غالبا، er للمهن ← der غالبا.",
 keywords:["Genus","جنس","der","die","das","Nomen","اسم"],
 tables:[{cap:"أنماط النهايات المساعدة",head:["النهاية","غالبا","مثال"],rows:[["-ung, -heit, -keit, -schaft","die (مؤنث)","die Zeitung"],["-chen, -lein","das (محايد)","das Mädchen"],["-er (مهن)","der (مذكر)","der Lehrer"],["غير ذلك","يُحفظ","der Tisch / die Tasche / das Buch"]]}],
 examples:[["Der Tisch ist groß.","الطاولة كبيرة."],["Die Lampe ist neu.","المصباح جديد."],["Das Buch ist interessant.","الكتاب شيّق."]],
 notes:["احفظ كل اسم مع أداته: der Freund وليس Freund فقط.","أداة الجمع القياسية die دائما مهما كانت أداة المفرد."],
 mistakes:[{w:"das Tasche",r:"die Tasche",why:"Tasche مؤنثة ثابتة — لا تخمن من المعنى العربي."},{w:"Tisch ist groß.",r:"Der Tisch ist groß.",why:"الاسم المفرد يحتاج أداته."}],
 related:["b-artikel-bestimmt","b-nomen-plural","d-nominativ"],explain:"g1",
 quiz:[{q:"ما أداة Tasche؟",opts:["der","die","das"],correct:1,why:"Tasche مؤنثة ثابتة."},{q:"كلمات تنتهي بـ -ung غالبا…",opts:["مذكرة (der)","مؤنثة (die)","محايدة (das)"],correct:1,why:"مثل die Zeitung."}]},
{id:"b-nomen-plural",level:"A1",de:"Plural des Nomens",ar:"جمع الأسماء",en:"Noun plurals",
 what:"للجمع عدة نهايات (e/er/n/en/s وتغيّر Umlaut أحيانا) ولا توجد قاعدة واحدة، لذلك يُحفظ الجمع مع كل اسم.",
 rule:"احفظ كل اسم هكذا: der Tisch → die Tische. الكلمات الأجنبية الحديثة غالبا +s.",
 keywords:["Plural","جمع","Tische","Bücher","Kinder"],
 tables:[{cap:"أشهر أنماط الجمع",head:["المفرد","الجمع","ملاحظة"],rows:[["der Tisch","die Tische","e+"],["das Buch","die Bücher","Umlaut + er"],["die Tasche","die Taschen","n+"],["der Lehrer","die Lehrer","بدون تغيير"],["das Taxi","die Taxis","كلمات أجنبية +s"]]}],
 examples:[["Die Kinder sind hier.","الأطفال هنا."],["Zwei Brötchen, bitte.","خبزتان صغيرتان من فضلك."],["Die Äpfel sind frisch.","التفاح طازج."]],
 notes:["بعض الكلمات جمعها = مفردها: das Fenster → die Fenster.","القاعدة القياسية: الجمع بـ die دائما."],
 mistakes:[{w:"die Buchs",r:"die Bücher",why:"الجمع لا يُخترع بإضافة s دائما."}],
 related:["b-nomen-genus","d-nominativ"],explain:"g2",
 quiz:[{q:"ما جمع das Kind؟",opts:["die Kinder","die Kindes","die Kinden"],correct:0,why:"Kind جمعها Kinder — تُحفظ."},{q:"أداة الجمع القياسية…",opts:["der","die","das"],correct:1,why:"الجمع بـ die دائما."}]},
{id:"b-nomen-gross",level:"A1",de:"Großschreibung & Komposita",ar:"الحرف الكبير والكلمات المركبة",en:"Capitalization & compounds",
 what:"كل اسم ألماني يُكتب بحرف كبير دائما حتى في وسط الجملة، وضمير حضرتك Sie كبير دائما. والكلمات المركبة كلمة واحدة جنسها من آخر جزء.",
 rule:"اسم ← كبير. بداية الجملة ← كبيرة. Sie الرسمية ← كبيرة. المركبة: جنس آخر مقطع هو جنس الكلمة.",
 keywords:["Großschreibung","حرف كبير","Komposita","مركبة","Sie"],
 tables:[{cap:"الكلمات المركبة",head:["الجزء 1","الجزء 2","المركبة","الجنس"],rows:[["die Hand","der Schuh","der Handschuh","مذكر (آخر جزء)"],["das Taschen","das Tuch","das Taschentuch","محايد (آخر جزء)"]]}],
 examples:[["Ich lerne Deutsch.","أنا أتعلم الألمانية."],["Können Sie mir helfen?","هل يمكنك مساعدتي؟ (رسمي)"]],
 notes:["sie الصغيرة (هي/هم) ≠ Sie الكبيرة (حضرتك).","اللغات كأسماء تُكتب كبيرة: Deutsch."],
 mistakes:[{w:"ich habe ein buch.",r:"Ich habe ein Buch.",why:"بداية الجملة كبيرة + Buch اسم فيكبر."}],
 related:["b-nomen-genus","c-personal"],
 quiz:[{q:"أي كتابة صحيحة؟",opts:["ich habe ein buch.","Ich habe ein Buch.","Ich habe ein buch."],correct:1,why:"بداية كبيرة + الاسم كبير."},{q:"جنس Handschuh؟",opts:["مذكر (der)","مؤنث (die)","محايد (das)"],correct:0,why:"من آخر جزء: der Schuh."}]},
{id:"b-artikel-bestimmt",level:"A1",de:"Bestimmte Artikel",ar:"أدوات التعريف",en:"Definite articles",
 what:"أداة التعريف للشيء المعروف: der (مذكر) — die (مؤنث) — das (محايد) — die (جمع). تتغير حسب الحالة الإعرابية.",
 rule:"Nominativ للفاعل، Akkusativ للمفعول المباشر، Dativ بعد حروف جر وأفعال معينة، Genitiv للملكية (B1).",
 keywords:["bestimmt","معرفة","der","die","das","Nominativ","Akkusativ","Dativ","Artikel"],
 tables:[{cap:"Bestimmte Artikel — الحالات الأربع",head:["","maskulin","feminin","neutral","Plural"],rows:[["Nominativ","der","die","das","die"],["Akkusativ","den","die","das","die"],["Dativ","dem","der","dem","den"],["Genitiv (B1)","des","der","des","der"]]}],
 examples:[["Der Mann kauft das Brot.","الرجل يشتري الخبز."],["Ich sehe den Hund.","أنا أرى الكلب."],["Sie hilft dem Kind.","هي تساعد الطفل."],["Die Kinder spielen im Garten.","الأطفال يلعبون في الحديقة."]],
 notes:["Akkusativ يغيّر المذكر فقط: der → den.","Dativ الجمع يضيف n: den Kindern."],
 mistakes:[{w:"Ich sehe der Hund.",r:"Ich sehe den Hund.",why:"المفعول المذكر في Akkusativ يأخذ den."}],
 related:["b-nomen-genus","d-nominativ","d-akkusativ","d-dativ","c-demonstrativ"],explain:"g1",
 quiz:[{q:"___ Mann ist nett. (فاعل)",opts:["Der","Den","Dem"],correct:0,why:"Nominativ مذكر = der."},{q:"Ich sehe ___ Hund. (مفعول)",opts:["der","den","dem"],correct:1,why:"Akkusativ مذكر = den."},{q:"Sie hilft ___ Kind. (helfen + Dativ)",opts:["das","dem","den"],correct:1,why:"helfen تأخذ Dativ: dem Kind."}]},
{id:"b-artikel-unbestimmt",level:"A1",de:"Unbestimmte Artikel",ar:"أدوات النكرة",en:"Indefinite articles",
 what:"أداة النكرة لشيء غير محدد: ein (مذكر/محايد) — eine (مؤنث). لا توجد صيغة جمع للنكرة.",
 rule:"نفس تصريف ein في كل الحالات. الجمع للنكرة بدون أداة: Ich lese Bücher.",
 keywords:["unbestimmt","نكرة","ein","eine","einen"],
 tables:[{cap:"Unbestimmte Artikel",head:["","maskulin","feminin","neutral"],rows:[["Nominativ","ein","eine","ein"],["Akkusativ","einen","eine","ein"],["Dativ","einem","einer","einem"]]}],
 examples:[["Ein Mann wartet hier.","رجل ما ينتظر هنا."],["Ich habe eine Frage.","لديّ سؤال."],["Er hilft einem Freund.","هو يساعد صديقًا."],["Ich lese Bücher.","أنا أقرأ كتبًا."]],
 notes:["eine تبقى eine في Akkusativ للمؤنث.","der/die/das للمعرفة تقابلها ein/eine للنكرة."],
 mistakes:[{w:"Ich habe ein Frage.",r:"Ich habe eine Frage.",why:"Frage مؤنثة: eine."}],
 related:["b-artikel-bestimmt","b-artikel-negativ"],
 quiz:[{q:"Ich habe ___ Frage.",opts:["ein","eine","einen"],correct:1,why:"Frage مؤنثة: eine."},{q:"Das ist ___ Buch. (محايد، فاعل)",opts:["ein","eine","einen"],correct:0,why:"Nominativ محايد = ein."}]},
{id:"b-artikel-negativ",level:"A1",de:"Negativartikel kein",ar:"أداة النفي kein",en:"Negative article kein",
 what:"kein تنفي اسمًا له أداة (تحل محل أداته)، وnicht تنفي الفعل أو الصفة أو الجملة. أشهر خطأ في A1 هو الخلط بينهما.",
 rule:"kein + اسم (يُصرَّف مثل ein). nicht + فعل/صفة/جملة (لا يُصرَّف). التفصيل الكامل في i-negation.",
 keywords:["kein","keine","nicht","نفي","Negation","ضمائر"],
 tables:[{cap:"kein مقابل nicht",head:["","kein","nicht"],rows:[["ينفي","اسمًا (بدل أداته)","فعلًا / صفة / جملة"],["مثال","Ich habe kein Auto.","Ich lerne heute nicht."],["مثال","Sie hat keine Zeit.","Das ist nicht gut."],["التصريف","مثل ein تمامًا","لا يُصرَّف"]]}],
 examples:[["Ich habe kein Buch.","ليس لديّ كتاب."],["Sie hat keine Freunde in Berlin.","ليس لديها أصدقاء في برلين."],["Ich komme heute nicht.","لن آتي اليوم."],["Das Wetter ist nicht schön.","الطقس ليس جميلًا."]],
 notes:["kein Deutsch ممكنة (نفي اللغة كاسم) لكن Ich spreche nicht Deutsch أصح سياقيًا.","niemand/nichts/nie في المسار I."],
 mistakes:[{w:"Ich habe nicht Auto.",r:"Ich habe kein Auto.",why:"نفي الاسم يحتاج kein."},{w:"Ich lerne heute kein.",r:"Ich lerne heute nicht.",why:"نفي الفعل يحتاج nicht."}],
 related:["b-artikel-unbestimmt","i-negation"],explain:"g5",
 quiz:[{q:"Ich habe ___ Auto.",opts:["nicht","kein","keine"],correct:1,why:"نفي اسم محايد: kein Auto."},{q:"Ich lerne heute ___.",opts:["kein","nicht","keine"],correct:1,why:"نفي الفعل = nicht."},{q:"Sie hat ___ Zeit.",opts:["kein","keine","nicht"],correct:1,why:"Zeit مؤنثة: keine Zeit."}]},
{id:"b-artikel-possessiv",level:"A1",de:"Possessivartikel",ar:"أدوات الملكية",en:"Possessive articles",
 what:"أداة الملكية = أساس الملكية + نهاية الإعراب: mein/dein/sein/ihr/sein/unser/euer/ihr/Ihr + نفس نهايات ein تمامًا، ويأتي بعدها اسم دائما.",
 rule:"بدون اسم بعدها تصبح ضميرًا مستقلًا (انظر c-possessiv). Ihr الكبيرة لحضرتك/حضراتكم.",
 keywords:["mein","deine","sein","ihr","unser","euer","Ihre","ملكية","Possessiv"],
 tables:[{cap:"أساس الملكية",head:["ich","du","er","sie","es","wir","ihr","sie","Sie"],rows:[["mein-","dein-","sein-","ihr-","sein-","unser-","euer-","ihr-","Ihr-"]]},{cap:"النهايات (مثل ein)",head:["","maskulin","feminin","neutral","Plural"],rows:[["Nominativ","mein","meine","mein","meine"],["Akkusativ","meinen","meine","mein","meine"],["Dativ","meinem","meiner","meinem","meinen"]]}],
 examples:[["Mein Vater arbeitet viel.","والدي يعمل كثيرًا."],["Ich liebe meine Mutter.","أنا أحب والدتي."],["Wir fahren mit unserem Auto.","نحن نذهب بسيارتنا."]],
 notes:["sein = ملكه، ihr = ملكها/ملكهم حسب السياق.","euer تفقد e قبل النهاية أحيانا: eure (وليس euere)."],
 mistakes:[{w:"meine Vater",r:"mein Vater",why:"Nominativ مذكر بدون نهاية."}],
 related:["c-possessiv","b-artikel-unbestimmt","d-dativ"],
 quiz:[{q:"___ Vater arbeitet. (والدي)",opts:["Mein","Meine","Meinen"],correct:0,why:"Nominativ مذكر: mein Vater."},{q:"Ich liebe ___ Mutter. (مفعول)",opts:["mein","meine","meiner"],correct:1,why:"Akkusativ مؤنث: meine Mutter."}]},
{id:"b-artikel-demonstrativ",level:"A1",de:"Demonstrativartikel",ar:"أدوات الإشارة",en:"Demonstrative articles",
 what:"أداة الإشارة تحدد اسمًا قريبًا أو مشارًا إليه: dieser/diese/dieses (هذا) — jener/jene/jenes (ذلك، B1).",
 rule:"تُصرَّف مثل der/die/das مع نهايات أوضح. dieser للمذكر يحتاج en في Akkusativ: diesen.",
 keywords:["dieser","diese","dieses","jener","إشارة","Demonstrativ"],
 tables:[{cap:"Demonstrativartikel",head:["","maskulin","feminin","neutral","Plural"],rows:[["Nominativ","dieser","diese","dieses","diese"],["Akkusativ","diesen","diese","dieses","diese"],["Dativ (A2)","diesem","dieser","diesem","diesen"]]},{cap:"jener (ذلك، B1)",head:["maskulin","feminin","neutral","Plural"],rows:[["jener","jene","jenes","jene"]]}],
 examples:[["Dieses Haus ist groß.","هذا البيت كبير."],["Ich nehme diesen Kuchen.","سآخذ هذه الكعكة."],["Diese Kinder sind nett.","هؤلاء الأطفال لطفاء."]],
 notes:["jener (ذلك للبعيد) مستوى B1 وقليل الاستخدام يوميًا.","كضمير مستقل: derjenige (B1)."],
 mistakes:[{w:"dieser Kuchen (كمفعول)",r:"diesen Kuchen",why:"Akkusativ مذكر: diesen."}],
 related:["c-demonstrativ","b-artikel-bestimmt"],
 quiz:[{q:"___ Haus ist groß. (محايد)",opts:["Dieser","Diese","Dieses"],correct:2,why:"Haus محايد: dieses Haus."},{q:"Ich nehme ___ Kuchen. (مفعول)",opts:["dieser","diesen","dieses"],correct:1,why:"Akkusativ مذكر: diesen."}]}
];
var REF_C=[
{id:"c-personal",level:"A1",de:"Personalpronomen",ar:"الضمائر الشخصية",en:"Personal pronouns",
 what:"تحل محل الاسم: من يقوم بالفعل (Nominativ) ومن يقع عليه الفعل (Akkusativ/Dativ). أساس تصريف كل الأفعال.",
 rule:"ich/du/er/sie/es/wir/ihr/sie/Sie. du للصديق والعائلة، Sie للرسمي. sie الصغيرة = هي/هم، Sie الكبيرة = حضرتك.",
 keywords:["Personalpronomen","ضمائر","ich","mich","mir","Nominativ","Akkusativ","Dativ"],
 tables:[{cap:"Personalpronomen",head:["","ich","du","er","sie","es","wir","ihr","sie","Sie"],rows:[["Nominativ (wer?)","ich","du","er","sie","es","wir","ihr","sie","Sie"],["Akkusativ (wen?)","mich","dich","ihn","sie","es","uns","euch","sie","Sie"],["Dativ (wem?)","mir","dir","ihm","ihr","ihm","uns","euch","ihnen","Ihnen"]]}],
 examples:[["Ich sehe dich.","أنا أراك."],["Er hilft mir.","هو يساعدني."],["Wir sprechen mit Ihnen.","نحن نتحدث مع حضرتك."],["Sie wohnt in Berlin.","هي تسكن في برلين."]],
 notes:["كل ضمير له نهاية فعل مختلفة — أساس التصريف.","mit تأخذ Dativ دائما: mit mir."],
 mistakes:[{w:"Du lernt Deutsch.",r:"Du lernst Deutsch.",why:"du تأخذ نهاية st."}],
 related:["d-nominativ","d-akkusativ","d-dativ","f-grundlagen"],explain:"g4",
 quiz:[{q:"___ helfe dir. (أنا)",opts:["Ich","Mich","Mir"],correct:0,why:"الفاعل Nominativ: ich."},{q:"Ich sehe ___. (هو)",opts:["er","ihn","ihm"],correct:1,why:"sehen + Akkusativ: ihn."},{q:"Er spricht mit ___. (أنا)",opts:["mich","mir","ich"],correct:1,why:"mit + Dativ: mir."}]},
{id:"c-possessiv",level:"A2",de:"Possessivpronomen",ar:"ضمائر الملكية المستقلة",en:"Independent possessive pronouns",
 what:"ضمير الملكية المستقل يقف وحده بدون اسم بعده (Das Buch ist meines). أما mein/meine + اسم فهو أداة ملكية (b-artikel-possessiv).",
 rule:"تُصرَّف مثل dieser: meiner/meine/meines/meine في Nominativ.",
 keywords:["meiner","meines","deine","Possessivpronomen","ملكية"],
 tables:[{cap:"Possessivpronomen — Nominativ (الأساس mein-)",head:["maskulin","feminin","neutral","Plural"],rows:[["meiner","meine","meines","meine"],["deiner","deine","deines","deine"],["seiner","seine","seines","seine"]]},{cap:"التصريف الكامل (mein-)",head:["","maskulin","feminin","neutral","Plural"],rows:[["Nominativ","meiner","meine","meines","meine"],["Akkusativ","meinen","meine","meines","meine"],["Dativ","meinem","meiner","meinem","meinen"]]}],
 examples:[["Das Buch ist meines.","هذا الكتاب ملكي."],["Die Tasche ist deine.","الحقيبة حقيبتك."],["Ist das dein Auto? — Ja, es ist meines.","هل هذه سيارتك؟ — نعم، إنها ملكي."]],
 notes:["الفرق الجوهري: الأداة + اسم، والضمير وحده.","الأداة A1، والضمير المستقل A2."],
 mistakes:[{w:"Das ist mein. (بدون اسم)",r:"Das ist meines.",why:"بدون اسم نستخدم الضمير المستقل."}],
 related:["b-artikel-possessiv","d-nominativ"],
 quiz:[{q:"Das Fahrrad ist ___. (ملكي، محايد)",opts:["mein","meines","meiner"],correct:1,why:"مستقل محايد: meines."},{q:"أي جملة فيها ضمير مستقل؟",opts:["Mein Vater arbeitet.","Das Auto ist meines.","Ich sehe mein Buch."],correct:1,why:"meines وحده بدون اسم."}]},
{id:"c-reflexiv",level:"A1",de:"Reflexivpronomen",ar:"الضمائر الانعكاسية",en:"Reflexive pronouns",
 what:"تعود على الفاعل نفسه مع أفعال مثل sich waschen / sich setzen / sich treffen: الفاعل والمفعول نفس الشخص.",
 rule:"er/sie/es/sie/Sie كلها sich. الفرق بين Akkusativ وDativ يظهر في ich/du فقط (mich/mir, dich/dir).",
 keywords:["sich","mich","dich","uns","reflexiv","انعكاسي"],
 tables:[{cap:"Reflexivpronomen — Akkusativ",head:["ich","du","er/sie/es","wir","ihr","sie/Sie"],rows:[["mich","dich","sich","uns","euch","sich"]]},{cap:"Reflexivpronomen — Dativ",head:["ich","du","er/sie/es","wir","ihr","sie/Sie"],rows:[["mir","dir","sich","uns","euch","sich"]]}],
 examples:[["Ich wasche mich.","أنا أغتسل."],["Du setzt dich hier.","أنت تجلس هنا."],["Wir treffen uns morgen.","سنلتقي غدًا."]],
 notes:["أفعال انعكاسية شائعة: sich freuen, sich interessieren, sich erinnern.","بعضها يأخذ حرف جر ثابت: sich freuen auf/über."],
 mistakes:[{w:"Ich wasche sich.",r:"Ich wasche mich.",why:"الفاعل ich يأخذ mich."}],
 related:["c-personal","f-grundlagen"],
 quiz:[{q:"Ich wasche ___.",opts:["mich","dich","sich"],correct:0,why:"الفاعل ich ← mich."},{q:"Wir treffen ___ morgen.",opts:["uns","euch","sich"],correct:0,why:"الفاعل wir ← uns."}]},
{id:"c-demonstrativ",level:"A1",de:"Demonstrativpronomen",ar:"ضمائر الإشارة",en:"Demonstrative pronouns",
 what:"تشير لشيء محدد: dieser (هذا) — der/die/das كإشارة أقوى — das (هذا/ذلك). الفرق عن الأداة: الضمير يقف وحده.",
 rule:"Dieser Tisch ist neu (أداة + اسم) مقابل Dieser ist neu (ضمير وحده). der/die/das كضمير إشارة تُنطق بنبرة أقوى.",
 keywords:["dieser","diese","dieses","derjenige","إشارة","Demonstrativ"],
 tables:[{cap:"dieser كضمير — Nominativ",head:["maskulin","feminin","neutral","Plural"],rows:[["dieser","diese","dieses","diese"]]},{cap:"dieser كضمير — Akkusativ",head:["maskulin","feminin","neutral","Plural"],rows:[["diesen","diese","dieses","diese"]]},{cap:"jener (ذلك، B1) — Nominativ",head:["maskulin","feminin","neutral","Plural"],rows:[["jener","jene","jenes","jene"]]},{cap:"derjenige (الذي، B1)",head:["maskulin","feminin","neutral"],rows:[["derjenige","diejenige","dasjenige"]]}],
 examples:[["Dieser ist neu.","هذا جديد."],["Ich kenne diese Frau.","أنا أعرف هذه المرأة."],["Das ist mein Lehrer.","هذا معلمي."],["Jener dort ist mein Onkel. (B1)","ذلك الرجل هناك عمي."]],
 notes:["derjenige/diejenige (الذي/التي، B1) للجمل الطويلة.","das المحايد يُستخدم للأشياء غير المعروفة الجنس."],
 mistakes:[{w:"Diesen ist neu. (فاعل)",r:"Dieser ist neu.",why:"الفاعل Nominativ: dieser."}],
 related:["b-artikel-demonstrativ","d-nominativ"],
 quiz:[{q:"___ ist neu. (هذا، فاعل مذكر)",opts:["Dieser","Diesen","Dieses"],correct:0,why:"Nominativ: dieser."},{q:"Ich nehme ___. (هذه، مفعول مؤنث)",opts:["dieser","diese","dieses"],correct:1,why:"Akkusativ مؤنث: diese."}]},
{id:"c-interrogativ",level:"A1",de:"Interrogativpronomen",ar:"ضمائر الاستفهام",en:"Interrogative pronouns",
 what:"تسأل عن الأشخاص والأشياء: wer (من) — was (ماذا) — welcher (أي). لا تخلط بينها وبين ظروف السؤال مثل wo/wann (انظر i-fragewoerter).",
 rule:"wer تُصرَّف (wer/wen/wem)، وwas ثابتة. welcher تُصرَّف مثل dieser.",
 keywords:["wer","wen","wem","was","welcher","استفهام","Dativ"],
 tables:[{cap:"wer / was",head:["Nominativ","Akkusativ","Dativ"],rows:[["wer","wen","wem"],["was","was","—"]]},{cap:"welcher (مثل dieser)",head:["maskulin","feminin","neutral","Plural"],rows:[["welcher","welche","welches","welche"]]}],
 examples:[["Wer ist das?","من هذا؟"],["Wen siehst du?","من ترى؟"],["Mit wem sprichst du?","مع من تتحدث؟"],["Was ist das?","ما هذا؟"],["Welcher Bus fährt ins Zentrum?","أي أتوبيس يذهب إلى المركز؟"]],
 notes:["wessen (ملك من) مستوى B1.","welcher يطابق جنس الاسم المذكور بعده."],
 mistakes:[{w:"Wen kommt heute?",r:"Wer kommt heute?",why:"الفاعل يُسأل عنه بـ wer."}],
 related:["i-fragewoerter","d-akkusativ","d-dativ"],
 quiz:[{q:"___ kommt heute؟ (فاعل)",opts:["Wer","Wen","Wem"],correct:0,why:"السؤال عن الفاعل: wer."},{q:"___ siehst du؟ (مفعول)",opts:["Wer","Wen","Wem"],correct:1,why:"sehen + Akkusativ: wen."}]},
{id:"c-relativ",level:"A2",de:"Relativpronomen",ar:"الضمائر النسبية",en:"Relative pronouns",
 what:"تربط جملتين وتصف الاسم: Der Mann, der hier wohnt (= الرجل الذي يسكن هنا). تطابق جنس الاسم وعدده، وحالتها حسب دورها في الجملة النسبية.",
 rule:"أشكالها مثل der/die/das مع اختلافين: الجمع في Dativ = denen، والإضافة deren/dessen (B1). الفعل في الجملة النسبية في النهاية.",
 keywords:["Relativpronomen","der","den","dem","denen","الذي","التي"],
 tables:[{cap:"Relativpronomen",head:["","maskulin","feminin","neutral","Plural"],rows:[["Nominativ","der","die","das","die"],["Akkusativ","den","die","das","die"],["Dativ","dem","der","dem","denen"],["Genitiv (B1)","dessen","deren","dessen","deren"]]}],
 examples:[["Der Mann, der hier wohnt, ist mein Lehrer.","الرجل الذي يسكن هنا هو معلمي."],["Das Buch, das ich lese, ist interessant.","الكتاب الذي أقرؤه شيّق."]],
 notes:["الفاصلة قبل الجملة النسبية إجبارية.","deren/dessen للملكية مستوى B1."],
 mistakes:[{w:"Der Film, der ich sehe",r:"Der Film, den ich sehe",why:"الفيلم مفعول (أشاهده): den."}],
 related:["m-haupt-neben","d-akkusativ","d-dativ"],
 quiz:[{q:"Der Film, ___ ich sehe, ist gut.",opts:["der","den","dem"],correct:1,why:"مفعول مذكر: den."},{q:"Die Frau, ___ hier arbeitet, ist nett.",opts:["die","der","den"],correct:0,why:"فاعلة مؤنثة: die."}]},
{id:"c-indefinit",level:"A1",de:"Indefinitpronomen",ar:"الضمائر غير المحددة",en:"Indefinite pronouns",
 what:"تتحدث عن شخص أو شيء غير معيّن: man (الناس عمومًا) — etwas/nichts — jemand/niemand — jeder/alle.",
 rule:"man يأخذ فعلًا مفردًا دائما. jeder + اسم مفرد، alle + جمع. الفرق المفرد/الجمع والقابل للعد في k-quantitaet.",
 keywords:["man","etwas","nichts","jemand","niemand","jeder","alle","einige","mehrere","غير محدد"],
 tables:[{cap:"الاستخدام",head:["الضمير","العربي","الاستخدام","مثال"],rows:[["man","الناس / المرء","فاعل عام + فعل مفرد","Man spricht hier Deutsch."],["etwas / nichts","شيء / لا شيء","أشياء غير محددة","Ich habe etwas gekauft."],["jemand / niemand","شخص ما / لا أحد","أشخاص غير محددين","Niemand ist hier."],["jeder / alle","كل واحد / الجميع","jeder + مفرد، alle + جمع","Jeder muss lernen."],["einer / keiner","واحد منهم / لا أحد منهم (بدل اسم)","Einer fehlt heute.","Keiner ist da."]]}],
 examples:[["Man spricht hier Deutsch.","الناس هنا يتحدثون الألمانية."],["Ich habe etwas gekauft.","اشتريت شيئًا ما."],["Jeder muss jeden Tag lernen.","على كل شخص أن يتعلم كل يوم."]],
 notes:["man ≠ Mann (رجل): الفرق حرف واحد ومعنى مختلف تماما.","einige/mehrere/viele في k-quantitaet."],
 mistakes:[{w:"Man sprechen Deutsch.",r:"Man spricht Deutsch.",why:"man تأخذ فعلًا مفردًا."}],
 related:["k-quantitaet","i-negation"],
 quiz:[{q:"___ ist hier. (لا أحد)",opts:["Jemand","Niemand","Man"],correct:1,why:"لا أحد = niemand."},{q:"___ spricht hier Deutsch. (الناس عمومًا)",opts:["Man","Etwas","Jeder"],correct:0,why:"الفاعل العام = man."}]}
];
