/* Deutsch Master — Reference data: path P (Vergleiche & Fehler). Pure data. */
"use strict";
var REF_P=[
{id:"p-vergleiche",level:"A1",de:"Verwechslungen im Vergleich",ar:"المقارنات السريعة",en:"Quick comparisons",
 what:"صفحة مراجعة سريعة لأشهر الثنائيات التي يخلط بينها الطلاب: متى أستخدم A ومتى B، مع مثال لكل منهما وخطأ شائع.",
 rule:"اقرأ الفرق أولًا، ثم احفظ مثالًا واحدًا لكل طرف — المثال المحفوظ يغني عن القاعدة وقت الاختبار.",
 keywords:["Vergleich","seit","vor","wann","wenn","wo","wohin","in","an","auf","haben","sein","viel","viele","مقارنة","Verwechslung"],
 tables:[{cap:"المقارنات (A مقابل B)",head:["المقارنة","A = متى","B = متى","الفرق"],rows:[["kein / nicht","نفي اسم (kein Auto)","نفي فعل/صفة (nicht gut)","الاسم مقابل الفعل"],["der / die / das","معرفة مذكر/مؤنث/محايد","—","جنس الاسم"],["ein / eine","نكرة مذكر+محايد / مؤنث","—","الجنس أيضًا"],["mein / meine","+ مذكر/محايد (mein Vater)","+ مؤنث/جمع (meine Mutter)","نهاية الملكية"],["dieser / diesen","فاعل (dieser Mann)","مفعول (diesen Mann)","الحالة"],["wer / wen / wem","فاعل / مفعول / مستفيد","—","Nominativ/Akkusativ/Dativ"],["wo / wohin / woher","ثابت / حركة / مصدر","—","Wo/Wohin/Woher"],["wann / wenn","سؤال زمني (متى)","رابط شرطي (عندما)","سؤال مقابل رابط"],["seit / vor / für","منذ مستمر / قبل منتهٍ / لمدة-لأجل","—","الزمن المستمر مقابل المنتهي"],["in / an / auf","داخل / عمودي-ماء / أفقي-مناسبة","—","نوع المكان"],["haben / sein","معظم الأفعال / حركة وتغير","—","المساعد في Perfekt"],["Perfekt / Präteritum","محكي يومي / كتابي وقصصي","—","السجل اللغوي"],["viel / viele","غير معدود / معدود جمع","—","قابلية العد"]]}],
 examples:[["Ich habe kein Auto. / Ich komme heute nicht.","ليس لديّ سيارة. / لن آتي اليوم."],["Ich bin in der Schule. / Ich gehe in die Schule.","أنا في المدرسة. / أنا ذاهب إلى المدرسة."],["Seit einem Jahr lerne ich. / Vor einem Jahr kam ich an.","أتعلم منذ سنة. / وصلت قبل سنة."],["Er hat gelernt. / Er ist gekommen.","لقد تعلم. / لقد جاء."]],
 notes:["كل مقارنة لها موضوعها المفصل — اضغط 🔗 للمراجعة العميقة.","احفظ مثالًا واحدًا لكل طرف قبل الاختبار."],
 mistakes:[{w:"الخلط بين seit و vor",r:"seit = مستمر حتى الآن، vor = منتهٍ",why:"الزمن يحدد المعنى."}],
 related:["b-artikel-negativ","i-negation","h-wechsel","h-dativ","g-perfekt","g-praeteritum","k-quantitaet","c-interrogativ","l-wo","l-wohin"],
 quiz:[{q:"Ich habe ___ Auto. (نفي اسم)",opts:["nicht","kein","nie"],correct:1,why:"نفي الاسم = kein."},{q:"Ich gehe ___ die Schule. (حركة)",opts:["in","mit","bei"],correct:0,why:"حركة + in + Akkusativ."},{q:"___ einem Jahr lerne ich. (مستمر)",opts:["Vor","Seit","Für"],correct:1,why:"مستمر حتى الآن = seit."}]},
{id:"p-fehler",level:"A1",de:"Häufige Fehler",ar:"الأخطاء الشائعة",en:"Common mistakes",
 what:"أشهر 15 خطأ عند العرب متعلمي الألمانية: كل خطأ مع تصحيحه وسببه — راجعها قبل أي اختبار.",
 rule:"معظم الأخطاء من الترجمة الحرفية من العربية أو الخلط بين كلمتين متشابهتين. القاعدة الذهبية: احفظ المثال الصحيح.",
 keywords:["Fehler","kennen","wissen","liegen","legen","sitzen","als","wenn","Mann","man","خطأ","أخطاء","falsch","richtig"],
 tables:[{cap:"خريطة الأخطاء",head:["الخطأ في","الصحيح","القاعدة"],rows:[["nicht/kein","kein + اسم، nicht + فعل","b-artikel-negativ"],["wo/wohin","ثابت/حركة","l-wo"],["seit/vor","مستمر/منتهٍ","h-dativ"],["zu/nach","شخص/مدينة","h-dativ"],["kennen/wissen","شخص-شيء/معلومة","—"],["liegen/legen","مستلقٍ/يضع","—"],["falscher Kasus","den/dem حسب الفعل","d-vergleich"]]}],
 examples:[["Ich kenne den Film. / Ich weiß die Antwort.","أعرف الفيلم. / أعرف الإجابة."],["Das Buch liegt auf dem Tisch. / Ich lege das Buch hin.","الكتاب مستلقٍ على الطاولة. / أضع الكتاب."]],
 notes:["kennen + شخص/شيء (تعارف)، wissen + معلومة/خبر (معرفة ذهنية).","liegen (يستلقي، لازم) ≠ legen (يضع شيئًا، متعدٍ). stehen/stellen و sitzen/setzen بنفس المنطق."],
 mistakes:[
  {w:"Ich weiß den Mann.",r:"Ich kenne den Mann.",why:"معرفة الأشخاص = kennen.",rel:"f-akkusativ-verben"},
  {w:"Ich lege im Bett. (بمعنى مستلقٍ)",r:"Ich liege im Bett.",why:"الاستلقاء لازم = liegen.",rel:"f-lage-verben"},
  {w:"Er hilft mich.",r:"Er hilft mir.",why:"helfen + Dativ.",rel:"f-dativ-verben"},
  {w:"Man (بمعنى رجل)",r:"Mann = رجل، man = المرء/الناس",why:"حرف واحد يغيّر المعنى تمامًا.",rel:"a-alphabet"},
  {w:"Ich bin 20 Jahre.",r:"Ich bin 20 Jahre alt.",why:"العمر يحتاج alt.",rel:"k-zahlen"},
  {w:"Ich fahre zu Berlin.",r:"Ich fahre nach Berlin.",why:"المدن مع nach.",rel:"l-wohin"},
  {w:"Wann du kommst, ruf an. (بمعنى عندما)",r:"Wenn du kommst, ruf an.",why:"عندما الشرطية = wenn (A2).",rel:"i-konjunktionen"},
  {w:"viele Wasser",r:"viel Wasser",why:"غير المعدود: viel.",rel:"k-quantitaet"},
  {w:"Ich habe seit einem Jahr gelernt. (وانتهيت)",r:"Ich habe vor einem Jahr gelernt.",why:"المنتهي = vor.",rel:"h-dativ"},
  {w:"Wo gehst du hin? (مكررة بلا داعٍ)",r:"Wohin gehst du?",why:"wohin وحدها كافية.",rel:"i-fragewoerter"},
  {w:"Das Wetter ist nicht schön? (صحيحة! البديل الخاطئ: kein schön)",r:"nicht + صفة، kein + اسم",why:"مراجعة b-artikel-negativ.",rel:"b-artikel-negativ"},
  {w:"Ich besuche dir.",r:"Ich besuche dich.",why:"besuchen + Akkusativ.",rel:"f-akkusativ-verben"},
  {w:"halb acht = 8:30",r:"halb acht = 7:30",why:"نصف نحو الثامنة.",rel:"j-uhrzeit"},
  {w:"Sie hilft den Kind.",r:"Sie hilft dem Kind.",why:"helfen + Dativ محايد: dem.",rel:"d-dativ"},
  {w:"Ich muss lerne.",r:"Ich muss lernen.",why:"المصدر الكامل بعد الناقص.",rel:"f-modal"}],
 related:["b-artikel-negativ","l-wo","h-dativ","d-vergleich","f-dativ-verben","j-uhrzeit","f-modal","k-quantitaet"],
 quiz:[{q:"Ich ___ den Mann. (أعرفه شخصيًا)",opts:["weiß","kenne","lerne"],correct:1,why:"الأشخاص = kennen."},{q:"Das Buch ___ auf dem Tisch. (مستلقٍ)",opts:["liegt","legt","läge"],correct:0,why:"الاستلقاء = liegen."},{q:"Ich ___ einen Kaffee. (أود — بتهذيب)",opts:["will","hätte gern","willst"],correct:1,why:"الطلب المهذب: hätte gern."},{q:"Ich ___ den Unterschied. (أعرف — معلومة)",opts:["weiß","kenne","lerne"],correct:0,why:"المعلومات = wissen."},{q:"___ acht ist 7:30.",opts:["Halb","Hälfte","Viertel"],correct:0,why:"halb acht = 7:30."}]}
];
