/* Deutsch Master — Reference data: path N (Zeichensetzung) + path O (Alltagssprache). Pure data. */
"use strict";
var REF_N=[
{id:"n-basis",level:"A1",de:"Grundzeichen",ar:"علامات الترقيم الأساسية",en:"Basic punctuation",
 what:"أربع علامات لا غنى عنها: النقطة تنهي الخبر، والفاصلة تفصل، والاستفهام للسؤال، والتعجب للانفعال والأمر.",
 rule:"Punkt (.) للخبر. Komma (,) قبل weil/dass/wenn وبين الجمل. Fragezeichen (?) للسؤال. Ausrufezeichen (!) للأمر والانفعال.",
 keywords:["Punkt","Komma","Fragezeichen","Ausrufezeichen","نقطة","فاصلة","استفهام","تعجب","Zeichensetzung"],
 tables:[{cap:"العلامات الأساسية",head:["العلامة","الألماني","الاستخدام","مثال"],rows:[[".","Punkt","نهاية الخبر","Ich lerne Deutsch."],[",","Komma","قبل الروابط والفواصل","Ich bleibe, weil ich krank bin."],["?","Fragezeichen","نهاية السؤال","Wo wohnst du?"],["!","Ausrufezeichen","الأمر والانفعال","Mach die Tür zu!"]]}],
 examples:[["Ich heiße Ahmed.","اسمي أحمد."],["Sprichst du Deutsch?","هل تتحدث الألمانية؟"]],
 notes:["الفاصلة قبل weil/dass/wenn إجبارية دائما.","بعد التحية في الرسائل تُستخدم الفاصلة غالبا: Lieber Ahmed, ..."],
 mistakes:[{w:"Ich bleibe weil ich krank bin.",r:"Ich bleibe, weil ich krank bin.",why:"فاصلة إجبارية قبل weil."}],
 related:["m-haupt-neben","n-weitere"],
 quiz:[{q:"Ich lerne Deutsch___",opts:[".","?","!"],correct:0,why:"الخبر ينتهي بنقطة."},{q:"Wo wohnst du___",opts:[".","?","!"],correct:1,why:"السؤال ينتهي باستفهام."}]},
{id:"n-weitere",level:"A2",de:"Weitere Zeichen",ar:"علامات إضافية (متقدم نسبيًا)",en:"More punctuation",
 what:"علامات للكتابة الأطول: النقطتان للشرح والتعداد، والفاصلة المنقوطة للربط، والاقتباس للكلام المباشر، والشرطة والأقواس للتوضيح.",
 rule:"Doppelpunkt (:) قبل شرح/تعداد. Semikolon (;) بين جملتين مرتبطتين. Anführungszeichen („…“) للكلام المباشر.",
 keywords:["Doppelpunkt","Semikolon","Anführungszeichen","Bindestrich","Klammern","نقطتان","اقتباس","أقواس"],
 tables:[{cap:"العلامات الإضافية",head:["العلامة","الألماني","الاستخدام","مثال"],rows:[[":","Doppelpunkt","قبل شرح أو تعداد","Er sagt: Ich komme."],[";","Semikolon","بين جملتين مرتبطتين","Ich lerne; er spielt."],['„…"',"Anführungszeichen","الكلام المباشر",'„Hallo!“, sagt er.'],["-","Bindestrich","الكلمات المركبة الطويلة","E-Mail-Adresse"],["()","Klammern","توضيح إضافي","Berlin (die Hauptstadt) ist schön."]]}],
 examples:[["Er sagt: „Ich komme morgen.“","يقول: سآتي غدًا."],["Meine Adresse: Berlin, Hauptstraße 5.","عنواني: برلين، هاوبت شتراسه 5."]],
 notes:["الألمانية تفتح الاقتباس بعلامة سفلية وتغلقه بعلوية.","Gedankenstrich (–) للوقفة والتأكيد في النصوص."],
 mistakes:[{w:"Er sagt Ich komme. (بلا نقطتين)",r:"Er sagt: Ich komme.",why:"النقطتان قبل القول المباشر."}],
 related:["n-basis","m-haupt-neben"],
 quiz:[{q:"Er sagt___ Ich komme.",opts:[":",";","!"],correct:0,why:"النقطتان قبل القول."}]}
];
var REF_O=[
{id:"o-gruesse",level:"A1",de:"Begrüßung & Vorstellung",ar:"التحية والتعارف",en:"Greetings and introductions",
 what:"عبارات اللقاء الأول: التحية حسب الوقت + الاسم + الأصل + السكن + جملة المجاملة.",
 rule:"Guten Morgen (صباحًا)، Guten Tag (نهارًا)، Guten Abend (مساءً)، Gute Nacht (عند النوم فقط!). التعارف: Ich heiße… / Ich komme aus… / Ich wohne in…",
 keywords:["Hallo","Guten Morgen","Guten Tag","Tschüs","تحية","تعارف","heiße","Freut mich","Begrüßung"],
 tables:[{cap:"التحية والتعارف",head:["الألماني","العربي","متى"],rows:[["Guten Morgen!","صباح الخير!","صباحًا"],["Guten Tag!","طاب يومك!","نهارًا"],["Guten Abend!","مساء الخير!","مساءً"],["Gute Nacht!","تصبح على خير!","عند النوم"],["Hallo! / Hi!","أهلًا!","غير رسمي"],["Tschüs! / Auf Wiedersehen!","مع السلامة!","وداع"],["Ich heiße …","اسمي …","تعارف"],["Woher kommst du?","من أين أنت؟","تعارف"],["Freut mich!","سعيد بلقائك!","مجاملة"]]}],
 examples:[["Guten Tag! Ich heiße Layla.","طاب يومك! اسمي ليلى."],["Woher kommst du? — Aus Kairo.","من أين أنت؟ — من القاهرة."],["Freut mich! Bis bald!","سعيد بلقائك! إلى اللقاء!"],["Guten Tag! Wie geht es Ihnen? — Danke, gut. Und Ihnen? — Auch gut.","طاب يومك! كيف حالك؟ — بخير شكرًا. وأنت؟ — بخير أيضًا."]],
 notes:["Gute Nacht للوداع عند النوم فقط وليست تحية مساء.","Sie الرسمية مع الكبار والغرباء أول مرة."],
 mistakes:[{w:"Gute Nacht! (تحية مساء في لقاء)",r:"Guten Abend!",why:"Gute Nacht عند النوم فقط."}],
 related:["a-alphabet","l-woher","o-alltag"],
 quiz:[{q:"تحية الصباح…",opts:["Guten Abend!","Guten Morgen!","Gute Nacht!"],correct:1,why:"Morgen = صباح."},{q:"رد المجاملة على التعارف…",opts:["Freut mich!","Gute Nacht!","Prost!"],correct:0,why:"سعيد بلقائك."}]},
{id:"o-dank",level:"A1",de:"Dank, Bitte & Entschuldigung",ar:"الشكر والطلب والاعتذار",en:"Thanks, requests and apologies",
 what:"عبارات التهذيب الثلاثة: الشكر (Danke)، الطلب (bitte)، الاعتذار (Entschuldigung / Es tut mir leid).",
 rule:"Danke für + Akk (Danke für deine Hilfe). Entschuldigung للفت الانتباه والاعتذار الخفيف، Es tut mir leid للأسف الحقيقي.",
 keywords:["Danke","bitte","Entschuldigung","leid","شكر","اعتذار","طلب","Vielen Dank"],
 tables:[{cap:"التهذيب اليومي",head:["الألماني","العربي","متى"],rows:[["Danke! / Vielen Dank!","شكرًا! / شكرًا جزيلًا!","شكر"],["Danke für deine Hilfe!","شكرًا لمساعدتك!","شكر محدد"],["Bitte! / Bitte schön!","من فضلك! / تفضل!","طلب ورد"],["Entschuldigung!","عذرًا!","اعتذار خفيف/استئذان"],["Es tut mir leid.","أنا آسف.","أسف حقيقي"],["Kein Problem!","لا مشكلة!","رد على الاعتذار"]]}],
 examples:[["Vielen Dank für deine Hilfe!","شكرًا جزيلًا لمساعدتك!"],["Entschuldigung, wo ist der Bahnhof?","عذرًا، أين المحطة؟"],["Danke für deine Hilfe! — Gern geschehen!","شكرًا لمساعدتك! — على الرحب!"]],
 notes:["Bitte تعني من فضلك وتفضل وعفوًا حسب السياق.","بعد العطس يُقال Gesundheit! (صحة!)."],
 mistakes:[{w:"Danke für dich.",r:"Danke für deine Hilfe.",why:"نشكر على الشيء لا الشخص غالبا."}],
 related:["o-gruesse","o-alltag","h-akkusativ"],
 quiz:[{q:"طلب مهذب…",opts:["Einen Kaffee, bitte.","Kaffee her!","Kaffee oder was?"],correct:0,why:"bitte للتهذيب."},{q:"أسف حقيقي…",opts:["Entschuldigung (للسؤال)","Es tut mir leid.","Kein Problem."],correct:1,why:"الأسف الحقيقي: Es tut mir leid."}]},
{id:"o-alltag",level:"A1",de:"Alltagsreaktionen",ar:"تفاعلات الحياة اليومية",en:"Everyday responses",
 what:"الموافقة والرفض وعدم الفهم وطلب التكرار وطلب المساعدة — عبارات النجاة اليومية.",
 rule:"Ja, genau (نعم بالضبط). Nein, danke (لا شكرًا). Ich verstehe nicht + Können Sie das bitte wiederholen؟",
 keywords:["Ja","Nein","verstehe","wiederholen","Hilfe","موافقة","رفض","مساعدة","Helfen"],
 tables:[{cap:"التفاعلات",head:["الألماني","العربي"],rows:[["Ja, genau! / Nein, leider nicht.","نعم بالضبط! / لا للأسف."],["Kein Problem! / Gern geschehen!","لا مشكلة! / على الرحب!"],["Ich verstehe nicht.","لا أفهم."],["Können Sie das bitte wiederholen?","هل يمكنك تكرار ذلك؟"],["Sprechen Sie bitte langsamer.","تحدث ببطء من فضلك."],["Können Sie mir bitte helfen?","هل يمكنك مساعدتي؟"],["Was bedeutet …?","ماذا تعني …؟"]]}],
 examples:[["Ich verstehe nicht. Können Sie das bitte wiederholen?","لا أفهم. هل يمكنك تكرار ذلك؟"],["Können Sie mir bitte helfen?","هل يمكنك مساعدتي من فضلك؟"]],
 notes:["langsamer = ببطء أكثر (مقارنة ظريفة مفيدة).","السؤال بـ Können Sie…؟ هو ألطف صيغة طلب."],
 mistakes:[{w:"Was? (بفظاظة)",r:"Wie bitte?",why:"Wie bitte؟ ألطف للاستيضاح."}],
 related:["o-gruesse","f-modal","l-richtungen"],
 quiz:[{q:"لم تفهم — تقول…",opts:["Was?","Ich verstehe nicht.","Egal."],correct:1,why:"عبارة مهذبة واضحة."},{q:"طلب مساعدة مهذب…",opts:["Hilf mir sofort!","Können Sie mir bitte helfen?","Du hilfst mir."],correct:1,why:"Können Sie + bitte."}]},
{id:"o-situationen",level:"A1",de:"Situationssätze",ar:"جمل المواقف (سعر/مطعم/سفر/طبيب/دراسة/عمل)",en:"Situational phrases",
 what:"جمل جاهزة لأهم المواقف: السؤال عن السعر، المطعم، التسوق، المواصلات، الطبيب، الدراسة، العمل.",
 rule:"كل موقف له سؤاله الذهبي: Wie viel kostet…؟ / Die Rechnung, bitte / Ich habe einen Termin / Ich suche…",
 keywords:["Rechnung","Termin","kostet","Preis","Restaurant","Arzt","Arbeit","مطعم","سعر","طبيب","مواقف"],
 tables:[{cap:"جمل المواقف",head:["الموقف","الألماني","العربي"],rows:[["السعر","Wie viel kostet das?","كم سعر هذا؟"],["المطعم","Die Rechnung, bitte.","الحساب من فضلك."],["المطعم","Ich hätte gern …","أود … (مهذب)"],["التسوق","Ich suche … / Ich schaue nur.","أبحث عن … / أتفرج فقط."],["المواصلات","Wann fährt der Bus?","متى يغادر الأتوبيس؟"],["الطبيب","Ich habe starke Schmerzen.","لديّ ألم شديد."],["الطبيب","Ich brauche einen Termin.","أحتاج موعدًا."],["الدراسة","Wann ist die Prüfung?","متى الامتحان؟"],["العمل","Ich habe eine Frage.","لديّ سؤال."]]}],
 examples:[["Die Rechnung, bitte.","الحساب من فضلك."],["Ich hätte gern einen Kaffee.","أود قهوة من فضلك."],["Was kostet das? — 5 Euro. — Ich nehme es.","كم سعر هذا؟ — 5 يورو. — سآخذه."]],
 notes:["Ich hätte gern = ألطف من Ich will في المطاعم.","التسوق: Haben Sie das in einer anderen Größe؟ (مقاس آخر)."],
 mistakes:[{w:"Ich will einen Kaffee. (فظ)",r:"Ich hätte gern einen Kaffee.",why:"التهذيب في الطلبات."}],
 related:["o-dank","k-zahlen","j-uhrzeit","l-richtungen"],
 quiz:[{q:"طلب الحساب…",opts:["Zahlen!","Die Rechnung, bitte.","Geld her!"],correct:1,why:"مهذبة ومباشرة."},{q:"طلب في مطعم بتهذيب…",opts:["Ich will …","Ich hätte gern …","Gib mir …"],correct:1,why:"hätte gern للطلب المهذب."}]}
];
