/* Deutsch Master — Reference data: path K (Zahlen & Menge) + path L (Ort & Richtung). Pure data. */
"use strict";
var REF_K=[
{id:"k-zahlen",level:"A1",de:"Grundzahlen",ar:"الأرقام الأساسية",en:"Cardinal numbers",
 what:"الأرقام 0-20 تُحفظ، ومن 21 تُركّب (واحد وعشرون = einundzwanzig). المئات والآلاف بسيطة.",
 rule:"21-99: الآحاد + und + العشرات. 100 = (ein)hundert, 1000 = (ein)tausend. العدد قبل الاسم غالبا بدون نهاية.",
 keywords:["Zahlen","eins","zwanzig","hundert","tausend","أرقام","einundzwanzig","number"],
 tables:[{cap:"0-20 (تُحفظ)",head:["0-5","6-10","11-15","16-20"],rows:[["null, eins, zwei, drei, vier, fünf","sechs, sieben, acht, neun, zehn","elf, zwölf, dreizehn, vierzehn, fünfzehn","sechzehn, siebzehn, achtzehn, neunzehn, zwanzig"]]},{cap:"التركيب",head:["الرقم","التركيب","مثال"],rows:[["21","ein-und-zwanzig","einundzwanzig"],["35","fünf-und-dreißig","fünfunddreißig"],["100","(ein)hundert","zweihundert"],["1000","(ein)tausend","zweitausend"]]}],
 examples:[["Ich habe zwei Brüder.","لديّ أخوان."],["Das kostet zwanzig Euro.","سعره عشرون يورو."],["Er ist einundzwanzig Jahre alt.","عمره واحد وعشرون عامًا."]],
 notes:["eins تفقد s قبل الاسم المؤنث/المحايد أحيانا: eine Tasse.","العمر: Ich bin 20 Jahre alt (بدون فعل يكون للعمر!)."],
 mistakes:[{w:"zwanzig-eins",r:"einundzwanzig",why:"الآحاد أولًا ثم und ثم العشرات."}],
 related:["k-ordinal","j-uhrzeit","k-quantitaet"],
 quiz:[{q:"21 = ؟",opts:["zwanzigeins","einundzwanzig","einszwanzig"],correct:1,why:"الآحاد + und + العشرات."},{q:"13 = ؟",opts:["dreizehn","dreibzehn","dreizig"],correct:0,why:"13 شاذة الإملاء قليلًا: dreizehn."}]},
{id:"k-ordinal",level:"A2",de:"Ordinalzahlen",ar:"الأعداد الترتيبية",en:"Ordinal numbers",
 what:"الأول، الثاني…: تُستخدم للتواريخ والطوابق والترتيب. تُصرَّف كصفة.",
 rule:"1-19: العدد + te (erste, zweite, dritte شاذة). 20+: + ste (zwanzigste). التاريخ: am ersten Mai.",
 keywords:["erste","zweite","dritte","Ordinal","ترتيبي","Datum"," Stock"],
 tables:[{cap:"الترتيبية",head:["الرقم","الترتيبي","ملاحظة"],rows:[["1","der erste","شاذ"],["2","der zweite","شاذ"],["3","der dritte","شاذ"],["4","der vierte","+ te"],["7","der siebte","شاذ قليلًا"],["8","der achte","شاذ قليلًا"],["20","der zwanzigste","+ ste"]]}],
 examples:[["Heute ist der erste Mai.","اليوم الأول من مايو."],["Ich wohne im zweiten Stock.","أسكن في الطابق الثاني."],["Er ist der Erste in der Klasse.","هو الأول في الفصل."]],
 notes:["التواريخ تُكتب: 1. Mai وتُقرأ der erste Mai.","الطوابق: Erdgeschoss (أرضي) ثم erster Stock."],
 mistakes:[{w:"der eins Mai",r:"der erste Mai",why:"التاريخ بالترتيبي."}],
 related:["k-zahlen","j-monate"],
 quiz:[{q:"der ___ Mai. (الأول)",opts:["eins","erste","einste"],correct:1,why:"1 → erste."},{q:"20 → ؟",opts:["zwanzigste","zwanzigste (ste)","zwanzig-te"],correct:1,why:"20+ تأخذ ste."}]},
{id:"k-quantitaet",level:"A1",de:"Mengenwörter",ar:"كلمات الكمية",en:"Quantity words",
 what:"كلمات تحدد الكمية: معدود (viele Äpfel) مقابل غير معدود (viel Wasser). بعضها مفرد وبعضها جمع دائما.",
 rule:"viel/wenig + غير معدود (مفرد). viele/wenige + معدود (جمع). mehr/weniger للمقارنة. jeder + مفرد، alle + جمع.",
 keywords:["viel","viele","wenig","wenige","mehr","weniger","genug","einige","mehrere","jeder","alle","كمية","Menge","alle"],
 tables:[{cap:"الكمية والعدد",head:["الكلمة","مع","مثال"],rows:[["viel","غير معدود (مفرد)","viel Wasser"],["viele","معدود (جمع)","viele Äpfel"],["wenig / wenige","قليل / قليلون","wenig Zeit / wenige Leute"],["mehr / weniger","أكثر / أقل","mehr Kaffee, bitte"],["genug","كافٍ","Das ist genug."],["einige / mehrere","بعض / عدة","einige Fragen"],["jeder/jede/jedes","كل (مفرد)","jeder Tag"],["alle","كل (جمع)","alle Leute"]]}],
 examples:[["Ich habe viel Arbeit.","لديّ عمل كثير."],["Viele Leute lernen Deutsch.","كثير من الناس يتعلمون الألمانية."],["Jeder muss helfen.","على كل واحد أن يساعد."]],
 notes:["Arbeit غير معدودة: viel Arbeit (وليس viele).","Leute جمع دائما: viele Leute."],
 mistakes:[{w:"viele Wasser",r:"viel Wasser",why:"الماء غير معدود: viel."},{w:"viel Äpfel",r:"viele Äpfel",why:"التفاح معدود: viele."}],
 related:["c-indefinit","k-zahlen","e-steigerung"],
 quiz:[{q:"___ Wasser, bitte. (كثير)",opts:["Viele","Viel","Mehrere"],correct:1,why:"غير معدود: viel."},{q:"___ Tag muss ich lernen. (كل)",opts:["Jeden","Alle","Jeder"],correct:0,why:"Akkusativ زمني: jeden Tag."}]}
];
var REF_L=[
{id:"l-wo",level:"A1",de:"Wo?",ar:"أين؟ (الموقع الثابت)",en:"Where? (location)",
 what:"السؤال عن المكان الثابت: Wo؟ الإجابة بـ Dativ مع حروف المكان (in, an, auf, bei, zu Hause).",
 rule:"hier (هنا)، dort (هناك)، oben/unten، vorne/hinten، links/rechts، draußen/drinnen. الموقع الثابت = Dativ دائما.",
 keywords:["Wo","hier","dort","oben","unten","links","rechts","Dativ","أين","مكان","Ort"],
 tables:[{cap:"ظروف المكان",head:["الكلمة","المعنى","مثال"],rows:[["hier / dort","هنا / هناك","Ich bin hier."],["oben / unten","فوق / تحت","Oben ist es ruhig."],["vorne / hinten","أمام / خلف","Vorne ist frei."],["links / rechts","يسار / يمين","Links ist die Bank."],["draußen / drinnen","خارج / داخل","Warte draußen!"]]}],
 examples:[["Wo bist du? — Ich bin zu Hause.","أين أنت؟ — أنا في البيت."],["Die Bank ist links.","البنك على اليسار."],["Das Buch liegt auf dem Tisch.","الكتاب على الطاولة."]],
 notes:["zu Hause ثابتة (في البيت) ≠ nach Hause (إلى البيت).","الموقع الثابت مع Wechsel يأخذ Dativ (h-wechsel)."],
 mistakes:[{w:"Wo gehst du? (بمعنى إلى أين)",r:"Wohin gehst du?",why:"Wo للموقع الثابت فقط."}],
 related:["l-wohin","h-wechsel","d-dativ"],
 quiz:[{q:"Wo bist du؟ تجيب عن…",opts:["الموقع الثابت","الحركة","المصدر"],correct:0,why:"Wo = أين (ثابت)."},{q:"___ ist die Bank. (على اليسار)",opts:["Nach links","Links","Link"],correct:1,why:"ظرف المكان: links."}]},
{id:"l-wohin",level:"A1",de:"Wohin?",ar:"إلى أين؟ (الاتجاه)",en:"Where to? (direction)",
 what:"السؤال عن الاتجاه: Wohin؟ الإجابة بـ Akkusativ (in/an/auf) أو nach/zu حسب القاعدة.",
 rule:"nach + مدينة/بلد بلا أداة (nach Berlin). nach Hause ثابتة. zu + شخص/مكان بأداة (zu meiner Oma). in + Akk للمباني.",
 keywords:["Wohin","nach","zu","Richtung","اتجاه","إلى أين","Berlin","Hause"],
 tables:[{cap:"الاتجاه",head:["القاعدة","مثال"],rows:[["nach + مدينة/بلد","Ich fahre nach Berlin."],["nach Hause (ثابتة)","Ich gehe nach Hause."],["zu + شخص/مكان","Ich gehe zu meinem Arzt."],["in + Akk (مبنى)","Ich gehe in die Schule."]]}],
 examples:[["Wohin fährst du? — Nach Hamburg.","إلى أين تسافر؟ — إلى هامبورغ."],["Kommst du mit zu mir?","هل تأتي معي إليّ؟"]],
 notes:["nach + اتجاه عام/مدينة، zu + هدف محدد بأداة.","in die / ans (= an das) / aufs (= auf das) اختصارات شائعة."],
 mistakes:[{w:"Ich fahre zu Berlin.",r:"Ich fahre nach Berlin.",why:"المدن مع nach."}],
 related:["l-wo","h-wechsel","h-dativ"],
 quiz:[{q:"Ich fahre ___ Berlin.",opts:["nach","zu","in"],correct:0,why:"المدن مع nach."},{q:"Ich gehe ___ meinem Arzt.",opts:["nach","zu","bei"],correct:1,why:"شخص محدد: zu + Dativ."}]},
{id:"l-woher",level:"A1",de:"Woher?",ar:"من أين؟ (المصدر)",en:"Where from? (origin)",
 what:"السؤال عن المصدر: Woher؟ الإجابة بـ aus (أصل/داخل) أو von (شخص/نقطة).",
 rule:"aus + بلد/مدينة/مبنى (خرجت من داخله). von + شخص/نقطة/جهة.",
 keywords:["Woher","aus","von","مصدر","من أين","Herkunft"],
 tables:[{cap:"المصدر",head:["القاعدة","مثال"],rows:[["aus + بلد/مدينة","Ich komme aus Ägypten."],["aus + مبنى","Er kommt aus dem Haus."],["von + شخص","Das ist von meiner Mutter."],["von + نقطة","Von hier sind es 5 Minuten."]]}],
 examples:[["Woher kommst du? — Aus Kairo.","من أين أنت؟ — من القاهرة."],["Der Brief ist von meinem Freund.","الرسالة من صديقي."]],
 notes:["aus للداخل (بلد/بيت)، von للسطح/النقطة (vom Bahnhof).","Herkunft = الأصل (موضوع محادثة شائع)."],
 mistakes:[{w:"Ich komme von Ägypten.",r:"Ich komme aus Ägypten.",why:"البلد الأصل: aus."}],
 related:["l-wo","h-dativ","o-gruesse"],
 quiz:[{q:"Er kommt ___ dem Haus.",opts:["von","aus","bei"],correct:1,why:"من داخل المبنى: aus."},{q:"Der Brief ist ___ meinem Freund.",opts:["aus","von","nach"],correct:1,why:"من شخص: von."}]},
{id:"l-richtungen",level:"A1",de:"Richtungen & Weg",ar:"الاتجاهات والسؤال عن الطريق",en:"Directions",
 what:"عبارات عملية للطريق: يمين/يسار/مباشرة/رجوع + كيف تسأل وتجيب عن الاتجاه بأدب.",
 rule:"Gehen Sie geradeaus (امشِ مباشرة). Nehmen Sie die erste Straße links. Entschuldigung, wo ist…؟",
 keywords:["links","rechts","geradeaus","zurück","Weg","طريق","اتجاهات","Richtung","Bahnhof"],
 tables:[{cap:"عبارات الطريق",head:["الألماني","العربي"],rows:[["Gehen Sie geradeaus.","امشِ مباشرة."],["Nehmen Sie die erste Straße links.","خذ أول شارع يسارًا."],["Es ist gleich hier.","إنه قريب من هنا."],["Weit weg / in der Nähe.","بعيد / قريب."],["Entschuldigung, wo ist der Bahnhof?","عذرًا، أين المحطة؟"]]}],
 examples:[["Der Bahnhof ist weit weg.","المحطة بعيدة."],["Die Apotheke ist in der Nähe.","الصيدلية قريبة."]],
 notes:["hinein (للداخل) / heraus (للخارج) / hinauf / hinunter مستوى A2.","Sie الرسمية مع الغرباء في الشارع."],
 mistakes:[{w:"Wo ist Bahnhof? (بلا أداة)",r:"Wo ist der Bahnhof?",why:"الأماكن المعروفة بأداتها."}],
 related:["l-wo","o-situationen","o-alltag"],
 quiz:[{q:"___ Sie geradeaus. (امشِ - رسمي)",opts:["Gehen","Geh","Geht"],correct:0,why:"الأمر الرسمي: المصدر + Sie."},{q:"السؤال المهذب عن مكان…",opts:["Wo Bahnhof?","Entschuldigung, wo ist der Bahnhof?","Bahnhof wo?"],correct:1,why:"اعتذار + سؤال كامل."}]}
];
