/* Deutsch Master — Reference word cards: modal verbs + machen (path F). Pure data. */
"use strict";
var REF_F2=[
{id:"f-machen",level:"A1",de:"machen",ar:"يفعل / يصنع (فعل نموذجي)",en:"to do, to make (model verb)",
 what:"الفعل النموذجي للتصريف المنتظم: الجذر mach + النهايات القياسية. يُستخدم للأنشطة والصنع.",
 rule:"ich mache, du machst, er macht, wir machen, ihr macht, sie machen. Hausaufgaben machen, ein Foto machen.",
 keywords:["machen","يفعل","يصنع","Konjugation","Hausaufgaben","Foto","regelmäßig"],
 tables:[{cap:"machen — Präsens",head:["ich","du","er","wir","ihr","sie"],rows:[["mache","machst","macht","machen","macht","machen"]]}],
 examples:[["Ich mache meine Hausaufgaben.","أعمل واجبي المنزلي."],["Er macht ein Foto.","يلتقط صورة."],["Was machst du am Wochenende?","ماذا تفعل في نهاية الأسبوع؟"]],
 notes:["machen + مهنة/نشاط: Sport machen, Musik machen.","aufmachen فعل منفصل مختلف (يفتح)!"],
 mistakes:[{w:"du macht",r:"du machst",why:"du + st."}],
 related:["f-grundlagen","f-trennbar","o-alltag"],
 quiz:[{q:"du + machen = ؟",opts:["machst","macht","mache"],correct:0,why:"du + st."},{q:"Ich ___ Hausaufgaben.",opts:["mache","macht","machen"],correct:0,why:"ich + e."}]},
{id:"f-w-koennen",level:"A1",de:"können",ar:"يستطيع (فعل ناقص)",en:"can, to be able to (modal)",
 what:"فعل ناقص للقدرة والاستطاعة. المُصرَّف في المرتبة الثانية + المصدر في النهاية.",
 rule:"ich kann, du kannst, er kann… + Infinitiv am Ende: Ich kann schwimmen.",
 keywords:["können","kann","يستطيع","Modalverb","schwimmen","Fähigkeit"],
 tables:[{cap:"können — Präsens",head:["ich","du","er","wir","ihr","sie"],rows:[["kann","kannst","kann","können","könnt","können"]]}],
 examples:[["Ich kann schwimmen.","أستطيع السباحة."],["Kannst du Auto fahren?","هل تستطيع قيادة السيارة؟"],["Er kann kein Deutsch sprechen.","لا يستطيع التحدث بالألمانية."]],
 notes:["ich/er بلا نهاية (شاذ).","Kann ich…؟ = طلب إذن مهذب."],
 mistakes:[{w:"Ich kann schwimme.",r:"Ich kann schwimmen.",why:"المصدر الكامل في النهاية."}],
 related:["f-modal","i-fragen","o-alltag"],
 quiz:[{q:"Ich ___ schwimmen. (أستطيع)",opts:["kann","kannst","können"],correct:0,why:"ich kann."},{q:"können تعني…",opts:["يستطيع","يجب","يريد"],correct:0,why:"القدرة."}]},
{id:"f-w-muessen",level:"A1",de:"müssen",ar:"يجب (فعل ناقص)",en:"must, to have to (modal)",
 what:"فعل ناقص للوجوب والضرورة.",
 rule:"ich muss, du musst, er muss… + Infinitiv: Ich muss arbeiten. النفي: nicht brauchen / müssen nicht.",
 keywords:["müssen","muss","يجب","Modalverb","arbeiten","Pflicht"],
 tables:[{cap:"müssen — Präsens",head:["ich","du","er","wir","ihr","sie"],rows:[["muss","musst","muss","müssen","müsst","müssen"]]}],
 examples:[["Ich muss heute arbeiten.","يجب أن أعمل اليوم."],["Du musst zum Arzt.","يجب أن تذهب للطبيب."],["Wir müssen Deutsch lernen.","علينا تعلم الألمانية."]],
 notes:["müssen nicht = لا يجب (غير ضروري) ≠ لا يجوز!","المنع = dürfen nicht."],
 mistakes:[{w:"Ich müsse",r:"Ich muss",why:"شاذة بلا نهاية مع ich."}],
 related:["f-modal","m-verbstellung","g-praeteritum"],
 quiz:[{q:"Ich ___ heute arbeiten.",opts:["muss","müsse","musst"],correct:0,why:"ich muss."},{q:"müssen تعني…",opts:["يجب","يستطيع","يحب"],correct:0,why:"الوجوب."}]},
{id:"f-w-wollen",level:"A1",de:"wollen",ar:"يريد (فعل ناقص)",en:"to want to (modal)",
 what:"فعل ناقص للإرادة القوية والنية.",
 rule:"ich will, du willst, er will… + Infinitiv. للطلب المهذب استخدم möchten.",
 keywords:["wollen","will","يريد","Modalverb","Absicht","Wunsch"],
 tables:[{cap:"wollen — Präsens",head:["ich","du","er","wir","ihr","sie"],rows:[["will","willst","will","wollen","wollt","wollen"]]}],
 examples:[["Ich will nach Berlin fahren.","أريد السفر إلى برلين."],["Was willst du trinken?","ماذا تريد أن تشرب؟"]],
 notes:["wollen قوية ومباشرة — مع الغرباء استخدم möchten.","wollte الماضي في g-praeteritum."],
 mistakes:[{w:"Ich wolle",r:"Ich will",why:"شاذة: ich will."}],
 related:["f-modal","f-w-moechten","o-situationen"],
 quiz:[{q:"Er ___ Kaffee. (يريد)",opts:["will","wolle","wollen"],correct:0,why:"er will."},{q:"للطلب المهذب بدل wollen…",opts:["müssen","möchten","sollen"],correct:1,why:"möchten ألطف."}]},
{id:"f-w-sollen",level:"A1",de:"sollen",ar:"ينبغي (فعل ناقص)",en:"should, to be supposed to (modal)",
 what:"فعل ناقص للنصيحة والواجب الخارجي (قالوا لك افعل).",
 rule:"ich soll, du sollst, er soll… + Infinitiv: Du sollst zum Arzt.",
 keywords:["sollen","soll","ينبغي","يجب","Modalverb","Rat","Arzt"],
 tables:[{cap:"sollen — Präsens",head:["ich","du","er","wir","ihr","sie"],rows:[["soll","sollst","soll","sollen","sollt","sollen"]]}],
 examples:[["Du sollst mehr Wasser trinken.","ينبغي أن تشرب ماءً أكثر."],["Ich soll meine Mutter anrufen.","يُفترض أن أتصل بأمي."]],
 notes:["sollen = نصيحة/أمر خارجي، müssen = ضرورة داخلية.","sollte الماضي تُستخدم للنصيحة اللطيفة."],
 mistakes:[{w:"Du soll",r:"Du sollst",why:"du + st."}],
 related:["f-modal","o-situationen"],
 quiz:[{q:"Du ___ zum Arzt. (ينبغي)",opts:["soll","sollst","sollen"],correct:1,why:"du sollst."},{q:"sollen تعني…",opts:["ينبغي","يريد","يُسمح"],correct:0,why:"الواجب الخارجي/النصيحة."}]},
{id:"f-w-duerfen",level:"A1",de:"dürfen",ar:"يُسمح (فعل ناقص)",en:"to be allowed to (modal)",
 what:"فعل ناقص للإذن والسماح. نفيه = المنع.",
 rule:"ich darf, du darfst, er darf… + Infinitiv. Darf ich…؟ = هل يُسمح لي؟",
 keywords:["dürfen","darf","يُسمح","مسموح","Modalverb","Erlaubnis","rauchen"],
 tables:[{cap:"dürfen — Präsens",head:["ich","du","er","wir","ihr","sie"],rows:[["darf","darfst","darf","dürfen","dürft","dürfen"]]}],
 examples:[["Darf ich hier rauchen?","هل يُسمح لي بالتدخين هنا؟"],["Kinder dürfen das nicht.","لا يجوز للأطفال ذلك."]],
 notes:["dürfen nicht = ممنوع (أقوى من müssen nicht!).","Durfte الماضي في g-praeteritum."],
 mistakes:[{w:"Ich dürfe",r:"Ich darf",why:"شاذة بلا نهاية."}],
 related:["f-modal","o-alltag"],
 quiz:[{q:"___ ich hier sitzen؟ (هل يُسمح)",opts:["Darf","Darfst","Dürfen"],correct:0,why:"ich darf (سؤال: Darf ich)."} ,{q:"dürfen nicht تعني…",opts:["ممنوع","غير ضروري","مسموح"],correct:0,why:"نفي الإذن = منع."}]},
{id:"f-w-moegen",level:"A1",de:"mögen",ar:"يحب (فعل ناقص)",en:"to like (modal)",
 what:"فعل ناقص للحب والتفضيل. غالبًا مع اسم (Ich mag Tee) أو möchten للطلب.",
 rule:"ich mag, du magst, er mag… Ich mag + اسم (Akk).",
 keywords:["mögen","mag","يحب","Modalverb","Tee","gern"],
 tables:[{cap:"mögen — Präsens",head:["ich","du","er","wir","ihr","sie"],rows:[["mag","magst","mag","mögen","mögt","mögen"]]}],
 examples:[["Ich mag Schokolade.","أحب الشوكولاتة."],["Magst du Kaffee?","هل تحب القهوة؟"]],
 notes:["mögen + اسم مباشرة (بدون فعل آخر غالبًا).","gern/lieber للتفضيل مع الأفعال (e-steigerung)."],
 mistakes:[{w:"Ich möge Tee.",r:"Ich mag Tee.",why:"ich mag."}],
 related:["f-modal","f-w-moechten","e-steigerung"],
 quiz:[{q:"Ich ___ Schokolade.",opts:["mag","möge","magst"],correct:0,why:"ich mag."},{q:"mögen تعني…",opts:["يحب","يريد","يجب"],correct:0,why:"الحب."}]},
{id:"f-w-moechten",level:"A1",de:"möchten",ar:"يود (صيغة مهذبة)",en:"would like (polite)",
 what:"صيغة التمني المهذبة من mögen — ملكة الطلبات: في المطعم والمحل ومع الغرباء.",
 rule:"ich möchte, du möchtest… + اسم أو مصدر: Ich möchte einen Kaffee / Ich möchte zahlen.",
 keywords:["möchten","möchte","يود","مهذب","Modalverb","Kaffee","Restaurant","höflich"],
 tables:[{cap:"möchten — Präsens",head:["ich","du","er","wir","ihr","sie"],rows:[["möchte","möchtest","möchte","möchten","möchtet","möchten"]]}],
 examples:[["Ich möchte einen Tee.","أود شايًا."],["Möchten Sie zahlen?","هل تود الدفع؟ (للزبون)"]],
 notes:["möchten ليست في الماضي — استخدم wollten.","ألطف من wollen في كل الطلبات."],
 mistakes:[{w:"Ich will einen Kaffee. (للحارس!)",r:"Ich möchte einen Kaffee.",why:"التهذيب مع الغرباء."}],
 related:["f-modal","f-w-moegen","o-situationen"],
 quiz:[{q:"Ich ___ einen Tee. (أود)",opts:["möchte","möchtest","möchten"],correct:0,why:"ich möchte."},{q:"möchten تُستخدم…",opts:["للطلب المهذب","للمنع","للسؤال عن القدرة"],correct:0,why:"صيغة التهذيب."}]}
];
