/* Deutsch Master — Reference data: path G (Zeiten) + path J (Zeit & Datum). Pure data. */
"use strict";
var REF_G=[
{id:"g-praesens",level:"A1",de:"Präsens",ar:"المضارع (الحاضر)",en:"Present tense",
 what:"يعبّر عن الحاضر والعادة، وأيضا عن المستقبل القريب مع كلمة زمنية (Morgen fahre ich = غدًا أسافر).",
 rule:"التصريف في f-grundlagen. مع ظروف التكرار (immer/oft/nie) يصف العادات.",
 keywords:["Präsens","حاضر","مضارع","lerne","fahre","Tense"],
 tables:[{cap:"الأزمنة الأربعة — نظرة شاملة",head:["الزمن","الاستخدام","التركيب","مثال"],rows:[["Präsens","الحاضر والعادة","الفعل مُصرَّف","Ich lerne Deutsch."],["Perfekt","الماضي في الكلام","haben/sein + Partizip II","Ich habe gelernt."],["Präteritum","الماضي الكتابي","صيغة الماضي","Ich war zu Hause."],["Futur I","المستقبل","werden + Infinitiv","Ich werde lernen."]]},{cap:"استخدامات Präsens",head:["الاستخدام","مثال","المعنى"],rows:[["الحاضر الآن","Ich lerne jetzt.","أتعلم الآن."],["العادة","Er trinkt gern Kaffee.","يشرب القهوة عادة."],["المستقبل القريب + وقت","Morgen fahre ich nach Berlin.","غدًا أسافر إلى برلين."]]}],
 examples:[["Ich wohne in Kairo.","أسكن في القاهرة."],["Morgen besuche ich dich.","غدًا أزورك."],["Er arbeitet jeden Tag.","يعمل كل يوم."]],
 notes:["لا يوجد مضارع مستمر منفصل مثل الإنجليزية: Ich lerne = أتعلم/أنا أتعلم الآن.","المستقبل بـ Präsens + وقت هو الأكثر استخداما يوميًا."],
 mistakes:[{w:"Ich bin lernen.",r:"Ich lerne.",why:"لا يوجد am + فعل في الألمانية."}],
 related:["f-grundlagen","g-perfekt","g-praeteritum","g-futur1","j-zeitwoerter"],
 quiz:[{q:"Morgen ___ ich nach Berlin. (fahren)",opts:["fahre","fährt","gefahren"],correct:0,why:"Präsens + وقت للمستقبل القريب."},{q:"أي جملة عن العادة؟",opts:["Ich lerne jetzt.","Er trinkt gern Kaffee.","Morgen fahre ich."],correct:1,why:"gern + Präsens يصف العادة."}]},
{id:"g-perfekt",level:"A1",de:"Perfekt",ar:"الماضي التام (المحكي)",en:"Present perfect (spoken past)",
 what:"ماضي الكلام اليومي: فعل مساعد (haben/sein) في المرتبة الثانية + Partizip II في نهاية الجملة.",
 rule:"معظم الأفعال مع haben. مع sein: أفعال الحركة (gehen/kommen/fahren) + تغيّر الحالة (aufstehen/sterben) + sein/bleiben/werden.",
 keywords:["Perfekt","ماضي","haben","sein","Partizip","gelernt","gekommen","Tense","ماض"],
 tables:[{cap:"haben أم sein؟",head:["haben (الأغلب)","sein (حركة/تغير)"],rows:[["lernen → habe gelernt","gehen → bin gegangen"],["kaufen → habe gekauft","kommen → bin gekommen"],["sehen → habe gesehen","aufstehen → bin aufgestanden"]]},{cap:"الأزمنة مقارنة (نفس الفعل)",head:["Präsens (حاضر)","Perfekt (ماضٍ محكي)","Präteritum (ماضٍ كتابي)"],rows:[["Ich lerne.","Ich habe gelernt.","Ich lernte."]]}],
 examples:[["Ich habe Deutsch gelernt.","تعلمت الألمانية."],["Er ist nach Berlin gefahren.","سافر إلى برلين."],["Wir haben einen Film gesehen.","شاهدنا فيلمًا."]],
 notes:["المحكي Perfekt، والكتابي/الرسمي Präteritum غالبا.","الاختيار الخاطئ بين haben/sein من أشهر أخطاء A1."],
 mistakes:[{w:"Ich bin gelernt.",r:"Ich habe gelernt.",why:"lernen بلا حركة: haben."},{w:"Er hat gekommen.",r:"Er ist gekommen.",why:"kommen حركة: sein."}],
 related:["g-praesens","g-partizip2","g-praeteritum","f-shw","f-trennbar","f-untrennbar","p-vergleiche"],
 quiz:[{q:"Ich ___ gelernt. (haben/sein)",opts:["habe","bin","bist"],correct:0,why:"lernen مع haben."},{q:"Er ___ gekommen.",opts:["hat","ist","haben"],correct:1,why:"kommen حركة مع sein."},{q:"أين Partizip II في الجملة؟",opts:["المرتبة 2","نهاية الجملة","البداية"],correct:1,why:"المساعد في 2 + Partizip في النهاية."},{q:"lernen في Perfekt يأخذ sein.",opts:["صحيح","خطأ"],correct:1,why:"بلا حركة = haben."},{type:"order",q:"رتب: تعلمت الألمانية",words:["Ich","habe","Deutsch","gelernt."],answer:"Ich habe Deutsch gelernt.",why:"فاعل + مساعد + مفعول + Partizip في النهاية."}]},
{id:"g-partizip2",level:"A1",de:"Partizip II",ar:"اسم المفعول (التصريف الثالث)",en:"Past participle",
 what:"الجزء الثاني من Perfekt. قواعده تعتمد على نوع الفعل: منتظم، شاذ، منتهٍ بـ ieren، منفصل، غير منفصل.",
 rule:"منتظم: ge + الجذر + t. شاذ: يُحفظ (gesprochen). ieren: بدون ge (studiert). منفصل: ge في الوسط (aufgestanden). غير منفصل: بلا ge (verstanden).",
 keywords:["Partizip","gespielt","gesprochen","studiert","ge-","تصريف ثالث"],
 tables:[{cap:"تكوين Partizip II",head:["النوع","القاعدة","مثال"],rows:[["منتظم","ge + Stamm + t","spielen → gespielt"],["شاذ","يُحفظ","sprechen → gesprochen"],["ieren-","بدون ge + t","studieren → studiert"],["منفصل","المقطع + ge + t","aufstehen → aufgestanden"],["غير منفصل","بلا ge","verstehen → verstanden"]]}],
 examples:[["Ich habe Fußball gespielt.","لعبت كرة القدم."],["Sie hat viel gesprochen.","تحدثت كثيرًا."],["Er hat in Kairo studiert.","درس في القاهرة."]],
 notes:["قائمة الأفعال الشاذة تُحفظ تدريجيًا — ابدأ بـ 20 فعلًا.","القاعدة الذهبية: ge في البداية إلا ieren وغير المنفصل."],
 mistakes:[{w:"gespielt mit haben؟ (صحيحة!) — الخطأ: Ich bin gespielt.",r:"Ich habe gespielt.",why:"spielen مع haben."}],
 related:["g-perfekt","f-arten","f-trennbar","f-untrennbar"],
 quiz:[{q:"Partizip II من aufstehen؟",opts:["aufgesteht","aufgestanden","geaufsteht"],correct:1,why:"منفصل: ge في الوسط + شاذ."},{q:"Partizip II من studieren؟",opts:["gestudiert","studiert","studieren"],correct:1,why:"ieren- بدون ge."}]},
{id:"g-praeteritum",level:"A2",de:"Präteritum",ar:"الماضي البسيط (الكتابي)",en:"Simple past",
 what:"ماضي الكتابة والقصص. في A1/A2 يكفي حفظ الأشكال الأساسية: war, hatte, wurde + الماضي الناقص (konnte, musste...).",
 rule:"sein → war, haben → hatte, werden → wurde. الناقصة: konnte, musste, wollte, durfte, sollte, mochte.",
 keywords:["Präteritum","war","hatte","wurde","konnte","musste","ماضي","كان"],
 tables:[{cap:"Präteritum الأساسي (ich/er)",head:["الفعل","ich/er","مثال"],rows:[["sein","war","Das war gut."],["haben","hatte","Ich hatte keine Zeit."],["werden","wurde","Er wurde Lehrer."],["können","konnte","Ich konnte nicht kommen."],["müssen","musste","Er musste arbeiten."],["wollen","wollte","Sie wollte Kaffee."],["dürfen","durfte","Wir durften gehen."],["sollen","sollte","Ich sollte lernen."]]}],
 examples:[["Das Wetter war schön.","كان الطقس جميلًا."],["Ich hatte gestern keine Zeit.","لم يكن لديّ وقت أمس."],["Er konnte nicht kommen.","لم يستطع المجيء."]],
 notes:["في الكلام اليومي استخدم Perfekt، وفي القصص Präteritum.","war/hatte هما الأكثر استخداما على الإطلاق."],
 mistakes:[{w:"Ich hattet",r:"Ich hatte",why:"hatte ثابتة مع ich/er."}],
 related:["g-perfekt","f-shw","f-modal","p-vergleiche"],
 quiz:[{q:"Präteritum من sein (ich)؟",opts:["war","warte","gewesen"],correct:0,why:"ich war."},{q:"Präteritum من können (er)؟",opts:["kann","konnte","gekonnt"],correct:1,why:"er konnte."}]},
{id:"g-futur1",level:"A2",de:"Futur I",ar:"المستقبل",en:"Future tense",
 what:"يُبنى بـ werden (مُصرَّف) + المصدر في النهاية. يوميًا يكفي Präsens مع وقت مستقبلي.",
 rule:"Ich werde lernen. السؤال: Wirst du kommen؟ النفي: Ich werde nicht kommen.",
 keywords:["Futur","werden","مستقبل","werde","wirst","Zukunft"],
 tables:[{cap:"Futur I",head:["الضمير","werden","مثال"],rows:[["ich","werde","Ich werde lernen."],["du","wirst","Du wirst kommen."],["er","wird","Er wird arbeiten."]]}],
 examples:[["Ich werde morgen anrufen.","سأتصل غدًا."],["Es wird regnen.","ستمطر."]],
 notes:["الألمان يتحدثون عن المستقبل بـ Präsens غالبا: Morgen rufe ich an.","werden هنا مساعد مستقبل لا فعل يصبح."],
 mistakes:[{w:"Ich werde lerne.",r:"Ich werde lernen.",why:"المصدر الكامل في النهاية."}],
 related:["g-praesens","f-shw","j-zeitwoerter"],
 quiz:[{q:"Ich ___ morgen anrufen.",opts:["werde","wird","worden"],correct:0,why:"ich werde + مصدر."}]}
];
var REF_J=[
{id:"j-uhrzeit",level:"A1",de:"Uhrzeit",ar:"الساعة",en:"Telling the time",
 what:"السؤال: Wie spät ist es؟ / Wie viel Uhr ist es؟ الرد: Es ist … halb تعني والنصف (نصف نحو الساعة التالية!).",
 rule:"halb acht = 7:30 (نصف الثامنة أي متجهة للثامنة). Viertel nach = والربع، Viertel vor = إلا الربع، vor/nach للدقائق.",
 keywords:["Uhrzeit","Uhr","halb","Viertel","vor","nach","ساعة","وقت","Es ist"],
 tables:[{cap:"قراءة الساعة",head:["الوقت","تُقال","المعنى"],rows:[["7:00","Es ist sieben Uhr.","السابعة"],["7:15","Viertel nach sieben","السابعة والربع"],["7:30","halb acht","السابعة والنصف"],["7:45","Viertel vor acht","الثامنة إلا الربع"],["8:10","zehn nach acht","الثامنة وعشر"]]}],
 examples:[["Der Zug kommt um halb acht.","يصل القطار السابعة والنصف."],["Wir treffen uns um Viertel nach drei.","نلتقي الثالثة والربع."]],
 notes:["halb + الساعة التالية: halb acht = 7:30 وليس 8:30!","um + الوقت للمواعيد: um drei Uhr."],
 mistakes:[{w:"halb acht = 8:30",r:"halb acht = 7:30",why:"نصف نحو الثامنة أي 7:30."}],
 related:["j-tageszeiten","k-zahlen","o-situationen"],
 quiz:[{q:"halb acht = ؟",opts:["8:30","7:30","8:00"],correct:1,why:"نصف نحو الثامنة."},{q:"Viertel nach drei = ؟",opts:["3:15","3:45","2:45"],correct:0,why:"والربع."},{q:"halb acht تعني 8:30.",opts:["صحيح","خطأ"],correct:1,why:"تعني 7:30."}]},
{id:"j-tage",level:"A1",de:"Wochentage",ar:"أيام الأسبوع",en:"Days of the week",
 what:"سبعة أيام، كلها مذكرة (der). مع حرف الجر am: am Montag (يوم الاثنين).",
 rule:"Montag, Dienstag, Mittwoch, Donnerstag, Freitag, Samstag/Sonnabend, Sonntag. نهاية الأسبوع = das Wochenende.",
 keywords:["Montag","Dienstag","Mittwoch","Donnerstag","Freitag","Samstag","Sonntag","أيام","Woche"],
 tables:[{cap:"الأيام",head:["اليوم","العربي","مثال"],rows:[["Montag","الاثنين","am Montag"],["Dienstag","الثلاثاء","am Dienstag"],["Mittwoch","الأربعاء","am Mittwoch"],["Donnerstag","الخميس","am Donnerstag"],["Freitag","الجمعة","am Freitag"],["Samstag","السبت","am Samstag"],["Sonntag","الأحد","am Sonntag"]]}],
 examples:[["Am Montag habe ich Deutsch.","يوم الاثنين لديّ ألماني."],["Schönes Wochenende!","نهاية أسبوع سعيدة!"]],
 notes:["Sonnabend = Samstag في الشمال.","الأيام تُكتب كبيرة لأنها أسماء."],
 mistakes:[{w:"in Montag",r:"am Montag",why:"الأيام مع am."}],
 related:["j-monate","j-zeitwoerter"],
 quiz:[{q:"___ Montag habe ich Deutsch.",opts:["in","am","um"],correct:1,why:"الأيام مع am."},{q:"اليوم بعد Freitag؟",opts:["Donnerstag","Samstag","Sonntag"],correct:1,why:"الجمعة ثم السبت."}]},
{id:"j-monate",level:"A1",de:"Monate",ar:"الشهور",en:"Months",
 what:"اثنا عشر شهرًا، كلها مذكرة. مع im: im Januar (في يناير).",
 rule:"Januar, Februar, März, April, Mai, Juni, Juli, August, September, Oktober, November, Dezember.",
 keywords:["Januar","Februar","März","April","Mai","Juni","Juli","August","September","Oktober","November","Dezember","شهور","Monate"],
 tables:[{cap:"الشهور",head:["الشهر","العربي","مثال"],rows:[["Januar","يناير","im Januar"],["Februar","فبراير","im Februar"],["März","مارس","im März"],["April","أبريل","im April"],["Mai","مايو","im Mai"],["Juni","يونيو","im Juni"],["Juli","يوليو","im Juli"],["August","أغسطس","im August"],["September","سبتمبر","im September"],["Oktober","أكتوبر","im Oktober"],["November","نوفمبر","im November"],["Dezember","ديسمبر","im Dezember"]]}],
 examples:[["Mein Geburtstag ist im Mai.","عيد ميلادي في مايو."],["Im Dezember ist es kalt.","في ديسمبر الجو بارد."]],
 notes:["März تُنطق ميرتس.","الشهور مع im دائما."],
 mistakes:[{w:"in Mai",r:"im Mai",why:"الشهور مع im (in + dem)."}],
 related:["j-tage","j-jahreszeiten"],
 quiz:[{q:"Mein Geburtstag ist ___ Mai.",opts:["in","im","am"],correct:1,why:"الشهور مع im."},{q:"الشهر بعد Juni؟",opts:["Mai","Juli","August"],correct:1,why:"يونيو ثم يوليو."}]},
{id:"j-jahreszeiten",level:"A1",de:"Jahreszeiten",ar:"فصول السنة",en:"Seasons",
 what:"أربعة فصول، كلها مذكرة ما عدا... كلها مذكرة: der Frühling, der Sommer, der Herbst, der Winter. مع im.",
 rule:"im Frühling, im Sommer, im Herbst, im Winter.",
 keywords:["Frühling","Sommer","Herbst","Winter","فصول","Jahreszeiten"],
 tables:[{cap:"الفصول",head:["الفصل","العربي","مثال"],rows:[["der Frühling","الربيع","im Frühling"],["der Sommer","الصيف","im Sommer"],["der Herbst","الخريف","im Herbst"],["der Winter","الشتاء","im Winter"]]}],
 examples:[["Im Sommer ist es heiß.","في الصيف الجو حار."],["Im Winter schneit es oft.","في الشتاء تثلج غالبا."]],
 notes:["كلها مذكرة: der.","الطقس المرتبط بكل فصل في المحادثات اليومية."],
 mistakes:[{w:"in Sommer",r:"im Sommer",why:"الفصول مع im."}],
 related:["j-monate","o-alltag"],
 quiz:[{q:"___ Winter schneit es.",opts:["In","Im","Am"],correct:1,why:"الفصول مع im."}]},
{id:"j-tageszeiten",level:"A1",de:"Tageszeiten",ar:"أجزاء اليوم",en:"Times of day",
 what:"تقسيم اليوم: الصباح، الظهيرة، المساء، الليل — مع حروف الجر الصحيحة لكل جزء.",
 rule:"am Morgen/Vormittag/Mittag/Nachmittag/Abend — aber: in der Nacht (مؤنث!).",
 keywords:["Morgen","Abend","Nacht","Mittag","Nachmittag","صباح","مساء","ليل"],
 tables:[{cap:"أجزاء اليوم",head:["الجزء","العربي","مع حرف الجر"],rows:[["der Morgen","الصباح","am Morgen"],["der Vormittag","قبل الظهر","am Vormittag"],["der Mittag","الظهر","am Mittag"],["der Nachmittag","بعد الظهر","am Nachmittag"],["der Abend","المساء","am Abend"],["die Nacht","الليل","in der Nacht"]]}],
 examples:[["Guten Morgen!","صباح الخير!"],["Am Abend sehe ich fern.","في المساء أشاهد التلفاز."],["In der Nacht schlafen wir.","في الليل ننام."]],
 notes:["التحيات: Morgen!/Tag!/Abend!/Gute Nacht!","Nacht مؤنثة لذلك in der Nacht."],
 mistakes:[{w:"am Nacht",r:"in der Nacht",why:"Nacht مؤنثة: in der."}],
 related:["j-uhrzeit","o-gruesse"],
 quiz:[{q:"___ der Nacht schlafen wir.",opts:["Am","In","Im"],correct:1,why:"in der Nacht."},{q:"تحية المساء؟",opts:["Guten Morgen!","Guten Abend!","Gute Nacht!"],correct:1,why:"Abend = مساء (Gute Nacht عند النوم)."}]},
{id:"j-zeitwoerter",level:"A1",de:"Zeitwörter",ar:"كلمات الزمن",en:"Time expressions",
 what:"كلمات تحدد متى يحدث الفعل: الماضي (gestern)، الحاضر (heute/jetzt)، المستقبل (morgen/bald)، التكرار (immer/oft/nie)، الترتيب (zuerst/dann).",
 rule:"كلمة الزمن غالبا في المرتبة الأولى أو بعد الفعل. الماضي الحقيقي يحتاج Perfekt/Präteritum معها.",
 keywords:["Zeit","gestern","heute","morgen","jetzt","oft","nie","immer","ماضي","وقت","زمن","damals","früher","Perfekt"],
 tables:[{cap:"الماضي",head:["الكلمة","العربي","مثال"],rows:[["gestern","أمس","Ich war gestern zu Hause."],["vorgestern","أول أمس","Vorgestern war Sonntag."],["früher / damals","سابقًا / في ذلك الوقت","Früher war alles anders."],["letzte Woche","الأسبوع الماضي","Letzte Woche war ich krank."],["vor zwei Tagen","قبل يومين","Vor zwei Tagen kam er."]]},{cap:"الحاضر والمستقبل",head:["الكلمة","العربي","مثال"],rows:[["heute / jetzt","اليوم / الآن","Ich lerne heute."],["morgen / übermorgen","غدًا / بعد غد","Morgen komme ich."],["bald / später","قريبًا / لاحقًا","Bis bald!"],["schon / noch","بالفعل / ما زال","Ich bin schon da."]]},{cap:"التكرار والترتيب",head:["الكلمة","العربي","مثال"],rows:[["immer / oft / manchmal / selten / nie","دائمًا/غالبًا/أحيانًا/نادرًا/أبدًا","Er kommt oft zu spät."],["zuerst / dann / danach / schließlich","أولًا/ثم/بعدها/أخيرًا","Zuerst lerne ich, dann spiele ich."]]},{cap:"كلمات إضافية مهمة",head:["الكلمة","العربي","مثال"],rows:[["gerade","الآن/للتو","Er ruft gerade an."],["vorher / nachher","قبلها / بعدها","Ruf vorher an!"],["gleich / sofort","حالًا / فورًا","Ich komme gleich."],["morgens / abends","صباحًا / مساءً (عادة)","Morgens trinke ich Tee."],["täglich / wöchentlich","يوميًا / أسبوعيًا","Ich lerne täglich."],["neulich / kürzlich","مؤخرًا","Neulich war ich krank."],["bisher","حتى الآن","Bisher alles gut."],["nachts","ليلًا (عادة)","Nachts ist es ruhig."]]}],
 examples:[["Ich war gestern zu Hause.","كنت في البيت أمس."],["Morgen fahre ich nach Berlin.","غدًا أسافر إلى برلين."],["Er kommt oft zu spät.","يأتي متأخرًا غالبا."]],
 notes:["الكلمات وحدها لا تصنع الماضي — الفعل هو الأساس (g-perfekt).","nie = أبدًا (نفي كامل) ≠ nicht (نفي عادي)."],
 mistakes:[{w:"Ich bin gestern lernen.",r:"Ich habe gestern gelernt.",why:"الماضي يحتاج Perfekt كاملًا."}],
 related:["g-perfekt","g-praesens","m-tmp","i-negation"],
 quiz:[{q:"___ war Sonntag. (أول أمس)",opts:["Gestern","Vorgestern","Morgen"],correct:1,why:"أول أمس = vorgestern."},{q:"أي كلمة للمستقبل؟",opts:["gestern","bald","nie"],correct:1,why:"bald = قريبًا."},{q:"Zuerst lerne ich, ___ spiele ich.",opts:["dann","gestern","nie"],correct:0,why:"ترتيب الأحداث: zuerst…dann."}]}
];
