/* Deutsch Master — Reference data: path D (Die vier Kasus). Pure data, see reference-data-bc.js for schema. */
"use strict";
var REF_D=[
{id:"d-nominativ",level:"A1",de:"Nominativ",ar:"حالة الفاعل (Nominativ)",en:"Nominative case",
 what:"حالة الفاعل الذي يقوم بالفعل، وحالة الاسم بعد sein/werden/bleiben (Er ist Lehrer). تجيب عن: Wer؟ (من) و Was؟ (ماذا).",
 rule:"الفاعل دائما في Nominativ. بعد sein لا يوجد مفعول: Ich bin Schüler (وليس Schüler في حالة أخرى).",
 keywords:["Nominativ","فاعل","Wer","Was","Nomen","Kasus","حالات","حالة"],
 tables:[{cap:"Nominativ — الأدوات",head:["maskulin","feminin","neutral","Plural"],rows:[["der","die","das","die"]]},{cap:"Nominativ — الضمائر",head:["ich","du","er","sie","es","wir","ihr","sie","Sie"],rows:[["ich","du","er","sie","es","wir","ihr","sie","Sie"]]}],
 examples:[["Der Mann trinkt Kaffee.","الرجل يشرب قهوة."],["Die Frau liest ein Buch.","المرأة تقرأ كتابًا."],["Er ist Lehrer.","هو معلم."]],
 notes:["القاموس يكتب m/f/n بدل der/die/das.","الجملة تبدأ غالبا بالفاعل لكن ليس دائما (انظر m-tmp)."],
 mistakes:[{w:"Mich bin Schüler.",r:"Ich bin Schüler.",why:"الفاعل يحتاج ضمير Nominativ: ich."}],
 related:["b-artikel-bestimmt","c-personal","d-vergleich","d-akkusativ"],
 quiz:[{q:"حدد الفاعل: Die Frau liest ein Buch.",opts:["Die Frau","ein Buch","liest"],correct:0,why:"من يقرأ؟ المرأة = الفاعل."},{q:"___ ist Lehrer. (هو)",opts:["Ihn","Ihm","Er"],correct:2,why:"الفاعل Nominativ: er."}]},
{id:"d-akkusativ",level:"A1",de:"Akkusativ",ar:"حالة المفعول المباشر (Akkusativ)",en:"Accusative case",
 what:"حالة المفعول المباشر الذي يقع عليه الفعل، وحالة تعبيرات زمنية بدون حرف جر (jeden Tag). تجيب عن: Wen؟ (من) و Was؟ (ماذا).",
 rule:"أفعال كثيرة تأخذ Akkusativ: sehen, haben, brauchen, kaufen, lesen, trinken. يتغير المذكر فقط: der → den.",
 keywords:["Akkusativ","مفعول","Wen","Was","den","Kasus","حالات"],
 tables:[{cap:"Akkusativ — الأدوات",head:["maskulin","feminin","neutral","Plural"],rows:[["den","die","das","die"]]},{cap:"Akkusativ — الضمائر",head:["ich","du","er","sie","es","wir","ihr","sie","Sie"],rows:[["mich","dich","ihn","sie","es","uns","euch","sie","Sie"]]}],
 examples:[["Ich kaufe den Tee.","أشتري الشاي."],["Er trinkt einen Kaffee.","هو يشرب قهوة."],["Ich besuche dich morgen.","سأزورك غدًا."]],
 notes:["المؤنث والمحايد والجمع لا تتغير أداتها في Akkusativ.","jeden Tag / jede Woche تعبيرات زمنية في Akkusativ بدون حرف جر.","حروف الجر المرتبطة: durch/für/gegen/ohne/um (h-akkusativ) + المتغيرة في الحركة (h-wechsel).","الأفعال المرتبطة: sehen, haben, brauchen, kaufen, lesen (f-akkusativ-verben)."],
 mistakes:[{w:"Ich sehe der Film.",r:"Ich sehe den Film.",why:"المفعول المذكر: den."}],
 related:["d-nominativ","c-personal","h-akkusativ","d-vergleich","f-akkusativ-verben"],
 quiz:[{q:"Ich kaufe ___ Tisch. (مذكر، مفعول)",opts:["der","den","dem"],correct:1,why:"Akkusativ مذكر = den."},{q:"Wen siehst du؟ تسأل عن…",opts:["الفاعل","المفعول (Akkusativ)","الملكية"],correct:1,why:"wen = سؤال Akkusativ."}]},
{id:"d-dativ",level:"A1",de:"Dativ",ar:"حالة المفعول غير المباشر (Dativ)",en:"Dative case",
 what:"حالة المستفيد أو المتأثر: أعطي لمن؟ أساعد من؟ تجيب عن: Wem؟ (لمن). تأتي مع أفعال مثل helfen/danken ومع حروف جر مثل mit/nach/bei.",
 rule:"الأدوات: dem/der/dem/den+n. الضمائر: mir/dir/ihm/ihr. في الجملة: الضمير Dativ قبل اسم Akkusativ (Ich gebe dir das Buch).",
 keywords:["Dativ","Wem","dem","mir","helfen","لمن","Kasus","حالات"],
 tables:[{cap:"Dativ — الأدوات",head:["maskulin","feminin","neutral","Plural"],rows:[["dem","der","dem","den + n"]]},{cap:"Dativ — الضمائر",head:["ich","du","er","sie","es","wir","ihr","sie","Sie"],rows:[["mir","dir","ihm","ihr","ihm","uns","euch","ihnen","Ihnen"]]}],
 examples:[["Sie dankt mir.","هي تشكرني."],["Ich danke dir.","أشكرك."],["Ich fahre mit dem Bus.","أنا أذهب بالحافلة."],["Sie spricht mit meinem Freund.","هي تتحدث مع صديقي."],["Ich helfe meinem Bruder.","أساعد أخي."],["Das Buch gehört dem Schüler.","الكتاب ملك التلميذ."]],
 notes:["أفعال Dativ شائعة: helfen, danken, gehören, gefallen, antworten.","حروف جر Dativ في h-dativ.","حروف الجر المرتبطة: aus/bei/mit/nach/seit/von/zu (h-dativ) + المتغيرة في الثبات (h-wechsel).","الأفعال المرتبطة: helfen, danken, gehören, gefallen (f-dativ-verben)."],
 mistakes:[{w:"Er hilft mich.",r:"Er hilft mir.",why:"helfen تأخذ Dativ: mir."},{w:"mit den Bus",r:"mit dem Bus",why:"mit + Dativ محايد: dem."}],
 related:["d-nominativ","c-personal","h-dativ","f-dativ-verben","d-vergleich"],
 quiz:[{q:"Er hilft ___. (أنا)",opts:["mich","mir","ich"],correct:1,why:"helfen + Dativ: mir."},{q:"Ich fahre mit ___ Bus.",opts:["den","dem","der"],correct:1,why:"mit + Dativ: dem Bus."},{q:"Wem؟ تسأل عن…",opts:["Nominativ","Akkusativ","Dativ"],correct:2,why:"wem = سؤال Dativ."}]},
{id:"d-genitiv",level:"B1",de:"Genitiv",ar:"حالة الملكية (Genitiv)",en:"Genitive case",
 what:"حالة الملكية والانتماء: سيارة والدي = das Auto meines Vaters. تجيب عن: Wessen؟ (ملك من). في اللغة اليومية يُستبدل غالبا بـ von + Dativ.",
 rule:"الأدوات: des/der/des/der. المذكر والمحايد يضيفان s/es للاسم: des Mannes. البديل الشائع: das Auto von meinem Vater.",
 keywords:["Genitiv","Wessen","des","ملكية","von","trotz","während","wegen"],
 tables:[{cap:"Genitiv — الأدوات",head:["maskulin","feminin","neutral","Plural"],rows:[["des + s","der","des + s","der"]]}],
 examples:[["Das Auto meines Vaters ist neu.","سيارة والدي جديدة."],["Trotz des Wetters gehen wir spazieren.","رغم الطقس نخرج للنزهة."],["Das ist das Buch meiner Schwester.","هذا كتاب أختي."]],
 notes:["يوميًا: von + Dativ بدل Genitiv (das Auto von meinem Vater).","trotz/während/wegen تأخذ Genitiv (التفصيل في h-genitiv)."],
 mistakes:[{w:"das Auto mein Vater",r:"das Auto meines Vaters",why:"الملكية تحتاج Genitiv أو von + Dativ."}],
 related:["d-vergleich","h-genitiv","b-artikel-bestimmt"],
 quiz:[{q:"Das Buch ___ Schwester. (ملكية، مؤنث)",opts:["meine","meiner","meinen"],correct:1,why:"Genitiv مؤنث: meiner Schwester."},{q:"Wessen؟ تسأل عن…",opts:["الفاعل","المفعول","الملكية (Genitiv)"],correct:2,why:"wessen = سؤال Genitiv."}]},
{id:"d-vergleich",level:"A1",de:"Kasus im Vergleich",ar:"جدول المقارنة بين الحالات الأربع",en:"Cases compared",
 what:"جدول مركزي يقارن الحالات الأربع: السؤال، الاستخدام، الأدوات، والضمائر — للمراجعة السريعة قبل أي اختبار.",
 rule:"احفظ الترتيب: Nominativ (الفاعل) ← Akkusativ (المفعول) ← Dativ (المستفيد) ← Genitiv (الملكية).",
 keywords:["Kasus","Vergleich","Fälle","مقارنة","حالات","Nominativ","Akkusativ","Dativ","Genitiv","حالة","إعراب"],
 tables:[{cap:"الحالات الأربع — الأسئلة والاستخدام",head:["الحالة","السؤال","الاستخدام","مثال"],rows:[["Nominativ","Wer? Was?","الفاعل","Der Mann schläft."],["Akkusativ","Wen? Was?","المفعول المباشر","Ich sehe den Mann."],["Dativ","Wem?","المستفيد / غير المباشر","Ich helfe dem Mann."],["Genitiv (B1)","Wessen?","الملكية","Das Auto des Mannes."]]},{cap:"الأدوات في الحالات الأربع",head:["","maskulin","feminin","neutral","Plural"],rows:[["Nominativ","der","die","das","die"],["Akkusativ","den","die","das","die"],["Dativ","dem","der","dem","den"],["Genitiv","des","der","des","der"]]},{cap:"الضمائر (er كمثال)",head:["Nominativ","Akkusativ","Dativ"],rows:[["er","ihn","ihm"]]},{cap:"النكرة والنفي والملكية (مذكر/مؤنث)",head:["","ein (m)","eine (f)","kein (m)","mein (m)"],rows:[["Nominativ","ein","eine","kein","mein"],["Akkusativ","einen","eine","keinen","meinen"],["Dativ","einem","einer","keinem","meinem"]]}],
 examples:[["Der Mann schläft. / Ich sehe den Mann. / Ich helfe dem Mann.","الرجل نائم. / أرى الرجل. / أساعد الرجل."],["Die Frau liest. / Ich kenne die Frau. / Ich danke der Frau.","المرأة تقرأ. / أعرف المرأة. / أشكر المرأة."],["Wer kommt? / Wen siehst du? / Wem hilfst du?","من يأتي؟ / من ترى؟ / من تساعد؟"]],
 notes:["نفس الاسم يتغير دوره بتغير الحالة — قارن الأمثلة الثلاثة.","ابدأ المراجعة من هنا ثم ادخل تفاصيل كل حالة."],
 mistakes:[{w:"الخلط بين den و dem للمذكر",r:"den = مفعول، dem = مستفيد",why:"den للـ Akkusativ و dem للـ Dativ."}],
 related:["d-nominativ","d-akkusativ","d-dativ","d-genitiv"],
 quiz:[{q:"Ich helfe dem Mann — dem Mann في حالة…",opts:["Nominativ","Akkusativ","Dativ"],correct:2,why:"helfen + المستفيد = Dativ."},{q:"Ich sehe den Mann — den Mann في حالة…",opts:["Nominativ","Akkusativ","Dativ"],correct:1,why:"المفعول المباشر = Akkusativ."},{q:"الجمع في الألمانية يأخذ die دائمًا.",opts:["صحيح","خطأ"],correct:0,why:"قاعدة ثابتة مهما كانت أداة المفرد."}]}
];
