/* Deutsch Master — Reference data: path H (Präpositionen). Pure data. */
"use strict";
var REF_H=[
{id:"h-akkusativ",level:"A1",de:"Akkusativpräpositionen",ar:"حروف الجر مع Akkusativ",en:"Prepositions with accusative",
 what:"خمسة حروف جر تأخذ Akkusativ دائما: durch, für, gegen, ohne, um — أي اسم بعدها منصوب (den/die/das).",
 rule:"احفظ المجموعة: durch für gegen ohne um. السؤال عنها غالبا Wen/Was؟",
 keywords:["Akkusativ","durch","für","gegen","ohne","um","Präposition","حروف الجر","bis"],
 tables:[{cap:"Akkusativpräpositionen",head:["الحرف","المعنى","مثال"],rows:[["durch","عبر / من خلال","Wir fahren durch die Stadt."],["für","من أجل / لـ","Das ist für dich."],["gegen","ضد / نحو (تقريبي)","Ich bin gegen 8 Uhr da."],["ohne","بدون (+ Akk)","Ohne dich geht es nicht."],["um","حول / في تمام (وقت)","Wir gehen um den Park."]]}],
 examples:[["Wir fahren durch die Stadt.","نمر عبر المدينة."],["Das Geschenk ist für dich.","الهدية لك."],["Ohne Fleiß kein Preis.","بدون اجتهاد لا جائزة."],["Der Unterricht beginnt um 9 Uhr.","يبدأ الدرس التاسعة."]],
 notes:["gegen للوقت التقريبي: gegen 8 Uhr = نحو الثامنة.","um + الوقت: um 9 Uhr (في تمام).","entlang (على طول) يأتي بعد الاسم غالبا — مستوى B1."],
 mistakes:[{w:"für dir",r:"für dich",why:"für + Akkusativ: dich."},{w:"ohne dem Auto",r:"ohne das Auto",why:"ohne + Akkusativ: das."}],
 related:["d-akkusativ","h-wechsel","h-dativ"],
 quiz:[{q:"Das ist ___ dich.",opts:["für","mit","bei"],correct:0,why:"für + Akkusativ."},{q:"Ohne ___ geht es nicht. (أنت)",opts:["dir","dich","du"],correct:1,why:"ohne + Akkusativ: dich."},{q:"Wir gehen um ___ Park.",opts:["der","den","dem"],correct:1,why:"um + Akkusativ مذكر: den."}]},
{id:"h-dativ",level:"A1",de:"Dativpräpositionen",ar:"حروف الجر مع Dativ",en:"Prepositions with dative",
 what:"ثمانية حروف جر تأخذ Dativ دائما: aus, bei, mit, nach, seit, von, zu, gegenüber — أي اسم بعدها مجرور (dem/der).",
 rule:"احفظ المجموعة كاملة. seit = منذ (مستمر حتى الآن)، vor = قبل/منذ (منتهٍ). nach للمدن والبلاد بلا أداة، zu للأشخاص والأماكن بأداة.",
 keywords:["Dativ","mit","aus","bei","nach","seit","von","zu","gegenüber","Präposition","حروف الجر","Bus"],
 tables:[{cap:"Dativpräpositionen",head:["الحرف","المعنى","مثال"],rows:[["aus","من (أصل/داخل)","Ich komme aus Ägypten."],["bei","عند / لدى","Ich bin bei meinem Freund."],["mit","مع / بـ (وسيلة)","Ich fahre mit dem Bus."],["nach","إلى (مدن/بلاد) / بعد","Ich fliege nach Berlin."],["seit","منذ (مستمر)","Ich lerne seit einem Jahr."],["von","من (شخص/مصدر)","Das ist von meinem Vater."],["zu","إلى (شخص/مكان بأداة)","Ich gehe zu meiner Oma."],["gegenüber","مقابل","Das Café ist gegenüber dem Bahnhof."]]}],
 examples:[["Ich spreche mit meinem Freund.","أتحدث مع صديقي."],["Nach der Arbeit gehe ich nach Hause.","بعد العمل أذهب للبيت."],["Ich wohne seit zwei Jahren hier.","أسكن هنا منذ سنتين."],["Kommst du zu mir?","هل تأتي إليّ؟"]],
 notes:["seit + زمن مستمر (حاضر)، vor + زمن منتهٍ (ماضٍ): seit einem Jahr أتعلم حتى الآن، vor einem Jahr حدث وانتهى.","nach Hause ثابتة بلا أداة.","gegenüber يأتي قبل الاسم حديثًا أو بعده: dem Bahnhof gegenüber."],
 mistakes:[{w:"mit den Bus",r:"mit dem Bus",why:"mit + Dativ: dem."},{w:"zu mein Freund",r:"zu meinem Freund",why:"zu + Dativ: meinem."},{w:"seit vor einem Jahr (خلط)",r:"seit einem Jahr (مستمر) / vor einem Jahr (منتهٍ)",why:"seit للحاضر المستمر و vor للماضي المنتهي."}],
 related:["d-dativ","h-wechsel","h-akkusativ","f-dativ-verben","j-zeitwoerter"],
 quiz:[{q:"Ich fahre ___ dem Bus.",opts:["mit","für","ohne"],correct:0,why:"mit + Dativ."},{q:"Ich komme ___ Ägypten.",opts:["von","aus","bei"],correct:1,why:"الأصل/البلد: aus."},{q:"Ich lerne ___ einem Jahr Deutsch. (مستمر)",opts:["vor","seit","nach"],correct:1,why:"مستمر حتى الآن: seit."},{q:"Ich gehe ___ meiner Oma.",opts:["nach","zu","bei"],correct:1,why:"شخص بأداة: zu + Dativ."}]},
{id:"h-genitiv",level:"B1",de:"Genitivpräpositionen",ar:"حروف الجر مع Genitiv (متقدم)",en:"Prepositions with genitive (advanced)",
 what:"حروف جر تأخذ Genitiv وتظهر في اللغة الرسمية: während, wegen, trotz, statt. يوميًا يُستبدل بعضها بـ von + Dativ.",
 rule:"während (أثناء)، wegen (بسبب)، trotz (رغم)، statt (بدلًا من). المستوى B1 — للتعرف والقراءة.",
 keywords:["Genitiv","während","wegen","trotz","statt","von","رغم","بسبب"],
 tables:[{cap:"Genitivpräpositionen",head:["الحرف","المعنى","مثال"],rows:[["während","أثناء","Während des Films."],["wegen","بسبب","Wegen des Wetters."],["trotz","رغم","Trotz des Regens."],["statt","بدلًا من","Statt des Busses."]]}],
 examples:[["Während des Unterrichts sind Handys aus.","أثناء الدرس الهواتف مغلقة."],["Wegen des Lärms schlafe ich nicht.","بسبب الضجيج لا أنام."],["Trotz des Regens bleiben wir zu Hause.","رغم المطر نبقى في البيت."]],
 notes:["يوميًا: wegen + Dativ شائع (wegen dem Wetter) لكن الرسمي Genitiv.","trotz/wegen/statt قد تأتي مع von + Dativ في الكلام."],
 mistakes:[{w:"wegen dem Wetter (رسميًا)",r:"wegen des Wetters",why:"الرسمي Genitiv."}],
 related:["d-genitiv","h-dativ"],
 quiz:[{q:"___ des Wetters bleiben wir zu Hause. (بسبب)",opts:["Wegen","Trotz","Während"],correct:0,why:"بسبب = wegen."},{q:"Trotz des Regens gehen wir. المعنى…",opts:["بسبب المطر","رغم المطر","أثناء المطر"],correct:1,why:"trotz = رغم."}]},
{id:"h-wechsel",level:"A1",de:"Wechselpräpositionen",ar:"حروف الجر المتغيرة (Wo؟ / Wohin؟)",en:"Two-way prepositions",
 what:"تسعة حروف تتغير حالتها حسب المعنى: موقع ثابت (Wo؟) ← Dativ، وحركة نحو المكان (Wohin؟) ← Akkusativ.",
 rule:"an, auf, hinter, in, neben, über, unter, vor, zwischen. اسأل: أين؟ (ثابت = Dativ) أم إلى أين؟ (حركة = Akkusativ).",
 keywords:["Wechsel","Wo","Wohin","in","an","auf","Dativ","Akkusativ","Schule","حروف الجر","مكان","حركة"],
 tables:[{cap:"التسعة المتغيرة",head:["الحرف","المعنى"],rows:[["an","على (عمودي)/عند"],["auf","على (أفقي)/في مناسبة"],["hinter","خلف"],["in","في / إلى"],["neben","بجوار"],["über","فوق / عن"],["unter","تحت"],["vor","أمام / قبل"],["zwischen","بين"]]}],
 examples:[["Ich bin in der Schule.","أنا في المدرسة. (ثابت Wo ← Dativ)"],["Ich gehe in die Schule.","أنا ذاهب إلى المدرسة. (حركة Wohin ← Akkusativ)"],["Das Bild hängt an der Wand.","الصورة معلقة على الحائط."],["Er legt das Buch auf den Tisch.","يضع الكتاب على الطاولة."],["Die Kinder spielen vor dem Haus.","الأطفال يلعبون أمام البيت."]],
 notes:["in للمباني المغلقة، auf للأسطح والمناسبات (auf dem Markt/auf der Party)، an للجدران والمياه (am Meer).","استخدامات زمنية ثابتة: im Sommer (in+Dativ)، am Montag (an+Dativ).","الفرق بين الحركة والموقع هو أشهر قاعدة في A1 — راجع أمثلة in der/in die."],
 mistakes:[{w:"Ich gehe in der Schule. (بمعنى ذاهب)",r:"Ich gehe in die Schule.",why:"الحركة نحو المكان = Akkusativ."},{w:"Ich bin in die Schule. (بمعنى موجود)",r:"Ich bin in der Schule.",why:"الموقع الثابت = Dativ."}],
 related:["d-dativ","d-akkusativ","h-dativ","l-wo","l-wohin","j-tageszeiten"],
 quiz:[{q:"Ich bin ___ der Schule. (موجود)",opts:["in","nach","zu"],correct:0,why:"موقع ثابت + in + Dativ."},{q:"Ich gehe ___ die Schule. (ذاهب)",opts:["in","mit","bei"],correct:0,why:"حركة + in + Akkusativ."},{q:"Das Bild hängt an ___. (الحائط، ثابت)",opts:["die Wand","der Wand","den Wand"],correct:1,why:"ثابت + an + Dativ مؤنث: der Wand."},{q:"Wo؟ تجيب عنها حالة…",opts:["Akkusativ","Dativ","Nominativ"],correct:1,why:"الموقع الثابت = Dativ."},{q:"In die Schule تعني أنا موجود في المدرسة.",opts:["صحيح","خطأ"],correct:1,why:"in + Akk = حركة (ذاهب)، والوجود = in der."}]}
];
