/* Adjectives base|ar|en|lvl|comp|sup ; FUNC de|type|ar|en|cat|lvl ; PHRASES de|ar|en|cat|lvl */
"use strict";
const ADJ=[
"gut|جيد|good|A1|besser|best","schlecht|سيئ|bad|A1|schlechter|schlechtest",
"groß|كبير|big|A1|größer|größt","klein|صغير|small|A1|kleiner|kleinst",
"neu|جديد|new|A1|neuer|neuest","alt|قديم / عجوز|old|A1|älter|ältest",
"jung|شاب|young|A1|jünger|jüngst","schnell|سريع|fast|A1|schneller|am schnellsten",
"langsam|بطيء|slow|A1|langsamer|am langsamsten","lang|طويل|long|A1|länger|längst",
"kurz|قصير|short|A1|kürzer|kürzest","hoch|عالٍ|high|A1|höher|höchst",
"tief|عميق|deep|A2|tiefer|tiefst","breit|عريض|wide|A2|breiter|breitest",
"schmal|ضيق|narrow|A2|schmaler|schmalst","dick|سميك|thick|A2|dicker|dickst",
"dünn|رفيع|thin|A2|dünner|dünnst","schwer|ثقيل / صعب|heavy|A1|schwerer|schwerst",
"leicht|خفيف / سهل|light/easy|A1|leichter|leichtest","stark|قوي|strong|A1|stärker|stärkst",
"schwach|ضعيف|weak|A2|schwächer|schwächst","teuer|غالٍ|expensive|A1|teurer|teuerst",
"billig|رخيص|cheap|A1|billiger|billigst","reich|غني|rich|A2|reicher|reichst",
"arm|فقير|poor|A2|ärmer|ärmst","schön|جميل|beautiful|A1|schöner|schönst",
"hässlich|قبيح|ugly|A2|hässlicher|hässlichst","nett|لطيف|nice|A1|netter|nettest",
"freundlich|ودود|friendly|A1|freundlicher|freundlichst","unfreundlich|غير ودود|unfriendly|A2|unfreundlicher|unfreundlichst",
"höflich|مهذب|polite|A1|höflicher|höflichst","unhöflich|غير مهذب|impolite|A2|unhöflicher|unhöflichst",
"pünktlich|دقيق (مواعيد)|punctual|A1|pünktlicher|pünktlichst","unpünktlich|غير دقيق|unpunctual|A2|unpünktlicher|unpünktlichst",
"fleißig|مجتهد|diligent|A2|fleißiger|fleißigst","faul|كسول|lazy|A2|fauler|faulst",
"klug|ذكي|smart|A2|klüger|klügst","dumm|غبي|silly|A2|dümmer|dümmst",
"wichtig|مهم|important|A1|wichtiger|wichtigst","unwichtig|غير مهم|unimportant|A2|unwichtiger|unwichtigst",
"richtig|صحيح|correct|A1|richtiger|richtigst","falsch|خاطئ|wrong|A1|falscher|falschest",
"einfach|بسيط|simple|A1|einfacher|einfachst","kompliziert|معقد|complicated|A2|komplizierter|kompliziertest",
"modern|حديث|modern|A2|moderner|modernst","traditionell|تقليدي|traditional|A2|traditioneller|traditionellst",
"bekannt|معروف|known|A2|bekannter|bekanntest","unbekannt|مجهول|unknown|A2|unbekannter|unbekanntest",
"berühmt|مشهور|famous|A2|berühmter|berühmtest","beliebt|محبوب|popular|A2|beliebter|beliebtest",
"zufrieden|راضٍ|satisfied|A2|zufriedener|zufriedenst","unzufrieden|غير راضٍ|dissatisfied|A2|unzufriedener|unzufriedenst",
"glücklich|سعيد|happy|A1|glücklicher|glücklichst","unglücklich|تعيس|unhappy|A2|unglücklicher|unglücklichst",
"traurig|حزين|sad|A1|trauriger|traurigst","lustig|مضحك|funny|A1|lustiger|lustigst",
"ernst|جاد|serious|A2|ernster|ernstest","ruhig|هادئ|calm|A1|ruhiger|ruhigst",
"laut|صاخب|loud|A1|lauter|lautest","leise|خافت|quiet|A1|leiser|leisest",
"hell|فاتح / مضيء|bright|A1|heller|hellst","dunkel|داكن / مظلم|dark|A1|dunkler|dunkelst",
"warm|دافئ|warm|A1|wärmer|wärmst","kalt|بارد|cold|A1|kälter|kältest",
"heiß|حار|hot|A1|heißer|heißest","kühl|منعش / بارد|cool|A2|kühler|kühlst",
"trocken|جاف|dry|A2|trockener|trockenst","nass|مبلل|wet|A2|nasser|nassest",
"sauber|نظيف|clean|A1|sauberer|sauberst","schmutzig|متسخ|dirty|A1|schmutziger|schmutzigst",
"ordentlich|مرتب|tidy|A1|ordentlicher|ordentlichst","unordentlich|غير مرتب|untidy|A2|unordentlicher|unordentlichst",
"leer|فارغ|empty|A1|leerer|leerst","voll|ممتلئ|full|A1|voller|vollst",
"offen|مفتوح|open|A1|offener|offenst","geschlossen|مغلق|closed|A1|geschlossener|geschlossenst",
"frei|حر / متاح|free|A1|freier|freist","besetzt|مشغول|occupied|A2|besetzter|besetztest",
"verfügbar|متاح|available|A2|verfügbarer|verfügbarst","besonders|خاص|special|A2|besonderer|besonderst",
"normal|طبيعي|normal|A1|normaler|normalst","seltsam|غريب|strange|A2|seltsamer|seltsamst",
"interessant|مثير للاهتمام|interesting|A1|interessanter|interessantest","langweilig|ممل|boring|A1|langweiliger|langweiligst",
"spannend|مشوق|exciting|A1|spannender|spannendst","lustig2|ممتع|fun|A1|lustiger|lustigst",
"müde|متعب|tired|A1|müder|müdest","wach|مستيقظ|awake|A2|wacher|wachst",
"krank|مريض|sick|A1|kränker|kränkst","gesund|صحي|healthy|A1|gesünder|gesündest",
"fit|لائق|fit|A2|fitter|fittest","hungrig|جائع|hungry|A1|hungriger|hungrigst",
"durstig|عطشان|thirsty|A1|durstiger|durstigst","satt|شبعان|full (food)|A2|satter|sattest",
"nervös|متوتر|nervous|A2|nervöser|nervösest","entspannt|مسترخٍ|relaxed|A2|entspannter|entspanntest",
"stolz|فخور|proud|A2|stolzer|stolzest","eifersüchtig|غيور|jealous|A2|eifersüchtiger|eifersüchtigst",
"neugierig|فضولي|curious|A2|neugieriger|neugierigst","mutig|شجاع|brave|A2|mutiger|mutigst",
"ängstlich|خائف|anxious|A2|ängstlicher|ängstlichst","sicher|آمن / متأكد|safe/sure|A1|sicherer|sicherst",
"unsicher|غير متأكد|unsure|A2|unsicherer|unsicherst","gefährlich|خطير|dangerous|A2|gefährlicher|gefährlichst",
"harmlos|غير ضار|harmless|A2|harmloser|harmlosest","verboten|ممنوع|forbidden|A2|-|-",
"erlaubt|مسموح|allowed|A2|-|-","pflichtig|إلزامي|mandatory|A2|-|-",
"freiwillig|تطوعي|voluntary|A2|-|-","kostenlos|مجاني|free of charge|A1|-|-",
"kostenpflichtig|مدفوع|paid|A2|-|-","barrierefrei|بدون عوائق|accessible|A2|-|-",
"pünktlich2|ملتزم بالمواعيد|on time|A1|pünktlicher|pünktlichst","zuverlässig|موثوق|reliable|A2|zuverlässiger|zuverlässigst",
"ehrlich|صادق|honest|A2|ehrlicher|ehrlichst","unehrlich|غير صادق|dishonest|A2|unehrlicher|unehrlichst",
"geduldig|صبور|patient|A2|geduldiger|geduldigst","ungeduldig|غير صبور|impatient|A2|ungeduldiger|ungeduldigst",
"grob|فظ|rough|A2|gröber|gröbst","vorsichtig|حذر|careful|A2|vorsichtiger|vorsichtigst",
"leichtsinnig|متهور|reckless|A2|leichtsinniger|leichtsinnigst","sparsam|مقتصد|thrifty|A2|sparsamer| sparsamst",
"großzügig|كريم|generous|A2|großzügiger|großzügigst","geizig|بخيل|stingy|A2|geiziger|geizigst",
"intelligent|ذكي|intelligent|A2|intelligenter|intelligentest","kreativ|مبدع|creative|A2|kreativer|kreativst",
"praktisch|عملي|practical|A2|praktischer|praktischst","theoretisch|نظري|theoretical|A2|-|-",
"sportlich|رياضي|sporty|A1|sportlicher|sportlichst","musikalisch|موسيقي|musical|A2|musikalischer|musikalischst",
"kulturell|ثقافي|cultural|A2|-|-","politisch|سياسي|political|A2|-|-",
"wirtschaftlich|اقتصادي|economic|A2|-|-","sozial|اجتماعي|social|A2|sozialer|sozialst",
"privat|خاص|private|A2|privater|privatest","öffentlich|عام|public|A2|-|-",
"persönlich|شخصي|personal|A2|persönlicher|persönlichst","beruflich|مهني|professional|A2|-|-",
"schulisch|مدرسي|school (adj)|A2|-|-","universitär|جامعي|university (adj)|A2|-|-",
"ärztlich|طبي|medical|A2|-|-","rechtlich|قانوني|legal|A2|-|-",
"täglich|يومي|daily|A1|-|-","wöchentlich|أسبوعي|weekly|A2|-|-",
"monatlich|شهري|monthly|A2|-|-","jährlich|سنوي|yearly|A2|-|-",
"derzeit|حاليًا|currently|A2|-|-","letzt|ماضٍ|last|A1|-|-",
"nächst|قادم|next|A1|-|-","jeweilig|م respective|respective|A2|-|-",
"einzeln|منفرد|single|A2|-|-","gemeinsam|مشترك|together|A1|-|-",
"allein|وحيد|alone|A1|-|-","zusammen|معًا|together|A1|-|-",
"bereit|مستعد|ready|A1|bereiter|bereitest","fertig|منتهٍ|done|A1|fertiger|fertigst",
"kaputt|معطل|broken|A1|kaputter|kaputtest","defekt|عاطل|defective|A2|defekter|defektest",
"neueste|الأحدث|latest|A2|-|-","früh|مبكر|early|A1|früher|frühest",
"spät|متأخر|late|A1|später|spätest","rechtzeitig|في الوقت المناسب|in time|A2|-|-",
"sofort|فوري|immediate|A1|-|-","baldig|قريب|soon-ish|A2|-|-",
"deutlich|واضح|clear|A2|deutlicher|deutlichst","undeutlich|غير واضح|unclear|A2|undeutlicher|undeutlichst",
"möglich|ممكن|possible|A1|möglicher|möglichst","unmöglich|مستحيل|impossible|A2|unmöglicher|unmöglichst",
"nötig|ضروري|necessary|A1|nötiger|nötigst","überflüssig|زائد|superfluous|A2|überflüssiger|überflüssigst",
"dringend|عاجل|urgent|A2|dringender|dringendst","egal|لا يهم|whatever|A1|-|-"
];
/* func: de|wtype|ar|en|cat|lvl — wtype in pron adv conj prep num quest det */
const FUNC=[
"ich|pron|أنا|I|general|A1","du|pron|أنت|you (sg)|general|A1","er|pron|هو|he|general|A1",
"sie_sg|pron|هي|she|general|A1","es|pron|هو/هي (محايد)|it|general|A1","wir|pron|نحن|we|general|A1",
"ihr|pron|أنتم|you (pl)|general|A1","sie_pl|pron|هم|they|general|A1","Sie|pron|حضرتك|you (formal)|polite|A1",
"mich|pron|ني (مفعول)|me|general|A1","dich|pron|ك (مفعول)|you|general|A1","ihn|pron|ه (مفعول)|him|general|A1",
"uns|pron|نا|us|general|A2","euch|pron|كم|you pl|general|A2","ihnen|pron|لهم / لحضرتك|them/you formal|polite|A2",
"mir|pron|لي (غير مباشر)|me (dat)|general|A2","dir|pron|لك|you (dat)|general|A2","sich|pron|نفسه (انعكاسي)|oneself|general|A2",
"mein|pron|ملكي|my|general|A1","dein|pron|ملكك|your|general|A1","sein|pron|ملكه|his|general|A1",
"unser|pron|ملكنا|our|general|A1","euer|pron|ملككم|your pl|general|A2","ihr_poss|pron|ملكهم|their|general|A2",
"dieser|pron|هذا|this|general|A1","diese|pron|هذه|this f|general|A1","dieses|pron|هذا (محايد)|this n|general|A1",
"jener|pron|ذلك|that|general|A2","jeder|pron|كل واحد|each|general|A1","alle|pron|الجميع|all|general|A1",
"man|pron|المرء (عام)|one|general|A2","etwas|pron|شيء ما|something|general|A1","nichts|pron|لا شيء|nothing|general|A1",
"jemand|pron|شخص ما|somebody|general|A2","niemand|pron|لا أحد|nobody|general|A2","kein|pron|لا (نفي)|no|general|A1",
"keiner|pron|لا أحد|no one|general|A2","welcher|pron|أي|which|general|A2","was für|pron|أي نوع|what kind|general|A2",
"und|conj|و|and|general|A1","oder|conj|أو|or|general|A1","aber|conj|لكن|but|general|A1",
"denn|conj|لأن|because|general|A1","sondern|conj|بل|but rather|general|A2","sowohl|conj|سواء|both|general|A2",
"weil|conj|لأن (فرعية)|because|general|A1","dass|conj|أن|that|general|A1","wenn|conj|عندما / إذا|when/if|general|A1",
"ob|conj|ما إذا|whether|general|A2","obwohl|conj|رغم أن|although|general|A2","damit|conj|لكي|so that|general|A2",
"bevor|conj|قبل أن|before|general|A2","nachdem|conj|بعد أن|after|general|A2","während|conj|أثناء|while|general|A2",
"bis|conj|حتى|until|general|A1","seit|conj|منذ|since|general|A2","als|conj|عندما (ماضٍ)|when (past)|general|A2",
"falls|conj|في حال|in case|general|A2","sobald|conj|حالما|as soon as|general|A2","sodass|conj|بحيث|so that|general|A2",
"indem|conj|بـ (بواسطة)|by (doing)|general|A2","trotzdem|adv|رغم ذلك|nevertheless|general|A2","deshalb|adv|لذلك|therefore|general|A1",
"deswegen|adv|لهذا السبب|that's why|general|A1","daher|adv|من هنا/لذا|hence|general|A2","also|adv|إذن|so|general|A1",
"dann|adv|ثم|then|general|A1","danach|adv|بعد ذلك|afterwards|general|A1","davor|adv|قبل ذلك|before that|general|A2",
"dabei|adv|أثناء ذلك|meanwhile|general|A2","außerdem|adv|بالإضافة|besides|general|A2","zudem|adv|علاوة على|moreover|general|A2",
"jedoch|adv|لكن|however|general|A2","allerdings|adv|صحيح لكن|admittedly|general|A2","vielleicht|adv|ربما|maybe|general|A1",
"wahrscheinlich|adv|على الأرجح|probably|general|A2","sicherlich|adv|بالتأكيد|certainly|general|A2","natürlich|adv|بالطبع|of course|general|A1",
"gern|adv|بحب / بسرور|gladly|general|A1","lieber|adv|يفضل|rather|general|A1","liebst|adv|الأحب|most|general|A2",
"sehr|adv|جدًا|very|general|A1","zu_adv|adv|جدًا (زيادة)|too|general|A1","genug|adv|كافٍ|enough|general|A1",
"fast|adv|تقريبًا|almost|general|A1","kaum|adv|بالكاد|hardly|general|A2","schon|adv|بالفعل|already|general|A1",
"noch|adv|ما زال / بعد|still/yet|general|A1","wieder|adv|مجددًا|again|general|A1","oft|adv|غالبًا|often|general|A1",
"selten|adv|نادرًا|rarely|general|A1","manchmal|adv|أحيانًا|sometimes|general|A1","immer|adv|دائمًا|always|general|A1",
"nie|adv|أبدًا|never|general|A1","niemals|adv|قط|never ever|general|A2","jetzt|adv|الآن|now|time|A1",
"gleich|adv|حالًا|right away|time|A1","bald|adv|قريبًا|soon|time|A1","später|adv|لاحقًا|later|time|A1",
"früher|adv|سابقًا|earlier|time|A2","heute|adv|اليوم|today|time|A1","morgen_adv|adv|غدًا|tomorrow|time|A1",
"gestern|adv|أمس|yesterday|time|A1","vorgestern|adv|أول أمس|day before|time|A2","übermorgen|adv|بعد غد|day after|time|A2",
"morgens|adv|صباحًا|in mornings|routine|A1","mittags|adv|ظهرًا|at noon|routine|A1","abends|adv|مساءً|in evenings|routine|A1",
"nachts|adv|ليلًا|at night|routine|A1","hier|adv|هنا|here|location|A1","dort|adv|هناك|there|location|A1",
"überall|adv|في كل مكان|everywhere|location|A2","nirgends|adv|في أي مكان|nowhere|location|A2","links|adv|يسارًا|left|directions|A1",
"rechts_adv|adv|يمينًا|right|directions|A1","geradeaus|adv|إلى الأمام|straight|directions|A1","zurück|adv|عائدًا|back|directions|A1",
"herein|adv|ادخل|come in|directions|A2","hinaus|adv|اخرج|go out|directions|A2","oben|adv|فوق|up|location|A1",
"unten|adv|تحت|down|location|A1","innen|adv|داخل|inside|location|A1","außen|adv|خارج|outside|location|A1",
"nebenan|adv|بجوار|next door|neighborhood|A2","gegenüber|adv|مقابل|opposite|directions|A2","in|prep|في|in|general|A1",
"an|prep|على / عند|on/at|general|A1","auf|prep|على|on|general|A1","unter|prep|تحت|under|general|A1",
"über|prep|فوق / عن|over/about|general|A1","vor|prep|أمام / قبل|before|general|A1","hinter|prep|خلف|behind|general|A1",
"neben|prep|بجانب|next to|general|A1","zwischen|prep|بين|between|general|A1","mit|prep|مع|with|general|A1",
"ohne|prep|بدون|without|general|A1","für|prep|لأجل|for|general|A1","gegen|prep|ضد / نحو|against|general|A2",
"um_prep|prep|حول / في تمام|around/at|general|A1","durch|prep|عبر|through|general|A2","wegen|prep|بسبب|because of|general|A2",
"trotz|prep|رغم|despite|general|A2","statt|prep|بدلًا من|instead of|general|A2","während_prep|prep|خلال|during|general|A2",
"bei|prep|عند|at|general|A1","seit_prep|prep|منذ|since|general|A1","ab|prep|اعتبارًا من|from|general|A2",
"aus|prep|من|from/out of|general|A1","zu_prep|prep|إلى|to|general|A1","nach|prep|إلى / بعد|to/after|general|A1",
"bis_prep|prep|حتى|until|general|A1","entlang|prep|على طول|along|general|A2","gegenüber_prep|prep|مقابل|opposite|general|A2",
"wer|quest|من؟|who|general|A1","was|quest|ماذا؟|what|general|A1","wo|quest|أين؟|where|general|A1",
"woher|quest|من أين؟|from where|general|A1","wohin|quest|إلى أين؟|where to|general|A1","wann|quest|متى؟|when|general|A1",
"warum|quest|لماذا؟|why|general|A1","wieso|quest|كيف؟ (لماذا)|why|general|A2","weshalb|quest|لأي سبب؟|why|general|A2",
"wie|quest|كيف؟|how|general|A1","wieviel|quest|كم؟|how much|general|A1","welche|quest|أي؟|which|general|A1",
"null|num|صفر|zero|numbers|A1","eins|num|واحد|one|numbers|A1","zwei|num|اثنان|two|numbers|A1",
"drei|num|ثلاثة|three|numbers|A1","vier|num|أربعة|four|numbers|A1","fünf|num|خمسة|five|numbers|A1",
"sechs|num|ستة|six|numbers|A1","sieben|num|سبعة|seven|numbers|A1","acht|num|ثمانية|eight|numbers|A1",
"neun|num|تسعة|nine|numbers|A1","zehn|num|عشرة|ten|numbers|A1","elf|num|أحد عشر|eleven|numbers|A1",
"zwölf|num|اثنا عشر|twelve|numbers|A1","dreizehn|num|ثلاثة عشر|thirteen|numbers|A1","zwanzig|num|عشرون|twenty|numbers|A1",
"dreißig|num|ثلاثون|thirty|numbers|A1","vierzig|num|أربعون|forty|numbers|A1","fünfzig|num|خمسون|fifty|numbers|A1",
"sechzig|num|ستون|sixty|numbers|A1","siebzig|num|سبعون|seventy|numbers|A1","achtzig|num|ثمانون|eighty|numbers|A1",
"neunzig|num|تسعون|ninety|numbers|A1","hundert|num|مائة|hundred|numbers|A1","tausend|num|ألف|thousand|numbers|A1",
"erste|num|الأول|first|numbers|A1","zweite|num|الثاني|second|numbers|A1","dritte|num|الثالث|third|numbers|A1",
"letzte|num|الأخير|last|numbers|A1","nächste|num|التالي|next|numbers|A1","paar|num|بضعة|couple|numbers|A2",
"viel|num|كثير|much|numbers|A1","wenig|num|قليل|little|numbers|A1","mehr|num|أكثر|more|numbers|A1",
"weniger|num|أقل|less|numbers|A2","genug_num|num|كافٍ|enough|numbers|A1","jed|det|كل|every|general|A1",
"dies|det|هذا|this|general|A1","solch|det|مثل هذا|such|general|A2","manch|det|بعض|some|general|A2",
"kein_det|det|لا|no|general|A1","mein_det|det|ملكي|my|general|A1"
];
const PHRASES=[
"Guten Morgen|صباح الخير|good morning|polite|A1","Guten Tag|طاب يومك|good day|polite|A1",
"Guten Abend|مساء الخير|good evening|polite|A1","Gute Nacht|ليلة سعيدة|good night|polite|A1",
"Hallo|مرحبًا|hello|polite|A1","Tschüss|وداعًا|bye|polite|A1",
"Auf Wiedersehen|إلى اللقاء|goodbye|polite|A1","Bis später|أراك لاحقًا|see you later|polite|A1",
"Bis morgen|أراك غدًا|see you tomorrow|polite|A1","Willkommen|أهلًا بك|welcome|polite|A1",
"Wie geht es Ihnen|كيف حالك (رسمي)|how are you|polite|A1","Wie geht es dir|كيف حالك|how are you|colloquial|A1",
"Mir geht es gut|أنا بخير|I'm fine|colloquial|A1","Danke|شكرًا|thanks|polite|A1",
"Vielen Dank|شكرًا جزيلًا|thanks a lot|polite|A1","Bitte|عفوًا / من فضلك|please/you're welcome|polite|A1",
"Gern geschehen|على الرحب|you're welcome|polite|A1","Kein Problem|لا مشكلة|no problem|colloquial|A1",
"Entschuldigung|عذرًا|excuse me|polite|A1","Es tut mir leid|أنا آسف|I'm sorry|polite|A1",
"Kein Ding|لا عليك|no worries|colloquial|A2","Alles klar|تمام / واضح|all clear|colloquial|A1",
"Kein Stress|لا تتوتر|no stress|colloquial|A2","Mach dir keine Sorgen|لا تقلق|don't worry|colloquial|A2",
"Viel Glück|حظًا سعيدًا|good luck|polite|A1","Viel Spaß|استمتع|have fun|polite|A1",
"Gute Reise|رحلة سعيدة|have a good trip|travel|A1","Gute Besserung|شفاك الله|get well soon|health|A1",
"Herzlichen Glückwunsch|تهانينا|congratulations|polite|A2","Frohe Weihnachten|عيد ميلاد مجيد|merry Christmas|general|A2",
"Frohes neues Jahr|سنة سعيدة|happy new year|dates|A2","Alles Gute zum Geburtstag|عيد ميلاد سعيد|happy birthday|dates|A1",
"Ich verstehe nicht|لا أفهم|I don't understand|study|A1","Können Sie das wiederholen|هل يمكنك التكرار|repeat please|polite|A1",
"Sprechen Sie Englisch|هل تتحدث الإنجليزية|do you speak English|communication|A1","Ich spreche ein bisschen Deutsch|أتحدث قليلًا من الألمانية|I speak a little German|study|A1",
"Was bedeutet das|ماذا يعني هذا|what does it mean|study|A1","Wie sagt man das auf Deutsch|كيف نقول هذا بالألمانية|how to say in German|study|A1",
"Langsamer bitte|ببطء من فضلك|slower please|polite|A1","Noch einmal bitte|مرة أخرى من فضلك|once more please|polite|A1",
"Ich habe eine Frage|لدي سؤال|I have a question|study|A1","Keine Ahnung|لا فكرة لدي|no idea|colloquial|A1",
"Stimmt|صحيح|correct|colloquial|A1","Stimmt nicht|غير صحيح|not correct|colloquial|A1",
"Genau|بالضبط|exactly|colloquial|A1","Wirklich|حقًا|really|colloquial|A1",
"Natürlich|بالطبع|of course|colloquial|A1","Sicher|بالتأكيد|sure|colloquial|A1",
"Klar|واضح / أكيد|clear/sure|colloquial|A1","Okay|حسنًا|okay|colloquial|A1",
"Super|رائع|great|colloquial|A1","Toll|مذهل|awesome|colloquial|A1",
"Schade|للأسف / يا خسارة|too bad|emotions|A1","Egal|لا يهم|whatever|colloquial|A1",
"Mal sehen|لنرَ|let's see|colloquial|A2","Abgemacht|اتفقنا|deal|colloquial|A2",
"Bis dann|إلى اللقاء|see you|colloquial|A1","Mach's gut|اعتن بنفسك|take care|colloquial|A2",
"Viel Erfolg|بالتوفيق|good luck (success)|polite|A2","Drück mir die Daumen|تمنَّ لي الحظ|cross fingers|colloquial|A2",
"Kein Thema|لا موضوع (عادي)|no issue|colloquial|A2","Läuft bei dir|أمورك تمام|going well|colloquial|A2",
"Was geht|ما الأخبار|what's up|colloquial|A1","Na|هاي (تحية)|hey|colloquial|A1",
"Moin|صباحو (تحية شمالية)|hey (northern)|colloquial|A2","Servus|أهلًا (جنوبية)|hello (southern)|colloquial|A2",
"Grüß Gott|حياك الله (جنوبية)|greetings|colloquial|A2","Prost|في صحتك|cheers|colloquial|A1",
"Guten Appetit|بالهناء والشفاء|enjoy your meal|restaurant|A1","Zum Wohl|في صحتك|cheers|restaurant|A2",
"Die Rechnung bitte|الحساب من فضلك|bill please|restaurant|A1","Stimmt so|احتفظ بالباقي|keep the change|restaurant|A2",
"Ich hätte gern|أود|I would like|restaurant|A1","Noch eins bitte|واحد آخر من فضلك|one more please|restaurant|A2",
"Wo ist die Toilette|أين الحمام|where is toilet|travel|A1","Wo ist der Bahnhof|أين محطة القطار|where is station|station|A1",
"Wie komme ich zum|كيف أصل إلى|how do I get to|directions|A1","Ist es weit von hier|هل هو بعيد من هنا|is it far|directions|A2",
"Links abbiegen|انعطف يسارًا|turn left|directions|A1","Rechts abbiegen|انعطف يمينًا|turn right|directions|A1",
"Geradeaus gehen|امشِ مستقيمًا|go straight|directions|A1","An der Ampel|عند الإشارة|at the light|roads|A2",
"An der Ecke|عند الزاوية|at the corner|directions|A1","Gegenüber vom Bahnhof|مقابل المحطة|opposite station|station|A2",
"Ich habe mich verfahren|لقد ضللت الطريق|I'm lost (driving)|directions|A2","Ich suche diese Adresse|أبحث عن هذا العنوان|looking for address|dailylife|A1",
"Ein Ticket nach Berlin|تذكرة إلى برلين|ticket to Berlin|station|A1","Einfach oder hin und zurück|ذهاب أم ذهاب وعودة|single or return|station|A2",
"Wann fährt der Zug ab|متى يغادر القطار|when does train leave|station|A1","Von welchem Gleis|من أي رصيف|which platform|station|A2",
"Ist der Platz frei|هل المقعد فارغ|is seat free|transport|A2","Ich muss umsteigen|يجب أن أبدّل|I must change|transport|A2",
"Wie viel kostet das|كم سعر هذا|how much|shopping|A1","Haben Sie das in einer anderen Größe|هل لديك مقاس آخر|other size|shopping|A2",
"Ich schaue mich nur um|أتصفح فقط|just looking|shopping|A1","Das ist zu teuer|هذا غالٍ جدًا|too expensive|shopping|A1",
"Gibt es einen Rabatt|هل يوجد خصم|any discount|shopping|A2","Kann ich mit Karte zahlen|هل يمكن الدفع بالبطاقة|pay by card|shopping|A1",
"Wo ist die Anprobe|أين غرفة القياس|where fitting room|shopping|A2","Ich möchte das umtauschen|أريد استبدال هذا|exchange this|shopping|A2",
"Ich habe einen Termin|لدي موعد|I have appointment|appointments|A1","Ich möchte einen Termin vereinbaren|أريد تحديد موعد|make appointment|appointments|A1",
"Können wir den Termin verschieben|هل يمكن تأجيل الموعد|reschedule|appointments|A2","Ich warte seit einer Stunde|أنتظر منذ ساعة|waiting an hour|services|A2",
"Welche Unterlagen brauchen Sie|ما المستندات المطلوبة|which documents|documents|A2","Füllen Sie bitte das Formular aus|املأ الاستمارة من فضلك|fill the form|documents|A2",
"Unterschreiben Sie hier bitte|وقّع هنا من فضلك|sign here|documents|A1","Einen Moment bitte|لحظة من فضلك|one moment|polite|A1",
"Ich rufe wegen|أتصل بخصوص|calling about|phones|A2","Sind Sie noch dran|هل ما زلت معي (هاتف)|still there|phones|A2",
"Können Sie mich zurückrufen|هل يمكنك معاودة الاتصال|call me back|phones|A2","Falsch verbunden|رقم خاطئ|wrong number|phones|A2",
"Mein Handy ist leer|هاتفي فارغ الشحن|phone dead|phones|A2","Kein Empfang|لا توجد تغطية|no signal|phones|A2",
"Das WLAN geht nicht|الواي فاي لا يعمل|wifi down|internet|A2","Wie ist das Passwort|ما كلمة المرور|what's password|internet|A1",
"Ich habe mich beworben|لقد تقدمت لوظيفة|I applied|applications|A2","Anbei mein Lebenslauf|مرفق سيرتي الذاتية|CV attached|applications|A2",
"Vielen Dank für das Gespräch|شكرًا على المقابلة|thanks for interview|interviews|A2","Wann kann ich anfangen|متى يمكنني البدء|when start|interviews|A2",
"Wie sind die Arbeitszeiten|ما أوقات العمل|working hours|worktalk|A2","Gibt es Homeoffice|هل يوجد عمل عن بعد|home office|worktalk|A2",
"Ich bin krank|أنا مريض|I'm sick|health|A1","Mir ist schlecht|أشعر بالغثيان|I feel sick|health|A2",
"Ich habe Kopfschmerzen|عندي صداع|headache|health|A1","Ich habe Fieber|عندي حمى|fever|health|A1",
"Rufen Sie einen Krankenwagen|اتصل بالإسعاف|call ambulance|emergency|A1","Ich brauche Hilfe|أحتاج مساعدة|need help|emergency|A1",
"Mir geht es nicht gut|لست بخير|not well|health|A1","Wo tut es weh|أين الألم|where pain|doctor|A2",
"Seit wann haben Sie das|منذ متى لديك هذا|since when|doctor|A2","Nehmen Sie das zweimal täglich|خذه مرتين يوميًا|twice daily|pharmacy|A2",
"Vor oder nach dem Essen|قبل أم بعد الأكل|before/after food|pharmacy|A2","Gute Besserung2|أتمنى لك الشفاء|get well|health|A1",
"Wie ist das Wetter heute|كيف الطقس اليوم|how's weather|weather|A1","Es regnet|إنها تمطر|it's raining|weather|A1",
"Es schneit|إنها تثلج|it's snowing|weather|A1","Die Sonne scheint|الشمس مشرقة|sun shining|weather|A1",
"Es ist kalt draußen|الجو بارد خارجًا|cold outside|weather|A1","Morgen wird es warm|غدًا سيكون دافئًا|warm tomorrow|weather|A2",
"Vergiss den Regenschirm nicht|لا تنس المظلة|don't forget umbrella|weather|A2","Zieh dich warm an|البس ملابس دافئة|dress warm|clothing|A1",
"Ich lerne Deutsch|أتعلم الألمانية|I learn German|study|A1","Deutsch ist schwer aber schön|الألمانية صعبة لكن جميلة|German hard but nice|study|A2",
"Übung macht den Meister|التدريب يصنع الإتقان|practice makes perfect|study|A2","Schritt für Schritt|خطوة بخطوة|step by step|study|A1",
"Nicht aufgeben|لا تستسلم|don't give up|study|A1","Weiter so|استمر هكذا|keep it up|study|A1",
"Du schaffst das|ستنجح في هذا|you can do it|study|A1","Fehler sind okay|الأخطاء مقبولة|mistakes ok|study|A1",
"Jeden Tag ein bisschen|كل يوم قليلًا|a little daily|study|A1","Wiederholung ist wichtig|التكرار مهم|repetition matters|study|A2",
"Keine Panik vor der Prüfung|لا ذعر قبل الامتحان|no exam panic|school|A2","Viel Erfolg bei der Prüfung|بالتوفيق في الامتحان|exam luck|school|A1",
"Herzlich willkommen in Deutschland|أهلًا بك في ألمانيا|welcome to Germany|germany|A1","Wie lange bleiben Sie|كم ستبقى|how long stay|hotel|A2",
"Ich hätte gern ein Doppelzimmer|أود غرفة مزدوجة|double room|hotel|A1","Ist das Frühstück inklusive|هل الفطور مشمول|breakfast included|hotel|A2",
"Um wie viel Uhr ist Checkout|في أي ساعة المغادرة|checkout time|hotel|A2","Das Zimmer ist zu laut|الغرفة صاخبة|room loud|hotel|A2",
"Könnten Sie mir helfen|هل يمكنك مساعدتي|could you help|polite|A1","Wären Sie so nett|هل تتكرم|would you be kind|polite|A2",
"Darf ich Sie etwas fragen|هل يمكنني سؤالك|may I ask|polite|A1","Würden Sie mir bitte helfen|هل تساعدني من فضلك|please help|polite|A2",
"Vielen Dank für Ihre Hilfe|شكرًا جزيلًا لمساعدتك|thanks for help|polite|A1","Das ist sehr nett von Ihnen|هذا لطف منك|very kind|polite|A2",
"Entschuldigen Sie die Störung|عذرًا على الإزعاج|sorry disturb|polite|A2","Kein Problem2|لا مشكلة أبدًا|no problem|colloquial|A1",
"Alles gut|كل شيء بخير|all good|colloquial|A1","Passt schon|لا بأس|it's fine|colloquial|A2",
"Klingt gut|يبدو جيدًا|sounds good|colloquial|A1","Mal schauen|لنرَ|we'll see|colloquial|A2",
"Abwarten|لننتظر|let's wait|colloquial|A2","Stimmt genau|صحيح تمامًا|exactly right|colloquial|A1",
"Auf jeden Fall|على أي حال|definitely|colloquial|A2","Auf keinen Fall|مستحيل|no way|colloquial|A2",
"Im Ernst|بجدية|seriously|colloquial|A2","Kein Witz|بدون مزاح|no joke|colloquial|A2",
"Ehrlich gesagt|بصراحة|honestly|colloquial|A2","Zum Glück|لحسن الحظ|luckily|general|A2",
"Leider|للأسف|unfortunately|general|A1","Hoffentlich|نرجو|hopefully|general|A2",
"Endlich|أخيرًا|finally|general|A1","Plötzlich|فجأة|suddenly|general|A2",
"Normalerweise|عادة|usually|routine|A2","Gewöhnlich|معتاد|ordinary|routine|A2",
"Früh aufstehen|الاستيقاظ مبكرًا|early rising|routine|A1","Spät ins Bett|النوم متأخرًا|late to bed|routine|A1",
"Zähne putzen|تنظيف الأسنان|brush teeth|routine|A1","Duschen gehen|الذهاب للاستحمام|go shower|routine|A1",
"Frühstücken|تناول الفطور|have breakfast|routine|A1","Zur Arbeit gehen|الذهاب للعمل|go to work|work|A1",
"Nach Hause kommen|العودة للبيت|come home|routine|A1","Abendessen kochen|طهي العشاء|cook dinner|food|A1",
"Fernsehen schauen|مشاهدة التلفاز|watch TV|hobbies|A1","Spazieren gehen|التنزه مشيًا|go for walk|hobbies|A1",
"Freunde treffen|لقاء الأصدقاء|meet friends|relationships|A1","Einkaufen gehen|الذهاب للتسوق|go shopping|shopping|A1",
"Ins Bett gehen|الذهاب للنوم|go to bed|routine|A1","Ausschlafen|النوم حتى الشبع|sleep in|routine|A2",
"Überstunden machen|عمل ساعات إضافية|do overtime|work|A2","Feierabend haben|انتهاء الدوام|off work|work|A2",
"Kaffeepause machen|استراحة قهوة|coffee break|work|A1","Mittagspause machen|استراحة الغداء|lunch break|work|A1"
];
if(typeof module!=="undefined")module.exports={ADJ,FUNC,PHRASES};
