/* Deutsch Master — BIG dialogue situations (deterministic, curated).
   100 situations × pools; generator crosses situation × twist × length × level.
   All lines hand-written [speaker, de, ar]. Shared formulaic pools reused honestly.
*/
"use strict";

/* shared formulaic lines [de, ar] (greetings/thanks/clarify/goodbye) */
const SHARED = {
  greet: [
    ["Hallo! Wie geht es dir?", "مرحبًا! كيف حالك؟"],
    ["Guten Tag! Schön, Sie zu sehen.", "طاب يومك! سعيد برؤيتك."],
    ["Hallo zusammen!", "مرحبًا بالجميع!"],
    ["Guten Morgen! Alles klar?", "صباح الخير! كل شيء تمام؟"],
    ["Hi! Lange nicht gesehen.", "مرحبًا! لم أرك منذ زمن."],
  ],
  thanks: [
    ["Vielen Dank!", "شكرًا جزيلًا!"],
    ["Danke schön!", "شكرًا!"],
    ["Das ist sehr nett von dir.", "هذا لطف منك."],
    ["Ich danke Ihnen.", "أشكرك."],
  ],
  clarify: [
    ["Wie bitte?", "عفوًا؟"],
    ["Kannst du das wiederholen?", "هل يمكنك التكرار؟"],
    ["Ich verstehe nicht ganz.", "لا أفهم تمامًا."],
    ["Was meinst du damit?", "ماذا تقصد؟"],
  ],
  bye: [
    ["Tschüss! Bis später!", "وداعًا! إلى اللقاء!"],
    ["Auf Wiedersehen!", "إلى اللقاء!"],
    ["Schönes Wochenende!", "عطلة سعيدة!"],
    ["Mach's gut!", "اعتن بنفسك!"],
  ],
  ok: [
    ["Gern geschehen.", "على الرحب."],
    ["Kein Problem.", "لا مشكلة."],
    ["Natürlich.", "بالطبع."],
    ["Sehr gern.", "بكل سرور."],
  ],
  smalltalk: [
    [["Schönes Wetter heute.", "جو جميل اليوم."], ["Ja, herrlich!", "نعم، رائع!"]],
    [["War viel los heute?", "هل كان اليوم مزدحمًا؟"], ["Ja, ziemlich viel.", "نعم، كثيرًا."]],
    [["Schönes Wochenende gehabt?", "عطلة سعيدة؟"], ["Ja, danke! Und du?", "نعم شكرًا! وأنت؟"]],
    [["Alles gut bei dir?", "كل شيء بخير؟"], ["Ja, alles bestens.", "نعم، كل شيء ممتاز."]],
    [["Schon Pläne fürs Wochenende?", "هل لديك خطط للعطلة؟"], ["Noch nicht.", "ليس بعد."]],
    [["Wie läuft die Arbeit?", "كيف العمل؟"], ["Gut, danke.", "جيد، شكرًا."]],
  ],
};

/* situations: [key, topic, titleDe, titleAr, speakers[A,B], open[], req[], res[], close[]]
   each pool entry [de, ar, lvl] lvl 1=A1 2=A2 3=B1 */
const SITS = [
  ["restaurant-bestellen", "restaurant", "Im Restaurant bestellen", "الطلب في المطعم", ["Gast", "Kellner"],
    [["Einen Tisch für zwei, bitte.", "طاولة لشخصين من فضلك.", 1], ["Haben Sie einen Tisch frei?", "هل لديك طاولة فارغة؟", 1]],
    [["Ich nehme die Suppe.", "آخذ الشوربة.", 1], ["Ich hätte gern das Schnitzel.", "أود الشنيتزل.", 2], ["Als Vorspeise nehme ich den Salat.", "كمقبلات آخذ السلطة.", 2]],
    [["Gern. Und zu trinken?", "بكل سرور. وماذا تشرب؟", 1], ["Sehr gern. Kommt sofort.", "بكل سرور. يأتي حالًا.", 1], ["Eine gute Wahl.", "اختيار جيد.", 2]],
    [["Die Rechnung, bitte.", "الفاتورة من فضلك.", 1], ["Stimmt so.", "الباقي لك.", 2]]],
  ["cafe-treffen", "drinks", "Treffen im Café", "لقاء في المقهى", ["Sara", "Jonas"],
    [["Hallo! Lange nicht gesehen.", "مرحبًا! لم أرك منذ زمن.", 1], ["Wie geht es dir?", "كيف حالك؟", 1]],
    [["Einen Kaffee, bitte.", "قهوة من فضلك.", 1], ["Für mich einen Tee mit Zitrone.", "لي شاي بالليمون.", 2]],
    [["Kommt sofort.", "يأتي حالًا.", 1], ["Sehr gern.", "بكل سرور.", 1]],
    [["Lass uns bald wieder treffen.", "لنتقابل قريبًا مجددًا.", 2], ["Tschüss!", "وداعًا!", 1]]],
  ["supermarkt-kasse", "supermarket", "An der Kasse", "عند الصندوق", ["Kunde", "Kassiererin"],
    [["Guten Tag!", "طاب يومك!", 1]],
    [["Ist die Tomate im Angebot?", "هل الطماطم في العرض؟", 2], ["Wo finde ich die Milch?", "أين أجد الحليب؟", 1]],
    [["Ja, diese Woche.", "نعم، هذا الأسبوع.", 2], ["Ganz hinten links.", "في الخلف يسارًا.", 2]],
    [["Das macht 12 Euro.", "الحساب 12 يورو.", 1], ["Mit Karte, bitte.", "بالبطاقة من فضلك.", 1]]],
  ["arzt-termin", "doctor", "Beim Arzt", "عند الطبيب", ["Patient", "Arzt"],
    [["Guten Tag, Herr Doktor.", "طاب يومك دكتور.", 1]],
    [["Ich habe seit gestern Fieber.", "لدي حمى منذ أمس.", 2], ["Mein Hals tut weh.", "حلقي يؤلمني.", 1]],
    [["Seit wann genau?", "منذ متى بالضبط؟", 2], ["Nehmen Sie diese Tabletten.", "خذ هذه الأقراص.", 2]],
    [["Gute Besserung!", "بالشفاء!", 1], ["Vielen Dank!", "شكرًا جزيلًا!", 1]]],
  ["hotel-checkin", "hotel", "An der Rezeption", "عند الاستقبال", ["Gast", "Rezeptionist"],
    [["Guten Abend! Ich habe reserviert.", "مساء الخير! حجزت.", 1]],
    [["Ein Einzelzimmer für zwei Nächte.", "غرفة مفردة لليلتين.", 2], ["Ist das Frühstück dabei?", "هل الفطور مشمول؟", 2]],
    [["Ja, von 7 bis 10 Uhr.", "نعم، من 7 حتى 10.", 2], ["Zimmer 204 im zweiten Stock.", "غرفة 204 في الطابق الثاني.", 2]],
    [["Vielen Dank!", "شكرًا جزيلًا!", 1], ["Gern geschehen.", "على الرحب.", 1]]],
  ["bahnhof-auskunft", "station", "Am Bahnhof", "في المحطة", ["Reisender", "Beamter"],
    [["Entschuldigung, wann fährt der Zug?", "عذرًا، متى يغادر القطار؟", 1]],
    [["Nach Berlin, bitte.", "إلى برلين من فضلك.", 1], ["Muss ich umsteigen?", "هل يجب أن أبدل؟", 2]],
    [["Um halb neun von Gleis 5.", "الثامنة والنصف من الرصيف 5.", 2], ["Nein, direkt.", "لا، مباشر.", 1]],
    [["Danke schön!", "شكرًا!", 1], ["Gute Fahrt!", "رحلة سعيدة!", 1]]],
  ["flughafen-checkin", "airport", "Am Flughafen", "في المطار", ["Passagier", "Angestellte"],
    [["Guten Morgen! Hier ist mein Ticket.", "صباح الخير! هذه تذكرتي.", 1]],
    [["Ein Fensterplatz, bitte.", "مقعد بجانب النافذة من فضلك.", 2], ["Nur Handgepäck.", "حقيبة يد فقط.", 2]],
    [["Gate 12, Boarding um zehn.", "البوابة 12، الصعود العاشرة.", 3], ["Der Flug hat Verspätung.", "الرحلة متأخرة.", 2]],
    [["Danke!", "شكرًا!", 1], ["Guten Flug!", "رحلة سعيدة!", 1]]],
  ["bank-konto", "banking", "In der Bank", "في البنك", ["Kunde", "Berater"],
    [["Guten Tag! Ich möchte ein Konto eröffnen.", "طاب يومك! أود فتح حساب.", 2]],
    [["Welche Unterlagen brauchen Sie?", "ما المستندات المطلوبة؟", 3], ["Ihren Pass, bitte.", "جوازك من فضلك.", 1]],
    [["Hier ist mein Pass.", "هذا جوازي.", 1], ["Unterschreiben Sie hier.", "وقع هنا.", 2]],
    [["Vielen Dank!", "شكرًا!", 1], ["Gern geschehen.", "على الرحب.", 1]]],
  ["arbeit-meeting", "work", "Im Meeting", "في الاجتماع", ["Chef", "Mitarbeiter"],
    [["Guten Morgen zusammen!", "صباح الخير جميعًا!", 1]],
    [["Wie ist der Stand beim Projekt?", "ما وضع المشروع؟", 3], ["Wir sind fast fertig.", "أوشكنا على الانتهاء.", 2]],
    [["Sehr gut. Weiter so!", "ممتاز. استمروا!", 2], ["Bis wann schaffen wir es?", "متى ننتهي؟", 2]],
    [["Bis Freitag.", "حتى الجمعة.", 1], ["Danke!", "شكرًا!", 1]]],
  ["schule-klasse", "school", "In der Klasse", "في الصف", ["Lehrer", "Schüler"],
    [["Guten Morgen, Klasse!", "صباح الخير يا صف!", 1]],
    [["Schlagt die Bücher auf Seite zehn auf!", "افتحوا الكتب صفحة عشرة!", 2], ["Wer kann antworten?", "من يجيب؟", 1]],
    [["Ich weiß es!", "أعرف!", 1], ["Sehr gut!", "ممتاز!", 1]],
    [["Hausaufgaben bis morgen!", "الواجب حتى الغد!", 2], ["Tschüss!", "وداعًا!", 1]]],
  ["uni-vorlesung", "university", "An der Uni", "في الجامعة", ["Professor", "Student"],
    [["Willkommen zur Vorlesung!", "مرحبًا بكم في المحاضرة!", 2]],
    [["Wann ist die Prüfung?", "متى الامتحان؟", 1], ["Gibt es ein Skript?", "هل يوجد ملخص؟", 2]],
    [["Nächsten Montag.", "الاثنين القادم.", 1], ["Ja, online.", "نعم، إلكترونيًا.", 1]],
    [["Danke schön!", "شكرًا!", 1], ["Bis dann!", "إلى اللقاء!", 1]]],
  ["familie-besuch", "family", "Familienbesuch", "زيارة عائلية", ["Oma", "Enkel"],
    [["Hallo Oma! Wie geht es dir?", "مرحبًا جدتي! كيف حالك؟", 1]],
    [["Mir geht es gut. Und dir?", "أنا بخير. وأنت؟", 1], ["Bleibst du zum Essen?", "هل تبقى للطعام؟", 1]],
    [["Gern!", "بسرور!", 1], ["Es gibt Kuchen.", "يوجد كعكة.", 1]],
    [["Tschüss Oma!", "وداعًا جدتي!", 1], ["Bis Sonntag!", "إلى الأحد!", 1]]],
  ["nachbarn-hilfe", "neighborhood", "Bei den Nachbarn", "عند الجيران", ["Nachbar", "Nachbarin"],
    [["Hallo! Kannst du mir helfen?", "مرحبًا! هل تساعدني؟", 1]],
    [["Mein Auto springt nicht an.", "سيارتي لا تعمل.", 2], ["Hast du ein Ladekabel?", "هل لديك شاحن؟", 2]],
    [["Ja, einen Moment.", "نعم، لحظة.", 1], ["Danke!", "شكرًا!", 1]],
    [["Gern geschehen.", "على الرحب.", 1], ["Tschüss!", "وداعًا!", 1]]],
  ["einkaufen-markt", "shopping", "Auf dem Markt", "في السوق", ["Kunde", "Verkäufer"],
    [["Guten Morgen! Was kostet das?", "صباح الخير! كم سعر هذا؟", 1]],
    [["Die Äpfel kosten zwei Euro.", "التفاح بيوروين.", 1], ["Geben Sie mir bitte ein Kilo.", "أعطني كيلو من فضلك.", 2]],
    [["Sonst noch etwas?", "شيء آخر؟", 2], ["Das ist alles.", "هذا كل شيء.", 1]],
    [["Das macht vier Euro.", "الحساب أربعة يورو.", 1], ["Danke! Tschüss!", "شكرًا! وداعًا!", 1]]],
  ["friseur-termin", "services", "Beim Friseur", "عند الحلاق", ["Kunde", "Friseur"],
    [["Hallo! Haben Sie Zeit?", "مرحبًا! هل لديك وقت؟", 1]],
    [["Nur schneiden, bitte.", "قص فقط من فضلك.", 1], ["Wie kurz?", "كم قصير؟", 2]],
    [["Nicht zu kurz.", "ليس قصيرًا جدًا.", 2], ["Verstanden.", "فهمت.", 1]],
    [["Das macht 20 Euro.", "الحساب 20 يورو.", 1], ["Danke! Tschüss!", "شكرًا! وداعًا!", 1]]],
  ["apotheke-rezept", "pharmacy", "In der Apotheke", "في الصيدلية", ["Kunde", "Apotheker"],
    [["Guten Tag! Ich habe ein Rezept.", "طاب يومك! لدي وصفة.", 2]],
    [["Einmal täglich eine Tablette.", "قرص واحد يوميًا.", 2], ["Vor oder nach dem Essen?", "قبل الأكل أم بعده؟", 2]],
    [["Nach dem Essen.", "بعد الأكل.", 1], ["Gute Besserung!", "بالشفاء!", 1]],
    [["Danke schön!", "شكرًا!", 1], ["Tschüss!", "وداعًا!", 1]]],
  ["taxi-fahrt", "transport", "Im Taxi", "في التاكسي", ["Fahrgast", "Fahrer"],
    [["Hallo! Zum Bahnhof, bitte.", "مرحبًا! إلى المحطة من فضلك.", 1]],
    [["Geht es auch schneller?", "هل يمكن أسرع؟", 2], ["Ich habe es eilig.", "أنا مستعجل.", 2]],
    [["Kein Problem.", "لا مشكلة.", 1], ["Das macht zehn Euro.", "الحساب عشرة يورو.", 1]],
    [["Stimmt so.", "الباقي لك.", 2], ["Danke! Tschüss!", "شكرًا! وداعًا!", 1]]],
  ["polizei-meldung", "emergency", "Bei der Polizei", "عند الشرطة", ["Bürger", "Polizist"],
    [["Guten Tag! Ich möchte etwas melden.", "طاب يومك! أود الإبلاغ عن شيء.", 3]],
    [["Was ist passiert?", "ماذا حدث؟", 2], ["Mein Fahrrad ist weg.", "دراجتي اختفت.", 2]],
    [["Wo war das?", "أين كان ذلك؟", 2], ["Vor dem Haus.", "أمام البيت.", 1]],
    [["Wir kümmern uns darum.", "سنهتم بالأمر.", 3], ["Danke!", "شكرًا!", 1]]],
  ["amt-termin", "documents", "Auf dem Amt", "في الدائرة", ["Bürger", "Beamter"],
    [["Guten Tag! Ich habe einen Termin.", "طاب يومك! لدي موعد.", 2]],
    [["Ihren Pass, bitte.", "جوازك من فضلك.", 1], ["Hier ist er.", "تفضل.", 1]],
    [["Unterschreiben Sie hier.", "وقع هنا.", 2], ["Fertig.", "انتهى.", 1]],
    [["Danke schön!", "شكرًا!", 1], ["Auf Wiedersehen!", "إلى اللقاء!", 1]]],
  ["bewerbung-gespraech", "interviews", "Im Vorstellungsgespräch", "في مقابلة العمل", ["Chef", "Bewerber"],
    [["Guten Tag! Nehmen Sie Platz.", "طاب يومك! تفضل بالجلوس.", 2]],
    [["Erzählen Sie etwas über sich!", "حدثنا عن نفسك!", 2], ["Ich habe drei Jahre Erfahrung.", "لدي ثلاث سنوات خبرة.", 3]],
    [["Warum wollen Sie hier arbeiten?", "لماذا تريد العمل هنا؟", 3], ["Die Firma gefällt mir.", "الشركة تعجبني.", 2]],
    [["Wir melden uns.", "سنتصل بك.", 2], ["Vielen Dank!", "شكرًا جزيلًا!", 1]]],
  ["wohnung-besichtigung", "home", "Bei der Besichtigung", "عند المعاينة", ["Mieter", "Vermieter"],
    [["Guten Tag! Ist die Wohnung noch frei?", "طاب يومك! هل الشقة متاحة؟", 2]],
    [["Wie hoch ist die Miete?", "كم الإيجار؟", 1], ["Ab wann ist sie frei?", "من متى تكون فارغة؟", 2]],
    [["Ab nächstem Monat.", "من الشهر القادم.", 2], ["Gibt es einen Keller?", "هل يوجد قبو؟", 2]],
    [["Ich melde mich.", "سأتصل بك.", 2], ["Auf Wiedersehen!", "إلى اللقاء!", 1]]],
  ["kinderarzt-besuch", "doctor", "Beim Kinderarzt", "عند طبيب الأطفال", ["Mutter", "Arzt"],
    [["Guten Tag! Mein Sohn hustet.", "طاب يومك! ابني يسعل.", 2]],
    [["Seit wann?", "منذ متى؟", 1], ["Seit drei Tagen.", "منذ ثلاثة أيام.", 1]],
    [["Keine Sorge, nur Erkältung.", "لا تقلقي، مجرد برد.", 2], ["Viel trinken.", "اشربوا كثيرًا.", 1]],
    [["Danke schön!", "شكرًا!", 1], ["Gute Besserung!", "بالشفاء!", 1]]],
  ["zahnarzt-kontrolle", "doctor", "Beim Zahnarzt", "عند طبيب الأسنان", ["Patient", "Zahnarzt"],
    [["Guten Tag! Ich habe Zahnschmerzen.", "طاب يومك! لدي ألم أسنان.", 2]],
    [["Wo genau?", "أين بالضبط؟", 1], ["Links oben.", "يسارًا أعلى.", 2]],
    [["Machen Sie bitte den Mund auf.", "افتح فمك من فضلك.", 1], ["Alles klar.", "تمام.", 1]],
    [["Bis in sechs Monaten.", "إلى اللقاء بعد ستة أشهر.", 2], ["Danke! Tschüss!", "شكرًا! وداعًا!", 1]]],
  ["post-paket", "services", "Bei der Post", "عند البريد", ["Kunde", "Beamter"],
    [["Guten Tag! Ich möchte ein Paket schicken.", "طاب يومك! أود إرسال طرد.", 2]],
    [["Wohin geht es?", "إلى أين؟", 1], ["Nach Kairo.", "إلى القاهرة.", 1]],
    [["Das dauert eine Woche.", "يستغرق أسبوعًا.", 2], ["Wie viel kostet das?", "كم يكلف؟", 1]],
    [["Fünf Euro.", "خمسة يورو.", 1], ["Danke! Tschüss!", "شكرًا! وداعًا!", 1]]],
  ["friseur-neu", "services", "Neuer Haarschnitt", "قصة شعر جديدة", ["Kundin", "Friseurin"],
    [["Hallo! Ich hätte gern einen Termin.", "مرحبًا! أود موعدًا.", 2]],
    [["Was schwebt Ihnen vor?", "ماذا تتصورين؟", 3], ["Nur die Spitzen, bitte.", "الأطراف فقط من فضلك.", 2]],
    [["Sehr gern.", "بكل سرور.", 1], ["So ist es schön.", "هكذا جميل.", 2]],
    [["Das macht 25 Euro.", "الحساب 25 يورو.", 1], ["Danke! Bis bald!", "شكرًا! إلى اللقاء!", 1]]],
  ["kino-karten", "hobbies", "Im Kino", "في السينما", ["Besucher", "Kassierer"],
    [["Hallo! Zwei Karten, bitte.", "مرحبًا! تذكرتان من فضلك.", 1]],
    [["Für welchen Film?", "لأي فيلم؟", 1], ["Für die Vorstellung um acht.", "لعرض الثامنة.", 2]],
    [["Reihe fünf, bitte.", "الصف الخامس من فضلك.", 2], ["Viel Spaß!", "استمتعوا!", 1]],
    [["Danke!", "شكرًا!", 1], ["Tschüss!", "وداعًا!", 1]]],
  ["sport-verein", "sports", "Im Sportverein", "في النادي الرياضي", ["Trainer", "Mitglied"],
    [["Hallo! Ich möchte mitmachen.", "مرحبًا! أود المشاركة.", 2]],
    [["Welche Sportart?", "أي رياضة؟", 1], ["Fußball, bitte.", "كرة القدم من فضلك.", 1]],
    [["Training ist dienstags.", "التدريب أيام الثلاثاء.", 2], ["Super, danke!", "ممتاز، شكرًا!", 1]],
    [["Bis Dienstag!", "إلى الثلاثاء!", 1], ["Tschüss!", "وداعًا!", 1]]],
  ["bibliothek-ausleihe", "study", "In der Bibliothek", "في المكتبة", ["Leser", "Bibliothekar"],
    [["Guten Tag! Ich suche ein Buch.", "طاب يومك! أبحث عن كتاب.", 1]],
    [["Welches Thema?", "أي موضوع؟", 2], ["Deutsche Grammatik.", "قواعد الألمانية.", 2]],
    [["Dritter Gang links.", "الممر الثالث يسارًا.", 3], ["Wie lange darf ich es behalten?", "كم أبقيه؟", 3]],
    [["Vier Wochen.", "أربعة أسابيع.", 2], ["Danke schön!", "شكرًا!", 1]]],
  ["handy-vertrag", "phones", "Im Handyladen", "في محل الهواتف", ["Kunde", "Verkäufer"],
    [["Hallo! Ich brauche einen neuen Vertrag.", "مرحبًا! أحتاج عقدًا جديدًا.", 2]],
    [["Mit viel Internet, bitte.", "بإنترنت كثير من فضلك.", 2], ["Dieser Tarif passt gut.", "هذه الباقة مناسبة.", 3]],
    [["Wie lange läuft er?", "كم مدته؟", 2], ["Zwei Jahre.", "سنتان.", 1]],
    [["Ich nehme ihn.", "آخذه.", 1], ["Danke! Tschüss!", "شكرًا! وداعًا!", 1]]],
  ["geburtstag-feier", "family", "Auf der Geburtstagsfeier", "في حفلة عيد الميلاد", ["Gastgeber", "Gast"],
    [["Hallo! Schön, dass du da bist.", "مرحبًا! سعيد بوجودك.", 1]],
    [["Alles Gute zum Geburtstag!", "عيد ميلاد سعيد!", 1], ["Danke! Komm rein.", "شكرًا! تفضل.", 1]],
    [["Kuchen?", "كعكة؟", 1], ["Gern!", "بسرور!", 1]],
    [["Es war ein schöner Abend.", "كانت أمسية جميلة.", 2], ["Bis bald!", "إلى اللقاء!", 1]]],
];

module.exports = { SHARED, SITS };
