/* Deutsch Master — BIG grammar data 2: connectors, prepositions, tenses, modals,
   pronouns, numbers, situational grammar. Hand-curated. Consumed by build-grammar2.js */
"use strict";

/* [connector, arMeaning, type S=sub C=coord, exDe, exAr] */
const CONN = [
  ["weil", "لأن", "S", "Ich bleibe zu Hause, weil ich krank bin.", "أبقى في البيت لأنني مريض."],
  ["dass", "أن", "S", "Er sagt, dass er morgen kommt.", "يقول إنه سيأتي غدًا."],
  ["wenn", "إذا / عندما", "S", "Wenn ich Zeit habe, rufe ich dich an.", "إذا كان لدي وقت اتصل بك."],
  ["als", "عندما (ماضٍ)", "S", "Als ich jung war, spielte ich Fußball.", "عندما كنت صغيرًا لعبت كرة القدم."],
  ["während", "أثناء", "S", "Während er kocht, höre ich Musik.", "أثناء طبخه أستمع للموسيقى."],
  ["bevor", "قبل أن", "S", "Bevor du gehst, ruf mich an.", "قبل أن تذهب اتصل بي."],
  ["nachdem", "بعد أن", "S", "Nachdem er gegessen hat, geht er spazieren.", "بعد أن أكل يذهب للتنزه."],
  ["bis", "حتى", "S", "Warte, bis ich fertig bin.", "انتظر حتى أنتهي."],
  ["seitdem", "منذ", "S", "Seitdem er in Berlin wohnt, spricht er Deutsch.", "منذ سكنه في برلين يتحدث الألمانية."],
  ["sobald", "حالما", "S", "Sobald du ankommst, ruf mich an.", "حالما تصل اتصل بي."],
  ["falls", "في حال", "S", "Falls du Zeit hast, komm vorbei.", "إن كان لديك وقت مر علي."],
  ["obwohl", "رغم أن", "S", "Obwohl er müde ist, arbeitet er.", "رغم أنه متعب يعمل."],
  ["obgleich", "رغم أن", "S", "Obgleich es regnet, gehen wir aus.", "رغم المطر نخرج."],
  ["auch wenn", "حتى لو", "S", "Auch wenn es kalt ist, jogge ich.", "حتى لو كان باردًا أركض."],
  ["damit", "لكي", "S", "Ich lerne viel, damit ich bestehe.", "أدرس كثيرًا لكي أنجح."],
  ["um zu", "لكي", "S", "Ich lerne Deutsch, um in Deutschland zu arbeiten.", "أتعلم الألمانية لأعمل في ألمانيا."],
  ["statt zu", "بدل أن", "S", "Statt zu Hause zu bleiben, geht er aus.", "بدل البقاء في البيت يخرج."],
  ["ohne zu", "بدون أن", "S", "Ohne zu fragen, nimmt er das Handy.", "بدون أن يسأل يأخذ الهاتف."],
  ["indem", "بـ (بواسطة)", "S", "Indem er täglich übt, wird er besser.", "بتدربه يوميًا يتحسن."],
  ["als ob", "كما لو", "S", "Er tut so, als ob er krank wäre.", "يتصرف كما لو كان مريضًا."],
  ["so dass", "بحيث", "S", "Er spricht laut, so dass alle hören.", "يتحدث بصوت عالٍ بحيث يسمع الجميع."],
  ["sodass", "بحيث", "S", "Es regnet, sodass wir bleiben.", "إنها تمطر بحيث نبقى."],
  ["und", "و", "C", "Ich koche und er deckt den Tisch.", "أطبخ وهو يجهز الطاولة."],
  ["oder", "أو", "C", "Willst du Tee oder Kaffee?", "أتريد شايًا أم قهوة؟"],
  ["aber", "لكن", "C", "Er ist müde, aber er arbeitet.", "هو متعب لكنه يعمل."],
  ["denn", "لأن", "C", "Ich bleibe zu Hause, denn ich bin krank.", "أبقى في البيت لأنني مريض."],
  ["sondern", "بل", "C", "Er trinkt keinen Tee, sondern Kaffee.", "لا يشرب شايًا بل قهوة."],
  ["doch", "لكن", "C", "Es regnet, doch wir gehen aus.", "إنها تمطر لكننا نخرج."],
  ["jedoch", "لكن", "C", "Er ist krank, jedoch kommt er.", "هو مريض لكنه يأتي."],
  ["allein", "لكن", "C", "Ich komme gern, allein habe ich keine Zeit.", "آتي بسرور لكن ليس لدي وقت."],
  ["entweder oder", "إما أو", "C", "Entweder du kommst mit, oder du bleibst hier.", "إما أن تأتي معي أو تبقى هنا."],
  ["sowohl als auch", "سواء و", "C", "Sowohl er als auch sie kommen.", "سواء هو أو هي يأتيان."],
  ["weder noch", "لا ولا", "C", "Weder er noch sie hat Zeit.", "لا هو ولا هي لديه وقت."],
  ["nicht nur sondern auch", "ليس فقط بل أيضًا", "C", "Nicht nur er, sondern auch sie lernt.", "ليس هو فقط بل هي أيضًا تتعلم."],
  ["zwar aber", "صحيح لكن", "C", "Es ist zwar kalt, aber sonnig.", "الجو بارد صحيح لكنه مشمس."],
  ["und zwar", "وتحديدًا", "C", "Er kommt heute, und zwar um acht.", "يأتي اليوم وتحديدًا في الثامنة."],
  ["bzw.", "أي", "C", "Wir treffen uns morgen, bzw. am Montag.", "نلتقي غدًا أي يوم الاثنين."],
  ["da", "بما أن", "S", "Da es regnet, bleiben wir zu Hause.", "بما أنها تمطر نبقى في البيت."],
  ["zumal", "خاصة أن", "S", "Ich bleibe hier, zumal es spät ist.", "أبقى هنا خاصة أنه متأخر."],
  ["ob", "إذا (غير مباشر)", "S", "Ich weiß nicht, ob er kommt.", "لا أعرف إذا كان سيأتي."],
];

/* [prep, case, arMeaning, ex1de, ex1ar, ex2de, ex2ar] */
const PREPCASE = [
  ["aus", "D", "من (مصدر)", "Ich komme aus Ägypten.", "أنا من مصر.", "Er trinkt aus der Tasse.", "يشرب من الفنجان."],
  ["bei", "D", "عند", "Ich wohne bei meinen Eltern.", "أسكن عند والدي.", "Er arbeitet bei Siemens.", "يعمل لدى سيمنز."],
  ["mit", "D", "مع / بـ", "Ich fahre mit dem Bus.", "أركب الحافلة.", "Er schreibt mit dem Stift.", "يكتب بالقلم."],
  ["nach", "D", "إلى / بعد", "Ich fahre nach Berlin.", "أسافر إلى برلين.", "Nach dem Essen ruhe ich.", "بعد الأكل أستريح."],
  ["seit", "D", "منذ", "Ich lerne seit einem Jahr Deutsch.", "أتعلم الألمانية منذ سنة.", "Er wohnt seit 2020 hier.", "يسكن هنا منذ 2020."],
  ["von", "D", "من", "Das Geschenk ist von mir.", "الهدية مني.", "Ich träume von Urlaub.", "أحلم بإجازة."],
  ["zu", "D", "إلى / لـ", "Ich gehe zum Arzt.", "أذهب إلى الطبيب.", "Herzlichen Glückwunsch zum Geburtstag!", "تهنئة بعيد الميلاد!"],
  ["gegenüber", "D", "مقابل", "Die Bank ist gegenüber dem Hotel.", "البنك مقابل الفندق.", "Er sitzt mir gegenüber.", "يجلس قبالي."],
  ["durch", "A", "عبر", "Wir fahren durch die Stadt.", "نسير عبر المدينة.", "Er fällt durch die Prüfung.", "يرسب في الامتحان."],
  ["für", "A", "لأجل", "Das Geschenk ist für dich.", "الهدية لك.", "Ich arbeite für meine Familie.", "أعمل من أجل عائلتي."],
  ["gegen", "A", "ضد / نحو", "Ich bin gegen den Plan.", "أنا ضد الخطة.", "Wir kommen gegen Abend.", "نصل نحو المساء."],
  ["ohne", "A", "بدون", "Ohne dich gehe ich nicht.", "بدونك لا أذهب.", "Er kommt ohne Geld.", "يأتي بدون نقود."],
  ["um", "A", "حول / في", "Wir sitzen um den Tisch.", "نجلس حول الطاولة.", "Der Termin ist um 8 Uhr.", "الموعد في الثامنة."],
  ["entlang", "A", "على طول", "Wir gehen die Straße entlang.", "نسير على طول الشارع.", "Der Weg führt den Fluss entlang.", "الطريق على طول النهر."],
  ["bis", "A", "حتى", "Ich warte bis morgen.", "أنتظر حتى الغد.", "Von Berlin bis München dauert es Stunden.", "من برلين حتى ميونخ يستغرق ساعات."],
  ["trotz", "G", "رغم", "Trotz des Regens gehen wir aus.", "رغم المطر نخرج.", "Trotz der Kälte läuft er.", "رغم البرد يركض."],
  ["während", "G", "أثناء", "Während des Films lachen alle.", "أثناء الفيلم يضحك الجميع.", "Während der Woche arbeite ich.", "أثناء الأسبوع أعمل."],
  ["wegen", "G", "بسبب", "Wegen des Wetters bleiben wir hier.", "بسبب الطقس نبقى هنا.", "Wegen Krankheit fehlt er.", "بسبب المرض يغيب."],
  ["statt", "G", "بدلًا من", "Statt des Busses nehme ich das Taxi.", "بدل الحافلة آخذ التاكسي.", "Statt der Arbeit bleibt er zu Hause.", "بدل العمل يبقى في البيت."],
  ["an", "A/D", "على / في / إلى", "Ich denke an dich.", "أفكر فيك.", "Das Bild hängt an der Wand.", "الصورة على الحائط."],
  ["auf", "A/D", "على", "Ich lege das Buch auf den Tisch.", "أضع الكتاب على الطاولة.", "Das Buch liegt auf dem Tisch.", "الكتاب على الطاولة."],
  ["in", "A/D", "في / إلى", "Ich gehe in die Schule.", "أذهب إلى المدرسة.", "Ich bin in der Schule.", "أنا في المدرسة."],
  ["über", "A/D", "فوق / عن", "Er hängt das Bild über das Sofa.", "يعلق الصورة فوق الأريكة.", "Wir sprechen über den Film.", "نتحدث عن الفيلم."],
  ["unter", "A/D", "تحت", "Die Katze liegt unter dem Tisch.", "القطة تحت الطاولة.", "Er stellt den Stuhl unter den Tisch.", "يضع الكرسي تحت الطاولة."],
  ["vor", "A/D", "أمام / قبل", "Das Auto steht vor dem Haus.", "السيارة أمام البيت.", "Er stellt das Auto vor das Haus.", "يضع السيارة أمام البيت."],
  ["hinter", "A/D", "خلف", "Der Garten ist hinter dem Haus.", "الحديقة خلف البيت.", "Geh hinter das Haus!", "اذهب خلف البيت!"],
  ["neben", "A/D", "بجانب", "Sie sitzt neben mir.", "تجلس بجانبي.", "Setz dich neben mich!", "اجلس بجانبي!"],
  ["zwischen", "A/D", "بين", "Der Brief liegt zwischen den Büchern.", "الرسالة بين الكتب.", "Leg den Brief zwischen die Bücher!", "ضع الرسالة بين الكتب!"],
];

/* [prep, accDe, accAr, datDe, datAr] Wechselpräposition contrasts */
const TWOWAY = [
  ["in", "Ich gehe in die Schule.", "أذهب إلى المدرسة.", "Ich bin in der Schule.", "أنا في المدرسة."],
  ["auf", "Leg das Buch auf den Tisch!", "ضع الكتاب على الطاولة!", "Das Buch liegt auf dem Tisch.", "الكتاب على الطاولة."],
  ["an", "Häng das Bild an die Wand!", "علق الصورة على الحائط!", "Das Bild hängt an der Wand.", "الصورة على الحائط."],
  ["über", "Häng die Lampe über den Tisch!", "علق المصباح فوق الطاولة!", "Die Lampe hängt über dem Tisch.", "المصباح فوق الطاولة."],
  ["unter", "Stell den Stuhl unter den Tisch!", "ضع الكرسي تحت الطاولة!", "Die Katze ist unter dem Tisch.", "القطة تحت الطاولة."],
  ["vor", "Fahr das Auto vor das Haus!", "قد السيارة أمام البيت!", "Das Auto steht vor dem Haus.", "السيارة أمام البيت."],
  ["hinter", "Geh hinter das Haus!", "اذهب خلف البيت!", "Der Garten ist hinter dem Haus.", "الحديقة خلف البيت."],
  ["neben", "Setz dich neben mich!", "اجلس بجانبي!", "Sie sitzt neben mir.", "تجلس بجانبي."],
  ["zwischen", "Leg es zwischen die Bücher!", "ضعه بين الكتب!", "Es liegt zwischen den Büchern.", "إنه بين الكتب."],
];

/* [prep/pattern, useAr, exDe, exAr] temporal expressions */
const TEMPORAL = [
  ["um 8 Uhr", "الساعة الثامنة", "Der Kurs beginnt um 8 Uhr.", "تبدأ الدورة في الثامنة."],
  ["am Montag", "يوم الاثنين", "Am Montag arbeite ich.", "يوم الاثنين أعمل."],
  ["im Mai", "في مايو", "Im Mai reisen wir.", "في مايو نسافر."],
  ["im Sommer", "في الصيف", "Im Sommer ist es heiß.", "في الصيف الجو حار."],
  ["vor einer Woche", "قبل أسبوع", "Vor einer Woche kam er an.", "قبل أسبوع وصل."],
  ["nach dem Essen", "بعد الأكل", "Nach dem Essen ruhe ich.", "بعد الأكل أستريح."],
  ["seit einem Jahr", "منذ سنة", "Seit einem Jahr lerne ich Deutsch.", "منذ سنة أتعلم الألمانية."],
  ["bis morgen", "حتى الغد", "Bis morgen bleibt er hier.", "حتى الغد يبقى هنا."],
  ["von 8 bis 12", "من 8 حتى 12", "Ich arbeite von 8 bis 12 Uhr.", "أعمل من الثامنة حتى الثانية عشرة."],
  ["an Weihnachten", "في عيد الميلاد", "An Weihnachten besuchen wir Oma.", "في عيد الميلاد نزور الجدة."],
  ["am Wochenende", "في عطلة الأسبوع", "Am Wochenende schlafen wir lange.", "في العطلة ننام طويلًا."],
  ["morgens/abends", "صباحًا/مساءً", "Morgens trinke ich Kaffee.", "صباحًا أشرب القهوة."],
];

/* [modal, meaningAr, exDe, exAr] */
const MODALMEAN = [
  ["können", "الاستطاعة", "Ich kann schwimmen.", "أستطيع السباحة."],
  ["können", "الإذن", "Du kannst gehen.", "يمكنك الذهاب."],
  ["müssen", "الضرورة", "Ich muss arbeiten.", "يجب أن أعمل."],
  ["müssen", "الاستنتاج القوي", "Er muss krank sein.", "لا بد أنه مريض."],
  ["dürfen", "السماح", "Du darfst hier parken.", "يُسمح لك بالوقوف هنا."],
  ["dürfen", "المنع (نفي)", "Du darfst hier nicht rauchen.", "ممنوع التدخين هنا."],
  ["sollen", "النصيحة/الأمر", "Du sollst zum Arzt gehen.", "ينبغي أن تذهب للطبيب."],
  ["sollen", "نقل الكلام", "Er soll krank sein.", "يُقال إنه مريض."],
  ["wollen", "الإرادة", "Ich will nach Hause.", "أريد الذهاب للبيت."],
  ["wollen", "الادعاء", "Er will alles wissen.", "يدعي معرفة كل شيء."],
  ["möchten", "الرغبة المهذبة", "Ich möchte einen Kaffee.", "أود قهوة."],
  ["möchten", "العرض", "Möchten Sie etwas trinken?", "هل تود شرب شيء؟"],
  ["können", "الاحتمال", "Es kann morgen regnen.", "قد تمطر غدًا."],
  ["müssen", "الحتمية", "Alle müssen sterben.", "الجميع سيموت حتمًا."],
  ["dürfen", "الاحتمال الضعيف", "Das dürfte stimmen.", "قد يكون صحيحًا."],
  ["sollen", "السؤال عن الرأي", "Soll ich dir helfen?", "هل أساعدك؟"],
  ["wollen", "المستقبل القريب", "Es will einfach nicht klappen.", "الأمر لا ينجح ببساطة."],
  ["mögen", "الإعجاب", "Ich mag Schokolade.", "أحب الشوكولاتة."],
  ["möchten", "التمني", "Ich möchte gern reisen.", "أتمنى السفر."],
  ["können", "المهارة", "Sie kann gut kochen.", "تجيد الطبخ."],
];

/* [tense, useAr, formAr, exDe, exAr] */
const TENSE = [
  ["Präsens", "الحاضر والعادات", "الفعل مصرف ثانيًا", "Ich lerne Deutsch.", "أتعلم الألمانية."],
  ["Präsens", "المستقبل القريب", "زمن حاضر + وقت", "Morgen fahre ich nach Berlin.", "غدًا أسافر إلى برلين."],
  ["Perfekt", "الماضي المحكي", "haben/sein + التصريف", "Ich habe gestern gearbeitet.", "عملت أمس."],
  ["Perfekt", "الماضي مع الحركة", "sein + التصريف", "Er ist nach Berlin gefahren.", "سافر إلى برلين."],
  ["Präteritum", "الماضي المكتوب", "صيغة الماضي", "Er kam, sah und siegte.", "أتى ورأى وانتصر."],
  ["Präteritum", "السرد والحكايات", "war/hatte/kam/ging", "Es war einmal ein König.", "كان يا ما كان ملك."],
  ["Plusquamperfekt", "ماضٍ قبل ماضٍ", "hatte/war + التصريف", "Nachdem er gegessen hatte, ging er.", "بعد أن أكل ذهب."],
  ["Futur I", "المستقبل والنية", "werden + المصدر", "Ich werde morgen anrufen.", "سأتصل غدًا."],
  ["Futur I", "الوعد", "werden + المصدر", "Ich werde dir helfen.", "سأساعدك."],
  ["Futur I", "الافتراض", "werden + المصدر", "Er wird schon schlafen.", "لابد أنه نائم الآن."],
  ["Präsens", "الحقائق العامة", "زمن حاضر", "Die Sonne scheint.", "الشمس مشرقة."],
  ["Perfekt", "التجارب", "haben + التصريف", "Ich habe Sushi noch nie gegessen.", "لم آكل السوشي أبدًا."],
  ["Präteritum", "الأفعال الشائعة", "war/hatte/wollte/konnte", "Ich wollte dich besuchen.", "أردت زيارتك."],
  ["Plusquamperfekt", "بعد nachdem", "hatte/war + التصريف", "Nachdem sie angekommen war, aßen wir.", "بعد وصولها أكلنا."],
  ["Futur I", "التخمين", "werden + المصدر", "Das wird stimmen.", "سيكون صحيحًا."],
  ["Präsens", "الأوامر المهذبة", "صيغة حاضر", "Du räumst jetzt dein Zimmer auf!", "رتب غرفتك الآن!"],
  ["Perfekt", "النفي في الماضي", "haben/sein + nicht + التصريف", "Ich habe nicht geschlafen.", "لم أنم."],
  ["Präteritum", "المداومة الماضية", "صيغة الماضي", "Früher spielte er Tennis.", "سابقًا لعب التنس."],
  ["Futur I", "القرار الفوري", "werden + المصدر", "Ich werde das machen!", "سأفعل ذلك!"],
  ["Präsens", "الجداول", "زمن حاضر", "Der Zug fährt um 8 Uhr.", "يغادر القطار الثامنة."],
  ["Perfekt", "الأسئلة عن الماضي", "haben/sein + التصريف", "Hast du schon gegessen?", "هل أكلت؟"],
  ["Präteritum", "التقارير", "صيغة الماضي", "Der Bericht erschien gestern.", "صدر التقرير أمس."],
  ["Plusquamperfekt", "الأعذار", "hatte + التصريف", "Ich hatte den Bus verpasst.", "فاتتني الحافلة."],
  ["Futur I", "التهديد اللطيف", "werden + المصدر", "Du wirst das bereuen!", "ستندم على ذلك!"],
  ["Präsens", "التعليمات", "زمن حاضر", "Man nimmt zwei Eier.", "نأخذ بيضتين."],
  ["Perfekt", "الأخبار", "haben/sein + التصريف", "Es hat gestern geregnet.", "أمطرت أمس."],
  ["Präteritum", "الأدب", "صيغة الماضي", "Er öffnete die Tür langsam.", "فتح الباب ببطء."],
  ["Futur I", "الوعود الرسمية", "werden + المصدر", "Wir werden uns melden.", "سنتصل بك."],
  ["Präsens", "الروتين", "زمن حاضر", "Jeden Tag stehe ich früh auf.", "كل يوم أنهض مبكرًا."],
  ["Perfekt", "الإنجازات", "haben + التصريف", "Ich habe viel gelernt.", "تعلمت كثيرًا."],
];

/* [point, ruleAr, exDe, exAr] negation */
const NEGATION = [
  ["nicht am Ende", "nicht في آخر الجملة", "Ich komme heute nicht.", "لن آتي اليوم."],
  ["nicht vor Adjektiv", "nicht قبل الصفة", "Das ist nicht gut.", "هذا ليس جيدًا."],
  ["kein + Nomen", "kein تنفي الاسم", "Ich habe kein Auto.", "ليس لدي سيارة."],
  ["kein dekliniert", "kein تُصرف", "Er trinkt keinen Kaffee.", "لا يشرب قهوة."],
  ["nie", "أبدًا", "Ich rauche nie.", "لا أدخن أبدًا."],
  ["niemals", "أبدًا (توكيد)", "Das vergesse ich niemals.", "لن أنسى ذلك أبدًا."],
  ["nichts", "لا شيء", "Ich höre nichts.", "لا أسمع شيئًا."],
  ["niemand", "لا أحد", "Niemand ist da.", "لا أحد هنا."],
  ["nirgends", "لا مكان", "Nirgends ist es so schön.", "لا مكان أجمل."],
  ["nicht mehr", "لم يعد", "Er raucht nicht mehr.", "لم يعد يدخن."],
  ["noch nicht", "ليس بعد", "Er ist noch nicht da.", "ليس هنا بعد."],
  ["kein vs nicht", "kein للأسماء", "Ich habe kein Geld, ich bin nicht reich.", "ليس لدي مال، لست غنيًا."],
  ["doppelte Verneinung", "نفي مزدوج خاطئ", "Falsch: Ich habe kein kein Geld.", "خطأ: نفي مزدوج."],
  ["nicht nur", "ليس فقط", "Er spricht nicht nur Deutsch.", "لا يتحدث الألمانية فقط."],
];

/* [point, ruleAr, exDe, exAr] comparison */
const COMPARISON = [
  ["als", "أفعل التفضيل مع als", "Er ist größer als ich.", "هو أطول مني."],
  ["wie", "التساوي مع wie", "Sie ist so groß wie ich.", "هي بطولي."],
  ["immer + Komparativ", "التزايد", "Es wird immer wärmer.", "الجو يزداد دفئًا."],
  ["je desto", "كلما", "Je mehr du übst, desto besser.", "كلما تدربت أكثر كان أفضل."],
  ["am + sten", "صيغة التفضيل العليا", "Er ist am schnellsten.", "هو الأسرع."],
  ["der/die/das + ste", "التفضيل مع أداة", "Sie ist die Beste.", "هي الأفضل."],
  ["mehr/weniger", "أكثر/أقل", "Ich habe mehr Zeit.", "لدي وقت أكثر."],
  ["lieber/am liebsten", "يفضل/الأفضل", "Ich trinke lieber Tee.", "أفضل الشاي."],
  ["Umlaut", "التفضيل مع umlaut", "groß - größer - größt", "كبير - أكبر."],
  ["unregelmäßig", "الشواذ", "gut - besser - best", "جيد - أفضل."],
];

/* [particle, useAr, exDe, exAr] modal particles */
const PARTICLES = [
  ["doch", "التوكيد/المخالفة", "Komm doch mit!", "تعال معنا!"],
  ["mal", "التخفيف", "Schau mal!", "انظر!"],
  ["denn", "الاستغراب في السؤال", "Was machst du denn hier?", "ماذا تفعل هنا؟"],
  ["ja", "المعروف", "Das ist ja klar!", "هذا واضح!"],
  ["eigentlich", "في الحقيقة (سؤال)", "Wie heißt du eigentlich?", "ما اسمك في الحقيقة؟"],
  ["wohl", "الاحتمال", "Er wird wohl schlafen.", "لابد أنه نائم."],
  ["etwa", "الدهشة", "Willst du etwa gehen?", "أتريد الذهاب حقًا؟"],
  ["bloß", "التحذير", "Pass bloß auf!", "انتبه جيدًا!"],
  ["nur", "الحصر اللطيف", "Bleib nur hier!", "ابق هنا فقط!"],
  ["schon", "الطمأنة", "Das wird schon!", "سيكون بخير!"],
];

/* [word, arMeaning, exDe, exAr] question words */
const QWORDS = [
  ["wer", "من (فاعل)", "Wer kommt heute?", "من يأتي اليوم؟"],
  ["wen", "من (مفعول)", "Wen besuchst du?", "من تزور؟"],
  ["wem", "لمن", "Wem gehört das Buch?", "لمن الكتاب؟"],
  ["wessen", "لمن (ملكية)", "Wessen Tasche ist das?", "حقيبة من هذه؟"],
  ["was", "ماذا", "Was machst du?", "ماذا تفعل؟"],
  ["welcher", "أي", "Welcher Film läuft?", "أي فيلم يُعرض؟"],
  ["was für", "أي نوع", "Was für Musik hörst du?", "أي موسيقى تسمع؟"],
  ["wo", "أين", "Wo wohnst du?", "أين تسكن؟"],
  ["wohin", "إلى أين", "Wohin gehst du?", "إلى أين تذهب؟"],
  ["woher", "من أين", "Woher kommst du?", "من أين أنت؟"],
  ["wann", "متى", "Wann kommst du?", "متى تأتي؟"],
  ["wie", "كيف", "Wie geht es dir?", "كيف حالك؟"],
  ["wie viel", "كم (غير معدود)", "Wie viel kostet das?", "كم سعر هذا؟"],
  ["wie viele", "كم (معدود)", "Wie viele Kinder hast du?", "كم طفلًا لديك؟"],
  ["warum", "لماذا", "Warum weinst du?", "لماذا تبكي؟"],
  ["wofür", "لأي غرض", "Wofür brauchst du das?", "لم تحتاج هذا؟"],
];

/* [expr, arMeaning, exDe, exAr] time expressions */
const TIMEEXPR = [
  ["morgens", "صباحًا", "Morgens trinke ich Kaffee.", "صباحًا أشرب القهوة."],
  ["mittags", "ظهرًا", "Mittags esse ich warm.", "ظهرًا آكل ساخنًا."],
  ["abends", "مساءً", "Abends sehe ich fern.", "مساءً أشاهد التلفاز."],
  ["nachts", "ليلًا", "Nachts schläft alles.", "ليلًا ينام الجميع."],
  ["heute Morgen", "صباح اليوم", "Heute Morgen war ich beim Arzt.", "صباح اليوم كنت عند الطبيب."],
  ["morgen früh", "غدًا صباحًا", "Morgen früh rufe ich an.", "غدًا صباحًا أتصل."],
  ["vorgestern", "أول أمس", "Vorgestern regnete es.", "أول أمس أمطرت."],
  ["übermorgen", "بعد غد", "Übermorgen fliege ich.", "بعد غد أسافر طيرانًا."],
  ["letzte Woche", "الأسبوع الماضي", "Letzte Woche war ich krank.", "الأسبوع الماضي مرضت."],
  ["nächste Woche", "الأسبوع القادم", "Nächste Woche reisen wir.", "الأسبوع القادم نسافر."],
  ["jedes Jahr", "كل سنة", "Jedes Jahr fahren wir ans Meer.", "كل سنة نذهب للبحر."],
  ["einmal pro Woche", "مرة أسبوعيًا", "Einmal pro Woche putze ich.", "مرة أسبوعيًا أنظف."],
  ["zweimal am Tag", "مرتين يوميًا", "Zweimal am Tag esse ich Obst.", "مرتين يوميًا آكل فاكهة."],
  ["den ganzen Tag", "طوال اليوم", "Den ganzen Tag arbeitet er.", "طوال اليوم يعمل."],
  ["pünktlich", "في الموعد", "Sei bitte pünktlich!", "كن دقيقًا من فضلك!"],
  ["zu spät", "متأخر", "Du kommst zu spät.", "تأتي متأخرًا."],
  ["rechtzeitig", "في الوقت المناسب", "Komm bitte rechtzeitig!", "تعال في الوقت المناسب!"],
  ["sofort", "فورًا", "Komm sofort her!", "تعال فورًا!"],
];

/* [topic, level, focusAr, exDe, exAr] situational grammar spotlights */
const SITU = [
  ["doctor", "A1", "الألم مع Dativ", "Mein Kopf tut mir weh.", "رأسي يؤلمني."],
  ["doctor", "A2", "seit + الأعراض", "Seit drei Tagen huste ich.", "منذ ثلاثة أيام أسعل."],
  ["doctor", "B1", "Schmerzen beschreiben", "Ich habe stechende Schmerzen im Rücken.", "لدي ألم طاعن في الظهر."],
  ["restaurant", "A1", "الطلب", "Ich hätte gern die Suppe.", "أود الشوربة."],
  ["restaurant", "A2", "الشكوى المهذبة", "Entschuldigung, die Suppe ist kalt.", "عذرًا، الشوربة باردة."],
  ["restaurant", "B1", "الدفع والبقشيش", "Stimmt so, der Rest ist für Sie.", "الباقي لك."],
  ["hotel", "A1", "الحجز", "Ich habe ein Zimmer reserviert.", "حجزت غرفة."],
  ["hotel", "A2", "المشاكل", "Die Dusche funktioniert nicht.", "الدش لا يعمل."],
  ["hotel", "B1", "الشكوى الرسمية", "Ich möchte mich über den Lärm beschweren.", "أود الشكوى من الضجيج."],
  ["airport", "A1", "الاتجاهات", "Wo ist Gate 5?", "أين البوابة 5؟"],
  ["airport", "A2", "التأخير", "Mein Flug hat zwei Stunden Verspätung.", "رحلتي متأخرة ساعتين."],
  ["airport", "B1", "الأمتعة المفقودة", "Mein Koffer ist verloren gegangen.", "حقيبتي ضاعت."],
  ["work", "A1", "تقديم النفس", "Ich arbeite als Lehrer.", "أعمل مدرسًا."],
  ["work", "A2", "المرضية", "Ich bin heute krank.", "أنا مريض اليوم."],
  ["work", "B1", "الاجتماعات", "Könnten wir das Meeting verschieben?", "هل يمكننا تأجيل الاجتماع؟"],
  ["shopping", "A1", "السؤال عن السعر", "Wie viel kostet das?", "كم سعر هذا؟"],
  ["shopping", "A2", "المقاس والتبديل", "Haben Sie das eine Nummer größer?", "هل لديك مقاس أكبر؟"],
  ["shopping", "B1", "الإرجاع", "Ich möchte das umtauschen.", "أود استبدال هذا."],
  ["bank", "A1", "فتح حساب", "Ich möchte ein Konto eröffnen.", "أود فتح حساب."],
  ["bank", "A2", "التحويل", "Ich möchte Geld überweisen.", "أود تحويل نقود."],
  ["bank", "B1", "القرض", "Ich interessiere mich für einen Kredit.", "أهتم بقرض."],
  ["school", "A1", "الاعتذار", "Entschuldigung, ich bin zu spät.", "عذرًا، تأخرت."],
  ["school", "A2", "الواجب", "Ich habe meine Hausaufgaben vergessen.", "نسيت واجبي."],
  ["school", "B1", "النقاش", "Meiner Meinung nach ist das unfair.", "في رأيي هذا ظالم."],
  ["travel", "A1", "التذاكر", "Eine Fahrkarte nach Berlin, bitte.", "تذكرة إلى برلين من فضلك."],
  ["travel", "A2", "التبديل", "Muss ich umsteigen?", "هل يجب أن أبدل؟"],
  ["travel", "B1", "الشكوى", "Der Zug hatte eine Stunde Verspätung.", "تأخر القطار ساعة."],
  ["home", "A1", "الأثاث", "Das Sofa steht im Wohnzimmer.", "الأريكة في غرفة المعيشة."],
  ["home", "A2", "الإصلاح", "Der Wasserhahn tropft.", "الصنبور يقطر."],
  ["home", "B1", "المالك", "Die Heizung funktioniert nicht.", "التدفئة لا تعمل."],
  ["family", "A1", "التعارف", "Das ist meine Schwester.", "هذه أختي."],
  ["family", "A2", "الخطط", "Am Sonntag besuchen wir Oma.", "الأحد نزور الجدة."],
  ["family", "B1", "الخلافات", "Lass uns in Ruhe darüber reden.", "لنتحدث بهدوء عن الأمر."],
  ["emergency", "A1", "طلب النجدة", "Hilfe! Rufen Sie einen Krankenwagen!", "النجدة! اتصلوا بالإسعاف!"],
  ["emergency", "A2", "وصف الحادث", "Es gab einen Unfall.", "وقع حادث."],
  ["emergency", "B1", "البلاغ", "Ich möchte einen Unfall melden.", "أود الإبلاغ عن حادث."],
  ["weather", "A1", "الوصف", "Heute ist es sonnig.", "اليوم مشمس."],
  ["weather", "A2", "الخطط حسب الطقس", "Bei Regen bleiben wir zu Hause.", "عند المطر نبقى في البيت."],
  ["weather", "B1", "التحذيرات", "Es wird vor Glatteis gewarnt.", "يُحذر من الجليد."],
  ["food", "A1", "الطلب", "Ich nehme den Salat.", "آخذ السلطة."],
  ["food", "A2", "الحساسية", "Ich bin allergisch gegen Nüsse.", "لدي حساسية من المكسرات."],
  ["food", "B1", "الوصفات", "Man brät die Zwiebeln glasig.", "نقلي البصل حتى يشف."],
  ["study", "A1", "الجامعة", "Ich studiere Medizin.", "أدرس الطب."],
  ["study", "A2", "الامتحانات", "Wann ist die Prüfung?", "متى الامتحان؟"],
  ["study", "B1", "الأطروحة", "Ich schreibe meine Bachelorarbeit.", "أكتب أطروحة البكالوريوس."],
  ["sports", "A1", "الهوايات", "Ich spiele gern Fußball.", "أحب كرة القدم."],
  ["sports", "A2", "النادي", "Bist du im Verein?", "هل أنت في النادي؟"],
  ["sports", "B1", "الإصابات", "Ich habe mir das Knie verletzt.", "أصبت ركبتي."],
  ["city", "A1", "السؤال عن الطريق", "Wo ist der Bahnhof?", "أين المحطة؟"],
  ["city", "A2", "الوصف", "Der Bahnhof ist weit weg.", "المحطة بعيدة."],
  ["city", "B1", "المواصلات", "Welche Linie fährt zum Zentrum?", "أي خط يذهب للمركز؟"],
  ["communication", "A1", "الهاتف", "Kann ich bitte mit Sara sprechen?", "هل يمكنني التحدث مع سارة؟"],
  ["communication", "A2", "الرسائل", "Ich rufe später zurück.", "سأعاود الاتصال لاحقًا."],
  ["communication", "B1", "الرسميات", "Wären Sie so nett, mir zu schreiben?", "هل تتفضل بالكتابة لي؟"],
  ["time", "A1", "الساعة", "Wie spät ist es?", "كم الساعة؟"],
  ["time", "A2", "المواعيد", "Passt dir morgen um drei?", "هل يناسبك الغد الثالثة؟"],
  ["time", "B1", "التأجيل", "Können wir auf Freitag verschieben?", "هل نؤجل للجمعة؟"],
  ["money", "A1", "الدفع", "Ich zahle bar.", "أدفع نقدًا."],
  ["money", "A2", "الفاتورة", "Die Rechnung, bitte.", "الفاتورة من فضلك."],
  ["money", "B1", "التقسيط", "Kann ich in Raten zahlen?", "هل يمكنني الدفع تقسيطًا؟"],
];

module.exports = { CONN, PREPCASE, TWOWAY, TEMPORAL, MODALMEAN, TENSE, NEGATION, COMPARISON, PARTICLES, QWORDS, TIMEEXPR, SITU };
