/* Deutsch Master — BIG grammar data 1: verb-prepositions, dative/ditransitive/
   reflexive verbs, mistake contrasts. All rows hand-curated (correct case,
   correct Arabic). Consumed by tools/build-grammar2.js */
"use strict";

/* [inf, prep, case(A/D), ar-with-prep] — NEW (existing VPREP covered via VPREP_CASES). */
const BIGVPREP = [
  ["sich erinnern", "an", "A", "يتذكر"], ["schreiben", "an", "A", "يكتب إلى"],
  ["schicken", "an", "A", "يرسل إلى"], ["liefern", "an", "A", "يوصل إلى"],
  ["verkaufen", "an", "A", "يبيع لـ"], ["vermieten", "an", "A", "يؤجر لـ"],
  ["sich wenden", "an", "A", "يتوجه إلى"], ["sich richten", "an", "A", "يوجه إلى"],
  ["grenzen", "an", "A", "يحد"], ["angrenzen", "an", "A", "يجاور"],
  ["appellieren", "an", "A", "يناشد"], ["fehlen", "an", "D", "يفتقد"],
  ["mangeln", "an", "D", "ينقص"], ["leiden", "an", "D", "يعاني من"],
  ["erkranken", "an", "D", "يمرض بـ"], ["sich orientieren", "an", "D", "يهتدي بـ"],
  ["liegen", "an", "D", "يكمن في"], ["hoffen", "auf", "A", "يأمل في"],
  ["achten", "auf", "A", "ينتبه إلى"], ["aufpassen", "auf", "A", "ينتبه إلى"],
  ["reagieren", "auf", "A", "يرد على"], ["antworten", "auf", "A", "يجيب على"],
  ["bestehen", "auf", "A", "يصر على"], ["verzichten", "auf", "A", "يتنازل عن"],
  ["zurückgreifen", "auf", "A", "يلجأ إلى"], ["sich beziehen", "auf", "A", "يستند إلى"],
  ["sich verlassen", "auf", "A", "يعتمد على"], ["schwören", "auf", "A", "يقسم على"],
  ["wetten", "auf", "A", "يراهن على"], ["sich vorbereiten", "auf", "A", "يستعد لـ"],
  ["Lust haben", "auf", "A", "يرغب في"], ["stolz sein", "auf", "A", "فخور بـ"],
  ["neugierig sein", "auf", "A", "فضولي حول"], ["gespannt sein", "auf", "A", "متشوق لـ"],
  ["eifersüchtig sein", "auf", "A", "غيور على"], ["wütend sein", "auf", "A", "غاضب من"],
  ["böse sein", "auf", "A", "غاضب على"], ["stehen", "auf", "A", "يصر على"],
  ["bauen", "auf", "A", "يبني على"], ["zählen", "auf", "A", "يعتمد على"],
  ["drängen", "auf", "A", "يلح على"], ["basieren", "auf", "D", "يستند إلى"],
  ["beharren", "auf", "D", "يصر على"], ["ruhen", "auf", "D", "يرتاح على"],
  ["lasten", "auf", "D", "يثقل على"], ["sich wundern", "über", "A", "يتعجب من"],
  ["sich aufregen", "über", "A", "ينفعل من"], ["schimpfen", "über", "A", "يوبخ على"],
  ["staunen", "über", "A", "يندهش من"], ["trauern", "über", "A", "يحزن على"],
  ["weinen", "über", "A", "يبكي على"], ["siegen", "über", "A", "ينتصر على"],
  ["sich einigen", "über", "A", "يتفق على"], ["sich konzentrieren", "über", "A", "يركز على"],
  ["einwirken", "über", "A", "يؤثر على"], ["sich auswirken", "über", "A", "يؤثر على"],
  ["anspielen", "über", "A", "يلمح إلى"], ["hindeuten", "über", "A", "يشير إلى"],
  ["arbeiten", "für", "A", "يعمل لدى"], ["zahlen", "für", "A", "يدفع لـ"],
  ["sich entschuldigen", "für", "A", "يعتذر عن"], ["sich schämen", "für", "A", "يخجل من"],
  ["bürgen", "für", "A", "يكفل"], ["garantieren", "für", "A", "يضمن"],
  ["sich verbürgen", "für", "A", "يكفل"], ["sich aussprechen", "für", "A", "يؤيد"],
  ["plädieren", "für", "A", "يترافع لـ"], ["werben", "für", "A", "يدعو لـ"],
  ["kämpfen", "um", "A", "يكافح من أجل"], ["spielen", "um", "A", "يلعب على"],
  ["wetten", "um", "A", "يراهن على"], ["beneiden", "um", "A", "يحسد على"],
  ["betrügen", "um", "A", "يغش في"], ["sich sorgen", "um", "A", "يقلق على"],
  ["sich ängstigen", "um", "A", "يخاف على"], ["trauern", "um", "A", "يحزن على"],
  ["weinen", "um", "A", "يبكي على"], ["sich bemühen", "um", "A", "يسعى لـ"],
  ["werben", "um", "A", "يروج لـ"], ["sich reißen", "um", "A", "يتقاتل على"],
  ["feilschen", "um", "A", "يساوم على"], ["sich verwandeln", "in", "A", "يتحول إلى"],
  ["einmünden", "in", "A", "يصب في"], ["übergehen", "in", "A", "يتحول إلى"],
  ["sich einfühlen", "in", "A", "يتعاطف مع"], ["sich vertiefen", "in", "A", "يتعمق في"],
  ["sich teilen", "in", "A", "يتقاسم"], ["sich irren", "in", "D", "يخطئ في"],
  ["sich täuschen", "in", "D", "يخطئ في"], ["sich auskennen", "in", "D", "يعرف في"],
  ["enden", "in", "D", "ينتهي بـ"], ["gipfeln", "in", "D", "يبلغ ذروته في"],
  ["passen", "zu", "D", "يناسب"], ["zählen", "zu", "D", "يُحتسب ضمن"],
  ["werden", "zu", "D", "يتحول إلى"], ["sich entwickeln", "zu", "D", "يتطور إلى"],
  ["sich entschließen", "zu", "D", "يقرر"], ["neigen", "zu", "D", "يميل إلى"],
  ["tendieren", "zu", "D", "يميل إلى"], ["beitragen", "zu", "D", "يساهم في"],
  ["handeln", "von", "D", "يتحدث عن"], ["wissen", "von", "D", "يعرف عن"],
  ["sich verabschieden", "von", "D", "يودع"], ["stammen", "von", "D", "ينحدر من"],
  ["sich unterscheiden", "von", "D", "يختلف عن"], ["abraten", "von", "D", "ينصح ضد"],
  ["schwärmen", "von", "D", "يتغنى بـ"], ["trinken", "aus", "D", "يشرب من"],
  ["essen", "aus", "D", "يأكل من"], ["lesen", "aus", "D", "يقرأ من"],
  ["vorlesen", "aus", "D", "يقرأ من"], ["zitieren", "aus", "D", "يقتبس من"],
  ["rechnen", "mit", "D", "يحسب"], ["handeln", "mit", "D", "يتاجر بـ"],
  ["prahlen", "mit", "D", "يتباهى بـ"], ["geizen", "mit", "D", "يبخل بـ"],
  ["sich rühmen", "mit", "D", "يفتخر بـ"], ["sich begnügen", "mit", "D", "يكتفي بـ"],
  ["sich abfinden", "mit", "D", "يتقبل"], ["arbeiten", "bei", "D", "يعمل لدى"],
  ["bleiben", "bei", "D", "يبقى عند"], ["sich bedanken", "bei", "D", "يشكر"],
  ["sich entschuldigen", "bei", "D", "يعتذر لدى"], ["sich beschweren", "bei", "D", "يشتكي لدى"],
  ["anrufen", "bei", "D", "يتصل بـ"], ["vorbeischauen", "bei", "D", "يزور"],
  ["übernachten", "bei", "D", "يبيت عند"], ["wohnen", "bei", "D", "يسكن عند"],
  ["greifen", "nach", "D", "يمسك بـ"], ["streben", "nach", "D", "يسعى إلى"],
  ["duften", "nach", "D", "يفوح بـ"], ["kämpfen", "gegen", "A", "يكافح ضد"],
  ["protestieren", "gegen", "A", "يحتج على"], ["verstoßen", "gegen", "A", "ينتهك"],
  ["wetten", "gegen", "A", "يراهن ضد"], ["sein", "gegen", "A", "يعترض على"],
  ["stimmen", "gegen", "A", "يصوت ضد"], ["sich wehren", "gegen", "A", "يدافع ضد"],
  ["sich wenden", "gegen", "A", "يتوجه ضد"], ["sprechen", "gegen", "A", "يتحدث ضد"],
  ["auskommen", "ohne", "A", "يستغني عن"], ["fallen", "durch", "A", "يرسب في"],
  ["kommen", "durch", "A", "يجتاز"], ["reisen", "durch", "A", "يسافر عبر"],
  ["schauen", "durch", "A", "ينظر عبر"],
];

/* cases for the existing VPREP rows (inf + prep -> case). */
const VPREP_CASES = {
  "warten auf": "A", "denken an": "A", "sich freuen auf": "A", "sich freuen über": "A",
  "Angst haben vor": "D", "sich kümmern um": "A", "sich bewerben um": "A", "bitten um": "A",
  "danken für": "A", "sich beschweren über": "A", "teilnehmen an": "D", "glauben an": "A",
  "sich interessieren für": "A", "sich verlieben in": "A", "sich trennen von": "D",
  "sich gewöhnen an": "A", "leiden an": "D", "zweifeln an": "D", "riechen nach": "D",
  "schmecken nach": "D", "fragen nach": "D", "suchen nach": "D", "sich sehnen nach": "D",
  "sich erkundigen nach": "D", "gehören zu": "D", "gratulieren zu": "D", "einladen zu": "D",
  "überreden zu": "D", "beginnen mit": "D", "aufhören mit": "D", "zufrieden sein mit": "D",
  "verheiratet sein mit": "D", "sich treffen mit": "D", "sprechen mit": "D", "sprechen über": "A",
  "diskutieren über": "A", "lachen über": "A", "sich ärgern über": "A", "sich informieren über": "A",
  "sich unterhalten über": "A", "nachdenken über": "A", "entscheiden über": "A", "verfügen über": "A",
  "herrschen über": "A", "klagen über": "A", "arbeiten an": "D", "sterben an": "D",
  "sich beteiligen an": "D", "haften für": "A", "sorgen für": "A", "sich entscheiden für": "A",
  "stimmen für": "A", "kämpfen für": "A", "sich einsetzen für": "A", "bestehen aus": "D",
  "resultieren aus": "D", "lernen aus": "D", "kommen aus": "D", "fliehen aus": "D",
  "sich ergeben aus": "D", "schützen vor": "D", "warnen vor": "D", "fliehen vor": "D",
  "sich fürchten vor": "D", "Respekt haben vor": "D", "sicher sein vor": "D", "abhängen von": "D",
  "träumen von": "D", "erzählen von": "D", "hören von": "D", "profitieren von": "D",
  "sich erholen von": "D", "überzeugt sein von": "D", "begeistert sein von": "D", "enttäuscht sein von": "D",
};

/* [inf, ar] dative verbs for unit generation (examples composed). */
const DATVERBS = [
  ["helfen", "يساعد"], ["danken", "يشكر"], ["gefallen", "يعجب"], ["gehören", "يخص"],
  ["gratulieren", "يهنئ"], ["folgen", "يتبع"], ["antworten", "يجيب"], ["glauben", "يصدق"],
  ["vertrauen", "يثق بـ"], ["fehlen", "ينقص"], ["passen", "يناسب"], ["schmecken", "يعجب طعمه"],
  ["wehtun", "يؤلم"], ["zuhören", "يصغي إلى"], ["zusehen", "يشاهد"], ["zustimmen", "يوافق"],
  ["widersprechen", "يعترض على"], ["entkommen", "يهرب من"], ["beitreten", "ينضم إلى"],
  ["begegnen", "يصادف"], ["danken", "يشكر"], ["schaden", "يضر"], ["nutzen", "يفيد"],
  ["schmeicheln", "يتملق"], ["drohen", "يهدد"], ["raten", "ينصح"], ["trauen", "يثق بـ"],
  ["verzeihen", "يسامح"], ["widersprechen", "يعترض"], ["zuhören", "يصغي"],
  ["widerstehen", "يقاوم"], ["nachgehen", "يتابع"], ["beistehen", "يساند"],
  ["unterliegen", "يخضع"], ["entsprechen", "يطابق"], ["genügen", "يكفي"],
  ["imponieren", "يبهر"], ["missfallen", "لا يعجب"], ["nützen", "ينفع"],
  ["trotzen", "يتحدى"], ["widerfahren", "يحدث لـ"], ["zuvorkommen", "يسبق إلى"],
  ["einleuchten", "يقنع"], ["auffallen", "يلفت"], ["einfallen", "يخطر"], ["gelingen", "ينجح"],
  ["misslingen", "يفشل"], ["passieren", "يحدث"], ["stehen", "يناسب"], ["bekommen", "يلائم"],
  ["zusagen", "يناسب"], ["behagen", "يروق"], ["grauen", "يرعب"], ["ekeln", "يقزز"],
];

/* [inf, ar] ditransitive verbs (person + thing). */
const DITRANVERBS = [
  ["geben", "يعطي"], ["schenken", "يهدي"], ["zeigen", "يري"], ["bringen", "يحضر"],
  ["schicken", "يرسل"], ["erklären", "يشرح"], ["leihen", "يعير"], ["verkaufen", "يبيع"],
  ["senden", "يرسل"], ["wünschen", "يتمنى"], ["verbieten", "يمنع"], ["erlauben", "يسمح"],
  ["verzeihen", "يسامح"], ["mitteilen", "يبلغ"], ["empfehlen", "يوصي"], ["verraten", "يفشي"],
  ["versprechen", "يعد"], ["beibringen", "يعلم"], ["abnehmen", "يأخذ من"], ["wegnehmen", "ينتزع"],
  ["vorlesen", "يقرأ لـ"], ["schenken", "يهدي"], ["anbieten", "يعرض"], ["überlassen", "يترك لـ"],
  ["zutrauen", "يثق بقدرة"], ["zumuten", "يحمل"], ["verweigern", "يرفض إعطاء"], ["gestehen", "يعترف لـ"],
  ["erzählen", "يروي لـ"], ["berichten", "يخبر"],
];

/* [inf-with-sich, ar] reflexive verbs. */
const REFLVERBS = [
  ["sich freuen", "يفرح"], ["sich interessieren", "يهتم"], ["sich beeilen", "يسرع"],
  ["sich ärgern", "ينزعج"], ["sich erholen", "يتعافى"], ["sich entspannen", "يسترخي"],
  ["sich vorstellen", "يقدم نفسه"], ["sich anmelden", "يسجل"], ["sich abmelden", "يلغي تسجيله"],
  ["sich bewerben", "يتقدم"], ["sich beschweren", "يشتكي"], ["sich kümmern", "يعتني"],
  ["sich unterhalten", "يتحادث"], ["sich verlieben", "يقع في حب"], ["sich irren", "يخطئ"],
  ["sich wundern", "يتعجب"], ["sich fürchten", "يخاف"], ["sich schämen", "يخجل"],
  ["sich trauen", "يجرؤ"], ["sich weigern", "يرفض"], ["sich entscheiden", "يقرر"],
  ["sich bemühen", "يسعى"], ["sich gewöhnen", "يعتاد"], ["sich erkälten", "يصاب بالبرد"],
  ["sich verspäten", "يتأخر"], ["sich aufregen", "ينفعل"], ["sich beruhigen", "يهدأ"],
  ["sich verloben", "يخطب"], ["sich trennen", "ينفصل"], ["sich vertragen", "يتصالح"],
  ["sich streiten", "يتشاجر"], ["sich versöhnen", "يتصالح"], ["sich einigen", "يتفق"],
  ["sich verabreden", "يتواعد"], ["sich treffen", "يلتقي"], ["sich kennenlernen", "يتعارف"],
  ["sich amüsieren", "يستمتع"], ["sich langweilen", "يمل"], ["sich erinnern", "يتذكر"],
  ["sich auskennen", "يعرف"], ["sich ausruhen", "يستريح"], ["sich duschen", "يستحم"],
  ["sich anziehen", "يلبس"], ["sich ausziehen", "يخلع"], ["sich umziehen", "يبدل ملابسه"],
  ["sich hinsetzen", "يجلس"], ["sich hinlegen", "يستلقي"], ["sich verabschieden", "يودع"],
  ["sich erkundigen", "يستفسر"], ["sich sehnen", "يتوق"], ["sich verlassen", "يعتمد على"],
  ["sich vorbereiten", "يستعد"], ["sich konzentrieren", "يركز"], ["sich benehmen", "يتصرف"],
  ["sich betrinken", "يسكر"], ["sich überessen", "يتخم"], ["sich verfahren", "يضل الطريق"],
  ["sich verlaufen", "يضل"], ["sich verhören", "يسمع خطأ"], ["sich versprechen", "يخطئ الكلام"],
  ["sich verwählen", "يخطئ الرقم"],
];

/* [wrong, right, ruleAr, level] real learner-error contrasts. */
const MISTAKES = [
  ["Ich Deutsch lerne.", "Ich lerne Deutsch.", "الفعل المصرف في المرتبة الثانية.", "A1"],
  ["Er hilft mich.", "Er hilft mir.", "helfen يأخذ مفعولًا داتيفًا.", "A1"],
  ["Ich danke dich.", "Ich danke dir.", "danken يأخذ داتيفًا.", "A1"],
  ["Das gehört mich.", "Das gehört mir.", "gehören يأخذ داتيفًا.", "A1"],
  ["Ich freue mich auf dem Urlaub.", "Ich freue mich auf den Urlaub.", "auf هنا بمعنى الاتجاه وتأخذ أكوزاتيفًا.", "A2"],
  ["Er wartet auf dem Bus.", "Er wartet auf den Bus.", "warten auf تأخذ أكوزاتيفًا.", "A1"],
  ["Ich denke an dem Urlaub.", "Ich denke an den Urlaub.", "denken an تأخذ أكوزاتيفًا.", "A2"],
  ["Sie interessiert sich für dem Film.", "Sie interessiert sich für den Film.", "für تأخذ أكوزاتيفًا.", "A2"],
  ["Er hat gestern gegangen.", "Er ist gestern gegangen.", "gehen يأخذ sein في الماضي.", "A1"],
  ["Ich habe nach Berlin gefahren.", "Ich bin nach Berlin gefahren.", "fahren (حركة) يأخذ sein.", "A1"],
  ["Ich kann nicht kommen, weil ich bin krank.", "Ich kann nicht kommen, weil ich krank bin.", "الفعل في آخر الجملة الفرعية.", "A2"],
  ["Er sagt, dass er kommt morgen.", "Er sagt, dass er morgen kommt.", "الفعل في آخر dass.", "A2"],
  ["Ich weiß nicht, wo ist die Toilette.", "Ich weiß nicht, wo die Toilette ist.", "السؤال غير المباشر: الفعل في الآخر.", "B1"],
  ["Obwohl er ist müde, arbeitet er.", "Obwohl er müde ist, arbeitet er.", "obwohl جملة فرعية: الفعل آخرًا.", "B1"],
  ["Wenn du hast Zeit, ruf mich an.", "Wenn du Zeit hast, ruf mich an.", "wenn فرعية ثم فعل ثم فاعل.", "A2"],
  ["Ich möchte ein Kaffee.", "Ich möchte einen Kaffee.", "مذكر أكوزاتيف: einen.", "A1"],
  ["Er kauft ein neue Auto.", "Er kauft ein neues Auto.", "neutrum أكوزاتيف: ein neues.", "A1"],
  ["Sie ist eine Lehrerin.", "Sie ist Lehrerin.", "المهن بلا أداة.", "A1"],
  ["Ich bin ein Student.", "Ich bin Student.", "المهن بلا أداة.", "A1"],
  ["Er spielt den Fußball.", "Er spielt Fußball.", "الرياضات بلا أداة.", "A1"],
  ["Ich spiele den Tennis.", "Ich spiele Tennis.", "الرياضات بلا أداة.", "A1"],
  ["Mein Vater ist ein Arzt.", "Mein Vater ist Arzt.", "المهن بلا أداة.", "A1"],
  ["Ich bin 20 Jahre.", "Ich bin 20 Jahre alt.", "العمر مع sein.", "A1"],
  ["Ich lerne Deutsch für 2 Jahre.", "Ich lerne Deutsch seit 2 Jahren.", "المدة المستمرة مع seit + داتيف جمع.", "A2"],
  ["Ich wohne in Berlin seit 5 Jahre.", "Ich wohne in Berlin seit 5 Jahren.", "seit تأخذ داتيفًا.", "A2"],
  ["Er kommt aus dem Ägypten.", "Er kommt aus Ägypten.", "الدول بلا أداة غالبًا.", "A1"],
  ["Ich fahre in dem Supermarkt.", "Ich fahre in den Supermarkt.", "الاتجاه: أكوزاتيف.", "A1"],
  ["Das Bild hängt an die Wand.", "Das Bild hängt an der Wand.", "الموقع: داتيف.", "A2"],
  ["Ich hänge das Bild an der Wand.", "Ich hänge das Bild an die Wand.", "الاتجاه: أكوزاتيف.", "A2"],
  ["Er legt das Buch auf dem Tisch.", "Er legt das Buch auf den Tisch.", "legen + اتجاه = أكوزاتيف.", "A2"],
  ["Das Buch liegt auf den Tisch.", "Das Buch liegt auf dem Tisch.", "liegen + موقع = داتيف.", "A2"],
  ["Er ist größer wie ich.", "Er ist größer als ich.", "المقارنة بـ als.", "A1"],
  ["Sie ist so groß als ich.", "Sie ist so groß wie ich.", "التساوي بـ wie.", "A1"],
  ["Ich habe mehr Geld wie du.", "Ich habe mehr Geld als du.", "أفعل التفضيل مع als.", "A2"],
  ["Das ist der Mann, der ich gesehen habe.", "Das ist der Mann, den ich gesehen habe.", "الموصول في الأكوزاتيف: den.", "B1"],
  ["Ich kenne einen Mann, der spricht Deutsch.", "Ich kenne einen Mann, der Deutsch spricht.", "الفعل آخر الموصولة.", "B1"],
  ["Wenn ich Zeit habe, ich rufe dich an.", "Wenn ich Zeit habe, rufe ich dich an.", "بعد الفرعية: فعل ثم فاعل.", "A2"],
  ["Heute ich gehe in die Schule.", "Heute gehe ich in die Schule.", "بعد الظرف: فعل ثم فاعل.", "A1"],
  ["Morgen wir fahren nach Berlin.", "Morgen fahren wir nach Berlin.", "الفعل ثانيًا دائمًا.", "A1"],
  ["In Berlin ich wohne seit 5 Jahren.", "In Berlin wohne ich seit 5 Jahren.", "الفعل ثانيًا.", "A1"],
  ["Ich kann schwimmen gut.", "Ich kann gut schwimmen.", "الظرف قبل المصدر.", "A2"],
  ["Er gelesen hat das Buch.", "Er hat das Buch gelesen.", "المساعد ثم التصريف آخرًا.", "A1"],
  ["Er ist nicht noch gekommen.", "Er ist noch nicht gekommen.", "noch nicht معًا.", "A2"],
  ["Ich habe keinen Auto.", "Ich habe kein Auto.", "neutrum: kein.", "A1"],
  ["Sie hat kein Kinder.", "Sie hat keine Kinder.", "الجمع: keine.", "A1"],
  ["Er trinkt kein Kaffee.", "Er trinkt keinen Kaffee.", "مذكر أكوزاتيف: keinen.", "A1"],
  ["Ich trinke Tee, denn ich mag nicht Kaffee.", "Ich trinke Tee, denn ich mag Kaffee nicht.", "nicht في آخر الجملة.", "A1"],
  ["Er lernt viel, deshalb er spricht gut.", "Er lernt viel, deshalb spricht er gut.", "بعد deshalb: فعل ثم فاعل.", "A2"],
  ["Trotzdem er geht spazieren.", "Trotzdem geht er spazieren.", "بعد trotzdem: فعل ثم فاعل.", "A2"],
  ["Zuerst wir frühstücken, dann wir gehen.", "Zuerst frühstücken wir, dann gehen wir.", "الفعل ثانيًا.", "A1"],
  ["Ich dusche jeden Morgen.", "Ich dusche mich jeden Morgen.", "duschen فعل منعكس.", "A2"],
  ["Er wäscht die Hände.", "Er wäscht sich die Hände.", "انتبه للضمير المنعكس.", "A2"],
  ["Wir treffen um 8 Uhr.", "Wir treffen uns um 8 Uhr.", "treffen (يلتقي) منعكس.", "A2"],
  ["Sie interessiert für Musik.", "Sie interessiert sich für Musik.", "interessieren منعكس.", "B1"],
  ["Ich erinnere an dich.", "Ich erinnere mich an dich.", "erinnern منعكس.", "B1"],
  ["Er hat verspätet.", "Er hat sich verspätet.", "verspäten منعكس.", "A2"],
  ["Beeile dich!", "Beeil dich!", "الأمر من beeilen: Beeil!", "A2"],
  ["Setze dich!", "Setz dich!", "الأمر: Setz dich!", "A1"],
  ["Stehe auf!", "Steh auf!", "الأمر: Steh auf!", "A1"],
  ["Lese das Buch!", "Lies das Buch!", "الأمر من lesen: Lies!", "A1"],
  ["Esse dein Gemüse!", "Iss dein Gemüse!", "الأمر من essen: Iss!", "A1"],
  ["Spreche langsam!", "Sprich langsam!", "الأمر من sprechen: Sprich!", "A1"],
  ["Helfe mir!", "Hilf mir!", "الأمر من helfen: Hilf!", "A1"],
  ["Gebe mir das Buch!", "Gib mir das Buch!", "الأمر من geben: Gib!", "A1"],
  ["Fahre vorsichtig!", "Fahr vorsichtig!", "الأمر: Fahr!", "A1"],
  ["Schlafe gut!", "Schlaf gut!", "الأمر: Schlaf gut!", "A1"],
  ["Bin pünktlich!", "Sei pünktlich!", "الأمر من sein: Sei!", "A1"],
  ["Du möchte einen Tee?", "Möchtest du einen Tee?", "السؤال: الفعل أولًا.", "A1"],
  ["Wo du wohnst?", "Wo wohnst du?", "السؤال: الفعل ثانيًا.", "A1"],
  ["Was du machst?", "Was machst du?", "أداة الاستفهام ثم الفعل.", "A1"],
  ["Er mag Kaffee nicht?", "Mag er keinen Kaffee?", "السؤال بـ ja/nein: الفعل أولًا.", "A1"],
  ["Ich habe das Buch gelesen gestern.", "Ich habe das Buch gestern gelesen.", "التصريف في آخر الجملة.", "A1"],
  ["Gestern ich habe einen Film gesehen.", "Gestern habe ich einen Film gesehen.", "بعد الظرف: المساعد ثم الفاعل.", "A1"],
  ["Ich bin in die Schule gegangen gestern.", "Ich bin gestern in die Schule gegangen.", "التصريف آخرًا.", "A1"],
  ["Kannst du mir helfen bitte?", "Kannst du mir bitte helfen?", "bitte قبل المصدر.", "A2"],
  ["Ich muss arbeiten jeden Tag.", "Ich muss jeden Tag arbeiten.", "المصدر آخرًا.", "A1"],
  ["Er will ein Auto kaufen morgen.", "Er will morgen ein Auto kaufen.", "المصدر آخرًا.", "A1"],
  ["Sie kann gut Deutsch sprechen.", "Sie kann gut Deutsch sprechen.", "الجملة صحيحة: الظرف قبل المصدر.", "A2"],
];

/* Arabic for the correct MISTAKES sentences (hand-verified). */
const MISTAKE_AR = {
  "Ich lerne Deutsch.": "أتعلم الألمانية.",
  "Er hilft mir.": "يساعدني.",
  "Ich danke dir.": "أشكرك.",
  "Das gehört mir.": "هذا لي.",
  "Ich freue mich auf den Urlaub.": "أتشوق للإجازة.",
  "Er wartet auf den Bus.": "ينتظر الحافلة.",
  "Ich denke an den Urlaub.": "أفكر في الإجازة.",
  "Sie interessiert sich für den Film.": "تهتم بالفيلم.",
  "Er ist gestern gegangen.": "ذهب أمس.",
  "Ich bin nach Berlin gefahren.": "سافرت إلى برلين.",
  "Ich kann nicht kommen, weil ich krank bin.": "لا أستطيع المجيء لأنني مريض.",
  "Er sagt, dass er morgen kommt.": "يقول إنه سيأتي غدًا.",
  "Ich weiß nicht, wo die Toilette ist.": "لا أعرف أين الحمام.",
  "Obwohl er müde ist, arbeitet er.": "رغم أنه متعب يعمل.",
  "Wenn du Zeit hast, ruf mich an.": "إذا كان لديك وقت اتصل بي.",
  "Ich möchte einen Kaffee.": "أود قهوة.",
  "Er kauft ein neues Auto.": "يشتري سيارة جديدة.",
  "Sie ist Lehrerin.": "هي معلمة.",
  "Ich bin Student.": "أنا طالب.",
  "Er spielt Fußball.": "يلعب كرة القدم.",
  "Ich spiele Tennis.": "ألعب التنس.",
  "Mein Vater ist Arzt.": "والدي طبيب.",
  "Ich bin 20 Jahre alt.": "عمري عشرون سنة.",
  "Ich lerne Deutsch seit 2 Jahren.": "أتعلم الألمانية منذ سنتين.",
  "Ich wohne in Berlin seit 5 Jahren.": "أسكن في برلين منذ خمس سنوات.",
  "Er kommt aus Ägypten.": "هو من مصر.",
  "Ich fahre in den Supermarkt.": "أذهب إلى السوبرماركت.",
  "Das Bild hängt an der Wand.": "الصورة على الحائط.",
  "Ich hänge das Bild an die Wand.": "أعلق الصورة على الحائط.",
  "Er legt das Buch auf den Tisch.": "يضع الكتاب على الطاولة.",
  "Das Buch liegt auf dem Tisch.": "الكتاب على الطاولة.",
  "Er ist größer als ich.": "هو أطول مني.",
  "Sie ist so groß wie ich.": "هي بطولي.",
  "Ich habe mehr Geld als du.": "لدي مال أكثر منك.",
  "Das ist der Mann, den ich gesehen habe.": "هذا الرجل الذي رأيته.",
  "Ich kenne einen Mann, der Deutsch spricht.": "أعرف رجلًا يتحدث الألمانية.",
  "Wenn ich Zeit habe, rufe ich dich an.": "إذا كان لدي وقت اتصل بك.",
  "Heute gehe ich in die Schule.": "اليوم أذهب إلى المدرسة.",
  "Morgen fahren wir nach Berlin.": "غدًا نسافر إلى برلين.",
  "In Berlin wohne ich seit 5 Jahren.": "في برلين أسكن منذ خمس سنوات.",
  "Ich kann gut schwimmen.": "أجيد السباحة.",
  "Er hat das Buch gelesen.": "قرأ الكتاب.",
  "Er ist noch nicht gekommen.": "لم يأتِ بعد.",
  "Ich habe kein Auto.": "ليس لدي سيارة.",
  "Sie hat keine Kinder.": "ليس لديها أطفال.",
  "Er trinkt keinen Kaffee.": "لا يشرب قهوة.",
  "Ich trinke Tee, denn ich mag Kaffee nicht.": "أشرب الشاي لأنني لا أحب القهوة.",
  "Er lernt viel, deshalb spricht er gut.": "يدرس كثيرًا لذلك يتحدث جيدًا.",
  "Trotzdem geht er spazieren.": "ومع ذلك يتنزه.",
  "Zuerst frühstücken wir, dann gehen wir.": "أولًا نفطر ثم نذهب.",
  "Ich dusche mich jeden Morgen.": "أستحم كل صباح.",
  "Er wäscht sich die Hände.": "يغسل يديه.",
  "Wir treffen uns um 8 Uhr.": "نلتقي الثامنة.",
  "Sie interessiert sich für Musik.": "تهتم بالموسيقى.",
  "Ich erinnere mich an dich.": "أتذكرك.",
  "Er hat sich verspätet.": "تأخر.",
  "Beeil dich!": "أسرع!",
  "Setz dich!": "اجلس!",
  "Steh auf!": "انهض!",
  "Lies das Buch!": "اقرأ الكتاب!",
  "Iss dein Gemüse!": "كل خضارك!",
  "Sprich langsam!": "تحدث ببطء!",
  "Hilf mir!": "ساعدني!",
  "Gib mir das Buch!": "أعطني الكتاب!",
  "Fahr vorsichtig!": "قد بحذر!",
  "Schlaf gut!": "نم جيدًا!",
  "Sei pünktlich!": "كن دقيقًا!",
  "Möchtest du einen Tee?": "هل تود شايًا؟",
  "Wo wohnst du?": "أين تسكن؟",
  "Was machst du?": "ماذا تفعل؟",
  "Mag er keinen Kaffee?": "ألا يحب القهوة؟",
  "Ich habe das Buch gestern gelesen.": "قرأت الكتاب أمس.",
  "Gestern habe ich einen Film gesehen.": "أمس شاهدت فيلمًا.",
  "Ich bin gestern in die Schule gegangen.": "ذهبت للمدرسة أمس.",
  "Kannst du mir bitte helfen?": "هل يمكنك مساعدتي من فضلك؟",
  "Ich muss jeden Tag arbeiten.": "يجب أن أعمل يوميًا.",
  "Er will morgen ein Auto kaufen.": "يريد شراء سيارة غدًا.",
  "Sie kann gut Deutsch sprechen.": "تجيد الألمانية.",
};

module.exports = { BIGVPREP, VPREP_CASES, DATVERBS, DITRANVERBS, REFLVERBS, MISTAKES, MISTAKE_AR };
