/* Deutsch Master — BIG grammar data 3: word formation, Nomen-Verb-Verbindungen,
   Funktionsverbgefüge, B2 connectors, formal registers. Hand-curated. */
"use strict";

/* [affix, type PRE/SUF, meaningAr, examples[[de,ar]]] */
const WORDFORM = [
  ["ver-", "PRE", "التغيير/الخطأ", [["verstehen", "يفهم"], ["verkaufen", "يبيع"], ["sich verirren", "يضل"]]],
  ["be-", "PRE", "التعدية (فعل + مفعول)", [["besuchen", "يزور"], ["bezahlen", "يدفع"], ["beginnen", "يبدأ"]]],
  ["er-", "PRE", "البلوغ/الحصول", [["erfahren", "يعرف"], ["erhalten", "يحصل على"], ["erzählen", "يروي"]]],
  ["ent-", "PRE", "الإزالة/الهروب", [["entkommen", "يهرب"], ["entdecken", "يكتشف"], ["entscheiden", "يقرر"]]],
  ["emp-", "PRE", "الاستقبال", [["empfangen", "يستقبل"], ["empfehlen", "يوصي"], ["empfinden", "يشعر"]]],
  ["miss-", "PRE", "الخطأ/السوء", [["missverstehen", "يسيء الفهم"], ["misslingen", "يفشل"]]],
  ["zer-", "PRE", "التفتيت", [["zerbrechen", "يكسر"], ["zerstören", "يدمر"]]],
  ["ge-", "PRE", "الجمع/الحدوث", [["gefallen", "يعجب"], ["geschehen", "يحدث"], ["gehören", "يخص"]]],
  ["an-", "PRE", "البدء/الاتجاه (منفصل)", [["anfangen", "يبدأ"], ["anrufen", "يتصل"], ["ankommen", "يصل"]]],
  ["auf-", "PRE", "الفتح/الصعود (منفصل)", [["aufmachen", "يفتح"], ["aufstehen", "ينهض"], ["aufhören", "يتوقف"]]],
  ["aus-", "PRE", "الخروج/الإتمام (منفصل)", [["ausgehen", "يخرج"], ["ausfüllen", "يملأ"], ["aussehen", "يبدو"]]],
  ["ein-", "PRE", "الدخول (منفصل)", [["einkaufen", "يتسوق"], ["einladen", "يدعو"], ["einsteigen", "يركب"]]],
  ["mit-", "PRE", "المصاحبة (منفصل)", [["mitkommen", "يأتي مع"], ["mitbringen", "يحضر مع"], ["mitmachen", "يشارك"]]],
  ["nach-", "PRE", "التكرار/الملاحقة (منفصل)", [["nachmachen", "يقلد"], ["nachfragen", "يستفسر"], ["nachsehen", "يتحقق"]]],
  ["vor-", "PRE", "التقديم (منفصل)", [["vortragen", "يلقي"], ["vorlesen", "يقرأ بصوت"], ["vormachen", "يري كيف"]]],
  ["zu-", "PRE", "الإغلاق (منفصل)", [["zumachen", "يغلق"], ["zuhören", "يصغي"], ["zuschauen", "يشاهد"]]],
  ["weg-", "PRE", "الابتعاد (منفصل)", [["weggehen", "يذهب بعيدًا"], ["wegwerfen", "يرمي"], ["wegbleiben", "يتغيب"]]],
  ["-ung", "SUF", "المصدر المؤنث", [["die Wohnung", "الشقة"], ["die Prüfung", "الامتحان"], ["die Zeitung", "الجريدة"]]],
  ["-heit", "SUF", "الصفة المؤنثة", [["die Krankheit", "المرض"], ["die Freiheit", "الحرية"]]],
  ["-keit", "SUF", "الصفة المؤنثة", [["die Möglichkeit", "الإمكانية"], ["die Schwierigkeit", "الصعوبة"]]],
  ["-schaft", "SUF", "المجموعة المؤنثة", [["die Freundschaft", "الصداقة"], ["die Mannschaft", "الفريق"]]],
  ["-tum", "SUF", "الحالة (مذكر/محايد)", [["das Eigentum", "الملكية"], ["der Reichtum", "الثراء"]]],
  ["-ling", "SUF", "الشخص (مذكر)", [["der Lehrling", "المتدرب"], ["der Liebling", "المفضل"]]],
  ["-chen", "SUF", "التصغير (محايد)", [["das Mädchen", "الفتاة"], ["das Brötchen", "الخبزة"]]],
  ["-lein", "SUF", "التصغير (محايد)", [["das Fräulein", "الآنسة"], ["das Büchlein", "الكتيب"]]],
  ["-isch", "SUF", "النسبة", [["deutsch", "ألماني"], ["touristisch", "سياحي"], ["praktisch", "عملي"]]],
  ["-lich", "SUF", "الصفة", [["freundlich", "ودود"], ["monatlich", "شهري"], ["pünktlich", "دقيق"]]],
  ["-ig", "SUF", "الصفة", [["fleißig", "مجتهد"], ["mutig", "شجاع"], ["hungrig", "جائع"]]],
  ["-bar", "SUF", "القابلية", [["lesbar", "مقروء"], ["machbar", "ممكن"], ["sichtbar", "مرئي"]]],
  ["-los", "SUF", "انعدام", [["arbeitslos", "عاطل"], ["hilflos", "عاجز"], ["kostenlos", "مجاني"]]],
  ["-voll", "SUF", "الامتلاء", [["sinnvoll", "مفيد"], ["erfolgreich", "ناجح"], ["wundervoll", "رائع"]]],
  ["-sam", "SUF", "الميل", [["langsam", "بطيء"], ["gemeinsam", "مشترك"], ["einsam", "وحيد"]]],
  ["un-", "PRE", "النفي", [["unmöglich", "مستحيل"], ["unglücklich", "غير سعيد"], ["unbekannt", "مجهول"]]],
  ["ur-", "PRE", "الأصل", [["uralt", "عتيق"], ["der Urlaub", "الإجازة"], ["die Ursache", "السبب"]]],
  ["erz-", "PRE", "الرتبة العليا", [["der Erzbischof", "رئيس الأساقفة"]]],
  ["miss-", "PRE", "الفشل", [["der Misserfolg", "الفشل"]]],
  ["nicht-", "PRE", "النفي الاسمي", [["der Nichtraucher", "غير المدخن"]]],
  ["-er", "SUF", "الفاعل", [["der Lehrer", "المعلم"], ["der Fahrer", "السائق"]]],
  ["-erin", "SUF", "المؤنث", [["die Lehrerin", "المعلمة"], ["die Fahrerin", "السائقة"]]],
  ["-erei", "SUF", "المكان/السلوك", [["die Bäckerei", "المخبز"], ["die Kinderei", "التصرف الطفولي"]]],
  ["-nis", "SUF", "النتيجة (مؤنث/محايد)", [["das Ergebnis", "النتيجة"], ["die Kenntnis", "المعرفة"]]],
  ["-sal", "SUF", "المحايد القديم", [["das Schicksal", "القدر"], ["das Labsal", "البلسم"]]],
  ["-tion", "SUF", "اللاتينية المؤنثة", [["die Information", "المعلومة"], ["die Nation", "الأمة"]]],
  ["-tät", "SUF", "اللاتينية المؤنثة", [["die Universität", "الجامعة"], ["die Qualität", "الجودة"]]],
  ["-anz", "SUF", "اللاتينية", [["die Toleranz", "التسامح"], ["die Distanz", "المسافة"]]],
  ["-enz", "SUF", "اللاتينية", [["die Existenz", "الوجود"], ["die Konferenz", "المؤتمر"]]],
  ["-ik", "SUF", "العلم المؤنث", [["die Musik", "الموسيقى"], ["die Klinik", "العيادة"]]],
  ["-ie", "SUF", "المؤنث", [["die Studie", "الدراسة"], ["die Garantie", "الضمان"]]],
  ["-age", "SUF", "الفرنسية", [["die Garage", "المرآب"], ["die Massage", "المساج"]]],
  ["-ette", "SUF", "التصغير الفرنسي", [["die Zigarette", "السيجارة"]]],
  ["-ine", "SUF", "المؤنث الحديث", [["die Polizistin", "الشرطية"]]],
  ["-eur", "SUF", "الفاعل الفرنسي", [["der Friseur", "الحلاق"], ["der Ingenieur", "المهندس"]]],
  ["Fugen-s", "FUG", "حرف الوصل s", [["der Arbeitsplatz", "مكان العمل"], ["das Urlaubsgeld", "نقود الإجازة"]]],
  ["Fugen-n", "FUG", "حرف الوصل n", [["die Blumenliebe", "حب الزهور"], ["der Gartenfreund", "صديق الحديقة"]]],
  ["Fugen-en", "FUG", "حرف الوصل en", [["der Menschenfreund", "محب البشر"], ["das Bettuch", "ملاءة السرير"]]],
  ["Fugen-e", "FUG", "حرف الوصل e", [["der Hundehalter", "صاحب الكلب"], ["das Pferderennen", "سباق الخيل"]]],
  ["Fugen-er", "FUG", "حرف الوصل er", [["der Kinderarzt", "طبيب الأطفال"], ["die Bücherwand", "مكتبة الكتب"]]],
  ["Fugen-∅", "FUG", "بلا وصل", [["der Haustürschlüssel", "مفتاح باب البيت"], ["das Bahnhofshuhn", "دجاجة المحطة"]]],
  ["Infinitiv→Nomen", "NOM", "المصدر اسمًا", [["das Lernen", "التعلم"], ["das Essen", "الطعام"]]],
  ["Adjektiv→Nomen", "NOM", "الصفة اسمًا", [["das Gute", "الخير"], ["der Kranke", "المريض"]]],
  ["Ge- -e Kollektiv", "NOM", "الجمع", [["das Gebirge", "الجبال"], ["das Gepäck", "الأمتعة"]]],
];

/* [nomen, verb, ar, exDe, exAr] Nomen-Verb-Verbindungen */
const NVV = [
  ["Angst", "haben", "يخاف", "Ich habe Angst vor Hunden.", "أخاف من الكلاب."],
  ["Lust", "haben", "يرغب", "Ich habe Lust auf Eis.", "أرغب في آيس كريم."],
  ["Hunger", "haben", "يجوع", "Ich habe Hunger.", "أنا جائع."],
  ["Durst", "haben", "يعطش", "Ich habe Durst.", "أنا عطشان."],
  ["Zeit", "haben", "يملك وقتًا", "Hast du Zeit?", "هل لديك وقت؟"],
  ["Glück", "haben", "محظوظ", "Du hast Glück gehabt.", "كنت محظوظًا."],
  ["Recht", "haben", "مُحق", "Du hast Recht.", "أنت محق."],
  ["Unrecht", "haben", "مخطئ", "Da hast du Unrecht.", "أنت مخطئ هنا."],
  ["Spaß", "machen", "يستمتع", "Das macht Spaß.", "هذا ممتع."],
  ["Schluss", "machen", "ينهي", "Mach Schluss damit!", "توقف عن ذلك!"],
  ["Platz", "machen", "يفسح", "Mach bitte Platz!", "افسح مكانًا من فضلك!"],
  ["Fotos", "machen", "يصور", "Er macht gern Fotos.", "يحب التصوير."],
  ["Sport", "machen", "يتدرب", "Ich mache zweimal pro Woche Sport.", "أتدرب مرتين أسبوعيًا."],
  ["Hausaufgaben", "machen", "يعمل الواجب", "Mach deine Hausaufgaben!", "اعمل واجبك!"],
  ["Platz", "nehmen", "يجلس", "Nehmen Sie bitte Platz!", "تفضل بالجلوس!"],
  ["Rücksicht", "nehmen", "يراعي", "Nimm bitte Rücksicht!", "راعِ من فضلك!"],
  ["Anteil", "nehmen", "يشارك", "Er nimmt regen Anteil.", "يشارك بحماس."],
  ["Abschied", "nehmen", "يودع", "Wir nehmen Abschied.", "نودع."],
  ["Stellung", "nehmen", "يبدي رأيه", "Nimm bitte Stellung dazu!", "أبدِ رأيك!"],
  ["Kenntnis", "nehmen", "يحيط علمًا", "Ich nehme es zur Kenntnis.", "أحيط علمًا."],
  ["Notiz", "nehmen", "يلاحظ", "Er nimmt keine Notiz davon.", "لا يلاحظ ذلك."],
  ["Bezug", "nehmen", "يشير إلى", "Ich nehme Bezug auf Ihr Schreiben.", "أشير إلى خطابكم."],
  ["Gebrauch", "machen", "يستخدم", "Mach bitte Gebrauch davon!", "استخدمه من فضلك!"],
  ["Anwendung", "finden", "يُطبق", "Die Regel findet Anwendung.", "تُطبق القاعدة."],
  ["Berücksichtigung", "finden", "يُؤخذ بعين الاعتبار", "Dein Vorschlag findet Berücksichtigung.", "يُؤخذ اقتراحك بعين الاعتبار."],
  ["in Kauf", "nehmen", "يتقبل", "Das nehme ich in Kauf.", "أتقبل ذلك."],
  ["zu Ende", "gehen", "ينتهي", "Der Film geht zu Ende.", "ينتهي الفيلم."],
  ["spazieren", "gehen", "يتنزه", "Wir gehen spazieren.", "نتنزه."],
  ["einkaufen", "gehen", "يتسوق", "Ich gehe einkaufen.", "أذهب للتسوق."],
  ["schlafen", "gehen", "ينام", "Die Kinder gehen schlafen.", "ينام الأطفال."],
  ["zur Schule", "gehen", "يذهب للمدرسة", "Er geht zur Schule.", "يذهب للمدرسة."],
  ["zur Arbeit", "gehen", "يذهب للعمل", "Sie geht zur Arbeit.", "تذهب للعمل."],
  ["in Rente", "gehen", "يتقاعد", "Er geht nächstes Jahr in Rente.", "يتقاعد العام القادم."],
  ["in Druck", "gehen", "يُطبع", "Das Buch geht nächste Woche in Druck.", "يُطبع الكتاب الأسبوع القادم."],
  ["verloren", "gehen", "يضيع", "Mein Schlüssel ist verloren gegangen.", "ضاع مفتاحي."],
  ["kaputt", "gehen", "يتعطل", "Mein Handy ist kaputt gegangen.", "تعطل هاتفي."],
  ["schief", "gehen", "يفشل", "Alles geht schief heute.", "كل شيء يفشل اليوم."],
  ["gut", "gehen", "بخير", "Es geht mir gut.", "أنا بخير."],
  ["zur Neige", "gehen", "ينفد", "Das Geld geht zur Neige.", "تنفد النقود."],
  ["in Erfüllung", "gehen", "يتحقق", "Mein Wunsch geht in Erfüllung.", "تتحقق أمنيتي."],
  ["zu Herzen", "nehmen", "يتأثر", "Nimm es dir nicht zu Herzen!", "لا تتأثر!"],
  ["sich", "Zeit nehmen", "يتمهل", "Nimm dir Zeit!", "خذ وقتك!"],
  ["sich", "Mühe geben", "يبذل جهدًا", "Gib dir bitte Mühe!", "ابذل جهدًا من فضلك!"],
  ["sich", "Sorgen machen", "يقلق", "Mach dir keine Sorgen!", "لا تقلق!"],
  ["sich", "Gedanken machen", "يفكر", "Mach dir darüber Gedanken!", "فكر في الأمر!"],
  ["sich", "Notizen machen", "يدون", "Mach dir Notizen!", "دون ملاحظات!"],
  ["sich", "ein Bild machen", "يكون فكرة", "Mach dir selbst ein Bild!", "كوّن فكرتك بنفسك!"],
  ["sich", "die Haare waschen", "يغسل شعره", "Ich wasche mir die Haare.", "أغسل شعري."],
  ["sich", "die Zähne putzen", "يفرش أسنانه", "Er putzt sich die Zähne.", "يفرش أسنانه."],
  ["sich", "die Hände waschen", "يغسل يديه", "Wasch dir die Hände!", "اغسل يديك!"],
  ["Kaffee", "kochen", "يعد قهوة", "Ich koche Kaffee.", "أعد قهوة."],
  ["Tee", "kochen", "يعد شايًا", "Sie kocht Tee.", "تعد شايًا."],
  ["Essen", "kochen", "يطبخ", "Mama kocht das Essen.", "تطبخ أمي الطعام."],
  ["Pause", "machen", "يستريح", "Wir machen eine Pause.", "نستريح قليلًا."],
  ["Urlaub", "machen", "يقضي إجازة", "Wir machen Urlaub in Spanien.", "نقضي الإجازة في إسبانيا."],
  ["Überstunden", "machen", "يعمل إضافيًا", "Er macht oft Überstunden.", "يعمل إضافيًا غالبًا."],
  ["Fortschritte", "machen", "يتقدم", "Du machst große Fortschritte.", "تحرز تقدمًا كبيرًا."],
  ["Erfahrungen", "machen", "يكتسب خبرة", "Er macht neue Erfahrungen.", "يكتسب خبرات جديدة."],
  ["einen Unterschied", "machen", "يُحدث فرقًا", "Das macht keinen Unterschied.", "لا فرق."],
  ["Sinn", "machen", "منطقي", "Das macht Sinn.", "هذا منطقي."],
];

/* [phrase, ar, exDe, exAr] Funktionsverbgefüge (B1/B2) */
const FVG = [
  ["in Kraft treten", "يدخل حيز التنفيذ", "Das Gesetz tritt morgen in Kraft.", "يدخل القانون حيز التنفيذ غدًا."],
  ["zur Verfügung stellen", "يوفر", "Wir stellen Ihnen das Auto zur Verfügung.", "نوفر لك السيارة."],
  ["zur Verfügung stehen", "متاح", "Ich stehe Ihnen zur Verfügung.", "أنا متاح لك."],
  ["in Frage kommen", "وارد", "Ein Umzug kommt nicht in Frage.", "الانتقال غير وارد."],
  ["in Betracht ziehen", "يأخذ بعين الاعتبار", "Wir ziehen alle Optionen in Betracht.", "نأخذ كل الخيارات بعين الاعتبار."],
  ["in Anspruch nehmen", "يستفيد من", "Er nimmt Hilfe in Anspruch.", "يستفيد من المساعدة."],
  ["in Angriff nehmen", "يشرع في", "Wir nehmen das Projekt in Angriff.", "نشرع في المشروع."],
  ["zum Abschluss bringen", "يُنهي", "Sie bringt das Studium zum Abschluss.", "تُنهي دراستها."],
  ["zum Ausdruck bringen", "يُعبر عن", "Er bringt seine Freude zum Ausdruck.", "يُعبر عن فرحته."],
  ["zur Sprache bringen", "يثير", "Er bringt das Problem zur Sprache.", "يثير المشكلة."],
  ["in Ordnung bringen", "يرتب", "Bring bitte dein Zimmer in Ordnung!", "رتب غرفتك من فضلك!"],
  ["in Erfahrung bringen", "يعرف", "Ich bringe die Preise in Erfahrung.", "أعرف الأسعار."],
  ["Verantwortung übernehmen", "يتحمل المسؤولية", "Er übernimmt die Verantwortung.", "يتحمل المسؤولية."],
  ["Rücksicht nehmen", "يراعي", "Nimm bitte Rücksicht auf die Nachbarn!", "راعِ الجيران من فضلك!"],
  ["Abschied nehmen", "يودع", "Wir nehmen Abschied von Oma.", "نودع الجدة."],
  ["Stellung nehmen", "يبدي رأيه", "Nimm bitte Stellung dazu!", "أبدِ رأيك!"],
  ["in Kauf nehmen", "يتقبل", "Die Verspätung nehme ich in Kauf.", "أتقبل التأخير."],
  ["Platz nehmen", "يجلس", "Bitte nehmen Sie Platz!", "تفضل بالجلوس!"],
  ["Anteil nehmen", "يشارك", "Er nimmt Anteil an unserem Schmerz.", "يشاركنا حزننا."],
  ["zur Kenntnis nehmen", "يحيط علمًا", "Ich nehme Ihr Schreiben zur Kenntnis.", "أحيط علمًا بخطابكم."],
  ["in Betrieb nehmen", "يُشغل", "Die Fabrik nimmt die Anlage in Betrieb.", "يُشغل المصنع الآلة."],
  ["außer Betrieb setzen", "يوقف", "Der Sturm setzt die Bahn außer Betrieb.", "توقف العاصفة القطار."],
  ["in Gang setzen", "يُشغل", "Er setzt die Maschine in Gang.", "يُشغل الآلة."],
  ["in Szene setzen", "يُخرج", "Sie setzt das Stück in Szene.", "تُخرج المسرحية."],
  ["unter Beweis stellen", "يُثبت", "Er stellt sein Können unter Beweis.", "يُثبت مهارته."],
  ["in Rechnung stellen", "يحاسب على", "Wir stellen Ihnen die Fahrt in Rechnung.", "نحاسبك على الرحلة."],
  ["zur Rede stellen", "يستجوب", "Er stellt ihn zur Rede.", "يستجوبه."],
  ["kaltstellen", "يُبعد", "Der Trainer stellt ihn kalt.", "يُبعده المدرب."],
  ["bloßstellen", "يُحرج", "Er stellt sie bloß.", "يُحرجها."],
  ["zurückstellen", "يؤجل", "Wir stellen das Projekt zurück.", "نؤجل المشروع."],
  ["fertigstellen", "يُنجز", "Er stellt den Bericht fertig.", "يُنجز التقرير."],
  ["sicherstellen", "يضمن", "Wir stellen die Qualität sicher.", "نضمن الجودة."],
  ["freistellen", "يُعفي", "Er stellt ihn vom Dienst frei.", "يُعفيه من الخدمة."],
  ["ausstellen", "يُصدر", "Sie stellt ein Visum aus.", "تُصدر تأشيرة."],
  ["anstellen", "يوظف", "Die Firma stellt Ingenieure an.", "توظف الشركة مهندسين."],
  ["einstellen", "يوقف/يوظف", "Er stellt das Rauchen ein.", "يتوقف عن التدخين."],
  ["vorstellen", "يتخيل/يقدم", "Stell dir das vor!", "تخيل ذلك!"],
  ["nachstellen", "يطارد", "Die Polizei stellt den Dieb.", "تطارد الشرطة اللص."],
  ["zur Schau stellen", "يعرض", "Er stellt seinen Reichtum zur Schau.", "يعرض ثراءه."],
  ["in Abrede stellen", "ينكر", "Er stellt alles in Abrede.", "ينكر كل شيء."],
];

/* [connector, arMeaning, exDe, exAr] B2 connectors */
const B2CONN = [
  ["indem", "بـ", "Indem er spart, reist er viel.", "بادخاره يسافر كثيرًا."],
  ["insofern", "بقدر", "Insofern du Recht hast, stimme ich zu.", "بقدر ما أنت محق أوافق."],
  ["insoweit", "بقدر", "Insoweit ist alles klar.", "بهذا القدر كل شيء واضح."],
  ["sofern", "شريطة", "Sofern du willst, komme ich mit.", "شريطة أن تريد آتي معك."],
  ["soweit", "بقدر", "Soweit ich weiß, ist er krank.", "على حد علمي هو مريض."],
  ["wenngleich", "رغم أن", "Wenngleich es regnet, gehen wir.", "رغم المطر نخرج."],
  ["obgleich", "رغم أن", "Obgleich er müde ist, hilft er.", "رغم تعبه يساعد."],
  ["obschon", "رغم أن", "Obschon sie krank ist, kommt sie.", "رغم مرضها تأتي."],
  ["trotzdem", "ومع ذلك", "Es regnet, trotzdem gehen wir.", "إنها تمطر ومع ذلك نخرج."],
  ["dennoch", "ومع ذلك", "Er ist krank, dennoch arbeitet er.", "هو مريض ومع ذلك يعمل."],
  ["daher", "لذلك", "Es regnet, daher bleiben wir.", "إنها تمطر لذلك نبقى."],
  ["folglich", "وبالتالي", "Er lernt viel, folglich besteht er.", "يدرس كثيرًا وبالتالي ينجح."],
  ["infolgedessen", "نتيجة لذلك", "Der Zug fällt aus, infolgedessen warten wir.", "أُلغي القطار ونتيجة لذلك ننتظر."],
  ["demzufolge", "وبناءً عليه", "Er ist krank, demzufolge fehlt er.", "هو مريض وبناءً عليه يغيب."],
  ["entsprechend", "وفقًا", "Entsprechend dem Plan starten wir.", "وفقًا للخطة نبدأ."],
  ["seitdem", "منذ", "Seitdem er hier wohnt, ist er glücklich.", "منذ سكنه هنا وهو سعيد."],
  ["währenddessen", "في هذه الأثناء", "Ich koche, währenddessen liest er.", "أطبخ وفي هذه الأثناء يقرأ."],
  ["wohingegen", "بينما", "Er spart, wohingegen sie ausgibt.", "هو يدخر بينما هي تنفق."],
  ["hingegen", "على العكس", "Ich bleibe, er hingegen geht.", "أبقى وهو على العكس يذهب."],
  ["dagegen", "ضد/بالمقابل", "Ich habe nichts dagegen.", "لا مانع لدي."],
  ["stattdessen", "بدلًا من ذلك", "Er bleibt nicht, stattdessen geht er.", "لا يبقى بل يذهب بدلًا من ذلك."],
  ["andererseits", "من جهة أخرى", "Einerseits ist es teuer, andererseits gut.", "من جهة غالٍ ومن أخرى جيد."],
  ["allerdings", "صحيح أن/لكن", "Das stimmt, allerdings nur teilweise.", "صحيح لكن جزئيًا فقط."],
  ["nämlich", "أي", "Er fehlt, er ist nämlich krank.", "يغيب أي أنه مريض."],
  ["also", "إذن", "Du bist müde, also schlaf!", "أنت متعب إذن نم!"],
];

/* [form, useAr, exDe, exAr] Konjunktiv I (indirekte Rede) */
const KONJ1 = [
  ["er sei", "نقل الكلام", "Er sagt, er sei krank.", "يقول إنه مريض."],
  ["er habe", "نقل الملكية", "Sie sagt, sie habe keine Zeit.", "تقول إنه ليس لديها وقت."],
  ["er könne", "نقل القدرة", "Er sagt, er könne kommen.", "يقول إنه يستطيع المجيء."],
  ["er müsse", "نقل الضرورة", "Sie sagt, sie müsse arbeiten.", "تقول إنه يجب أن تعمل."],
  ["er wolle", "نقل الإرادة", "Er sagt, er wolle bleiben.", "يقول إنه يريد البقاء."],
  ["sie seien", "نقل الجمع", "Sie sagen, sie seien müde.", "يقولون إنهم متعبون."],
  ["man nehme", "الوصفات", "Man nehme zwei Eier.", "نأخذ بيضتين."],
  ["es lebe", "الهتاف", "Es lebe der König!", "يحيا الملك!"],
  ["Gott segne", "الدعاء", "Gott segne dich!", "باركك الله!"],
  ["man beachte", "الملاحظة", "Man beachte die Regel.", "لاحظ القاعدة."],
  ["sei es", "التسليم", "Sei es wie es sei.", "ليكن ما يكن."],
  ["lange lebe", "التمني", "Lang lebe die Freundschaft!", "لتعش الصداقة!"],
];

/* [prep, arMeaning, exDe, exAr] genitive prepositions */
const GENPREP = [
  ["angesichts", "نظرًا لـ", "Angesichts der Lage bleiben wir.", "نظرًا للوضع نبقى."],
  ["anlässlich", "بمناسبة", "Anlässlich des Festes gibt es Rabatt.", "بمناسبة العيد يوجد خصم."],
  ["aufgrund", "بسبب", "Aufgrund des Wetters fällt es aus.", "بسبب الطقس يُلغى."],
  ["anhand", "استنادًا إلى", "Anhand des Beispiels lernt man.", "استنادًا للمثال نتعلم."],
  ["betreffs", "بخصوص", "Betreffs Ihrer Anfrage schreiben wir.", "بخصوص استفساركم نكتب."],
  ["hinsichtlich", "فيما يخص", "Hinsichtlich der Kosten fragen wir.", "فيما يخص التكاليف نسأل."],
  ["infolge", "نتيجة لـ", "Infolge des Sturms bleibt der Zug.", "نتيجة العاصفة يقف القطار."],
  ["mangels", "لعدم", "Mangels Beweisen spricht man frei.", "لعدم الأدلة يُبرأ."],
  ["seitens", "من جانب", "Seitens der Firma gibt es Lob.", "من جانب الشركة يوجد مديح."],
  ["unweit", "بالقرب من", "Unweit des Bahnhofs wohne ich.", "بالقرب من المحطة أسكن."],
  ["zwecks", "بغرض", "Zwecks Klärung rufen wir an.", "بغرض التوضيح نتصل."],
  ["zugunsten", "لصالح", "Zugunsten der Kinder spenden wir.", "لصالح الأطفال نتبرع."],
  ["zuungunsten", "ضد", "Zuungunsten des Angeklagten entscheidet man.", "يُقرر ضد المتهم."],
  ["diesseits", "على هذا الجانب", "Diesseits des Flusses wohnen wir.", "على هذا الجانب من النهر نسكن."],
  ["jenseits", "على الجانب الآخر", "Jenseits der Berge liegt Italien.", "خلف الجبال تقع إيطاليا."],
  ["beiderseits", "على الجانبين", "Beiderseits der Straße stehen Bäume.", "على جانبي الشارع أشجار."],
];

/* [adv, verbLink, arMeaning, exDe, exAr] pronominal adverbs */
const PRONOMADV = [
  ["darauf", "warten", "على ذلك", "Ich warte darauf.", "أنتظر ذلك."],
  ["damit", "arbeiten", "بذلك", "Ich arbeite damit.", "أعمل بذلك."],
  ["davon", "träumen", "بذلك", "Ich träume davon.", "أحلم بذلك."],
  ["dazu", "gehören", "إلى ذلك", "Das gehört dazu.", "هذا جزء منه."],
  ["darüber", "sprechen", "عن ذلك", "Wir sprechen darüber.", "نتحدث عن ذلك."],
  ["darunter", "leiden", "من ذلك", "Er leidet darunter.", "يعاني من ذلك."],
  ["davor", "Angst haben", "من ذلك", "Ich habe Angst davor.", "أخاف من ذلك."],
  ["dahinter", "kommen", "وراء ذلك", "Ich komme dahinter.", "أكتشف الأمر."],
  ["daneben", "liegen", "بجانب ذلك", "Er liegt daneben.", "هو مخطئ."],
  ["dazwischen", "kommen", "بين ذلك", "Es kommt etwas dazwischen.", "يحدث طارئ."],
  ["worauf", "warten", "على ماذا", "Worauf wartest du?", "ماذا تنتظر؟"],
  ["womit", "schreiben", "بماذا", "Womit schreibst du?", "بماذا تكتب؟"],
  ["wovon", "träumen", "بماذا", "Wovon träumst du?", "بماذا تحلم؟"],
  ["wozu", "brauchen", "لماذا", "Wozu brauchst du das?", "لم تحتاج هذا؟"],
  ["worüber", "lachen", "على ماذا", "Worüber lachst du?", "على ماذا تضحك؟"],
  ["worunter", "leiden", "مما", "Worunter leidest du?", "مما تعاني؟"],
  ["wovor", "Angst haben", "مما", "Wovor hast du Angst?", "مما تخاف؟"],
  ["woher", "kommen", "من أين", "Woher weißt du das?", "من أين تعرف ذلك؟"],
];

/* [word, arMeaning, exDe, exAr] adjectival numbers/quantifiers */
const ZAHLADJ = [
  ["erste", "الأول", "Der erste Mai ist frei.", "الأول من مايو عطلة."],
  ["zweite", "الثاني", "Nimm die zweite Straße!", "خذ الشارع الثاني!"],
  ["dritte", "الثالث", "Zum dritten Mal!", "للمرة الثالثة!"],
  ["letzte", "الأخير", "Letzte Woche war ich krank.", "الأسبوع الماضي مرضت."],
  ["nächste", "القادم", "Nächste Woche reisen wir.", "الأسبوع القادم نسافر."],
  ["alle", "كل", "Alle Kinder spielen.", "كل الأطفال يلعبون."],
  ["beide", "كلاهما", "Beide Filme sind gut.", "كلا الفيلمين جيد."],
  ["viele", "كثير", "Viele Leute kommen.", "يأتي كثير من الناس."],
  ["wenige", "قليل", "Wenige wissen das.", "قليلون يعرفون ذلك."],
  ["einige", "بعض", "Einige Gäste bleiben.", "بعض الضيوف يبقون."],
  ["mehrere", "عدة", "Mehrere Busse fallen aus.", "عدة حافلات تُلغى."],
  ["jede", "كل", "Jede Woche putze ich.", "كل أسبوع أنظف."],
];

/* [situation, pointAr, exDe, exAr] formal registers (Bewerbung/Telefon/E-Mail/Interview...) */
const FORMAL = [
  ["Bewerbung", "الموضوع", "Betreff: Bewerbung als Verkäufer", "الموضوع: التقديم كبائع."],
  ["Bewerbung", "التحية الرسمية", "Sehr geehrte Damen und Herren,", "سيداتي سادتي المحترمون،"],
  ["Bewerbung", "المقدمة", "Mit großem Interesse habe ich Ihre Anzeige gelesen.", "باهتمام كبير قرأت إعلانكم."],
  ["Bewerbung", "الخبرة", "Ich verfüge über drei Jahre Erfahrung.", "لدي ثلاث سنوات خبرة."],
  ["Bewerbung", "الختام", "Über eine Einladung freue ich mich.", "يسعدني دعوتكم."],
  ["Bewerbung", "التوقيع", "Mit freundlichen Grüßen, Ahmed", "مع أطيب التحيات، أحمد."],
  ["Bewerbung", "المرفقات", "Anlagen: Lebenslauf, Zeugnisse", "المرفقات: السيرة، الشهادات."],
  ["Telefon", "التعريف", "Hier spricht Ahmed.", "معك أحمد."],
  ["Telefon", "الطلب", "Könnte ich bitte mit Frau Müller sprechen?", "هل يمكنني التحدث مع السيدة مولر؟"],
  ["Telefon", "الانتظار", "Einen Moment bitte, ich verbinde.", "لحظة من فضلك، أحولك."],
  ["Telefon", "الرسالة", "Kann ich etwas ausrichten?", "هل أبلغ رسالة؟"],
  ["Telefon", "الوداع", "Danke für Ihren Anruf.", "شكرًا لاتصالكم."],
  ["E-Mail", "التحية", "Guten Tag Herr Schmidt,", "طاب يومك سيد شميدت،"],
  ["E-Mail", "السبب", "Ich schreibe Ihnen wegen meines Termins.", "أكتب لك بخصوص موعدي."],
  ["E-Mail", "الطلب", "Könnten Sie mir bitte antworten?", "هل يمكنك الرد من فضلك؟"],
  ["E-Mail", "الشكر", "Vielen Dank im Voraus.", "شكرًا مقدمًا."],
  ["E-Mail", "الختام", "Mit freundlichen Grüßen", "مع أطيب التحيات."],
  ["Interview", "الترحيب", "Nehmen Sie bitte Platz.", "تفضل بالجلوس."],
  ["Interview", "التعريف", "Erzählen Sie etwas über sich!", "حدثنا عن نفسك!"],
  ["Interview", "الخبرة", "Wo haben Sie zuletzt gearbeitet?", "أين عملت آخر مرة؟"],
  ["Interview", "الراتب", "Was stellen Sie sich vor?", "ماذا تتوقع؟"],
  ["Interview", "الختام", "Wir melden uns bei Ihnen.", "سنتصل بك."],
  ["Beschwerde", "الافتتاح", "Leider muss ich mich beschweren.", "للأسف يجب أن أشكو."],
  ["Beschwerde", "الوصف", "Das Zimmer war leider sehr laut.", "للأسف الغرفة مزعجة جدًا."],
  ["Beschwerde", "المطلب", "Ich bitte um Rückerstattung.", "أطلب استرداد المبلغ."],
  ["Beschwerde", "الختام", "Ich hoffe auf eine schnelle Lösung.", "آمل حلًا سريعًا."],
  ["Smalltalk", "الطقس", "Schönes Wetter heute, oder?", "جو جميل اليوم، أليس كذلك؟"],
  ["Smalltalk", "السؤال", "Was machen Sie beruflich?", "ما مهنتك؟"],
  ["Smalltalk", "الوداع", "Es war nett, Sie kennenzulernen!", "سعدت بلقائك!"],
  ["Behörde", "الموعد", "Ich habe einen Termin um zehn.", "لدي موعد العاشرة."],
  ["Behörde", "المستندات", "Bringen Sie bitte Ihren Pass mit.", "أحضر جوازك من فضلك."],
  ["Behörde", "الانتظار", "Nehmen Sie bitte im Wartezimmer Platz.", "انتظر في غرفة الانتظار."],
  ["Behörde", "الدفع", "Die Gebühr beträgt zehn Euro.", "الرسوم عشرة يورو."],
  ["Arzt", "الأعراض", "Seit wann haben Sie Schmerzen?", "منذ متى لديك ألم؟"],
  ["Arzt", "الوصفة", "Nehmen Sie bitte dreimal täglich eine Tablette.", "خذ قرصًا ثلاث مرات يوميًا."],
  ["Arzt", "المتابعة", "Kommen Sie in einer Woche wieder.", "تعال بعد أسبوع."],
  ["Restaurant", "الحجز", "Ich habe einen Tisch reserviert.", "حجزت طاولة."],
  ["Restaurant", "التوصية", "Was empfehlen Sie?", "بم تنصح؟"],
  ["Restaurant", "الحساب", "Die Rechnung, bitte.", "الفاتورة من فضلك."],
  ["Hotel", "الوصول", "Ich habe eine Reservierung.", "لدي حجز."],
  ["Hotel", "الفطور", "Wann gibt es Frühstück?", "متى الفطور؟"],
  ["Hotel", "المغادرة", "Bis wann muss ich auschecken?", "حتى متى يجب المغادرة؟"],
  ["Bank", "الحساب", "Ich möchte ein Konto eröffnen.", "أود فتح حساب."],
  ["Bank", "البطاقة", "Meine Karte funktioniert nicht.", "بطاقتي لا تعمل."],
  ["Bank", "التحويل", "Ich möchte Geld überweisen.", "أود تحويل نقود."],
  ["Schule", "الغياب", "Mein Sohn ist heute krank.", "ابني مريض اليوم."],
  ["Schule", "الاجتماع", "Wann ist der Elternabend?", "متى أمسية أولياء الأمور؟"],
  ["Schule", "الشهادة", "Wo bekomme ich das Zeugnis?", "أين آخذ الشهادة؟"],
  ["Arbeit", "المرضية", "Ich melde mich krank.", "أبلغ بمرضي."],
  ["Arbeit", "الإجازة", "Ich beantrage Urlaub vom 1. bis 10.", "أطلب إجازة من 1 حتى 10."],
];

module.exports = { WORDFORM, NVV, FVG, B2CONN, KONJ1, GENPREP, PRONOMADV, ZAHLADJ, FORMAL };
