/* Deutsch Master — BIG sentence patterns (fillGeneric-safe slots only).
   [deTpl, arTpl, lvl, topic, gram] — every gram code is new (no override collision),
   except codes implemented as overrides in build-sentences.js (marked OV).
   Transformation families: simple -> expanded -> connected -> subordinate.
*/
"use strict";
const BIGPATS = [
  // ---- full statements (A1) ----
  ["{S} {V} {O} {T} {P}.", "{Sa} {Va} {Oa} {Ta} {Pa}.", "A1", "dailylife", "praesens-voll"],
  ["{T} {V} {Sl} {P}.", "{Ta} {Va} {Sa} {Pa}.", "A1", "general", "inversion-ort"],
  ["{S} {V} {T} {O}.", "{Sa} {Va} {Ta} {Oa}.", "A1", "general", "te-ka-mo"],
  ["{P} {V} {Sl} {O}.", "{Pa} {Va} {Sa} {Oa}.", "A1", "general", "lokal-voran-3"],
  ["{S} {V} {O} {P}.", "{Sa} {Va} {Oa} {Pa}.", "A1", "general", "praesens-ort"],
  ["{S} {V} {O} und {O4}.", "{Sa} {Va} {Oa} و{O4a}.", "A1", "general", "reihung-obj"],
  ["{S} {V} {O} für {O8}.", "{Sa} {Va} {Oa} لـ{O8a}.", "A1", "relationships", "fuer-name"],
  ["{S} {V} {O} mit {O8}.", "{Sa} {Va} {Oa} مع {O8a}.", "A1", "relationships", "mit-name"],
  ["{S} {V} {O} ohne {O8}.", "{Sa} {Va} {Oa} بدون {O8a}.", "A2", "general", "ohne-name"],
  ["{S} {V} {O} {T} nicht.", "{Sa} لا {Va} {Oa} {Ta}.", "A1", "general", "negation-zeit"],
  ["{S} {V} {O} gern {T}.", "{Sa} {Va} {Oa} بسرور {Ta}.", "A1", "general", "gern-zeit"],
  ["{S} {V} {O}. Und {S2} {V2}.", "{Sa} {Va} {Oa}. و{S2a} {V2a}.", "A1", "general", "satzfolge"],
  ["{S} {V} {O}, und {S2} {V2} {T}.", "{Sa} {Va} {Oa}، و{S2a} {V2a} {Ta}.", "A2", "general", "satzreihe"],
  ["{S} {V} {O}. {S2} {V2} {T}.", "{Sa} {Va} {Oa}. {S2a} {V2a} {Ta}.", "A2", "general", "satzfolge-2"],
  ["{T} {V} {Sl} {O} nicht.", "{Ta} لا {Va} {Sa} {Oa}.", "A1", "general", "inversion-neg"],
  ["{S} {V} {T} {P}.", "{Sa} {Va} {Ta} {Pa}.", "A1", "routine", "praesens-kurz"],
  ["{S} {V} {O} {T}. {T} {V} {Sl} {P}.", "{Sa} {Va} {Oa} {Ta}. {Ta} {Va} {Sa} {Pa}.", "A2", "general", "satzpaar"],
  // ---- yes/no questions ----
  ["{Vq} {Sl} {T} {O}?", "هل {Va} {Sa} {Ta} {Oa}؟", "A1", "general", "ja-nein-voll"],
  ["{Vq} {Sl} {O} {P}?", "هل {Va} {Sa} {Oa} {Pa}؟", "A1", "general", "ja-nein-ort"],
  ["{Vq} {Sl} {T} {P}?", "هل {Va} {Sa} {Ta} {Pa}؟", "A1", "general", "ja-nein-kurz"],
  // ---- w-questions (fillGeneric-safe) ----
  ["Warum {V} {Sl} {O}?", "لماذا {Va} {Sa} {Oa}؟", "A1", "general", "warum-neu"],
  ["Warum {V} {Sl} {T} {P}?", "لماذا {Va} {Sa} {Ta} {Pa}؟", "A2", "general", "warum-voll"],
  ["Wann {V} {Sl} {O}?", "متى {Va} {Sa} {Oa}؟", "A1", "general", "wann-neu"],
  ["Wen {V} {Sl} {T}?", "من {Va} {Sa} {Ta}؟", "A2", "general", "wen-neu"],
  // ---- opinions + dass (B1) ----
  ["{S} glaubt, dass {S2} {V2}.", "{Sa} يعتقد أن {S2a} {V2a}.", "B1", "general", "glaubt-dass"],
  ["{S} hofft, dass {S2} {V2}.", "{Sa} يأمل أن {S2a} {V2a}.", "B1", "general", "hofft-dass"],
  ["{S} weiß, dass {S2} {V2}.", "{Sa} يعرف أن {S2a} {V2a}.", "B1", "general", "weiss-dass"],
  ["{S} denkt, dass {S2} {V2}.", "{Sa} يظن أن {S2a} {V2a}.", "B1", "general", "denkt-dass"],
  ["{S} sagt, dass {S2} {V2}.", "{Sa} يقول إن {S2a} {V2a}.", "B1", "general", "sagt-dass"],
  // ---- concession fronted (B1) ----
  ["Obwohl {S2} {V2}, {V} {Sl} {P}.", "رغم أن {S2a} {V2a}، {Sa} {Va} {Pa}.", "B1", "general", "obwohl-voran-neu"],
  ["Obwohl {S2} {V2}, {V} {Sl} {O}.", "رغم أن {S2a} {V2a}، {Sa} {Va} {Oa}.", "B1", "general", "obwohl-voran-neu-2"],
  // ---- fixed-core patterns (OV = override; template is placeholder) ----
  ["{S} wird {T} {O}.", "", "A2", "general", "futur-tr"],
  ["Wird {S} {T}?", "", "A2", "general", "futur-frage"],
  ["Wer {V} {O}?", "", "A2", "general", "wer-frage"],
  ["Wen {V} {Sl}?", "من {Va} {Sa}؟", "A2", "general", "wen-frage-2"],
  ["Wem gehört {O1}?", "لمن {O1a}؟", "A2", "general", "wem-frage"],
  ["Wie viel kostet {O1}?", "كم سعر {O1a}؟", "A1", "general", "wieviel-frage"],
  ["{S} findet {O} {A}.", "", "A2", "general", "findet-neu"],
  ["{S} macht {O} {A}.", "", "A2", "general", "macht-adj"],
  ["Bitte {V} {O}!", "", "A1", "general", "imperativ-neu"],
  ["Könnten Sie {V}?", "", "B1", "polite", "koennten-bitte"],
  ["Würden Sie {V}?", "", "B1", "polite", "wuerden-bitte"],
  ["Man {V} hier nicht.", "", "B1", "general", "man-satz"],
  ["Wie geht es {Sl}?", "كيف حال {Sa}؟", "A1", "general", "geht-es"],
  ["Wie schmeckt {O1}?", "كيف طعم {O1a}؟", "A1", "food", "schmeckt-neu"],
  ["Wie gefällt {O8} {O1}?", "هل يعجب {O8a} {O1a}؟", "A2", "general", "gefaellt-neu"],
  ["Was braucht man {P}?", "ماذا يحتاج المرء {Pa}؟", "A2", "general", "braucht-man"],
  ["Entschuldigung, wo ist {P}?", "", "A1", "general", "entschuldigung-wo"],
  ["Entschuldigung, wie viel kostet {O1}?", "عذرا، كم سعر {O1a}؟", "A1", "shopping", "entschuldigung-preis"],
  ["Sprechen Sie Deutsch?", "هل تتحدث الألمانية؟", "A1", "general", "sprechen-sie"],
  ["Ich lerne Deutsch, weil {S2} {V2}.", "أنا أتعلم الألمانية لأن {S2a} {V2a}.", "A1", "study", "ich-lerne-weil"],
  ["Es donnert {T}.", "إنها ترعد {Ta}.", "A2", "weather", "wetter-neu-3"],
  ["Es blitzt {T}.", "إنها تبرق {Ta}.", "A2", "weather", "wetter-neu-4"],
  ["Hast du {T} Zeit?", "هل لديك وقت {Ta}؟", "A1", "general", "hast-du-zeit"],
  ["Haben Sie {T} Zeit?", "هل لديكم وقت {Ta}؟", "A1", "polite", "haben-sie-zeit"],
  ["Es gibt {O} {P}.", "يوجد {Oa} {Pa}.", "A1", "general", "gibt-es-neu"],
  ["Gibt es {O} {P}?", "هل يوجد {Oa} {Pa}؟", "A1", "general", "gibt-es-frage"],
  ["Es gibt kein {On} {P}.", "لا يوجد أي {Ona} {Pa}.", "A1", "general", "gibt-es-kein"],
  ["Wie lange dauert {O1}?", "كم تستغرق {O1a}؟", "A2", "general", "dauert-neu"],
  ["{O1} dauert {T}.", "{O1a} تستغرق {Ta}.", "A2", "general", "reise-dauert"],
  ["Es riecht hier nach {On}.", "تفوح هنا رائحة {Ona}.", "A2", "general", "riecht-nach"],
  ["Passt {O8} {O1}?", "هل يناسب {O8a} {O1a}؟", "A2", "shopping", "passt-neu"],
  ["Was fehlt {O8}?", "ما الذي ينقص {O8a}؟", "A2", "general", "fehlt-neu"],
  ["Ich freue mich auf {O}!", "أنا متحمس لـ{Oa}!", "A2", "emotions", "freut-mich"],
  ["Wir freuen uns auf {O}!", "نحن متحمسون لـ{Oa}!", "A2", "emotions", "freut-uns"],
  ["Danke für {O}!", "شكرا على {Oa}!", "A1", "general", "danke-fuer-neu"],
  ["Vielen Dank für {O}!", "شكرا جزيلا على {Oa}!", "A1", "polite", "vielen-dank"],
  ["Viel Spaß {P}!", "استمتع {Pa}!", "A1", "general", "viel-spass"],
  ["Viel Glück {P}!", "بالتوفيق {Pa}!", "A1", "general", "viel-glueck"],
  ["Viel Erfolg {P}!", "بالتوفيق {Pa}!", "A1", "study", "viel-erfolg"],
  ["Gute Besserung, {O8}!", "بالشفاء العاجل يا {O8a}!", "A1", "health", "gute-besserung"],
  ["Alles Gute zum Geburtstag, {O8}!", "عيد ميلاد سعيد يا {O8a}!", "A1", "general", "alles-gute"],
  ["Herzlich willkommen {P}!", "أهلا بك {Pa}!", "A1", "general", "willkommen"],
  // ---- haben/sein/werden families ----
  ["{S} hat {T} {O}.", "لدى {Sa} {Ta} {Oa}.", "A1", "general", "haben-zeit"],
  ["{T} hat {Sl} {O}.", "{Ta} لدى {Sa} {Oa}.", "A1", "general", "haben-inversion"],
  ["{S} ist {T} {P}.", "{Sa} {Ta} {Pa}.", "A1", "general", "sein-ort-zeit"],
  ["Ist {Sl} {T} {P}?", "هل {Sa} {Ta} {Pa}؟", "A1", "general", "sein-frage"],
  ["{S} wird {T} {A}.", "{Sa} سيصبح {Ta} {Aa}.", "A2", "general", "werden-adj"],
  ["{S} bleibt {T} {P}.", "{Sa} {Va} {Ta} {Pa}.", "A2", "general", "bleiben-ort"],
  // ---- modal-flavored statements via fixed verbs ----
  ["{S} muss {T} {O}.", "", "A1", "general", "muss-voll"],
  ["{S} kann {T} {O}.", "", "A1", "general", "kann-voll"],
  ["{S} will {T} {O}.", "", "A1", "general", "will-voll"],
  ["{S} soll {T} {O}.", "", "A2", "general", "soll-voll"],
  ["{S} darf hier nicht {V}.", "", "A1", "general", "darf-hier"],
  ["{S} möchte {T} {O}.", "{Sa} يود {Ta} {Oa}.", "A1", "general", "moechte-voll"],
  // ---- past/future families ----
  ["{S} hat {T} {O} {V}.", "", "A2", "general", "perfekt-tr"],
  ["Was hat {S} {T} {V}?", "", "A2", "general", "perfekt-frage"],
  ["{S} ist {T} {P} {V}.", "", "A2", "general", "perfekt-sein"],
  ["{T} hat {S} {O} {V}.", "", "A2", "general", "perfekt-inv-neu"],
  // ---- comparisons/descriptions ----
  ["{S} findet {O} {A}.", "{Sa} يجد {Oa} {Aa}.", "A1", "general", "finden-einfach"],
  ["{S} macht {O8} {A}.", "{Sa} يجعل {O8a} {Aa}.", "A2", "emotions", "macht-name"],
  ["{S} nennt {O} {O8}.", "{Sa} يسمي {Oa} {O8a}.", "A2", "general", "nennt-name"],
  // ---- routines/habits ----
  ["{S} {V} {O} jeden Tag.", "{Sa} {Va} {Oa} كل يوم.", "A1", "routine", "routine-taeglich"],
  ["{S} {V} {T} {O} {P}.", "{Sa} {Va} {Ta} {Oa} {Pa}.", "A1", "routine", "routine-voll"],
  ["{S} {V} nie {O}.", "{Sa} لا {Va} {Oa} أبدا.", "A1", "routine", "routine-nie"],
  ["{S} {V} oft {O} {P}.", "{Sa} {Va} {Oa} غالبا {Pa}.", "A1", "routine", "routine-oft"],
  ["{S} {V} manchmal {O}.", "{Sa} {Va} {Oa} أحيانا.", "A1", "routine", "routine-manchmal"],
  // ---- plans/intentions ----
  ["{S} will {T} {O} {V}.", "", "A2", "general", "will-zukunft"],
  ["{S} möchte {T} {O} {V}.", "", "A2", "general", "moechte-zukunft"],
  ["{S} plant {T} {O}.", "{Sa} يخطط {Ta} {Oa}.", "A2", "general", "plant"],
  ["{S} hat {T} keine Zeit.", "ليس لدى {Sa} {Ta} وقت.", "A1", "general", "keine-zeit-t"],
  ["{S} hat {T} viel Zeit.", "لدى {Sa} {Ta} وقت كثير.", "A1", "general", "viel-zeit-t"],
  // ---- reasons/causes ----
  ["{S} {V} {O}, denn {S2} {V2}.", "{Sa} {Va} {Oa} لأن {S2a} {V2a}.", "A2", "general", "denn-neu"],
  ["{S} bleibt {T} zu Hause.", "{Sa} يبقى {Ta} في البيت.", "A1", "health", "bleibt-haus"],
  ["{S} ist krank.", "{Sa} مريض.", "A1", "health", "ist-krank"],
  ["{S2} ist krank.", "{S2a} مريض.", "A1", "health", "ist-krank-2"],
  // ---- formal/informal ----
  ["Bitte {V} {Sl} {O}.", "من فضلك {Va} {Sa} {Oa}.", "A2", "polite", "bitte-imperativ"],
  ["{S} grüßt {O8}.", "{Sa} يحيي {O8a}.", "A1", "relationships", "gruesst"],
  ["{S} dankt {O8}.", "{Sa} يشكر {O8a}.", "A1", "relationships", "dankt"],
  ["{S} gratuliert {O8}.", "{Sa} يهنئ {O8a}.", "A1", "relationships", "gratuliert"],
  ["{S} besucht {O8} {T}.", "{Sa} يزور {O8a} {Ta}.", "A1", "relationships", "besucht-name"],
  ["{S} ruft {O8} {T} an.", "{Sa} يتصل بـ{O8a} {Ta}.", "A1", "communication", "ruft-an"],
  ["{S} holt {O8} {P} ab.", "{Sa} يستقبل {O8a} {Pa}.", "A1", "general", "holt-ab"],
  ["{S} bringt {O8} {O}.", "{Sa} يحضر لـ{O8a} {Oa}.", "A2", "general", "bringt-name"],
  // ---- shopping/food/service ----
  ["{S} kauft {O} {P}.", "{Sa} يشتري {Oa} {Pa}.", "A1", "shopping", "kauft-ort"],
  ["{S} bestellt {O} {P}.", "{Sa} يطلب {Oa} {Pa}.", "A1", "restaurant", "bestellt-ort"],
  ["{S} kocht {O} {T}.", "{Sa} يطبخ {Oa} {Ta}.", "A1", "food", "kocht-zeit"],
  ["{S} trinkt {O} {P}.", "{Sa} يشرب {Oa} {Pa}.", "A1", "drinks", "trinkt-ort"],
  ["{S} isst {O} {T}.", "{Sa} يأكل {Oa} {Ta}.", "A1", "food", "isst-zeit"],
  ["{S} bezahlt {O} {T}.", "{Sa} يدفع {Oa} {Ta}.", "A1", "money", "bezahlt-zeit"],
  // ---- work/study ----
  ["{S} arbeitet {T} {P}.", "{Sa} يعمل {Ta} {Pa}.", "A1", "work", "arbeitet-ort"],
  ["{S} lernt {T} {O}.", "{Sa} يتعلم {Ta} {Oa}.", "A1", "study", "lernt-obj"],
  ["{S} schreibt {T} {O}.", "{Sa} يكتب {Ta} {Oa}.", "A1", "study", "schreibt-zeit"],
  ["{S} liest {T} {P}.", "{Sa} يقرأ {Ta} {Pa}.", "A1", "study", "liest-ort"],
  ["{S} übt {T} {O}.", "{Sa} يتدرب {Ta} على {Oa}.", "A2", "study", "uebt-obj"],
  ["{S} wiederholt {O} {T}.", "{Sa} يراجع {Oa} {Ta}.", "A2", "study", "wiederholt"],
  // ---- health/body ----
  ["{S} hat {T} {O}.", "لدى {Sa} {Ta} {Oa}.", "A1", "health", "haben-koerper"],
  ["{O1} tut {S} weh.", "{O1a} يؤلم {Sa}.", "A2", "health", "wehtut-neu"],
  ["{S} nimmt {O} {T}.", "{Sa} يأخذ {Oa} {Ta}.", "A2", "health", "nimmt-med"],
  ["{S} braucht {O}.", "{Sa} يحتاج {Oa}.", "A1", "health", "braucht-neu"],
  // ---- travel/transport ----
  ["{S} fährt {T} {P}.", "{Sa} يسافر {Ta} {Pa}.", "A1", "travel", "faehrt-ort"],
  ["{S} fliegt {T} {P}.", "{Sa} يطير {Ta} {Pa}.", "A2", "travel", "fliegt-ort"],
  ["{S} kommt {T} {P} an.", "{Sa} يصل {Ta} {Pa}.", "A1", "travel", "kommt-an"],
  ["{S} steigt {P} um.", "{Sa} يبدل {Pa}.", "A2", "transport", "steigt-um"],
  ["{S} bucht {O} {T}.", "{Sa} يحجز {Oa} {Ta}.", "A2", "travel", "bucht-zeit"],
  ["{S} reserviert {O} {P}.", "{Sa} يحجز {Oa} {Pa}.", "A2", "hotel", "reserviert-ort"],
  // ---- weather/nature ----
  ["Die Sonne scheint {T}.", "الشمس مشرقة {Ta}.", "A1", "weather", "sonne-scheint"],
  // ---- person-object verbs (valency-safe) ----
  ["{S} bleibt {T} zu Hause.", "{Sa} يبقى {Ta} في البيت.", "A1", "weather", "bleibt-haus-t"],
  ["{S} {V} {O8} {T}.", "", "A2", "relationships", "person-akk"],
  ["{S} {V} {O8} {P}.", "", "A2", "relationships", "person-akk"],
  ["{S} {V} {O8}.", "", "A2", "general", "person-akk"],
  ["{S} {V} {O8} {T} {P}.", "", "A2", "relationships", "person-akk"],
  ["{S} {V} {O8} nicht.", "", "A2", "general", "person-akk"],
  ["{S} {V} {O8} {T}?", "", "A2", "general", "person-akk"],
  // ---- B1: relative clauses, indirect questions, narrative past, formal ----
  ["Der {N} {V}.", "", "B1", "general", "relativ-subjekt"],
  ["Die {N} {V} {O}.", "", "B1", "general", "relativ-subjekt"],
  ["Das {N} {V} {T}.", "", "B1", "general", "relativ-subjekt"],
  ["Weißt du, wo {S} {V}?", "", "B1", "general", "indirekt-frage"],
  ["Sag mir, wann {S} {V}.", "", "B1", "general", "indirekt-frage"],
  ["Ich weiß nicht, wo {S} {V}.", "", "B1", "general", "indirekt-frage"],
  ["{S} {V} seit {T}.", "", "A2", "general", "seit-praesens"],
  ["{S} {V} seit {T} {P}.", "", "A2", "general", "seit-praesens"],
  ["{S} wollte {O}.", "", "B1", "general", "praet-modal"],
  ["{S} konnte {O} {T}.", "", "B1", "general", "praet-modal"],
  ["{S} kam {T} an.", "", "B1", "travel", "praet-ankommen"],
  ["{S} gab {O} {T}.", "", "B1", "general", "praet-geben"],
  ["{S} sah {O} {T}.", "", "B1", "general", "praet-sehen"],
  ["Könnten Sie {O}?", "", "B1", "polite", "formell-transitiv"],
  ["Könnten Sie {O} {T}?", "", "B1", "polite", "formell-transitiv"],
];

module.exports = { BIGPATS };
