/* Deutsch Master — BIG vocabulary fuel (deterministic, curated).
   Category-constrained productive compounding (German compounds inherit the HEAD's
   gender/plural, so generation is morphologically safe), derived prefix verbs,
   derived adjectives, premium phrases, collocation + prepositional extensions.
   Every row carries explicit Arabic (+English) — never invented by the engine.
   Consumed by tools/build-content-library.js (stage 1). All output passes the gate.
*/
"use strict";

/* MODGEN: modifier form (incl. Fugen-s/en/n) + genitive Arabic + English + head categories + cap.
   Arabic composes as "<headAr-stripped> <modAr>"; English as "<modEn> <headEn>". */
const MODGEN = [
  ["Schul", "المدرسة", "school", ["school", "education"], 120],
  ["Arbeits", "العمل", "work", ["work", "workplace", "rooms", "jobs"], 120],
  ["Haus", "المنزل", "house", ["home", "rooms", "clothing"], 110],
  ["Stadt", "المدينة", "city", ["city", "transport"], 100],
  ["Reise", "السفر", "travel", ["travel", "airport", "station", "transport", "hotel"], 100],
  ["Familien", "العائلة", "family", ["family"], 80],
  ["Kinder", "الأطفال", "children's", ["family", "home", "school"], 80],
  ["Büro", "المكتب", "office", ["work", "workplace", "documents"], 60],
  ["Berufs", "المهنة", "professional", ["jobs", "ausbildung"], 60],
  ["Betriebs", "الشركة", "company", ["work", "workplace"], 50],
  ["Kunden", "العملاء", "customer", ["services", "shopping"], 50],
  ["Kollegen", "الزملاء", "colleagues'", ["work"], 25],
  ["Wohn", "السكن", "living", ["home", "rooms"], 60],
  ["Schlaf", "النوم", "sleeping", ["home", "rooms", "furniture"], 40],
  ["Küchen", "المطبخ", "kitchen", ["food", "home"], 60],
  ["Bade", "الحمام", "bath", ["home", "rooms"], 30],
  ["Ess", "الطعام", "dining", ["rooms"], 40],
  ["Garten", "الحديقة", "garden", ["home", "nature", "hobbies"], 40],
  ["Nachbar", "الجيران", "neighbour", ["neighborhood"], 25],
  ["Haupt", "الرئيسي", "main", ["city", "station", "transport", "roads", "services"], 60],
  ["Urlaubs", "الإجازة", "holiday", ["travel", "hotel", "transport"], 50],
  ["Hotel", "الفندق", "hotel", ["hotel", "travel"], 30],
  ["Flughafen", "المطار", "airport", ["airport", "transport"], 25],
  ["Strand", "الشاطئ", "beach", ["travel", "hotel"], 25],
  ["Berg", "الجبل", "mountain", ["nature"], 25],
  ["Meer", "البحر", "sea", ["nature", "travel"], 20],
  ["Fluss", "النهر", "river", ["nature", "city"], 15],
  ["Wald", "الغابة", "forest", ["nature"], 20],
  ["Blumen", "الزهور", "flower", ["home", "shopping"], 20],
  ["Wochen", "الأسبوع", "week", ["time", "routine"], 40],
  ["Jahres", "السنة", "year", ["time"], 40],
  ["Tages", "اليوم", "day", ["time", "routine"], 40],
  ["Abend", "المساء", "evening", ["time", "routine"], 40],
  ["Morgen", "الصباح", "morning", ["time", "routine"], 40],
  ["Nacht", "الليل", "night", ["time", "transport"], 30],
  ["Sommer", "الصيف", "summer", ["clothing", "travel", "sports"], 60],
  ["Winter", "الشتاء", "winter", ["clothing", "sports", "travel"], 60],
  ["Wetter", "الطقس", "weather", ["weather", "nature"], 30],
  ["Regen", "المطر", "rain", ["weather", "clothing"], 30],
  ["Schnee", "الثلج", "snow", ["weather", "seasons", "sports"], 25],
  ["Sport", "الرياضة", "sports", ["sports", "hobbies", "clothing", "shopping"], 50],
  ["Fußball", "كرة القدم", "football", ["sports", "hobbies"], 30],
  ["Tennis", "التنس", "tennis", ["sports"], 20],
  ["Schwimm", "السباحة", "swimming", ["sports", "health"], 25],
  ["Fitness", "اللياقة", "fitness", ["sports", "health"], 25],
  ["Musik", "الموسيقى", "music", ["hobbies", "school"], 30],
  ["Film", "الفيلم", "film", ["hobbies"], 25],
  ["Buch", "الكتاب", "book", ["education"], 30],
  ["Spiel", "اللعب", "game", ["hobbies", "sports", "family"], 30],
  ["Woll", "الصوف", "wool", ["clothing"], 20],
  ["Leder", "الجلد", "leather", ["clothing", "shopping"], 20],
  ["Patienten", "المرضى", "patient", ["health", "doctor", "hospital", "pharmacy"], 50],
  ["Arzt", "الطبيب", "doctor's", ["health", "doctor", "appointments"], 50],
  ["Krankenhaus", "المستشفى", "hospital", ["health", "hospital", "doctor"], 30],
  ["Apotheken", "الصيدلية", "pharmacy", ["health", "pharmacy"], 25],
  ["Not", "الطوارئ", "emergency", ["emergency", "health", "hospital", "doctor"], 30],
  ["Kranken", "المرض", "sickness", ["health", "doctor"], 40],
  ["Computer", "الحاسوب", "computer", ["computers", "tech", "work"], 40],
  ["Internet", "الإنترنت", "internet", ["internet", "computers", "communication"], 30],
  ["Handy", "الهاتف", "mobile", ["phones", "communication"], 30],
  ["Telefon", "الهاتف", "telephone", ["phones", "communication", "work"], 40],
  ["Fernseh", "التلفاز", "TV", ["general", "communication"], 20],
  ["Radio", "الراديو", "radio", ["general", "communication"], 15],
  ["E-Mail", "البريد الإلكتروني", "email", ["internet", "communication", "work"], 25],
  ["Geld", "النقود", "money", ["money", "banking"], 50],
  ["Bank", "البنك", "bank", ["banking", "money"], 40],
  ["Konto", "الحساب", "account", ["banking", "money"], 25],
  ["Kredit", "الائتمان", "credit", ["banking", "money"], 20],
  ["Steuer", "الضريبة", "tax", ["money", "documents", "work"], 25],
  ["Versicherungs", "التأمين", "insurance", ["services", "documents", "health"], 25],
  ["Termin", "الموعد", "appointment", ["appointments", "doctor", "services"], 40],
  ["Antrags", "الطلب", "application", ["documents", "applications", "services"], 25],
  ["Bewerbungs", "التقديم", "job-application", ["applications", "interviews"], 25],
  ["Prüfungs", "الامتحان", "exam", ["education", "study", "ausbildung", "university"], 40],
  ["Ausbildungs", "التدريب المهني", "training", ["ausbildung", "work", "jobs"], 40],
  ["Studien", "الدراسة", "study", ["university"], 40],
  ["Vorlesungs", "المحاضرة", "lecture", ["university", "study"], 25],
  ["Hunde", "الكلاب", "dog", ["home", "food"], 20],
  ["Katzen", "القطط", "cat", ["home", "food"], 20],
  ["Vogel", "الطيور", "bird", ["home", "nature"], 20],
  ["Frauen", "النساء", "women's", ["people"], 30],
  ["Männer", "الرجال", "men's", ["people", "clothing"], 25],
  ["Baby", "الرضيع", "baby", ["family", "health"], 20],
  ["Senioren", "كبار السن", "senior", ["people", "health", "services"], 20],
  ["Freundes", "الأصدقاء", "friends'", ["relationships", "people", "communication"], 25],
  ["Hochzeits", "الزفاف", "wedding", ["relationships", "family"], 25],
  ["Geburts", "الميلاد", "birth", ["family", "documents", "city"], 20],
  ["Verkehrs", "المرور", "traffic", ["roads", "transport", "city"], 40],
  ["Auto", "السيارة", "car", ["transport", "roads", "travel", "jobs"], 50],
  ["Fahrrad", "الدراجة", "bike", ["transport", "sports", "city"], 40],
  ["Zug", "القطار", "train", ["station", "transport", "travel"], 30],
  ["Bus", "الحافلة", "bus", ["transport", "station"], 25],
  ["Park", "المنتزه", "park", ["city", "nature"], 25],
  ["Dankes", "الشكر", "thanks", ["general", "communication"], 15],
  ["Glückwunsch", "التهنئة", "congratulation", ["general", "relationships"], 10],
  ["Pass", "الجواز", "passport", ["documents", "airport", "travel"], 20],
  ["Holz", "الخشب", "wooden", ["furniture", "rooms"], 40],
  ["Glas", "الزجاج", "glass", ["home", "food", "drinks"], 35],
  ["Stein", "الحجر", "stone", ["home", "nature", "city"], 30],
  ["Papier", "الورق", "paper", ["school", "work", "documents"], 30],
  ["Stoff", "القماش", "fabric", ["clothing", "home"], 25],
  ["Seiden", "الحرير", "silk", ["clothing"], 15],
  ["Baumwoll", "القطن", "cotton", ["clothing"], 20],
  ["Dorf", "القرية", "village", ["city", "nature", "travel"], 30],
  ["Zentrum", "المركز", "center", ["city", "services"], 30],
  ["Markt", "السوق", "market", ["city", "shopping"], 35],
  ["Hafen", "الميناء", "harbour", ["city", "travel"], 20],
  ["Konzert", "الحفل", "concert", ["hobbies", "city"], 20],
  ["Theater", "المسرح", "theatre", ["hobbies", "city"], 20],
  ["Museum", "المتحف", "museum", ["city", "study", "travel"], 20],
  ["Bibliothek", "المكتبة", "library", ["study", "school", "university"], 20],
];

/* MODHEADS: food modifiers with CURATED head allowlists (high precision).
   [mod, modAr(genitive), modEn, [headDe...]] — Arabic composes as "<headAr> <modAr>". */
const MODHEADS = [
  ["Apfel", "التفاح", "apple", ["Kuchen", "Saft", "Mus", "Tee", "Wein"]],
  ["Orangen", "البرتقال", "orange", ["Saft", "Marmelade"]],
  ["Zitronen", "الليمون", "lemon", ["Saft", "Tee"]],
  ["Erdbeer", "الفراولة", "strawberry", ["Kuchen", "Marmelade", "Joghurt"]],
  ["Kartoffel", "البطاطا", "potato", ["Salat", "Suppe", "Püree"]],
  ["Tomaten", "الطماطم", "tomato", ["Suppe", "Soße", "Mark"]],
  ["Zwiebel", "البصل", "onion", ["Kuchen", "Suppe"]],
  ["Hähnchen", "الدجاج", "chicken", ["Brust", "Suppe", "Keule", "Flügel"]],
  ["Rind", "البقر", "beef", ["Fleisch", "Suppe"]],
  ["Schweine", "الخنزير", "pork", ["Braten", "Fleisch"]],
  ["Lachs", "السلمون", "salmon", ["Filet", "Brötchen"]],
  ["Honig", "العسل", "honey", ["Kuchen", "Milch", "Senf"]],
  ["Butter", "الزبدة", "butter", ["Brot", "Kuchen", "Milch"]],
  ["Eier", "البيض", "egg", ["Kuchen", "Becher", "Likör"]],
  ["Reis", "الأرز", "rice", ["Pfanne", "Auflauf"]],
  ["Nudel", "المعكرونة", "pasta", ["Auflauf", "Salat", "Suppe"]],
  ["Milch", "الحليب", "milk", ["Reis", "Kaffee", "Brei"]],
  ["Kaffee", "القهوة", "coffee", ["Tasse", "Maschine", "Pause", "Milch"]],
  ["Brot", "الخبز", "bread", ["Dose", "Korb", "Messer", "Aufstrich"]],
  ["Fleisch", "اللحم", "meat", ["Wurst", "Spieß", "Brühe"]],
  ["Hack", "المفروم", "minced", ["Fleisch"]],
  ["Fisch", "السمك", "fish", ["Filet", "Suppe", "Stäbchen"]],
  ["Gemüse", "الخضار", "vegetable", ["Suppe", "Pfanne", "Brühe", "Auflauf"]],
  ["Obst", "الفاكهة", "fruit", ["Kuchen", "Salat", "Korb"]],
  ["Schoko", "الشوكولاتة", "chocolate", ["Kuchen", "Milch", "Eis", "Pudding", "Müsli"]],
  ["Käse", "الجبن", "cheese", ["Kuchen", "Brot", "Spätzle", "Fondue"]],
  ["Kuchen", "الكعكة", "cake", ["Blech", "Form"]],
  ["Salz", "الملح", "salt", ["Stange", "Gurke"]],
];

/* QMOD: qualifier prefixes applied to BASE nouns only (safe, highly productive):
   Großstadt, Kleinstadt, Neustadt, Altstadt, Hauptstraße, Nebenstraße ... */
const QMOD = [
  ["Groß", "الكبير", "big", ["city", "family", "home", "rooms"], 60],
  ["Klein", "الصغير", "small", ["city", "family", "home", "rooms"], 60],
  ["Neu", "الجديد", "new", ["city", "home"], 50],
  ["Alt", "القديم", "old", ["city", "home"], 40],
  ["Ober", "العلوي", "upper", ["city", "home"], 30],
  ["Unter", "السفلي", "lower", ["city", "home"], 30],
  ["Neben", "الجانبي", "side", ["city", "home", "rooms", "roads"], 40],
  ["Hinter", "الخلفي", "back", ["city", "home"], 30],
  ["Vorder", "الأمامي", "front", ["city", "home"], 25],
  ["Bio", "العضوي", "organic", ["food", "drinks"], 40],
  ["Öko", "البيئي", "eco", ["food", "home"], 25],
  ["Super", "الممتاز", "super", ["supermarket", "food", "general"], 20],
  ["Mini", "الصغير", "mini", ["food", "general", "phones", "computers"], 20],
];

/* BIGCOMP: explicit high-frequency compounds [head, "mod:ar:en,..."] — same format as COMP. */
const BIGCOMP = [
  ["Bahnhof", "Haupt:المحطة الرئيسية:main station,Bus:محطة الحافلات:bus station"],
  ["Straße", "Haupt:الشارع الرئيسي:main street,Neben:الشارع الجانبي:side street,Seiten:الشارع الجانبي:side street"],
  ["Stadt", "Groß:المدينة الكبيرة:big city,Klein:المدينة الصغيرة:small town,Neu:المدينة الجديدة:new town,Alt:المدينة القديمة:old town,Hafen:مدينة الميناء:port city,Universitäts:المدينة الجامعية:university town"],
  ["Platz", "Markt:الساحة السوق:market square,Bahnhofs:ساحة المحطة:station square,Park:موقف السيارات:parking lot,Spiel:ملعب الأطفال:playground"],
  ["Brücke", "Autobahn:جسر الطريق السريع:motorway bridge,Eisenbahn:جسر السكة الحديد:railway bridge,Fußgänger:جسر المشاة:footbridge"],
  ["Ampel", "Fußgänger:إشارة المشاة:pedestrian light"],
  ["Haltestelle", "Bus:موقف الحافلات:bus stop,Straßenbahn:موقف الترام:tram stop"],
  ["Fahrkarte", "Tages:تذكرة يومية:day ticket,Wochen:تذكرة أسبوعية:weekly ticket,Monats:تذكرة شهرية:monthly ticket,Gruppen:تذكرة جماعية:group ticket,Hin:تذكرة ذهاب:single outward ticket,Rück:تذكرة عودة:return ticket"],
  ["Flug", "Hin:رحلة الذهاب:outward flight,Rück:رحلة العودة:return flight,Nonstop:رحلة مباشرة:nonstop flight,Charter:رحلة مستأجرة:charter flight"],
  ["Gepäck", "Hand:حقيبة اليد:hand luggage,Reise:أمتعة السفر:travel luggage,Über:الأمتعة الزائدة:excess baggage"],
  ["Zimmer", "Hotel:غرفة الفندق:hotel room,Doppel:غرفة مزدوجة:double room,Einzel:غرفة مفردة:single room,Kinder:غرفة الأطفال:children's room,Arbeits:غرفة العمل:study room,Wohn:غرفة المعيشة:living room,Schlaf:غرفة النوم:bedroom,Bade:الحمام:bathroom"],
  ["Schlüssel", "Haus:مفتاح البيت:house key,Auto:مفتاح السيارة:car key,Zimmer:مفتاح الغرفة:room key,Ersatz:المفتاح الاحتياطي:spare key"],
  ["Tür", "Haus:باب البيت:front door,Zimmer:باب الغرفة:room door,Auto:باب السيارة:car door,Schiebe:الباب المنزلق:sliding door"],
  ["Fenster", "Küchen:نافذة المطبخ:kitchen window,Auto:نافذة السيارة:car window,Dach:النافذة السقفية:skylight"],
  ["Tisch", "Ess:طاولة الطعام:dining table,Schreib:مكتب الكتابة:writing desk,Küchen:طاولة المطبخ:kitchen table,Nachtt:طاولة الليل:bedside table"],
  ["Stuhl", "Büro:كرسي المكتب:office chair,Küchen:كرسي المطبخ:kitchen chair,Schauckel:الكرسي الهزاز:rocking chair"],
  ["Bett", "Doppel:السرير المزدوج:double bed,Etagen:السرير بطابقين:bunk bed,Kinder:سرير الأطفال:children's bed,Gäste:سرير الضيوف:guest bed"],
  ["Schrank", "Kleider:خزانة الملابس:wardrobe,Bücher:خزانة الكتب:bookcase,Küchen:خزانة المطبخ:kitchen cupboard"],
  ["Lampe", "Tisch:مصباح الطاولة:table lamp,Steh:المصباح الأرضي:floor lamp,Nacht:المصباح الليلي:night lamp"],
  ["Tasche", "Hand:حقيبة اليد:handbag,Reise:حقيبة السفر:travel bag,Sport:حقيبة الرياضة:sports bag,Einkaufs:كيس التسوق:shopping bag"],
  ["Geld", "Taschen:مصروف الجيب:pocket money,Urlaubs:نقود الإجازة:holiday money,Trink:الإكرامية:tip"],
  ["Konto", "Giro:الحساب الجاري:current account,Spar:حساب التوفير:savings account,Geschäfts:حساب الأعمال:business account"],
  ["Karte", "Bank:البطاقة البنكية:bank card,Kredit:بطاقة الائتمان:credit card,Versicherungs:بطاقة التأمين:insurance card,Glückwunsch:بطاقة التهنئة:greeting card,Post:البطاقة البريدية:postcard,Menü:قائمة الطعام:menu"],
  ["Rechnung", "Telefon:فاتورة الهاتف:phone bill,Strom:فاتورة الكهرباء:electricity bill,Arzt:فاتورة الطبيب:doctor's bill"],
  ["Termin", "Arzt:موعد الطبيب:doctor's appointment,Frisör:موعد الحلاق:hair appointment,Vorstellungs:موعد المقابلة:interview appointment"],
  ["Buch", "Schul:الكتاب المدرسي:school book,Koch:كتاب الطبخ:cookbook,Wörter:القاموس:dictionary,Telefon:دليل الهاتف:phone book,Notiz:دفتر الملاحظات:notebook,Märchen:كتاب الحكايات:storybook"],
  ["Heft", "Schul:الدفتر المدرسي:school exercise book,Vokabel:دفتر المفردات:vocabulary book"],
  ["Stift", "Bunt:القلم الملون:coloured pencil,Kugel:القلم الجاف:ballpoint pen,Filz:قلم اللباد:felt pen"],
  ["Papier", "Brief:ورق الرسائل:letter paper,Toiletten:ورق الحمام:toilet paper,Geschenk:ورق الهدايا:wrapping paper"],
  ["Lehrer", "Deutsch:مدرس الألمانية:German teacher,Musik:مدرس الموسيقى:music teacher,Sport:مدرس الرياضة:sports teacher,Klassen:مدرس الصف:class teacher"],
  ["Schüler", "Grundschul:تلميذ الابتدائية:primary pupil,Gymnasial:طالب الثانوية:grammar school pupil,Austausch:طالب التبادل:exchange student"],
  ["Prüfung", "Deutsch:امتحان الألمانية:German exam,Führerschein:امتحان القيادة:driving test,Abschluss:الامتحان النهائي:final exam,Nach:الامتحان التكميلي:retake exam"],
  ["Arbeit", "Haus:الواجب المنزلي:homework,Klassen:العمل الصفي:class test,Teilzeit:العمل بدوام جزئي:part-time work,Vollzeit:العمل بدوام كامل:full-time work,Nacht:العمل الليلي:night work,Team:العمل الجماعي:teamwork"],
  ["Kollege", "Arbeits:زميل العمل:work colleague,Büro:زميل المكتب:office colleague,Zimmer:زميل الغرفة:roommate"],
  ["Chef", "Abteilungs:رئيس القسم:department head,Firmen:مدير الشركة:company boss,Küchen:رئيس المطبخ:head chef"],
  ["Firma", "Familien:الشركة العائلية:family business,Tochter:الشركة التابعة:subsidiary,Reise:وكالة السفر:travel agency"],
  ["Bewerbung", "Job:طلب التوظيف:job application,Stellen:طلب الوظيفة:job application,Initiativ:الطلب العفوي:speculative application"],
  ["Gespräch", "Vorstellungs:مقابلة التقديم:job interview,Telefon:المكالمة الهاتفية:phone call"],
  ["Rechnung", "Handy:فاتورة الهاتف:mobile bill"],
  ["Urlaub", "Sommer:الإجازة الصيفية:summer holiday,Elternzeit:إجازة الوالدين:parental leave"],
  ["Feiertag", "Weihnachts:عيد الميلاد:Christmas holiday,Oster:عيد الفصح:Easter holiday"],
  ["Wetter", "Regen:طقس ممطر:rainy weather,Schnee:طقس مثلج:snowy weather,Herbst:طقس الخريف:autumn weather"],
  ["Kleidung", "Arbeits:ملابس العمل:work clothes,Sport:الملابس الرياضية:sportswear,Winter:ملابس الشتاء:winter clothes,Schutz:الملابس الواقية:protective clothing"],
  ["Schuh", "Sport:الحذاء الرياضي:sports shoe,Wander:حذاء المشي:hiking boot,Hauss:النعال المنزلية:house shoe"],
  ["Mantel", "Winter:المعطف الشتوي:winter coat,Regen:معطف المطر:raincoat"],
  ["Jacke", "Jeans:الجاكيت الجينز:denim jacket,Leder:الجاكيت الجلد:leather jacket,Daunen:جاكيت الريش:down jacket"],
  ["Hose", "Jeans:بنطال الجينز:jeans,Anzugs:بنطال البدلة:suit trousers,Sport:البنطال الرياضي:sports trousers"],
  ["Hemd", "Ober:القميص العلوي:shirt,Flanell:قميص الفلانيل:flannel shirt"],
  ["Mahlzeit", "Mittags:وجبة الغداء:lunch meal,Abend:وجبة العشاء:dinner meal"],
  ["Frühstück", "Hotel:فطور الفندق:hotel breakfast,Sonntags:فطور الأحد:Sunday breakfast"],
  ["Abendessen", "Familien:عشاء العائلة:family dinner,Weihnachts:عشاء عيد الميلاد:Christmas dinner"],
  ["Getränk", "Heiß:المشروب الساخن:hot drink,Erfrischungs:المشروب المنعش:refreshing drink"],
  ["Kaffee", "Morgen:قهوة الصباح:morning coffee,Filter:القهوة المقطرة:filter coffee,Milch:القهوة بالحليب:milky coffee"],
  ["Tee", "Kräuter:شاي الأعشاب:herbal tea,Früchte:شاي الفواكه:fruit tea,Schwarz:الشاي الأسود:black tea"],
  ["Saft", "Apfel:عصير التفاح:apple juice,Orangen:عصير البرتقال:orange juice,Multi:العصير المشكل:mixed juice"],
  ["Brot", "Vollkorn:خبز الحبوب الكاملة:wholegrain bread,Weiß:الخبز الأبيض:white bread,Roggen:خبز الجاودار:rye bread,Toast:خبز التوست:toast bread"],
  ["Käse", "Berg:جبن الجبل:mountain cheese,Frisch:الجبن الطازج:fresh cheese,Schafs:جبن الغنم:sheep cheese"],
  ["Fleisch", "Rind:لحم البقر:beef,Schwein:لحم الخنزير:pork,Hähnchen:لحم الدجاج:chicken meat,Hack:اللحم المفروم:minced meat"],
  ["Fisch", "Lachs:سمك السلمون:salmon,Thun:سمك التونة:tuna,Forellen:سمك السلمون المرقط:trout"],
  ["Gemüse", "Frisch:الخضار الطازجة:fresh vegetables,Tiefkühl:الخضار المجمدة:frozen vegetables,Bio:الخضار العضوية:organic vegetables"],
  ["Obst", "Frisch:الفاكهة الطازجة:fresh fruit,Trocken:الفاكهة المجففة:dried fruit,Zitrus:الحمضيات:citrus fruit"],
  ["Arzt", "Haus:طبيب العائلة:family doctor,Zahn:طبيب الأسنان:dentist,Kinder:طبيب الأطفال:pediatrician,Haut:طبيب الجلد:dermatologist,Augen:طبيب العيون:eye doctor,Frauen:طبيبة النساء:gynecologist"],
  ["Krankenhaus", "Universitäts:المستشفى الجامعي:university hospital,Kinder:مستشفى الأطفال:children's hospital"],
  ["Apotheke", "Not:صيدلية الطوارئ:emergency pharmacy,Online:الصيدلية الإلكترونية:online pharmacy"],
  ["Rezept", "Kassen:وصفة التأمين الصحي:insurance prescription,Privat:الوصفة الخاصة:private prescription,Folge:الوصفة المتابعة:repeat prescription"],
  ["Schmerz", "Kopf:ألم الرأس:headache,Zahn:ألم الأسنان:toothache,Rücken:ألم الظهر:back pain,Bauch:ألم البطن:stomach ache"],
  ["Fieber", "Grippe:حمى الإنفلونزا:flu fever"],
  ["Krankheit", "Kinder:مرض الأطفال:childhood illness,Herz:مرض القلب:heart disease,Haut:مرض الجلد:skin disease"],
  ["Versicherung", "Kranken:التأمين الصحي:health insurance,Auto:تأمين السيارة:car insurance,Hausrat:تأمين محتويات المنزل:household insurance,Lebens:التأمين على الحياة:life insurance"],
  ["Steuer", "Einkommens:ضريبة الدخل:income tax,Mehrwert:ضريبة القيمة المضافة:VAT,Kraftfahrzeug:ضريبة السيارة:vehicle tax"],
  ["Brief", "Bewerbungs:خطاب التقديم:application letter,Liebes:رسالة الحب:love letter,Beschwerde:خطاب الشكوى:complaint letter,Kündigungs:خطاب الاستقالة:resignation letter"],
  ["E-Mail", "Bewerbungs:إيميل التقديم:application email,Geschäfts:إيميل العمل:business email,Bestätigungs:إيميل التأكيد:confirmation email"],
  ["Anruf", "Not:مكالمة الطوارئ:emergency call,Weck:مكالمة الإيقاظ:wake-up call"],
  ["Nachricht", "Sprach:الرسالة الصوتية:voice message,Text:الرسالة النصية:text message,Fehler:رسالة الخطأ:error message"],
  ["Computer", "Büro:حاسوب المكتب:office computer,Spiele:حاسوب الألعاب:gaming computer,Taschen:الحاسوب المحمول:laptop"],
  ["Bildschirm", "Riesen:الشاشة الكبيرة:big screen,Touch:شاشة اللمس:touch screen"],
  ["Tastatur", "Funk:لوحة المفاتيح اللاسلكية:wireless keyboard"],
  ["Maus", "Funk:الفأرة اللاسلكية:wireless mouse"],
  ["Drucker", "Laser:طابعة الليزر:laser printer,Tinten:طابعة الحبر:inkjet printer"],
  ["Handy", "Dienst:هاتف العمل:work phone,Prepaid:الهاتف مسبق الدفع:prepaid phone"],
  ["Telefon", "Schnurlos:الهاتف اللاسلكي:cordless phone,Not:هاتف الطوارئ:emergency phone,Mobil:الهاتف المحمول:mobile phone"],
  ["Nummer", "Telefon:رقم الهاتف:phone number,Not:رقم الطوارئ:emergency number,Kunden:رقم العميل:customer number"],
  ["Hund", "Familien:كلب العائلة:family dog,Schäfer:كلب الراعي:shepherd dog,Blinden:كلب المكفوفين:guide dog"],
  ["Katze", "Haus:قطة البيت:house cat,Freigänger:قطة التجوال:outdoor cat"],
  ["Vogel", "Sing:الطائر المغرد:singing bird,Zug:الطائر المهاجر:migratory bird"],
  ["Baum", "Apfel:شجرة التفاح:apple tree,Weihnachts:شجرة عيد الميلاد:Christmas tree,Oliven:شجرة الزيتون:olive tree"],
  ["Blume", "Topf:زهرة الأصيص:potted flower,Schnitt:زهرة القطف:cut flower,Wiesen:زهرة المرج:meadow flower"],
  ["Park", "Stadt:منتزه المدينة:city park,Natur:المنتزه الطبيعي:nature park,Freizeit:منتزه الترفيه:leisure park"],
  ["Spielplatz", "Abenteuer:ملعب المغامرات:adventure playground,Wasser:الملعب المائي:water playground"],
  ["Sport", "Schul:الرياضة المدرسية:school sports,Mannschafts:الرياضة الجماعية:team sports,Winter:الرياضة الشتوية:winter sports,Breitens:الرياضة الشعبية:popular sports"],
  ["Training", "Fußball:تدريب كرة القدم:football training,Kraft:تدريب القوة:strength training,Ausdauer:تدريب التحمل:endurance training"],
  ["Spiel", "Heim:المباراة البيتية:home game,Auswärts:المباراة الخارجية:away game,Karten:لعبة الورق:card game,Brett:لعبة اللوح:board game"],
  ["Mannschaft", "Fußball:فريق كرة القدم:football team,National:المنتخب الوطني:national team,Jugend:فريق الشباب:youth team"],
  ["Musik", "Klassik:الموسيقى الكلاسيكية:classical music,Pop:موسيقى البوب:pop music,Live:الموسيقى الحية:live music"],
  ["Film", "Abend:سهرة الفيلم:film evening,Action:فيلم الأكشن:action film,Komödien:الفيلم الكوميدي:comedy film"],
  ["Buch", "Taschen:كتاب الجيب:pocket book,Kinder:كتاب الأطفال:children's book,Bilder:كتاب الصور:picture book"],
  ["Fest", "Schul:حفلة المدرسة:school party,Garten:حفلة الحديقة:garden party,Weihnachts:حفلة عيد الميلاد:Christmas party,Geburtstags:حفلة عيد الميلاد:birthday party"],
  ["Hochzeit", "Traum:زفاف الأحلام:dream wedding,Standesamts:زفاف البلدية:civil wedding"],
  ["Geburtstag", "Kinder:عيد ميلاد الأطفال:children's birthday,Runden:عيد الميلاد المستدير:milestone birthday"],
  ["Geschenk", "Weihnachts:هدية عيد الميلاد:Christmas gift,Geburtstags:هدية عيد الميلاد:birthday gift,Hochzeits:هدية الزفاف:wedding gift"],
  ["Freund", "Schul:صديق المدرسة:school friend,Kindheits:صديق الطفولة:childhood friend,Arbeits:صديق العمل:work friend"],
  ["Nachbar", "Zimmer:جار الغرفة:next-door neighbour,Haus:جار البيت:house neighbour"],
  ["Gast", "Hotel:نزيل الفندق:hotel guest,Hochzeits:ضيف الزفاف:wedding guest,Staats:ضيف الدولة:state guest"],
  ["Kunde", "Stamm:العميل الدائم:regular customer,Neu:العميل الجديد:new customer,Geschäfts:عميل الأعمال:business customer"],
  ["Verkäufer", "Markt:بائع السوق:market seller,Auto:بائع السيارات:car dealer"],
  ["Markt", "Wochen:السوق الأسبوعي:weekly market,Weihnachts:سوق عيد الميلاد:Christmas market,Floh:سوق البرغوث:flea market"],
  ["Laden", "Tante-Emma:دكان الحي:corner shop,Juwelier:محل المجوهرات:jeweller's,Blumen:محل الزهور:flower shop"],
  ["Kasse", "Schnell:الصندوق السريع:express checkout,Selbstbedienungs:الصندوق الذاتي:self checkout"],
  ["Preis", "Sonder:السعر الخاص:special price,Fest:السعر الثابت:fixed price,End:السعر النهائي:final price"],
  ["Rabatt", "Mengen:خصم الكمية:bulk discount,Studenten:خصم الطلاب:student discount"],
  ["Strafe", "Geld:الغرامة المالية:money fine,Park:مخالفة الوقوف:parking fine"],
  ["Unfall", "Auto:حادث السيارة:car accident,Arbeits:حادث العمل:work accident,Sport:الحادث الرياضي:sports accident"],
  ["Verkehr", "Berufs:مرور الذهاب للعمل:commuter traffic,Feierabend:مرور نهاية الدوام:rush-hour traffic"],
  ["Stau", "Morgen:ازدحام الصباح:morning jam,Feierabend:ازدحام نهاية الدوام:evening jam"],
  ["Führerschein", "Auto:رخصة السيارة:car licence,Motorrad:رخصة الدراجة النارية:motorbike licence,Probe:رخصة التجربة:probationary licence"],
  ["Kontrolle", "Pass:مراقبة الجوازات:passport control,Grenz:المراقبة الحدودية:border control,Geschwindigkeits:مراقبة السرعة:speed check"],
  ["Grenze", "Landes:حدود البلاد:country border,Stadt:حدود المدينة:city limit"],
  ["Zeit", "Freizeit:وقت الفراغ:free time,Arbeits:وقت العمل:working time,Schlafens:وقت النوم:bedtime,Ankunfts:وقت الوصول:arrival time,Abfahrts:وقت المغادرة:departure time"],
  ["Uhr", "Armband:ساعة اليد:wristwatch,Wand:ساعة الحائط:wall clock,Wecker:المنبه:alarm clock,Sonnen:الساعة الشمسية:sundial"],
  ["Kalender", "Wand:تقويم الحائط:wall calendar,Advents:تقويم المجيء:advent calendar,Termin:تقويم المواعيد:appointment calendar"],
  ["Woche", "Arbeits:أسبوع العمل:working week,Ferien:أسبوع العطلة:holiday week,Projekt:أسبوع المشروع:project week"],
  ["Monat", "Probe:شهر التجربة:trial month,Beitrags:شهر الاشتراك:contribution month"],
  ["Jahr", "Schul:السنة الدراسية:school year,Kalender:السنة التقويمية:calendar year,Gründungs:سنة التأسيس:founding year"],
  ["Morgen", "Weihnachts:صباح العيد:Christmas morning,Sonntag:صباح الأحد:Sunday morning"],
  ["Abend", "Film:سهرة الفيلم:film evening,Eltern:أمسية أولياء الأمور:parents' evening,Info:الأمسية التعريفية:info evening"],
  ["Nacht", "Hochzeits:ليلة الزفاف:wedding night,Schicht:نوبة الليل:night shift"],
  ["Kurs", "Deutsch:دورة الألمانية:German course,Abend:الدورة المسائية:evening course,Online:الدورة الإلكترونية:online course,Intensiv:الدورة المكثفة:intensive course"],
  ["Unterricht", "Deutsch:درس الألمانية:German lesson,Musik:درس الموسيقى:music lesson,Nachhilfe:درس التقوية:tutoring lesson"],
  ["Hausaufgabe", "Mathe:واجب الرياضيات:maths homework,Deutsch:واجب الألمانية:German homework"],
  ["Note", "Schul:العلامة المدرسية:school grade,Abitur:علامة الثانوية:abitur grade"],
  ["Zeugnis", "Schul:الشهادة المدرسية:school report,Arbeits:شهادة العمل:work reference"],
  ["Studium", "Bachelor:دراسة البكالوريوس:bachelor studies,Master:دراسة الماجستير:master studies,Medizin:دراسة الطب:medical studies"],
  ["Vorlesung", "Antritts:المحاضرة الافتتاحية:inaugural lecture,Online:المحاضرة الإلكترونية:online lecture"],
  ["Stipendium", "Deutschland:منحة ألمانيا:Germany scholarship,DAAD:منحة الداد:DAAD scholarship"],
  ["Ausbildung", "Bank:تدريب البنك:bank training,Krankenpflege:تدريب التمريض:nursing training,Lehr:تدريب التعليم:teaching training"],
  ["Praktikum", "Schüler:تدريب التلاميذ:pupil internship,Pflicht:التدريب الإلزامي:compulsory internship,Auslands:التدريب الخارجي:internship abroad"],
  ["Lebenslauf", "Muster:نموذج السيرة الذاتية:CV template,Euro:السيرة الأوروبية:europass CV"],
  ["Stelle", "Vollzeit:الوظيفة بدوام كامل:full-time post,Teilzeit:الوظيفة بدوام جزئي:part-time post,Lehr:وظيفة التعليم:teaching post,Traum:وظيفة الأحلام:dream job"],
  ["Gehalt", "Monats:الراتب الشهري:monthly salary,Einstiegs:راتب البداية:starting salary,Brutto:الراتب الإجمالي:gross salary"],
  ["Urlaubstag", "Rest:يوم الإجازة المتبقي:remaining leave day"],
  ["Kollegin", "Arbeits:زميلة العمل:female work colleague"],
  ["Chefin", "Abteilungs:رئيسة القسم:female department head"],
  ["Ärztin", "Kinder:طبيبة الأطفال:female pediatrician,Haus:طبيبة العائلة:female family doctor"],
  ["Lehrerin", "Deutsch:مدرسة الألمانية:female German teacher,Grundschul:معلمة الابتدائية:female primary teacher"],
  ["Verkäuferin", "Bäckerei:بائعة المخبز:female bakery seller"],
  ["Fahrerin", "Bus:سائقة الحافلة:female bus driver"],
  ["Kleid", "Abend:فستان السهرة:evening dress,Sommer:فستان صيفي:summer dress,Braut:فستان الزفاف:wedding dress"],
  ["Kaffee", "Morgen:قهوة الصباح:morning coffee"],
  ["Brot", "Abend:خبز العشاء:evening bread"],
  ["Essen", "Abend:طعام العشاء:dinner,Mittag:طعام الغداء:lunch"],
  ["Sendung", "Fernseh:برنامج تلفزيوني:TV programme,Radio:برنامج إذاعي:radio programme"],
  ["Adresse", "E-Mail:عنوان البريد الإلكتروني:email address,Heim:عنوان المنزل:home address,Geschäfts:عنوان العمل:business address,Internet:عنوان الإنترنت:internet address"],
  ["Datum", "Geburts:تاريخ الميلاد:date of birth,Ablauf:تاريخ الانتهاء:expiry date,Anreise:تاريخ الوصول:arrival date"],
  ["Ort", "Geburts:مكان الميلاد:birthplace,Wohn:مكان السكن:place of residence,Tat:مكان الحادث:crime scene"],
  ["Futter", "Hunde:طعام الكلاب:dog food,Katzen:طعام القطط:cat food,Vogel:طعام الطيور:bird food"],
  ["Haus", "Vogel:بيت الطيور:birdhouse,Puppen:بيت الدمى:dollhouse,Baum:بيت الشجرة:treehouse"],
  ["Foto", "Bewerbungs:صورة التقديم:application photo,Pass:صورة الجواز:passport photo,Hochzeits:صورة الزفاف:wedding photo,Urlaubs:صورة الإجازة:holiday photo"],
  ["Maus", "Computer:فأرة الحاسوب:computer mouse,Feld:فأر الحقل:field mouse"],
  ["Tour", "Berg:جولة الجبل:mountain tour,Stadt:جولة المدينة:city tour,Fahrrad:جولة الدراجة:bike tour"],
  ["Ufer", "Fluss:ضفة النهر:riverbank,See:ضفة البحيرة:lakeshore"],
  ["Vase", "Blumen:مزهرية الزهور:flower vase,Glas:مزهرية الزجاج:glass vase"],
  ["Bus", "Flughafen:حافلة المطار:airport bus,Schul:حافلة المدرسة:school bus,Nacht:الحافلة الليلية:night bus"],
  ["Hotel", "Strand:فندق الشاطئ:beach hotel,Berg:فندق الجبل:mountain hotel"],
  ["Laden", "Fahrrad:محل الدراجات:bike shop,Blumen:محل الزهور:flower shop"],
  ["Plan", "Wochen:الخطة الأسبوعية:weekly plan,Stadt:خريطة المدينة:city map,Flucht:خطة الهروب:escape plan"],
  ["Zeit", "Jahres:الموسم:season,Ankunfts:وقت الوصول:arrival time"],
  ["Geburtstag", "Kinder:عيد ميلاد الأطفال:children's birthday"],
  ["Film", "Spiel:الفيلم الروائي:feature film"],
  ["Anzug", "Schlaf:بيجامة:pajamas,Ski:بدلة التزلج:ski suit,Taucher:بدلة الغوص:diving suit"],
  ["Gericht", "Haupt:الطبق الرئيسي:main course"],
  ["Bericht", "Wetter:تقرير الطقس:weather report,Polizei:تقرير الشرطة:police report,Unfall:تقرير الحادث:accident report,Reise:تقرير الرحلة:travel report"],
  ["Bogen", "Regen:قوس قزح:rainbow"],
  ["Mann", "Schnee:رجل الثلج:snowman"],
  ["Angst", "Prüfungs:قلق الامتحان:exam anxiety,Flug:الخوف من الطيران:fear of flying,Zahnarzt:الخوف من طبيب الأسنان:dental fear"],
  ["Brei", "Baby:مهروس الأطفال:baby food"],
  ["Heim", "Senioren:دار المسنين:retirement home,Kinder:دار الأطفال:children's home"],
  ["Schicht", "Nacht:نوبة الليل:night shift,Früh:النوبة الصباحية:early shift,Spät:النوبة المسائية:late shift"],
  ["Zeitung", "Abend:جريدة المساء:evening paper,Morgen:جريدة الصباح:morning paper"],
  ["Wagen", "Kranken:سيارة الإسعاف:ambulance,Kinder:عربة الأطفال:pram"],
  ["Reise", "Hochzeits:شهر العسل:honeymoon,Studien:رحلة دراسية:study trip,Geschäfts:رحلة العمل:business trip,Traum:رحلة الأحلام:dream trip"],
  ["Fach", "Studien:التخصص الدراسي:field of study"],
  ["Gebühr", "Studien:الرسوم الدراسية:tuition fee"],
  ["Mode", "Kinder:أزياء الأطفال:children's fashion"],
  ["Amt", "Arbeits:مكتب العمل:employment office,Finanz:مصلحة الضرائب:tax office,Standes:مكتب الأحوال المدنية:registry office"],
  ["Glas", "Wein:كأس النبيذ:wine glass,Milch:كوب الحليب:glass of milk,Wasser:كوب الماء:glass of water"],
  ["Tisch", "Glas:طاولة زجاجية:glass table,Holz:طاولة خشبية:wooden table"],
  ["Spielzeug", "Holz:لعبة خشبية:wooden toy"],
  ["Tasse", "Unter:الصحن:saucer"],
  ["Haus", "Holz:بيت خشبي:wooden house"],
  ["Dose", "Thunfisch:علبة التونة:tuna can,Cola:علبة الكولا:cola can"],
  ["Becher", "Joghurt:علبة الزبادي:yogurt cup,Eier:كوب البيض:egg cup"],
  ["Tüte", "Plastik:كيس البلاستيك:plastic bag,Papier:كيس الورق:paper bag"],
  ["Korb", "Papier:سلة المهملات:wastepaper basket,Einkaufs:سلة التسوق:shopping basket,Obst:سلة الفاكهة:fruit basket"],
  ["Schüssel", "Glas:وعاء زجاجي:glass bowl,Salat:وعاء السلطة:salad bowl"],
  ["Milch", "Reis:حليب الأرز:rice milk"],
  ["Insel", "Museums:جزيرة المتاحف:museum island"],
  ["Kirche", "Dorf:كنيسة القرية:village church"],
  ["Fest", "Dorf:مهرجان القرية:village festival,Stadt:مهرجان المدينة:city festival,Schul:حفلة المدرسة:school festival"],
  ["Stand", "Markt:جناح السوق:market stall,Taxi:موقف التاكسي:taxi stand"],
  ["Kamm", "Holz:مشط خشبي:wooden comb"],
  ["Bahn", "Berg:سكة الجبل:mountain railway"],
  ["Automat", "Geld:الصراف الآلي:ATM,Fahrkarten:جهاز التذاكر:ticket machine"],
  ["Kalender", "Advents:تقويم المجيء:advent calendar,Wand:تقويم الحائط:wall calendar,Termin:تقويم المواعيد:appointment calendar"],
  ["Haus", "Park:موقف السيارات:parking garage,Holz:بيت خشبي:wooden house"],
  ["Schirm", "Regen:مظلة المطر:umbrella,Sonnen:مظلة الشمس:sunshade"],
  ["Licht", "Tages:ضوء النهار:daylight,Kerzen:ضوء الشموع:candlelight"],
  ["Schule", "Abend:المدرسة المسائية:evening school"],
  ["Shorts", "Jeans:شورت جينز:denim shorts,Sport:شورت رياضي:sports shorts"],
  ["Spätzle", "Käse:نودلز البيض بالجبن:cheese spaetzle"],
  ["Eltern", "Adoptiv:الوالدان بالتبني:adoptive parents,Pflege:الوالدان الحاضنان:foster parents"],
];

/* BIGPREFIX: separable (1) / inseparable (0) prefixed verbs, "inf|sep|reg|ar".
   reg=I marks strong verbs. Principal parts derive from the base verb automatically. */
const BIGPREFIX = [
  "ankommen|1|I|يصل", "mitkommen|1|I|يأتي مع", "zurückkommen|1|I|يعود", "nachkommen|1|I|يلحق", "vorkommen|1|I|يحدث",
  "auskommen|1|I|يتدبر", "bekommen|0|I|يحصل على", "entkommen|0|I|يهرب",
  "aufgehen|1|I|يشرق / يفتح", "untergehen|1|I|يغرب", "ausgehen|1|I|يخرج", "eingehen|1|I|يدخل / يتقلص", "mitgehen|1|I|يذهب مع", "nachgehen|1|I|يتابع", "vorgehen|1|I|يتقدم", "vergehen|0|I|يمضي",
  "abfahren|1|I|يغادر", "anfahren|1|I|يصل / يصدم", "ausfahren|1|I|يخرج بالسيارة", "einfahren|1|I|يدخل / يعتاد", "mitfahren|1|I|يركب مع", "fortfahren|1|I|يواصل", "weiterfahren|1|I|يتابع السير", "heimfahren|1|I|يعود للبيت", "losfahren|1|I|ينطلق", "vorfahren|1|I|يتقدم بالسيارة", "erfahren|0|I|يعرف / يختبر", "überfahren|0|I|يدهس",
  "aufstehen|1|I|ينهض", "bestehen|0|I|يجتاز / يتكون", "verstehen|0|I|يفهم", "entstehen|0|I|ينشأ", "anstehen|1|I|يقف في الطابور", "feststehen|1|I|يثبت", "bevorstehen|1|I|يوشك",
  "aufstellen|1|R|ينصب", "ausstellen|1|R|يعرض", "bestellen|1|R|يطلب", "vorstellen|1|R|يقدم", "sich vorstellen|1|R|يتخيل / يقدم نفسه", "einstellen|1|R|يوظف / يضبط", "herstellen|1|R|ينتج", "anstellen|1|R|يوظف", "darstellen|1|R|يمثل", "zustallen|1|R|يغلق", "zustellen|1|R|يوصل", "umstellen|1|R|يحول / يعيد الترتيب", "verstellen|1|R|يحرف / يضبط", "erstellen|1|R|ينشئ",
  "abnehmen|1|I|ينقص / يأخذ", "zunehmen|1|I|يزيد", "annehmen|1|I|يقبل / يفترض", "aufnehmen|1|I|يستقبل / يسجل", "einnehmen|1|I|يتناول / يحتل", "mitnehmen|1|I|يأخذ معه", "teilnehmen|1|I|يشارك", "übernehmen|0|I|يتولى", "sich benehmen|0|I|يتصرف", "entnehmen|0|I|يستخرج",
  "abgeben|1|I|يسلم", "angeben|1|I|يذكر / يتباهى", "aufgeben|1|I|يستسلم / يرسل", "ausgeben|1|I|ينفق", "sich begeben|0|I|يتوجه", "eingeben|1|I|يدخل (بيانات)", "mitgeben|1|I|يعطي مع", "nachgeben|1|I|يتنازل", "übergeben|0|I|يسلم", "vergeben|0|I|يمنح / يسامح", "vorgeben|1|I|يدعي", "wiedergeben|1|I|يعيد / يروي", "zugeben|1|I|يعترف",
  "abhalten|1|I|يعقد / يمنع", "anhalten|1|I|يتوقف", "aufhalten|1|I|يؤخر", "aushalten|1|I|يتحمل", "erhalten|0|I|يحصل على", "behalten|0|I|يحتفظ", "sich unterhalten|0|I|يتحدث / يتسلى", "sich verhalten|0|I|يتصرف",
  "verlassen|0|I|يغادر", "entlassen|0|I|يفصل / يسرح", "hinterlassen|0|I|يترك وراءه", "nachlassen|1|I|يخف / يتراجع", "unterlassen|0|I|يمتنع", "zulassen|1|I|يسمح", "einlassen|1|I|يدخل", "auslassen|1|I|يحذف",
  "aufschlagen|1|I|يفتح (كتاب) / يقترح سعرا", "vorschlagen|1|I|يقترح", "zuschlagen|1|I|يضرب / يغلق بقوة", "abschlagen|1|I|يرفض",
  "beitragen|1|I|يساهم", "auftragen|1|I|يدهن / يكلف", "austragen|1|I|يوزع", "eintragen|1|I|يسجل", "nachtragen|1|I|يلحق", "übertragen|0|I|ينقل", "sich vertragen|0|I|يتفاهم", "vortragen|1|I|يلقي",
  "besprechen|0|I|يناقش", "versprechen|0|I|يعد", "widersprechen|0|I|يعترض", "ansprechen|1|I|يخاطب", "aussprechen|1|I|يلفظ", "nachsprechen|1|I|يردد",
  "abbrechen|1|I|يقطع / يهدم", "aufbrechen|1|I|ينطلق / يكسر", "ausbrechen|1|I|يندلع / يهرب", "einbrechen|1|I|يقتحم", "unterbrechen|0|I|يقاطع", "zusammenbrechen|1|I|ينهار", "durchbrechen|1|I|يخترق",
  "ansehen|1|I|ينظر إلى", "aussehen|1|I|يبدو", "sich vorsehen|1|I|يحذر", "nachsehen|1|I|يتحقق", "übersehen|0|I|يتغاضى / يفوته", "zusehen|1|I|يشاهد", "fernsehen|1|I|يشاهد التلفاز", "wiedersehen|1|I|يرى مجددا",
  "aufschreiben|1|I|يدون", "abschreiben|1|I|ينسخ / يغش", "vorschreiben|1|I|يفرض", "beschreiben|0|I|يصف", "sich verschreiben|0|I|يخطئ الكتابة", "unterschreiben|0|I|يوقع", "mitschreiben|1|I|يدون مع", "umschreiben|1|I|يعيد الصياغة",
  "sich anziehen|1|I|يلبس", "ausziehen|1|I|يخلع / ينتقل", "umziehen|1|I|ينتقل", "einziehen|1|I|ينتقل إلى", "erziehen|0|I|يربي", "sich verziehen|0|I|يتشوه / ينسحب", "aufziehen|1|I|يربي / يشد", "nachziehen|1|I|يلحق", "vorziehen|1|I|يفضل", "sich zurückziehen|1|I|ينسحب", "großziehen|1|I|يربي",
  "nachdenken|1|I|يفكر", "bedenken|0|I|يراعي", "sich ausdenken|1|I|يبتكر",
  "mitbringen|1|I|يحضر معه", "beibringen|1|I|يعلم", "aufbringen|1|I|يجمع / يثير", "vollbringen|0|I|ينجز", "umbringen|1|I|يقتل", "überbringen|0|I|يوصل", "vorbringen|1|I|يطرح", "zurückbringen|1|I|يعيد",
  "anfangen|1|I|يبدأ", "empfangen|0|I|يستقبل", "auffangen|1|I|يلتقط", "einfangen|1|I|يمسك",
  "weglaufen|1|I|يهرب", "sich verlaufen|1|I|يضل الطريق", "mitlaufen|1|I|يركض مع", "nachlaufen|1|I|يركض خلف",
  "anrufen|1|I|يتصل", "aufrufen|1|I|ينادي / يستدعي", "ausrufen|1|I|يهتف", "zurufen|1|I|ينادي", "hervorrufen|1|I|يثير",
  "gefallen|0|I|يعجب", "auffallen|1|I|يلفت النظر", "einfallen|1|I|يخطر بباله", "ausfallen|1|I|يلغى", "umfallen|1|I|يسقط", "hinfallen|1|I|يسقط", "überfallen|0|I|يهاجم", "zerfallen|1|I|يتفتت",
  "einschlafen|1|I|ينام", "ausschlafen|1|I|يشبع نوما", "verschlafen|1|I|يفوته (النوم)",
  "aufessen|1|I|يأكل كله", "mitessen|1|I|يأكل مع", "sich überessen|0|I|يتخم",
  "austrinken|1|I|يشرب كله", "sich betrinken|0|I|يسكر",
  "vorlesen|1|I|يقرأ بصوت عال", "nachlesen|1|I|يراجع القراءة", "durchlesen|1|I|يقرأ كاملا", "überlesen|0|I|يتصفح سريعا",
  "abarbeiten|1|R|ينجز بالترتيب", "aufarbeiten|1|R|يعالج / يستدرك", "ausarbeiten|1|R|يعد بالتفصيل", "sich überarbeiten|0|R|يرهق نفسه", "sich einarbeiten|1|R|يتأقلم مع العمل", "mitarbeiten|1|R|يتعاون", "nacharbeiten|1|R|يستدرك", "vorarbeiten|1|R|يجهز مسبقا",
  "aufmachen|1|R|يفتح", "zumachen|1|R|يغلق", "mitmachen|1|R|يشارك", "nachmachen|1|R|يقلد", "vormachen|1|R|يري كيف", "anmachen|1|R|يشعل / يثبت", "ausmachen|1|R|يطفي / يتفق", "weitermachen|1|R|يواصل",
  "einkaufen|1|R|يتسوق", "verkaufen|1|R|يبيع",
  "aufsuchen|1|R|يزور / يقصد", "aussuchen|1|R|يختار", "besuchen|0|R|يزور", "versuchen|0|R|يحاول",
  "bezahlen|0|R|يدفع", "anzahlen|1|R|يدفع مقدما", "nachzahlen|1|R|يدفع لاحقا", "zurückzahlen|1|R|يرد المبلغ", "einzahlen|1|R|يودع",
  "aufsetzen|1|R|يضع على", "absetzen|1|R|ينزل / يوقف", "aussetzen|1|R|يعلق / يعرض لـ", "besetzen|0|R|يشغل", "ersetzen|0|R|يستبدل", "fortsetzen|1|R|يواصل", "umsetzen|1|R|ينفذ / يحول", "übersetzen|0|R|يترجم", "versetzen|0|R|ينقل", "zusetzen|1|R|يضيف",
  "ablegen|1|R|يخلع / يؤدي", "auflegen|1|R|يضع / يغلق الهاتف", "auslegen|1|R|يعرض / يفسر", "belegen|0|R|يسجل مادة / يحجز", "sich überlegen|0|R|يفكر", "verlegen|0|R|يؤجل / ينشر", "vorlegen|1|R|يقدم", "zurücklegen|1|R|يضع جانبا", "zusammenlegen|1|R|يجمع / يطوي",
  "abwarten|1|R|ينتظر", "erwarten|0|R|يتوقع",
  "anerkennen|0|I|يعترف", "sich bekennen|0|I|يقر", "erkennen|0|I|يتعرف على",
  "benennen|0|I|يسمي", "umbenennen|0|I|يعيد التسمية",
  "beraten|0|I|يستشير", "verraten|0|I|يخون / يفشي", "erraten|0|I|يخمن",
  "antreten|1|I|يبدأ / يمثل", "auftreten|1|I|يظهر / يتصرف", "austreten|1|I|ينسحب", "betreten|0|I|يدخل", "eintreten|1|I|يدخل / يحدث", "vertreten|0|I|ينوب", "vortreten|1|I|يتقدم", "zurücktreten|1|I|يستقيل",
  "abschneiden|1|I|يقص", "aufschneiden|1|I|يقطع / يفتح", "ausschneiden|1|I|يقص", "einschneiden|1|I|يجرح / يقطع", "zerschneiden|1|I|يقطع إربا",
  "abwaschen|1|I|يغسل", "aufwaschen|1|I|يغسل الصحون", "auswaschen|1|I|يغسل جيدا",
  "abputzen|1|R|يمسح", "ausputzen|1|R|ينظف", "wegputzen|1|R|يمسح",
  "abkochen|1|R|يسلق", "aufkochen|1|R|يغلي", "einkochen|1|R|يركز بالغلي", "überkochen|1|R|يفور", "verkochen|1|R|يطهو زيادة",
  "aufbacken|1|I|يخبز", "ausbacken|1|I|يقلي",
  "aufheizen|1|R|يسخن", "einheizen|1|R|يشعل التدفئة",
  "abkühlen|1|R|يبرد", "auskühlen|1|R|يبرد تماما", "sich verkühlen|1|R|يصاب بالبرد",
  "eröffnen|0|R|يفتتح", "wiedereröffnen|1|R|يعيد الافتتاح",
  "abschließen|1|I|يغلق / يبرم", "aufschließen|1|I|يفتح بالقفل", "sich anschließen|0|I|ينضم", "ausschließen|1|I|يستبعد", "beschließen|0|I|يقرر", "verschließen|1|I|يغلق بإحكام", "zuschließen|1|I|يقفل",
  "absperren|1|R|يغلق / يحجز", "entsperren|0|R|يفك القفل", "versperren|0|R|يسد",
  "abdrucken|1|R|يطبع", "ausdrucken|1|R|يطبع", "aufdrucken|1|R|يطبع على", "nachdrucken|1|R|يعيد الطبع",
  "abpacken|1|R|يغلف", "auspacken|1|R|يفرغ الحقائب", "einpacken|1|R|يحزم", "umpacken|1|R|يعيد التغليف", "verpacken|0|R|يغلف", "zupacken|1|R|يمسك بقوة",
  "abladen|1|I|يفرغ", "aufladen|1|I|يشحن", "ausladen|1|I|يفرغ / يلغي الدعوة", "einladen|1|I|يدعو", "überladen|0|I|يثقل", "verladen|0|I|يحمل", "herunterladen|1|I|يحمل (من الإنترنت)", "hochladen|1|I|يرفع (ملفا)",
  "sich anmelden|1|R|يسجل", "sich abmelden|1|R|يلغي التسجيل", "sich zurückmelden|1|R|يرد / يعود",
  "sich ankleiden|1|R|يلبس", "auskleiden|1|R|يخلع", "bekleiden|0|R|يشغل منصبا", "sich verkleiden|0|R|يتنكر",
  "abschieben|1|I|يرحل / يؤجل", "aufschieben|1|I|يؤجل", "einschieben|1|I|يدخل بين", "verschieben|0|I|يؤجل", "zuschieben|1|I|يدفع نحو",
  "abhängen|1|I|يسترخي / يعلق", "anhängen|1|I|يعلق / يرفق", "aufhängen|1|I|يعلق", "aushängen|1|I|يعلق إعلانا", "einhängen|1|I|يعلق في", "sich umhängen|1|R|يلف حوله", "verhängen|0|R|يفرض",
  "abfassen|1|R|يصوغ", "anfassen|1|R|يلمس", "auffassen|1|R|يفهم", "erfassen|0|R|يسجل / يدرك", "umfassen|0|R|يشمل", "verfassen|0|R|يؤلف", "zusammenfassen|1|R|يلخص",
  "abpassen|1|R|يتحين", "sich anpassen|1|R|يتكيف", "aufpassen|1|R|ينتبه", "verpassen|0|R|يفوت", "hereinpassen|1|R|يناسب / يتسع",
  "begrüßen|0|R|يرحب",
  "abteilen|1|R|يقسم", "aufteilen|1|R|يوزع", "einteilen|1|R|يقسم / يجدول", "verteilen|0|R|يوزع", "zuteilen|1|R|يخصص", "mitteilen|0|R|يبلغ", "austeilen|1|R|يوزع",
  "beurteilen|0|R|يقيّم", "verurteilen|0|R|يدين",
  "aushandeln|1|R|يتفاوض", "behandeln|0|R|يعالج", "verhandeln|0|R|يتفاوض", "misshandeln|0|R|يسيء معاملة",
  "sich abwechseln|1|R|يتناوب", "auswechseln|1|R|يستبدل", "einwechseln|1|R|يبدل لاعبا", "verwechseln|0|R|يخلط بين",
  "abwandern|1|R|يهاجر", "auswandern|1|R|يهاجر", "einwandern|1|R|يهاجر إلى", "zuwandern|1|R|ينزح إلى",
  "abreisen|1|R|يسافر", "anreisen|1|R|يصل مسافرا", "verreisen|0|R|يسافر", "weiterreisen|1|R|يتابع السفر", "durchreisen|1|R|يعبر",
  "abfliegen|1|I|يقلع", "anfliegen|1|I|يقترب طائرا", "sich verfliegen|0|I|يضل طائرا", "wegfliegen|1|I|يطير بعيدا", "weiterfliegen|1|I|يتابع الطيران", "zurückfliegen|1|I|يعود طائرا",
  "mitschwimmen|1|I|يسبح مع",
  "abspringen|1|I|يقفز", "anspringen|1|I|يشتغل / يقفز على", "aufspringen|1|I|يقفز فجأة", "einspringen|1|I|يحل محل", "überspringen|0|I|يتخطى",
  "absteigen|1|I|ينزل", "ansteigen|1|I|يرتفع", "aufsteigen|1|I|يصعد", "aussteigen|1|I|ينزل / ينسحب", "besteigen|0|I|يتسلق", "einsteigen|1|I|يركب", "umsteigen|1|I|يبدل (القطار)", "übersteigen|1|I|يتجاوز", "sich versteigen|1|I|يضل", "zusteigen|1|I|يركب",
  "absinken|1|I|يهبط", "einsinken|1|I|يغوص", "versinken|1|I|يغرق",
  "erlernen|0|R|يتعلم", "verlernen|0|R|ينسى ما تعلمه",
  "belehren|0|R|يعظ",
  "abfragen|1|R|يسأل / يستجوب", "anfragen|1|R|يستفسر", "befragen|0|R|يستجوب", "erfragen|0|R|يستعلم", "nachfragen|1|R|يسأل مجددا",
  "beantworten|0|R|يجيب", "sich verantworten|0|R|يبرر",
  "erbitten|0|I|يلتمس", "sich verbitten|0|I|يرفض",
  "abdanken|1|R|يستقيل", "sich bedanken|0|R|يشكر", "verdanken|0|R|يدين بالفضل",
  "bewohnen|0|R|يسكن",
  "anmieten|1|R|يستأجر", "untermieten|0|R|يؤجر من الباطن", "vermieten|0|R|يؤجر",
  "abbauen|1|R|يفكك / يخفض", "anbauen|1|R|يبني ملحقا / يزرع", "aufbauen|1|R|يبني / يؤسس", "ausbauen|1|R|يوسع", "einbauen|1|R|يركب", "umbauen|1|R|يرمم / يحول", "verbauen|0|R|يسد / يبني خطأ", "wiederaufbauen|1|R|يعيد البناء",
  "abdecken|1|R|يغطي / يكشف", "aufdecken|1|R|يكشف", "entdecken|0|R|يكتشف", "verdecken|0|R|يحجب", "zudecken|1|R|يغطي",
  "abräumen|1|R|يرتب / يفرغ", "aufräumen|1|R|يرتب", "einräumen|1|R|يرتب / يمنح", "umräumen|1|R|يعيد الترتيب", "verräumen|0|R|يضع في مكانه", "wegräumen|1|R|يبعد",
  "entleeren|0|R|يفرغ",
  "abfüllen|1|R|يعبئ", "auffüllen|1|R|يملأ", "ausfüllen|1|R|يملأ (استمارة)", "einfüllen|1|R|يسكب في", "nachfüllen|1|R|يعيد الملء", "überfüllen|1|R|يملأ زيادة",
  "begießen|1|I|يسقي", "vergießen|0|I|يسكب / يذرف",
  "erscheinen|0|I|يظهر", "bescheinen|0|I|يضيء",
  "aufblühen|1|R|يزدهر", "erblühen|0|R|يتفتح",
  "aufwachsen|1|I|ينشأ", "anwachsen|1|I|ينمو", "sich auswachsen|1|I|يتطور إلى", "nachwachsen|1|I|ينمو مجددا", "sich verwachsen|1|I|يلتحم", "zusammenwachsen|1|I|يلتحم",
  "abheilen|1|R|يندمل", "ausheilen|1|R|يبرأ", "verheilen|1|R|يلتئم",
  "ankleben|1|R|يلصق", "aufkleben|1|R|يلصق على", "einkleben|1|R|يلصق في", "verkleben|0|R|يلصق", "zukleben|1|R|يلصق مغلقا",
  "annähen|1|R|يخيط", "aufnähen|1|R|يخيط على", "einnähen|1|R|يخيط داخل", "vernähen|0|R|يخيط", "zunähen|1|R|يخيط مغلقا",
  "abbügeln|1|R|يكوي", "aufbügeln|1|R|يكوي / يلصق بالكي",
  "abschalten|1|R|يطفي", "anschalten|1|R|يشعل", "einschalten|1|R|يشغل", "ausschalten|1|R|يطفي", "umschalten|1|R|يحول", "hochschalten|1|R|يرفع السرعة", "runterschalten|1|R|يخفض السرعة", "sich zwischenschalten|1|R|يتوسط",
  "andauern|1|R|يستمر", "bedauern|0|R|يأسف",
  "sich beeilen|0|R|يسرع",
  "sich verspäten|0|R|يتأخر",
  "erhoffen|0|R|يأمل",
  "beglückwünschen|0|R|يهنئ",
  "befürchten|0|R|يخشى",
  "beängstigen|0|R|يخيف",
  "erfreuen|0|R|يسر", "sich befreunden|0|R|يصادق",
  "verärgern|0|R|يغضب",
  "verwundern|0|R|يدهش", "bewundern|0|R|يعجب بـ",
  "beschämen|0|R|يخجل",
  "verkosten|0|R|يتذوق",
  "abschmecken|1|R|يتذوق / يضبط الطعم",
  "abhören|1|R|يستمع / يختبر", "anhören|1|R|يستمع إلى", "aufhören|1|R|يتوقف", "mithören|1|R|يستمع مع", "überhören|0|R|لا يسمع / يتجاهل", "sich verhören|0|R|يسمع خطأ", "weghören|1|R|يصم أذنيه", "zuhören|1|R|يصغي",
  "anschauen|1|R|يشاهد", "ausschauen|1|R|يبدو / يطل", "nachschauen|1|R|يتحقق", "vorschauen|1|R|يستعرض", "zuschauen|1|R|يشاهد", "wegschauen|1|R|يشيح بنظره", "herumschauen|1|R|ينظر حوله",
  "angucken|1|R|ينظر إلى", "nachgucken|1|R|يتحقق", "weggucken|1|R|يشيح بنظره",
  "aufzeigen|1|R|يري / يوضح", "vorzeigen|1|R|يري", "anzeigen|1|R|يبلغ / يعرض",
  "abweisen|1|I|يرفض / يرد", "anweisen|1|I|يوجه", "aufweisen|1|I|يظهر", "sich ausweisen|1|I|يثبت هويته", "beweisen|0|I|يثبت", "einweisen|1|I|يدخل (مستشفى) / يوجه", "überweisen|0|I|يحول (مالا)", "verweisen|0|I|يحيل إلى",
  "andeuten|1|R|يلمح", "bedeuten|0|R|يعني", "hindeuten|1|R|يشير إلى",
];

/* BIGADJ: derived adjectives "base|ar|en|lvl|comp|sup". */
const BIGADJ = [
  "unfreundlich|غير ودود|unfriendly|A2|unfreundlicher|unfreundlichst",
  "unhöflich|غير مهذب|impolite|A2|unhöflicher|unhöflichst",
  "ungeduldig|غير صبور|impatient|A2|ungeduldiger|ungeduldigst",
  "unzufrieden|غير راض|dissatisfied|A2|unzufriedener|unzufriedenst",
  "unglücklich|غير سعيد|unhappy|A2|unglücklicher|unglücklichst",
  "unklar|غير واضح|unclear|A2|unklarer|unklarst",
  "unsicher|غير متأكد|unsure|A2|unsicherer|unsicherst",
  "unbekannt|غير معروف|unknown|A2|unbekannter|unbekanntest",
  "ungewohnt|غير معتاد|unaccustomed|A2|ungewohnter|ungewohntest",
  "unbequem|غير مريح|uncomfortable|A2|unbequemer|unbequemst",
  "unpraktisch|غير عملي|impractical|A2|unpraktischer|unpraktischst",
  "unpünktlich|غير دقيق (المواعيد)|unpunctual|A2|unpünktlicher|unpünktlichst",
  "unordentlich|غير مرتب|untidy|A2|unordentlicher|unordentlichst",
  "unruhig|غير هادئ|restless|A2|unruhiger|unruhigst",
  "unwichtig|غير مهم|unimportant|A1|unwichtiger|unwichtigst",
  "unnötig|غير ضروري|unnecessary|A2|unnötiger|unnötigst",
  "unmöglich|مستحيل|impossible|A2|unmöglicher|unmöglichst",
  "unsichtbar|غير مرئي|invisible|B1|unsichtbarer|unsichtbarst",
  "unvergesslich|لا ينسى|unforgettable|B1|unvergesslicher|unvergesslichst",
  "unabhängig|مستقل|independent|B1|unabhängiger|unabhängigst",
  "freundlich|ودود|friendly|A1|freundlicher|freundlichst",
  "höflich|مهذب|polite|A1|höflicher|höflichst",
  "beruflich|مهني|professional|A2|-|-",
  "persönlich|شخصي|personal|A2|persönlicher|persönlichst",
  "schriftlich|كتابي|written|A2|-|-",
  "mündlich|شفهي|oral|A2|-|-",
  "monatlich|شهري|monthly|A1|-|-",
  "jährlich|سنوي|yearly|A1|-|-",
  "wöchentlich|أسبوعي|weekly|A1|-|-",
  "täglich|يومي|daily|A1|-|-",
  "pünktlich|دقيق (المواعيد)|punctual|A1|pünktlicher|pünktlichst",
  "ordentlich|مرتب|tidy|A1|ordentlicher|ordentlichst",
  "deutlich|واضح|clear|A1|deutlicher|deutlichst",
  "gemütlich|مريح|cosy|A1|gemütlicher|gemütlichst",
  "nützlich|مفيد|useful|A1|nützlicher|nützlichst",
  "schädlich|ضار|harmful|A2|schädlicher|schädlichst",
  "fröhlich|مبتهج|cheerful|A1|fröhlicher|fröhlichst",
  "traurig|حزين|sad|A1|trauriger|traurigst",
  "eilig|مستعجل|urgent|A2|eiliger|eiligst",
  "mutig|شجاع|brave|A1|mutiger|mutigst",
  "vorsichtig|حذر|careful|A1|vorsichtiger|vorsichtigst",
  "neugierig|فضولي|curious|A2|neugieriger|neugierigst",
  "eifersüchtig|غيور|jealous|A2|eifersüchtiger|eifersüchtigst",
  "stolz|فخور|proud|A1|stolzer|stolzest",
  "zufrieden|راض|satisfied|A1|zufriedener|zufriedenst",
  "bereit|مستعد|ready|A1|bereiter|bereitest",
  "ruhig|هادئ|calm|A1|ruhiger|ruhigst",
  "laut|عال|loud|A1|lauter|lautest",
  "leise|هادئ|quiet|A1|leiser|leisest",
  "hell|مشرق|bright|A1|heller|hellst",
  "dunkel|داكن|dark|A1|dunkler|dunkelst",
  "sauber|نظيف|clean|A1|sauberer|sauberest",
  "schmutzig|متسخ|dirty|A1|schmutziger|schmutzigst",
  "trocken|جاف|dry|A1|trockener|trockenst",
  "nass|مبلل|wet|A1|nasser|nassest",
  "heiß|ساخن|hot|A1|heißer|heißest",
  "kühl|بارد|cool|A1|kühler|kühlst",
  "warm|دافئ|warm|A1|wärmer|wärmst",
  "kalt|بارد|cold|A1|kälter|kältest",
  "süß|حلو|sweet|A1|süßer|süßest",
  "sauer|حامض|sour|A1|saurer|sauerst",
  "bitter|مر|bitter|A2|bitterer|bitterst",
  "salzig|مالح|salty|A1|salziger|salzigst",
  "scharf|حاد / حار|spicy|A1|schärfer|schärfst",
  "frisch|طازج|fresh|A1|frischer|frischest",
  "faul|فاسد / كسول|rotten|A2|fauler|faulst",
  "reif|ناضج|ripe|A2|reifer|reifst",
  "müde|متعب|tired|A1|müder|müdest",
  "wach|مستيقظ|awake|A1|wacher|wachst",
  "gesund|صحي|healthy|A1|gesünder|gesündest",
  "krank|مريض|sick|A1|kränker|kränkest",
  "stark|قوي|strong|A1|stärker|stärkst",
  "schwach|ضعيف|weak|A1|schwächer|schwächst",
  "dick|سميك|thick|A1|dicker|dickst",
  "dünn|رفيع|thin|A1|dünner|dünnst",
  "breit|عريض|wide|A1|breiter|breitest",
  "schmal|ضيق|narrow|A1|schmaler|schmalst",
  "hoch|عال|high|A1|höher|höchst",
  "tief|عميق|deep|A1|tiefer|tiefst",
  "weit|بعيد / واسع|far|A1|weiter|weitest",
  "nah|قريب|near|A1|näher|nächst",
  "schnell|سريع|fast|A1|schneller|schnellst",
  "langsam|بطيء|slow|A1|langsamer|langsamst",
  "früh|مبكر|early|A1|früher|frühest",
  "spät|متأخر|late|A1|später|spätest",
  "pünktlich|دقيق|punctual|A1|pünktlicher|pünktlichst",
  "fleißig|مجتهد|diligent|A1|fleißiger|fleißigst",
  "faulig|متعفن|mouldy|A2|fauliger|fauligst",
  "ärgerlich|مزعج|annoying|A2|ärgerlicher|ärgerlichst",
  "peinlich|محرج|embarrassing|A2|peinlicher|peinlichst",
  "langweilig|ممل|boring|A1|langweiliger|langweiligst",
  "spannend|مشوق|exciting|A1|spannender|spannendst",
  "interessant|مثير للاهتمام|interesting|A1|interessanter|interessantest",
  "wichtig|مهم|important|A1|wichtiger|wichtigst",
  "richtig|صحيح|correct|A1|richtiger|richtigst",
  "falsch|خاطئ|wrong|A1|falscher|falschest",
  "ehrlich|صادق|honest|A1|ehrlicher|ehrlichst",
  "lügnerisch|كاذب|lying|A2|lügnerischer|lügnerischst",
  "gerecht|عادل|fair|A2|gerechter|gerechtest",
  "ungerecht|ظالم|unfair|A2|ungerechter|ungerechtest",
  "sicher|آمن / متأكد|safe|A1|sicherer|sicherst",
  "gefährlich|خطير|dangerous|A1|gefährlicher|gefährlichst",
  "mutig|شجاع|brave|A1|mutiger|mutigst",
  "ängstlich|خائف|anxious|A1|ängstlicher|ängstlichst",
  "glücklich|سعيد|happy|A1|glücklicher|glücklichst",
  "traurig|حزين|sad|A1|trauriger|traurigst",
  "wütend|غاضب|angry|A1|wütender|wütendst",
  "verliebt|واقع في الحب|in love|A2|verliebter|verliebtest",
  "verlobt|مخطوب|engaged|A2|verlobter|verlobtest",
  "verheiratet|متزوج|married|A1|-|-",
  "geschieden|مطلق|divorced|A2|-|-",
  "ledig|أعزب|single|A2|-|-",
  "schwanger|حامل|pregnant|A2|-|-",
  "erwachsen|بالغ|adult|A1|erwachsener|erwachsenst",
  "kindisch|طفولي|childish|A2|kindischer|kindischst",
  "jugendlich|شاب|youthful|A2|jugendlicher|jugendlichst",
  "altmodisch|قديم الطراز|old-fashioned|A2|altmodischer|altmodischst",
  "modern|حديث|modern|A1|moderner|modernst",
  "klassisch|كلاسيكي|classic|A2|klassischer|klassischst",
  "romantisch|رومانسي|romantic|A2|romantischer|romantischst",
  "praktisch|عملي|practical|A1|praktischer|praktischst",
  "theoretisch|نظري|theoretical|B1|theoretischer|theoretischst",
  "logisch|منطقي|logical|A2|logischer|logischst",
  "unlogisch|غير منطقي|illogical|A2|unlogischer|unlogischst",
  "typisch|نموذجي|typical|A1|typischer|typischst",
  "untypisch|غير نموذجي|atypical|A2|untypischer|untypischst",
  "sympathisch|لطيف|likeable|A1|sympathischer|sympathischst",
  "unsympathisch|غير لطيف|unlikeable|A2|unsympathischer|unsympathischst",
  "fantastisch|رائع|fantastic|A1|fantastischer|fantastischst",
  "realistisch|واقعي|realistic|A2|realistischer|realistischst",
  "optimistisch|متفائل|optimistic|A2|optimistischer|optimistischst",
  "pessimistisch|متشائم|pessimistic|A2|pessimistischer|pessimistischst",
  "touristisch|سياحي|touristy|A2|touristischer|touristischst",
  "städtisch|حضري|urban|A2|städtischer|städtischst",
  "ländlich|ريفي|rural|A2|ländlicher|ländlichst",
  "staatlich|حكومي|state|A2|-|-",
  "öffentlich|عام|public|A1|-|-",
  "privat|خاص|private|A1|privater|privatest",
  "berufstätig|عامل|employed|A2|-|-",
  "arbeitslos|عاطل عن العمل|unemployed|A2|-|-",
  "obdachlos|بلا مأوى|homeless|B1|-|-",
  "sprachlos|عاجز عن الكلام|speechless|B1|sprachloser|sprachlosest",
  "hilflos|عاجز|helpless|A2|hilfloser|hilflosest",
  "hoffnungslos|يائس|hopeless|A2|hoffnungsloser|hoffnungslosest",
  "sinnvoll|مفيد / ذو معنى|sensible|A2|sinnvoller|sinnvollst",
  "sinnlos|بلا معنى|senseless|A2|sinnloser|sinnlosest",
  "erfolgreich|ناجح|successful|A1|erfolgreicher|erfolgreichst",
  "erfolglos|غير ناجح|unsuccessful|A2|erfolgloser|erfolglosest",
  "preiswert|رخيص ومناسب|good value|A1|preiswerter|preiswertest",
  "kostspielig|مكلف|costly|A2|kostspieliger|kostspieligst",
  "kostenlos|مجاني|free|A1|-|-",
  "umsonst|مجانا / عبثا|free|A2|-|-",
  "vergeblich|عبثا|in vain|B1|vergeblicher|vergeblichst",
];

/* BIGPHR: premium everyday phrases "de|ar|en|cat|lvl". */
const BIGPHR = [
  "Guten Appetit|شهية طيبة|enjoy your meal|restaurant|A1",
  "Gute Besserung|شفاك الله / بالشفاء|get well soon|health|A1",
  "Viel Glück|حظا سعيدا|good luck|general|A1",
  "Viel Spaß|استمتع بوقتك|have fun|general|A1",
  "Viel Erfolg|بالتوفيق|good success|general|A1",
  "Herzlich willkommen|أهلا وسهلا بك|welcome|general|A1",
  "Schön dich zu sehen|سعيد برؤيتك|nice to see you|relationships|A1",
  "Lange nicht gesehen|لم أرك منذ زمن|long time no see|relationships|A2",
  "Wie geht es dir|كيف حالك|how are you|general|A1",
  "Mir geht es gut|أنا بخير|I'm fine|general|A1",
  "Es freut mich|يسعدني|I'm pleased|general|A2",
  "Kein Problem|لا مشكلة|no problem|general|A1",
  "Macht nichts|لا بأس|never mind|general|A2",
  "Das macht Sinn|هذا منطقي|that makes sense|general|A2",
  "Das stimmt|هذا صحيح|that's right|general|A1",
  "Das stimmt nicht|هذا غير صحيح|that's not right|general|A1",
  "Ich bin mir nicht sicher|لست متأكدا|I'm not sure|general|A2",
  "Ich habe keine Ahnung|ليست لدي فكرة|I have no idea|general|A2",
  "Keine Ahnung|لا فكرة|no idea|general|A1",
  "Mal sehen|لنر|let's see|general|A2",
  "Komm schon|هيا|come on|general|A2",
  "Pass auf|انتبه|watch out|general|A1",
  "Mach dir keine Sorgen|لا تقلق|don't worry|emotions|A2",
  "Alles wird gut|كل شيء سيكون بخيرا|everything will be fine|emotions|A2",
  "Kopf hoch|ارفع رأسك|cheer up|emotions|A2",
  "Bis später|إلى اللقاء لاحقا|see you later|general|A1",
  "Bis morgen|إلى الغد|see you tomorrow|general|A1",
  "Bis bald|أراك قريبا|see you soon|general|A1",
  "Schönes Wochenende|عطلة نهاية أسبوع سعيدة|nice weekend|general|A1",
  "Schönen Tag noch|أتمنى لك يوما سعيدا|have a nice day|general|A1",
  "Gute Nacht|ليلة سعيدة|good night|general|A1",
  "Guten Morgen|صباح الخير|good morning|general|A1",
  "Guten Abend|مساء الخير|good evening|general|A1",
  "Guten Tag|طاب يومك|good day|general|A1",
  "Hallo zusammen|مرحبا بالجميع|hello everyone|general|A1",
  "Entschuldigung|عذرا|excuse me|general|A1",
  "Es tut mir leid|أنا آسف|I'm sorry|general|A1",
  "Kein Ding|لا شيء يذكر|no big deal|colloquial|A2",
  "Alles klar|تمام / واضح|all clear|colloquial|A1",
  "Na klar|بالطبع|of course|colloquial|A2",
  "Na gut|حسنا|all right|colloquial|A2",
  "Na ja|حسنا نوعا ما|well|colloquial|A2",
  "Ach so|آه هكذا|I see|colloquial|A1",
  "Ach nee|حقا؟|oh really|colloquial|A2",
  "Na und|وماذا في ذلك|so what|colloquial|B1",
  "Egal|لا يهم|whatever|colloquial|A2",
  "Stimmt genau|صحيح تماما|exactly right|general|A2",
  "Genau|بالضبط|exactly|general|A1",
  "Ungefähr|تقريبا|approximately|general|A2",
  "Meiner Meinung nach|في رأيي|in my opinion|general|A2",
  "Ich bin der Meinung|أنا أرى|I think|general|A2",
  "Ich finde|أجد / أرى|I find|general|A1",
  "Was meinst du|ما رأيك|what do you think|general|A2",
  "Da hast du recht|أنت محق|you're right|general|A2",
  "Da hast du unrecht|أنت مخطئ|you're wrong|general|A2",
  "Das kommt darauf an|هذا يعتمد|it depends|general|A2",
  "Kommt darauf an|يعتمد|depends|general|A2",
  "Auf jeden Fall|على أي حال / بالتأكيد|in any case|general|A2",
  "Auf keinen Fall|أبدا|no way|general|A2",
  "Zum Beispiel|على سبيل المثال|for example|general|A1",
  "Im Gegenteil|على العكس|on the contrary|general|B1",
  "Im Allgemeinen|بشكل عام|in general|general|B1",
  "Alles in allem|في المجمل|all in all|general|B1",
  "Schritt für Schritt|خطوة بخطوة|step by step|study|A2",
  "Tag für Tag|يوما بعد يوم|day by day|time|A2",
  "Nach und nach|تدريجيا|little by little|general|B1",
  "Hin und wieder|من حين لآخر|now and then|time|A2",
  "Ab und zu|أحيانا|sometimes|time|A1",
  "Hin und her|ذهابا وإيابا|back and forth|general|A2",
  "Auf und ab|صعودا ونزولا|up and down|general|A2",
  "Durch dick und dünn|في السراء والضراء|through thick and thin|relationships|B1",
  "Mit anderen Worten|بكلمات أخرى|in other words|general|B1",
  "Ehrlich gesagt|بصراحة|honestly|general|A2",
  "Um ehrlich zu sein|لأكون صادقا|to be honest|general|B1",
  "Gott sei Dank|الحمد لله|thank goodness|general|A2",
  "Zum Glück|لحسن الحظ|luckily|general|A2",
  "Leider|للأسف|unfortunately|general|A1",
  "Hoffentlich|نأمل|hopefully|general|A2",
  "Wirklich|حقا|really|general|A1",
  "Tatsächlich|في الواقع|actually|general|B1",
  "Plötzlich|فجأة|suddenly|general|A2",
  "Endlich|أخيرا|finally|general|A1",
  "Sofort|فورا|immediately|general|A1",
  "Bald|قريبا|soon|general|A1",
  "Gleich|حالا|right away|general|A1",
  "Später|لاحقا|later|general|A1",
  "Früher|سابقا|earlier|general|A1",
  "Neulich|مؤخرا|recently|general|A2",
  "Kürzlich|حديثا|lately|general|B1",
  "Vor kurzem|منذ وقت قريب|recently|general|A2",
  "Seit kurzem|منذ فترة قصيرة|since recently|general|A2",
  "Bis jetzt|حتى الآن|until now|general|A2",
  "Von nun an|من الآن فصاعدا|from now on|general|B1",
  "Von Zeit zu Zeit|من وقت لآخر|from time to time|time|A2",
  "Pünktlich|في الموعد|on time|general|A1",
  "Zu spät|متأخر|too late|general|A1",
  "Rechtzeitig|في الوقت المناسب|in time|general|A2",
  "Ich habe es eilig|أنا مستعجل|I'm in a hurry|general|A2",
  "Lass dir Zeit|خذ وقتك|take your time|general|A2",
  "Beeil dich|أسرع|hurry up|general|A1",
  "Warte einen Moment|انتظر لحظة|wait a moment|general|A1",
  "Einen Moment bitte|لحظة من فضلك|one moment please|polite|A1",
  "Kommen Sie herein|تفضل بالدخول|come in|polite|A1",
  "Nehmen Sie Platz|تفضل بالجلوس|take a seat|polite|A1",
  "Wie kann ich Ihnen helfen|كيف يمكنني مساعدتك|how can I help you|polite|A2",
  "Womit kann ich dienen|بماذا أخدمك|what can I do for you|polite|B1",
  "Darf ich Sie etwas fragen|هل يمكنني أن أسألك|may I ask you something|polite|A2",
  "Könnten Sie mir helfen|هل يمكنك مساعدتي|could you help me|polite|A2",
  "Wären Sie so nett|هل تتفضل|would you be so kind|polite|B1",
  "Es wäre nett von Ihnen|سيكون لطفا منك|it would be kind of you|polite|B1",
  "Vielen Dank im Voraus|شكرا مقدما|thanks in advance|polite|A2",
  "Ich danke Ihnen|أشكرك|I thank you|polite|A1",
  "Gern geschehen|على الرحب والسعة|you're welcome|polite|A1",
  "Nichts zu danken|لا شكر على واجب|don't mention it|polite|A2",
  "Es war mir ein Vergnügen|كان من دواعي سروري|it was my pleasure|polite|B1",
  "Bis zum nächsten Mal|إلى المرة القادمة|until next time|general|A2",
  "Man sieht sich|سنلتقي|see you around|colloquial|A2",
  "Hau rein|اعتن بنفسك (وداعا)|take care (bye)|colloquial|B1",
  "Mach's gut|اعتن بنفسك|take care|colloquial|A2",
  "Tschüss|وداعا|bye|general|A1",
  "Ciao|تشاو|ciao|colloquial|A1",
  "Servus|مرحبا (جنوب ألمانيا)|hello (southern)|colloquial|A2",
  "Moin|مرحبا (شمال ألمانيا)|hello (northern)|colloquial|A2",
  "Grüß Gott|تحية (جنوب ألمانيا)|greetings (southern)|colloquial|A2",
  "Gute Fahrt|رحلة سعيدة|have a good trip|travel|A1",
  "Guten Flug|رحلة طيران سعيدة|have a good flight|travel|A1",
  "Schöne Ferien|إجازة سعيدة|nice holidays|travel|A1",
  "Erhol dich gut|استرح جيدا|rest well|health|A2",
  "Werd schnell gesund|شفاك الله سريعا|get well soon|health|A1",
  "Gute Besserung|بالشفاء العاجل|get well soon|health|A1",
  "Alles Gute zum Geburtstag|عيد ميلاد سعيد|happy birthday|general|A1",
  "Alles Gute zur Hochzeit|مبارك الزواج|congratulations on wedding|relationships|A2",
  "Herzlichen Glückwunsch|تهانينا الحارة|congratulations|general|A1",
  "Viel Glück bei der Prüfung|بالتوفيق في الامتحان|good luck on exam|study|A1",
  "Du schaffst das|ستنجح في ذلك|you can do it|general|A2",
  "Ich drücke dir die Daumen|أتمنى لك التوفيق|I'll keep my fingers crossed|general|B1",
  "Halte durch|اصمد|hang in there|general|B1",
  "Gib nicht auf|لا تستسلم|don't give up|general|A2",
  "Weiter so|استمر هكذا|keep it up|general|A2",
  "Gut gemacht|أحسنت|well done|general|A1",
  "Nicht schlecht|ليس سيئا|not bad|general|A1",
  "Sehr gut|جيد جدا|very good|general|A1",
  "Das ist toll|هذا رائع|that's great|general|A1",
  "Wie schön|كم هو جميل|how nice|general|A1",
  "Wie interessant|كم هو مثير|how interesting|general|A2",
  "Kein Wunder|لا عجب|no wonder|general|B1",
  "Was für eine Überraschung|يا لها من مفاجأة|what a surprise|general|A2",
  "Das darf nicht wahr sein|هذا لا يصدق|that can't be true|general|B1",
  "Unglaublich|لا يصدق|unbelievable|general|A2",
  "Stell dir vor|تخيل|imagine|general|A2",
  "Hör mal|اسمع|listen|general|A1",
  "Schau mal|انظر|look|general|A1",
  "Komm mal her|تعال هنا|come here|general|A1",
  "Geh weg|اذهب بعيدا|go away|general|A1",
  "Lass mich in Ruhe|اتركني وشأني|leave me alone|general|B1",
  "Das geht dich nichts an|هذا لا يعنيك|none of your business|colloquial|B1",
  "Kümmere dich um deine Sachen|اهتم بشؤونك|mind your business|colloquial|B1",
  "Was soll das|ما هذا|what's that supposed to mean|colloquial|B1",
  "Lass das|توقف عن ذلك|stop that|general|A2",
  "Hör auf damit|توقف عن ذلك|stop it|general|A2",
  "Genug|كفى|enough|general|A1",
  "Schluss damit|انتهى الأمر|that's enough|general|A2",
  "Jetzt reicht es|هذا يكفي الآن|that's enough now|general|B1",
  "Beruhige dich|اهدأ|calm down|emotions|A2",
  "Reg dich nicht auf|لا تنفعل|don't get upset|emotions|B1",
  "Alles halb so wild|الأمر ليس بهذا السوء|it's not that bad|colloquial|B1",
  "Halb so schlimm|ليس سيئا لهذه الدرجة|not that bad|colloquial|B1",
  "Das wird schon|سيكون كل شيء بخير|it'll be fine|general|A2",
  "Keine Sorge|لا تقلق|no worries|general|A1",
  "Schon gut|لا بأس|it's okay|general|A2",
  "Ist schon okay|لا بأس|it's okay|general|A2",
  "Vergiss es|انس الأمر|forget it|general|A2",
  "Lass uns gehen|لنذهب|let's go|general|A1",
  "Gehen wir|لنذهب|let's go|general|A1",
  "Fangen wir an|لنبدأ|let's start|general|A1",
  "Machen wir weiter|لنواصل|let's continue|general|A2",
  "Hören wir auf|لنتوقف|let's stop|general|A2",
  "Passen Sie auf sich auf|اعتن بنفسك|take care of yourself|polite|B1",
  "Ich freue mich für dich|أنا سعيد من أجلك|I'm happy for you|relationships|A2",
  "Es tut mir leid für dich|أنا آسف من أجلك|I'm sorry for you|emotions|A2",
  "Das freut mich zu hören|يسعدني سماع ذلك|glad to hear that|general|A2",
  "Schade|يا للأسف|what a pity|general|A1",
  "Wie schade|يا للأسف|what a shame|general|A1",
  "Zum Glück|لحسن الحظ|luckily|general|A2",
  "Glück gehabt|كنت محظوظا|lucky|colloquial|A2",
  "Pech gehabt|سوء حظ|bad luck|colloquial|A2",
  "So ein Pech|يا لسوء الحظ|what bad luck|colloquial|A2",
  "Was für ein Glück|يا لحسن الحظ|what luck|general|A2",
];

/* BIGCOLL: extra verb+object collocation rows [inf, cat, n]. */
const BIGCOLL = [
  ["putzen", "rooms", 6], ["waschen", "clothing", 6], ["bügeln", "clothing", 5],
  ["kochen", "drinks", 6], ["backen", "food", 8], ["schneiden", "food", 8],
  ["reparieren", "transport", 6], ["waschen", "transport", 5], ["tanken", "transport", 4],
  ["buchen", "hotel", 6], ["stornieren", "travel", 5], ["reservieren", "restaurant", 8],
  ["überweisen", "banking", 5], ["abheben", "money", 5], ["einzahlen", "banking", 5],
  ["beantragen", "documents", 6], ["ausfüllen", "documents", 6], ["unterschreiben", "documents", 6],
  ["besuchen", "city", 6], ["fotografieren", "travel", 5], ["bestaunen", "city", 4],
  ["trainieren", "sports", 8], ["gewinnen", "hobbies", 4], ["verlieren", "sports", 4],
  ["füttern", "animals", 5], ["gassi führen", "animals", 3], ["streicheln", "animals", 4],
  ["gießen", "nature", 5], ["pflanzen", "nature", 5], ["mähen", "home", 4],
  ["lüften", "rooms", 4], ["saugen", "home", 4], ["wischen", "rooms", 4],
  ["stillen", "family", 3], ["wickeln", "family", 3], ["trösten", "emotions", 4],
  ["gratulieren", "relationships", 4], ["einladen", "relationships", 6], ["beschenken", "family", 4],
  ["loben", "school", 4], ["tadeln", "school", 3], ["bestehen", "education", 5],
  ["wiederholen", "study", 5], ["übersetzen", "study", 4], ["nachschlagen", "study", 4],
  ["bedienen", "restaurant", 5], ["kassieren", "shopping", 4], ["beraten", "shopping", 5],
  ["vermieten", "home", 4], ["renovieren", "home", 4], ["tapezieren", "rooms", 3],
  ["parken", "roads", 4], ["abschleppen", "transport", 3], ["anhalten", "roads", 4],
  ["löschen", "computers", 4], ["speichern", "computers", 5], ["installieren", "computers", 4],
  ["aufladen", "phones", 4], ["wegdrücken", "phones", 3], ["zurückrufen", "communication", 4],
  ["verarzten", "health", 4], ["verbinden", "health", 4], ["impfen", "health", 4],
  ["schminken", "routine", 4], ["kämmen", "routine", 3], ["rasieren", "routine", 3],
];

/* BIGPREP: extra prepositional phrases [de, ar, cat]. */
const BIGPREP = [
  ["mit der Familie", "مع العائلة", "family"], ["mit den Kindern", "مع الأطفال", "family"],
  ["bei den Großeltern", "عند الأجداد", "family"], ["bei Freunden", "عند الأصدقاء", "relationships"],
  ["in der Küche", "في المطبخ", "home"], ["im Wohnzimmer", "في غرفة المعيشة", "rooms"],
  ["im Schlafzimmer", "في غرفة النوم", "rooms"], ["im Badezimmer", "في الحمام", "rooms"],
  ["auf dem Balkon", "في الشرفة", "home"], ["im Garten", "في الحديقة", "home"],
  ["im Unterricht", "في الدرس", "school"], ["in der Pause", "في الاستراحة", "school"],
  ["vor der Schule", "أمام المدرسة", "school"], ["nach der Schule", "بعد المدرسة", "school"],
  ["in der Uni", "في الجامعة", "university"], ["in der Vorlesung", "في المحاضرة", "university"],
  ["in der Bibliothek", "في المكتبة", "study"], ["beim Lernen", "أثناء المذاكرة", "study"],
  ["bei der Arbeit", "في العمل", "work"], ["im Meeting", "في الاجتماع", "work"],
  ["nach der Arbeit", "بعد العمل", "work"], ["vor der Arbeit", "قبل العمل", "work"],
  ["im Urlaub", "في الإجازة", "travel"], ["auf Reisen", "في رحلة", "travel"],
  ["am Flughafen", "في المطار", "airport"], ["am Gate", "عند البوابة", "airport"],
  ["im Flugzeug", "في الطائرة", "travel"], ["im Zug", "في القطار", "transport"],
  ["an der Haltestelle", "عند الموقف", "transport"], ["in der U-Bahn", "في المترو", "transport"],
  ["im Stau", "في الازدحام", "roads"], ["an der Ampel", "عند الإشارة", "roads"],
  ["in der Innenstadt", "في وسط المدينة", "city"], ["auf dem Marktplatz", "في ساحة السوق", "city"],
  ["im Einkaufszentrum", "في مركز التسوق", "shopping"], ["an der Kasse", "عند الصندوق", "shopping"],
  ["im Angebot", "في العرض", "shopping"], ["im Schlussverkauf", "في التخفيضات", "shopping"],
  ["im Restaurant", "في المطعم", "restaurant"], ["auf der Speisekarte", "في قائمة الطعام", "restaurant"],
  ["beim Frühstück", "عند الفطور", "food"], ["beim Abendessen", "عند العشاء", "food"],
  ["im Café", "في المقهى", "drinks"], ["an der Bar", "عند البار", "drinks"],
  ["beim Arzt", "عند الطبيب", "doctor"], ["im Wartezimmer", "في غرفة الانتظار", "doctor"],
  ["in der Notaufnahme", "في الطوارئ", "emergency"], ["auf der Station", "في القسم", "hospital"],
  ["bei Regen", "عند المطر", "weather"], ["bei Sonne", "عند الشمس", "weather"],
  ["im Schatten", "في الظل", "weather"], ["in der Sonne", "في الشمس", "weather"],
  ["am Strand", "على الشاطئ", "travel"], ["in den Bergen", "في الجبال", "nature"],
  ["am See", "عند البحيرة", "nature"], ["im Wald", "في الغابة", "nature"],
  ["im Kino", "في السينما", "hobbies"], ["im Konzert", "في الحفل", "hobbies"],
  ["im Stadion", "في الملعب", "sports"], ["auf dem Spielfeld", "في الملعب", "sports"],
  ["im Fitnessstudio", "في صالة اللياقة", "sports"], ["im Schwimmbad", "في المسبح", "sports"],
  ["am Telefon", "على الهاتف", "phones"], ["im Internet", "في الإنترنت", "internet"],
  ["am Computer", "على الحاسوب", "computers"], ["vor dem Bildschirm", "أمام الشاشة", "computers"],
  ["bei der Bank", "عند البنك", "banking"], ["am Geldautomaten", "عند الصراف", "money"],
  ["im Rathaus", "في البلدية", "services"], ["auf dem Amt", "في الدائرة الحكومية", "documents"],
];

/* BIGBASE: base nouns required as heads by BIGCOMP, "de|art|plural|ar|en|cat|lvl".
   Duplicates merge safely via addVocab dedup. */
const BIGBASE = [
  "Papier|das|Papiere|الورق|paper|general|A1",
  "Firma|die|Firmen|الشركة|company|work|A2",
  "Mahlzeit|die|Mahlzeiten|الوجبة|meal|food|A1",
  "Telefon|das|Telefone|الهاتف|telephone|phones|A1",
  "Geschenk|das|Geschenke|الهدية|gift|shopping|A1",
  "Strafe|die|Strafen|العقوبة|punishment|general|A2",
  "Verkehr|der|-|المرور|traffic|transport|A2",
  "Kontrolle|die|Kontrollen|المراقبة|control|documents|A2",
  "Grenze|die|Grenzen|الحدود|border|germany|A2",
  "Unterricht|der|-|الدرس|lesson|school|A1",
  "Studium|das|Studien|الدراسة الجامعية|studies|university|A2",
  "Fahrer|der|Fahrer|السائق|driver|jobs|A1",
  "Fahrerin|die|Fahrerinnen|السائقة|driver (f)|jobs|A1",
  "Kollegin|die|Kolleginnen|الزميلة|colleague (f)|work|A1",
  "Chefin|die|Chefinnen|المديرة|boss (f)|jobs|A2",
  "Ärztin|die|Ärztinnen|الطبيبة|doctor (f)|doctor|A1",
  "Lehrerin|die|Lehrerinnen|المدرسة|teacher (f)|school|A1",
  "Verkäuferin|die|Verkäuferinnen|البائعة|seller (f)|shopping|A1",
  "Datum|das|Daten|التاريخ|date|dates|A1",
  "Ort|der|Orte|المكان|place|city|A1",
  "Futter|das|-|العلف|feed|animals|A2",
  "Tour|die|Touren|الجولة|tour|travel|A2",
  "Ufer|das|Ufer|الضفة|riverbank|nature|A2",
  "Vase|die|Vasen|المزهرية|vase|home|A2",
  "Bogen|der|Bögen|القوس|arc|general|A2",
  "Brei|der|-|المهروس|mash|food|A2",
  "Heim|das|Heime|الدار|care home|home|A2",
  "Maschine|die|Maschinen|الآلة|machine|tech|A2",
  "Mus|das|Muse|المهروس الحلو|sauce|food|A2",
  "Filet|das|Filets|الفيليه|fillet|food|B1",
  "Brust|die|Brüste|الصدر|chest|body|A2",
  "Auflauf|der|Aufläufe|الطاجن|bake|food|B1",
  "Püree|das|Pürees|المهروس|puree|food|B1",
  "Soße|die|Soßen|الصلصة|sauce|food|A2",
  "Mark|das|-|معجون الطماطم|paste|food|B1",
  "Keule|die|Keulen|فخذ الدجاج|drumstick|food|B1",
  "Flügel|der|Flügel|جناح الدجاج|wing|food|B1",
  "Braten|der|-|الشواء|roast|food|A2",
  "Senf|der|-|الخردل|mustard|food|A2",
  "Stange|die|Stangen|العيدان|stick|food|B1",
  "Schwitze|die|-|الرو|roux|food|B1",
  "Likör|der|Liköre|مشروب البيض|eggnog|drinks|B1",
  "Spieß|der|Spieße|السيخ|skewer|food|B1",
  "Brühe|die|-|المرق|broth|food|A2",
  "Stäbchen|das|Stäbchen|أصابع السمك|fish finger|food|A1",
  "Blech|das|Bleche|الصينية|tray|food|A2",
  "Form|die|Formen|القالب|mould|food|A2",
  "Pudding|der|Puddings|البودينغ|pudding|food|A1",
  "Spätzle|die|Spätzle|السباتزل|spaetzle|food|B1",
  "Fondue|das|Fondues|الفوندو|fondue|food|B1",
  "Aufstrich|der|Aufstriche|الدهن|spread|food|B1",
  "Cola|die|Colas|الكولا|cola|drinks|A1",
  "Plastik|das|-|البلاستيك|plastic|general|A1",
  "Bier|das|Biere|البيرة|beer|drinks|A1",
  "Hack|das|-|اللحم المفروم|mince|food|A2",
  "Spielzeug|das|-|اللعبة|toy|hobbies|A1",
  "Bahn|die|Bahnen|السكة|railway|transport|A2",
  "Gebühr|die|Gebühren|الرسوم|fee|services|A2",
  "Roman|der|Romane|الرواية|novel|hobbies|A2",
  "Magazin|das|Magazine|المجلة|magazine|hobbies|A2",
  "Comic|der|Comics|الكوميكس|comic|hobbies|A2",
  "Geräusch|das|Geräusche|الضجيج|noise|general|A2",
  "Ball|der|Bälle|الكرة|ball|sports|A1",
  "Stein|der|Steine|الحجر|stone|nature|A2",
  "Stock|der|Stöcke|العصا|stick|general|A2",
  "Ware|die|Waren|البضاعة|goods|shopping|A2",
];

/* BIGVERBS: common base verbs absent from the base table, "inf|sep|reg|ar|en|cat|lvl|parts".
   Parts verified (strong verbs); weather impersonals included as vocab (never pooled). */
const BIGVERBS = [
  "hören|0|R|يسمع|hear|general|A1|hörte,gehört",
  "nennen|0|R|يسمي|name|general|A2|nannte,genannt",
  "bedienen|0|R|يخدم|serve|restaurant|A2|bediente,bedient",
  "benutzen|0|R|يستخدم|use|general|A1|benutzte,benutzt",
  "beobachten|0|R|يراقب|observe|general|A2|beobachtete,beobachtet",
  "decken|0|R|يغطي|cover|home|A2|deckte,gedeckt",
  "fassen|0|R|يمسك|grasp|general|A2|fasste,gefasst",
  "filmen|0|R|يصور|film|hobbies|A2|filmte,gefilmt",
  "führen|0|R|يقود|lead|general|A2|führte,geführt",
  "füllen|0|R|يملأ|fill|home|A2|füllte,gefüllt",
  "grüßen|0|R|يحيي|greet|general|A1|grüßte,gegrüßt",
  "holen|0|R|يحضر|fetch|general|A1|holte,geholt",
  "kassieren|0|R|يحاسب|charge|shopping|A2|kassierte,kassiert",
  "kontrollieren|0|R|يراقب|check|general|A2|kontrollierte,kontrolliert",
  "laden|0|I|يحمل|load|transport|A2|lud,geladen",
  "lagern|0|R|يخزن|store|work|A2|lagerte,gelagert",
  "leeren|0|R|يفرغ|empty|home|A2|leerte,geleert",
  "liefern|0|R|يوصل|deliver|services|A2|lieferte,geliefert",
  "loben|0|R|يمدح|praise|school|A2|lobte,gelobt",
  "nutzen|0|R|يستخدم|utilize|general|A2|nutzte,genutzt",
  "packen|0|R|يحزم|pack|travel|A1|packte,gepackt",
  "räumen|0|R|يرتب|tidy|home|A2|räumte,geräumt",
  "reinigen|0|R|ينظف|clean|home|A2|reinigte,gereinigt",
  "schützen|0|R|يحمي|protect|general|A2|schützte,geschützt",
  "senden|0|R|يرسل|send|communication|A1|sendete,gesendet",
  "sichern|0|R|يؤمن|secure|general|B1|sicherte,gesichert",
  "stören|0|R|يزعج|disturb|general|A2|störte,gestört",
  "träumen|0|R|يحلم|dream|general|A2|träumte,geträumt",
  "umarmen|0|R|يعانق|hug|relationships|A2|umarmte,umarmt",
  "verwalten|0|R|يدير|manage|work|B1|verwaltete,verwaltet",
  "wecken|0|R|يوقظ|wake|routine|A1|weckte,geweckt",
  "wiegen|0|I|يزن|weigh|general|B1|wog,gewogen",
  "wischen|0|R|يمسح|wipe|home|A1|wischte,gewischt",
  "zählen|0|R|يعد|count|general|A1|zählte,gezählt",
  "frühstücken|0|R|يتناول الفطور|have breakfast|food|A1|frühstückte,gefrühstückt",
  "spazieren|0|R|يتنزه|stroll|hobbies|A1|spazierte,spaziert",
  "bummeln|0|R|يتجول|stroll|city|A2|bummelte,gebummelt",
  "niesen|0|R|يعطس|sneeze|health|A1|nieste,geniest",
  "gähnen|0|R|يتثاءب|yawn|health|A2|gähnte,gegähnt",
  "schnarchen|0|R|يشخر|snore|health|A2|schnarchte,geschnarcht",
  "frieren|0|I|يتجمد|freeze|weather|A2|fror,gefroren",
  "schwitzen|0|R|يتعرق|sweat|health|A2|schwitzte,geschwitzt",
  "zittern|0|R|يرتجف|tremble|health|A2|zitterte,gezittert",
  "strahlen|0|R|يشع|shine|general|A2|strahlte,gestrahlt",
  "glänzen|0|R|يلمع|shine|general|A2|glänzte,geglänzt",
  "schimpfen|0|R|يوبخ|scold|general|A2|schimpfte,geschimpft",
  "zweifeln|0|R|يشك|doubt|general|B1|zweifelte,gezweifelt",
  "zögern|0|R|يتردد|hesitate|general|B1|zögerte,gezögert",
  "eilen|0|R|يسرع|hurry|general|A2|eilte,geeilt",
  "rennen|0|R|يركض|run|sports|A1|rannte,gerannt",
  "klettern|0|R|يتسلق|climb|sports|A2|kletterte,geklettert",
  "stolpern|0|R|يتعثر|stumble|general|A2|stolperte,gestolpert",
  "zurückkehren|1|R|يعود|return|travel|A2|kehrte zurück,zurückgekehrt",
  "grillen|0|R|يشوي|grill|food|A2|grillte,gegrillt",
  "angeln|0|R|يصطاد|fish|hobbies|A2|angelte,geangelt",
  "segeln|0|R|يبحر|sail|travel|B1|segelte,gesegelt",
  "surfen|0|R|يتصفح|surf|internet|A2|surfte,gesurft",
  "tauchen|0|R|يغوص|dive|sports|B1|tauchte,getaucht",
  "bluten|0|R|ينزف|bleed|health|A2|blutete,geblutet",
  "reichen|0|R|يناول|hand|general|A2|reichte,gereicht",
  "verbieten|0|I|يمنع|forbid|general|A2|verbot,verboten",
  "erlauben|0|R|يسمح|allow|general|A2|erlaubte,erlaubt",
  "verzeihen|0|I|يسامح|forgive|general|B1|verzieh,verziehen",
  "borgen|0|R|يقرض|lend|money|B1|borgte,geborgt",
  "brechen|0|I|يكسر|break|general|A2|brach,gebrochen",
  "werfen|0|I|يرمي|throw|sports|A2|warf,geworfen",
  "treten|0|I|يركل|kick|sports|A2|trat,getreten",
  "reiten|0|I|يركب الخيل|ride|sports|B1|ritt,geritten",
  "leiden|0|I|يعاني|suffer|health|B1|litt,gelitten",
  "meiden|0|I|يتجنب|avoid|general|B1|mied,gemieden",
  "kleben|0|R|يلصق|stick|home|A2|klebte,geklebt",
  "baden|0|R|يستحم|bathe|routine|A1|badete,gebadet",
  "jagen|0|R|يصطاد|hunt|nature|B1|jagte,gejagt",
  "klagen|0|R|يشتكي|complain|general|B1|klagte,geklagt",
  "winken|0|R|يلوح|wave|general|A1|winkte,gewinkt",
  "heben|0|R|يرفع|lift|general|A2|hob,gehoben",
  "betrügen|0|R|يغش|cheat|school|B1|betrog,betrogen",
  "hängen|0|I|يعلق|hang|home|A2|hing,gehangen",
  "springen|0|R|يقفز|jump|sports|A1|sprang,gesprungen",
  "regnen|0|R|تمطر|rain|weather|A1|regnete,geregnet",
  "schneien|0|R|تثلج|snow|weather|A1|schneite,geschneit",
  "donnern|0|R|ترعد|thunder|weather|A2|donnerte,gedonnert",
  "blitzen|0|R|تبرق|lightning|weather|A2|blitzte,geblitzt",
  "dämmern|0|R|يخيم الغسق|dawn|weather|B1|dämmerte,gedämmert",
  "hageln|0|R|تمطر بردا|hail|weather|B1|hagelte,gehagelt",
  "verschwinden|0|I|يختفي|disappear|general|B1|verschwand,verschwunden",
  "leben|0|R|يعيش|live|general|A1|lebte,gelebt",
  "heißen|0|R|يسمى|be called|general|A1|hieß,geheißen",
  "danken|0|R|يشكر|thank|general|A1|dankte,gedankt",
  "bringen|0|I|يحضر|bring|general|A1|brachte,gebracht",
  "begleiten|0|R|يرافق|accompany|general|A2|begleitete,begleitet",
  "zeigen|0|R|يري|show|general|A1|zeigte,gezeigt",
  "zahlen|0|R|يدفع|pay|money|A1|zahlte,gezahlt",
  "heiraten|0|R|يتزوج|marry|relationships|A2|heiratete,geheiratet",
  "küssen|0|R|يقبل|kiss|relationships|A2|küsste,geküsst",
  "bewundern|0|R|يعجب بـ|admire|general|B1|bewunderte,bewundert",
  "beneiden|0|R|يحسد|envy|general|B1|beneidete,beneidet",
  "trösten|0|R|يواسي|console|emotions|A2|tröstete,getröstet",
  "bestrafen|0|R|يعاقب|punish|general|B1|bestrafte,bestraft",
  "befördern|0|R|يرقي|promote|work|B1|beförderte,befördert",
  "beschenken|0|R|يهدي|gift|family|A2|beschenkte,beschenkt",
];

module.exports = { MODGEN, QMOD, MODHEADS, BIGCOMP, BIGPREFIX, BIGADJ, BIGPHR, BIGCOLL, BIGPREP, BIGBASE, BIGVERBS };