/* Compounds: [headDe, "mod:ar:en, ..."] — head gender/plural/cat inherited from noun tables.
   All pairs are established real German compounds with hand-written Arabic. */
"use strict";
const COMP=[
["Arzt","Haus:الطبيب العام:GP,Zahn:طبيب الأسنان:dentist,Kinder:طبيب الأطفال:pediatrician,Frauen:طبيب النساء:gynecologist,Haut:طبيب الجلد:dermatologist,Augen:طبيب العيون:eye doctor"],
["Termin","Arzt:موعد الطبيب:doctor appointment,Bank:موعد البنك:bank appointment,Impf:موعد اللقاح:vaccination appointment"],
["Karte","Bank:البطاقة البنكية:bank card,Speise:قائمة الطعام:menu,Fahr:تذكرة السفر:travel ticket,Telefon:بطاقة الهاتف:phone card"],
["Bahnhof","Haupt:المحطة الرئيسية:main station,Bus:محطة الحافلات:bus station"],
["Schein","Führer:رخصة القيادة:driving licence,Geld:الورقة النقدية:banknote,Kranken:قسيمة التأمين الصحي:health insurance voucher"],
["Schule","Grund:المدرسة الابتدائية:primary school,Fahr:مدرسة القيادة:driving school,Sprach:مدرسة اللغة:language school,Musik:مدرسة الموسيقى:music school,Berufs:المدرسة المهنية:vocational school"],
["Kurs","Sprach:دورة اللغة:language course,Deutsch:دورة الألمانية:German course,Tanz:دورة الرقص:dance course,Koch:دورة الطبخ:cooking course"],
["Zimmer","Wohn:غرفة المعيشة:living room,Schlaf:غرفة النوم:bedroom,Kinder:غرفة الأطفال:kids room,Bade:الحمام:bathroom,Hotel:غرفة الفندق:hotel room,Arbeits:غرفة العمل:study"],
["Tür","Haus:باب البيت:front door,Wohnungs:باب الشقة:apartment door,Auto:باب السيارة:car door"],
["Schlüssel","Haus:مفتاح البيت:house key,Auto:مفتاح السيارة:car key,Zimmer:مفتاح الغرفة:room key"],
["Zeugnis","Schul:الشهادة المدرسية:school report,Arbeits:شهادة العمل:job reference,Impf:شهادة اللقاح:vaccination card"],
["Vertrag","Arbeits:عقد العمل:work contract,Miet:عقد الإيجار:rental contract,Kauf:عقد الشراء:purchase contract,Handy:عقد الهاتف:phone contract"],
["Brief","Bewerbungs:خطاب التقديم:application letter,Liebes:رسالة حب:love letter,Kündigungs:خطاب الاستقالة:termination letter"],
["Gespräch","Vorstellungs:مقابلة التعارف:interview,Beratungs:جلسة الاستشارة:consultation,Telefons:مكالمة هاتفية:phone call"],
["Geld","Taschen:مصروف الجيب:pocket money,Trink:البقشيش:tip,Urlaubs:مصروف العطلة:holiday money,Fahr:أجرة المواصلات:fare money"],
["Konto","Bank:الحساب البنكي:bank account,Giro:الحساب الجاري:current account,Spar:حساب التوفير:savings account"],
["Tag","Geburts:يوم الميلاد:birthday,Feier:يوم الاحتفال:holiday,Arbeits:يوم العمل:workday"],
["Essen","Mittag:وجبة الغداء:lunch,Abend:وجبة العشاء:dinner"],
["Wasser","Trink:ماء الشرب:drinking water,Mineral:ماء معدني:mineral water,Leitungs:ماء الصنبور:tap water,Regen:ماء المطر:rainwater"],
["Milch","Kaffee:قهوة بالحليب:milky coffee,Mandel:حليب اللوز:almond milk,Soja:حليب الصويا:soy milk"],
["Brot","Vollkorn:خبز الحبوب الكاملة:wholegrain bread,Weiß:الخبز الأبيض:white bread,Toast:خبز التوست:toast bread"],
["Arbeit","Haus:العمل المنزلي:housework,Teilzeit:العمل الجزئي:part-time work,Vollzeit:العمل الكامل:full-time work,Team:العمل الجماعي:teamwork,Büro:العمل المكتبي:office work"],
["Platz","Park:موقف السيارات:parking space,Spiel:ملعب اللعب:playground,Markt:السوق:marketplace,Sitz:المقعد:seat"],
["Straße","Haupt:الشارع الرئيسي:main street,Bahn:سكة القطار:railway,Einkaufs:شارع التسوق:shopping street"],
["Stadt","Alt:المدينة القديمة:old town,Innen:وسط المدينة:city centre,Heimat:الوطن:home town"],
["Park","Stadt:منتزه المدينة:city park,Tier:حديقة الحيوان:zoo"],
["Markt","Wochen:السوق الأسبوعي:weekly market,Weihnachts:سوق الكريسماس:Christmas market,Floh:سوق البرغوث:flea market"],
["Laden","Bäcker:المخبز:bakery,Fahrrad:محل الدراجات:bike shop,Handy:محل الهواتف:phone shop,Blumen:محل الزهور:flower shop"],
["Preis","Fest:السعر الثابت:fixed price,Miet:سعر الإيجار:rental price"],
["Schuh","Sport:الحذاء الرياضي:sports shoe,Haus:حذاء البيت:slipper,Winter:حذاء الشتاء:winter boot,Lauf:حذاء الجري:running shoe"],
["Hose","Jeans:بنطال الجينز:jeans,Sport:البنطال الرياضي:sports pants,Regen:بنطال المطر:rain pants"],
["Jacke","Regen:سترة المطر:rain jacket,Winter:سترة الشتاء:winter jacket,Leder:سترة الجلد:leather jacket"],
["Tasche","Hand:الحقيبة اليدوية:handbag,Sport:حقيبة الرياضة:sports bag,Schul:الحقيبة المدرسية:school bag,Einkaufs:كيس التسوق:shopping bag"],
["Krankheit","Kinder:مرض الأطفال:childhood illness,Herz:مرض القلب:heart disease,Haut:المرض الجلدي:skin disease"],
["Schmerz","Kopf:صداع الرأس:headache,Bauch:ألم البطن:stomach ache,Zahn:ألم الأسنان:toothache,Rücken:ألم الظهر:back pain,Hals:ألم الحلق:sore throat"],
["Sport","Fußball:كرة القدم:football,Winter:الرياضة الشتوية:winter sport,Wasser:الرياضة المائية:water sport"],
["Spiel","Karten:لعب الورق:card game,Brett:اللعبة اللوحية:board game,Fußball:مباراة الكرة:football match"],
["Film","Kino:فيلم السينما:cinema film,Liebes:فيلم رومانسي:romance film"],
["Buch","Schul:الكتاب المدرسي:school book,Koch:كتاب الطبخ:cookbook,Wörter:القاموس:dictionary,Lehr:الكتاب التعليمي:textbook,Kinder:كتاب الأطفال:children book"],
["Zeitung","Tages:الجريدة اليومية:daily paper,Wand:جريدة الحائط:wall newspaper"],
["Bild","Pass:صورة الجواز:passport photo,Titel:صورة الغلاف:cover picture,Profil:الصورة الشخصية:profile picture"],
["Foto","Pass:صورة الجواز:passport photo,Urlaubs:صورة العطلة:holiday photo,Familien:صورة العائلة:family photo"],
["Rechner","Taschen:الآلة الحاسبة:pocket calculator"],
["Seite","Internet:صفحة الإنترنت:web page,Start:صفحة البداية:start page"],
["Kontakt","Notfall:جهة الطوارئ:emergency contact"],
["Nummer","Telefon:رقم الهاتف:phone number,Notfall:رقم الطوارئ:emergency number,Konto:رقم الحساب:account number,Haus:رقم المبنى:house number"],
["Name","Familien:اسم العائلة:family name,Vor:الاسم الأول:first name,Benutzer:اسم المستخدم:username"],
["Lehrer","Deutsch:معلم الألمانية:German teacher,Mathe:معلم الرياضيات:maths teacher,Sport:معلم الرياضة:sports teacher,Englisch:معلم الإنجليزية:English teacher"],
["Fahrer","Bus:سائق الحافلة:bus driver,Taxi:سائق التاكسي:taxi driver,Zug:سائق القطار:train driver"],
["Flug","Rück:رحلة العودة:return flight,Hin:رحلة الذهاب:outbound flight"],
["Gepäck","Hand:حقيبة اليد:hand luggage,Reise:أمتعة السفر:travel luggage"],
["Sitz","Fenster:مقعد النافذة:window seat,Gang:مقعد الممر:aisle seat"],
["Fahrplan","Bus:جدول الحافلات:bus timetable,Bahn:جدول القطارات:train timetable"],
["Verspätung","Zug:تأخير القطار:train delay,Flug:تأخير الرحلة:flight delay"],
["Fahrschein","Tages:تذكرة اليوم:day ticket,Wochen:التذكرة الأسبوعية:weekly ticket,Monats:التذكرة الشهرية:monthly ticket"],
["Wohnung","Miet:الشقة المستأجرة:rental flat,Ferien:شقة العطلة:holiday flat"],
["Miete","Kalt:الإيجار البارد:base rent,Warm:الإيجار الشامل:warm rent,Monats:الإيجار الشهري:monthly rent"],
["Lärm","Bau:ضجيج البناء:construction noise,Verkehrs:ضجيج المرور:traffic noise"],
["Müll","Haus:القمامة المنزلية:household waste,Rest:البقايا:residual waste,Plastik:البلاستيك:plastic waste"],
["Rechnung","Strom:فاتورة الكهرباء:electricity bill,Telefon:فاتورة الهاتف:phone bill,Arzt:فاتورة الطبيب:doctor bill"],
["Kindergarten","Wald:روضة الغابة:forest kindergarten"],
["Spielplatz","Abenteuer:ملعب المغامرات:adventure playground"],
["Tierarzt","Klein:طبيب الحيوانات الصغيرة:small-animal vet"],
["Krankenkasse","Pflicht:التأمين الإلزامي:statutory insurance,Privat:التأمين الخاص:private insurance"],
["Bewerbung","Job:طلب الوظيفة:job application,Initiativ:التقديم المبادر:speculative application"],
["Kollege","Arbeits:زميل العمل:work colleague,Büro:زميل المكتب:office colleague"],
["Pause","Mittags:استراحة الغداء:lunch break,Kaffee:استراحة القهوة:coffee break"],
["Urlaub","Sommer:العطلة الصيفية:summer holiday,Jahres:الإجازة السنوية:annual leave,Eltern:إجازة الوالدين:parental leave"],
["Feiertag","Weihnachts:عطلة الكريسماس:Christmas holiday,Oster:عطلة الفصح:Easter holiday"],
["Wochenende","Verlängertes:عطلة نهاية أسبوع مطولة:long weekend"],
["Gericht","Lieblings:الطبق المفضل:favourite dish,Tages:طبق اليوم:dish of the day,Fisch:طبق السمك:fish dish"],
["Getränk","Heiß:المشروب الساخن:hot drink,Kalt:المشروب البارد:cold drink"],
["Bestellung","Online:الطلب الإلكتروني:online order,Tisch:طلب الطاولة:table order"],
["Anfrage","Kunden:استفسار العميل:customer enquiry,Preis:الاستفسار عن السعر:price enquiry"],
["Baumarkt","Holz:قسم الأخشاب:timber section"],
["Möbelhaus","Küchen:قسم المطابخ:kitchen section"],
["Fernseher","Flachbild:التلفاز المسطح:flat TV"],
["Steckdose","Wand:مقبس الحائط:wall socket"],
["Regenschirm","Taschen:المظلة الجيبية:pocket umbrella"],
["Gutschein","Geschenk:قسيمة الهدية:gift voucher,Buch:قسيمة الكتب:book voucher"],
["Wartezimmer","Arzt:غرفة انتظار الطبيب:waiting room"],
["Sprechstunde","Arzt:ساعة العيادة:consultation hour"],
["Krankmeldung","Arbeit:الإجازة المرضية:sick note"],
["Attest","Arzt:الشهادة الطبية:medical certificate"],
["Impfpass","Gelber:دفتر اللقاح الأصفر:yellow vaccine booklet"],
["Führerschein","Auto:رخصة السيارة:car licence"],
["Kennzeichen","Auto:لوحة السيارة:number plate,Wunsch:اللوحة المخصصة:personalised plate"],
["Werkstatt","Auto:ورشة السيارات:car workshop,Fahrrad:ورشة الدراجات:bike workshop"],
["Panne","Auto:عطل السيارة:breakdown,Reifen:ثقب الإطار:puncture"],
["Tankstelle","Autobahn:محطة طريق السريع:motorway station"],
["Stau","Verkehrs:الازدحام المروري:traffic jam"],
["Parkplatz","Kunden:موقف العملاء:customer parking,Besucher:موقف الزوار:visitor parking"],
["Parkschein","Tages:تذكرة الموقف اليومية:day parking ticket"],
["Strafzettel","Park:مخالفة الموقف:parking fine"],
["Rathaus","Alt:دار البلدية القديمة:old town hall"],
["Anmeldung","Wohnungs:تسجيل السكن:residence registration,Auto:تسجيل السيارة:car registration"],
["Steuer","Einkommens:ضريبة الدخل:income tax,Mehrwert:ضريبة القيمة المضافة:VAT"],
["Steuererklärung","Einkommens:الإقرار الضريبي:income tax return"],
["Versicherung","Kranken:التأمين الصحي:health insurance,Auto:تأمين السيارة:car insurance,Haftpflicht:تأمين المسؤولية:liability insurance"],
["Beitrag","Mitglieds:اشتراك العضوية:membership fee"],
["Rente","Alters:راتب التقاعد:old-age pension"],
["Prüfungsamt","Uni:مكتب الامتحانات الجامعي:examinations office"],
["Studentenwohnheim","Haupt:السكن الجامعي الرئيسي:main dormitory"],
["Bibliotheksausweis","Studenten:بطاقة مكتبة الطالب:student library card"],
["Hausarbeit","Uni:الواجب الجامعي:term paper"],
["Abschlussarbeit","Bachelor:أطروحة البكالوريوس:bachelor thesis,Master:أطروحة الماجستير:master thesis"],
["Deutschkurs","Intensiv:دورة الألمانية المكثفة:intensive course,Abend:دورة المساء:evening course,Online:الدورة الإلكترونية:online course"],
["Integrationskurs","Deutsch:دورة الاندماج:integration course"],
["Sprachschule","Deutsch:مدرسة اللغة الألمانية:German language school"],
["Sprachprüfung","Telc:امتحان telc:telc exam,Goethe:امتحان غوته:Goethe exam"],
["Zertifikat","Sprach:الشهادة اللغوية:language certificate,Teilnahme:شهادة المشاركة:participation certificate"],
["Vokabelheft","Schul:دفتر المفردات:school vocab book"],
["Wörterbuch","Bild:القاموس المصور:picture dictionary,Online:القاموس الإلكتروني:online dictionary"],
["Lernpartner","Tandem:شريك التاندوم:tandem partner"],
["Nachhilfe","Mathe:درس تقوية الرياضيات:maths tutoring,Deutsch:درس تقوية الألمانية:German tutoring"],
["Klassenarbeit","Mathe:اختبار الرياضيات:maths test,Deutsch:اختبار الألمانية:German test"],
["Stundenplan","Schul:الجدول المدرسي:school timetable"],
["Klassenraum","Neu:الفصل الجديد:new classroom"],
["Schulbus","Gelben:الحافلة المدرسية الصفراء:school bus"],
["Schulranzen","Rote:الحقيبة المدرسية الحمراء:red satchel"]
];
if(typeof module!=="undefined")module.exports={COMP};
