/* Grammar micro-units: TOPIC = [id, deTitle, arTitle, lvl, cat, relatedIds[], UNITS[]]
   UNIT = [focusAr(core rule, 1 line), exDe1, exAr1, exDe2, exAr2, wrongEx, rightEx, whyAr] */
"use strict";
const GT1=[
["g01","Satzbau: Grundwortstellung","ترتيب الجملة الأساسي","A1","syntax",["g02","g06"],[
["الفعل المصرف يأتي في المرتبة الثانية في الجملة الخبرية.","Ich lerne Deutsch.","أنا أتعلم الألمانية.","Er wohnt in Berlin.","هو يسكن في برلين.","Ich Deutsch lerne.","Ich lerne Deutsch.","لأن الفعل الثاني هو عمود الجملة الألمانية."],
["الفاعل غالبًا أولًا ثم الفعل ثم بقية الجملة.","Wir kaufen Brot.","نحن نشتري خبزًا.","Sie trinkt Tee.","هي تشرب شايًا.","Wir Brot kaufen.","Wir kaufen Brot.","الفعل لا يأتي أخيرًا في الجملة الرئيسية."],
["الجملة تبدأ بفعل الأمر عند إعطاء أمر.","Trink Wasser!","اشرب ماءً!","Komm her!","تعال هنا!","Du trink Wasser!","Trink Wasser!","الأمر يحذف الفاعل ويبدأ بالفعل."],
["السؤال بـ هل يبدأ بالفعل المصرف.","Kommst du mit?","هل تأتي معنا؟","Sprichst du Deutsch?","هل تتحدث الألمانية؟","Du kommst mit?","Kommst du mit?","تقديم الفعل يحوّل الخبر إلى سؤال."],
["السؤال بأداة استفهام: أداة ثم فعل ثم فاعل.","Wo wohnst du?","أين تسكن؟","Wann kommt er?","متى يأتي؟","Wo du wohnst?","Wo wohnst du?","الفعل يبقى ثانيًا حتى بعد أداة الاستفهام."],
["الظرف في البداية يقلب الترتيب: فعل ثم فاعل.","Heute lerne ich.","اليوم أتعلم.","Morgen kommt er.","غدًا يأتي.","Heute ich lerne.","Heute lerne ich.","أي عنصر أول يعني الفعل ثانيًا والفاعل ثالثًا."],
["النفي nicht يأتي بعد الفعل أو آخر الجملة.","Ich komme nicht.","أنا لا آتي.","Er arbeitet heute nicht.","هو لا يعمل اليوم.","Ich nicht komme.","Ich komme nicht.","nicht لا تتقدم على الفعل المصرف."],
["kein تنفي الاسم النكرة وتتصرف كأداة.","Ich habe kein Auto.","ليس لدي سيارة.","Das ist kein Problem.","هذه ليست مشكلة.","Ich habe nicht Auto.","Ich habe kein Auto.","kein تحل محل أداة النكرة المنفية."],
["الزمن يأتي قبل المكان في الترتيب المحايد.","Ich fahre morgen nach Berlin.","أسافر غدًا إلى برلين.","Er kommt heute nach Hause.","يأتي اليوم إلى البيت.","Ich fahre nach Berlin morgen.","Ich fahre morgen nach Berlin.","القاعدة الذهبية: time قبل place."],
["الطريقة تأتي قبل المكان والزمن أخيرًا عند التعارض.","Er fährt schnell nach Hause.","يقود بسرعة إلى البيت.","Sie lernt gut in der Schule.","تتعلم جيدًا في المدرسة.","Er fährt nach Hause schnell.","Er fährt schnell nach Hause.","ترتيب te-ka-mo-lo يحفظ الإيقاع الطبيعي."],
["الجملة الفرعية ترسل الفعل المصرف إلى النهاية.","Ich weiß, dass er kommt.","أعرف أنه يأتي.","Weil er krank ist, bleibt er.","لأنه مريض يبقى.","Ich weiß, dass er kommt morgen.","Ich weiß, dass er morgen kommt.","الفرعية = فعل أخير دائمًا."],
["الفعل الثاني (مصدر) يذهب لنهاية الجملة.","Ich will Deutsch lernen.","أريد تعلم الألمانية.","Er kann gut schwimmen.","يستطيع السباحة جيدًا.","Ich will lernen Deutsch.","Ich will Deutsch lernen.","المصدر يستقر في النهاية."],
["الأفعال المنفصلة: المقطع ينفصل لنهاية الجملة.","Ich stehe früh auf.","أنهض مبكرًا.","Er ruft mich an.","يتصل بي.","Ich aufstehe früh.","Ich stehe früh auf.","المقطع المنفصل ساكن في النهاية."],
["المفعول به العاقل يسبق غير العاقل غالبًا.","Ich gebe dem Kind das Buch.","أعطي الطفل الكتاب.","Er zeigt mir das Foto.","يُريني الصورة.","Ich gebe das Buch dem Kind.","Ich gebe dem Kind das Buch.","العاقل (dativ) قبل الشيء (akkusativ)."],
["الضمير المفعول يتقدم على الاسم المفعول.","Ich gebe es dem Kind.","أعطيه للطفل.","Er zeigt sie mir.","يُريها لي.","Ich gebe dem Kind es.","Ich gebe es dem Kind.","الضمير أخف فيتقدم."]]],
["g02","Verbzweitstellung (V2)","الفعل في المرتبة الثانية","A1","syntax",["g01","g06"],[
["كل جملة خبرية رئيسية فعلها ثانيًا مهما طال الأول.","Meine Schwester lernt Medizin.","أختي تدرس الطب.","Jeden Morgen trinke ich Kaffee.","كل صباح أشرب قهوة.","Jeden Morgen ich trinke Kaffee.","Jeden Morgen trinke ich Kaffee.","طول العنصر الأول لا يغيّر مرتبة الفعل."],
["جملتان رئيسيتان تُربطان بفعل ثانٍ في كلتيهما.","Ich koche und er deckt den Tisch.","أطبخ وهو يجهز الطاولة.","Sie lacht und er freut sich.","تضحك وهو يفرح.","Ich koche und er den Tisch deckt.","Ich koche und er deckt den Tisch.","العطف لا يلغي V2 في الجملة الثانية."],
["und/aber/denn لا تحسب ضمن الترتيب.","Aber ich bleibe zu Hause.","لكنني أبقى في البيت.","Denn er ist müde.","لأنه متعب.","Aber bleibe ich zu Hause.","Aber ich bleibe zu Hause.","أدوات العطف خارج الجملة ترتيبيًا."],
["الفعل المساعد يحتل المرتبة الثانية والمصدر أخيرًا.","Ich habe das Buch gelesen.","قرأت الكتاب.","Er wird morgen kommen.","سيأتي غدًا.","Ich gelesen habe das Buch.","Ich habe das Buch gelesen.","المساعد ثانٍ والأساسي أخير."],
["الأفعال الشاذة تحافظ على V2 بتصريفها الخاص.","Er ist heute krank.","هو مريض اليوم.","Wir haben keine Zeit.","ليس لدينا وقت.","Er heute ist krank.","Er ist heute krank.","الشذوذ في التصريف لا في الموقع."],
["النفي والتوكيد لا يكسران V2.","Ich komme heute leider nicht.","للأسف لا آتي اليوم.","Er trinkt nie Alkohol.","لا يشرب الكحول أبدًا.","Heute leider ich komme nicht.","Ich komme heute leider nicht.","الجسيمات تملأ الوسط لا المقدمة."],
["الجملة الشرطية بدون wenn تبدأ بالفعل.","Kommt er, freue ich mich.","إن أتى أفرح.","Regnet es, bleiben wir.","إن مطرت نبقى.","Er kommt, ich freue mich.","Kommt er, freue ich mich.","الشرط الفعلي-الأول يعوّض wenn."],
["التقديم للتوكيد: أي عنصر أولًا والفعل ثابت.","Dich habe ich gestern gesehen.","رأيتك أمس.","In Berlin wohne ich seit 2020.","أسكن في برلين منذ 2020.","Dich ich habe gestern gesehen.","Dich habe ich gestern gesehen.","التقديم توكيد لا كسر للقاعدة."],
["الجملة الاسمية تحتاج فعلًا ظاهرًا دائمًا.","Das Wetter ist schön.","الطقس جميل.","Er ist Lehrer.","هو معلم.","Das Wetter schön.","Das Wetter ist schön.","الألمانية لا تقبل جملة بلا فعل."],
["الاستفهام المنفي يحافظ على تقديم الفعل.","Kommst du nicht mit?","ألا تأتي معنا؟","Hast du kein Geld?","أليس معك مال؟","Du kommst nicht mit?","Kommst du nicht mit?","النفي لا يعيد الفعل للخلف."],
["أدوات الاستفهام المركبة تتصرف كعنصر واحد.","Wie lange bleibst du?","كم ستبقى؟","Um wie viel Uhr kommst du?","في أي ساعة تأتي؟","Wie lange du bleibst?","Wie lange bleibst du?","العبارة الاستفهامية كلها في المرتبة الأولى."],
["الجملة التعجبية تبدأ بالفعل غالبًا.","Bist du aber groß geworden!","لقد كبرت كثيرًا!","Hast du ein schönes Haus!","ما أجمل بيتك!","Du bist aber groß geworden!","Bist du aber groß geworden!","التعجب يستعير بنية السؤال."],
["الفعل في المرتبة الثانية حتى مع الفاعل الطويل.","Der Mann mit dem Hut wartet.","الرجل ذو القبعة ينتظر.","Die Frau aus Ägypten kocht gut.","المرأة المصرية تطبخ جيدًا.","Der Mann mit dem Hut wartet lange schon.","Der Mann mit dem Hut wartet.","الفاعل الطويل كله مرتبة أولى واحدة."],
["في المحكي قد تُكسر القاعدة للتوكيد العاطفي.","Ich — ich weiß nicht.","أنا — لا أعرف.","Morgen — morgen komme ich.","غدًا — سآتي.","قاعدة صارمة بلا استثناء.","القاعدة صارمة كتابيًا ومرنة شفهيًا.","اعرف الكسر لتفهم الأفلام لا لتكتب به."],
["اختبر نفسك: حدد الفعل وتأكد أنه ثانٍ.","Gestern ___ ich krank. (sein)","أمس كنت مريضًا.","Heute ___ wir Pizza. (essen)","اليوم نأكل بيتزا.","Gestern ich war krank.","Gestern war ich krank.","ضع الفعل ثانيًا دائمًا."]]],
["g03","Artikel: der die das","أدوات التعريف","A1","artikel",["g04","g05"],[
["المذكر der: أغلب المهن المذكرة والأيام.","der Mann, der Montag","الرجل، الاثنين.","der Tisch, der Lehrer","الطاولة، المعلم.","die Mann, das Montag","der Mann, der Montag.","احفظ الأداة مع الكلمة دائمًا."],
["المؤنث die: أغلب المهن المؤنثة والأعداد.","die Frau, die Uhr","المرأة، الساعة.","die Schule, die Lampe","المدرسة، المصباح.","der Frau, das Uhr","die Frau, die Uhr.","الجمع كله die — احفظ المفرد."],
["المحايد das: الصغار والحروف والمصادر.","das Kind, das Buch","الطفل، الكتاب.","das Haus, das Mädchen","البيت، الفتاة.","die Kind, der Buch","das Kind, das Buch.","Mädchen محايد رغم المعنى!"],
["لا توجد قاعدة شاملة: الحفظ مع الكلمة.","der Löffel, die Gabel, das Messer","الملعقة والشوكة والسكين.","der Apfel, die Banane, das Brot","التفاح والموز والخبز.","تخمين الأدوات من المعنى.","احفظ ثلاثية: كلمة+أداة+جمع."],
["نهايات تكشف المؤنث: -ung -heit -keit -schaft.","die Wohnung, die Freiheit","الشقة، الحرية.","die Krankheit, die Freundschaft","المرض، الصداقة.","das Wohnung, der Freiheit","die Wohnung, die Freiheit.","النهاية أقوى من التخمين."],
["نهايات المذكر: -er (فاعل) -ismus -ling.","der Lehrer, der Schmetterling","المعلم، الفراشة.","der Tourismus","السياحة.","die Lehrer, das Schmetterling","der Lehrer, der Schmetterling.","قاعدة إحصائية مفيدة جدًا."],
["نهايات المحايد: -chen -lein -ment -um.","das Mädchen, das Museum","الفتاة، المتحف.","das Dokument, das Fräulein","المستند، الآنسة.","die Mädchen, der Museum","das Mädchen, das Museum.","التصغير دائمًا محايد."],
["المركبات تأخذ جنس الكلمة الأخيرة.","die Haustür (die Tür)","باب البيت.","der Bahnhof (der Hof)","محطة القطار.","das Haustür","die Haustür.","انظر لآخر مقطع فقط."],
["الجمع دائمًا die مهما كان المفرد.","die Männer, die Frauen","الرجال، النساء.","die Kinder, die Bücher","الأطفال، الكتب.","der Männer, das Kinder","die Männer, die Kinder.","الجمع يوحد الأداة."],
["أداة النكرة ein/eine تتبع الجنس.","ein Mann, eine Frau, ein Kind","رجل، امرأة، طفل.","ein Tisch, eine Lampe","طاولة، مصباح.","eine Mann, ein Frau","ein Mann, eine Frau.","المحايد والمذكر ein والمؤنث eine."],
["لا أداة مع الأسماء العامة والوجبات غالبًا.","Ich esse Brot.","آكل خبزًا.","Er trinkt Kaffee.","يشرب قهوة.","Ich esse das Brot gern.","Ich esse Brot.","العموم يُسقط الأداة."],
["الدول المذكرة والمؤنثة تأخذ أداة.","die Türkei, die Schweiz","تركيا، سويسرا.","der Irak, der Sudan","العراق، السودان.","Türkei ohne Artikel","die Türkei.","معظم الدول بلا أداة لكن هذه بأداة."],
["الأوقات والوجبات المحددة تأخذ أداة.","am Morgen, in der Nacht","في الصباح، في الليل.","das Frühstück, das Wochenende","الفطور، العطلة.","in Nacht, am Morgen","in der Nacht, am Morgen.","التحديد يستدعي الأداة."],
["الصفات بعد الأداة تتصرف بإعرابها.","der gute Mann","الرجل الطيب.","das kleine Kind","الطفل الصغير.","der gut Mann","der gute Mann.","الأداة تحدد نهاية الصفة."],
["اختبر: اختر الأداة الصحيحة.","___ Wohnung (die)","الشقة.","___ Museum (das)","المتحف.","der Wohnung / das Museum","die Wohnung / das Museum.","احفظ النهايات الدالة."]]],
["g04","Pluralbildung","تكوين الجمع","A1","nomen",["g03","g05"],[
["الجمع بـ -e مع تغير صوتي أحيانًا.","der Tisch → die Tische","الطاولات.","der Stuhl → die Stühle","الكراسي.","die Tischs","die Tische.","لا تضف s إنجليزية أبدًا."],
["الجمع بـ -er غالبًا للمحايد مع Umlaut.","das Buch → die Bücher","الكتب.","das Kind → die Kinder","الأطفال.","die Buchs","die Bücher.","-er جمع ألماني أصيل."],
["الجمع بـ -en/-n للمؤنث غالبًا.","die Frau → die Frauen","النساء.","die Tür → die Türen","الأبواب.","die Fraus","die Frauen.","المؤنث يحب -n."],
["جمع بـ -s للكلمات الدخيلة الحديثة.","das Handy → die Handys","الهواتف.","das Hotel → die Hotels","الفنادق.","die Handyen","die Handys.","الدخيل يحتفظ بـ -s."],
["جمع بلا تغيير: كثير من -er المذكر.","der Lehrer → die Lehrer","المعلمون.","der Fahrer → die Fahrer","السائقون.","die Lehrers","die Lehrer.","الفاعل -er لا يتغير."],
["الجمع الشاذ يُحفظ ولا يُقاس عليه.","der Mann → die Männer","الرجال.","die Mutter → die Mütter","الأمهات.","die Manns","die Männer.","الشواذ قليلة ومحدودة."],
["كلمات بلا جمع: مواد ومجردات.","das Wasser, die Milch","الماء، الحليب.","das Geld, die Liebe","المال، الحب.","die Wässer (عام)","بلا جمع في الاستعمال العام."],
["كلمات جمع دائم: Eltern, Leute, Ferien.","Meine Eltern kommen.","والداي يأتيان.","Die Leute sind nett.","الناس لطفاء.","Mein Eltern kommt.","Meine Eltern kommen.","فعلها جمع دائمًا."],
["Umlaut وحده يجمع بعض الكلمات.","der Vater → die Väter","الآباء.","der Bruder → die Brüder","الإخوة.","die Vaters","die Väter.","التغير الصوتي جمع كافٍ."],
["المركبات تجمع كلمتها الأخيرة فقط.","der Bahnhof → die Bahnhöfe","المحطات.","die Haustür → die Haustüren","الأبواب.","die Bahnhofs","die Bahnhöfe.","اجمع الرأس فقط."],
["جمع المهن المؤنثة بـ -nen.","die Lehrerin → die Lehrerinnen","المعلمات.","die Ärztin → die Ärztinnen","الطبيبات.","die Lehrerins","die Lehrerinnen.","مضاعفة النون إلزامية."],
["الأرقام والمقادير بعد العدد مفردة.","zwei Kilo Brot","كيلوان من الخبز.","drei Glas Wasser","ثلاثة أكواب ماء.","zwei Kilos","zwei Kilo.","المقدار لا يُجمع بعد العدد."],
["صيغة الجمع تُحفظ مع الأداة.","das Brot, die Brote","الخبز.","der Zug, die Züge","القطار.","حفظ المفرد وحده ناقص.","احفظ: مفرد+أداة+جمع."],
["الجمع في الجملة: الفعل جمع.","Die Kinder spielen.","الأطفال يلعبون.","Die Bücher sind neu.","الكتب جديدة.","Die Kinder spielt.","Die Kinder spielen.","الفعل يطابق الجمع."],
["اختبر: اجمع الكلمات.","Frau→Frauen, Buch→?","المرأة، الكتاب.","Mann→Männer, Kind→?","الرجل، الطفل.","Fraus, Buchs","Frauen, Bücher.","تدرّب على الأنماط الخمسة."]]],
["g05","Nominativ","حالة الرفع","A1","kasus",["g03","g07"],[
["الفاعل دائمًا في الرفع.","Der Mann liest.","الرجل يقرأ.","Die Frau kocht.","المرأة تطبخ.","Den Mann liest.","Der Mann liest.","الفاعل = nominativ."],
["أدوات الرفع: der die das die.","der Vater, die Mutter","الأب، الأم.","das Kind, die Kinder","الطفل، الأطفال.","den Vater, der Mutter","der Vater, die Mutter.","احفظ جدول الرفع أولًا."],
["sein/werden/bleiben تتبعها رفع لا نصب.","Er ist Lehrer.","هو معلم.","Sie wird Ärztin.","ستصبح طبيبة.","Er ist Lehrer (Akk).","Er ist Lehrer (Nom).","المسند بعد sein مرفوع."],
["ein/eine في الرفع للمبتدأ النكرة.","Ein Mann wartet.","رجل ينتظر.","Eine Frau singt.","امرأة تغني.","Einen Mann wartet.","Ein Mann wartet.","الفاعل النكرة بـ ein."],
["الصفات في الرفع بعد ein تتغير.","Ein guter Mann hilft.","رجل طيب يساعد.","Eine nette Frau lacht.","امرأة لطيفة تضحك.","Ein gut Mann hilft.","Ein guter Mann hilft.","النهاية -er/-e في الرفع."],
["الضمائر المرفوعة: ich du er...","Ich lerne, du spielst.","أتعلم، أنت تلعب.","Er kommt, wir gehen.","يأتي، نذهب.","Mich lerne.","Ich lerne.","الفاعل ضمير رفع."],
["السؤال: Wer/Was + فعل.","Wer kommt heute?","من يأتي اليوم؟","Was ist das?","ما هذا؟","Wen kommt heute?","Wer kommt heute?","wer للفاعل العاقل."],
["المنادى والخبر المبتدأ رفع.","Hallo, Ahmed!","مرحبًا أحمد!","Das ist mein Bruder.","هذا أخي.","Hallo, Ahmeds!","Hallo, Ahmed!","الاسم المستقل مرفوع."],
["الجمع المرفوع أداته die دائمًا.","Die Männer arbeiten.","الرجال يعملون.","Die Frauen lachen.","النساء يضحكن.","Der Männer arbeiten.","Die Männer arbeiten.","الجمع يوحد الأداة."],
["الاسم بعد als في المقارنة رفع غالبًا.","Er ist größer als ich.","هو أطول مني.","Sie ist älter als er.","هي أكبر منه.","als mich","als ich.","المقارن به مرفوع بعد als."],
["العطف على الفاعل يبقى رفعًا.","Mein Bruder und ich spielen.","أخي وأنا نلعب.","Du und er kommt.","أنت وهو تأتيان.","Mich und er.","Mein Bruder und ich.","المعطوف يشارك الحالة."],
["الأعداد والكميات المبتدأ رفع.","Viele Leute warten.","كثيرون ينتظرون.","Zwei Kinder spielen.","طفلان يلعبان.","Viele Leute wartet.","Viele Leute warten.","الكمية الفاعلة مرفوعة."],
["المصدر الفاعل محايد مرفوع.","Rauchen ist ungesund.","التدخين غير صحي.","Lesen macht Spaß.","القراءة ممتعة.","Rauchen ungesund.","Rauchen ist ungesund.","المصدر اسم محايد."],
["الأسماء بعد es ist رفع.","Es ist ein Fehler.","إنه خطأ.","Es ist meine Schuld.","إنه خطئي.","Es ist einen Fehler.","Es ist ein Fehler.","المسند بعد sein رفع."],
["اختبر: حدد الفاعل وحالته.","___ Mann liest. (der)","الرجل يقرأ.","___ Frau kocht. (die)","المرأة تطبخ.","Den / Der","Der / Die.","الفاعل رفع دائمًا."]]],
["g06","W-Fragen","أدوات الاستفهام","A1","syntax",["g01","g02"],[
["wer للعاقل الفاعل.","Wer ist das?","من هذا؟","Wer kommt mit?","من يأتي معنا؟","Wen ist das?","Wer ist das?","wer = الفاعل العاقل."],
["wen للعاقل المفعول.","Wen siehst du?","من ترى؟","Wen rufst du an?","من تتصل به؟","Wer siehst du?","Wen siehst du?","المفعول العاقل wen."],
["wem للعاقل غير المباشر.","Wem hilfst du?","من تساعد؟","Wem gehört das?","لمن هذا؟","Wen hilfst du?","Wem hilfst du?","dativ العاقل wem."],
["was لغير العاقل والمعنى.","Was ist das?","ما هذا؟","Was machst du?","ماذا تفعل؟","Wer ist das? (لشيء)","Was ist das?","غير العاقل was."],
["wo للمكان الساكن.","Wo wohnst du?","أين تسكن؟","Wo ist der Bahnhof?","أين المحطة؟","Wohin wohnst du?","Wo wohnst du?","السكون wo والحركة wohin."],
["woher للأصل وwohin للوجهة.","Woher kommst du?","من أين أنت؟","Wohin gehst du?","إلى أين تذهب؟","Wo gehst du hin? (مقبول)","Wohin gehst du?","الاتجاه her/hin يحدد المعنى."],
["wann للزمن.","Wann kommst du?","متى تأتي؟","Wann beginnt der Kurs?","متى تبدأ الدورة؟","Wenn kommst du?","Wann kommst du?","wann سؤال، wenn رابط."],
["warum/wieso للسبب.","Warum weinst du?","لماذا تبكي؟","Wieso bist du spät?","لم تأخرت؟","Warum du weinst?","Warum weinst du?","الفعل ثانٍ بعدها."],
["wie للكيفية والحال.","Wie geht es dir?","كيف حالك؟","Wie heißt du?","ما اسمك؟","Was geht es dir?","Wie geht es dir?","الحال wie."],
["wie viel للكمية.","Wie viel kostet das?","كم سعره؟","Wie viele Kinder hast du?","كم طفلًا لديك؟","Wie viel Kinder?","Wie viele Kinder?","المعدود viel-e."],
["welch للاختيار المحدد.","Welcher Tag ist heute?","أي يوم اليوم؟","Welche Farbe magst du?","أي لون تحب؟","Was Tag?","Welcher Tag?","welch تتصرف كأداة."],
["was für للوصف والنوع.","Was für ein Auto hast du?","أي نوع سيارة لديك؟","Was für Musik hörst du?","أي موسيقى تسمع؟","Welches für Auto?","Was für ein Auto?","النوع was für."],
["أداة الاستفهام مرتبة أولى والفعل ثانٍ.","Woher kommst du?","من أين أنت؟","Seit wann lernst du?","منذ متى تتعلم؟","Woher du kommst?","Woher kommst du?","V2 حتى في السؤال."],
["السؤال المنفي بـ nicht/kein.","Warum kommst du nicht?","لماذا لا تأتي؟","Hast du keine Zeit?","أليس لديك وقت؟","Warum du nicht kommst?","Warum kommst du nicht?","النفي لا يكسر V2."],
["اختبر: أكمل بالأداة.","___ wohnst du? (Wo)","أين تسكن؟","___ kostet das? (Wie viel)","كم سعره؟","Wohin / Was","Wo / Wie viel.","فرّق wo/wohin."]]],
["g07","Akkusativ","حالة النصب","A1","kasus",["g05","g08"],[
["المفعول المباشر منصوب.","Ich sehe den Mann.","أرى الرجل.","Er kauft das Brot.","يشتري الخبز.","Ich sehe der Mann.","Ich sehe den Mann.","der تتحول إلى den."],
["التغير فقط في المذكر المفرد.","Ich sehe den Hund.","أرى الكلب.","Ich sehe die Katze.","أرى القطة.","Ich sehe der Hund.","Ich sehe den Hund.","die/das ثابتة."],
["ein تتحول إلى einen للمذكر.","Ich habe einen Bruder.","لدي أخ.","Ich sehe einen Film.","أشاهد فيلمًا.","Ich habe ein Bruder.","Ich habe einen Bruder.","النكرة تتبع المعرفة."],
["الضمائر: mich dich ihn...","Ich sehe dich.","أراك.","Er liebt sie.","يحبها.","Ich sehe du.","Ich sehe dich.","احفظ ضمائر النصب."],
["الأفعال المتعدية تحتاج نصبًا.","Ich esse einen Apfel.","آكل تفاحة.","Sie trinkt einen Saft.","تشرب عصيرًا.","Ich esse ein Apfel.","Ich esse einen Apfel.","الفعل يطلب المفعول."],
["حروف النصب: durch für gegen ohne um.","Das ist für dich.","هذا لك.","Wir gehen ohne ihn.","نذهب بدونه.","Das ist für dir.","Das ist für dich.","هذه الحروف نصب دائم."],
["الاتجاه بعد حرفي الاتجاه نصب.","Ich gehe in die Schule.","أذهب إلى المدرسة.","Er stellt das Glas auf den Tisch.","يضع الكوب على الطاولة.","in der Schule (حركة)","in die Schule.","الحركة نصب والسكون dativ."],
["الزمن المحدد بلا حرف نصب.","Ich bleibe einen Monat.","أبقى شهرًا.","Er arbeitet jede Woche.","يعمل كل أسبوع.","einem Monat","einen Monat.","المدة الزمنية منصوبة."],
["المنادى المفعول بعد wen.","Wen siehst du? — Den Lehrer.","من ترى؟ — المعلم.","Wen rufst du an? — Meinen Freund.","بمن تتصل؟ — صديقي.","Der Lehrer.","Den Lehrer.","الإجابة تطابق السؤال."],
["الصفات في النصب: guten Mann.","Ich sehe den guten Mann.","أرى الرجل الطيب.","Er trinkt kalten Tee.","يشرب شايًا باردًا.","den gut Mann","den guten Mann.","النهاية -en غالبًا."],
["مكان العمل والوجهة نصب بعد zu? لا!","Ich gehe zum Arzt.","أذهب للطبيب.","Er fährt nach Berlin.","يسافر لبرلين.","Ich gehe zu den Arzt.","Ich gehe zum Arzt.","zu دائمًا dativ — احذر."],
["الأفعال الانعكاسية نصب غالبًا.","Ich wasche mich.","أغتسل.","Er setzt sich.","يجلس.","Ich wasche mir (خطأ هنا).","Ich wasche mich.","المعتاد akk إلا مع مفعول ثانٍ."],
["الجملة المزدوجة المفعول: شخص dativ.","Ich gebe dir das Buch.","أعطيك الكتاب.","Er zeigt mir das Foto.","يُريني الصورة.","Ich gebe dich das Buch.","Ich gebe dir das Buch.","الشخص dativ والشيء akk."],
["النفي: keinen/keine.","Ich habe keinen Hunger.","لست جائعًا.","Er hat keine Zeit.","ليس لديه وقت.","Ich habe kein Hunger.","Ich habe keinen Hunger.","kein تتصرف كـ ein."],
["اختبر: ضع الأداة.","Ich sehe ___ Mann. (den)","أرى الرجل.","Für ___ (mich).","لأجلي.","der / mir","den / mich.","المذكر يتغير."]]],
["g08","Dativ","حالة الجر (غير المباشر)","A1","kasus",["g07","g09"],[
["المفعول غير المباشر dativ.","Ich gebe dir das Buch.","أعطيك الكتاب.","Er hilft mir.","يساعدني.","Ich gebe dich.","Ich gebe dir.","الشخص المستفيد dativ."],
["أدوات الجر: dem der dem den+n.","dem Mann, der Frau","للرجل، للمرأة.","dem Kind, den Kindern","للطفل، للأطفال.","den Mann, die Frau","dem Mann, der Frau.","احفظ الصف كاملًا."],
["einem/einer في النكرة.","Ich helfe einem Kind.","أساعد طفلًا.","Sie dankt einer Frau.","تشكر امرأة.","Ich helfe ein Kind.","Ich helfe einem Kind.","النكرة تتصرف أيضًا."],
["أفعال dativ خالصة: helfen danken...","Er hilft dem Kind.","يساعد الطفل.","Das gehört mir.","هذا يخصني.","Er hilft den Kind.","Er hilft dem Kind.","احفظ قائمة أفعال الـdativ."],
["gefallen schmecken passen + dativ.","Das gefällt mir.","هذا يعجبني.","Die Suppe schmeckt mir.","تعجبني الشوربة.","Das gefällt mich.","Das gefällt mir.","الإعجاب dativ دائمًا."],
["حروف الجر dativ: mit bei seit...","Ich fahre mit dem Bus.","أركب الحافلة.","Er wohnt bei seinen Eltern.","يسكن عند والديه.","mit den Bus","mit dem Bus.","احفظ: mit nach bei seit von zu aus."],
["السكون بعد حرفي الاتجاه dativ.","Ich bin in der Schule.","أنا في المدرسة.","Das Glas steht auf dem Tisch.","الكوب على الطاولة.","in die Schule (سكون)","in der Schule.","السكون dativ والحركة akk."],
["الضمائر: mir dir ihm ihr...","Hilf mir bitte!","ساعدني من فضلك!","Ich danke Ihnen.","أشكرك.","Hilf mich!","Hilf mir!","الضمير يتبع الفعل."],
["السؤال بـ wem.","Wem hilfst du?","من تساعد؟","Wem gehört das Auto?","لمن هذه السيارة؟","Wen hilfst du?","Wem hilfst du?","wem = dativ العاقل."],
["الصفات في الجر: -en غالبًا.","mit dem neuen Auto","بالسيارة الجديدة.","bei guter Laune","بمزاج جيد.","mit dem neue Auto","mit dem neuen Auto.","النهاية -en تحكم."],
["الجمع dativ يضيف n.","mit den Kindern","مع الأطفال.","von den Freunden","من الأصدقاء.","mit den Kinder","mit den Kindern.","الجمع -n إلا ما انتهى بـ n/s."],
["الأفعال ذات المفعولين: الترتيب.","Ich schenke meiner Mutter Blumen.","أهدي أمي ورودًا.","Er zeigt seinem Freund das Haus.","يُري صديقه البيت.","Ich schenke Blumen meiner Mutter.","الأشخاص أولًا: dativ قبل akk."],
["الانعكاسي dativ مع مفعول ثانٍ.","Ich wasche mir die Hände.","أغسل يديّ.","Er kauft sich ein Auto.","يشتري لنفسه سيارة.","Ich wasche mich die Hände.","Ich wasche mir die Hände.","وجود مفعول ثانٍ يحوّل الانعكاسي dativ."],
["الأسماء بعد zu دائمًا dativ.","zum Arzt, zur Schule","للطبيب، للمدرسة.","zum Bahnhof, zur Arbeit","للمحطة، للعمل.","zu den Arzt","zum Arzt.","zu + dem = zum."],
["اختبر: اختر الحالة.","Ich helfe ___ (dem Mann).","أساعد الرجل.","mit ___ (der Frau).","مع المرأة.","den / die","dem / der.","احفظ أفعال وحروف الـdativ."]]],
["g09","Genitiv","حالة الإضافة","A2","kasus",["g08","g10"],[
["الملكية الرسمية بالـgenitiv.","das Auto des Mannes","سيارة الرجل.","die Tasche der Frau","حقيبة المرأة.","das Auto von dem Mann (عامية)","das Auto des Mannes.","الكتابي genitiv والمحكي von+dativ."],
["أدوات الإضافة: des der des der.","des Vaters, der Mutter","والد الأب، والدة الأم.","des Kindes, der Kinder","طفل الأطفال.","dem Vaters","des Vaters.","المذكر والمحايد des + s."],
["الأسماء المذكرة تضيف s/es.","des Freundes, des Hauses","الصديق، البيت.","des Lehrers, des Buches","المعلم، الكتاب.","des Freund","des Freundes.","النهاية -(e)s إلزامية."],
["الأعلام تضيف s بلا أداة.","Ahmeds Auto ist neu.","سيارة أحمد جديدة.","Marias Tasche ist rot.","حقيبة ماريا حمراء.","Ahmeds sein Auto","Ahmeds Auto.","اسم العلم + s."],
["حروف الإضافة: wegen trotz während.","wegen des Regens","بسبب المطر.","trotz des Sturms","رغم العاصفة.","wegen dem Regen (عامية)","wegen des Regens.","الرسمي genitiv والعامي dativ."],
["الصفات في الإضافة: -en.","trotz des starken Regens","رغم المطر الشديد.","wegen guter Freunde","بسبب أصدقاء جيدين.","des starke Regens","des starken Regens.","النهاية -en."],
["الزمن بالإضافة: eines Tages.","Eines Tages kam er.","ذات يوم أتى.","Eines Morgens sah ich ihn.","ذات صباح رأيته.","Einem Tag","Eines Tages.","صيغ زمنية محفوظة."],
["von+dativ بديل المحكي.","das Auto von meinem Vater","سيارة والدي.","die Meinung von vielen","رأي الكثيرين.","مقبول شفهيًا.","مقبول شفهيًا.","افهم البديل واستعمل الأصلي كتابيًا."],
["الأسماء المؤنثة بلا نهاية.","die Farbe der Tür","لون الباب.","die Meinung der Ärztin","رأي الطبيبة.","der Türs","der Tür.","المؤنث والجمع بلا s."],
["الجمع بالإضافة: der Kinder.","das Spiel der Kinder","لعب الأطفال.","die Zukunft der Welt","مستقبل العالم.","den Kinder","der Kinder.","الجمع der."],
["التحية الرسمية بالإضافة.","Sehr geehrte Damen und Herren","سيداتي سادتي.","Guten Appetit!","بالهناء!","صيغ محفوظة.","صيغ محفوظة.","احفظ قوالب الرسائل."],
["البدل الإضافي (Apposition) يطابق.","Herr Müller, der Lehrer, kommt.","السيد مولر المعلم يأتي.","Berlin, die Hauptstadt, ist schön.","برلين العاصمة جميلة.","تابع مرفوع/منصوب حسب المتبوع.","يطابق حالة المتبوع.","البدل يشارك الحالة."],
["الأعداد الترتيبية بالإضافة.","der erste des Monats","أول الشهر.","der letzte des Jahres","آخر السنة.","der erste vom Monat","der erste des Monats.","صيغ رسمية محفوظة."],
["الأسماء الضعيفة (n-Deklination).","den Studenten, des Studenten","الطالب.","den Kollegen, des Kollegen","الزميل.","des Student","des Studenten.","فئة تنتهي بـ -n في كل الحالات."],
["اختبر: أكمل الإضافة.","das Buch ___ (des Lehrers).","كتاب المعلم.","wegen ___ (des Wetters).","بسبب الطقس.","dem Lehrer / dem Wetter","des Lehrers / des Wetters.","المذكر des + s."]]],
["g10","Personalpronomen","الضمائر الشخصية","A1","pronomen",["g07","g11"],[
["ضمائر الرفع الأساسية.","Ich lerne Deutsch.","أتعلم الألمانية.","Du sprichst gut.","تتحدث جيدًا.","Mich lerne.","Ich lerne.","الفاعل رفع."],
["ضمائر النصب.","Ich sehe dich.","أراك.","Er liebt sie.","يحبها.","Ich sehe du.","Ich sehe dich.","المفعول المباشر نصب."],
["ضمائر الجر.","Hilf mir!","ساعدني!","Das gehört uns.","هذا لنا.","Hilf mich!","Hilf mir!","المستفيد جر."],
["Sie الرسمية كبيرة دائمًا.","Kommen Sie mit?","هل تأتي معنا؟","Ich danke Ihnen.","أشكرك.","kommen sie mit? (رسمي)","Kommen Sie mit?","الحرف الكبير يفرّق المعنى."],
["es للأشياء والحيوانات والمجهول.","Es regnet.","إنها تمطر.","Es ist spät.","الوقت متأخر.","Er regnet.","Es regnet.","الطقس es دائمًا."],
["man للعموم.","Man spricht hier Deutsch.","هنا يُتحدث بالألمانية.","Man darf nicht rauchen.","ممنوع التدخين.","Menschen spricht.","Man spricht.","الفعل مفرد بعد man."],
["الضمير يطابق الجنس النحوي لا المعنى.","Das Mädchen spielt. Es lacht.","الفتاة تلعب. تضحك.","Das Baby weint. Es hat Hunger.","الرضيع يبكي. جائع.","Sie lacht (لـMädchen).","Es lacht.","الجنس النحوي يحكم."],
["ترتيب الضميرين: نصب قبل جر.","Ich gebe es dir.","أعطيه لك.","Er zeigt sie mir.","يُريها لي.","Ich gebe dir es.","Ich gebe es dir.","akk قبل dativ عند الضميرين."],
["الضمير الانعكاسي للغائب sich.","Er wäscht sich.","يغتسل.","Sie treffen sich.","يلتقيان.","Er wäscht ihn.","Er wäscht sich.","الغائب انعكاسيه sich."],
["حذف الضمير في الأمر.","Komm her!","تعال!","Trink das!","اشرب هذا!","Du komm her!","Komm her!","الأمر بلا فاعل ظاهر."],
["الضمير في الجملة الفرعية.","Ich weiß, dass er kommt.","أعرف أنه يأتي.","Obwohl sie müde ist, lacht sie.","رغم تعبها تضحك.","dass kommt er.","dass er kommt.","الترتيب يتغير لا الضمير."],
["التوكيد بالضمير المنفصل.","Ich selbst mache das.","أفعل هذا بنفسي.","Du selbst weißt es.","أنت نفسك تعرف.","Ich selber (عامية مقبولة).","Ich selbst.","selbst توكيد رسمي."],
["الضمائر مع حروف الجر.","für mich, mit dir","لأجلي، معك.","bei uns, ohne euch","عندنا، بدونكم.","für ich, mit du","für mich, mit dir.","الحرف يحدد حالة الضمير."],
["الفرق er/sie/es وder/die/das.","Er (شخص) vs der (إشارة).","هو مقابل هذا.","Kennst du ihn?","هل تعرفه؟","der = إشارة.","er = شخص غالبًا.","السياق يفرّق."],
["اختبر: اختر الضمير.","Ich sehe ___ (dich).","أراك.","Hilf ___ (mir).","ساعدني.","du / mich","dich / mir.","الفعل يحدد الحالة."]]],
["g11","Possessivpronomen","ضمائر الملكية","A1","pronomen",["g10","g12"],[
["mein/dein/sein تتصرف كـ ein.","mein Bruder, meine Schwester","أخي، أختي.","sein Auto, ihr Buch","سيارته، كتابها.","meine Bruder","mein Bruder.","الجنس والعدد يحددان النهاية."],
["النصب المذكر: meinen/deinen.","Ich sehe meinen Vater.","أرى والدي.","Er liebt seinen Job.","يحب عمله.","Ich sehe mein Vater.","Ich sehe meinen Vater.","المذكر المفرد -en."],
["الجر: meinem/meiner.","mit meinem Auto","بسيارتي.","bei meiner Freundin","عند صديقتي.","mit mein Auto","mit meinem Auto.","الجر -em/-er."],
["seine (ملكه) vs ihre (ملكها/ملكهم).","Sein Auto ist neu.","سيارته جديدة.","Ihr Auto ist neu.","سيارتها جديدة.","التباس شائع.","انتبه للمرجع: من المالك؟"],
["unser/euer بلا e زائدة غالبًا.","unser Haus, eure Wohnung","بيتنا، شقتكم.","unsere Kinder","أطفالنا.","unsere Haus","unser Haus.","الجنس يحكم لا العادة."],
["الملكية المستقلة: meiner/meine.","Das Buch ist meins.","الكتاب لي.","Die Tasche ist meine.","الحقيبة لي.","Das Buch ist mein.","Das Buch ist meins.","المسند بصيغة مستقلة."],
["الملكية بعد sein مسند رفع.","Das ist mein Bruder.","هذا أخي.","Das sind meine Eltern.","هؤلاء والداي.","Das ist meinen Bruder.","Das ist mein Bruder.","المسند رفع."],
["النفي: kein يطابق الملكية عكسًا.","Das ist nicht mein Buch.","هذا ليس كتابي.","Das ist kein Buch.","هذا ليس كتابًا.","Das ist kein mein Buch.","Das ist nicht mein Buch.","nicht للمعين وkein للنكرة."],
["الملكية مع الجمع: meine Freunde.","meine Freunde, deine Bücher","أصدقائي، كتبك.","seine Eltern","والداه.","mein Freunde","meine Freunde.","الجمع -e."],
["الاحترام: Ihr groß.","Ist das Ihr Gepäck?","هل هذه أمتعتك؟","Ihre Tasche ist schön.","حقيبتك جميلة.","ist das ihr Gepäck?","Ist das Ihr Gepäck?","الرسمي كبير."],
["الملكية والصفات معًا.","mein neues Auto","سيارتي الجديدة.","seine kleine Schwester","أخته الصغيرة.","mein neue Auto","mein neues Auto.","النهاية على الصفة."],
["الملكية في العناوين.","Liebe Anna, lieber Ahmed","عزيزتي آنا، عزيزي أحمد.","المنادى يطابق جنس المخاطب.","liebe Ahmed","lieber Ahmed.","المنادى مذكر -er."],
["von + ملكية بديل المحكي.","das Auto von mir","سيارتي.","ein Freund von dir","صديق لك.","مقبول شفهيًا.","مقبول شفهيًا.","الكتابي ملكية مباشرة."],
["الملكية المنعكسة: sich sein? لا.","Er wäscht sein Auto.","يغسل سيارته.","Sie kämmt ihre Haare.","تمشط شعرها.","Er wäscht sich sein Auto.","Er wäscht sein Auto.","الملكية تكفي بلا انعكاسي."],
["اختبر: أكمل.","Das ist ___ (mein) Bruder.","هذا أخي.","Ich sehe ___ (meinen) Vater.","أرى والدي.","meinen / mein","mein / meinen.","الفاعل رفع والمفعول نصب."]]],
["g12","Demonstrativ & Fragepronomen","الإشارة والاستفهام","A2","pronomen",["g10","g13"],[
["dieser/diese/dieses للقريب.","dieser Mann, diese Frau","هذا الرجل، هذه المرأة.","dieses Kind","هذا الطفل.","diese Mann","dieser Mann.","يتصرف كأداة التعريف."],
["jener للبعيد الكتابي.","jener Tag","ذلك اليوم.","in jenen Jahren","في تلك السنوات.","نادر المحكي.","نادر المحكي.","استعمل das/dort شفهيًا."],
["der/die/das كضمير إشارة.","Der da ist mein Bruder.","هذا هناك أخي.","Die dort kenne ich.","أعرف تلك هناك.","كإشارة مشددة.","كإشارة مشددة.","النبرة تفرّق."],
["welcher للسؤال المحدد.","Welcher Bus fährt ab?","أي حافلة تغادر؟","Welche Tasche ist deine?","أي حقيبة لك؟","Was Bus?","Welcher Bus?","welch يتصرف."],
["was für للسؤال عن النوع.","Was für ein Mensch ist er?","أي نوع من الناس هو؟","Was für Musik hörst du?","أي موسيقى تسمع؟","Welcher für Mensch?","Was für ein Mensch?","النوع was für."],
["الفرق was/welch: مفتوح/محدد.","Was ist das? (مفتوح)","ما هذا؟","Welches ist deins? (محدد)","أيها لك؟","التبادل خطأ.","السياق يحدد."],
["selbst/selber للتوكيد.","Ich selbst komme.","آتي بنفسي.","Er hat es selber gemacht.","فعلها بنفسه.","مقبولان.","selbst أرقى."],
["alle/jede للعموم.","Alle kommen.","الجميع يأتون.","Jeder hilft.","كل واحد يساعد.","Alle kommt.","Alle kommen.","alle جمع وjede مفرد."],
["etwas/nichts المحايدة.","Etwas stimmt nicht.","شيء ما خطأ.","Nichts ist unmöglich.","لا شيء مستحيل.","فعل مفرد.","فعل مفرد."],
["jemand/niemand للعاقل.","Jemand ruft an.","شخص ما يتصل.","Niemand weiß es.","لا أحد يعرف.","فعل مفرد.","فعل مفرد."],
["الضمير الإشاري في الفرعية.","Ich kenne den, der das gemacht hat.","أعرف من فعل هذا.","ضمير + جملة وصل.","ضمير + جملة وصل.","تركيب متقدم.","تركيب متقدم."],
["الإشارة الزمنية: diese Woche.","diese Woche, diesen Monat","هذا الأسبوع، هذا الشهر.","letzte Woche","الأسبوع الماضي.","diese Wochen","diese Woche.","الزمن القريب diese."],
["الإشارة المكانية: hier/dort.","Komm hierher!","تعال إلى هنا!","Geh dorthin!","اذهب إلى هناك.","اتجاه her/hin.","اتجاه her/hin."],
["derjenige للتمييز الرسمي.","derjenige, der...","الذي...","diejenige, die...","التي...","رسمي كتابي.","رسمي كتابي."],
["اختبر: اختر.","___ Mann (dieser).","هذا الرجل.","___ ist deins? (Welches)","أيها لك؟","diese / Was","dieser / Welches.","طابق الجنس."]]],
["g13","Negation: nicht & kein","النفي","A1","syntax",["g01","g14"],[
["nicht تنفي الفعل والصفات.","Ich komme nicht.","لا آتي.","Das ist nicht gut.","هذا ليس جيدًا.","Ich nicht komme.","Ich komme nicht.","الموقع بعد الفعل."],
["kein تنفي الأسماء النكرة.","Ich habe kein Geld.","ليس معي مال.","Das ist kein Arzt.","هذا ليس طبيبًا.","Ich habe nicht Geld.","Ich habe kein Geld.","الاسم النكرة kein."],
["nicht آخر الجملة للنفي العام.","Er arbeitet heute nicht.","لا يعمل اليوم.","Sie kommt morgen nicht.","لن تأتي غدًا.","Er nicht arbeitet heute.","Er arbeitet heute nicht.","النفي العام في النهاية."],
["nicht قبل المحدد للنفي الجزئي.","Nicht ich mache das.","لست أنا من يفعل.","Nicht heute, morgen!","ليس اليوم بل غدًا!","Ich nicht mache das.","Nicht ich mache das.","التقديم = حصر النفي."],
["kein تتصرف: keinen keine...","keinen Hunger haben","لا شهية.","keine Zeit haben","لا وقت.","kein Hunger (فاعل معنوي).","keinen Hunger.","المفعول منصوب."],
["nie/niemals نفي زمني مطلق.","Ich rauche nie.","لا أدخن أبدًا.","Nie lüge ich.","أبدًا لا أكذب.","Ich rauche nie nicht.","مضاعفة النفي خطأ.","نفي واحد يكفي."],
["niemand/nichts نفي الوجود.","Niemand weiß es.","لا أحد يعرف.","Nichts hilft.","لا شيء ينفع.","Niemand nicht weiß.","Niemand weiß.","الفعل مثبت معها."],
["weder...noch للنفي المزدوج.","Weder er noch sie kommt.","لا هو ولا هي يأتي.","الفعل مفرد.","الفعل مفرد.","Weder er noch sie kommen.","Weder er noch sie kommt.","الفاعل المزدوج المنفي = مفرد."],
["nicht mehr = لم يعد.","Er raucht nicht mehr.","لم يعد يدخن.","Es gibt keine Milch mehr.","لم يعد هناك حليب.","Er raucht kein mehr.","Er raucht nicht mehr.","الانقطاع nicht mehr."],
["noch nicht = ليس بعد.","Er ist noch nicht da.","لم يصل بعد.","Noch nicht!","ليس بعد!","Er ist kein noch da.","Er ist noch nicht da.","الانتظار noch nicht."],
["الأمر المنفي: Sprich nicht!","Sprich nicht so laut!","لا تتحدث بصوت عالٍ!","Mach das nicht!","لا تفعل هذا!","Nicht sprich!","Sprich nicht!","الأمر ثم النفي."],
["السؤال المنفي يتوقع التأكيد.","Kommst du nicht mit?","ألا تأتي؟","Doch!","بل آتي!","Ja (ناقص).","Doch!","الإثبات بعد النفي doch."],
["النفي في الفرعية.","Ich weiß, dass er nicht kommt.","أعرف أنه لن يأتي.","Weil ich kein Geld habe, bleibe ich.","لأني بلا مال أبقى.","dass er kommt nicht.","dass er nicht kommt.","النفي قبل الفعل الأخير."],
["الفرق kein/nicht مع الأسماء المعرفة.","Das ist nicht mein Buch.","ليس كتابي.","Das ist kein Buch.","ليس كتابًا.","Das ist kein mein Buch.","Das ist nicht mein Buch.","المعرف nicht والنكرة kein."],
["اختبر: انفِ الجمل.","Ich habe Geld. → ___","ليس معي مال.","Er kommt. → ___","لن يأتي.","kein Geld / nicht","kein Geld / kommt nicht.","الاسم kein والفعل nicht."]]],
["g14","Modalverben","الأفعال الناقصة","A1","verben",["g15","g16"],[
["können للقدرة والإمكان.","Ich kann schwimmen.","أستطيع السباحة.","Kannst du helfen?","هل تستطيع المساعدة؟","Ich kann schwimme.","Ich kann schwimmen.","المصدر أخيرًا بلا zu."],
["müssen للوجوب القوي.","Ich muss arbeiten.","يجب أن أعمل.","Du musst pünktlich sein.","يجب أن تكون دقيقًا.","Ich muss zu arbeiten.","Ich muss arbeiten.","بلا zu بعد الناقص."],
["dürfen للإذن والمنع.","Darf ich fragen?","هل يمكنني السؤال؟","Hier darf man nicht rauchen.","ممنوع التدخين هنا.","Darf ich zu fragen?","Darf ich fragen?","المنع darf nicht."],
["sollen للأمر المنقول والنصيحة.","Du sollst zum Arzt.","عليك زيارة الطبيب.","Was soll ich tun?","ماذا أفعل؟","Du sollst zum Arzt zu gehen.","Du sollst zum Arzt gehen.","نصيحة خارجية sollen."],
["wollen للإرادة القوية.","Ich will Deutsch lernen.","أريد تعلم الألمانية.","Willst du mitkommen?","هل تريد المجيء؟","Ich will zu lernen.","Ich will lernen.","الرغبة الحاسمة wollen."],
["möchten للرغبة المهذبة.","Ich möchte einen Tee.","أود شايًا.","Möchten Sie zahlen?","هل تود الدفع؟","Ich möchte zu trinken.","Ich möchte trinken.","التهذيب möchten."],
["التصريف شاذ: ich kann, du kannst.","ich muss, du musst, er muss","أجب، تجب، يجب.","ich will, du willst","أريد، تريد.","ich könne, du könnt","ich kann, du kannst.","احفظ تصريفها."],
["الماضي: konnte musste wollte...","Ich konnte nicht kommen.","لم أستطع المجيء.","Er musste arbeiten.","اضطر للعمل.","Ich gekonnt (منفردًا).","Ich habe nicht kommen können.","المصدر المزدوج في الماضي."],
["النفي: nicht بعد الناقص.","Du musst nicht kommen.","لا يجب أن تأتي.","Du darfst das nicht.","لا يجوز هذا.","Du musst kommen nicht.","Du musst nicht kommen.","النفي قبل المصدر الأخير."],
["السؤال بالناقص أولًا.","Kannst du mir helfen?","هل تساعدني؟","Muss ich das machen?","هل يجب أن أفعل؟","Du kannst mir helfen?","Kannst du mir helfen?","تقديم الناقص."],
["حذف المصدر المفهوم.","Ich muss nach Hause.","يجب أن أعود للبيت.","Kannst du Deutsch?","هل تعرف الألمانية؟","الحذف طبيعي.","الحذف طبيعي.","المصدر المفهوم يُحذف."],
["الفرعية: الناقص أخيرًا.","Ich weiß, dass er kommen kann.","أعرف أنه يستطيع المجيء.","Weil ich arbeiten muss, bleibe ich.","لأني يجب أن أعمل أبقى.","dass er kann kommen.","dass er kommen kann.","الفعل المصرف أخيرًا."],
["الفرق müssen/sollen.","müssen = إلزام داخلي/موضوعي.","يجب.","sollen = أمر خارجي/نصيحة.","عليك (قيل لك).","التبادل يغيّر المصدر.","انتبه للمصدر."],
["الفرق können/dürfen.","können = قدرة.","أستطيع.","dürfen = إذن.","يجوز.","Ich kann rauchen (أقدر).","Ich darf rauchen (يُسمح).","الإذن dürfen."],
["اختبر: اختر الناقص.","___ ich fragen? (Darf)","هل يجوز أن أسأل؟","Ich ___ schwimmen. (kann)","أستطيع السباحة.","Kann / muss","Darf / kann.","الإذن dürfen والقدرة können."]]],
["g15","Trennbare Verben","الأفعال المنفصلة","A1","verben",["g14","g16"],[
["المقطع ينفصل في الجملة الرئيسية.","Ich stehe um 7 Uhr auf.","أنهض السابعة.","Er ruft mich heute an.","يتصل بي اليوم.","Ich aufstehe.","Ich stehe auf.","الفعل جذع ثانٍ والمقطع أخير."],
["أشهر المقاطع: an auf aus ein mit...","anrufen, aufstehen, ausgehen","يتصل، ينهض، يخرج.","einkaufen, mitkommen","يتسوق، يرافق.","خلطها بأفعال لازمة.","احفظ الفعل كاملًا."],
["الأمر: المقطع أخيرًا.","Steh auf!","انهض!","Ruf mich an!","اتصل بي!","Aufsteh!","Steh auf!","الأمر جذع + مقطع أخير."],
["المصدر مع zu بين المقطعين.","anzurufen, aufzustehen","أن يتصل، أن ينهض.","Es ist Zeit aufzustehen.","حان وقت النهوض.","zu aufstehen","aufzustehen.","zu في الوسط."],
["التصريف الثالث: ge في الوسط.","angrufen, aufgestanden","متصل، ناهض.","Er hat mich angerufen.","اتصل بي.","geanrufen","angerufen.","ge بعد المقطع."],
["الفرعية: الفعل ملتحم أخيرًا.","Ich weiß, dass er anruft.","أعرف أنه يتصل.","Weil er früh aufsteht, ...","لأنه ينهض مبكرًا...","dass er ruft an.","dass er anruft.","الفرعية تلحم الفعل."],
["السؤال: الجذع أولًا.","Stehst du früh auf?","هل تنهض مبكرًا؟","Rufst du mich an?","هل تتصل بي؟","Aufstehst du?","Stehst du auf?","الجذع المصرف أولًا."],
["النفي قبل المقطع.","Ich stehe heute nicht auf.","لا أنهض اليوم.","Er ruft nicht an.","لا يتصل.","Ich stehe auf nicht.","Ich stehe nicht auf.","النفي يسبق المقطع."],
["الفرق المنفصل/المتصل: umstellen.","Ich stelle um (أعيد الترتيب).","أعيد الترتيب.","Ich umstelle (أحاصر).","أحاصر.","النبرة تحدد.","النبرة على المقطع = منفصل."],
["أفعال مزدوجة المعنى بالنبرة.","durchbrechen (منفصل: ينكسر).","ينكسر.","durchbrechen (متصل: يخترق).","يخترق.","تجاهل النبرة.","احفظ النبرة مع المعنى."],
["الماضي: المساعد + ge الوسطى.","Er ist früh aufgestanden.","نهض مبكرًا.","Sie hat eingekauft.","تسوقت.","Er hat aufgestanden.","Er ist aufgestanden.","الحركة sein غالبًا."],
["الحاضر المستمر بالمعنى.","Ich räume gerade auf.","أرتب الآن.","Er zieht gerade um.","ينتقل الآن.","gerademid.","gerade قبل المقطع."],
["التوكيد بالمقطع.","Ruf doch mal an!","اتصل إذن!","Steh endlich auf!","انهض أخيرًا!","الجسيمات قبل المقطع.","الجسيمات قبل المقطع."],
["قائمة الحفظ اليومية.","anfangen, aufhören, zumachen","يبدأ، يتوقف، يغلق.","einkaufen, fernsehen","يتسوق، يشاهد.","حفظ منفرد.","احفظ الجمل لا القوائم."],
["اختبر: رتّب.","Ich / stehe / früh / auf.","أنهض مبكرًا.","Er / ruft / mich / an.","يتصل بي.","Ich aufstehe früh.","Ich stehe früh auf.","الجذع ثانٍ والمقطع أخير."]]],
["g16","Reflexive Verben","الأفعال الانعكاسية","A1","verben",["g14","g17"],[
["الانعكاسي يحتاج ضميرًا مطابقًا.","Ich wasche mich.","أغتسل.","Du beeilst dich.","تستعجل.","Ich wasche mir (هنا).","Ich wasche mich.","بلا مفعول ثانٍ = akk."],
["sich للغائب دائمًا.","Er trifft sich mit Freunden.","يقابل أصدقاءه.","Sie freuen sich.","يفرحون.","Er trifft ihn.","Er trifft sich.","الغائب sich."],
["أفعال انعكاسية خالصة.","sich freuen, sich beeilen","يفرح، يستعجل.","sich verspäten, sich erholen","يتأخر، يتعافى.","بلا sich لا معنى.","احفظها مع sich."],
["أفعال بمعنيين: حر/انعكاسي.","waschen (يغسل) vs sich waschen (يغتسل).","يغسل مقابل يغتسل.","treffen vs sich treffen.","يقابل مقابل يلتقي.","التبادل خطأ.","sich تغيّر المعنى."],
["dativ الانعكاسي مع مفعول ثانٍ.","Ich wasche mir die Hände.","أغسل يديّ.","Er kauft sich ein Auto.","يشتري سيارة لنفسه.","Ich wasche mich die Hände.","Ich wasche mir die Hände.","المفعول الثاني يحوّل لـdativ."],
["الترتيب: الضمير بعد الفعل.","Ich freue mich sehr.","أفرح جدًا.","Er ärgert sich oft.","ينزعج غالبًا.","Ich mich freue.","Ich freue mich.","الضمير ملاصق للفعل."],
["الفرعية: الضمير بعد الفاعل.","Ich weiß, dass er sich freut.","أعرف أنه فرح.","Weil sie sich beeilt, ...","لأنها مستعجلة...","dass sich er freut.","dass er sich freut.","الفاعل ثم الانعكاسي."],
["الأمر الانعكاسي.","Beeil dich!","أسرع!","Setz dich!","اجلس!","Beeile dich (رسمية).","Beeil dich! / Setzen Sie sich!","الأمر جذع + ضمير."],
["الماضي: haben غالبًا.","Ich habe mich gefreut.","فرحت.","Er hat sich verletzt.","أصيب.","Ich bin mich gefreut.","Ich habe mich gefreut.","المساعد haben."],
["النفي قبل الانعكاسي أو بعده.","Ich freue mich nicht.","لا أفرح.","Ich beeile mich heute nicht.","لست مستعجلًا اليوم.","Ich freue nicht mich.","Ich freue mich nicht.","الضمير ملاصق والنفي حر."],
["التقابل: einander.","Sie helfen einander.","يساعد بعضهم بعضًا.","Wir sehen uns.","نلتقي.","Sie helfen sich (غامض).","einander للتقابل الواضح."],
["الانفعالات انعكاسية غالبًا.","sich ärgern, sich schämen","ينزعج، يخجل.","sich verlieben, sich fürchten","يقع في الحب، يخاف.","بلا sich.","احفظ قائمة الانفعالات."],
["الروتين اليومي انعكاسي.","sich anziehen, sich duschen","يلبس، يستحم.","sich rasieren, sich kämmen","يحلق، يمشط.","نسيان sich.","الروتين sich."],
["الفرق treffen/sich treffen.","Ich treffe ihn (أقابله).","أقابله.","Wir treffen uns (نلتقي).","نلتقي.","التبادل يغيّر المعنى.","المعنى يتحدد بـsich."],
["اختبر: اختر الضمير.","Ich wasche ___ (mich).","أغتسل.","Er kauft ___ ein Auto. (sich)","يشتري لنفسه سيارة.","mir / ihn","mich / sich.","بلا مفعول ثانٍ akk."]]],
["g17","Präsens","المضارع","A1","zeiten",["g14","g18"],[
["النهايات: -e -st -t -en -t -en.","ich lerne, du lernst","أتعلم، تتعلم.","er lernt, wir lernen","يتعلم، نتعلم.","ich lernt","ich lerne.","الجذع + النهاية."],
["الجذع المنتهي بـ -t يحتاج e.","du arbeitest, er wartet","تعمل، ينتظر.","du findest","تجد.","du arbeitst","du arbeitest.","التسهيل الصوتي."],
["تغير الجذع e→i لبعض الأفعال.","du sprichst, er spricht","تتحدث، يتحدث.","du siehst, er sieht","ترى، يرى.","du sprechst","du sprichst.","فقط du/er."],
["تغير a→ä لبعض الأفعال.","du fährst, er fährt","تسافر، يسافر.","du schläfst","تنام.","du fahrst","du fährst.","فقط du/er."],
["sein شاذ كليًا.","ich bin, du bist, er ist","أكون، تكون، يكون.","wir sind, ihr seid","نكون، تكونون.","ich binst","ich bin.","يُحفظ غيبًا."],
["haben شاذ جزئيًا.","ich habe, du hast","لديّ، لديك.","er hat","لديه.","du habst","du hast.","احفظه."],
["werden للمستقبل والمبني للمجهول.","ich werde, du wirst","سأكون...","er wird","سيكون.","ich werdt","ich werde.","متعدد المهام."],
["الناقصة شاذة: kann musst will.","ich kann, du kannst","أستطيع، تستطيع.","ich muss, will, darf","أجب، أريد، يجوز.","ich könne","ich kann.","احفظ جدولها."],
["المضارع للحاضر والمستقبل القريب.","Morgen komme ich.","سآتي غدًا.","Ich gehe jetzt.","أذهب الآن.","سياق زمني إلزامي للمستقبل.","الظرف يحدد الزمن."],
["المضارع للعادات.","Ich trinke gern Tee.","أحب الشاي.","Er spielt Fußball.","يلعب كرة.","واضح.","العادات مضارع."],
["النفي والاستفهام بالموقع.","Kommst du? — Nein.","هل تأتي؟ — لا.","Arbeitest du heute?","هل تعمل اليوم؟.","هل تفعل؟ (مساعد).","الموقع يكفي بلا مساعد."],
["الجمع: ihr -t وsie -en.","ihr spielt, sie spielen","تلعبون، يلعبون.","Ihr lernt","تتعلمون.","ihr spielen","ihr spielt.","فرّق ihr/sie."],
["الأفعال بـ -eln/-ern تسقط e.","ich lächle, wir lächeln","أبتسم، نبتسم.","du sammelst","تجمع.","ich lächele (مقبول).","ich lächle.","الحذف طبيعي."],
["المصدر بعد الناقص بلا zu.","Ich will lernen.","أريد أن أتعلم.","Du musst kommen.","يجب أن تأتي.","Ich will zu lernen.","Ich will lernen.","بلا zu."],
["اختبر: صرف.","sein: ich ___ (bin).","أكون.","fahren: er ___ (fährt).","يسافر.","ich bist / er fahrt","ich bin / er fährt.","احفظ الشواذ."]]],
["g18","Perfekt","الماضي التام","A1","zeiten",["g17","g19"],[
["التكوين: haben/sein + التصريف الثالث.","Ich habe gelernt.","تعلمت.","Er ist gekommen.","أتى.","Ich habe gelernt (خطأ المساعد).","اختر المساعد الصحيح."],
["haben لمعظم الأفعال.","Ich habe gegessen.","أكلت.","Wir haben gekauft.","اشترينا.","Ich bin gegessen.","Ich habe gegessen.","المتعدي haben."],
["sein للحركة والتغير.","Ich bin gegangen.","ذهبت.","Er ist aufgewacht.","استيقظ.","Ich habe gegangen.","Ich bin gegangen.","الحركة sein."],
["التصريف الثالث للمنتظم: ge+t.","gelernt, gespielt, gemacht","متعَلَّم، ملعوب، مصنوع.","gekauft, gehört","مشترى، مسموع.","gelernt ohne ge.","ge- إلزامية."],
["الشاذ: ge+تغير الجذع.","gegessen, getrunken","مأكول، مشروب.","gesehen, gelesen","مرئي، مقروء.","geesst","gegessen.","احفظ القائمة."],
["المنفصل: ge في الوسط.","aufgestanden, angerufen","ناهض، متصل.","eingekauft","متسوق.","geaufstanden","aufgestanden.","المقطع أولًا ثم ge."],
["المتصل بـ be-/ver-: بلا ge.","verkauft, bestellt","مبيع، مطلوب.","erzählt","مروي.","geverkauft","verkauft.","البداية المتصلة تمنع ge."],
["الناقص: المصدر المزدوج.","Ich habe kommen müssen.","اضطررت للمجيء.","Er hat nicht schlafen können.","لم يستطع النوم.","Ich habe gemusst kommen.","Ich habe kommen müssen.","مصدران أخيرًا."],
["الترتيب: المساعد ثانٍ والثالث أخير.","Ich habe gestern viel gelernt.","تعلمت كثيرًا أمس.","Er ist heute angekommen.","وصل اليوم.","Ich gestern habe gelernt.","المساعد ثانٍ."],
["النفي قبل الثالث.","Ich habe nicht gelernt.","لم أتعلم.","Er ist nicht gekommen.","لم يأتِ.","Ich habe gelernt nicht.","Ich habe nicht gelernt.","النفي يسبق الثالث."],
["السؤال بتقديم المساعد.","Hast du gelernt?","هل تعلمت؟","Bist du gegangen?","هل ذهبت؟","Habe du gelernt?","Hast du gelernt?","المساعد أولًا."],
["المحكي يفضل Perfekt على Präteritum.","Ich habe das gemacht.","فعلت هذا.","Wir haben uns getroffen.","التقينا.","Ich machte das (كتابي).","المحكي perfekt."],
["الزمن مع schon/noch nie.","Ich habe schon gegessen.","أكلت already.","Noch nie gesehen!","لم أرَ قط!","الجسيمات قبل الثالث.","الجسيمات قبل الثالث."],
["sein/bleiben شاذة: gewesen/geblieben.","Ich bin gewesen.","كنت.","Er ist geblieben.","بقي.","Ich habe gewesen.","Ich bin gewesen.","الحركة والبقاء sein."],
["اختبر: اختر المساعد.","___ gegangen (sein).","ذُهب.","___ gelernt (haben).","تُعلِّم.","habe/bin","bin/habe.","الحركة sein."]]],
["g19","Präteritum","الماضي البسيط","A2","zeiten",["g18","g20"],[
["الكتابي يفضل Präteritum.","Er ging nach Hause.","ذهب للبيت.","Sie las ein Buch.","قرأت كتابًا.","Er ist gegangen (محكي).","الكتابي präteritum."],
["المنتظم: جذع + -te.","lernte, spielte, machte","تعلم، لعب، فعل.","kaufte, hörte","اشترى، سمع.","lernte vs gelernt.","-te علامة الماضي."],
["الشاذ: تغير الجذع.","ging, kam, sah","ذهب، أتى، رأى.","aß, trank, schlief","أكل، شرب، نام.","gehte, komte","احفظ القائمة."],
["sein/haben: war/hatte.","Ich war krank.","كنت مريضًا.","Wir hatten Zeit.","كان لدينا وقت.","Ich bin gewesen (محكي).","الكتابي war/hatte."],
["الناقص: konnte musste wollte.","Er konnte nicht kommen.","لم يستطع المجيء.","Sie wollte bleiben.","أرادت البقاء.","Er gekonnt (منفرد).","الناقص ماضيه -te."],
["القصص والحكايات präteritum.","Es war einmal...","كان يا ما كان...","Plötzlich kam er.","فجأة أتى.","Es ist einmal gewesen.","القصص präteritum."],
["التقارير الرسمية präteritum.","Der Zug fuhr ab.","غادر القطار.","Die Polizei kam.","أتت الشرطة.","Der Zug ist abgefahren.","الرسمي präteritum."],
["المنفصل يلتحم في الماضي.","Er stand auf.","نهض.","Sie kaufte ein.","تسوقت.","Er aufstand (أخيرًا فقط).","الفعل ملتحم ثانيًا."],
["النفي والترتيب كالمضارع.","Er kam nicht.","لم يأتِ.","Kam er?","هل أتى؟","Er nicht kam.","V2 كالمعتاد."],
["الفرق المحكي/الكتابي.","sagte vs hat gesagt","قال.","ging vs ist gegangen","ذهب.","التبادل أسلوبي.","اختر حسب المقام."],
["الأفعال المختلطة.","brannte, kannte, wusste","احترق، عرف، علم.","dachte, brachte","فكر، أحضر.","منتظم وشاذ معًا.","احفظها."],
["الزمن مع damals/früher.","Damals wohnte ich in Kairo.","سكنت القاهرة قديمًا.","Früher spielte ich.","لعبت سابقًا.","الظرف يصاحب الماضي.","الظرف يصاحب الماضي."],
["التتابع القصصي.","Er stand auf, duschte und frühstückte.","نهض واستحم وأفطر.","تتابع بنفس الزمن.","تتابع بنفس الزمن.","الثبات الزمني."],
["الأخطاء: خلط المساعد.","Er hat gegangen (محكي مقبول).","ذهب.","كتابيًا: Er ging.","المحكي يتسامح.","الكتابي لا."],
["اختبر: حوّل.","gehen → er ___ (ging).","ذهب.","haben → wir ___ (hatten).","كان لدينا.","er gehtete","er ging. / wir hatten."]]],
["g20","Plusquamperfekt & Futur","الماضي الأسبق والمستقبل","A2","zeiten",["g19","g21"],[
["الأسبق: hatte/war + الثالث.","Ich hatte gelernt.","كنت قد تعلمت.","Er war gegangen.","كان قد ذهب.","المساعد ماضٍ.","المساعد ماضٍ."],
["الاستعمال: حدث قبل حدث ماضٍ.","Nachdem ich gegessen hatte, ging ich.","بعد أن أكلت ذهبت.","Als er kam, war ich gegangen.","عندما أتى كنت قد ذهبت.","ترتيب زمني مزدوج.","ترتيب زمني مزدوج."],
["الإشارة: nachdem/bevor/schon.","Ich hatte schon gehört.","كنت قد سمعت.","Er war noch nicht da.","لم يكن قد أتى.","الأسبقية schon.","الأسبقية schon."],
["Futur I: werden + مصدر.","Ich werde kommen.","سآتي.","Er wird helfen.","سيساعد.","Ich werde gekommen.","werden + مصدر."],
["المضارع يكفي للمستقبل مع ظرف.","Morgen komme ich.","سآتي غدًا.","Nächste Woche fliege ich.","أسافر الأسبوع القادم.","الألمان يفضلون المضارع.","الألمان يفضلون المضارع."],
["Futur للوعود والتخمين.","Ich werde dir helfen.","سأساعدك.","Er wird schon da sein.","لابد أنه هناك.","الوعد والظن futur.","الوعد والظن futur."],
["النفي في المستقبل.","Ich werde nicht kommen.","لن آتي.","Er wird nicht helfen.","لن يساعد.","werde kommen nicht.","النفي قبل المصدر."],
["السؤال المستقبلي.","Wirst du kommen?","هل ستأتي؟","Wird er helfen?","هل سيساعد؟","Wirst kommen du?","V2 كالمعتاد."],
["Futur II للنخمين عن الماضي.","Er wird das gemacht haben.","لابد أنه فعلها.","تخمين ماضٍ.","تخمين ماضٍ.","متقدم.","متقدم."],
["الجدول الزمني: vorhaben.","Ich habe vor zu kommen.","أنوي المجيء.","Wir haben vor zu reisen.","ننوي السفر.","vorhaben + zu.","vorhaben + zu."],
["الترتيب في الفرعية.","dass ich kommen werde.","أنني سآتي.","المصدر قبل werden أخيرًا.","المصدر قبل werden أخيرًا."],
["الأخطاء: werde + الثالث.","Ich werde gelernt (خطأ).","خطأ.","Ich werde lernen.","سأتعلم.","الثالث للماضي فقط."],
["الأسبق مع sein للحركة.","Ich war schon gegangen.","كنت قد ذهبت.","Er war angekommen.","كان قد وصل.","المساعد يطابق الحركة."],
["التدريب: رتّب زمنيًا.","zuerst essen, dann gehen.","أولًا الأكل ثم الذهاب.","Nachdem ich gegessen hatte, ging ich.","بعد الأكل ذهبت.","الترتيب المنطقي."],
["اختبر: أكمل.","Ich ___ kommen. (werde)","سآتي.","Ich hatte ___ (gelernt).","كنت قد تعلمت.","wird / habe","werde / hatte gelernt."]]],
["g21","Adjektivdeklination","إعراب الصفات","A2","adjektiv",["g03","g22"],[
["بعد der: النهاية -e/-en.","der gute Mann","الرجل الطيب.","die schöne Frau","المرأة الجميلة.","der guten Mann (فاعل).","der gute Mann.","الرفع -e وباقي -en."],
["بعد ein: -er/-e/-es في الرفع.","ein guter Mann","رجل طيب.","eine schöne Frau","امرأة جميلة.","ein gute Mann","ein guter Mann.","النكرة تُظهر الجنس."],
["بلا أداة: النهاية كالأداة.","guter Kaffee, kalte Milch","قهوة جيدة، حليب بارد.","frisches Brot","خبز طازج.","gut Kaffee","guter Kaffee.","الصفة تحمل الإعراب."],
["الجمع بلا أداة: -e.","kalte Getränke","مشروبات باردة.","nette Leute","أناس لطفاء.","kalten Getränke","kalte Getränke.","الرفع الجمع -e."],
["النصب المذكر: -en دائمًا.","den guten Mann","الرجل الطيب.","einen schönen Tag","يومًا جميلًا.","den gute Mann","den guten Mann.","النصب -en."],
["الجر: -en دائمًا.","mit dem neuen Auto","بالسيارة الجديدة.","bei guter Musik","بموسيقى جيدة.","mit dem neue Auto","mit dem neuen Auto.","الجر -en."],
["المحايد: -es في الرفع النكرة.","ein kleines Kind","طفل صغير.","frisches Brot","خبز طازج.","ein kleine Kind","ein kleines Kind.","المحايد -es."],
["الصفات بعد sein بلا نهاية.","Das Auto ist neu.","السيارة جديدة.","Die Frau ist nett.","المرأة لطيفة.","Das Auto ist neues.","المسند بلا إعراب."],
["الصفات الظرفية بلا نهاية.","Er fährt schnell.","يقود بسرعة.","Sie singt schön.","تغني جميلًا.","Er fährt schneller (مقارنة).","الظرف بلا نهاية."],
["الألوان والمواد تتصرف.","ein rotes Auto","سيارة حمراء.","die blaue Tasche","الحقيبة الزرقاء.","ein rot Auto","ein rotes Auto.","كل الصفات تُعرب."],
["الصفات المركبة.","ein deutsch-arabisches Wörterbuch","قاموس ألماني عربي.","die deutschsprachige Community","الجالية الناطقة بالألمانية.","الواصلة لا تمنع الإعراب.","الواصلة لا تمنع الإعراب."],
["الأعداد الترتيبية كالصفات.","der erste Tag","اليوم الأول.","am zweiten Mai","في الثاني من مايو.","der erst Tag","der erste Tag.","الترتيبي يُعرب."],
["أسماء الصفات: der Kranke.","der Kranke, die Kranke","المريض، المريضة.","etwas Neues","شيء جديد.","der Kranke ohne Endung.","تُعرب كالصفات."],
["الحالات المختلطة.","viel guter Kaffee (بلا أداة).","كثير من القهوة الجيدة.","trotz schlechten Wetters","رغم الطقس السيئ.","السياق يحدد.","السياق يحدد."],
["اختبر: أعرب.","___ gute Mann (der).","الرجل الطيب.","mit ___ Auto (dem neuen).","بالسيارة الجديدة.","der guten / dem neue","der gute / dem neuen."]]],
["g22","Komparation","المقارنة والتفضيل","A1","adjektiv",["g21","g23"],[
["المقارنة: -er + als.","größer als, kleiner als","أكبر من، أصغر من.","Er ist größer als ich.","هو أطول مني.","größer wie ich.","größer als ich.","المقارنة als."],
["التفضيل: am + -sten.","am größten, am besten","الأكبر، الأفضل.","Sie ist am schnellsten.","هي الأسرع.","der größte (قبل الاسم).","am größten (مسند)."],
["الشاذ: gut besser best.","gut, besser, am besten","جيد، أفضل، الأفضل.","viel, mehr, am meisten","كثير، أكثر، الأكثر.","guter, gutest","gut, besser, best."],
["gern lieber liebst.","Ich spiele gern Fußball.","أحب لعب الكرة.","Am liebsten lese ich.","أفضل القراءة.","am gernsten.","am liebsten."],
["bald eher äußerst.","Bald kommt er.","سيأتي قريبًا.","eher früher","بل مبكرًا أكثر.","مقارنة الظروف.","مقارنة الظروف."],
["المساواة: so...wie.","so groß wie, so gut wie","بطول، بجودة.","Er ist so groß wie ich.","بطولي.","so groß als.","so...wie للمساواة."],
["التفضيل قبل الاسم يُعرب.","der größte Mann","أطول رجل.","die beste Freundin","أفضل صديقة.","der größte (بلا سياق).","يُعرب كالصفة."],
["Umlaut في المقارنة.","groß→größer, jung→jünger","أكبر، أصغر.","alt→älter, kurz→kürzer","أقدم، أقصر.","grosser.","Umlaut إلزامي."],
["المقارنة السلبية: weniger.","weniger teuer","أقل غلاءً.","weniger interessant","أقل إثارة.","nicht so teuer.","weniger للمقارنة السفلى."],
["je...desto للمقارنة المزدوجة.","Je mehr, desto besser.","كلما أكثر كان أفضل.","Je früher, desto besser.","كلما أبكر كان أفضل.","صيغة محفوظة.","صيغة محفوظة."],
["immer + مقارنة للتقدم.","immer besser","يتحسن دائمًا.","immer größer","يكبر باستمرار.","التقدم المستمر.","التقدم المستمر."],
["viel/bald الشاذة.","viel→mehr→meist","كثير.","bald→eher→ehest","قريب.","mehre.","mehr."],
["المقارنة في الفرعية.","dass er größer ist als ich.","أنه أطول مني.","الترتيب ثابت.","الترتيب ثابت."],
["الأخطاء: wie بعد المقارنة.","größer wie (عامية).","عامية.","الصحيح größer als.","الصحيح größer als."],
["اختبر: قارن.","gut → ___ → ___","جيد.","groß → ___","كبير.","besser/best, größer","besser, best / größer."]]],
["g23","Präpositionen: Wechsel","حروف الجر ثنائية الاتجاه","A1","praeposition",["g07","g24"],[
["in an auf über unter vor hinter neben zwischen.","in die Schule (حركة).","إلى المدرسة.","in der Schule (سكون).","في المدرسة.","الحركة akk والسكون dat."],
["السؤال wohin = حركة.","Wohin gehst du? — In die Stadt.","إلى أين؟ — للمدينة.","Wohin stellst du das?","أين تضع هذا؟","Wo (للاتجاه).","Wohin للاتجاه."],
["السؤال wo = سكون.","Wo bist du? — In der Stadt.","أين أنت؟ — في المدينة.","Wo liegt das Buch?","أين الكتاب؟","Wohin (للسكون).","Wo للسكون."],
["stellen/stehen الثنائية.","stellen (يضع) حركة.","يضع.","stehen (يقف) سكون.","يقف.","التبادل خطأ.","الفعل يحدد."],
["legen/liegen الثنائية.","legen (يضجع) حركة.","يضجع.","liegen (يستلقي) سكون.","يستلقي.","التبادل خطأ.","الفعل يحدد."],
["setzen/sitzen الثنائية.","sich setzen حركة.","يجلس.","sitzen سكون.","جالس.","التبادل خطأ.","الفعل يحدد."],
["hängen الثنائية.","hängen (يعلّق) حركة.","يعلّق.","hängen (معلق) سكون.","معلق.","السياق يحدد.","السياق يحدد."],
["الأفعال الموضعية.","Das Bild hängt an der Wand.","الصورة على الحائط.","Er hängt das Bild an die Wand.","يعلّق الصورة.","الموضع dat والوضع akk."],
["التعبيرات المحفوظة.","zu Hause, nach Hause","في البيت، إلى البيت.","ins Kino, im Kino","للسينما، في السينما.","حفظ ثنائي.","حفظ ثنائي."],
["الأخطاء الشائعة.","Ich bin in die Schule (وأنا فيها).","خطأ.","الصحيح in der Schule.","الصحيح in der Schule."],
["التدريب الحركي.","Wohin? → akk.","اتجاه.","Wo? → dat.","مكان.","القاعدة الذهبية."],
["in + السنة/الشهر بلا أداة إضافية.","im Mai, im Sommer","في مايو، في الصيف.","in der Nacht","في الليل.","in Mai.","im Mai."],
["an + الأيام والتواريخ.","am Montag, am Wochenende","الاثنين، العطلة.","am 3. Mai","في 3 مايو.","in Montag.","an للأيام."],
["um + الساعة.","um 8 Uhr","الثامنة.","Um wie viel Uhr?","في أي ساعة؟.","an 8 Uhr.","um للساعة."],
["اختبر: اختر الحالة.","Ich gehe ___ Schule. (in die)","أذهب للمدرسة.","Ich bin ___ Schule. (in der)","أنا في المدرسة.","in der / in die","in die / in der.","الحركة نصب."]]],
["g24","Temporale Präpositionen","حروف الجر الزمنية","A1","praeposition",["g23","g25"],[
["um للساعة الدقيقة.","um 8 Uhr, um Mitternacht","الثامنة، منتصف الليل.","Der Film beginnt um 20 Uhr.","يبدأ الفيلم الثامنة.","am 8 Uhr.","um للساعة."],
["am للأيام وأجزاء اليوم.","am Montag, am Morgen","الاثنين، الصباح.","am Wochenende","العطلة.","im Montag.","am للأيام."],
["im للشهور والفصول والسنوات.","im Mai, im Sommer","مايو، الصيف.","im Jahr 2024","سنة 2024.","am Mai.","im للمدد."],
["von...bis للمدد.","von 8 bis 12 Uhr","من 8 إلى 12.","von Montag bis Freitag","من الاثنين للجمعة.","bis...von.","von...bis."],
["seit للبداية المستمرة + dativ.","seit einem Jahr","منذ سنة.","Seit wann lernst du?","منذ متى تتعلم؟","seit ein Jahr.","seit + dativ."],
["vor للماضي المنقضي.","vor zwei Tagen","قبل يومين.","Vor einer Woche kam er.","أتى قبل أسبوع.","vor zwei Tage.","vor + dativ."],
["in للمستقبل.","in zwei Tagen","بعد يومين.","In einer Woche fliege ich.","أسافر بعد أسبوع.","in + dativ.","in للمستقبل."],
["nach للترتيب التالي.","nach dem Essen","بعد الأكل.","Nach der Arbeit gehe ich.","بعد العمل أذهب.","nach dem Essen (dat).","nach + dativ."],
["während + genitiv للمدد.","während des Films","أثناء الفيلم.","Während der Arbeit","أثناء العمل.","während dem Film (عامية).","الرسمي genitiv."],
["gegen للتقريب.","gegen Abend","نحو المساء.","gegen 8 Uhr","حوالي الثامنة.","التقريب gegen.","التقريب gegen."],
["ab للبداية المستقبلية.","ab Montag","اعتبارًا من الاثنين.","Ab morgen rauche ich nicht.","من الغد لا أدخن.","ab + dativ/akk.","ab للبداية."],
["zu للمناسبات.","zu Weihnachten, zu Ostern","الكريسماس، الفصح.","zum Geburtstag","عيد الميلاد.","an Weihnachten (مقبول).","zu للمناسبات."],
["pünktlich وrechtzeitig.","pünktlich um 8","تمام الثامنة.","rechtzeitig kommen","يأتي في الوقت.","الفرق دقيق.","pünktlich تمام وrechtzeitig مبكر كافٍ."],
["Dauer: -lang.","eine Woche lang","لمدة أسبوع.","den ganzen Tag","طوال اليوم.","المدة akk بلا حرف.","المدة akk."],
["اختبر: اختر الحرف.","___ Montag (am).","الاثنين.","___ 8 Uhr (um).","الثامنة.","im / an","am / um.","الأيام am والساعة um."]]],
["g25","Lokale Präpositionen","حروف الجر المكانية","A1","praeposition",["g23","g26"],[
["zu للوجهة dativ.","zum Arzt, zur Schule","للطبيب، للمدرسة.","Ich gehe zum Bahnhof.","أذهب للمحطة.","zu den Arzt.","zum = zu+dem."],
["nach للمدن والدول بلا أداة.","nach Berlin, nach Hause","لبرلين، للبيت.","nach Deutschland","لألمانيا.","zu Berlin.","nach للمدن."],
["in للبلدان بالأداة والداخل.","in die Türkei, in der Türkei","لتركيا، في تركيا.","in den Supermarkt","للسوبرماركت.","nach Türkei.","الأداة تفرض in."],
["bei للأشخاص والأماكن.","bei meinen Eltern","عند والديّ.","beim Arzt","عند الطبيب.","zu meinen Eltern (حركة).","السكون bei."],
["von للأصل.","vom Bahnhof","من المحطة.","Von wo kommst du?","من أين أنت؟.","aus Bahnhof.","von للنقطة."],
["aus للداخل-للخارج والأصل.","aus dem Haus","من البيت.","aus Ägypten","من مصر.","von Ägypten (سكون).","الأصل الداخلي aus."],
["bis للحد.","bis Berlin","حتى برلين.","bis morgen","حتى الغد.","الحد bis.","الحد bis."],
["durch للاختراق akk.","durch den Park","عبر المنتزه.","Durch den Wald laufen.","المشي عبر الغابة.","durch dem Park.","durch + akk."],
["entlang على طول.","den Fluss entlang","على طول النهر.","Die Straße entlang gehen.","المشي على طول الشارع.","الموضع بعد الاسم غالبًا.","الموضع بعد الاسم."],
["gegenüber المقابل.","gegenüber dem Bahnhof","مقابل المحطة.","Dem Haus gegenüber.","مقابل البيت.","gegenüber den.","gegenüber + dativ."],
["التعبيرات الثابتة.","zu Hause vs nach Hause","في البيت مقابل إلى البيت.","ans Meer, ans Telefon","للبحر، للهاتف.","حفظ ثنائي.","حفظ ثنائي."],
["الاتجاهات: links rechts.","links abbiegen","انعطف يسارًا.","rechts neben der Bank","يمينًا بجانب البنك.","ظرف بلا إعراب.","ظرف بلا إعراب."],
["Stockwerke: im ersten Stock.","im ersten Stock","في الطابق الأول.","in den zweiten Stock","للطابق الثاني.","السكون dat.","الحركة akk."],
["الأخطاء: zu/nach.","zu Hause bleiben.","البقاء في البيت.","nach Hause gehen.","الذهاب للبيت.","zu Hause gehen.","zu سكون وnach حركة للبيت."],
["اختبر: اختر.","___ Berlin (nach).","لبرلين.","___ Arzt (zum).","للطبيب.","zu / zu dem","nach / zum.","المدن nach."]]],
["g26","Konjunktionen: nebenordnend","أدوات العطف","A1","konjunktion",["g25","g27"],[
["und/aber/oder/denn لا تغيّر الترتيب.","Ich koche und er hilft.","أطبخ ويساعد.","Er ist klein, aber stark.","صغير لكن قوي.","Ich koche und er hilft (V2).","V2 بعدهما."],
["aber للتعارض.","teuer, aber gut","غالٍ لكن جيد.","Er lernt, aber langsam.","يتعلم لكن ببطء.","sondern (للنفي).","aber تعارض مثبت."],
["sondern بعد النفي.","nicht Tee, sondern Kaffee","ليس شايًا بل قهوة.","Nicht heute, sondern morgen.","ليس اليوم بل غدًا.","aber (بعد النفي).","النفي + sondern."],
["oder للاختيار.","Tee oder Kaffee?","شاي أم قهوة؟","Kommst du oder bleibst du?","هل تأتي أم تبقى؟.","und (للاختيار).","oder اختيار."],
["denn للسبب الرئيسي.","Ich bleibe, denn ich bin müde.","أبقى لأني متعب.","Er lacht, denn er freut sich.","يضحك لأنه فرح.","weil (فرعية).","denn رئيسية V2."],
["doppelt: sowohl...als auch.","sowohl Tee als auch Kaffee","شاي وقهوة معًا.","Sowohl er als auch sie kommt.","كلاهما يأتي.","الفعل مفرد غالبًا.","الفعل مفرد غالبًا."],
["entweder...oder للحصر.","Entweder du oder ich.","إما أنت أو أنا.","الفعل يطابق الأقرب.","الفعل يطابق الأقرب."],
["nicht nur...sondern auch.","Nicht nur Tee, sondern auch Kaffee.","ليس شايًا فقط بل قهوة أيضًا.","التوكيد المزدوج.","التوكيد المزدوج."],
["weder...noch.","Weder Tee noch Kaffee.","لا شاي ولا قهوة.","الفعل مفرد.","الفعل مفرد."],
["je...desto.","Je mehr, desto besser.","كلما أكثر كان أفضل.","صيغة محفوظة.","صيغة محفوظة."],
["الفرق aber/sondern.","aber بعد المثبت.","لكن.","sondern بعد المنفي.","بل.","السياق يحدد."],
["الفرق denn/weil.","denn رئيسية.","لأن (V2).","weil فرعية (فعل أخير).","لأن (فعل أخير)."],
["العطف والفواصل.","Ich kaufe Brot, Milch und Käse.","أشتري خبزًا وحليبًا وجبنًا.","الفاصلة قبل und ممنوعة غالبًا.","الفاصلة ممنوعة قبل und."],
["العطف الطويل.","Er arbeitet, sie kocht und wir essen.","يعمل وتطبخ ونأكل.","V2 في كل جملة.","V2 في كل جملة."],
["اختبر: اختر.","nicht Tee, ___ Kaffee (sondern).","بل قهوة.","Ich bleibe, ___ ich bin müde (denn).","لأني متعب.","aber / weil","sondern / denn.","النفي sondern والسبب الرئيسي denn."]]],
["g27","Nebensätze: weil dass wenn","الجمل الفرعية الأساسية","A1","konjunktion",["g26","g28"],[
["weil + فعل أخير.","Ich bleibe, weil ich krank bin.","أبقى لأني مريض.","Weil es regnet, bleibe ich.","لأنها تمطر أبقى.","weil ich bin krank.","weil + فعل أخير."],
["dass + فعل أخير.","Ich weiß, dass er kommt.","أعرف أنه يأتي.","Es ist gut, dass du da bist.","جميل أنك هنا.","dass er kommt heute.","الفعل أخيرًا."],
["wenn الشرطية والزمانية.","Wenn es regnet, bleibe ich.","إن مطرت أبقى.","Wenn ich Zeit habe, komme ich.","إن كان لدي وقت آتِ.","When (إنجليزية).","wenn شرط/زمان حاضر."],
["als للماضي المفرد.","Als ich klein war, ...","عندما كنت صغيرًا...","Als er kam, lachte sie.","عندما أتى ضحكت.","wenn للماضي المفرد.","als = مرة ماضية."],
["ob السؤال غير المباشر.","Ich weiß nicht, ob er kommt.","لا أعرف إن كان سيأتي.","Frag, ob sie Zeit hat.","اسأل إن كان لديها وقت.","ob vs wenn.","ob = هل غير مباشرة."],
["الفرعية أولًا تقلب الرئيسية.","Weil ich krank bin, bleibe ich.","لأني مريض أبقى.","Wenn du kommst, freue ich mich.","إن أتيت أفرح.","الفاصلة ثم V2.","الفاصلة ثم V2."],
["الناقص في الفرعية أخيرًا مضاعفًا.","dass ich arbeiten muss.","أنني يجب أن أعمل.","weil er nicht kommen kann.","لأنه لا يستطيع المجيء.","dass ich muss arbeiten.","المصدر قبل المصرف."],
["المنفصل ملتحم في الفرعية.","dass er anruft.","أنه يتصل.","weil sie aufsteht.","لأنها تنهض.","dass er ruft an.","الفرعية تلحم."],
["النفي قبل الفعل الأخير.","dass er nicht kommt.","أنه لن يأتي.","weil ich kein Geld habe.","لأني بلا مال.","dass er kommt nicht.","النفي يسبق الأخير."],
["الفرق wenn/als/wann.","wann سؤال.","متى؟","wenn شرط حاضر.","إن/عندما.","als ماضٍ مفرد.","الثلاثية الذهبية."],
["الفرق ob/wenn.","ob = هل.","هل.","wenn = إن.","إن.","التبادل خطأ."],
["الفرق dass/was.","dass رابط.","أن.","was ضمير وصل.","الذي (غير العاقل).","السياق يحدد."],
["الفرعية والفواصل.","الفاصلة قبل الرابط إلزامية.","،.","dass/weil/wenn.","الفاصلة إلزامية."],
["التدريب: ادمج.","Ich bin krank. Ich bleibe. → weil.","أنا مريض. أبقى.","Ich bleibe, weil ich krank bin.","أبقى لأني مريض.","الدمج بالرابط."],
["اختبر: أكمل.","Ich weiß, ___ er kommt. (dass)","أعرف أنه يأتي.","___ es regnet, bleibe ich. (Weil/Wenn)","إن مطرت أبقى.","was / Als","dass / Weil-Wenn."]]],
["g28","obwohl damit bevor nachdem","روابط متقدمة","B1","konjunktion",["g27","g29"],[
["obwohl + تناقض.","Obwohl er krank ist, arbeitet er.","رغم مرضه يعمل.","الفعل أخير في الفرعية.","الفعل أخير."],
["trotzdem الرئيسية المقابلة.","Er ist krank, trotzdem arbeitet er.","مريض لكنه يعمل.","obwohl فرعية وتrotzdem رئيسية.","الزوج المتقابل."],
["damit الغرض.","Ich lerne, damit ich bestehe.","أتعلم لأنجح.","Er spart, damit er reist.","يدخر ليسافر.","الفاعلان مختلفان غالبًا.","الفاعلان مختلفان."],
["um...zu نفس الفاعل.","Ich lerne, um zu bestehen.","أتعلم لأنجح.","Er kommt, um zu helfen.","يأتي ليساعد.","الفاعل واحد.","الفاعل واحد."],
["bevor القبلية.","Bevor ich esse, wasche ich mich.","قبل الأكل أغتسل.","Ruf an, bevor du kommst.","اتصل قبل أن تأتي.","الفعل أخير."],
["nachdem البعدية + أسبق.","Nachdem ich gegessen hatte, ging ich.","بعد أن أكلت ذهبت.","الأسبق مع nachdem.","الأسبق مع nachdem."],
["während التزامن.","Während ich koche, hört er Musik.","أثناء الطبخ يستمع للموسيقى.","während + genitiv اسميًا.","الوجهان."],
["bis الحد الزمني.","Warte, bis ich komme.","انتظر حتى آتي.","Bis er kommt, lese ich.","حتى يأتي أقرأ.","الفعل أخير."],
["seit/sobald.","Seit ich hier wohne, ...","منذ سكنت هنا...","Sobald er kommt, gehen wir.","حالما يأتي نذهب.","الفعل أخير."],
["falls الاحتمال.","Falls es regnet, bleibe ich.","إن مطرت أبقى.","falls أضعف من wenn.","falls أضعف."],
["indem الوسيلة.","Er lernt, indem er liest.","يتعلم بالقراءة.","الوسيلة indem.","الوسيلة indem."],
["sodass النتيجة.","Es war laut, sodass ich nichts hörte.","كان صاخبًا فلم أسمع.","النتيجة sodass.","النتيجة sodass."],
["ohne dass/außer dass.","Er ging, ohne dass er grüßte.","ذهب دون أن يحيّي.","الاستثناء ohne dass.","الاستثناء."],
["الفرق damit/um-zu.","فاعلان مختلفان damit.","لكي.","فاعل واحد um-zu.","لكي.","الفاعل يحدد."],
["اختبر: اختر.","Ich lerne, ___ ich bestehe. (damit)","لأنجح.","___ er krank ist, arbeitet er. (Obwohl)","رغم مرضه يعمل.","um zu / Weil","damit / Obwohl."]]],
["g29","Infinitiv mit zu","المصدر مع zu","B1","infinitiv",["g28","g30"],[
["zu بعد معظم الأفعال.","Ich versuche zu schlafen.","أحاول النوم.","Er beginnt zu arbeiten.","يبدأ العمل.","Ich versuche schlafen.","zu إلزامية."],
["أفعال بلا zu: الناقصة والحواس.","Ich sehe ihn kommen.","أراه يأتي.","Lass mich schlafen.","دعني أنام.","Ich sehe ihn zu kommen.","الحواس بلا zu."],
["zu + منفصل في الوسط.","anzurufen, aufzustehen","أن يتصل، أن ينهض.","Er versucht anzurufen.","يحاول الاتصال.","zu anrufen.","zu الوسطى."],
["zu في الفرعية.","Ich freue mich, dich zu sehen.","سعيد برؤيتك.","Es ist schwer, zu verstehen.","من الصعب الفهم.","الفاصلة قبل zu غالبًا.","الفاصلة قبل zu."],
["es + صفة + zu.","Es ist wichtig zu lernen.","المهم أن تتعلم.","Es ist schön, hier zu sein.","جميل أن تكون هنا.","البنية غير الشخصية.","البنية غير الشخصية."],
["haben/sein + zu للوجوب.","Das ist zu machen.","يجب فعل هذا.","Es gibt viel zu tun.","هناك كثير لفعله.","الوجوب haben/sein+zu.","الوجوب."],
["statt/ohne + zu.","Statt zu schlafen, lernt er.","بدل النوم يتعلم.","Ohne zu fragen, ging er.","ذهب دون سؤال.","المصدر المنفي.","المصدر."],
["الأخطاء: zu بعد الناقص.","Ich will zu lernen (خطأ).","خطأ.","Ich will lernen.","أريد التعلم.","الناقص بلا zu."],
["الأخطاء: نسيان zu.","Ich versuche schlafen (خطأ).","خطأ.","Ich versuche zu schlafen.","أحاول النوم.","العادي يحتاج zu."],
["zu المزدوجة.","zu arbeiten, zu wohnen","أن يعمل، أن يسكن.","Jeder مصدر zu مستقلة.","كل مصدر zu."],
["zu مع الماضي: gemacht zu haben.","Er behauptet, gelernt zu haben.","يدعي أنه تعلم.","الماضي المصدري.","الماضي المصدري."],
["السؤال: Was zu tun?","Was soll ich tun?","ماذا أفعل؟.","zu وحدها لا تسأل.","الناقص يسأل."],
["التدريب: أكمل بـzu.","versuchen ___ (zu schlafen).","أن ينام.","beginnen ___ (zu arbeiten).","أن يعمل.","بلا zu.","zu."],
["القائمة الذهبية.","anfangen, aufhören, versuchen","يبدأ، يتوقف، يحاول.","hoffen, vergessen, versprechen","يأمل، ينسى، يعد.","كلها + zu."],
["اختبر: zu أم لا؟","Ich kann ___ (kommen, بلا).","أستطيع المجيء.","Ich versuche ___ (zu kommen).","أحاول المجيء.","zu / بلا","بلا / zu."]]],
["g30","Relativsätze","جمل الوصل","B1","relativ",["g27","g31"],[
["der/die/das كضمير وصل.","Der Mann, der dort steht, ...","الرجل الواقف هناك...","Die Frau, die lacht, ...","المرأة التي تضحك...","الوصل يطابق الموصوف جنسًا وعددًا."],
["الوصل في النصب: den/die/das.","Den Film, den ich sah, ...","الفيلم الذي رأيته...","Das Buch, das ich lese, ...","الكتاب الذي أقرؤه...","الحالة من وظيفة الوصل."],
["الوصل في الجر: dem/der.","Der Freund, dem ich helfe, ...","الصديق الذي أساعده...","Die Stadt, in der ich wohne, ...","المدينة التي أسكنها...","الحرف يحدد الحالة."],
["الفعل أخير في الوصل.","der Mann, der dort steht","الرجل الواقف هناك.","das Kind, das spielt","الطفل الذي يلعب.","الوصل فرعية."],
["الفواصل حول الوصل إلزامية.","Mein Bruder, der Arzt ist, ...","أخي — وهو طبيب —...","الفاصلة قبل وبعد.","الفاصلة."],
["was للعموم وغير المحدد.","Alles, was ich habe, ...","كل ما أملك...","Das Beste, was es gibt, ...","أفضل ما يوجد...","العموم was."],
["wo للمدن والأماكن.","Die Stadt, wo ich wohne, ...","المدينة حيث أسكن...","Der Platz, wo wir uns trafen, ...","المكان حيث التقينا...","الأماكن wo."],
["الوصل بالحرف: worüber.","Das Thema, worüber wir sprechen, ...","الموضوع الذي نتحدث عنه...","wo(r)+حرف للأشياء.","للأشخاص الحرف+الوصل."],
["حذف الوصل ممنوع.","The man I saw (إنجليزية).","ممنوع ألمانيًا.","Der Mann, den ich sah, ...","الرجل الذي رأيت...","الحذف خطأ."],
["الوصل الطويل.","Der Mann, den ich gestern am Bahnhof getroffen habe, ...","الرجل الذي قابلته أمس في المحطة...","الفعل أخير مهما طال.","الفعل أخير."],
["الوصل والملكية: dessen/deren.","Der Mann, dessen Auto...","الرجل الذي سيارته...","Die Frau, deren Kind...","المرأة التي طفلها...","الملكية dessen/deren."],
["الوصل الرسمي: welcher.","Der Film, welcher... (رسمي).","الفيلم الذي...","der geläufiger.","der أشيع."],
["الوصل والتوكيد.","Es ist mein Bruder, der...","إنه أخي الذي...","التقديم للتوكيد.","التقديم."],
["الأخطاء: der/dem.","dem للجر فقط.","للجر.","den للنصب المذكر.","للنصب."],
["اختبر: اختر الوصل.","Der Mann, ___ dort steht (der).","الواقف هناك.","Die Frau, ___ ich helfe (der).","التي أساعدها.","den / die","der / der."]]]
];
if(typeof module!=="undefined")module.exports={GT1};
