/* Grammar topics 31-60. Same UNIT format as grammar1.js */
"use strict";
const GT2=[
["g31","Imperativ","صيغة الأمر","A1","imperativ",["g01","g15"],[
["الأمر المف informal: جذع الفعل.","Komm! Geh! Mach!","تعال! اذهب! افعل!","Trink Wasser!","اشرب ماءً!","Du komm!","Komm!","الجذع وحده يكفي."],
["الأمر الجمع: جذع + t.","Kommt! Geht! Macht!","تعالوا! اذهبوا! افعلوا!","Trinkt das!","اشربوا هذا!","Komme! (للجمع)","Kommt!","الجمع -t."],
["الأمر الرسمي: Sie + مصدر.","Kommen Sie!","تفضل!","Setzen Sie sich!","اجلس من فضلك!","Kommt Sie!","Kommen Sie!","المصدر + Sie."],
["الأمر المنفي: nicht.","Komm nicht zu spät!","لا تتأخر!","Mach das nicht!","لا تفعل هذا!","Nicht komm!","Komm nicht!","الفعل أولًا."],
["الأمر المنفصل: المقطع أخيرًا.","Steh auf!","انهض!","Ruf an!","اتصل!","Aufsteh!","Steh auf!","المقطع أخير."],
["الأمر الانعكاسي.","Setz dich!","اجلس!","Beeil dich!","أسرع!","Setze dich (رسمية).","Setz dich!","الضمير بعد الفعل."],
["الأمر المهذب بـ bitte.","Komm bitte her.","تعال من فضلك.","Helfen Sie mir bitte.","ساعدني من فضلك.","bitte أولًا إلزامًا.","bitte مرن الموضع."],
["الأمر المقترح: Lass uns...","Lass uns gehen.","هيا نذهب.","Lasst uns essen.","هيا نأكل.","Lassen uns.","Lass uns."],
["sein/haben الشاذة.","Sei ruhig!","اهدأ!","Hab Geduld!","اصبر!","Seie ruhig!","Sei ruhig!","شاذة تُحفظ."],
["الأمر بالصيغة العامة.","Nicht rauchen!","ممنوع التدخين!","Bitte anstellen!","الاصطفاف من فضلك!","اللافتات مصدر.","اللافتات مصدر."],
["أمر النصائح الصحية.","Trink viel Wasser!","اشرب كثيرًا!","Iss langsam!","كُل ببطء!","النصيحة أمر لطيف.","النصيحة أمر."],
["أمر الاتجاهات.","Geh geradeaus!","امشِ مستقيمًا!","Bieg links ab!","انعطف يسارًا!","الاتجاهات أوامر.","الاتجاهات أوامر."],
["الأمر والتوكيد doch/mal.","Komm doch mit!","تعال معنا إذن!","Schau mal her!","انظر هنا!","الجسيمات تلطف.","الجسيمات تلطف."],
["أخطاء الأمر.","Gehe nicht (رسمي زائد).","رسمي.","Geh nicht!","لا تذهب!","الزيادة e اختيارية."],
["اختبر: كوّن أمرًا.","kommen (du) → ___!","تعال!","aufstehen (ihr) → ___!","انهضوا!","Kommt / Steht auf","Komm! / Steht auf!"]]],
["g32","Konjunktiv II","الشرطي الثاني","A2","konjunktiv",["g14","g33"],[
["للتمني والافتراض.","Ich wäre gern da.","ليتني هناك.","Hätte ich Zeit!","لو كان لدي وقت!","التمني ماضٍ صوري."],
["würde + مصدر للاحتمال.","Ich würde helfen.","سأساعد.","Würdest du kommen?","هل ستأتي؟","الأشيع محكيًا."],
["wäre/hätte/ginge الشاذة.","wäre, hätte, könnte","لكان، لكان لديه، لاستطاع.","würde sein (بديل).","الأصل أرقى."],
["النصيحة: solltest.","Du solltest schlafen.","عليك النوم.","Du solltest zum Arzt.","زر الطبيب.","النصيحة solltest."],
["الطلب المهذب.","Könnten Sie helfen?","هل تساعدني؟","Würden Sie bitte...?","هل تتفضل...؟","التهذيب شرطي."],
["الشرط بـ wenn.","Wenn ich könnte, käme ich.","لو استطعت لأتيت.","Wenn du wolltest...","لو أردت...","الفعل أخير."],
["الشرط بلا wenn.","Käme er, freute ich mich.","إن أتى لفرحت.","الترتيب يعوّض.","الترتيب يعوّض."],
["المقارنة الخيالية als ob.","als ob er krank wäre.","كأنه مريض.","tut als ob.","يتظاهر.","als ob + شرطي."],
["الندم: hätte...sollen.","Ich hätte lernen sollen.","كان عليّ التعلم.","Hättest du kommen können!","لو أتيت!","الندم ماضٍ مزدوج."],
["الأمنية بـ nur/doch.","Wenn er nur käme!","ليته يأتي!","Wäre ich doch da!","ليتني هناك!","التوكيد nur/doch."],
["الاحتمال العلمي.","Das wäre möglich.","قد يكون ممكنًا.","Es könnte regnen.","قد تمطر.","الظن würde/könnte."],
["الفرق würde/käme.","käme أرقى كتابيًا.","لأتى.","würde kommen أشيع.","سوف يأتي.","المقام يحدد."],
["الشرطي في الفرعية.","dass er käme.","أنه سيأتي.","الفعل أخير.","الفعل أخير."],
["الأخطاء: würde مزدوج.","würde kommen würde.","خطأ.","würde kommen.","يكفي واحدة."],
["اختبر: أكمل.","Wenn ich Zeit ___ (hätte).","لو كان لدي وقت.","Ich ___ helfen. (würde)","سأساعد."]]],
["g33","Passiv","المبني للمجهول","A2","passiv",["g18","g32"],[
["werden + الثالث.","Das Haus wird gebaut.","يُبنى البيت.","Es wird gemacht.","يُفعل.","التركيز على الحدث."],
["الفاعل بـ von.","Von wem? — Von mir.","من؟ — مني.","Das Buch wurde von ihm geschrieben.","كُتب بواسطته.","von للفاعل."],
["الوسيلة بـ mit.","mit dem Bus fahren (نشط).","بالحافلة.","Mit Wasser waschen.","بالماء.","mit للوسيلة."],
["الماضي: wurde + الثالث.","Es wurde gemacht.","فُعل.","Sie wurden eingeladen.","دُعوا.","wurde للماضي."],
["التام: worden.","Es ist gemacht worden.","قد فُعل.","Er ist operiert worden.","أُجريت له عملية.","worden بلا ge."],
["المستقبل: wird gemacht werden.","Es wird gemacht werden.","سيُفعل.","مزدوج werden.","مزدوج werden."],
["الناقص: muss gemacht werden.","Es muss gemacht werden.","يجب فعله.","الناقص قبل werden.","الناقص قبل werden."],
["man بديل المحكي.","Man macht das so.","هكذا يُفعل.","بديل سهل.","بديل سهل."],
["sein-Passiv للنتيجة.","Die Tür ist geöffnet.","الباب مفتوح.","Er ist verletzt.","مصاب.","النتيجة sein."],
["الفرق werden/sein.","wird geöffnet (عملية).","يُفتح.","ist geöffnet (حالة).","مفتوح.","العملية/الحالة."],
["الأفعال بلا مجهول.","haben, wissen, kennen.","يملك، يعرف.","لا مجهول لها.","لا مجهول."],
["الأسئلة بالمجهول.","Wird das gemacht?","هل يُفعل هذا؟","V2 كالمعتاد.","V2."],
["المجهول والنفي.","Es wird nicht gemacht.","لا يُفعل.","النفي قبل الثالث.","النفي قبل الثالث."],
["المجهول الرسمي.","Es wird gebeten...","يُرجى...","Bitte-Sprache.","لغة اللافتات."],
["اختبر: ابنِ للمجهول.","Er baut das Haus. → ___","يُبنى البيت.","Das Haus wird gebaut.","يُبنى البيت."]]],
["g34","Adverbien & Position","الظروف ومواضعها","A1","adverb",["g01","g21"],[
["الظرف أولًا يقلب الفاعل.","Heute komme ich.","اليوم آتي.","Oft lernt er.","غالبًا يتعلم.","Heute ich komme.","V2 ثابت."],
["التكرار: oft selten nie.","oft, manchmal, selten","غالبًا، أحيانًا، نادرًا.","nie, immer","أبدًا، دائمًا.","الوسط غالبًا."],
["الترتيب te-ka-mo-lo.","morgens gut zu Hause","صباحًا جيدًا في البيت.","Ich lerne morgens gut zu Hause.","أتعلم صباحًا جيدًا في البيت.","القاعدة الإيقاعية."],
["الظرف قبل الصفة.","sehr gut, zu teuer","جيد جدًا، غالٍ جدًا.","ganz neu","جديد تمامًا.","التقوية قبل الصفة."],
["الظرف بعد الفعل.","Er läuft schnell.","يركض بسرعة.","Sie singt schön.","تغني جميلًا.","الملاصقة للفعل."],
["auch/denn في الوسط.","Ich auch!","أنا أيضًا!","Komm doch!","تعال إذن!","الجسيمات وسط."],
["leider للأسف.","Leider bin ich krank.","للأسف مريض.","الافتتاحية leider.","الافتتاحية."],
["schon/noch للزمن.","schon fertig","انتهى already.","noch nicht","ليس بعد.","الزمن الدقيق."],
["gern/lieber للرغبة.","Ich trinke gern Tee.","أحب الشاي.","Am liebsten Kaffee.","أفضل القهوة.","الرغبة gern."],
["vielleicht للاحتمال.","Vielleicht komme ich.","ربما آتي.","الاحتمال أولًا أو وسطًا."],
["kaum/fast للتقريب.","fast fertig","يكاد ينتهي.","kaum Zeit","بالكاد وقت.","التقريب."],
["zusammen/allein للصحبة.","allein wohnen","يسكن وحده.","zusammen lernen","يتعلمان معًا."],
["täglich/wöchentlich.","täglich üben","التدرب يوميًا.","التكرار المنتظم."],
["الأخطاء: الظرف كالصفة.","schneller Fahrer vs schnell fahren.","سائق سريع مقابل يقود بسرعة.","الصفة تُعرب والظرف لا."],
["اختبر: رتّب.","Ich / lerne / morgens / gut.","أتعلم صباحًا جيدًا.","Ich lerne morgens gut.","الترتيب الصحيح."]]],
["g35","Präfixe: trennbar/untrennbar","السوابق","A2","verben",["g15","g36"],[
["المنفصلة مشددة: an- auf-...","anrufen, aufstehen","يتصل، ينهض.","النبرة على المقطع.","النبرة تحدد."],
["المتصلة غير مشددة: be- ver-...","verkaufen, verstehen","يبيع، يفهم.","النبرة على الجذع.","النبرة تحدد."],
["be- تجعل لازمًا متعديًا.","antworten → beantworten","يجيب → يجيب عن.","Der Brief beantwortet die Frage.","الخطاب يجيب عن السؤال.","التعدية."],
["ver- للتغير والخطأ.","verkaufen, verlieren","يبيع، يفقد.","sich verirren","يضيع.","المعاني المشتقة."],
["er- للنتيجة.","erzählen, erreichen","يروي، يصل إلى.","lernen → erlernen","يتعلم → يتقن.","النتيجة."],
["ent- للإزالة والبدء.","entdecken, entstehen","يكتشف، ينشأ.","sich entscheiden","يقرر.","الإزالة/البدء."],
["zer- للتدمير.","zerbrechen","يتحطم.","Das Glas zerbricht.","يتحطم الزجاج.","التدمير."],
["miss- للخطأ.","verstehen vs missverstehen","يفهم مقابل يسيء الفهم.","النبرة جذعية.","النبرة جذعية."],
["durch-über-um مزدوجة.","umstellen (منفصل).","يعيد الترتيب.","umstellen (متصل).","يُحاصر.","النبرة تحسم."],
["wieder مزدوجة.","wiederholen (متصل).","يكرر.","wiederkommen (منفصل).","يعود.","النبرة تحسم."],
["voll- مزدوجة.","vollenden (متصل).","يُتم.","volltanken (منفصل).","يملأ الوقود.","النبرة تحسم."],
["الأخطاء: فصل المتصل.","Ich verstehe auf (خطأ).","خطأ.","Ich verstehe.","المتصل لا ينفصل."],
["الحفظ بالنبرة.","ANrufen vs verKAUfen.","يتصل مقابل يبيع.","اسمع النبرة.","اسمع النبرة."],
["القائمة الذهبية.","be-, emp-, ent-, er-, ge-, miss-, ver-, zer- متصلة.","متصلة دائمًا.","احفظها."],
["اختبر: منفصل أم متصل؟","anrufen → ___","يتصل.","verkaufen → ___","يبيع.","beide trennbar","منفصل/متصل."]]],
["g36","N-Deklination","الأسماء الضعيفة","A2","nomen",["g09","g37"],[
["الفئة: مذكر بـ -e غالبًا.","der Junge, des Jungen","الفتى.","der Kollege","الزميل.","-n في كل الحالات عدا الرفع."],
["المهن والجنسيات.","der Student, der Experte","الطالب، الخبير.","der Nachbar, der Bauer","الجار، المزارع.","القائمة محدودة."],
["الحيوانات المذكرة.","der Löwe, der Affe","الأسد، القرد.","der Bär, der Hase","الدب، الأرنب.","مجموعة محفوظة."],
["الأجنبية: -ant -ent -ist.","der Polizist, des Polizisten","الشرطي.","der Patient","المريض.","الدخيل العلمي."],
["القلب: das Herz.","das Herz, des Herzens","القلب.","唯一的 -ens.","حالة خاصة."],
["الجمع -n منتظم.","die Jungen, die Studenten","الفتية، الطلاب.","الجمع سهل.","الجمع سهل."],
["الفرق القوي/الضعيف.","der Lehrer (قوي).","المعلم.","der Student (ضعيف).","الطالب.","النهاية -e تحسم غالبًا."],
["في الجملة.","Ich sehe den Studenten.","أرى الطالب.","mit dem Kollegen","مع الزميل.","-n إلزامية."],
["الأخطاء: نسيان n.","des Student (خطأ).","خطأ.","des Studenten.","-n إلزامية."],
["الأخطاء: n زائدة.","des Lehrern (خطأ).","خطأ.","des Lehrers.","القوي s."],
["التدريب: أكمل.","mit ___ (dem Jungen).","مع الفتى.","für ___ (den Patienten).","للمريض."],
["القائمة الكاملة.","Junge, Kollege, Kunde, Nachbar, Name, Student...","فتى، زميل، زبون، جار، اسم، طالب.","احفظ القائمة."],
["Name الخاص.","der Name, des Namens","الاسم.","-ns الخاصة.","-ns الخاصة."],
["الأسماء بـ -or.","der Doktor (قوي غالبًا).","الدكتور.","der Professor (ضعيف)!","الأستاذ.","احذر الاستثناءات."],
["اختبر: ضع النهاية.","Ich helfe dem ___ (Student).","أساعد الطالب.","dem Studenten.","-n."]]],
["g37","Komposita","الكلمات المركبة","A2","wortbildung",["g03","g38"],[
["الرأس الأخير يحدد الجنس.","die Tür → die Haustür","الباب → باب البيت.","der Hof → der Bahnhof","الساحة → المحطة.","انظر للأخير."],
["الرأس يحدد الجمع.","die Türen → die Haustüren","الأبواب.","die Höfe → die Bahnhöfe","المحطات.","اجمع الرأس."],
["حرف الوصل -s-.","das Haus + die Tür = die Haustür","باب البيت.","die Arbeit + der Platz = der Arbeitsplatz","مكان العمل.","الوصل -s- شائع."],
["حرف الوصل -n-.","die Blume + der Topf = der Blumentopf","مزهرية.","-n- الوصلية.","-n- الوصلية."],
["حرف الوصل -en-.","die Straße + die Bahn = die Straßenbahn","الترام.","-en- الوصلية.","-en- الوصلية."],
["بلا وصلة كثيرًا.","das Hotel + das Zimmer = das Hotelzimmer","غرفة الفندق.","التحام مباشر.","التحام مباشر."],
["المعنى: الأول يخصص الثاني.","der Kühlschrank (خزانة باردة).","الثلاجة.","der Handschuh (حذاء اليد).","القفاز.","التخصيص."],
["المركبات الطويلة.","die Krankenversicherungskarte","بطاقة التأمين الصحي.","قسّم من اليمين.","قسّم من اليمين."],
["الفعل + اسم.","das Schlafzimmer (schlafen).","غرفة النوم.","der Wohnraum","مساحة المعيشة.","الجذع الفعلي."],
["الصفة + اسم.","der Hochhaus (hoch).","البناية العالية.","das Kleinkind","الطفل الصغير.","الوصف."],
["الأخطاء: جنس الأول.","das Tür (خطأ).","خطأ.","die Tür.","الرأس يحكم."],
["الأخطاء: جمع الأول.","die Häusetüren (خطأ).","خطأ.","die Haustüren.","الرأس فقط."],
["التدريب: ركّب.","Haus + Tür → ___","باب البيت.","die Haustür.","الرأس مؤنث."],
["المركبات والكتابة.","كلمة واحدة بلا مسافة.","كلمة واحدة.","Getrennt = خطأ.","ملتصقة."],
["اختبر: حدد الجنس.","Bahnhof → ___ (der).","المحطة.","Krankenkasse → ___ (die).","التأمين الصحي."]]],
["g38","Partizipien als Adjektive","التصاريف كصفات","A2","adjektiv",["g18","g39"],[
["الثالث كصفة: -t/-en.","gekocht, gelesen","مطبوخ، مقروء.","das gekochte Ei","البيضة المسلوقة.","يُعرب كالصفة."],
["الحاضر كصفة: -d.","lachend, schlafend","ضاحك، نائم.","das lachende Kind","الطفل الضاحك.","-d الحاضر."],
["الترتيب قبل الاسم.","die geöffnete Tür","الباب المفتوح.","der verlorene Schlüssel","المفتاح المفقود.","يُعرب."],
["بعد sein مسندًا.","Die Tür ist geöffnet.","الباب مفتوح.","Er ist verletzt.","مصاب.","بلا نهاية."],
["الفرق النشط/المنفعل.","der weinende Junge (نشط).","الفتى الباكي.","das gestohlene Auto (منفعل).","السيارة المسروقة.","الحاضر نشط والثالث منفعل."],
["التعبيرات الثابتة.","frisch gebacken","طازج الخبز.","gut gekleidet","أنيق.","محفوظات."],
["المركبات الوصفية.","der neueste Film","أحدث فيلم.","die sogenannte Lösung","الحل المزعوم.","الوظيفة وصفية."],
["الإعلانات واللافتات.","Geöffnet! Geschlossen!","مفتوح! مغلق!","Rauchen verboten!","ممنوع التدخين!","لغة اللافتات."],
["الأخطاء: ge زائدة.","geöffnetet (خطأ).","خطأ.","geöffnet.","التصريف يكفي."],
["الأخطاء: -d ناقصة.","lachen Kind (خطأ).","خطأ.","lachendes Kind.","-d إلزامية."],
["التدريب: صِف.","Tür/offen → ___","الباب المفتوح.","die geöffnete Tür.","الثالث + إعراب."],
["الوصل البديل.","die Tür, die geöffnet ist.","الباب المفتوح.","الوصف = وصل مختصر.","الوصل البديل."],
["الاستعمال الأدبي.","die untergehende Sonne","الشمس الغاربة.","die strahlende Zukunft","المستقبل المشرق."],
["الحدود: ليس كل فعل يصلح.","*der gegangene Mann (نادر).","نادر.","الحركة تُقيد.","الحركة تُقيد."],
["اختبر: اختر.","___ Kind (lachend).","الطفل الضاحك.","das lachende Kind.","-d + إعراب."]]],
["g39","Modalpartikeln","جسيمات المحكي","A2","stil",["g34","g40"],[
["doch للتوكيد والتعارض.","Komm doch mit!","تعال إذن!","Das ist doch klar.","هذا واضح حقًا.","التلطيف والتوكيد."],
["mal للتخفيف.","Schau mal!","انظر!","Warte mal!","انتظر قليلًا!","الأمر اللطيف."],
["denn في السؤال.","Was ist denn los?","ما الأمر؟","Wo bist du denn?","أين أنت؟","الفضول اللطيف."],
["eigentlich للتدقيق.","Wo wohnst du eigentlich?","أين تسكن أصلًا؟","التدقيق المهذب."],
["ja للمعروف المشترك.","Das ist ja klar.","هذا واضح كما تعلم.","المشترك ja."],
["eben/halt للاستسلام.","Es ist eben so.","هكذا الأمر.","التسليم eben."],
["wohl للتخمين.","Er ist wohl krank.","لابد مريض.","التخمين wohl."],
["etwa للدهشة.","Bist du etwa krank?","أمريض أنت؟!","الدهشة etwa."],
["bloß/nur للتحذير.","Pass bloß auf!","احذر!","Be Jung nur ruhig!","اهدأ فقط!","التحذير."],
["schon للتطمين.","Das wird schon.","سيكون بخير.","Wird schon gut.","سيتحسن.","التطمين."],
["ruhig للإذن.","Komm ruhig rein.","ادخل مطمئنًا.","الإذن ruhig."],
["vielleicht للتخفيف.","Das ist vielleicht gut.","ربما جيد.","التخفيف."],
["الموضع: الوسط.","الفعل ثم الجسيم.","الفعل ثم الجسيم.","Komm doch mal!","الوسط."],
["الكتابي يتجنبها.","نادرًا في الرسميات.","نادرًا.","المحكي فقط."],
["اختبر: لطّف الأمر.","Komm her! → ___","تعال هنا!","Komm doch mal her!","الجسيمات."]]],
["g40","Indirekte Rede","الكلام غير المباشر","A2","konjunktiv",["g32","g41"],[
["er sagt, dass...","Er sagt, dass er krank ist.","يقول إنه مريض.","الهيكل الأساسي."],
["السؤال غير المباشر ob.","Er fragt, ob du kommst.","يسأل إن كنت ستأتي.","ob للـja/nein."],
["السؤال بـ W.","Er fragt, wo du wohnst.","يسأل أين تسكن.","الأداة + فعل أخير."],
["الأمر غير المباشر sollen.","Er sagt, ich soll warten.","يقول عليّ الانتظار.","sollen للأمر المنقول."],
["Konjunktiv I الرسمي.","Er sagt, er sei krank.","يقول إنه مريض (رسمي).","sei/st/cht."],
["المحكي: Indikativ يكفي.","Er sagt, er ist krank.","يقول إنه مريض.","المحكي مباشر."],
["الضمائر تتغير.","Ich → er, mein → sein.","أنا → هو.","منظور الناقل."],
["الأزمنة تتغير منطقيًا.","gestern → am Tag zuvor.","أمس → اليوم السابق.","الإحالة الزمنية."],
["hier/dort التحويل.","Bring es her → bringen.","أحضره.","الاتجاه يتبدل."],
["الطلب الرسمي.","Er bittet mich zu kommen.","يطلب مني المجيء.","bitten + zu."],
["النفي المنقول.","Er sagt, er komme nicht.","يقول إنه لن يأتي.","النفي ينتقل."],
["التحية المنقولة.","Er lässt dich grüßen.","يُقرئك السلام.","lassen grüßen."],
["الترتيب: فعل أخير.","dass/ob/W + فعل أخير.","أن/هل + فعل أخير.","القاعدة ثابتة."],
["الأخطاء: نسيان التحويل.","Er sagt, dass ich krank bin (وهو المريض).","خطأ الضمير.","المنظور."],
["اختبر: انقل.","Er sagt: Ich bin müde. → ___","يقول إنه متعب.","Er sagt, dass er müde ist.","الضمير والفعل."]]],
["g41","Lassen & Brauchen","أفعال خاصة","A2","verben",["g14","g42"],[
["lassen = يدع/يترك.","Lass mich schlafen.","دعني أنام.","Lass das!","اترك هذا!.","بلا zu."],
["lassen = يكلّف.","Ich lasse mein Auto reparieren.","أصلح سيارتي (عند مختص).","التكليف lassen."],
["lassen + sich للاحتمال.","Das lässt sich machen.","يمكن فعله.","الصيغة السلبية الأنيقة."],
["Gruß lassen.","Lass Mama grüßen.","أقرئ أمك السلام.","الصيغة الاجتماعية."],
["brauchen nicht + zu.","Du brauchst nicht zu kommen.","لا حاجة للمجيء.","النفي brauchen + zu."],
["brauchen + zu المثبت.","Du brauchst nur zu fragen.","يكفي أن تسأل.","المثبت + zu."],
["scheinen + zu.","Er scheint krank zu sein.","يبدو مريضًا.","الظهور scheinen."],
["drohen + zu.","Es droht zu regnen.","يهدد بالمطر.","التهديد drohen."],
["pflegen + zu للعادة.","Er pflegt früh aufzustehen.","اعتاد النهوض مبكرًا.","العادة pflegen."],
["versprechen + zu.","Er verspricht zu helfen.","يعد بالمساعدة.","الوعد + zu."],
["behaupten + الماضي المصدري.","Er behauptet, gelernt zu haben.","يدعي التعلم.","الماضي المصدري."],
["glauben + zu.","Ich glaube zu verstehen.","أظن أنني أفهم.","الظن + zu."],
["hoffen + zu.","Ich hoffe zu bestehen.","آمل النجاح.","الأمل + zu."],
["الأخطاء: zu بعد lassen.","Lass zu schlafen (خطأ).","خطأ.","Lass schlafen.","lassen بلا zu."],
["اختبر: أكمل.","Lass mich ___ (schlafen).","دعني أنام.","Du brauchst nicht ___ (zu kommen).","لا حاجة للمجيء."]]],
["g42","Vergleiche & Proportional","التناسب والمقارنة المتقدمة","A2","adjektiv",["g22","g43"],[
["immer + مقارنة.","immer besser","يتحسن.","immer teurer","يزداد غلاءً.","التقدم."],
["je...desto/je...umso.","Je mehr, umso besser.","كلما أكثر كان أفضل.","desto/umso سيان."],
["Vergleich mit Satz.","größer, als ich dachte.","أكبر مما ظننت.","als + جملة.","als + جملة."],
["so + صفة + wie möglich.","so schnell wie möglich.","بأسرع ما يمكن.","الصيغة القصوى العملية."],
["zu + صفة + zum.","zu teuer zum Kaufen.","غالٍ جدًا للشراء.","الغاية zum."],
["genug + zu.","gut genug zum Leben.","جيد بما يكفي للعيش.","الكفاية genug."],
["Unterschied: anders als.","anders als ich.","مختلف عني.","anders als للمغايرة."],
["gleich/selbe.","der gleiche Mann.","نفس الرجل.","gleich النوع وselbe الهوية."],
["Vergleiche im Beruf.","effizienter arbeiten.","العمل بكفاءة أكبر.","لغة العمل."],
["Sportvergleiche.","schneller laufen.","الجري أسرع.","لغة الرياضة."],
["Preisvergleiche.","billiger einkaufen.","التسوق أرخص.","لغة التسوق."],
["Wettervergleiche.","wärmer als gestern.","أدفأ من أمس.","لغة الطقس."],
["Steigerung mit viel/weitaus.","viel besser.","أفضل بكثير.","weitaus الأرقى."],
["Doppelte Steigerung.","mehr und mehr.","أكثر فأكثر.","التكرار التصاعدي."],
["اختبر: أكمل.","so schnell ___ möglich.","بأسرع ما يمكن.","wie.","so...wie."]]],
["g43","Zahlen Daten Uhrzeit","الأرقام والتواريخ والساعة","A1","zahlen",["g21","g44"],[
["الأعداد 0-12 حفظًا.","null bis zwölf.","صفر إلى اثني عشر.","eins→eine (المؤنث).","التذكير/التأنيث."],
["13-19: -zehn.","dreizehn, vierzehn.","ثلاثة عشر...","sechszehn (بلا s).","الاستثناءات."],
["العشرات: -zig.","zwanzig, dreißig.","عشرون، ثلاثون.","sechzig (بلا s).","الاستثناءات."],
["المركبات مع und.","einundzwanzig.","واحد وعشرون.","الواحد أولًا!","الترتيب الألماني."],
["المئات والآلاف.","einhundert, eintausend.","مائة، ألف.","zweihundert.","التركيب."],
["الترتيبية: -te/-ste.","der erste, der zweite.","الأول، الثاني.","der dritte (شاذ).","الشواذ."],
["الساعة الرسمية.","Es ist dreizehn Uhr.","الواحدة ظهرًا.","vierzehn Uhr dreißig.","الثانية والنصف.","24 ساعة رسميًا."],
["الساعة المحكية.","halb drei = 2:30.","الثانية والنصف.","viertel vor/nach.","إلا ربع/وربع.","المنطقة تختلف!"],
["halb + التالية.","halb vier = 3:30.","الثالثة والنصف.","halb = النصف نحو التالية.","القاعدة المحيرة."],
["التواريخ.","am dritten Mai.","في الثالث من مايو.","der 3. Mai.","النقطة بعد الرقم."],
["السنوات.","im Jahr 2024.","سنة 2024.","zweitausendvierundzwanzig.","النطق."],
["الأسعار.","3,50 Euro (فاصلة!).","3.50 يورو.","الفاصلة العشرية ألمانيًا."],
["النسب.","50 Prozent.","خمسون بالمئة.","Prozent مفرد دائمًا."],
["الهواتف.","die Null einzeln.","الصفر منفردًا.","Null→nulo? لا: null.","النطق الرقمي."],
["اختبر: اقرأ.","21 → ___","واحد وعشرون.","einundzwanzig.","الواحد أولًا."]]],
["g44","Meinung äußern","إبداء الرأي","A2","kommunikation",["g27","g45"],[
["Ich finde, dass...","Ich finde, dass es gut ist.","أرى أنه جيد.","الرأي finde."],
["Meiner Meinung nach...","Meiner Meinung nach ist es teuer.","برأيي غالٍ.","الصيغة الرسمية."],
["Ich bin dafür/dagegen.","Ich bin dafür.","أنا مع.","dafür/dagegen."],
["Vorteil/Nachteil.","Ein Vorteil ist...","الميزة...","Der Nachteil ist...","العيب..."],
["Einerseits...andererseits.","Einerseits billig, andererseits...","من جهة رخيص ومن جهة...","التوازن."],
["Zustimmung.","Da stimme ich zu.","أوافق.","Da hast du recht.","معك حق."],
["Widerspruch höflich.","Da bin ich anderer Meinung.","لي رأي مختلف.","الاعتراض المهذب."],
["Verstärkung.","Auf jeden Fall!","بالتأكيد!","Absolut!","تمامًا!"],
["Abschwächung.","Vielleicht, aber...","ربما، لكن...","Jein.","نعم-لا."],
["Beispiele geben.","Zum Beispiel...","مثلًا...","Beispielsweise...","على سبيل المثال."],
["Zusammenfassen.","Zusammenfassend...","خلاصة...","Insgesamt...","إجمالًا."],
["Schlussfolgern.","Also finde ich...","لذا أرى...","Deshalb...","لذلك."],
["Nachfragen.","Was meinst du dazu?","ما رأيك؟","Wie siehst du das?","كيف ترى؟"],
["Thema wechseln.","Übrigens...","بالمناسبة...","Was anderes:...","موضوع آخر."],
["اختبر: عبّر.","Ich ___ (finde), dass...","أرى أن...","Meiner Meinung nach.","الصيغتان."]]],
["g45","Telefonieren & Termine","الهاتف والمواعيد","A1","kommunikation",["g44","g46"],[
["التحية الهاتفية.","Guten Tag, hier spricht Ahmed.","مرحبًا، معك أحمد.","hier spricht..."],
["السؤال عن الشخص.","Kann ich bitte Frau Müller sprechen?","هل يمكنني التحدث مع السيدة؟","الصيغة الرسمية."],
["غير موجود.","Er ist gerade nicht da.","غير موجود الآن.","Kann ich etwas ausrichten?","هل أبلغه شيئًا؟"],
["ترك رسالة.","Rufen Sie bitte zurück.","عاود الاتصال من فضلك.","Ich rufe später an.","سأتصل لاحقًا."],
["تحديد موعد.","Ich hätte gern einen Termin.","أود موعدًا.","Passt es Ihnen am Montag?","هل يناسبك الاثنين؟"],
["التأكيد.","Abgemacht!","اتفقنا!","Bis Montag um 10 Uhr.","حتى الاثنين العاشرة."],
["التأجيل.","Können wir verschieben?","هل نؤجل؟","Leider muss ich absagen.","للأسف يجب الإلغاء."],
["التأخير.","Ich komme 10 Minuten später.","سأتأخر 10 دقائق.","Entschuldigen Sie die Verspätung.","عذرًا على التأخير."],
["الفهم.","Könnten Sie das wiederholen?","هل تكرر؟","Ich höre Sie schlecht.","أسمعك بصعوبة."],
["الأرقام هاتفيًا.","Null, Zwo (2 عامية هاتفية).","صفر، اثنان.","Buchstabieren.","التهجئة."],
["الإنهاء.","Vielen Dank, tschüss!","شكرًا، وداعًا.","Danke für Ihren Anruf.","شكرًا لاتصالك."],
["الخطأ.","Falsch verbunden.","رقم خاطئ.","Entschuldigung!","عذرًا!"],
["الطوارئ.","Rufen Sie einen Krankenwagen!","اتصل بالإسعاف!","110/112.","الأرقام."],
["البريد الصوتي.","Bitte hinterlassen Sie eine Nachricht.","اترك رسالة.","nach dem Piepton.","بعد الصافرة."],
["اختبر: أكمل.","Hier spricht ___ (Ahmed).","معك أحمد.","Kann ich ___ sprechen?","هل أكلم...؟"]]],
["g46","Einkaufen & Reklamation","التسوق والشكوى","A1","kommunikation",["g45","g47"],[
["السؤال عن السعر.","Wie viel kostet das?","كم سعره؟","Was macht das zusammen?","كم المجموع؟"],
["الطلب.","Ich hätte gern...","أود...","Ich nehme das.","سآخذ هذا."],
["المقاس.","Haben Sie Größe M?","هل لديك مقاس M؟","Kann ich es anprobieren?","هل أجربه؟"],
["الدفع.","Kann ich mit Karte zahlen?","هل أدفع بالبطاقة؟","Bar oder mit Karte?","نقدًا أم بطاقة؟"],
["الخصم.","Gibt es Rabatt?","هل يوجد خصم؟","Das ist zu teuer.","غالٍ جدًا."],
["الاستبدال.","Ich möchte umtauschen.","أريد الاستبدال.","Geht das auch in Blau?","هل يوجد بالأزرق؟"],
["الشكوى المهذبة.","Leider ist es kaputt.","للأسف معطل.","Ich möchte mich beschweren.","أريد الشكوى."],
["الضمان.","Haben Sie die Quittung?","هل معك الإيصال؟","Garantie zwei Jahre.","ضمان سنتين."],
["المقارنة.","Das ist billiger.","هذا أرخص.","LEIDER ausverkauft.","للأسف نافد."],
["الكمية.","Ein Kilo Äpfel, bitte.","كيلو تفاح.","Noch etwas?","شيء آخر؟"],
["الوزن والعدد.","Darf es etwas mehr sein?","هل يمكن زيادة؟","Passt so.","يكفي."],
["السوق الأسبوعي.","Frisch vom Markt.","طازج من السوق.","Handel und Feilschen.","المساومة محدودة."],
["السوبرماركت.","Wo finde ich Milch?","أين الحليب؟","An der Kasse.","عند الصندوق."],
["الإرجاع.","Ich gebe es zurück.","أُعيده.","Geld zurück.","استرداد المال."],
["اختبر: تسوّق.","___ kostet das? (Wie viel)","كم سعره؟","Ich ___ gern (hätte).","أود."]]],
["g47","Arztbesuch & Gesundheit","عند الطبيب","A2","kommunikation",["g46","g48"],[
["وصف الألم.","Mir tut der Kopf weh.","رأسي يؤلمني.","Ich habe Bauchschmerzen.","بطني تؤلمني."],
["منذ متى.","Seit drei Tagen.","منذ 3 أيام.","Seit wann?","منذ متى؟"],
["الأعراض.","Ich habe Fieber.","عندي حمى.","Mir ist schwindelig.","أشعر بالدوار."],
["الحساسية.","Ich bin allergisch gegen...","لدي حساسية من...","Nehmen Sie Medikamente?","هل تأخذ أدوية؟"],
["الفحص.","Der Arzt untersucht mich.","يفحصني الطبيب.","Machen Sie bitte den Mund auf.","افتح فمك."],
["التشخيص.","Sie haben eine Grippe.","لديك إنفلونزا.","Nichts Schlimmes.","لا شيء خطير."],
["الوصفة.","Ich verschreibe Ihnen...","أصف لك...","Zweimal täglich.","مرتين يوميًا."],
["الصيدلية.","Haben Sie etwas gegen Husten?","هل لديك شيء للسعال؟","Vor dem Essen.","قبل الأكل."],
["الإجازة المرضية.","Ich brauche eine Krankmeldung.","أحتاج إجازة مرضية.","Drei Tage Bettruhe.","3 أيام راحة."],
["الطوارئ.","Es ist dringend!","الأمر عاجل!","Rufen Sie Hilfe!","اطلب المساعدة!"],
["التحسن.","Es geht mir besser.","أنا أفضل.","Gute Besserung!","شفاك الله!"],
["الوقاية.","Viel trinken.","اشرب كثيرًا.","Sich ausruhen.","الراحة."],
["الموعد الدوري.","Vorsorgetermin.","موعد وقائي.","Einmal im Jahr.","مرة سنويًا."],
["التأمين.","Krankenkassenkarte.","بطاقة التأمين.","Zuzahlung.","المساهمة."],
["اختبر: اشتكِ.","Mir tut ___ weh. (der Kopf)","رأسي يؤلمني.","Seit ___ (drei Tagen).","منذ 3 أيام."]]],
["g48","Behörden & Formulare","الدوائر الرسمية","A2","kommunikation",["g47","g49"],[
["التسجيل.","Ich möchte mich anmelden.","أريد التسجيل.","Anmeldung des Wohnsitzes.","تسجيل السكن."],
["الاستمارة.","Füllen Sie das Formular aus.","املأ الاستمارة.","In Druckbuchstaben.","بحروف كبيرة."],
["التوقيع.","Unterschreiben Sie hier.","وقّع هنا.","Datum und Unterschrift.","التاريخ والتوقيع."],
["المستندات.","Bringen Sie Ihren Pass mit.","أحضر جوازك.","Eine Kopie bitte.","نسخة من فضلك."],
["الموعد.","Haben Sie einen Termin?","هل لديك موعد؟","Ohne Termin lange Wartezeit.","بلا موعد انتظار طويل."],
["الرقم.","Ziehen Sie eine Nummer.","اسحب رقمًا.","Warten Sie bitte.","انتظر من فضلك."],
["السؤال.","Wo muss ich hin?","إلى أين أتوجه؟","Zimmer 204, bitte.","الغرفة 204."],
["الطلب الرسمي.","Ich beantrage...","أتقدم بطلب...","Der Antrag dauert...","الطلب يستغرق..."],
["الرسوم.","Das kostet 10 Euro.","يكلف 10 يورو.","Bar oder mit Karte.","نقدًا أم بطاقة؟"],
["الانتظار.","Die Bearbeitung dauert zwei Wochen.","المعاملة تستغرق أسبوعين.","Geduld bitte.","الصبر من فضلك."],
["الرفض والقبول.","Abgelehnt vs genehmigt.","مرفوض مقابل مقبول.","Widerspruch einlegen.","تقديم اعتراض."],
["الترجمة.","Beglaubigte Übersetzung.","ترجمة مصدقة.","Original und Kopie.","الأصل والنسخة."],
["اللغة.","Sprechen Sie Englisch?","هل تتحدث الإنجليزية؟","Dolmetscher mitbringen.","أحضر مترجمًا."],
["الوداع الرسمي.","Vielen Dank für Ihre Hilfe.","شكرًا لمساعدتك.","Auf Wiedersehen.","إلى اللقاء."],
["اختبر: أكمل.","___ Sie hier. (Unterschreiben)","وقّع هنا.","Ich möchte mich ___ (anmelden).","أريد التسجيل."]]],
["g49","Bewerbung & Beruf","التقديم والعمل","A2","kommunikation",["g48","g50"],[
["الإعلان.","Stellenanzeige lesen.","قراءة الإعلان.","Vollzeit/Teilzeit.","دوام كامل/جزئي."],
["السيرة.","Lebenslauf beifügen.","إرفاق السيرة.","Lückenlos und ehrlich.","كاملة وصادقة."],
["الخطاب.","Sehr geehrte Damen und Herren...","سيداتي سادتي...","Mit freundlichen Grüßen.","مع أطيب التحيات."],
["المهارات.","Teamfähig und pünktlich.","جماعي ودقيق.","Berufserfahrung.","خبرة مهنية."],
["الراتب.","Gehaltsvorstellung.","الراتب المتوقع.","Ab wann?","من متى؟"],
["المقابلة.","Vielen Dank für die Einladung.","شكرًا للدعوة.","Pünktlich erscheinen.","الحضور دقيقًا."],
["التعريف.","Erzählen Sie von sich.","حدثنا عن نفسك.","Stärken und Schwächen.","نقاط القوة والضعف."],
["الأسئلة.","Warum wir?","لماذا نحن؟","Fragen stellen.","اطرح أسئلة."],
["المتابعة.","Danke für das Gespräch.","شكرًا للمقابلة.","Nachfassen per E-Mail.","المتابعة بريديًا."],
["العقد.","Arbeitsvertrag unterschreiben.","توقيع العقد.","Probezeit.","الفترة التجريبية."],
["الدوام.","Schicht/Überstunden.","وردية/إضافي.","Urlaubsanspruch.","حق الإجازة."],
["الزملاء.","Sich vorstellen.","التعريف بالنفس.","Per Du/per Sie.","المخاطبة."],
["الفصل.","Kündigung schreiben.","كتابة الاستقالة.","Frist beachten.","احترام المهلة."],
["الشهادة.","Arbeitszeugnis.","شهادة العمل.","Wohlwollend formuliert.","صياغة إيجابية."],
["اختبر: اكتب.","Mit ___ Grüßen.","مع أطيب التحيات.","freundlichen.","الصيغة."]]],
["g50","Small Talk & Höflichkeit","المجاملة والكياسة","A1","kommunikation",["g49","g51"],[
["الطقس كمدخل.","Schönes Wetter heute!","طقس جميل اليوم!","Endlich Sommer!","أخيرًا الصيف!"],
["السؤال عن الحال.","Wie geht's?","كيف حالك؟","Läuft's?","هل تسير الأمور؟"],
["المجاملة.","Das steht dir gut.","يليق بك.","Gute Idee!","فكرة جيدة!"],
["الشكر المتدرج.","Danke! Vielen Dank!","شكرًا! شكرًا جزيلًا!","Tausend Dank! (مبالغة).","ألف شكر!"],
["الاعتذار المتدرج.","Sorry! Entschuldigung!","آسف! عذرًا!","Es tut mir wirklich leid.","آسف حقًا."],
["الإذن.","Darf ich?","هل يمكنني؟","Wäre es okay, wenn...?","هل يمكن...؟"],
["الاقتراح.","Wie wäre es mit...?","ما رأيك بـ...؟","Lass uns...","هيا..."],
["الوداع المتدرج.","Tschüss! Mach's gut!","وداعًا! اعتنِ بنفسك!","Bis bald!","أراك قريبًا!"],
["التهنئة.","Herzlichen Glückwunsch!","تهانينا!","Viel Erfolg!","بالتوفيق!"],
["المواساة.","Das tut mir leid.","يؤسفني.","Kopf hoch!","ارفع رأسك!"],
["الضيافة.","Nimm dir!","تفضل!","Greif zu!","مد يدك!"],
["الإطراء المهذب.","Interessant!","مثير!","Erzähl mehr!","حدثني أكثر!"],
["إنهاء الحديث.","Ich muss leider los.","للأسف يجب أن أذهب.","War nett!","كان لطيفًا!"],
["الرسمي مقابل العامي.","Guten Tag vs Hallo.","طاب يومك مقابل مرحبًا.","Sie vs du.","المقام."],
["اختبر: اختر.","Fremder → ___ (Guten Tag).","طاب يومك.","Freund → ___ (Hallo).","مرحبًا."]]],
["g51","Wortstellung Fallen","مصائد الترتيب","A2","syntax",["g02","g52"],[
["nicht الموضعية.","Er arbeitet nicht heute (بل غدًا).","لا يعمل اليوم.","Er arbeitet heute nicht (أبدًا).","لا يعمل اليوم أصلًا.","الموضع يغيّر المعنى."],
["auch الموضعية.","Auch ich komme (أنا أيضًا).","أنا أيضًا آتي.","Ich komme auch (بالإضافة).","آتي أيضًا.","التركيز يتحرك."],
["nur الموضعية.","Nur ich weiß es (وحدي).","وحدي أعرف.","Ich weiß es nur (فقط أعرف).","فقط أعرف.","نطاق nur."],
["erst الموضعية.","Erst morgen komme ich.","فقط غدًا آتي.","Ich komme erst morgen an.","أصل غدًا متأخرًا.","المعنيان."],
["الضمير قبل الاسم.","Ich gebe es dem Mann.","أعطيه للرجل.","Ich gebe dem Mann es (نادر).","الضمير أولًا."],
["الفرعية المزدوجة.","..., weil er sagt, dass...","لأنه يقول إن...","الفعلان أخيران متتاليان.","التداخل."],
["Infinitiv الطويل.","anzufangen vs an zu fangen.","أن يبدأ.","الملتحم الصحيح.","الملتحم."],
["الترتيب مع Modal.","Ich will morgen früh kommen.","أريد المجيء غدًا مبكرًا.","الظروف قبل المصدر.","الظروف قبل المصدر."],
["التقديم الخاطئ.","Morgen ich komme (خطأ).","خطأ.","Morgen komme ich.","التقديم + قلب."],
["الفاصلة المنسية.","Weil krank bin (خطأ).","خطأ.","Weil ich krank bin.","الفاعل إلزامي."],
["dass المحذوفة.","Ich denke, er kommt (مقبول).","أظن أنه يأتي.","الحذف المحكي مقبول.","المحكي."],
["الأسئلة المضمنة.","Ich weiß nicht, wo er ist.","لا أعرف أين هو.","ليست سؤالًا مباشرًا.","V2 ممنوعة هنا."],
["التكرار الزمني.","jeden Tag vs täglich.","كل يوم مقابل يوميًا.","التبادل صحيح.","التبادل."],
["العطف الناقص.","Ich Tee (خطأ).","خطأ.","Ich trinke Tee.","الفعل إلزامي."],
["اختبر: صحّح.","Morgen ich komme. → ___","غدًا آتي.","Morgen komme ich.","القلب."]]],
["g52","Häufige Fehler A1","أخطاء A1 الشائعة","A1","fehler",["g51","g53"],[
["der/die الخلط.","die Mann (خطأ).","خطأ.","der Mann.","احفظ الأداة."],
["الفعل أخيرًا.","Ich Deutsch lerne (خطأ).","خطأ.","Ich lerne Deutsch.","V2."],
["kein/nicht.","Ich habe nicht Auto (خطأ).","خطأ.","Ich habe kein Auto.","kein للأسماء."],
["den المفقودة.","Ich sehe der Mann (خطأ).","خطأ.","Ich sehe den Mann.","النصب."],
["الفعل بلا تصريف.","Er gehen (خطأ).","خطأ.","Er geht.","التصريف."],
["sein المحذوفة.","Ich krank (خطأ).","خطأ.","Ich bin krank.","الفعل إلزامي."],
["السؤال بلا قلب.","Du kommst? (نبرة فقط).","مقبول شفهيًا.","Kommst du?","الكتابي مقلوب."],
["الجمع الإنجليزي.","die Manns (خطأ).","خطأ.","die Männer.","الجمع الألماني."],
["الكلمة الإنجليزية.","das Handy gut (المعنى!).","الهاتف.","die Handys...","انتبه للمعنى."],
["الحرف الكبير.","ich (خطأ بداية).","خطأ.","Ich.","الجملة كبيرة."],
["الأسماء صغيرة.","der mann (خطأ).","خطأ.","der Mann.","الأسماء كبيرة."],
["Umlaut المنسي.","Madchen (خطأ).","خطأ.","Mädchen.","النقاط معنى."],
["ß/ss.","Strasse = Straße.","الشارع.","ss بعد القصير.","القاعدة."],
["النطق الكتابي.","w = v (انجليزية).","خطأ.","w = و.","الصوت."],
["اختبر: صحّح.","Ich sehe der Mann. → ___","أرى الرجل.","Ich sehe den Mann."]]],
["g53","Häufige Fehler A2","أخطاء A2 الشائعة","A2","fehler",["g52","g54"],[
["weil + V2.","weil ich bin müde (خطأ).","خطأ.","weil ich müde bin.","الفعل أخير."],
["dass + V2.","dass er kommt morgen (خطأ).","خطأ.","dass er morgen kommt.","الفعل أخير."],
["zu بعد الناقص.","Ich will zu gehen (خطأ).","خطأ.","Ich will gehen.","بلا zu."],
["zu المنسية.","Ich versuche gehen (خطأ).","خطأ.","Ich versuche zu gehen.","zu إلزامية."],
["المنفصل ملتحم.","Ich aufstehe (خطأ).","خطأ.","Ich stehe auf.","الانفصال."],
["المتصل منفصل.","Ich verstehe auf (خطأ).","خطأ.","Ich verstehe.","الالتحام."],
["dativ الفعل.","Ich helfe dich (خطأ).","خطأ.","Ich helfe dir.","أفعال الـdativ."],
["gefallen + akk.","Das gefällt mich (خطأ).","خطأ.","Das gefällt mir.","الإعجاب dativ."],
[" أكبر/wie.","größer wie (عامية).","عامية.","größer als.","als."],
["الوصل المحذوف.","Der Mann ich sah (خطأ).","خطأ.","Der Mann, den ich sah.","الوصل إلزامي."],
["Perfekt المساعد.","Ich bin gegessen (خطأ).","خطأ.","Ich habe gegessen.","haben."],
["ge المفقودة.","Ich habe gelernt (صح) vs gelernt.","انتبه.","ge- إلزامية للمنتظم."],
["التذكير الخاطئ.","meine Bruder (خطأ).","خطأ.","mein Bruder.","التطابق."],
["الإعراب المنسي.","mit dem neue Auto (خطأ).","خطأ.","mit dem neuen Auto.","-en."],
["اختبر: صحّح.","weil ich bin müde → ___","لأني متعب.","weil ich müde bin."]]],
["g54","Kontrast Paare","ثنائيات مربكة","A2","kontrast",["g53","g55"],[
["kennen/wissen.","Person kennen, Fakt wissen.","الأشخاص kennen.","Ich weiß, wo er wohnt.","أعرف أين يسكن."],
["leihen/borgen (نفس الفعل!).","leihen = يُعير ويستعير.","يُعير/يستعير.","Der Kontext klärt.","السياق يوضح."],
["stellen/stehen.","stellen حركة.","يضع.","stehen سكون.","يقف."],
["legen/liegen.","legen حركة.","يضجع.","liegen سكون.","يستلقي."],
["setzen/sitzen.","sich setzen حركة.","يجلس.","sitzen سكون.","جالس."],
["hängen/hängen.","على/يعلّق.","يعلّق/معلق.","السياق."],
["als/wenn/wann.","als ماضٍ، wenn شرط، wann سؤال.","ماضٍ/شرط/سؤال.","الثلاثية."],
["ob/wenn.","ob هل، wenn إن.","هل/إن.","الفرق."],
["denn/weil.","denn رئيسية، weil فرعية.","V2/فعل أخير.","المستوى."],
["aber/sondern.","aber مثبت، sondern بعد النفي.","لكن/بل.","النفي."],
["zu/nach.","zu + dativ عام، nach مدن.","إلى.","الوجهة."],
["bei/zu Hause.","bei = عند، zu Hause = في البيت.","عند/في البيت.","الفرق."],
["viel/sehr.","viel للكمية، sehr للشدة.","كثير/جدًا.","Ich lerne viel (خطأ شائع).","sehr للشدة."],
["letzte/nächste.","letzte ماضٍ، nächste قادم.","الماضي/القادم.","الاتجاه."],
["اختبر: اختر.","Ich ___ ihn. (kenne, شخص)","أعرفه.","Ich ___ es. (weiß, معلومة)","أعرفه."]]],
["g55","Verb + Präposition","الأفعال مع حروف الجر","A2","verben",["g54","g56"],[
["warten auf + akk.","warten auf den Bus.","انتظار الحافلة.","Worauf wartest du?","ماذا تنتظر؟"],
["denken an + akk.","denken an die Familie.","التفكير بالعائلة.","Woran denkst du?","بم تفكر؟"],
["sich freuen auf/über.","freuen auf (قادم).","متشوق لقادم.","freuen über (حاضر).","سعيد بحاضر."],
["Angst haben vor + dat.","Angst vor der Prüfung.","الخوف من الامتحان.","Wovor?","مم؟"],
["sich kümmern um + akk.","kümmern um die Kinder.","الاعتناء بالأطفال.","Worum?","بم؟"],
["sich bewerben um/bewelche.","bewerben um die Stelle.","التقدم للوظيفة.","Bewerbung + um."],
["bitten um + akk.","bitten um Hilfe.","طلب المساعدة.","Worum bitten?","ماذا تطلب؟"],
["danken für + akk.","danken für das Geschenk.","الشكر على الهدية.","Wofür?","على ماذا؟"],
["sich beschweren über + akk.","beschweren über den Lärm.","الشكوى من الضجيج.","Worüber?","مم؟"],
["teilnehmen an + dat.","teilnehmen am Kurs.","المشاركة بالدورة.","Woran?","في ماذا؟"],
["leiden an/unter.","leiden an Fieber.","المعاناة من الحمى.","leiden unter Druck.","تحت الضغط."],
["glauben an + akk.","glauben an Gott/dich.","الإيمان.","Woran glauben?","بم تؤمن؟"],
["zweifeln an + dat.","zweifeln am Erfolg.","الشك بالنجاح.","Woran zweifeln?","بم تشك؟"],
["riechen/schmecken nach.","Es riecht nach Kaffee.","رائحة قهوة.","Nach für Geruch.","الرائحة nach."],
["اختبر: أكمل.","warten ___ (auf).","ينتظر.","denken ___ (an).","يفكر في."]]],
["g56","Satzverbindungen","ربط الجمل","A2","konjunktion",["g55","g57"],[
["Hauptsatz + Hauptsatz.","Ich koche, und er hilft.","أطبخ ويساعد.","الفاصلة اختيارية قصيرًا."],
["Hauptsatz + Nebensatz.","Ich bleibe, weil...","أبقى لأن...","الفاصلة إلزامية."],
["Nebensatz voran.","Weil..., bleibe ich.","لأن... أبقى.","القلب بعد الفاصلة."],
["Infinitivsatz.","Ich freue mich, dich zu sehen.","سعيد برؤيتك.","الفاصلة قبل zu."],
["Aufzählung.","Brot, Milch und Käse.","خبز وحليب وجبن.","بلا فاصلة قبل und."],
["Gegensatz.","zwar..., aber...","صحيح... لكن...","التعارض المزدوج."],
["Folge.","so..., dass...","...لدرجة أن...","so müde, dass...","متعب لدرجة..."],
["Bedingung.","wenn..., dann...","إن... ف...","dann اختيارية."],
["Vergleichssatz.","als ob...","كأن...","als + شرطي."],
["Je...desto.","Je mehr, desto besser.","كلما...","المقارنة المزدوجة."],
["Entweder...oder.","Entweder du oder ich.","إما أنت أو أنا.","الحصر."],
["Weder...noch.","Weder...noch...","لا... ولا...","الفعل مفرد."],
["Nicht nur...sondern.","Nicht nur..., sondern auch...","ليس فقط بل أيضًا...","التوكيد."],
["Zusammenfassung.","kurz gesagt.","باختصار.","mit anderen Worten.","بعبارة أخرى."],
["اختبر: ادمج.","Ich bin müde. Ich bleibe. → ___","متعب. أبقى.","Ich bleibe, weil ich müde bin."]]],
["g57","Alltag: Wohnung & Umzug","السكن والانتقال","A2","kommunikation",["g56","g58"],[
["البحث.","Wohnungssuche: Anzeige lesen.","قراءة الإعلان."," provisionsfrei.","بلا عمولة."],
["الاتصال.","Ist die Wohnung noch frei?","هل الشقة متاحة؟","Besichtigung vereinbaren.","تحديد معاينة."],
["المعاينة.","Wie hoch ist die Miete?","كم الإيجار؟","Kaltmiete vs Warmmiete.","البارد مقابل الشامل."],
["العقد.","Mietvertrag unterschreiben.","توقيع العقد.","Kaution drei Monatsmieten.","تأمين 3 شهور."],
["التسجيل.","Sich beim Bürgeramt anmelden.","التسجيل بالدائرة.","Innerhalb von 14 Tagen.","خلال 14 يومًا."],
["الكهرباء.","Strom anmelden.","تسجيل الكهرباء.","Zählerstand notieren.","تسجيل العداد."],
["الإنترنت.","Internetanschluss beantragen.","طلب الإنترنت.","WLAN einrichten.","إعداد الواي فاي."],
["الجيران.","Sich vorstellen.","التعريف.","Ruhezeiten beachten.","احترام الهدوء."],
["النفايات.","Mülltrennung.","فرز النفايات.","Gelb, Blau, Rest, Bio.","الأصفر والأزرق..."],
["الإصلاح.","Mängel melden.","الإبلاغ عن العيوب.","Übergabeprotokoll.","محضر التسليم."],
["الانتقال.","Umzugskartons packen.","تعبئة الصناديق.","Nachsendeantrag.","طلب تحويل البريد."],
["الخروج.","Schönheitsreparaturen.","إصلاحات التجميل.","Kaution zurück.","استرداد التأمين."],
["التأمين.","Hausratversicherung.","تأمين المحتويات.","Sinnvoll.","مفيد."],
["التلفاز.","Rundfunkbeitrag.","رسوم البث.","Pflicht pro Wohnung.","إلزامي لكل شقة."],
["اختبر: أكمل.","___ Miete? (Wie hoch ist die)","كم الإيجار؟","Kaution = ___ Monatsmieten.","3."]]],
["g58","Alltag: Bank & Geld","البنك والمال","A2","kommunikation",["g57","g59"],[
["الحساب.","Konto eröffnen.","فتح حساب.","Girokonto.","الحساب الجاري."],
["البطاقة.","EC-Karte/Girocard.","بطاقة الخصم.","PIN geheim halten.","الرقم سري."],
["السحب.","Geld abheben.","سحب نقود.","Am Automaten.","من الصراف."],
["التحويل.","Überweisung ausfüllen.","ملء التحويل.","IBAN prüfen.","تحقق من IBAN."],
["الدائم.","Dauerauftrag einrichten.","أمر مستديم.","Miete automatisch.","الإيجار تلقائيًا."],
["الكشف.","Kontoauszug.","كشف الحساب.","Online-Banking.","البنكية الإلكترونية."],
["الادخار.","Sparen für...","الادخار لـ...","Tagesgeld.","الحساب اليومي."],
["القرض.","Kredit beantragen.","طلب قرض.","Zinsen vergleichen.","قارن الفوائد."],
["الرسوم.","Kontoführungsgebühr.","رسوم الحساب.","Kostenlos für Studenten.","مجاني للطلاب."],
["الضياع.","Karte verloren → sperren.","البطاقة ضاعت → أوقفها.","Sperrnummer.","رقم الإيقاف."],
["العملة.","Euro und Cent.","يورو وسنت.","Wechselgeld prüfen.","تحقق من الباقي."],
["الفاتورة.","Rechnung bezahlen.","دفع الفاتورة.","Mahnung ernst nehmen.","الإنذار جدي."],
["التقسيط.","Ratenzahlung.","الدفع بالتقسيط.","Kleingedrucktes lesen.","اقرأ الشروط."],
["التأمين.","Versicherung vergleichen.","قارن التأمين.","Jährlich kündbar.","إلغاء سنوي."],
["اختبر: أكمل.","Geld ___ (abheben).","سحب نقود.","Konto ___ (eröffnen).","فتح حساب."]]],
["g59","Studium & Ausbildung","الدراسة والتدريب","A2","kommunikation",["g58","g60"],[
["التقديم.","Sich bewerben.","التقديم.","Frist beachten.","احترام الموعد."],
["القبول.","Zulassung erhalten.","الحصول على القبول.","Numerus clausus.","المعدل المطلوب."],
["التسجيل.","Sich immatrikulieren.","التسجيل الجامعي.","Semesterbeitrag.","رسوم الفصل."],
["المحاضرات.","Vorlesung vs Seminar.","محاضرة مقابل ندوة.","Anwesenheitspflicht.","الحضور إلزامي."],
["الامتحانات.","Sich anmelden.","التسجيل للامتحان.","Durchfallen → wiederholen.","الرسوب → الإعادة."],
["الدرجات.","Bestanden/nicht bestanden.","ناجح/راسب.","1,0 bis 5,0.","من 1 إلى 5."],
["الأطروحة.","Bachelorarbeit schreiben.","كتابة الأطروحة.","Betreuer finden.","إيجاد مشرف."],
["التدريب.","Praktikum machen.","القيام بتدريب.","Pflichtpraktikum.","تدريب إلزامي."],
["Ausbildung.","Duale Ausbildung.","تدريب مزدوج.","Berufsschule + Betrieb.","مدرسة + شركة."],
["المنحة.","BAföG beantragen.","طلب المنحة.","Stipendium.","المنحة الدراسية."],
["السكن.","Studentenwohnheim.","السكن الجامعي.","WG-Zimmer.","غرفة مشتركة."],
["العمل.","Werkstudent.","طالب عامل.","Minijob.","عمل مصغر."],
["اللغة.","Deutsch auf C1.","الألمانية C1.","TestDaF/DSH.","اختبارات اللغة."],
["التخرج.","Abschlussfeier.","حفل التخرج.","Zeugnis abholen.","استلام الشهادة."],
["اختبر: أكمل.","___ beantragen (BAföG).","طلب المنحة.","Sich ___ (immatrikulieren).","التسجيل."]]],
["g60","Briefe & E-Mails","الرسائل والإيميل","A2","kommunikation",["g59","g01"],[
["التحية الرسمية.","Sehr geehrte Frau Müller,","سيدتي العزيزة...","Sehr geehrter Herr...","سيدي العزيز..."],
["التحية العامية.","Liebe Anna,","عزيزتي آنا...","Hallo zusammen,","مرحبًا جميعًا..."],
["المقدمة.","Vielen Dank für Ihre E-Mail.","شكرًا لإيميلك.","Ich schreibe Ihnen wegen...","أكتب بخصوص..."],
["الطلب.","Könnten Sie mir bitte...?","هل يمكنك...؟","Ich hätte eine Bitte.","لدي طلب."],
["الشكوى.","Leider muss ich mich beschweren.","للأسف أشكو.","Mit Bedauern...","بأسف..."],
["الاعتذار.","Entschuldigen Sie bitte...","عذرًا...","Es tut mir leid, dass...","يؤسفني أن..."],
["التأكيد.","Ich bestätige hiermit...","أؤكد بموجبه...","Wie vereinbart...","كما اتفقنا..."],
["الإرفاق.","Im Anhang finden Sie...","مرفق...","Anbei...","طيه..."],
["الموعد.","Ich schlage... vor.","أقترح...","Passt Ihnen...?","هل يناسبك...؟"],
["الختام الرسمي.","Mit freundlichen Grüßen.","مع أطيب التحيات.","MfG (مختصر).","م.ف.غ."],
["الختام العامي.","Liebe Grüße.","تحياتي.","Viele Grüße.","تحيات كثيرة."],
["التوقيع.","Vor- und Nachname.","الاسم الكامل.","Telefonnummer.","رقم الهاتف."],
["الرد.","Vielen Dank für Ihre schnelle Antwort.","شكرًا لسرعة الرد.","Bis bald.","أراك قريبًا."],
["المتابعة.","Ich melde mich wieder.","سأعاود الاتصال.","Für Rückfragen...","للاستفسارات..."],
["اختبر: اختر.","Formell: ___ (Sehr geehrte).","سيدتي العزيزة.","Schluss: ___ (Mit freundlichen Grüßen).","مع التحيات."]]]
];
if(typeof module!=="undefined")module.exports={GT2};
