/* Extra head nouns for compounds + coverage boosters. Same pipe format as nouns.js */
"use strict";
const HEADS=[
"Karte|die|Karten|البطاقة|card|general|A1","Laden|der|Läden|المتجر|shop|shopping|A2",
"Krankheit|die|Krankheiten|المرض|illness|health|A2","Zeitung|die|Zeitungen|الجريدة|newspaper|general|A2",
"Rechner|der|Rechner|الحاسوب (رسمي)|computer|computers|A2","Programm|das|Programme|البرنامج|program|tech|A2",
"Seite|die|Seiten|الصفحة|page|internet|A1","Kontakt|der|Kontakte|جهة الاتصال|contact|communication|A2",
"Nummer|die|Nummern|الرقم|number|general|A1","Verkäufer|der|Verkäufer|البائع|salesman|jobs|A2",
"Verkäuferin|die|Verkäuferinnen|البائعة|saleswoman|jobs|A2","Pfleger|der|Pfleger|الممرض|nurse (m)|jobs|A2",
"Pflegerin|die|Pflegerinnen|الممرضة|nurse (f)|jobs|A2","Gepäck|das|-|الأمتعة|luggage|travel|A2",
"Fahrplan|der|Fahrpläne|جدول المواعيد|timetable|transport|A2","Verspätung|die|Verspätungen|التأخير|delay|transport|A2",
"Fahrschein|der|Fahrscheine|تذكرة السفر|ticket|transport|A2","Lärm|der|-|الضجيج|noise|home|A2",
"Müll|der|-|القمامة|rubbish|home|A2","Strom|der|Ströme|الكهرباء|electricity|home|A2",
"Rechnung|die|Rechnungen|الفاتورة|bill|money|A2","Kindergarten|der|Kindergärten|الروضة|kindergarten|school|A2",
"Spielplatz|der|Spielplätze|ملعب اللعب|playground|city|A2","Tierarzt|der|Tierärzte|الطبيب البيطري|vet|doctor|A2",
"Tierärztin|die|Tierärztinnen|الطبيبة البيطرية|vet (f)|doctor|A2","Krankenkasse|die|Krankenkassen|التأمين الصحي|health insurance|health|A2",
"Wochenende|das|Wochenenden|عطلة الأسبوع|weekend|time|A1","Alltag|der|-|الحياة اليومية|everyday life|routine|A2",
"Morgenroutine|die|Morgenroutinen|روتين الصباح|morning routine|routine|A2","Gericht|das|Gerichte|الطبق (طعام)|dish|restaurant|A1",
"Getränk|das|Getränke|المشروب|beverage|drinks|A1","Bestellung|die|Bestellungen|الطلب|order|restaurant|A2",
"Service|der|Services|الخدمة|service|services|A2","Dienst|der|Dienste|الخدمة (رسمي)|service|services|A2",
"Anfrage|die|Anfragen|الاستفسار|enquiry|communication|A2","Antwort3|die|Antworten|الرد|reply|communication|A1",
"Baumarkt|der|Baumärkte|سوق مواد البناء|DIY store|shopping|A2","Möbelhaus|das|Möbelhäuser|محل الأثاث|furniture store|shopping|A2",
"Fernseher|der|Fernseher|التلفاز|TV|home|A1","Fernbedienung|die|Fernbedienungen|جهاز التحكم|remote|home|A2",
"Steckdose|die|Steckdosen|مقبس الكهرباء|socket|home|A2","Glühbirne|die|Glühbirnen|المصباح (لمبة)|bulb|home|A2",
"Regenschirm|der|Regenschirme|المظلة|umbrella|weather|A1","Sonnenbrille|die|Sonnenbrillen|نظارة الشمس|sunglasses|clothing|A1",
"Wintermantel|der|Wintermäntel|معطف الشتاء|winter coat|clothing|A1","Gutschein|der|Gutscheine|القسيمة|voucher|shopping|A2",
"Umtausch|der|-|الاستبدال|exchange|shopping|A2","Anprobe|die|Anproben|القياس (تجربة)|fitting|shopping|A2",
"Umkleidekabine|die|Umkleidekabinen|غرفة القياس|fitting room|shopping|A2","Warteschlange|die|Warteschlangen|طابور الانتظار|queue|services|A2",
"Wartenummer|die|Wartenummern|رقم الانتظار|queue number|services|A2","Wartezimmer|das|Wartezimmer|غرفة الانتظار|waiting room|doctor|A2",
"Sprechstunde|die|Sprechstunden|ساعة العيادة|consultation|doctor|A2","Krankmeldung|die|Krankmeldungen|الإجازة المرضية|sick note|work|A2",
"Attest|das|Atteste|الشهادة الطبية|certificate|doctor|A2","Impfpass|der|Impfpässe|دفتر اللقاح|vaccine booklet|documents|A2",
"Führerschein|der|Führerscheine|رخصة القيادة|licence|documents|A2","Kennzeichen|das|Kennzeichen|لوحة السيارة|plate|documents|A2",
"Werkstatt|die|Werkstätten|الورشة|workshop|services|A2","Panne|die|Pannen|العطل|breakdown|transport|A2",
"Tankstelle|die|Tankstellen|محطة الوقود|petrol station|transport|A1","Diesel|der|-|الديزل|diesel|transport|A2",
"Kilometer|der|Kilometer|الكيلومتر|kilometre|transport|A1","Stau|der|Staus|الازدحام|jam|roads|A2",
"Umleitung|die|Umleitungen|التحويلة|diversion|roads|A2","Fußgängerzone|die|Fußgängerzonen|منطقة المشاة|pedestrian zone|city|A2",
"Parkplatz|der|Parkplätze|موقف السيارات|car park|city|A1","Parkschein|der|Parkscheine|تذكرة الموقف|parking ticket|city|A2",
"Strafzettel|der|Strafzettel|مخالفة الموقف|parking fine|services|A2","Rathaus|das|Rathäuser|دار البلدية|town hall|city|A2",
"Bürgermeister|der|Bürgermeister|رئيس البلدية|mayor|services|A2","Anmeldung|die|Anmeldungen|التسجيل|registration|services|A2",
"Abmeldung|die|Abmeldungen|إلغاء التسجيل|deregistration|services|A2","Steuer|die|Steuern|الضريبة|tax|money|A2",
"Steuererklärung|die|Steuererklärungen|الإقرار الضريبي|tax return|money|A2","Versicherung|die|Versicherungen|التأمين|insurance|services|A2",
"Beitrag|der|Beiträge|الاشتراك|contribution|money|A2","Rente|die|Renten|راتب التقاعد|pension|money|A2",
"Arbeitslosengeld|das|-|إعانة البطالة|unemployment benefit|money|A2","Kindergeld|das|-|إعانة الأطفال|child benefit|money|A2",
"Elterngeld|das|-|إعانة الوالدين|parental benefit|money|A2","Wohngeld|das|-|إعانة السكن|housing benefit|money|A2",
"Prüfungsamt|das|Prüfungsämter|مكتب الامتحانات|exams office|university|A2","Studentenwohnheim|das|Studentenwohnheime|السكن الجامعي|dormitory|unilife|A2",
"Bibliotheksausweis|der|Bibliotheksausweise|بطاقة المكتبة|library card|university|A2","Hausarbeit|die|Hausarbeiten|الواجب الجامعي|term paper|university|A2",
"Abschlussarbeit|die|Abschlussarbeiten|أطروحة التخرج|thesis|university|A2","Deutschkurs|der|Deutschkurse|دورة الألمانية|German course|study|A1",
"Integrationskurs|der|Integrationskurse|دورة الاندماج|integration course|study|A2","Sprachschule|die|Sprachschulen|مدرسة اللغة|language school|study|A1",
"Sprachprüfung|die|Sprachprüfungen|امتحان اللغة|language exam|study|A2","Zertifikat|das|Zertifikate|الشهادة|certificate|study|A2",
"Vokabelheft|das|Vokabelhefte|دفتر المفردات|vocab book|study|A1","Wörterbuch|das|Wörterbücher|القاموس|dictionary|study|A1",
"Lernpartner|der|Lernpartner|شريك التعلم|study buddy|study|A2","Lernpartnerin|die|Lernpartnerinnen|شريكة التعلم|study buddy (f)|study|A2",
"Nachhilfe|die|-|درس التقوية|tutoring|education|A2","Klassenarbeit|die|Klassenarbeiten|الاختبار الصفي|class test|school|A1",
"Matura|die|Maturen|امتحان الثانوية (نمساوي)|school-leaving exam|education|A2","Stundenplan|der|Stundenpläne|الجدول الدراسي|timetable|school|A1",
"Klassenraum|der|Klassenräume|الفصل الدراسي|classroom|school|A1","Schulbus|der|Schulbusse|الحافلة المدرسية|school bus|school|A1",
"Schulranzen|der|Schulranzen|الحقيبة المدرسية|satchel|school|A1","Federmäppchen|das|Federmäppchen|المقلمة|pencil case|school|A1",
"Tafelschwamm|der|Tafelschwämme|ممحاة السبورة|board eraser|school|A2","Kreidestück|das|Kreidestücke|قطعة الطباشير|chalk piece|school|A2",
"Ingenieur|der|Ingenieure|المهندس|engineer|jobs|A2","Ingenieurin|die|Ingenieurinnen|المهندسة|engineer (f)|jobs|A2",
"Architekt|der|Architekten|المهندس المعماري|architect|jobs|A2","Anwalt|der|Anwälte|المحامي|lawyer|jobs|A2",
"Anwältin|die|Anwältinnen|المحامية|lawyer (f)|jobs|A2","Richter|der|Richter|القاضي|judge|jobs|A2",
"Polizist|der|Polizisten|الشرطي|policeman|jobs|A1","Polizistin|die|Polizistinnen|الشرطية|policewoman|jobs|A1",
"Feuerwehrmann|der|Feuerwehrmänner|الإطفائي|firefighter|jobs|A2","Soldat|der|Soldaten|الجندي|soldier|jobs|A2",
"Koch|der|Köche|الطباخ|cook|jobs|A1","Köchin|die|Köchinnen|الطباخة|cook (f)|jobs|A1",
"Bäcker|der|Bäcker|الخباز|baker|jobs|A1","Bäckerin|die|Bäckerinnen|الخبازة|baker (f)|jobs|A1",
"Friseur|der|Friseure|الحلاق|hairdresser|jobs|A1","Friseurin|die|Friseurinnen|الحلاقة|hairdresser (f)|jobs|A1",
"Mechaniker|der|Mechaniker|الميكانيكي|mechanic|jobs|A2","Elektriker|der|Elektriker|الكهربائي|electrician|jobs|A2",
"Maler|der|Maler|الدهّان|painter|jobs|A2","Tischler|der|Tischler|النجار|carpenter|jobs|A2",
"Schneider|der|Schneider|الخياط|tailor|jobs|A2","Gärtner|der|Gärtner|البستاني|gardener|jobs|A2",
"Landwirt|der|Landwirte|المزارع|farmer|jobs|A2","Fischer|der|Fischer|الصياد|fisher|jobs|A2",
"Pilot|der|Piloten|الطيار|pilot|jobs|A2","Pilotin|die|Pilotinnen|الطيارة|pilot (f)|jobs|A2",
"Kapitän|der|Kapitäne|القبطان|captain|jobs|A2","Matrose|der|Matrosen|البحار|sailor|jobs|A2",
"Sekretär|der|Sekretäre|السكرتير|secretary|jobs|A2","Sekretärin|die|Sekretärinnen|السكرتيرة|secretary (f)|jobs|A2",
"Buchhalter|der|Buchhalter|المحاسب|accountant|jobs|A2","Steuerberater|der|Steuerberater|المستشار الضريبي|tax advisor|jobs|A2",
"Journalist|der|Journalisten|الصحفي|journalist|jobs|A2","Journalistin|die|Journalistinnen|الصحفية|journalist (f)|jobs|A2",
"Fotograf|der|Fotografen|المصور|photographer|jobs|A2","Fotografin|die|Fotografinnen|المصورة|photographer (f)|jobs|A2",
"Schauspieler|der|Schauspieler|الممثل|actor|jobs|A2","Schauspielerin|die|Schauspielerinnen|الممثلة|actress|jobs|A2",
"Sänger|der|Sänger|المغني|singer|jobs|A2","Sängerin|die|Sängerinnen|المغنية|singer (f)|jobs|A2",
"Tänzer|der|Tänzer|الراقص|dancer|jobs|A2","Musiker|der|Musiker|الموسيقي|musician|jobs|A2",
"Malerin|die|Malerinnen|الرسامة|painter (f)|jobs|A2","Schriftsteller|der|Schriftsteller|الكاتب|writer|jobs|A2",
"Dichter|der|Dichter|الشاعر|poet|jobs|A2","Forscher|der|Forscher|الباحث|researcher|jobs|A2",
"Wissenschaftler|der|Wissenschaftler|العالم|scientist|jobs|A2","Entwickler|der|Entwickler|المطور|developer|profi|A2",
"Designer|der|Designer|المصمم|designer|profi|A2","Manager|der|Manager|المدير|manager|profi|A2",
"Berater|der|Berater|المستشار|consultant|profi|A2","Kunde|der|Kunden|الزبون|client|profi|A2",
"Klient|der|Klienten|العميل|client|profi|A2","Lieferant|der|Lieferanten|المورّد|supplier|profi|A2",
"Partner|der|Partner|الشريك|partner|profi|A2","Konkurrent|der|Konkurrenten|المنافس|competitor|profi|A2",
"Abteilung|die|Abteilungen|القسم|department|workplace|A2","Filiale|die|Filialen|الفرع|branch|workplace|A2",
"Zentrale|die|Zentralen|المقر الرئيسي|headquarters|workplace|A2","Lager|das|Lager|المخزن|warehouse|workplace|A2",
"Werkstatt2|die|Werkstätten|ورشة العمل|workshop|workplace|A2","Labor|das|Labors|المختبر|laboratory|workplace|A2",
"Praxis|die|Praxen|العيادة|practice|workplace|A2","Kanzlei|die|Kanzleien|مكتب المحاماة|law office|workplace|A2",
"Atelier|das|Ateliers|المرسم|studio|workplace|A2","Bühne|die|Bühnen|المسرح|stage|hobbies|A2",
"Publikum|das|-|الجمهور|audience|hobbies|A2","Vorstellung|die|Vorstellungen|العرض|performance|hobbies|A2",
"Eintritt|der|Eintritte|الدخول (تذكرة)|admission|general|A2","Austritt|der|Austritte|الخروج|exit|general|A2",
"Kultur|die|Kulturen|الثقافة|culture|general|A2","Kunst|die|Künste|الفن|art|hobbies|A2",
"Literatur|die|-|الأدب|literature|education|A2","Geschichte|die|Geschichten|التاريخ / القصة|history/story|education|A1",
"Erdkunde|die|-|الجغرافيا|geography|education|A2","Biologie|die|-|الأحياء|biology|education|A2",
"Chemie|die|-|الكيمياء|chemistry|education|A2","Physik|die|-|الفيزياء|physics|education|A2",
"Informatik|die|-|المعلوماتية|computer science|education|A2","Religion|die|Religionen|الدين (مادة)|religion (subject)|education|A2",
"Ethik|die|-|الأخلاق (مادة)|ethics|education|A2","Turnen|das|-|التربية البدنية|PE|school|A2",
"Pause2|die|Pausen|الفسحة|break|school|A1","AG|die|AGs|مجموعة النشاط|club|school|A2",
"Schulfest|das|Schulfeste|الاحتفال المدرسي|school festival|school|A2","Ausflug|der|Ausflüge|الرحلة المدرسية|school trip|school|A1",
"Klassenfahrt|die|Klassenfahrten|رحلة الصف|class trip|school|A2","Austausch|der|Austausche|التبادل|exchange|school|A2",
"Stipendiat|der|Stipendiaten|المبعوث (منحة)|scholarship holder|university|A2","Doktorand|der|Doktoranden|طالب الدكتوراه|PhD student|university|A2",
"Masterstudent|der|Masterstudenten|طالب الماجستير|master student|university|A2","Erstsemester|der|Erstsemester|طالب الفصل الأول|fresher|unilife|A2",
"Vorlesungsverzeichnis|das|Vorlesungsverzeichnisse|دليل المحاضرات|course catalogue|university|A2","Seminarraum|der|Seminarräume|قاعة الندوة|seminar room|university|A2",
"Hörsaal|der|Hörsäle|المدرج|lecture hall|university|A2","Mensa2|die|Mensen|مطعم الجامعة|canteen|unilife|A2",
"Wohnheim|das|Wohnheime|السكن الطلابي|dorm|unilife|A2","WG|die|WGs|السكن المشترك|shared flat|unilife|A2",
"Mitbewohner|der|Mitbewohner|رفيق السكن|flatmate|unilife|A2","Nachmieter|der|Nachmieter|المستأجر التالي|next tenant|home|A2",
"Vormieter|der|Vormieter|المستأجر السابق|previous tenant|home|A2","Hausmeister|der|Hausmeister|البواب|caretaker|home|A2",
"Hausverwaltung|die|Hausverwaltungen|إدارة المبنى|property management|home|A2","Nebenkosten|die|Nebenkosten|التكاليف الإضافية|utilities|home|A2",
"Betriebskosten|die|Betriebskosten|تكاليف التشغيل|operating costs|home|A2","Mietspiegel|der|Mietspiegel|مؤشر الإيجارات|rent index|home|A2",
"Wohnungsanzeige|die|Wohnungsanzeigen|إعلان الشقة|flat advert|home|A2","Besichtigung|die|Besichtigungen|المعاينة|viewing|home|A2",
"Selbstauskunft|die|Selbstauskünfte|الإفصاح الذاتي|self-disclosure|home|A2","Schufa|die|-|السجل الائتماني|credit record|home|A2",
"Übergabe|die|Übergaben|التسليم|handover|home|A2","Protokoll|das|Protokolle|المحضر|report|services|A2",
"Quittung2|die|Quittungen|الإيصال|receipt|shopping|A1","Garantie|die|Garantien|الضمان|guarantee|shopping|A2",
"Umfrage|die|Umfragen|الاستطلاع|survey|social|A2","Bewertung|die|Bewertungen|التقييم|review|internet|A2",
"Kommentar|der|Kommentare|التعليق|comment|social|A1","Like|das|Likes|الإعجاب|like|social|A1",
"Follower|der|Follower|المتابع|follower|social|A2","Profil|das|Profile|الملف الشخصي|profile|internet|A1",
"Beitrag2|der|Beiträge|المنشور|post|social|A1","Story|die|Storys|القصة (ستوري)|story|social|A2",
"Hashtag|der|Hashtags|الوسم|hashtag|social|A2","Trend|der|Trends|الترند|trend|social|A2",
"Virus|der|Viren|الفيروس|virus|tech|A2","Update|das|Updates|التحديث|update|tech|A1",
"Download|der|Downloads|التنزيل|download|internet|A1","Upload|der|Uploads|الرفع|upload|internet|A2",
"Account|der|Accounts|الحساب|account|internet|A1","Profilbild|das|Profilbilder|الصورة الشخصية|profile pic|social|A1",
"Tastenkombination|die|Tastenkombinationen|اختصار لوحة المفاتيح|shortcut|computers|A2","Datei|die|Dateien|الملف|file|computers|A1",
"Ordner|der|Ordner|المجلد|folder|computers|A1","Fenster2|das|Fenster|النافذة (برنامج)|window|computers|A1",
"Symbol|das|Symbole|الأيقونة|icon|computers|A1","Mauszeiger|der|Mauszeiger|مؤشر الفأرة|cursor|computers|A2",
"Ladekabel|das|Ladekabel|كابل الشحن|charger cable|phones|A1","Akku|der|Akkus|البطارية|battery|phones|A1",
"SIM-Karte|die|SIM-Karten|شريحة الهاتف|SIM card|phones|A1","Guthaben|das|-|الرصيد|credit|phones|A1",
"Flatrate|die|Flatrates|الباقة المفتوحة|flat rate|phones|A2","Roaming|das|-|التجوال|roaming|phones|A2",
"Netz|das|Netze|الشبكة|network|internet|A1","Empfang|der|-|التغطية|reception|phones|A2",
"Anbieter|der|Anbieter|مزوّد الخدمة|provider|services|A2","Kündigung2|die|Kündigungen|الإلغاء|cancellation|services|A2",
"Laufzeit|die|Laufzeiten|مدة العقد|contract term|money|A2",
"Bericht|der|Berichte|التقرير|report|general|A2","Besuch|der|Besuche|الزيارة|visit|general|A1","Café|das|Cafés|المقهى|café|restaurant|A1","Kiosk|der|Kioske|الكشك|kiosk|shopping|A2","Fleischer|der|Fleischer|الجزار|butcher|jobs|A2","Krücke|die|Krücken|العكاز|crutch|health|A2","Tod|der|Tode|الموت|death|general|A2","Konzert|das|Konzerte|الحفل الموسيقي|concert|hobbies|A1","Kosten|die|Kosten|التكاليف|costs|money|A2","Trinken|das|-|الشرب|drinking|drinks|A1","Party|die|Partys|الحفلة|party|hobbies|A1","Empfänger|der|Empfänger|المستلم|recipient|communication|A2","Absender|der|Absender|المرسل|sender|communication|A2","Päckchen|das|Päckchen|الطرد الصغير|small parcel|communication|A2","Moschee|die|Moscheen|المسجد|mosque|general|A2","Kirche2|die|Kirchen|الكنيسة|church|general|A2","Aufzug2|der|Aufzüge|المصعد|lift|home|A1","Taufe|die|Taufen|المعمودية|baptism|general|A2","Grundgebühr|die|Grundgebühren|الرسوم الأساسية|base fee|money|A2","Referenz|die|Referenzen|المرجع|reference|profi|A2","Bild|das|Bilder|الصورة|picture|general|A1","Sitz|der|Sitze|المقعد|seat|travel|A2","Fahrt|die|Fahrten|الرحلة|ride|transport|A1","Ferien|die|Ferien|العطلة|holidays|time|A1","Kino|das|Kinos|السينما|cinema|hobbies|A1","Lied|das|Lieder|الأغنية|song|hobbies|A1","Liste|die|Listen|القائمة|list|general|A1","Museum|das|Museen|المتحف|museum|general|A2","Pizza|die|Pizzen|البيتزا|pizza|food|A1","Radio|das|Radios|الراديو|radio|tech|A1","Saal|der|Säle|القاعة|hall|general|A2","Wein|der|Weine|النبيذ|wine|drinks|A2","Reifen|der|Reifen|الإطار|tyre|transport|A2","Motor|der|Motoren|المحرك|engine|tech|A2","Licht|das|Lichter|الضوء|light|home|A1","Bremse|die|Bremsen|الفرامل|brake|transport|A2","Schaden|der|Schäden|الضرر|damage|general|A2","Notruf|der|Notrufe|نداء الطوارئ|emergency call|emergency|A1","Feuer|das|-|النار|fire|general|A1","Speicher|der|Speicher|العلية|attic|home|A2","Bad|das|Bäder|الحمام|bathroom|rooms|A1","WC|das|WCs|المرحاض|toilet|home|A1","Dusche|die|Duschen|الدش|shower|home|A1","Badewanne|die|Badewannen|حوض الاستحمام|bathtub|home|A1","Waschbecken|das|Waschbecken|المغسلة|basin|home|A1","Creme|die|Cremes|الكريم|cream|health|A2","Parfüm|das|Parfüms|العطر|perfume|shopping|A2","Bürste|die|Bürsten|الفرشاة|brush|home|A1","Kamm|der|Kämme|المشط|comb|home|A1","Föhn|der|Föhne|مجفف الشعر|hair dryer|home|A2","Rasierer|der|Rasierer|ماكينة الحلاقة|shaver|home|A2","Hörgerät|das|Hörgeräte|سماعة الأذن|hearing aid|health|A2","Rollstuhl|der|Rollstühle|الكرسي المتحرك|wheelchair|health|A2","Hustensaft|der|Hustensäfte|شراب السعال|cough syrup|pharmacy|A2","Schmerztablette|die|Schmerztabletten|قرص الألم|pain tablet|pharmacy|A2","Vitamin|das|Vitamine|الفيتامين|vitamin|health|A2","Impfung|die|Impfungen|اللقاح|vaccination|health|A2","Test|der|Tests|الاختبار|test|general|A1","Maske|die|Masken|الكمامة|mask|health|A1","Desinfektion|die|Desinfektionen|التطهير|disinfection|health|A2","Allergie|die|Allergien|الحساسية|allergy|health|A2","Asthma|das|-|الربو|asthma|health|A2","Diabetes|der|-|السكري|diabetes|health|A2","Operation|die|Operationen|العملية|surgery|health|A2","Narbe|die|Narben|الندبة|scar|health|A2","Gips|der|Gipse|الجبيرة|cast|health|A2","Reha|die|Rehas|التأهيل|rehab|health|A2","Kur|die|Kuren|العلاج بالمنتجع|cure|health|A2","Therapie|die|Therapien|العلاج|therapy|health|A2","Massage|die|Massagen|المساج|massage|health|A2","Sauna|die|Saunen|الساونا|sauna|hobbies|A2","Wellness|die|-|الاستجمام|wellness|hobbies|A2","Fitness|die|-|اللياقة|fitness|sports|A1","Yoga|das|-|اليوغا|yoga|sports|A2","Jogging|das|-|الهرولة|jogging|sports|A2","Spaziergang|der|Spaziergänge|النزهة مشيًا|walk|hobbies|A1","Picknick|das|Picknicks|النزهة|picnic|hobbies|A2","Geburt|die|Geburten|الولادة|birth|family|A2","Beerdigung|die|Beerdigungen|الدفن|burial|general|A2","Grab|das|Gräber|القبر|grave|general|A2","Friedhof|der|Friedhöfe|المقبرة|cemetery|city|A2","Gottesdienst|der|Gottesdienste|القداس|service|general|A2","Urlaubstag|der|Urlaubstage|يوم الإجازة|leave day|work|A2","Empfehlung|die|Empfehlungen|التوصية|recommendation|worktalk|A2","Motivation|die|Motivationen|الدافع|motivation|general|A2","Team|das|Teams|الفريق|team|work|A1","Besprechung|die|Besprechungen|الاجتماع|meeting|work|A1","Präsentation|die|Präsentationen|العرض|presentation|worktalk|A2","Vortrag|der|Vorträge|المحاضرة|lecture|education|A2","Workshop|der|Workshops|ورشة العمل|workshop|education|A2","Konferenz|die|Konferenzen|المؤتمر|conference|worktalk|A2","Messe|die|Messen|المعرض|fair|general|A2","Stand|der|Stände|الجناح|stand|general|A2","Aussteller|der|Aussteller|العارض|exhibitor|jobs|A2","Auftrag|der|Aufträge|الطلب|order|work|A2","Angebot|das|Angebote|العرض|offer|shopping|A2","Mahnung|die|Mahnungen|الإنذار|reminder|money|A2","Zahlung|die|Zahlungen|الدفع|payment|money|A2","Retoure|die|Retouren|الإرجاع|return|shopping|A2","Lieferung|die|Lieferungen|التوصيل|delivery|shopping|A2","Sendung|die|Sendungen|الشحنة|shipment|communication|A2","Briefkasten|der|Briefkästen|صندوق البريد|postbox|communication|A1","Briefmarke|die|Briefmarken|الطابع|stamp|communication|A2","Postkarte|die|Postkarten|البطاقة البريدية|postcard|communication|A2","Taufe|die|Taufen|المعمودية|baptism|general|A2","Aufzug|der|Aufzüge|المصعد|lift|home|A1"
];
if(typeof module!=="undefined")module.exports={HEADS};
