/* Idioms, proverbs, fixed chunks: de|ar|en|cat|lvl — all established, hand-translated. */
"use strict";
const IDIOMS=[
"Ins kalte Wasser springen|يقفز إلى المجهول|jump in at the deep end|colloquial|A2",
"Die Daumen drücken|يتمنى الحظ (يمسك الإبهام)|keep fingers crossed|colloquial|A2",
"Schwein haben|محظوظ (لديه خنزير)|be lucky|colloquial|A2",
"Alles in Butter|كل شيء على ما يرام|everything is fine|colloquial|A2",
"Da liegt der Hund begraben|هنا تكمن المشكلة|that's the crux|colloquial|A2",
"Jemandem auf die Nerven gehen|يستفز أعصاب أحد|get on nerves|colloquial|A2",
"Den Nagel auf den Kopf treffen|يصيب كبد الحقيقة|hit the nail on the head|colloquial|A2",
"Zwei Fliegen mit einer Klappe schlagen|يصيب عصفورين بحجر|kill two birds|colloquial|A2",
"Die Kirche im Dorf lassen|لا يبالغ|not overdo it|colloquial|A2",
"Tomaten auf den Augen haben|لا يرى الواضح|not see obvious|colloquial|A2",
"Ein Brett vor dem Kopf haben|مخه مقفل|have a block|colloquial|A2",
"Kalter Kaffee|موضوع قديم|old news|colloquial|A2",
"Alter Schwede|يا للعجب!|wow expression|colloquial|A2",
"Null acht fünfzehn|عادي جدًا|run-of-the-mill|colloquial|A2",
"Fix und fertig|منهك تمامًا|dead tired|colloquial|A2",
"Klar wie Kloßbrühe|واضح تمامًا|crystal clear|colloquial|A2",
"Arm wie eine Kirchenmaus|فقير جدًا|poor as a church mouse|colloquial|A2",
"Stumm wie ein Fisch|صامت كالسمكة|silent as fish|colloquial|A2",
"Leben wie Gott in Frankreich|يعيش برغد|live like a king|colloquial|A2",
"Friede Freude Eierkuchen|كل شيء وردي|all sweetness|colloquial|A2",
"Ende gut alles gut|النهاية السعيدة تبرر|all's well that ends well|general|A2",
"Aller Anfang ist schwer|البداية صعبة|beginnings are hard|study|A1",
"Ohne Fleiß kein Preis|بلا جهد لا أجر|no pain no gain|study|A1",
"Übung macht den Meister|التدريب يصنع الإتقان|practice makes perfect|study|A1",
"Was Hänschen nicht lernt|ما لا يتعلمه الصغير|what isn't learned young|study|A2",
"Kleider machen Leute|المظهر يصنع الانطباع|clothes make the man|general|A2",
"Ordnung muss sein|النظام واجب|order must be|general|A2",
"Der Apfel fällt nicht weit vom Stamm|الولد سر أبيه|apple doesn't fall far|family|A2",
"Stille Wasser sind tief|المياه الهادئة عميقة|still waters run deep|general|A2",
"Reden ist Silber Schweigen ist Gold|الصمت ذهب|silence is golden|communication|A2",
"Morgenstund hat Gold im Mund|البركة في البكور|early bird catches|routine|A2",
"Wer rastet der rostet|الحركة بركة|who rests rusts|general|A2",
"Geteiltes Leid ist halbes Leid|مشاركة الحزن نصفه|shared sorrow|emotions|A2",
"Vorfreude ist die schönste Freude|انتظار الفرح أجمله|anticipation joy|emotions|A2",
"Gleich und gleich gesellt sich gern|الطيور على أشكالها|birds of a feather|relationships|A2",
"Gegensätze ziehen sich an|الأضداد تتجاذب|opposites attract|relationships|A2",
"Liebe geht durch den Magen|أقصر طريق لقلبه معدته|love through stomach|food|A2",
"Der Hunger treibt ihn|الجوع يدفعه|hunger drives|food|A2",
"Man ist was man isst|أنت ما تأكل|you are what you eat|food|A2",
"Appetit kommt beim Essen|الشهية تأتي مع الأكل|appetite comes|food|A2",
"Viele Köche verderben den Brei|كثرة الطباخين تفسد|too many cooks|worktalk|A2",
"Arbeit adelt|العمل شرف|work ennobles|work|A2",
"Erst die Arbeit dann das Vergnügen|العمل أولًا ثم المتعة|work first|work|A1",
"Zeit ist Geld|الوقت مال|time is money|money|A1",
"Geld regiert die Welt|المال يحكم العالم|money rules|money|A2",
"Geld allein macht nicht glücklich|المال وحده لا يسعد|money not happiness|money|A2",
"Spare in der Zeit|ادخر وقت الرخاء|save in time|money|A2",
"Wer den Pfennig nicht ehrt|من لا يحترم القرش|respect the penny|money|A2",
"Reisen bildet|السفر يعلّم|travel educates|travel|A2",
"Andere Länder andere Sitten|لكل بلد عاداته|other countries customs|travel|A2",
"Zu Hause ist es am schönsten|لا مكان كالبيت|home sweetest|home|A2",
"Trautes Heim Glück allein|بيتي جنتي|home bliss|home|A2",
"Ordnung ist das halbe Leben|النظام نصف الحياة|order half life|routine|A2",
"Jeder ist seines Glückes Schmied|كل صانع حظه|fortune smith|general|A2",
"Man lernt nie aus|المرء لا ينتهي من التعلم|never stop learning|study|A1",
"Es ist noch kein Meister vom Himmel gefallen|لا أحد وُلد معلمًا|no master fell|study|A2",
"Aller guten Dinge sind drei|الأشياء الجيدة ثلاثة|third time lucky|general|A2",
"Der dritte Mann gewinnt|الثالث يفوز|third wins|sports|A2",
"Hochmut kommt vor dem Fall|الغرور قبل السقوط|pride before fall|general|A2",
"Ehrlich währt am längsten|الصدق يدوم|honesty lasts|general|A2",
"Lügen haben kurze Beine|للكذب أرجل قصيرة|lies short legs|general|A2",
"Der Ehrliche ist der Dumme|الصادق يُستغل أحيانًا|honest fool|general|A2",
"Guter Rat ist teuer|النصيحة الجيدة غالية|advice expensive|general|A2",
"Rat kommt über Nacht|الصباح يجلب الحل|sleep on it|general|A2",
"Kommt Zeit kommt Rat|مع الوقت يأتي الحل|time brings counsel|general|A2",
"Abwarten und Tee trinken|انتظر واشرب شايًا|wait and see|colloquial|A2",
"Alles zu seiner Zeit|لكل شيء وقته|all in good time|time|A2",
"Eile mit Weile|العجلة مع التمهل|haste slowly|general|A2",
"Gut Ding will Weile haben|الشيء الجيد يحتاج وقتًا|good things take time|general|A2",
"Was lange währt wird endlich gut|ما طال انتظاره حلا|long wait good|general|A2",
"Ende gut alles gut2|نهاية جيدة كل شيء جيد|all well ends|general|A2",
"Aus den Augen aus dem Sinn|بعيد عن العين بعيد عن القلب|out of sight|emotions|A2",
"Getrennte Wege gehen|كل في طريقه|go separate ways|relationships|A2",
"Ein Herz und eine Seele|قلب واحد وروح واحدة|one heart soul|relationships|A2",
"Durch dick und dünn|في السراء والضراء|through thick and thin|relationships|A2",
"Hand in Hand|يدًا بيد|hand in hand|relationships|A2",
"In guten wie in schlechten Zeiten|في الجيد والسيئ|good and bad times|relationships|A2",
"Bis dass der Tod euch scheidet|حتى يفرقكم الموت|till death|relationships|A2",
"Alte Liebe rostet nicht|الحب القديم لا يصدأ|old love rusts not|relationships|A2",
"Gegenteil2|على العكس|on the contrary|general|A2",
"Im Großen und Ganzen|في المجمل|by and large|general|A2",
"Früher oder später|عاجلًا أم آجلًا|sooner or later|time|A2",
"Mehr oder weniger|أكثر أو أقل|more or less|general|A2",
"Nach und nach|شيئًا فشيئًا|little by little|general|A2",
"Hin und wieder|من حين لآخر|now and then|routine|A2",
"Ab und zu|أحيانًا|occasionally|routine|A1",
"Hier und da|هنا وهناك|here and there|location|A2",
"Auf und ab|صعودًا وهبوطًا|up and down|directions|A2",
"Mit Ach und Krach|بصعوبة بالغة|by skin of teeth|general|A2",
"Klipp und klar|بوضوح تام|loud and clear|communication|A2",
"Gang und gäbe|شائع ومعتاد|common practice|general|A2",
"Tag für Tag|يومًا بعد يوم|day by day|routine|A1",
"Stück für Stück|قطعة قطعة|piece by piece|general|A2",
"Wort für Wort|كلمة كلمة|word for word|study|A2",
"Schritt für Schritt2|خطوة خطوة|step by step|study|A1",
"Nach wie vor|كما قبل|as before|general|A2",
"Wie immer|كالعادة|as always|routine|A1",
"So oder so|على أي حال|either way|general|A2",
"Jetzt oder nie|الآن أو أبدًا|now or never|general|A2",
"Alles oder nichts|كل شيء أو لا شيء|all or nothing|general|A2",
"Halb so wild|ليس سيئًا لهذه الدرجة|half as bad|colloquial|A2",
"Nicht der Rede wert|لا يستحق الذكر|not worth mentioning|polite|A2",
"Keine Ursache|لا داعي للشكر|no reason|polite|A1",
"Selbstverständlich|بديهي|of course|polite|A1",
"Gern geschehen2|على الرحب والسعة|you're welcome|polite|A1",
"Kein Thema2|لا موضوع|no issue|colloquial|A2",
"Das geht klar|هذا مقبول|that works|colloquial|A2",
"Das passt mir|هذا يناسبني|suits me|general|A1",
"Das passt mir nicht|لا يناسبني|doesn't suit|general|A2",
"Da bin ich dabei|أنا مشارك|count me in|colloquial|A2",
"Da mache ich mit|سأشارك|I'll join|colloquial|A2",
"Ich bin dabei|أنا معكم|I'm in|colloquial|A1",
"Mal sehen2|لنرَ|let's see|colloquial|A1",
"Schauen wir mal|لنرَ|we'll see|colloquial|A1",
"Warten wir ab|لننتظر|let's wait|colloquial|A2",
"Kommt drauf an|يعتمد|depends|colloquial|A2",
"Je nachdem|حسب|depending|general|A2",
"Auf jeden Fall2|على أي حال|definitely|colloquial|A1",
"Auf keinen Fall2|مستحيل|no way|colloquial|A1",
"Keinesfalls|أبدًا|by no means|general|A2",
"Jedenfalls|على كل حال|anyway|general|A2",
"Trotzdem2|رغم ذلك|nevertheless|general|A1",
"Immerhin|على الأقل|at least|general|A2",
"Schließlich|في النهاية|after all|general|A2",
"Schließlich2|أخيرًا|finally|general|A2",
"Endlich2|أخيرًا|finally|general|A1",
"Plötzlich2|فجأة|suddenly|general|A1",
"Allmählich|تدريجيًا|gradually|general|A2",
"Gleichzeitig|في نفس الوقت|simultaneously|general|A2",
"Inzwischen|في هذه الأثناء|meanwhile|general|A2",
"Unterdessen|أثناء ذلك|meanwhile|general|A2",
"Nebenbei|على الهامش|on the side|general|A2",
"Beiläufig|عرضًا|incidentally|general|A2",
"Übrigens2|بالمناسبة|by the way|communication|A1",
"Apropos|بالمناسبة|apropos|communication|A2",
"Sozusagen|كما يقال|so to speak|communication|A2",
"Quasi|شبه|quasi|colloquial|A2",
"So ungefähr|تقريبًا هكذا|roughly|general|A2",
"Ungefähr2|حوالي|about|general|A1",
"Circa|نحو|circa|general|A2",
"Etwa2|حوالي|about|general|A1",
"Beinahe|يكاد|almost|general|A2",
"Fast2|تقريبًا|almost|general|A1",
"Kaum2|بالكاد|hardly|general|A2",
"Gerade2|للتو|just|time|A1",
"Eben2|للتو|just now|time|A2",
"Soeben|قبل قليل|just now|time|A2",
"Neulich|مؤخرًا|recently|time|A2",
"Kürzlich|حديثًا|lately|time|A2",
"Vorhin|قبل قليل|earlier|time|A2",
"Damals|آنذاك|back then|time|A2",
"Früher2|سابقًا|formerly|time|A1",
"Später2|لاحقًا|later|time|A1",
"Bald2|قريبًا|soon|time|A1",
"Gleich2|حالًا|right away|time|A1",
"Sofort2|فورًا|immediately|time|A1",
"Augenblicklich|لحظيًا|instantly|time|A2",
"Momentan|حاليًا|currently|time|A2",
"Derzeit2|حاليًا|at present|time|A2",
"Zurzeit|في الوقت الحالي|currently|time|A2",
"Heutzutage|في أيامنا|nowadays|time|A2",
"Alltags|يوميًا|daily|routine|A2",
"Wochentags|أيام الأسبوع|weekdays|routine|A2",
"Wochenends|عطلة الأسبوع|weekends|routine|A2"
];
if(typeof module!=="undefined")module.exports={IDIOMS};
