/* Coverage boosters: extra nouns, countries, verb-prep collocations, un-adjectives, transparent compounds. */
"use strict";
const NOUNS2=[
"Löffel2|der|Löffel|الملعقة الكبيرة|serving spoon|restaurant|A1","Serviette|die|Servietten|المنديل الورقي|napkin|restaurant|A1",
"Tablett|das|Tabletts|الصينية|tray|restaurant|A2","Krug|der|Krüge|الإبريق|jug|restaurant|A2",
"Kanne|die|Kannen|إبريق الشاي|teapot|food|A2","Pfanne|die|Pfannen|المقلاة|pan|food|A1",
"Topf|der|Töpfe|القدر|pot|food|A1","Deckel|der|Deckel|الغطاء|lid|food|A2",
"Schüssel|die|Schüsseln|الوعاء|bowl|food|A1","Becher|der|Becher|الكوب الورقي|cup|food|A1",
"Flasche|die|Flaschen|الزجاجة|bottle|food|A1","Dose|die|Dosen|العلبة|can|food|A1",
"Tüte|die|Tüten|الكيس|bag|shopping|A1","Karton|der|Kartons|الكرتون|box|home|A2",
"Seife|die|Seifen|الصابون|soap|home|A1","Shampoo|das|Shampoos|الشامبو|shampoo|home|A1",
"Zahnpasta|die|Zahnpasten|معجون الأسنان|toothpaste|home|A1","Zahnbürste|die|Zahnbürsten|فرشاة الأسنان|toothbrush|home|A1",
"Handtuch|das|Handtücher|المنشفة|towel|home|A1","Bademantel|der|Bademäntel|روب الحمام|bathrobe|clothing|A2",
"Pyjama|der|Pyjamas|البيجاما|pyjamas|clothing|A2","Badeanzug|der|Badeanzüge|لباس السباحة|swimsuit|clothing|A2",
"Regenmantel|der|Regenmäntel|معطف المطر|raincoat|clothing|A1","Pullover|der|Pullover|الكنزة|pullover|clothing|A1",
"T-Shirt|das|T-Shirts|التيشيرت|T-shirt|clothing|A1","Bluse|die|Blusen|البلوزة|blouse|clothing|A2",
"Jeans2|die|Jeans|بنطال الجينز|jeans|clothing|A1","Shorts|die|Shorts|الشورت|shorts|clothing|A2",
"Gürtel|der|Gürtel|الحزام|belt|clothing|A1","Krawatte2|die|Krawatten|ربطة العنق|necktie|clothing|A2",
"Schmuck|der|-|المجوهرات|jewellery|clothing|A2","Ring|der|Ringe|الخاتم|ring|clothing|A1",
"Kette|die|Ketten|العقد (قلادة)|necklace|clothing|A2","Ohrring|der|Ohrringe|القرط|earring|clothing|A2",
"Armband|das|Armbänder|السوار|bracelet|clothing|A2","Geldbörse|die|Geldbörsen|المحفظة|wallet|money|A1",
"Rucksack2|der|Rucksäcke|حقيبة الظهر|backpack|travel|A1","Koffer2|der|Koffer|حقيبة السفر|suitcase|travel|A1",
"Schirm|der|Schirme|المظلة|umbrella|weather|A1","Sonnenhut|der|Sonnenhüte|قبعة الشمس|sun hat|clothing|A2",
"Handschuh2|der|Handschuhe|القفاز|glove|clothing|A1","Schal2|der|Schals|الوشاح|scarf|clothing|A1",
"Werkzeug|das|Werkzeuge|الأداة (عدة)|tool|workplace|A2","Hammer|der|Hämmer|المطرقة|hammer|workplace|A2",
"Nagel|der|Nägel|المسمار|nail|workplace|A2","Schraube|die|Schrauben|البرغي|screw|workplace|A2",
"Schraubenzieher|der|Schraubenzieher|المفك|screwdriver|workplace|A2","Zange|die|Zangen|الكماشة|pliers|workplace|A2",
"Säge|die|Sägen|المنشار|saw|workplace|A2","Bohrer|der|Bohrer|المثقاب|drill|workplace|A2",
"Leiter|die|Leitern|السلم|ladder|home|A2","Eimer|der|Eimer|الدلو|bucket|home|A1",
"Besen|der|Besen|المكنسة|broom|home|A1","Wischmopp|der|Wischmopps|الممسحة|mop|home|A2",
"Lappen|der|Lappen|قطعة القماش|cloth|home|A2","Schwamm|der|Schwämme|الإسفنجة|sponge|home|A2",
"Kerze|die|Kerzen|الشمعة|candle|home|A1","Streichholz|das|Streichhölzer|عود الثقاب|match|home|A2",
"Feuerzeug|das|Feuerzeuge|الولاعة|lighter|home|A2","Batterie|die|Batterien|البطارية|battery|tech|A1",
"Glühlampe|die|Glühlampen|المصباح الكهربائي|light bulb|home|A2","Verlängerungskabel|das|Verlängerungskabel|وصلة الكهرباء|extension cable|home|A2",
"Schreibtisch|der|Schreibtische|مكتب الكتابة|desk|furniture|A1","Bürostuhl|der|Bürostühle|كرسي المكتب|office chair|workplace|A1",
"Aktenschrank|der|Aktenschränke|خزانة الملفات|filing cabinet|workplace|A2","Whiteboard|das|Whiteboards|السبورة البيضاء|whiteboard|workplace|A2",
"Beamer|der|Beamer|جهاز العرض|projector|workplace|A2","Flipchart|das|Flipcharts|لوحة العرض|flipchart|workplace|A2",
"Kugelschreiber|der|Kugelschreiber|القلم الجاف|ballpoint|school|A1","Marker|der|Marker|قلم التحديد|marker|school|A1",
"Textmarker|der|Textmarker|قلم التظليل|highlighter|study|A1","Klebestift|der|Klebestifte|صمغ الورق|glue stick|school|A1",
"Locher|der|Locher|الخرامة|hole punch|workplace|A2","Tacker|der|Tacker|الدباسة|stapler|workplace|A2",
"Ordner2|der|Ordner|ملف الأوراق|binder|workplace|A1","Heftstreifen|der|Heftstreifen|شريط الملف|file strip|school|A2",
"Notizbuch|das|Notizbücher|دفتر الملاحظات|notebook|study|A1","Kalender2|der|Kalender|المفكرة|planner|time|A1",
"Wecker|der|Wecker|المنبه|alarm clock|routine|A1","Brillenputztuch|das|Brillenputztücher|منديل النظارة|lens cloth|clothing|A2",
"Kontaktlinse|die|Kontaktlinsen|العدسة اللاصقة|contact lens|health|A2","Pflaster|das|Pflaster|اللاصق الطبي|plaster|health|A1",
"Verband|der|Verbände|الضمادة|bandage|health|A2","Salbe|die|Salben|المرهم|ointment|pharmacy|A2",
"Tropfen|der|Tropfen|القطرة (دواء)|drops|pharmacy|A2","Spritze|die|Spritzen|الحقنة|syringe|doctor|A2",
"Blutdruck|der|-|ضغط الدم|blood pressure|health|A2","Blutzucker|der|-|سكر الدم|blood sugar|health|A2",
"Puls|der|Pulse|النبض|pulse|health|A2","Röntgenbild|das|Röntgenbilder|صورة الأشعة|X-ray|doctor|A2",
"Wartebereich|der|Wartebereiche|منطقة الانتظار|waiting area|services|A2","Schalter|der|Schalter|الشباك (خدمة)|counter|services|A1",
"Automat|der|Automaten|الجهاز الآلي|machine|services|A1","Fahrkartenautomat|der|Fahrkartenautomaten|جهاز التذاكر|ticket machine|station|A2",
"Geldautomat|der|Geldautomaten|الصراف الآلي|ATM|banking|A1","Kontoauszug2|der|Kontoauszüge|كشف الحساب|statement|banking|A2",
"Überweisungsformular|das|Überweisungsformulare|نموذج التحويل|transfer form|banking|A2","Dauerauftrag|der|Daueraufträge|الأمر المستديم|standing order|banking|A2",
"Lastschrift|die|Lastschriften|الخصم المباشر|direct debit|banking|A2","Zinsen|die|Zinsen|الفوائد|interest|money|A2",
"Schulden|die|Schulden|الديون|debts|money|A2","Raten|die|Raten|الأقساط|instalments|money|A2",
"Anzahlung|die|Anzahlungen|المقدم (دفعة)|down payment|money|A2","Restbetrag|der|Restbeträge|المبلغ المتبقي|remainder|money|A2",
"Trinkgeld2|das|Trinkgelder|الإكرامية|tip|restaurant|A2","Speisekarte2|die|Speisekarten|قائمة الطعام|menu|restaurant|A1",
"Tagesgericht|das|Tagesgerichte|طبق اليوم|daily special|restaurant|A2","Vorspeise|die|Vorspeisen|المقبلات|starter|restaurant|A2",
"Hauptgericht|das|Hauptgerichte|الطبق الرئيسي|main course|restaurant|A2","Nachtisch|der|Nachtische|الحلوى|dessert|restaurant|A1",
"Beilage|die|Beilagen|الطبق الجانبي|side dish|restaurant|A2","Gewürz|das|Gewürze|التابل|spice|food|A1",
"Pfeffer|der|-|الفلفل|pepper|food|A1","Paprika|der|-|الفلفل الحلو / البابريكا|paprika|food|A2",
"Essig|der|-|الخل|vinegar|food|A2","Öl2|das|Öle|الزيت|oil|food|A1",
"Mehl|das|-|الدقيق|flour|food|A1","Hefe|die|-|الخميرة|yeast|food|A2",
"Teig|der|Teige|العجين|dough|food|A2","Kuchen2|der|Kuchen|الكعكة|cake|food|A1",
"Torte|die|Torten|التورتة|gateau|food|A2","Keks|der|Kekse|البسكويت|biscuit|food|A1",
"Schokolade|die|Schokoladen|الشوكولاتة|chocolate|food|A1","Bonbon|das|Bonbons|الحلوى|candy|food|A2",
"Eis|das|-|الآيس كريم|ice cream|food|A1","Eiswürfel|der|Eiswürfel|مكعب الثلج|ice cube|food|A2",
"Sahne|die|-|الكريمة|cream|food|A2","Joghurt|der|Joghurts|الزبادي|yoghurt|food|A1",
"Quark|der|-|الجبن القريش|curd cheese|food|A2","Marmelade|die|Marmeladen|المربى|jam|food|A1",
"Honig|der|-|العسل|honey|food|A1","Nuss|die|Nüsse|المكسرات (حبة)|nut|food|A2",
"Mandel|die|Mandeln|اللوز|almond|food|A2","Haselnuss|die|Haselnüsse|البندق|hazelnut|food|A2",
"Walnuss|die|Walnüsse|الجوز|walnut|food|A2","Rosine|die|Rosinen|الزبيب|raisin|food|A2",
"Dattel|die|Datteln|التمر|date|food|A2","Feige|die|Feigen|التين|fig|food|A2",
"Granatapfel|der|Granatäpfel|الرمان|pomegranate|food|A2","Weintraube|die|Weintrauben|العنب|grape|food|A1",
"Erdbeere|die|Erdbeeren|الفراولة|strawberry|food|A1","Himbeere|die|Himbeeren|توت العليق|raspberry|food|A2",
"Blaubeere|die|Blaubeeren|التوت الأزرق|blueberry|food|A2","Kirsche|die|Kirschen|الكرز|cherry|food|A1",
"Pfirsich|der|Pfirsiche|الخوخ|peach|food|A1","Aprikose|die|Aprikosen|المشمش|apricot|food|A2",
"Pflaume|die|Pflaumen|البرقوق|plum|food|A2","Birne|die|Birnen|الكمثرى|pear|food|A1",
"Zitrone|die|Zitronen|الليمون|lemon|food|A1","Limette|die|Limetten|الليمون الأخضر|lime|food|A2",
"Kiwi|die|Kiwis|الكيوي|kiwi|food|A2","Mango|die|Mangos|المانجو|mango|food|A2",
"Ananas|die|Ananas|الأناناس|pineapple|food|A2","Melone|die|Melonen|البطيخ|melon|food|A1",
"Wassermelone|die|Wassermelonen|البطيخ الأحمر|watermelon|food|A1","Zwiebel|die|Zwiebeln|البصل|onion|food|A1",
"Knoblauch|der|-|الثوم|garlic|food|A1","Karotte|die|Karotten|الجزر|carrot|food|A1",
"Paprikaschote|die|Paprikaschoten|ثمرة الفلفل|bell pepper|food|A2","Champignon|der|Champignons|الفطر|mushroom|food|A2",
"Brokkoli|der|-|البروكلي|broccoli|food|A2","Blumenkohl|der|-|القرنبيط|cauliflower|food|A2",
"Spinat|der|-|السبانخ|spinach|food|A2","Erbse|die|Erbsen|البازلاء|pea|food|A2",
"Bohne|die|Bohnen|الفاصوليا|bean|food|A2","Linse|die|Linsen|العدس|lentil|food|A2",
"Kichererbse|die|Kichererbsen|الحمص|chickpea|food|A2","Mais|der|-|الذرة|corn|food|A1",
"Hafer|der|-|الشوفان|oats|food|A2","Müsli|das|Müslis|الموسلي|muesli|food|A2",
"Portion|die|Portionen|الحصة (طعام)|portion|food|A2","Rest|der|Reste|البقايا|leftovers|food|A2",
"Butterbrot|das|Butterbrote|شطيرة الزبدة|buttered bread|food|A1","Käsebrot|das|Käsebrote|شطيرة الجبن|cheese sandwich|food|A1",
"Wurstbrot|das|Wurstbrote|شطيرة النقانق|sausage sandwich|food|A1","Belag|der|Beläge|الحشو (شطيرة)|topping|food|A2",
"Wurst|die|Würste|النقانق|sausage|food|A1","Schinken|der|-|لحم الخنزير المقدد|ham|food|A2",
"Aufschnitt|der|-|اللانشون (شرائح)|cold cuts|food|A2","Rindfleisch|das|-|لحم البقر|beef|food|A2",
"Schweinefleisch|das|-|لحم الخنزير|pork|food|A2","Lammfleisch|das|-|لحم الضأن|lamb|food|A2",
"Hähnchenbrust|die|Hähnchenbrüste|صدر الدجاج|chicken breast|food|A2","Fischstäbchen|das|Fischstäbchen|أصابع السمك|fish fingers|food|A2",
"Thunfisch|der|Thunfische|التونة|tuna|food|A2","Lachs|der|Lachse|السلمون|salmon|food|A2",
"Garnele|die|Garnelen|الروبيان|shrimp|food|A2","Eiweiß|das|-|بياض البيض|egg white|food|A2",
"Eigelb|das|-|صفار البيض|egg yolk|food|A2","Rührei|das|Rühreier|البيض المخفوق|scrambled eggs|food|A2",
"Spiegelei|das|Spiegeleier|البيض المقلي (عيون)|fried egg|food|A2","Pfannkuchen|der|Pfannkuchen|البان كيك|pancake|food|A2",
"Waffel|die|Waffeln|الوافل|waffle|food|A2","Toastbrot|das|Toastbrote|خبز التوست|toast|food|A1",
"Vollkornbrot|das|Vollkornbrote|خبز الحبوب الكاملة|wholegrain bread|food|A1","Brötchen2|das|Brötchen|الخبز الصغير|roll|food|A1",
"Brezel|die|Brezeln|البريتزل|pretzel|food|A2","Croissant|das|Croissants|الكرواسون|croissant|food|A2",
"Marmeladenbrot|das|Marmeladenbrote|شطيرة المربى|jam sandwich|food|A2","Nusscreme|die|Nusscremes|كريمة البندق|nut spread|food|A2",
"Kaffeemaschine|die|Kaffeemaschinen|ماكينة القهوة|coffee machine|home|A2","Wasserkocher|der|Wasserkocher|غلاية الماء|kettle|home|A2",
"Toaster|der|Toaster|محمصة الخبز|toaster|home|A2","Mikrowelle|die|Mikrowellen|الميكروويف|microwave|home|A2",
"Geschirrspüler|der|Geschirrspüler|غسالة الصحون|dishwasher|home|A2","Backofen|der|Backöfen|الفرن|oven|home|A1",
"Dunstabzugshaube|die|Dunstabzugshauben|شفاط المطبخ|extractor hood|home|A2","Küchenrolle|die|Küchenrollen|ورق المطبخ|kitchen roll|home|A2",
"Müllbeutel|der|Müllbeutel|كيس القمامة|bin bag|home|A1","Putzmittel|das|Putzmittel|منظف|cleaning agent|home|A2",
"Waschmittel|das|Waschmittel|مسحوق الغسيل|detergent|home|A2","Weichspüler|der|Weichspüler|منعم الملابس|softener|home|A2",
"Bügelbrett|das|Bügelbretter|طاولة الكي|ironing board|home|A2","Wäscheständer|der|Wäscheständer|منشر الغسيل|clothes horse|home|A2",
"Wäschekorb|der|Wäschekörbe|سلة الغسيل|laundry basket|home|A2","Kleiderbügel|der|Kleiderbügel|شماعة الملابس|hanger|home|A1",
"Schuhschrank|der|Schuhschränke|خزانة الأحذية|shoe cabinet|furniture|A2","Garderobe|die|Garderoben|المشجب (مدخل)|hall stand|furniture|A2",
"Kommode|die|Kommoden|الكومودينو|chest of drawers|furniture|A2","Nachttisch|der|Nachttische|الكومودينو (جانب السرير)|nightstand|furniture|A2",
"Bücherregal|das|Bücherregale|مكتبة الكتب|bookshelf|furniture|A1","Schreibtischlampe|die|Schreibtischlampen|مصباح المكتب|desk lamp|furniture|A2",
"Stehlampe|die|Stehlampen|المصباح الأرضي|floor lamp|furniture|A2","Tischdecke|die|Tischdecken|مفرش الطاولة|tablecloth|home|A2",
"Blumentopf|der|Blumentöpfe|مزهرية النبات|flowerpot|home|A2","Gießkanne|die|Gießkannen|سقاية النبات|watering can|home|A2",
"Balkonkasten|der|Balkonkästen|صندوق الشرفة|balcony box|home|A2","Gartenschlauch|der|Gartenschläuche|خرطوم الحديقة|garden hose|home|A2",
"Rasenmäher|der|Rasenmäher|جزازة العشب|lawnmower|home|A2","Grill|der|Grills|الشواية|grill|home|A2",
"Holzkohle|die|-|فحم الشواء|charcoal|food|A2","Picknickkorb|der|Picknickkörbe|سلة النزهة|picnic basket|hobbies|A2",
"Zelt|das|Zelte|الخيمة|tent|travel|A2","Schlafsack|der|Schlafsäcke|كيس النوم|sleeping bag|travel|A2",
"Isomatte|die|Isomatten|فرشة العزل|sleeping mat|travel|A2","Taschenlampe|die|Taschenlampen|الكشاف|torch|travel|A2",
"Reiseführer|der|Reiseführer|دليل السفر|guidebook|travel|A2","Stadtplan|der|Stadtpläne|خريطة المدينة|city map|city|A2",
"Aussichtspunkt|der|Aussichtspunkte|نقطة المشاهدة|viewpoint|travel|A2","Sehenswürdigkeit|die|Sehenswürdigkeiten|المعلم السياحي|sight|travel|A2",
"Eintrittskarte|die|Eintrittskarten|تذكرة الدخول|admission ticket|travel|A2","Reisepass|der|Reisepässe|جواز السفر|passport|documents|A1",
"Boardkarte|die|Boardkarten|بطاقة الصعود|boarding pass|airport|A2","Sicherheitskontrolle|die|Sicherheitskontrollen|التفتيش الأمني|security check|airport|A2",
"Gepäckband|das|Gepäckbänder|سير الأمتعة|carousel|airport|A2","Verspätungsmeldung|die|Verspätungsmeldungen|إعلان التأخير|delay announcement|airport|A2",
"Ankunftshalle|die|Ankunftshallen|صالة الوصول|arrivals hall|airport|A2","Abflughalle|die|Abflughallen|صالة المغادرة|departure hall|airport|A2",
"Fernzug|der|Fernzüge|القطار السريع|long-distance train|transport|A2","Regionalzug|der|Regionalzüge|القطار الإقليمي|regional train|transport|A2",
"Waggon|der|Waggons|عربة القطار|carriage|transport|A2","Schaffner|der|Schaffner|مفتش التذاكر|conductor|jobs|A2",
"Reservierung2|die|Reservierungen|الحجز|reservation|travel|A2","Stornierung|die|Stornierungen|الإلغاء|cancellation|travel|A2",
"Reiseversicherung|die|Reiseversicherungen|تأمين السفر|travel insurance|travel|A2","Impfnachweis|der|Impfnachweise|إثبات اللقاح|vaccination proof|documents|A2",
"Aufenthaltserlaubnis|die|Aufenthaltserlaubnisse|تصريح الإقامة|residence permit|documents|A2","Arbeitserlaubnis|die|Arbeitserlaubnisse|تصريح العمل|work permit|documents|A2",
"Einbürgerung|die|Einbürgerungen|التجنيس|naturalisation|services|A2","Integrationsbescheinigung|die|Integrationsbescheinigungen|شهادة الاندماج|integration certificate|services|A2",
"Sprachzertifikat|das|Sprachzertifikate|الشهادة اللغوية|language certificate|study|A2","Anerkennung|die|Anerkennungen|الاعتراف بالمؤهل|recognition|services|A2",
"Zeugnisanerkennung|die|Zeugnisanerkennungen|معادلة الشهادة|credential evaluation|services|A2","Vorbereitungskurs|der|Vorbereitungskurse|الدورة التحضيرية|preparatory course|study|A2"
];
/* Countries: land|ar|adjDe|adjAr|personM|personF — person nouns attach table gender/pl */
const COUNTRIES=[
"Deutschland|ألمانيا|deutsch|ألماني|Deutscher|Deutsche","Frankreich|فرنسا|französisch|فرنسي|Franzose|Französin",
"Italien|إيطاليا|italienisch|إيطالي|Italiener|Italienerin","Spanien|إسبانيا|spanisch|إسباني|Spanier|Spanierin",
"Portugal|البرتغال|portugiesisch|برتغالي|Portugiese|Portugiesin","Niederlande|هولندا|niederländisch|هولندي|Niederländer|Niederländerin",
"Belgien|بلجيكا|belgisch|بلجيكي|Belgier|Belgierin","Schweiz|سويسرا|schweizerisch|سويسري|Schweizer|Schweizerin",
"Österreich|النمسا|österreichisch|نمساوي|Österreicher|Österreicherin","Polen|بولندا|polnisch|بولندي|Pole|Polin",
"Tschechien|التشيك|tschechisch|تشيكي|Tscheche|Tschechin","Slowakei|سلوفاكيا|slowakisch|سلوفاكي|Slowake|Slowakin",
"Ungarn|المجر|ungarisch|مجري|Ungar|Ungarin","Rumänien|رومانيا|rumänisch|روماني|Rumäne|Rumänin",
"Bulgarien|بلغاريا|bulgarisch|بلغاري|Bulgare|Bulgarin","Griechenland|اليونان|griechisch|يوناني|Grieche|Griechin",
"Kroatien|كرواتيا|kroatisch|كرواتي|Kroate|Kroatin","Serbien|صربيا|serbisch|صربي|Serbe|Serbin",
"Bosnien|البوسنة|bosnisch|بوسني|Bosnier|Bosnierin","Albanien|ألبانيا|albanisch|ألباني|Albaner|Albanerin",
"Nordmazedonien|مقدونيا الشمالية|nordmazedonisch|مقدوني|Nordmazedonier|Nordmazedonierin","Ukraine|أوكرانيا|ukrainisch|أوكراني|Ukrainer|Ukrainerin",
"Russland|روسيا|russisch|روسي|Russe|Russin","Weißrussland|بيلاروسيا|weißrussisch|بيلاروسي|Weißrusse|Weißrussin",
"Türkei|تركيا|türkisch|تركي|Türke|Türkin","Griechenland2|اليونان|griechisch|يوناني|Zypriot|Zypriotin",
"Ägypten|مصر|ägyptisch|مصري|Ägypter|Ägypterin","Libyen|ليبيا|libysch|ليبي|Libyer|Libyerin",
"Tunesien|تونس|tunesisch|تونسي|Tunesier|Tunesierin","Algerien|الجزائر|algerisch|جزائري|Algerier|Algerierin",
"Marokko|المغرب|marokkanisch|مغربي|Marokkaner|Marokkanerin","Sudan|السودان|sudanesisch|سوداني|Sudanese|Sudanesin",
"Äthiopien|إثيوبيا|äthiopisch|إثيوبي|Äthiopier|Äthiopierin","Somalia|الصومال|somalisch|صومالي|Somalier|Somalierin",
"Syrien|سوريا|syrisch|سوري|Syrer|Syrerin","Irak|العراق|irakisch|عراقي|Iraker|Irakerin",
"Jordanien|الأردن|jordanisch|أردني|Jordanier|Jordanierin","Libanon|لبنان|libanesisch|لبناني|Libanese|Libanesin",
"Israel|إسرائيل|israelisch|إسرائيلي|Israeli|Israelin","Palästina|فلسطين|palästinensisch|فلسطيني|Palästinenser|Palästinenserin",
"Saudi-Arabien|السعودية|saudisch|سعودي|Saudi|Saudin","Jemen|اليمن|jemenitisch|يمني|Jemenit|Jemenitin",
"Oman|عمان|omanisch|عماني|Omani|Omanin","Vereinigte Arabische Emirate|الإمارات|emiratisch|إماراتي|Emirater|Emiraterin",
"Katar|قطر|katarisch|قطري|Katarer|Katarerin","Kuwait|الكويت|kuwaitisch|كويتي|Kuwaiter|Kuwaiterin",
"Bahrain|البحرين|bahrainisch|بحريني|Bahrainer|Bahrainerin","Iran|إيران|iranisch|إيراني|Iraner|Iranerin",
"Afghanistan|أفغانستان|afghanisch|أفغاني|Afghane|Afghanin","Pakistan|باكستان|pakistanisch|باكستاني|Pakistaner|Pakistanerin",
"Indien|الهند|indisch|هندي|Inder|Inderin","Bangladesch|بنغلاديش|bangladeschisch|بنغلاديشي|Bangladescher|Bangladescherin",
"China|الصين|chinesisch|صيني|Chinese|Chinesin","Japan|اليابان|japanisch|ياباني|Japaner|Japanerin",
"Südkorea|كوريا الجنوبية|südkoreanisch|كوري جنوبي|Südkoreaner|Südkoreanerin","Vietnam|فيتنام|vietnamesisch|فيتنامي|Vietnamese|Vietnamesin",
"Thailand|تايلاند|thailändisch|تايلاندي|Thailänder|Thailänderin","Indonesien|إندونيسيا|indonesisch|إندونيسي|Indonesier|Indonesierin",
"Malaysia|ماليزيا|malaysisch|ماليزي|Malaysier|Malaysierin","Philippinen|الفلبين|philippinisch|فلبيني|Philippiner|Philippinerin",
"USA|الولايات المتحدة|amerikanisch|أمريكي|Amerikaner|Amerikanerin","Kanada|كندا|kanadisch|كندي|Kanadier|Kanadierin",
"Mexiko|المكسيك|mexikanisch|مكسيكي|Mexikaner|Mexikanerin","Brasilien|البرازيل|brasilianisch|برازيلي|Brasilianer|Brasilianerin",
"Argentinien|الأرجنتين|argentinisch|أرجنتيني|Argentinier|Argentinierin","Kolumbien|كولومبيا|kolumbianisch|كولومبي|Kolumbianer|Kolumbianerin",
"Australien|أستراليا|australisch|أسترالي|Australier|Australierin","Neuseeland|نيوزيلندا|neuseeländisch|نيوزيلندي|Neuseeländer|Neuseeländerin",
"Nigeria|نيجيريا|nigerianisch|نيجيري|Nigerianer|Nigerianerin","Ghana|غانا|ghanaisch|غاني|Ghanaer|Ghanaerin",
"Kenia|كينيا|kenianisch|كيني|Kenianer|Kenianerin","Südafrika|جنوب أفريقيا|südafrikanisch|جنوب أفريقي|Südafrikaner|Südafrikanerin",
"Eritrea|إريتريا|eritreisch|إريتري|Eritreer|Eritreerin","England|إنجلترا|englisch|إنجليزي|Engländer|Engländerin",
"Schottland|اسكتلندا|schottisch|اسكتلندي|Schotte|Schottin","Irland|أيرلندا|irisch|أيرلندي|Ire|Irin",
"Norwegen|النرويج|norwegisch|نرويجي|Norweger|Norwegerin","Schweden|السويد|schwedisch|سويدي|Schwede|Schwedin",
"Dänemark|الدنمارك|dänisch|دنماركي|Däne|Dänin","Finnland|فنلندا|finnisch|فنلندي|Finne|Finnin"
];
/* Verb+Prep collocations as phrase entries: de|ar|en */
const VPREP=[
"warten auf|ينتظر|wait for","denken an|يفكر في|think of","sich freuen auf|متشوق لـ|look forward to",
"sich freuen über|سعيد بـ|be glad about","Angst haben vor|خائف من|be afraid of","sich kümmern um|يعتني بـ|take care of",
"sich bewerben um|يتقدم لـ|apply for","bitten um|يطلب|ask for","danken für|يشكر على|thank for",
"sich beschweren über|يشتكي من|complain about","teilnehmen an|يشارك في|take part in","glauben an|يؤمن بـ|believe in",
"sich interessieren für|مهتم بـ|be interested in","sich verlieben in|يقع في حب|fall in love with","sich trennen von|ينفصل عن|separate from",
"sich gewöhnen an|يعتاد على|get used to","leiden an|يعاني من|suffer from","zweifeln an|يشك في|doubt",
"riechen nach|تفوح منه رائحة|smell of","schmecken nach|طعمه مثل|taste of","fragen nach|يسأل عن|ask about",
"suchen nach|يبحث عن|search for","sich sehnen nach|يتوق إلى|long for","sich erkundigen nach|يستفسر عن|enquire about",
"gehören zu|ينتمي إلى|belong to","gratulieren zu|يهنئ بـ|congratulate on","einladen zu|يدعو إلى|invite to",
"überreden zu|يقنع بـ|persuade to","beginnen mit|يبدأ بـ|begin with","aufhören mit|يتوقف عن|stop",
"zufrieden sein mit|راضٍ عن|be satisfied with","verheiratet sein mit|متزوج من|be married to","sich treffen mit|يلتقي بـ|meet with",
"sprechen mit|يتحدث مع|speak with","sprechen über|يتحدث عن|speak about","diskutieren über|يناقش|discuss",
"lachen über|يضحك على|laugh about","sich ärgern über|ينزعج من|be annoyed about","sich informieren über|يستعلم عن|inform about",
"sich unterhalten über|يتحادث عن|converse about","nachdenken über|يتأمل|reflect on","entscheiden über|يقرر بشأن|decide on",
"verfügen über|يملك/يتصرف في|have at disposal","herrschen über|يسود على|rule over","klagen über|يشكو من|complain of",
"arbeiten an|يعمل على|work on","sterben an|يموت بـ|die of","sich beteiligen an|يشارك في|participate in",
"haften für|يضمن|be liable for","sorgen für|يعتني/يوفر لـ|provide for","sich entscheiden für|يختار|opt for",
"stimmen für|يصوت لـ|vote for","kämpfen für|يكافح من أجل|fight for","sich einsetzen für|يدافع عن|stand up for",
"bestehen aus|يتكون من|consist of","resultieren aus|ينتج عن|result from","lernen aus|يتعلم من|learn from",
"kommen aus|يأتي من|come from","fliehen aus|يهرب من|flee from","sich ergeben aus|ينتج عن|follow from",
"schützen vor|يحمي من|protect from","warnen vor|يحذر من|warn about","fliehen vor|يفر من|flee from",
"sich fürchten vor|يخاف من|fear","Respekt haben vor|يحترم|respect","sicher sein vor|آمن من|be safe from",
"abhängen von|يعتمد على|depend on","träumen von|يحلم بـ|dream of","erzählen von|يروي عن|tell about",
"hören von|يسمع عن|hear of","profitieren von|يستفيد من|profit from","sich erholen von|يتعافى من|recover from",
"überzeugt sein von|مقتنع بـ|be convinced of","begeistert sein von|متحمس لـ|be excited about","enttäuscht sein von|مصاب بخيبة من|be disappointed by"
];
/* un- adjectives: base -> full form (all real words) */
const UNADJ=[
"geduldig|ungeduldig|غير صبور|impatient","ehrlich|unehrlich|غير صادق|dishonest","deutlich|undeutlich|غير واضح|unclear",
"sicher|unsicher|غير متأكد|unsure","möglich|unmöglich|مستحيل|impossible","nötig|unnötig|غير ضروري|unnecessary",
"ruhig|unruhig|قلق|restless","geduldig2|ungeduldig|متسرع|impatient","frei|unfrei|غير حر|unfree",
"gerecht|ungerecht|ظالم|unjust","gläubig|ungläubig|غير مصدق|incredulous","gesund|ungesund|غير صحي|unhealthy",
"glücklich2|unglücklich|تعيس|unhappy","geduldig3|ungeduldig|نافد الصبر|impatient","höflich2|unhöflich|غير مهذب|impolite",
"klar|unklar|غير واضح|unclear","logisch|unlogisch|غير منطقي|illogical","moralisch|unmoralisch|غير أخلاقي|immoral",
"natürlich|unnatürlich|غير طبيعي|unnatural","normal2|unnormal|شاذ|abnormal","praktisch2|unpraktisch|غير عملي|impractical",
"pünktlich3|unpünktlich|غير دقيق|unpunctual","reif|unreif|غير ناضج|immature","rein|unrein|غير نقي|impure",
"schuldig|unschuldig|بريء|innocent","sichtbar|unsichtbar|غير مرئي|invisible","sicher2|unsicher|متزعزع|insecure",
"sympathisch|unsympathisch|غير محبوب|unlikable","typisch|untypisch|غير نمطي|atypical","wahr|unwahr|غير صحيح|untrue",
"wichtig2|unwichtig|غير مهم|unimportant","gleich|ungleich|غير متساوٍ|unequal","endlich|unendlich|لا نهائي|infinite",
"sterblich|unsterblich|خالد|immortal","abhängig|unabhängig|مستقل|independent","bekannt2|unbekannt|مجهول|unknown",
"bequem|unbequem|غير مريح|uncomfortable","bewusst|unbewusst|غير واعٍ|unconscious","brauchbar|unbrauchbar|غير صالح|useless",
"dankbar|undankbar|جاحد|ungrateful","ehrlich3|unehrlich|مخادع|deceitful","erfahren|unerfahren|غير خبير|inexperienced",
"erwartet|unerwartet|غير متوقع|unexpected","freundlich2|unfreundlich|غير ودود|unfriendly","geduldig4|ungeduldig|عصبي|nervous",
"geeignet|ungeeignet|غير مناسب|unsuitable","gerecht2|ungerecht|جائر|unfair","gern2|ungern|على مضض|reluctantly"
];
/* Transparent compounds: head -> mods with gloss mode g(genitive noun gloss)/a(adjective gloss).
   MODG: stem -> [glossAr, mode]. Only transparent, non-lexicalized combos listed. */
const MODG={
Sommer:["الصيف","g"],Winter:["الشتاء","g"],Herbst:["الخريف","g"],Kinder:["الأطفال","g"],Schul:["المدرسة","g"],
Büro:["المكتب","g"],Stadt:["المدينة","g"],Haus:["المنزل","g"],Garten:["الحديقة","g"],Strand:["الشاطئ","g"],
Berg:["الجبل","g"],See:["البحيرة","g"],Fluss:["النهر","g"],Wald:["الغابة","g"],Dorf:["القرية","g"],
Haupt:["الرئيسية","a"],Neu:["الجديدة","a"],Alt:["القديمة","a"],Klein:["الصغيرة","a"],Groß:["الكبيرة","a"],
Tages:["اليوم","g"],Wochen:["الأسبوع","g"],Monats:["الشهر","g"],Jahres:["السنة","g"],Morgen:["الصباح","g"],
Abend:["المساء","g"],Nacht:["الليل","g"],Ferien:["العطلة","g"],Urlaubs:["العطلة","g"],Weihnachts:["الكريسماس","g"],
Hochzeits:["الزفاف","g"],Geburtstags:["الميلاد","g"],Familien:["العائلة","g"],Freundes:["الصديق","g"],Gäste:["الضيوف","g"],
Studenten:["الطلاب","g"],Lehrer:["المعلم","g"],Arzt:["الطبيب","g"],Patienten:["المرضى","g"],Kunden:["العملاء","g"],
Frauen:["النساء","g"],Männer:["الرجال","g"],Jugend:["الشباب","g"],Senioren:["الكبار","g"],Baby:["الرضيع","g"],
Hunde:["الكلاب","g"],Katzen:["القطط","g"],Vogel:["الطيور","g"],Fisch:["السمك","g"],Blumen:["الزهور","g"],
Apfel:["التفاح","g"],Milch:["الحليب","g"],Kaffee:["القهوة","g"],Tee:["الشاي","g"],Brot:["الخبز","g"],
Käse:["الجبن","g"],Schoko:["الشوكولاتة","g"],Zitronen:["الليمون","g"],Kartoffel:["البطاطا","g"],Tomaten:["الطماطم","g"],
Holz:["الخشب","g"],Glas:["الزجاج","g"],Metall:["المعدن","g"],Leder:["الجلد","g"],Wolle:["الصوف","g"],
Baumwoll:["القطن","g"],Seiden:["الحرير","g"],Papier:["الورق","g"],Plastik:["البلاستيك","g"],Stein:["الحجر","g"],
Sport:["الرياضة","g"],Spiel:["اللعب","g"],Tanz:["الرقص","g"],Musik:["الموسيقى","g"],Film:["الفيلم","g"],
Theater:["المسرح","g"],Konzert:["الحفل","g"],Fußball:["كرة القدم","g"],Tennis:["التنس","g"],Schwimm:["السباحة","g"],
Reise:["السفر","g"],Wander:["التنزه","g"],Camping:["التخييم","g"],Strand2:["الشاطئ","g"],Ski:["التزلج","g"],
Arbeit:["العمل","g"],Büro2:["المكتب","g"],Betriebs:["الشركة","g"],Firmen:["الشركة","g"],Kollegen:["الزملاء","g"],
Schicht:["الوردية","g"],Nachtschicht:["الليلية","a"],Überstunden:["الإضافي","a"],Teilzeit:["الجزئي","a"],Vollzeit:["الكامل","a"],
Miet:["الإيجار","g"],Kauf:["الشراء","g"],Verkaufs:["البيع","g"],Werbe:["الإعلان","g"],Geschäfts:["العمل","g"],
Kranken:["المرضى","g"],Notfall:["الطوارئ","g"],Impf:["اللقاح","g"],Zahn:["الأسنان","g"],Augen:["العيون","g"],
Herz:["القلب","g"],Rücken:["الظهر","g"],Kopf:["الرأس","g"],Hand:["اليد","g"],Fuß:["القدم","g"],
Blut:["الدم","g"],Haut:["الجلد","g"],Knochen:["العظام","g"],Magen:["المعدة","g"],Leber:["الكبد","g"],
Bus:["الحافلة","g"],Bahn:["القطار","g"],Zug:["القطار","g"],Flug:["الطائرة","g"],Auto:["السيارة","g"],
Fahrrad:["الدراجة","g"],Schiff:["السفينة","g"],U:["المترو","g"],Straßenbahn:["الترام","g"],Taxi:["التاكسي","g"],
Internet:["الإنترنت","g"],Computer:["الحاسوب","g"],Handy:["الهاتف","g"],E:["الإلكترونية","a"],Online:["الإلكتروني","a"],
Video:["الفيديو","g"],Foto:["الصور","g"],Ton:["الصوت","g"],Druck:["الطباعة","g"],Kopier:["النسخ","g"]
};
const SAFECOMP=[
"Abend:Abend2:Abendessen,Abendkleid:Abend:Abendprogramm","Kurs:Sprach:Kursraum,Kursleiter:Kursteilnehmer",
"Platz:Markt:Parkplatz,Sitz:Spiel:Sitzplatz","Raum:Wohn:Arbeits:Wohnraum,Schlaf:Schlafraum,Klassen:Klassenraum",
"Zeit:Morgen:Abend:Mittags:Freizeit:Arbeitszeit,Schlafenszeit:Essenszeit",
"Plan:Stadt:Tages:Wochen:Stundenplan:Reise:Reiseplan",
"Liste:Einkaufs:Wort:Gäste:Preis:Preisliste:Anwesenheitsliste",
"Buch:Lesebuch:Liederbuch:Merkbuch:Tagebuch:Notiz:Notizbuch",
"Spiel:Ball:Gesellschafts:Handy:Kartenspiel:Würfelspiel",
"Wetter:Regen:Schnee:Sturm:Unwetter:Frühlingswetter",
"Urlaub:Strand:Berg:Ski:Camping:Urlaubsort:Urlaubszeit",
"Kleidung:Sommer:Winter:Sport:Arbeits:Berufs:Arbeitskleidung",
"Schuh:Sommer:Winter:Lauf:Fußballschuh:Tanzschuh",
"Essen:Hunde:Katzen:Baby:Abend:Abendbrot",
"Trinken:Erfrischungs:Heißgetränk:Kaltgetränk:Pausengetränk",
"Milch:Kaffee:Schoko:Kondens:Vollmilch",
"Käse:Berg:Frisch:Parmesan:Käseplatte",
"Wurst:Leber:Blut:Teewurst:Wurstplatte",
"Fisch:See:Fluss:Meeresfrüchte:Räucherfisch",
"Obst:Beeren:Zitrus:Trockenobst:Obstsalat",
"Gemüse:Wurzel:Blatt:Gemüsesuppe:Tiefkühlgemüse",
"Salat:Kartoffel:Nudel:Obst:Blattsalat",
"Suppe:Tomaten:Kürbis:Hühner:Linsensuppe",
"Kuchen:Apfel:Schoko:Käse:Marmorkuchen",
"Brot:Toast:Roggen:Misch:Butterbrot",
"Getränk:Sport:Energie:Softgetränk:Heißgetränk2",
"Wasser:Apfel:Orangen:Trauben:Kirschsaft",
"Tee:Kräuter:Früchte:Schwarz:Eistee",
"Kaffee:Milch:Filter:Espresso:Cappuccino",
"Zimmer:Kinder:Gäste:Bade:Esszimmer",
"Wohnung:Dach:Ferien:Maisonette:Eigentumswohnung",
"Haus:Reihen:Doppel:Mehrfamilien:Landhaus",
"Garten:Gemüse:Blumen:Obst:Vorgarten",
"Tür:Zimmer:Balkon:Glashaus:Feuerschutztür",
"Fenster:Dach:Keller:Küchenfenster",
"Schrank:Kleider:Bücher:Wäsche:Eckschrank",
"Tisch:Ess:Küchen:Schreib:Nacht:Nachttisch",
"Stuhl:Büro:Küchen:Garten:Kinderstuhl",
"Bett:Kinder:Gäste:Etagen:Himmelbett",
"Lampe:Tisch:Steh:Nacht:Wandleuchte",
"Teppich:Läufer:Bad:Orientteppich",
"Bild:Rahmen:Familien:Urlaubs:Ölbild",
"Uhr:Wand:Armband:Wecker:Kirchturmuhr",
"Schlüssel:Nach:Haus:Briefkasten:Fahrradschlüssel",
"Geld:Bus:Taschen:Spiel:Urlaubsgeld",
"Preis:Grund:Tages:Sonder:Einheitspreis",
"Markt:Floh:Fisch:Wochen:Gemüsemarkt",
"Laden:Tante:Handy:Blumen:Buchladen",
"Ticket:Kino:Zug:Flug:Konzertticket",
"Reise:Bus:Flug:Schiffs:Tagesausflug",
"Koffer:Hand:Trolley:Reisekoffer",
"Rucksack:Wander:Schul:Tagesrucksack",
"Zelt:Kuppel:Familien:Festivalzelt",
"Strand:Handtuch:Liege:Sonnenschirm",
"Sport:Verein:Fitness:Leistungs-Schulsport",
"Training:Kraft:Ausdauer:Intervalltraining",
"Spiel:Feld:Hallen:Pokal:Freundschaftsspiel",
"Ball:Fuß:Tennis:Golf:Medizinball",
"Musik:Pop:Klassik:Rock:Hintergrundmusik",
"Film:Action:Horror:Doku:Kinderfilm",
"Konzert:Rock:Klassik:Open:Benefizkonzert",
"Theater:Kinder:Puppen:Straßentheater",
"Museum:Kunst:Natur:Freilichtmuseum",
"Park:Freizeit:National:Hundepark",
"Garten:Zoo:Botanischer:Rosengarten",
"See:Bad:Stausee:Bergsee",
"Fluss:Donau:Rhein:Uferpromenade",
"Berg:Haus:Hütte:Gipfelkreuz",
"Wald:Stadt:Misch:Pilzweg",
"Weg:Rad:Wander:Fußweg",
"Straße:Spiel:Einbahn:Seitenstraße",
"Brücke:Holz:Stein:Hängebrücke",
"Platz:Rathaus:Kirch:Marktplatz2",
"Turm:Fernseh:Kirch:Aussichtsturm",
"Kirche:Dorf:Stadt:Holzkirche",
"Schule:Grund:Musik:Tanz:Fahrschule",
"Uni:Bibliothek:Mensa:Campusplan",
"Kurs:Erste:Koch:Nähkurs",
"Prüfung:Nach:Abschluss:Zwischenprüfung",
"Note:Kopf:Schul:Endnote",
"Zeugnis:Zwischen:Abgangs:Arbeitszeugnis",
"Arbeit:Klausur:Gruppen:Projektarbeit",
"Hausaufgabe:Mathe:Deutsch:Englischaufgabe",
"Buch:Mathe:Deutsch:Lesebuch2",
"Heft:Schreib:Rechen:Vokabelheft2",
"Stift:Bunt:Blei:Filzstift",
"Tasche:Feder:Sport:Schultasche",
"Ranzen:Schul2:Grundschulranzen",
"Pause:Hof:Milch:Lesepause",
"Hof:Schul:Bauern:Pausenhof",
"Lehrer:Sport:Musik:Klassenlehrer",
"Schüler:Austausch:Erstklässler",
"Klasse:Schul:Abschlussklasse",
"Ferien:Sommer:Herbst:Osterferien",
"Zeugnis2:Halbjahres:Zwischenzeugnis",
"Beruf:Traum:Wunsch:Lehrberuf",
"Job:Ferien:Minijob:Nebenjob",
"Stelle:Voll:Teil:Lehrstelle",
"Bewerbung:Online:Initiativbewerbung",
"Lebenslauf:Tabellarischer:Onlinelebenslauf",
"Gespräch:Feedback:Mitarbeiter:Gehaltsgespräch",
"Vertrag:Leih:Zeit:Mietvertrag2",
"Gehalt:Einstiegs:Brutto:Nettogehalt",
"Lohn:Mindest:Stundenlohn",
"Urlaub:Rest:Sonder:Elternzeit",
"Schicht:Früh:Spät:Nachtschicht",
"Pause:Rauch:Kaffee:Feierabendpause",
"Kollege:Team:Büro:Zimmerkollege",
"Chef:Abteilungs:Schichtleiter",
"Büro:Großraum:Homeoffice:Chefbüro",
"Firma:Tochter:Mutterfirma",
"Meeting:Team:Online:Frühmeeting",
"Projekt:Schul:Forschungs:Herzensprojekt",
"Termin:Frist:Abgabe:Arzttermin2",
"Mail:Chef:Rund:Erinnerungsmail",
"Anruf:Kunden:Not:Fehlanruf",
"Handy:Ladekabel:Schutzhülle:Handyhülle",
"Computer:Arbeits:Büro:Gaming-PC",
"Laptop:Taschen:Büro:Businesslaptop",
"Tastatur:Funk:Gamingtastatur",
"Maus:Funk:Gamingmaus",
"Bildschirm:Flach:Zweitbildschirm",
"Drucker:Laser:Tintenstrahldrucker",
"Kabel:USB:HDMI:Ladekabel2",
"Akku:Handy:Laptop:Ersatzakku",
"App:Bank:Wetter:Nachrichtenapp",
"Seite:Start:Hilfe:Kontaktseite",
"Passwort:Mail:WLAN:Masterpasswort",
"Konto:E:Benutzerkonto",
"Mail:Adresse:Bestätigung:Spam-Mail",
"Foto:Pass:Urlaubs:Bewerbungsfoto",
"Video:Urlaubs:Image:Erklärvideo",
"Musik:Streaming:Lieblings:Warteschleifenmusik",
"Nachricht:Sprach:Fehler:Push-Nachricht",
"Anruf2:Rück:Notruf",
"Nummer:Service:Hotline:Rufnummer",
"Adresse:E:Rechnungsadresse",
"Paket:DHL:Nachnahme:Retourenpaket",
"Brief:Einschreiben:Liebesbrief2",
"Post:Abend:Morgenpost",
"Bank:Filial:Online:Hausbank",
"Karte:Geschenk:Rabatt:Kundenkarte",
"Automat:Geld:Fahrkarten:Getränkeautomat",
"Schalter:Info:Service:Abendschalter",
"Termin:Online:Beratung:Servicetermin",
"Formular:Online:Antragsformular",
"Antrag:Urlaubs:BAföG:Kindergeldantrag",
"Bescheid:Steuer:BAföG:Rentenbescheid",
"Ausweis:Studenten:Presse:Personalausweis",
"Pass:Impf:Reise:EU-Pass",
"Visum:Touristen:Arbeitsvisum",
"Ticket:Rück:Online:Gruppenticket",
"Bahnhof:Bus:Flughafenbahnhof",
"Gleis:Kopf:Stumpfgleis",
"Zug:Nacht:ICE:Regionalzug2",
"Bus:Nacht:Schul:Fernbus",
"Taxi:Ruf:Flughafentaxi",
"Fahrrad:E:Lasten:Klappfahrrad",
"Auto:Miet:E:Familienauto",
"Straße:Umgehungs:Spiel:Anliegerstraße",
"Ampel:Fußgänger:Bettlerampel",
"Kreuzung:Riesen:Beampelkreuzung",
"Parkhaus:Tief:Cityparkhaus",
"Tankstelle:Autobahn:SB-Tankstelle",
"Werkstatt:Vertrags:Freie:Fahrradwerkstatt",
"Reifen:Winter:Sommer:Ganzjahresreifen",
"Motor:E:Diesel:Benzinmotor",
"Bremse:Hand:Notbremse",
"Licht:Abblend:Fernlicht",
"Sitz:Kind:Auto:Beifahrersitz",
"Spiegel:Seiten:Rückspiegel",
"Kofferraum:Wunder:Reserveradmulde",
"Hospital:Kranken:Unfall:Notaufnahme",
"Arzt:Haus:Kinder:Notarzt",
"Praxis:Haus:Physio:Zahnarztpraxis",
"Apotheke:Online:Versandapotheke",
"Medikament:Schmerz:Husten:Krebsmedikament",
"Rezept:Kassen:Privat:Onlinerezept",
"Tee:Husten:Erkältungs:Kräutertee2",
"Salbe:Wund:Schmerz:Brandsalbe",
"Tablette:Schmerz:Schlaf:Eisentablette",
"Fieber:Heuschnupfen:Prüfungsangst",
"Husten:Reiz:Keuchhusten",
"Schnupfen:Heu:Stockschnupfen",
"Schmerz:Rücken:Kopf:Bauchschmerz",
"Allergie:Pollen:Nuss:Hausstauballergie",
"Impfung:Grippe:Corona:Auffrischimpfung",
"Test:Corona:Allergie:Selbsttest",
"Maske:FFP2:OP:Alltagsmaske",
"Termin:Impf:Blutspende:Vorsorgetermin",
"Sport:Yoga:Jogging:Rehasport",
"Diät:Eiweiß:Kartoffel:Brigitte-Diät",
"Rauch:Stopp:Passivrauchen",
"Alkohol:Bier:Wein:Feierabendbier",
"Droge:Einstiegs:Partydroge",
"Sucht:Handy:Spiel:Kaufsucht"
];
if(typeof module!=="undefined")module.exports={NOUNS2,COUNTRIES,VPREP,UNADJ,MODG,SAFECOMP};
