/* Curated nouns: de|art|plural|ar|en|cat|lvl — articles/plurals hand-verified, uncertain items excluded. */
"use strict";
const NOUNS=[
"Frau|die|Frauen|المرأة|woman|family|A1","Mann|der|Männer|الرجل|man|family|A1",
"Mutter|die|Mütter|الأم|mother|family|A1","Vater|der|Väter|الأب|father|family|A1",
"Kind|das|Kinder|الطفل|child|family|A1","Tochter|die|Töchter|الابنة|daughter|family|A1",
"Sohn|der|Söhne|الابن|son|family|A1","Eltern|die|Eltern|الوالدان|parents|family|A1",
"Bruder|der|Brüder|الأخ|brother|family|A1","Schwester|die|Schwestern|الأخت|sister|family|A1",
"Großmutter|die|Großmütter|الجدة|grandmother|family|A1","Großvater|der|Großväter|الجد|grandfather|family|A1",
"Baby|das|Babys|الرضيع|baby|family|A1","Familie|die|Familien|العائلة|family|family|A1",
"Onkel|der|Onkel|العم / الخال|uncle|family|A1","Tante|die|Tanten|العمة / الخالة|aunt|family|A1",
"Cousin|der|Cousins|ابن العم|cousin (m)|family|A2","Cousine|die|Cousinen|ابنة العم|cousin (f)|family|A2",
"Neffe|der|Neffen|ابن الأخ|nephew|family|A2","Nichte|die|Nichten|ابنة الأخ|niece|family|A2",
"Schwiegersohn|der|Schwiegersöhne|صهر|son-in-law|relationships|A2","Schwiegertochter|die|Schwiegertöchter|كنّة|daughter-in-law|relationships|A2",
"Freund|der|Freunde|الصديق|friend|people|A1","Freundin|die|Freundinnen|الصديقة|friend (f)|people|A1",
"Nachbar|der|Nachbarn|الجار|neighbor|neighborhood|A1","Nachbarin|die|Nachbarinnen|الجارة|neighbor (f)|neighborhood|A1",
"Gast|der|Gäste|الضيف|guest|people|A1","Besucher|der|Besucher|الزائر|visitor|people|A2",
"Mensch|der|Menschen|الإنسان|human|people|A1","Person|die|Personen|الشخص|person|people|A1",
"Name|der|Namen|الاسم|name|general|A1","Vorname|der|Vornamen|الاسم الأول|first name|documents|A2",
"Nachname|der|Nachnamen|اسم العائلة|last name|documents|A2","Adresse|die|Adressen|العنوان|address|dailylife|A1",
"Telefonnummer|die|Telefonnummern|رقم الهاتف|phone number|dailylife|A1","E-Mail|die|E-Mails|البريد الإلكتروني|email|internet|A1",
"Haus|das|Häuser|البيت|house|home|A1","Wohnung|die|Wohnungen|الشقة|apartment|home|A1",
"Zimmer|das|Zimmer|الغرفة|room|rooms|A1","Küche|die|Küchen|المطبخ|kitchen|rooms|A1",
"Badezimmer|das|Badezimmer|الحمام|bathroom|rooms|A1","Wohnzimmer|das|Wohnzimmer|غرفة المعيشة|living room|rooms|A1",
"Schlafzimmer|das|Schlafzimmer|غرفة النوم|bedroom|rooms|A1","Flur|der|Flure|الممر|hallway|rooms|A1",
"Balkon|der|Balkone|الشرفة|balcony|home|A1","Garten|der|Gärten|الحديقة|garden|home|A1",
"Keller|der|Keller|القبو|basement|home|A2","Dach|das|Dächer|السقف|roof|home|A2",
"Fenster|das|Fenster|النافذة|window|home|A1","Tür|die|Türen|الباب|door|home|A1",
"Wand|die|Wände|الحائط|wall|rooms|A1","Boden|der|Böden|الأرضية|floor|rooms|A1",
"Decke|die|Decken|السقف الداخلي|ceiling|rooms|A2","Treppe|die|Treppen|الدرج|stairs|home|A2",
"Aufzug|der|Aufzüge|المصعد|elevator|home|A2","Heizung|die|Heizungen|التدفئة|heating|home|A2",
"Lampe|die|Lampen|المصباح|lamp|furniture|A1","Tisch|der|Tische|الطاولة|table|furniture|A1",
"Stuhl|der|Stühle|الكرسي|chair|furniture|A1","Sofa|das|Sofas|الأريكة|sofa|furniture|A1",
"Bett|das|Betten|السرير|bed|furniture|A1","Schrank|der|Schränke|الخزانة|wardrobe|furniture|A1",
"Regal|das|Regale|الرف|shelf|furniture|A1","Spiegel|der|Spiegel|المرآة|mirror|furniture|A1",
"Teppich|der|Teppiche|السجادة|carpet|furniture|A1","Vorhang|der|Vorhänge|الستارة|curtain|furniture|A2",
"Kissen|das|Kissen|الوسادة|pillow|furniture|A1","Decke2|die|Decken|البطانية|blanket|furniture|A1",
"Herd|der|Herde|الموقد|stove|rooms|A2","Kühlschrank|der|Kühlschränke|الثلاجة|fridge|rooms|A1",
"Waschmaschine|die|Waschmaschinen|الغسالة|washing machine|home|A2","Staubsauger|der|Staubsauger|المكنسة الكهربائية|vacuum cleaner|home|A2",
"Schlüssel|der|Schlüssel|المفتاح|key|home|A1","Schloss|das|Schlösser|القفل|lock|home|A2",
"Miete|die|Mieten|الإيجار|rent|home|A2","Kaution|die|Kautionen|التأمين (مبلغ الضمان)|deposit|home|A2",
"Schule|die|Schulen|المدرسة|school|school|A1","Klasse|die|Klassen|الصف الدراسي|class|school|A1",
"Lehrer|der|Lehrer|المعلم|teacher|school|A1","Lehrerin|die|Lehrerinnen|المعلمة|teacher (f)|school|A1",
"Schüler|der|Schüler|التلميذ|pupil|school|A1","Schülerin|die|Schülerinnen|التلميذة|pupil (f)|school|A1",
"Buch|das|Bücher|الكتاب|book|school|A1","Heft|das|Hefte|الدفتر|notebook|school|A1",
"Stift|der|Stifte|القلم|pen|school|A1","Bleistift|der|Bleistifte|قلم الرصاص|pencil|school|A1",
"Radiergummi|der|Radiergummis|الممحاة|eraser|school|A1","Lineal|das|Lineale|المسطرة|ruler|school|A1",
"Schere|die|Scheren|المقص|scissors|school|A1","Klebstoff|der|Klebstoffe|الغراء|glue|school|A2",
"Tafel|die|Tafeln|السبورة|board|school|A1","Kreide|die|Kreiden|الطباشير|chalk|school|A2",
"Hausaufgabe|die|Hausaufgaben|الواجب المنزلي|homework|school|A1","Prüfung|die|Prüfungen|الامتحان|exam|school|A1",
"Note|die|Noten|الدرجة / العلامة|grade|school|A1","Zeugnis|das|Zeugnisse|الشهادة المدرسية|report card|school|A2",
"Pause|die|Pausen|الاستراحة|break|school|A1","Stunde|die|Stunden|الحصة / الساعة|lesson/hour|school|A1",
"Fach|das|Fächer|المادة الدراسية|subject|school|A1","Mathematik|die|-|الرياضيات|mathematics|education|A1",
"Deutsch2|das|-|اللغة الألمانية|German (language)|study|A1","Englisch|das|-|اللغة الإنجليزية|English|study|A1",
"Arabisch|das|-|اللغة العربية|Arabic|study|A1","Französisch|das|-|اللغة الفرنسية|French|study|A2",
"Universität|die|Universitäten|الجامعة|university|university|A1","Student|der|Studenten|الطالب الجامعي|student|university|A1",
"Studentin|die|Studentinnen|الطالبة الجامعية|student (f)|university|A1","Professor|der|Professoren|الأستاذ الجامعي|professor|university|A2",
"Vorlesung|die|Vorlesungen|المحاضرة|lecture|university|A2","Seminar|das|Seminare|الندوة الدراسية|seminar|university|A2",
"Bibliothek|die|Bibliotheken|المكتبة|library|university|A1","Mensa|die|Mensen|مطعم الجامعة|canteen|unilife|A2",
"Stipendium|das|Stipendien|المنحة الدراسية|scholarship|university|A2","Abschluss|der|Abschlüsse|التخرج / الشهادة|graduation|university|A2",
"Arbeit|die|Arbeiten|العمل|work|work|A1","Beruf|der|Berufe|المهنة|profession|jobs|A1",
"Job|der|Jobs|الوظيفة|job|jobs|A1","Stelle|die|Stellen|الوظيفة الشاغرة|position|jobs|A2",
"Bewerbung|die|Bewerbungen|طلب التوظيف|application|applications|A2","Lebenslauf|der|Lebensläufe|السيرة الذاتية|CV|applications|A2",
"Vorstellungsgespräch|das|Vorstellungsgespräche|مقابلة العمل|job interview|interviews|A2","Gehalt|das|Gehälter|الراتب|salary|work|A2",
"Lohn|der|Löhne|الأجر|wage|work|A2","Chef|der|Chefs|المدير|boss|work|A1",
"Chefin|die|Chefinnen|المديرة|boss (f)|work|A1","Kollege|der|Kollegen|الزميل|colleague|work|A1",
"Kollegin|die|Kolleginnen|الزميلة|colleague (f)|work|A1","Büro|das|Büros|المكتب|office|workplace|A1",
"Fabrik|die|Fabriken|المصنع|factory|workplace|A2","Baustelle|die|Baustellen|موقع البناء|construction site|workplace|A2",
"Schicht|die|Schichten|الوردية|shift|work|A2","Überstunde|die|Überstunden|ساعة العمل الإضافية|overtime|work|A2",
"Urlaub|der|Urlaube|الإجازة|vacation|work|A1","Feiertag|der|Feiertage|يوم العطلة الرسمية|public holiday|time|A2",
"Vertrag|der|Verträge|العقد|contract|work|A2","Kündigung|die|Kündigungen|الاستقالة / الفصل|termination|work|A2",
"Ausbildung|die|Ausbildungen|التدريب المهني|vocational training|ausbildung|A2","Azubi|der|Azubis|المتدرب|trainee|ausbildung|A2",
"Praktikum|das|Praktika|التدريب العملي|internship|work|A2","Erfahrung|die|Erfahrungen|الخبرة|experience|work|A2",
"Reise|die|Reisen|الرحلة|trip|travel|A1","Urlaub2|der|Urlaube|العطلة|holiday|travel|A1",
"Flug|der|Flüge|الرحلة الجوية|flight|airport|A1","Flughafen|der|Flughäfen|المطار|airport|airport|A1",
"Flugzeug|das|Flugzeuge|الطائرة|airplane|airport|A1","Ticket|das|Tickets|التذكرة|ticket|travel|A1",
"Pass|der|Pässe|جواز السفر|passport|documents|A1","Visum|das|Visa|التأشيرة|visa|documents|A2",
"Koffer|der|Koffer|الحقيبة|suitcase|travel|A1","Rucksack|der|Rucksäcke|حقيبة الظهر|backpack|travel|A1",
"Bahnhof|der|Bahnhöfe|محطة القطار|train station|station|A1","Zug|der|Züge|القطار|train|transport|A1",
"Gleis|das|Gleise|الرصيف (في المحطة)|platform|station|A2","Fahrkarte|die|Fahrkarten|تذكرة السفر|fare ticket|transport|A1",
"Bus|der|Busse|الحافلة|bus|transport|A1","Haltestelle|die|Haltestellen|موقف الحافلات|bus stop|transport|A1",
"U-Bahn|die|U-Bahnen|مترو الأنفاق|subway|transport|A1","Straßenbahn|die|Straßenbahnen|الترام|tram|transport|A2",
"Taxi|das|Taxis|سيارة الأجرة|taxi|transport|A1","Fahrer|der|Fahrer|السائق|driver|jobs|A1",
"Auto|das|Autos|السيارة|car|transport|A1","Fahrrad|das|Fahrräder|الدراجة|bicycle|transport|A1",
"Straße|die|Straßen|الشارع|street|roads|A1","Ampel|die|Ampeln|إشارة المرور|traffic light|roads|A1",
"Kreuzung|die|Kreuzungen|التقاطع|crossing|roads|A2","Brücke|die|Brücken|الجسر|bridge|city|A2",
"Stadt|die|Städte|المدينة|city|city|A1","Dorf|das|Dörfer|القرية|village|city|A2",
"Zentrum|das|Zentren|المركز|center|city|A1","Platz|der|Plätze|الساحة|square|city|A1",
"Park|der|Parks|المنتزه|park|city|A1","Markt|der|Märkte|السوق|market|shopping|A1",
"Supermarkt|der|Supermärkte|السوبرماركت|supermarket|supermarket|A1","Geschäft|das|Geschäfte|المتجر|shop|shopping|A1",
"Kasse|die|Kassen|صندوق الدفع|cash register|supermarket|A1","Korb|der|Körbe|السلة|basket|supermarket|A1",
"Wagen|der|Wagen|العربة|cart|supermarket|A1","Preis|der|Preise|السعر|price|shopping|A1",
"Rabatt|der|Rabatte|الخصم|discount|shopping|A2","Quittung|die|Quittungen|الإيصال|receipt|shopping|A2",
"Kleidung|die|-|الملابس|clothes|clothing|A1","Hemd|das|Hemden|القميص|shirt|clothing|A1",
"Hose|die|Hosen|البنطال|pants|clothing|A1","Jacke|die|Jacken|السترة|jacket|clothing|A1",
"Mantel|der|Mäntel|المعطف|coat|clothing|A1","Schuh|der|Schuhe|الحذاء|shoe|clothing|A1",
"Stiefel|der|Stiefel|الحذاء الطويل|boot|clothing|A2","Socke|die|Socken|الجورب|sock|clothing|A1",
"Mütze|die|Mützen|القبعة الشتوية|cap|clothing|A1","Schal|der|Schals|الوشاح|scarf|clothing|A1",
"Handschuh|der|Handschuhe|القفاز|glove|clothing|A1","Kleid|das|Kleider|الفستان|dress|clothing|A1",
"Rock|der|Röcke|التنورة|skirt|clothing|A1","Anzug|der|Anzüge|البدلة|suit|clothing|A2",
"Krawatte|die|Krawatten|ربطة العنق|tie|clothing|A2","Brille|die|Brillen|النظارة|glasses|clothing|A1",
"Uhr|die|Uhren|الساعة|watch/clock|time|A1","Tasche|die|Taschen|الحقيبة اليدوية|bag|clothing|A1",
"Essen|das|-|الطعام|food|food|A1","Brot|das|Brote|الخبز|bread|food|A1",
"Brötchen|das|Brötchen|الخبز الصغير|bread roll|food|A1","Butter|die|-|الزبدة|butter|food|A1",
"Käse|der|-|الجبن|cheese|food|A1","Ei|das|Eier|البيضة|egg|food|A1",
"Milch|die|-|الحليب|milk|drinks|A1","Wasser|das|Wässer|الماء|water|drinks|A1",
"Saft|der|Säfte|العصير|juice|drinks|A1","Kaffee|der|Kaffees|القهوة|coffee|drinks|A1",
"Tee|der|Tees|الشاي|tea|drinks|A1","Zucker|der|-|السكر|sugar|food|A1",
"Salz|das|-|الملح|salt|food|A1","Reis|der|-|الأرز|rice|food|A1",
"Nudel|die|Nudeln|المعكرونة|pasta|food|A1","Kartoffel|die|Kartoffeln|البطاطا|potato|food|A1",
"Fleisch|das|-|اللحم|meat|food|A1","Hähnchen|das|Hähnchen|الدجاج|chicken|food|A1",
"Fisch|der|Fische|السمك|fish|food|A1","Gemüse|das|-|الخضار|vegetables|food|A1",
"Obst|das|-|الفاكهة|fruit|food|A1","Apfel|der|Äpfel|التفاحة|apple|food|A1",
"Banane|die|Bananen|الموز|banana|food|A1","Orange|die|Orangen|البرتقالة|orange|food|A1",
"Tomate|die|Tomaten|الطماطم|tomato|food|A1","Gurke|die|Gurken|الخيار|cucumber|food|A1",
"Salat|der|Salate|السلطة / الخس|salad|food|A1","Suppe|die|Suppen|الشوربة|soup|food|A1",
"Frühstück|das|-|الفطور|breakfast|food|A1","Mittagessen|das|-|الغداء|lunch|food|A1",
"Abendessen|das|-|العشاء|dinner|food|A1","Restaurant|das|Restaurants|المطعم|restaurant|restaurant|A1",
"Speisekarte|die|Speisekarten|قائمة الطعام|menu|restaurant|A1","Kellner|der|Kellner|النادل|waiter|restaurant|A1",
"Kellnerin|die|Kellnerinnen|النادلة|waitress|restaurant|A1","Trinkgeld|das|Trinkgelder|البقشيش|tip|restaurant|A2",
"Teller|der|Teller|الطبق|plate|restaurant|A1","Glas|das|Gläser|الكوب الزجاجي|cup/glass|restaurant|A1",
"Tasse|die|Tassen|الفنجان|cup|restaurant|A1","Messer|das|Messer|السكين|knife|restaurant|A1",
"Gabel|die|Gabeln|الشوكة|fork|restaurant|A1","Löffel|der|Löffel|الملعقة|spoon|restaurant|A1",
"Hotel|das|Hotels|الفندق|hotel|hotel|A1","Rezeption|die|Rezeptionen|الاستقبال|reception|hotel|A2",
"Reservierung|die|Reservierungen|الحجز|reservation|hotel|A2","Schlüsselkarte|die|Schlüsselkarten|بطاقة المفتاح|key card|hotel|A2",
"Gesundheit|die|-|الصحة|health|health|A1","Körper|der|Körper|الجسم|body|body|A1",
"Kopf|der|Köpfe|الرأس|head|body|A1","Gesicht|das|Gesichter|الوجه|face|body|A1",
"Auge|das|Augen|العين|eye|body|A1","Ohr|das|Ohren|الأذن|ear|body|A1",
"Nase|die|Nasen|الأنف|nose|body|A1","Mund|der|Münder|الفم|mouth|body|A1",
"Zahn|der|Zähne|السن|tooth|body|A1","Hals|der|Hälse|الرقبة / الحلق|neck/throat|body|A1",
"Schulter|die|Schultern|الكتف|shoulder|body|A1","Arm|der|Arme|الذراع|arm|body|A1",
"Hand|die|Hände|اليد|hand|body|A1","Finger|der|Finger|الإصبع|finger|body|A1",
"Bein|das|Beine|الساق|leg|body|A1","Fuß|der|Füße|القدم|foot|body|A1",
"Rücken|der|Rücken|الظهر|back|body|A1","Bauch|der|Bäuche|البطن|belly|body|A1",
"Herz|das|Herzen|القلب|heart|body|A1","Blut|das|-|الدم|blood|health|A1",
"Arzt|der|Ärzte|الطبيب|doctor|doctor|A1","Ärztin|die|Ärztinnen|الطبيبة|doctor (f)|doctor|A1",
"Krankenhaus|das|Krankenhäuser|المستشفى|hospital|hospital|A1","Apotheke|die|Apotheken|الصيدلية|pharmacy|pharmacy|A1",
"Medikament|das|Medikamente|الدواء|medicine|pharmacy|A2","Rezept|das|Rezepte|الوصفة الطبية|prescription|doctor|A2",
"Termin|der|Termine|الموعد|appointment|appointments|A1","Schmerz|der|Schmerzen|الألم|pain|health|A1",
"Fieber|das|-|الحمى|fever|health|A1","Husten|der|-|السعال|cough|health|A1",
"Schnupfen|der|-|الزكام|cold|health|A1","Kopfschmerz|der|Kopfschmerzen|صداع الرأس|headache|health|A1",
"Unfall|der|Unfälle|الحادث|accident|emergency|A2","Notfall|der|Notfälle|حالة الطوارئ|emergency|emergency|A2",
"Polizei|die|-|الشرطة|police|emergency|A1","Feuerwehr|die|Feuerwehren|الإطفاء|fire dept|emergency|A2",
"Krankenwagen|der|Krankenwagen|سيارة الإسعاف|ambulance|emergency|A2","Hilfe|die|-|المساعدة|help|emergency|A1",
"Wetter|das|-|الطقس|weather|weather|A1","Sonne|die|Sonnen|الشمس|sun|weather|A1",
"Regen|der|-|المطر|rain|weather|A1","Schnee|der|-|الثلج|snow|weather|A1",
"Wind|der|Winde|الرياح|wind|weather|A1","Wolke|die|Wolken|السحابة|cloud|weather|A1",
"Sturm|der|Stürme|العاصفة|storm|weather|A2","Nebel|der|-|الضباب|fog|weather|A2",
"Temperatur|die|Temperaturen|درجة الحرارة|temperature|weather|A1","Grad|das|Grade|الدرجة|degree|weather|A1",
"Frühling|der|-|الربيع|spring|seasons|A1","Sommer|der|-|الصيف|summer|seasons|A1",
"Herbst|der|-|الخريف|autumn|seasons|A1","Winter|der|-|الشتاء|winter|seasons|A1",
"Natur|die|-|الطبيعة|nature|nature|A1","Baum|der|Bäume|الشجرة|tree|nature|A1",
"Blume|die|Blumen|الزهرة|flower|nature|A1","Wald|der|Wälder|الغابة|forest|nature|A1",
"Fluss|der|Flüsse|النهر|river|nature|A1","See|der|Seen|البحيرة|lake|nature|A1",
"Meer|das|Meere|البحر|sea|nature|A1","Berg|der|Berge|الجبل|mountain|nature|A1",
"Tier|das|Tiere|الحيوان|animal|animals|A1","Hund|der|Hunde|الكلب|dog|animals|A1",
"Katze|die|Katzen|القطة|cat|animals|A1","Vogel|der|Vögel|الطائر|bird|animals|A1",
"Pferd|das|Pferde|الحصان|horse|animals|A1","Kuh|die|Kühe|البقرة|cow|animals|A1",
"Schaf|das|Schafe|الخروف|sheep|animals|A1","Maus|die|Mäuse|الفأرة|mouse|animals|A1",
"Fisch2|der|Fische|السمكة|fish|animals|A1","Biene|die|Bienen|النحلة|bee|animals|A2",
"Spinne|die|Spinnen|العنكبوت|spider|animals|A2","Schlange|die|Schlangen|الأفعى|snake|animals|A2",
"Computer|der|Computer|الحاسوب|computer|computers|A1","Laptop|der|Laptops|الحاسوب المحمول|laptop|computers|A1",
"Tastatur|die|Tastaturen|لوحة المفاتيح|keyboard|computers|A1","Maus2|die|Mäuse|فأرة الحاسوب|mouse (device)|computers|A1",
"Bildschirm|der|Bildschirme|الشاشة|screen|computers|A1","Drucker|der|Drucker|الطابعة|printer|computers|A2",
"Handy|das|Handys|الهاتف المحمول|mobile phone|phones|A1","Smartphone|das|Smartphones|الهاتف الذكي|smartphone|phones|A1",
"Anruf|der|Anrufe|المكالمة|call|phones|A1","Nachricht|die|Nachrichten|الرسالة|message|communication|A1",
"Internet|das|-|الإنترنت|internet|internet|A1","Webseite|die|Webseiten|صفحة الويب|website|internet|A1",
"Passwort|das|Passwörter|كلمة المرور|password|internet|A1","Konto|das|Konten|الحساب|account|banking|A1",
"Bank|die|Banken|البنك|bank|banking|A1","Geld|das|Gelder|المال|money|money|A1",
"Münze|die|Münzen|العملة المعدنية|coin|money|A1","Schein|der|Scheine|الورقة النقدية|banknote|money|A2",
"Kreditkarte|die|Kreditkarten|بطاقة الائتمان|credit card|banking|A2","Überweisung|die|Überweisungen|التحويل البنكي|transfer|banking|A2",
"Regierung|die|Regierungen|الحكومة|government|services|A2","Amt|das|Ämter|المكتب الحكومي|office|services|A2",
"Bürgeramt|das|Bürgerämter|مكتب المواطنين| citizens office|services|A2","Dokument|das|Dokumente|المستند|document|documents|A1",
"Formular|das|Formulare|الاستمارة|form|documents|A2","Antrag|der|Anträge|الطلب الرسمي|application (formal)|services|A2",
"Bescheinigung|die|Bescheinigungen|الشهادة الرسمية|certificate|documents|A2","Ausweis|der|Ausweise|بطاقة الهوية|ID card|documents|A1",
"Brief|der|Briefe|الرسالة|letter|communication|A1","Paket|das|Pakete|الطرد|parcel|communication|A1",
"Post|die|-|البريد|post|communication|A1","Gespräch|das|Gespräche|المحادثة|conversation|communication|A1",
"Treffen|das|Treffen|اللقاء|meeting|communication|A1","Einladung|die|Einladungen|الدعوة|invitation|communication|A2",
"Morgen|der|-|الصباح|morning|time|A1","Mittag|der|-|الظهر|noon|time|A1",
"Abend|der|Abende|المساء|evening|time|A1","Nacht|die|Nächte|الليل|night|time|A1",
"Woche|die|Wochen|الأسبوع|week|time|A1","Monat|der|Monate|الشهر|month|dates|A1",
"Jahr|das|Jahre|السنة|year|dates|A1","Tag|der|Tage|اليوم|day|time|A1",
"Stunde2|die|Stunden|الساعة الزمنية|hour|time|A1","Minute|die|Minuten|الدقيقة|minute|time|A1",
"Sekunde|die|Sekunden|الثانية|second|time|A2","Zeit|die|Zeiten|الوقت|time|time|A1",
"Kalender|der|Kalender|التقويم|calendar|dates|A1","Geburtstag|der|Geburtstage|عيد الميلاد|birthday|dates|A1",
"Montag|der|Montage|الاثنين|Monday|dates|A1","Dienstag|der|Dienstage|الثلاثاء|Tuesday|dates|A1",
"Mittwoch|der|Mittwoche|الأربعاء|Wednesday|dates|A1","Donnerstag|der|Donnerstage|الخميس|Thursday|dates|A1",
"Freitag|der|Freitage|الجمعة|Friday|dates|A1","Samstag|der|Samstage|السبت|Saturday|dates|A1",
"Sonntag|der|Sonntage|الأحد|Sunday|dates|A1","Januar|der|Januare|يناير|January|dates|A1",
"Februar|der|Februare|فبراير|February|dates|A1","März|der|Märze|مارس|March|dates|A1",
"April|der|Aprile|أبريل|April|dates|A1","Mai|der|Maie|مايو|May|dates|A1",
"Juni|der|Junis|يونيو|June|dates|A1","Juli|der|Julis|يوليو|July|dates|A1",
"August|der|Auguste|أغسطس|August|dates|A1","September|der|September|سبتمبر|September|dates|A1",
"Oktober|der|Oktober|أكتوبر|October|dates|A1","November|der|November|نوفمبر|November|dates|A1",
"Dezember|der|Dezember|ديسمبر|December|dates|A1","Zahl|die|Zahlen|الرقم|number|numbers|A1",
"Richtung|die|Richtungen|الاتجاه|direction|directions|A1","Weg|der|Wege|الطريق|way|directions|A1",
"Rechts|das|-|اليمين|right|directions|A1","Links|das|-|اليسار|left|directions|A1",
"Norden|der|-|الشمال|north|directions|A2","Süden|der|-|الجنوب|south|directions|A2",
"Osten|der|-|الشرق|east|directions|A2","Westen|der|-|الغرب|west|directions|A2",
"Ecke|die|Ecken|الزاوية|corner|directions|A1","Leben|das|-|الحياة|life|general|A1",
"Liebe|die|-|الحب|love|emotions|A1","Glück|das|-|السعادة|luck/happiness|emotions|A1",
"Angst|die|Ängste|الخوف|fear|emotions|A1","Freude|die|Freuden|الفرح|joy|emotions|A1",
"Wut|die|-|الغضب|anger|emotions|A2","Trauer|die|-|الحزن|sorrow|emotions|A2",
"Hoffnung|die|Hoffnungen|الأمل|hope|emotions|A2","Sorge|die|Sorgen|القلق|worry|emotions|A2",
"Beziehung|die|Beziehungen|العلاقة|relationship|relationships|A2","Ehe|die|Ehen|الزواج|marriage|relationships|A2",
"Hochzeit|die|Hochzeiten|حفل الزفاف|wedding|relationships|A2","Scheidung|die|Scheidungen|الطلاق|divorce|relationships|A2",
"Sport|der|-|الرياضة|sport|sports|A1","Fußball|der|Fußbälle|كرة القدم|football|sports|A1",
"Spiel|das|Spiele|اللعبة|game|sports|A1","Mannschaft|die|Mannschaften|الفريق|team|sports|A2",
"Sieg|der|Siege|الفوز|victory|sports|A2","Niederlage|die|Niederlagen|الهزيمة|defeat|sports|A2",
"Training|das|Trainings|التدريب|training|sports|A2","Wettkampf|der|Wettkämpfe|المنافسة|competition|sports|A2",
"Hobby|das|Hobbys|الهواية|hobby|hobbies|A1","Musik|die|-|الموسيقى|music|hobbies|A1",
"Film|der|Filme|الفيلم|film|hobbies|A1","Buch2|das|Bücher|الكتاب (للقراءة)|book|hobbies|A1",
"Foto|das|Fotos|الصورة|photo|hobbies|A1","Kamera|die|Kameras|الكاميرا|camera|hobbies|A2",
"Gitarre|die|Gitarren|القيثارة|guitar|hobbies|A2","Klavier|das|Klaviere|البيانو|piano|hobbies|A2",
"Deutschland|das|-|ألمانيا|Germany|germany|A1","Berlin|das|-|برلين|Berlin|germany|A1",
"Frankreich|das|-|فرنسا|France|germany|A2","Italien|das|-|إيطاليا|Italy|germany|A2",
"Spanien|das|-|إسبانيا|Spain|germany|A2","Türkei|die|-|تركيا|Turkey|germany|A2",
"Ägypten|das|-|مصر|Egypt|germany|A2","Syrien|das|-|سوريا|Syria|germany|A2",
"Sprache|die|Sprachen|اللغة|language|study|A1","Kurs|der|Kurse|الدورة|course|study|A1",
"Lehrerzimmer|das|Lehrerzimmer|غرفة المعلمين|staff room|school|A2","Pausenbrot|das|Pausenbrote|ساندويش الاستراحة|break snack|food|A2",
"Schulhof|der|Schulhöfe|ساحة المدرسة|schoolyard|school|A2","Klassensprecher|der|Klassensprecher|مندوب الصف|class rep|school|A2",
"Mode|die|Moden|الموضة|fashion|shopping|A2","Größe|die|Größen|المقاس|size|shopping|A1",
"Farbe|die|Farben|اللون|color|general|A1","Rot|das|-|الأحمر|red|general|A1",
"Blau|das|-|الأزرق|blue|general|A1","Grün|das|-|الأخضر|green|general|A1",
"Gelb|das|-|الأصفر|yellow|general|A1","Schwarz|das|-|الأسود|black|general|A1",
"Weiß|das|-|الأبيض|white|general|A1","Grau|das|-|الرمادي|grey|general|A1",
"Braun|das|-|البني|brown|general|A1","Rosa|das|-|الوردي|pink|general|A2",
"Plan|der|Pläne|الخطة|plan|general|A1","Idee|die|Ideen|الفكرة|idea|general|A1",
"Problem|das|Probleme|المشكلة|problem|general|A1","Lösung|die|Lösungen|الحل|solution|general|A1",
"Frage|die|Fragen|السؤال|question|general|A1","Antwort|die|Antworten|الجواب|answer|general|A1",
"Beispiel|das|Beispiele|المثال|example|study|A1","Regel|die|Regeln|القاعدة|rule|study|A1",
"Fehler|der|Fehler|الخطأ|mistake|study|A1","Erfolg|der|Erfolge|النجاح|success|general|A2",
"Ziel|das|Ziele|الهدف|goal|general|A1","Grund|der|Gründe|السبب|reason|general|A1",
"Folge|die|Folgen|النتيجة|consequence|general|A2","Unterschied|der|Unterschiede|الفرق|difference|general|A2",
"Vorteil|der|Vorteile|الميزة|advantage|general|A2","Nachteil|der|Nachteile|العيب|disadvantage|general|A2",
"Meinung|die|Meinungen|الرأي|opinion|general|A1","Entscheidung|die|Entscheidungen|القرار|decision|general|A2",
"Wahl|die|Wahlen|الاختيار / الانتخابات|choice/election|general|A2","Zukunft|die|-|المستقبل|future|general|A1",
"Vergangenheit|die|-|الماضي|past|general|A2","Gegenwart|die|-|الحاضر|present|general|A2",
"Welt|die|Welten|العالم|world|general|A1","Gesellschaft|die|Gesellschaften|المجتمع|society|general|A2",
"Kultur|die|Kulturen|الثقافة|culture|general|A2","Tradition|die|Traditionen|التقاليد|tradition|general|A2",
"Fest|das|Feste|الاحتفال|festival|general|A2","Weihnachten|das|-|عيد الميلاد (الكريسماس)|Christmas|general|A2",
"Ostern|das|-|عيد الفصح|Easter|general|A2","Neujahr|das|-|رأس السنة|New Year|dates|A2",
"Gebet|das|Gebete|الصلاة (دعاء عام)|prayer|dailylife|A2","Feier|die|Feiern|الحفلة|party|hobbies|A1",
"Donner|der|-|الرعد|thunder|weather|A2","Blitz|der|Blitze|البرق|lightning|weather|A2",
"Regenbogen|der|Regenbogen|قوس قزح|rainbow|nature|A2","Stern|der|Sterne|النجمة|star|nature|A1",
"Mond|der|Monde|القمر|moon|nature|A1","Himmel|der|-|السماء|sky|nature|A1",
"Erde|die|-|الأرض|earth|nature|A1","Luft|die|-|الهواء|air|nature|A1",
"Wasserfall|der|Wasserfälle|الشلال|waterfall|nature|A2","Insel|die|Inseln|الجزيرة|island|nature|A2",
"Strand|der|Strände|الشاطئ|beach|travel|A1","Hotelzimmer|das|Hotelzimmer|غرفة الفندق|hotel room|hotel|A1",
"Ausweis2|der|Ausweise|إثبات الهوية|ID|hotel|A2","Frühstücksbuffet|das|Frühstücksbuffets|بوفيه الفطور|breakfast buffet|hotel|A2"
];
/* Compound program: head -> {art, plural, mods[]} — gender/number inherited from head (German head rule).
   All pairs below are established real compounds. mod is a stem; de = Mod+head with linking-s handled explicitly. */
const COMPOUNDS=[
"Arzt|der|Ärzte|Haus,Zahn,Kinder,Frauen,Haut,Augen|doctor|A2",
"Termin|der|Termine|Arzt,Behörden,Bank,Impf,Besprechungs,Vorstellungs|health|A2",
"Karte|die|Karten|Bank,Kredit,Speise,Fahr,Telefon,Versicherungs|general|A1",
"Bahnhof|der|Bahnhöfe|Haupt,Flug,Bus,West,Ost|station|A1",
"Schein|der|Scheine|Führer,Überweisungs,Kranken,Geld|documents|A2",
"Schule|die|Schulen|Grund,Fahr,Sprach,Tanz,Musik,Berufs|school|A1",
"Kurs|der|Kurse|Sprach,Deutsch,Tanz,Koch,Computer|study|A1",
"Zimmer|das|Zimmer|Wohn,Schlaf,Kinder,Bade,Hotel,Arbeits|rooms|A1",
"Tür|die|Türen|Haus,Wohnungs,Zimmer,Auto,Schlafzimmer|home|A1",
"Schlüssel|der|Schlüssel|Haus,Wohnungs,Auto,Zimmer,Fahrzeug|home|A2",
"Zeugnis|das|Zeugnisse|Schul,Arbeits,Impf,Sprach|documents|A2",
"Vertrag|der|Verträge|Arbeits,Miet,Kauf,Handy,Versicherungs|work|A2",
"Brief|der|Briefe|Bewerbungs,Liebes,Amts,Kündigungs|communication|A2",
"Gespräch|das|Gespräche|Vorstellungs,Beratungs,Telefons,Arzt,Bewerbungs|worktalk|A2",
"Geld|das|Gelder|Taschen,Trink,Urlaubs,Fahr,Kranken|money|A1",
"Konto|das|Konten|Bank,Giro,Spar,Online|banking|A2",
"Wetter|das|-|Regen,Schnee,Sturm,Herbst,Urlaubs|weather|A1",
"Tag|der|Tage|Geburts,Feier,Urlaubs,Arbeits,Montag|time|A1",
"Essen|das|-|Mittag,Abend,Frühstücks,Fest,Hunde|food|A1",
"Wasser|das|Wässer|Trink,Mineral,Regen,Leitungs|drinks|A1",
"Milch|die|-|Kaffee,Mandel,Soja,Kondens|food|A2",
"Brot|das|Brote|Vollkorn,Weiß,Toast,Roggen|food|A1",
"Arbeit|die|Arbeiten|Haus,Teilzeit,Vollzeit,Team,Büro|work|A1",
"Platz|der|Plätze|Park,Spiel,Markt,Arbeits,Sitz|city|A1",
"Straße|die|Straßen|Haupt,Bahn,Einkaufs,Neben|roads|A1",
"Stadt|die|Städte|Alt,Innen,Klein,Heimat|city|A1",
"Park|der|Parks|Stadt,National,Tier,Freizeit|city|A2",
"Markt|der|Märkte|Wochen,Weihnachts,Floh,Supermarkt|shopping|A2",
"Laden|der|Läden|Bäcker,Fahrrad,Handy,Blumen|shopping|A2",
"Preis|der|Preise|Fest,Miet,Fahr,Tages|shopping|A2",
"Schuh|der|Schuhe|Sport,Haus,Turn,Winter,Lauf|clothing|A1",
"Hose|die|Hosen|Jeans,Sport,Arbeits,Regen|clothing|A1",
"Jacke|die|Jacken|Regen,Winter,Jeans,Leder|clothing|A1",
"Tasche|die|Taschen|Hand, Sport,Schul,Einkaufs|clothing|A1",
"Krankheit|die|Krankheiten|Kinder,Herz,Haut,Berufs|health|A2",
"Schmerz|der|Schmerzen|Kopf,Bauch,Zahn,Rücken,Hals|health|A1",
"Medikament|das|Medikamente|Schmerz,Husten,Fieber,Blutdruck|pharmacy|A2",
"Sport|der|-|Fußball,Winter,Wasser,Schul,Leistungs|sports|A1",
"Spiel|das|Spiele|Karten,Brett,Fußball,Handy,Glück|hobbies|A1",
"Film|der|Filme|Kino,Abenteuer,Liebes,Zeichentrick|hobbies|A1",
"Musik|die|-|Pop,Klassik,Rock,Hintergrund|hobbies|A1",
"Buch|das|Bücher|Schul,Koch,Wörter,Lehr,Kinder|school|A1",
"Zeitung|die|Zeitungen|Tages,Bild,Wand|general|A2",
"Bild|das|Bilder|Pass,Titel,Urlaubs,Profil|general|A2",
"Foto|das|Fotos|Pass,Urlaubs,Familien,Hochzeits|hobbies|A1",
"Handy|das|Handys|Dienst,Firmen,Kinder|phones|A1",
"Rechner|der|Rechner|Taschen,Büro|computers|A2",
"Programm|das|Programme|Computer,Fernseh,Wasch,Parteien|tech|A2",
"Seite|die|Seiten|Internet,Start,Startseiten|internet|A2",
"Kontakt|der|Kontakte|Notfall,Geschäfts,Augen|communication|A2",
"Nummer|die|Nummern|Telefon,Notfall,Konto,Haus|general|A1",
"Name2|der|Namen|Familien,Vor,Benutzer,Spitz|general|A1",
"Lehrer|der|Lehrer|Deutsch,Mathe,Sport,Englisch,Musik|school|A1",
"Fahrer|der|Fahrer|Bus,Taxi,Zug,Lkw|jobs|A1",
"Verkäufer|der|Verkäufer|Auto,Schuh,Handy|jobs|A2",
"Pfleger|der|Pfleger|Alten,Kranken,Tier|jobs|A2",
"Flug|der|Flüge|Rück,Hin,Inlands,Langstrecken|airport|A1",
"Gepäck|das|-|Hand,Reise,Über|travel|A2",
"Sitz|der|Sitze|Fenster,Gang,Kindersitz|travel|A2",
"Fahrplan|der|Fahrpläne|Bus,Bahn,Flug|transport|A2",
"Verspätung|die|Verspätungen|Zug,Flug,Bus|transport|A2",
"Haltestelle|die|Haltestellen|Bus,Bahn,End|transport|A1",
"Fahrschein|der|Fahrscheine|Tages,Wochen,Monats,Gruppen|transport|A2",
"Wohnung|die|Wohnungen|Miet,Eigentums,Ferien, WG|home|A1",
"Miete|die|Mieten|Kalt,Warm,Monats|home|A2",
"Nachbar|der|Nachbarn|Wohnungs,Haus,Zimmer|neighborhood|A1",
"Lärm|der|-|Bau,Verkehrs,Nachbarschafts|home|A2",
"Müll|der|-|Haus,Rest,Plastik,Sperr|home|A2",
"Strom|der|Ströme|Haus,Öko,Nacht|home|A2",
"Rechnung|die|Rechnungen|Strom,Telefon,Handy,Arzt|money|A2",
"Kindergarten|der|Kindergärten|Wald,Betriebs|school|A2",
"Spielplatz|der|Spielplätze|Abenteuer,Wasser|city|A2",
"Tierarzt|der|Tierärzte|Klein,Pferde|doctor|A2",
"Apotheke|die|Apotheken|Not,Online,Versand|pharmacy|A2",
"Krankenkasse|die|Krankenkassen|Pflicht,Privat|health|A2",
"Überweisung|die|Überweisungen|Bank,Arzt|banking|A2",
"Bewerbung|die|Bewerbungen|Job,Stellen,Initiativ|applications|A2",
"Gespräch2|das|Gespräche|Kunden,Mitarbeiter,Feedback|worktalk|A2",
"Kollege|der|Kollegen|Arbeits,Zimmer,Büro|work|A1",
"Pause|die|Pausen|Mittags,Kaffee,Rauch|work|A1",
"Urlaub|der|Urlaube|Sommer,Jahres,Bildungs,Eltern|work|A1",
"Feiertag|der|Feiertage|Weihnachts,Oster,Brücken|time|A2",
"Wochenende|das|Wochenenden|Verlängertes|time|A1",
"Alltag|der|-|Arbeits,Büro,Familien|routine|A2",
"Morgenroutine|die|Morgenroutinen|-|routine|A2",
"Abendessen2|das|-|Familien,Weihnachts|food|A1",
"Rezept2|das|Rezepte|Koch,Back,Arzt|food|A1",
"Gericht|das|Gerichte|Lieblings,Tages,Fisch,Fleisch|restaurant|A1",
"Getränk|das|Getränke|Heiß,Kalt,Erfrischungs|drinks|A1",
"Bestellung|die|Bestellungen|Online,Tisch|restaurant|A2",
"Service|der|Services|Kunden,Zimmer,Not|services|A2",
"Dienst|der|Dienste|Not,Kunden,Paket|services|A2",
"Anfrage|die|Anfragen|Kunden,Preis,Presse|communication|A2",
"Antwort2|die|Antworten|Standard,E-Mail|communication|A1",
"Baumarkt|der|Baumärkte|-|shopping|A2",
"Möbelhaus|das|Möbelhäuser|-|shopping|A2",
"Schlafzimmer2|das|Schlafzimmer|Gäste,Kinder|rooms|A1",
"Badezimmer2|das|Badezimmer|Gäste|rooms|A1",
"Kühlschrank2|der|Kühlschränke|Mini|rooms|A1",
"Waschmaschine2|die|Waschmaschinen|Münz|home|A2",
"Fernseher|der|Fernseher|Röhren,Flachbild|home|A1",
"Fernbedienung|die|Fernbedienungen|-|home|A2",
"Steckdose|die|Steckdosen|-|home|A2",
"Glühbirne|die|Glühbirnen|LED,Energiespar|home|A2",
"Regenschirm|der|Regenschirme|Taschen,Kinder|weather|A1",
"Sonnenbrille|die|Sonnenbrillen|-|weather|A1",
"Wintermantel|der|Wintermäntel|-|clothing|A1",
"Sommerschlussverkauf|der|-|-|shopping|A2",
"Gutschein|der|Gutscheine|Geschenk,Rabatt,Buch|shopping|A2",
"Umtausch|der|-|-|shopping|A2",
"Anprobe|die|Anproben|-|shopping|A2",
"Umkleidekabine|die|Umkleidekabinen|-|shopping|A2",
"Warteschlange|die|Warteschlangen|-|services|A2",
"Wartenummer|die|Wartenummern|-|services|A2",
"Formular2|das|Formulare|Anmelde,Antrags|documents|A2",
"Wartezimmer|das|Wartezimmer|Arzt|doctor|A2",
"Sprechstunde|die|Sprechstunden|Arzt,Notfall|doctor|A2",
"Krankmeldung|die|Krankmeldungen|-|work|A2",
"Attest|das|Atteste|Arzt|doctor|A2",
"Impfpass|der|Impfpässe|-|documents|A2",
"Führerschein|der|Führerscheine|Auto,Motorrad|documents|A2",
"Kennzeichen|das|Kennzeichen|Auto,Wunsch|documents|A2",
"TÜV|der|-|-|services|A2",
"Werkstatt|die|Werkstätten|Auto,Fahrrad|services|A2",
"Panne|die|Pannen|Auto,Reifen|transport|A2",
"Tankstelle|die|Tankstellen|-|transport|A1",
"Benzin|das|-|Super|transport|A1",
"Diesel|der|-|-|transport|A2",
"Kilometer|der|Kilometer|-|transport|A1",
"Stau|der|Staus|Verkehrs,Feierabend|roads|A2",
"Umleitung|die|Umleitungen|-|roads|A2",
"Fußgängerzone|die|Fußgängerzonen|-|city|A2",
"Ampel2|die|Ampeln|Fußgänger|roads|A1",
"Parkplatz|der|Parkplätze|Kunden,Behinderten,Besucher|city|A1",
"Parkschein|der|Parkscheine|-|city|A2",
"Strafzettel|der|Strafzettel|Park|services|A2",
"Rathaus|das|Rathäuser|-|city|A2",
"Bürgermeister|der|Bürgermeister|-|services|A2",
"Anmeldung|die|Anmeldungen|Wohnungs,Auto,Schul|services|A2",
"Abmeldung|die|Abmeldungen|-|services|A2",
"Steuer|die|Steuern|Einkommens,Mehrwert|money|A2",
"Steuererklärung|die|Steuererklärungen|-|money|A2",
"Versicherung|die|Versicherungen|Kranken,Haftpflicht,Hausrat,Auto|services|A2",
"Beitrag|der|Beiträge|Mitglieds,Krankenkassen|money|A2",
"Rente|die|Renten|Alters|money|A2",
"Arbeitslosengeld|das|-|-|money|A2",
"Kindergeld|das|-|-|money|A2",
"Elterngeld|das|-|-|money|A2",
"Wohngeld|das|-|-|money|A2",
"BAföG|das|-|-|money|A2",
"Stipendium2|das|Stipendien|Deutschland,Studien|university|A2",
"Prüfungsamt|das|Prüfungsämter|-|university|A2",
"Studentenwohnheim|das|Studentenwohnheime|-|unilife|A2",
"Mensaessen|das|Mensaessen|-|unilife|A2",
"Bibliotheksausweis|der|Bibliotheksausweise|-|university|A2",
"Hausarbeit|die|Hausarbeiten|-|university|A2",
"Abschlussarbeit|die|Abschlussarbeiten|Bachelor,Master|university|A2",
"Vorlesungszeit|die|-|-|university|A2",
"Semesterferien|die|-|-|university|A2",
"Deutschkurs|der|Deutschkurse|Intensiv,Abend,Online|study|A1",
"Integrationskurs|der|Integrationskurse|-|study|A2",
"Sprachschule|die|Sprachschulen|-|study|A1",
"Sprachprüfung|die|Sprachprüfungen|Telc,Goethe|study|A2",
"Zertifikat|das|Zertifikate|Sprach,Teilnahme|study|A2",
"Vokabelheft|das|Vokabelhefte|-|study|A1",
"Wörterbuch|das|Wörterbücher|Bild,Online|study|A1",
"Grammatikbuch|das|Grammatikbücher|-|study|A1",
"Übungsbuch|das|Übungsbücher|-|study|A1",
"Lernpartner|der|Lernpartner|Tandem|study|A2",
"Nachhilfe|die|-|Mathe,Deutsch|education|A2",
"Schulwechsel|der|-|-|education|A2",
"Klassenarbeit|die|Klassenarbeiten|Mathe,Deutsch|school|A1",
"Matura2|die|-|-|education|A2",
"Stundenplan|der|Stundenpläne|-|school|A1",
"Klassenraum|der|Klassenräume|-|school|A1",
"Schulbus|der|Schulbusse|-|school|A1",
"Schulranzen|der|Schulranzen|-|school|A1",
"Federmäppchen|das|Federmäppchen|-|school|A1",
"Tafelschwamm|der|Tafelschwämme|-|school|A2",
"Kreidestück|das|Kreidestücke|-|school|A2"
];
if(typeof module!=="undefined")module.exports={NOUNS,COMPOUNDS};
