/* Sentence patterns: [deTpl, arTpl, lvl, topic, gram] slots: {S}{V1|V2|V3 present forms auto} {O} {T} {P} {A}
   Builder fills {O} noun-phrase pool, {T} time pool, {P} place pool, {A} adj pool, {V*} verb pool by valency.
   STEMS: present stem-change for irregular verbs (du/er forms); regulars conjugated by rule. */
"use strict";
const STEMS={"sprechen":["sprichst","spricht"],"sehen":["siehst","sieht"],"lesen":["liest","liest"],"geben":["gibst","gibt"],"nehmen":["nimmst","nimmt"],"fahren":["fährst","fährt"],"laufen":["läufst","läuft"],"schlafen":["schläfst","schläft"],"tragen":["trägst","trägt"],"treffen":["triffst","trifft"],"helfen":["hilfst","hilft"],"essen":["isst","isst"],"vergessen":["vergisst","vergisst"],"waschen":["wäschst","wäscht"],"fallen":["fällst","fällt"],"halten":["hältst","hält"],"fangen":["fängst","fängt"],"stoßen":["stößt","stößt"],"sein":["bist","ist"],"haben":["hast","hat"],"werden":["wirst","wird"],"wissen":["weißt","weiß"],"können":["kannst","kann"],"müssen":["musst","muss"],"dürfen":["darfst","darf"],"sollen":["sollst","soll"],"wollen":["willst","will"],"möchten":["möchtest","möchte"],"fahren2":["fährst","fährt"],"backen":["bäckst","bäckt"],"braten":["brätst","brät"],"schneiden":["schneidest","schneidet"],"scheinen":["scheinst","scheint"],"wachsen":["wächst","wächst"],"rufen":["rufst","ruft"],"lügen":["lügst","lügt"],"gestehen":["gestehst","gesteht"],"schwimmen":["schwimmst","schwimmt"],"singen":["singst","singt"],"beginnen":["beginnst","beginnt"],"gewinnen":["gewinnst","gewinnt"],"verlieren":["verlierst","verliert"],"empfehlen":["empfiehlst","empfiehlt"],"empfangen":["empfängst","empfängt"],"stehlen":["stiehlt","stiehlt"],"schließen":["schließt","schließt"],"schreien":["schreist","schreit"],"fliehen":["fliehst","flieht"],"fliegen":["fliegst","fliegt"],"ziehen":["ziehst","zieht"],"leihe":["leihst","leiht"],"leihen":["leihst","leiht"],"bieten":["bietest","bietet"],"anbieten":["bietest an","bietet an"],"raten":["rätst","rät"],"braten2":["brätst","brät"],"blasen":["bläst","bläst"],"graben":["gräbst","gräbt"],"laden":["lädst","lädt"],"einladen":["lädst ein","lädt ein"],"raten2":["rätst","rät"],"halten2":["hältst","hält"],"schlafen2":["schläfst","schläft"]};
const SUBJ=[
["Ich","أنا","ich","A1"],["Du","أنت","du","A1"],["Er","هو","er","A1"],["Sie","هي","sie","A1"],
["Wir","نحن","wir","A1"],["Ihr","أنتم","ihr","A1"],["Sie","حضرتك","Sie","A1"],["Mein Bruder","أخي","er","A1"],
["Meine Schwester","أختي","sie","A1"],["Mein Freund","صديقي","er","A1"],["Meine Freundin","صديقتي","sie","A1"],
["Der Lehrer","المعلم","er","A1"],["Die Ärztin","الطبيبة","sie","A2"],["Der Kollege","الزميل","er","A2"],
["Die Nachbarin","الجارة","sie","A2"],["Das Kind","الطفل","es","A1"],["Die Kinder","الأطفال","siepl","A1"],
["Mein Vater","والدي","er","A1"],["Meine Mutter","والدتي","sie","A1"],["Der Chef","المدير","er","A2"],
["Die Chefin","المديرة","sie","A2"],["Der Kellner","النادل","er","A2"],["Niemand","لا أحد","er","A2"],
["Jeder","كل واحد","er","A2"],["Viele Leute","كثير من الناس","siepl","A2"],["Meine Eltern","والداي","siepl","A1"]
];
const TIMES=[
["heute","اليوم","A1"],["morgen","غدًا","A1"],["gestern","أمس","A1"],["jetzt","الآن","A1"],
["bald","قريبًا","A1"],["später","لاحقًا","A1"],["am Montag","يوم الاثنين","A1"],["am Wochenende","في عطلة الأسبوع","A1"],
["jeden Tag","كل يوم","A1"],["jede Woche","كل أسبوع","A2"],["oft","غالبًا","A1"],["manchmal","أحيانًا","A1"],
["nie","أبدًا","A1"],["immer","دائمًا","A1"],["schon lange","منذ زمن","A2"],["seit einem Jahr","منذ سنة","A2"],
["nächste Woche","الأسبوع القادم","A2"],["letzte Woche","الأسبوع الماضي","A2"],["im Sommer","في الصيف","A1"],["im Winter","في الشتاء","A1"],
["morgens","صباحًا","A1"],["abends","مساءً","A1"],["pünktlich","في الموعد","A2"],["sofort","فورًا","A2"]
];
const PLACES=[
["zu Hause","في البيت","home","A1"],["in der Schule","في المدرسة","school","A1"],["in der Stadt","في المدينة","city","A1"],
["auf dem Markt","في السوق","shopping","A1"],["im Supermarkt","في السوبرماركت","supermarket","A1"],["im Büro","في المكتب","work","A1"],
["im Restaurant","في المطعم","restaurant","A1"],["im Hotel","في الفندق","hotel","A1"],["am Bahnhof","في المحطة","station","A1"],
["im Krankenhaus","في المستشفى","hospital","A2"],["in der Apotheke","في الصيدلية","pharmacy","A2"],["im Park","في المنتزه","city","A1"],
["bei meinen Eltern","عند والديّ","family","A2"],["in Berlin","في برلين","germany","A1"],["in Deutschland","في ألمانيا","germany","A1"],
["im Zug","في القطار","transport","A2"],["an der Haltestelle","عند الموقف","transport","A2"],["in der Bibliothek","في المكتبة","university","A2"],["im Kurs","في الدورة","study","A1"]
];
/* valency pools reference verb ids by group */
const VG_TRAN=[
[["kaufen","يشتري"],["bestellen","يطلب"],["brauchen","يحتاج"],["suchen","يبحث عن"],["finden","يجد"],["bekommen","يحصل على"],["mitbringen","يحضر"],["vergessen","ينسى"],["verlieren","يفقد"],["empfehlen","يوصي"]],
[["kochen","يطبخ"],["putzen","ينظف"],["reparieren","يصلح"],["öffnen","يفتح"],["schließen","يغلق"],["bezahlen","يدفع"],["reservieren","يحجز"],["waschen","يغسل"],["bügeln","يكوي"],["fotografieren","يصور"]]];
const VG_INTRAN=[
[["arbeiten","يعمل"],["lernen","يتعلم"],["schlafen","ينام"],["warten","ينتظر"],["reisen","يسافر"],["spielen","يلعب"],["tanzen","يرقص"],["lachen","يضحك"],["weinen","يبكي"],["bleiben","يبقى"]],
[["joggen","يهرول"],["schwimmen","يسبح"],["wandern","يتنزه"],["trainieren","يتدرب"],["entspannen","يسترخي (sich)"],["feiern","يحتفل"],["telefonieren","يتهاتف"],["diskutieren","يناقش"],["funktionieren","يعمل"],["passieren","يحدث"]]];
const VG_DITRAN=[[["geben","يعطي"],["schenken","يهدي"],["zeigen","يُري"],["bringen","يحضر"],["schicken","يرسل"],["erklären","يشرح"],["leihen","يُعير"],["verkaufen","يبيع"]]];
const VG_MODAL=[[["lernen","يتعلم"],["arbeiten","يعمل"],["kommen","يأتي"],["helfen","يساعد"],["bleiben","يبقى"],["schlafen","ينام"],["einkaufen","يتسوق"],["aufräumen","يرتب"]]];
const PATS=[
["{S} {V} {O} {T}.","{Sa} {Va} {Oa} {Ta}.","A1","general","praesens"],
["{S} {V} {T} {P}.","{Sa} {Va} {Ta} {Pa}.","A1","dailylife","praesens"],
["{T} {V} {Sl} {O}.","{Ta} {Va} {Sa} {Oa}.","A1","general","inversion"],
["{S} {Vm} {Vi} {O}.","{Sa} {Vma} أن {Via} {Oa}.","A1","general","modal"],
["{S} {V} {O} nicht.","{Sa} لا {Va} {Oa}.","A1","general","negation"],
["{S} {V} kein {On}.","{Sa} لا {Va} أي {Ona}.","A1","general","kein"],
["{Vq} {Sl} {O}?","هل {Va} {Sa} {Oa}؟","A1","general","ja-nein-frage"],
["{W} {V} {S} {T}?","{Wa} {Va} {Sa} {Ta}؟","A1","general","w-frage"],
["{S} {V} {O}, weil {S2} {V2}.","{Sa} {Va} {Oa} لأن {S2a} {V2a}.","A2","general","weil"],
["{S} {V} {O}, dass {S2} {V2}.","{Sa} {Va} {Oa} أنّ {S2a} {V2a}.","A2","general","dass"],
["Wenn {S} {V}, {V} {S} {O}.","إذا {Va} {Sa} {Va2} {Sa} {Oa}.","A2","general","wenn"],
["{S} {V} {O1} {O2d}.","{Sa} {Va} {O1a} لـ{O2da}.","A2","general","dativ"],
["{S} {Vs} {O} {T}.","{Sa} {Vsa} {Oa} {Ta}.","A1","routine","trennbar"],
["{S} ist {A}.","{Sa} {Aa}.","A1","emotions","sein-adj"],
["{S} hat {O}.","لدى {Sa} {Oa}.","A1","general","haben"],
["{S} {V} gern {O}.","{Sa} {Va} {Oa} بسرور.","A1","general","gern"],
["{S} {V} lieber {P}.","{Sa} يفضل أن {Va} {Pa}.","A2","general","komparativ-adv"],
["{S} {V} am liebsten {T}.","{Sa} يفضل {Va} {Ta}.","A2","general","superlativ-adv"],
["{O1} ist {Ac} als {O2}.","{O1a} {Aca} من {O2a}.","A1","general","komparativ"],
["{O1} ist am {As}.","{O1a} هو {Asa}.","A2","general","superlativ"],
["{S} {Vperf}.","{Sa} {Vperfa}.","A1","general","perfekt"],
["{T} hat {S} {Vperf}.","{Ta} {Va-past} {Sa}.","A2","general","perfekt-inversion"],
["Bitte {Vi} {O}!","من فضلك {Via} {Oa}!","A1","polite","imperativ"],
["{Vi} {S} {P}!","{Via} {Sa} {Pa}!","A1","directions","imperativ-pl"],
["{S} möchte {O}.","{Sa} يود {Oa}.","A1","general","konjunktiv-hoeflich"],
["Könnten {S} mir helfen?","هل يمكنك مساعدتي؟","A1","polite","konjunktiv-bitte"],
["{S} muss {Vi}.","يجب على {Sa} أن {Via}.","A1","general","modal-muessen"],
["{S} kann {Vi} {T}.","يستطيع {Sa} أن {Via} {Ta}.","A1","general","modal-koennen"],
["{S} will {Vi} {P}.","يريد {Sa} أن {Via} {Pa}.","A1","general","modal-wollen"],
["{S} soll {Vi}.","ينبغي على {Sa} أن {Via}.","A2","general","modal-sollen"],
["{S} darf hier nicht {Vi}.","لا يجوز لـ{Sa} أن {Via} هنا.","A2","general","modal-duerfen"],
["{S} {V} {O} für {P2}.","{Sa} {Va} {Oa} لـ{Pa2}.","A2","shopping","praeposition-fuer"],
["{S} {V} mit {O3}.","{Sa} {Va} مع {O3a}.","A1","relationships","praeposition-mit"],
["{S} wartet auf {O4}.","{Sa} ينتظر {O4a}.","A1","general","verb-praep-auf"],
["{S} denkt an {O4}.","{Sa} يفكر في {O4a}.","A2","general","verb-praep-an"],
["{S} fragt nach {O5}.","{Sa} يسأل عن {O5a}.","A2","communication","verb-praep-nach"],
["{S} spricht mit {O6} über {O7}.","{Sa} يتحدث مع {O6a} عن {O7a}.","A2","communication","sprechen-ueber"],
["{S} {V} {O} {P} {T}.","{Sa} {Va} {Oa} {Pa} {Ta}.","A1","dailylife","te-ka-mo-lo"],
["{S} {V} {T} wegen {Og}.","{Sa} {Va} {Ta} بسبب {Oga}.","A2","general","genitiv-praep"],
["Trotz {Og} {V} {S}.","رغم {Oga} {Va} {Sa}.","A2","general","trotz"],
["Während {Og} {V} {S} {O}.","خلال {Oga} {Va} {Sa} {Oa}.","A2","time","waehrend"],
["{S} {V} {O}, obwohl {S2} müde ist.","{Sa} {Va} {Oa} رغم أن {S2a} متعب.","A2","general","obwohl"],
["Bevor {S} {V}, {V} {S} {O}.","قبل أن {Va} {Sa} {Va2} {Sa} {Oa}.","A2","routine","bevor"],
["Nachdem {S} {Vperf-a}, {V} {S} {O}.","بعد أن {Va-past} {Sa} {Va2} {Sa} {Oa}.","A2","general","nachdem"],
["Um {Vi2} {Vi}, {V} {S} {T}.","لكي {Via2} {Va2} {Sa} {Ta}.","A2","general","um-zu"],
["{S} {V} {O}, statt {Vi2}.","{Sa} {Va} {Oa} بدل أن {Via2}.","A2","general","statt-zu"],
["Ohne {Vi2} {V} {S} {O}.","بدون أن {Va2} {Va} {Sa} {Oa}.","A2","general","ohne-zu"],
["{S} lässt {O} {Vi2}.","{Sa} يدع {Oa} {Va2}.","A2","general","lassen"],
["{S} hilft {O6} beim {N}.","{Sa} يساعد {O6a} في {Na}.","A2","worktalk","helfen-bei"],
["Es gibt {O} {P}.","يوجد {Oa} {Pa}.","A1","general","es-gibt"],
["Es ist {A} {T}.","الجو {Aa} {Ta}.","A1","weather","wetter-es"],
["Es regnet {T}.","إنها تمطر {Ta}.","A1","weather","wetter-verb"],
["Wie ist {O}?","كيف {Oa}؟","A1","general","w-frage-wie"],
["Wo ist {O}?","أين {Oa}؟","A1","directions","w-frage-wo"],
["Wann {V} {S}?","متى {Va} {Sa}؟","A1","time","w-frage-wann"],
["Warum {V} {S} {O}?","لماذا {Va} {Sa} {Oa}؟","A2","general","w-frage-warum"],
["{S} freut sich über {O4}.","{Sa} سعيد بـ{O4a}.","A2","emotions","reflexiv-freuen"],
["{S} interessiert sich für {O4}.","{Sa} مهتم بـ{O4a}.","A2","hobbies","reflexiv-interesse"],
["{S} beeilt sich, weil {S2} spät dran ist.","{Sa} مستعجل لأن {S2a} متأخر.","A2","routine","reflexiv-beeilen"],
["{S} hat sich über {O4} geärgert.","{Sa} انزعج من {O4a}.","A2","emotions","reflexiv-aergern"],
["{S} wird {A}.","{Sa} سيصبح {Aa}.","A2","general","werden"],
["{S} wird {T} {Vi}.","{Sa} سوف {Via} {Ta}.","A2","general","futur"],
["{S} war {A}.","كان {Sa} {Aa}.","A1","general","praeteritum-sein"],
["{S} hatte {O} {T}.","كان لدى {Sa} {Oa} {Ta}.","A2","general","praeteritum-haben"],
["{S} ging {P} {T}.","ذهب {Sa} {Pa} {Ta}.","A2","travel","praeteritum-gehen"],
["{S} findet {O} {A}.","{Sa} يجد {Oa} {Aa}.","A2","general","finden-adj"],
["{S} nennt {O1} {O8}.","{Sa} يسمي {O1a} {O8a}.","A2","general","akk-doppelt"],
["Man {V} hier nicht {Vi-n}.","لا {Va} هنا.","A2","general","man-passiv-sinn"],
["{O} wird {Vpp}.","{Oa} {Vppa}.","A2","general","passiv"],
["{O} kann {Vpp} werden.","يمكن {Va-pass} {Oa}.","A2","general","passiv-modal"],
["{S} lässt sich nicht {Vi-n}.","{Oa} لا يمكن {Va-pass}.","A2","general","lassen-passiv-sinn"],
["Je mehr {S} {V}, desto {Ac} wird es.","كلما {Va} {Sa} أكثر صار {Aca}.","A2","general","je-desto"],
 ["Entweder {Sl} {V} oder {S2} {V2}.","إما أن {Va} {Sa} أو {V2a} {S2a}.","A2","general","entweder-oder"],
["Sowohl {O1} als auch {O2} sind {A}.","كل من {O1a} و{O2a} {Aa}.","A2","general","sowohl-als-auch"],
 ["Nicht nur {Sl}, sondern auch {S2} {V}.","ليس {Sa} فقط بل {S2a} أيضًا {V2a}.","A2","general","nicht-nur-sondern"],
["{S} {V} zwar {O}, aber {S2} {V2} nicht.","{Sa} {Va} {Oa} صحيح لكن {S2a} لا {V2a}.","A2","general","zwar-aber"],
["{S} {V} {O} für seine Familie.","{Sa} {Va} {Oa} لعائلته.","A2","family","possessiv-sein"],
["{O1} und {O2} sind {A}.","{O1a} و{O2a} {Aa}.","A1","general","und-koordination"],
["{S} {V} {O} und danach {V3} {S} {P}.","{Sa} {Va} {Oa} وبعدها {Va3} {Sa} {Pa}.","A2","routine","reihung"],
 ["{T}, {Sl} {V} {O} {P}.","{Ta} {Va} {Sa} {Oa} {Pa}.","A1","travel","adverb-voran"],
["{P}, {V} {Sl} {O}.","{Pa} {Va} {Sa} {Oa}.","A1","directions","lokal-voran"],
["Zu Hause {V} {Sl} {O}.","في البيت {Va} {Sa} {Oa}.","A1","home","lokal-voran-2"],
["Leider {V} {S} {T} nicht {Vi-n}.","للأسف لا {Va} {Sa} {Ta}.","A2","general","modal-partikel"],
["{S} {V} doch {O}!","{Sa} {Va} {Oa} حقًا!","A2","emotions","partikel-doch"],
["{S} {V} mal {O}!","{Va} {Sa} {Oa} قليلًا!","A2","colloquial","partikel-mal"],
["Was für {O9} {V} {S}?","أي {O9a} {Va} {Sa}؟","A2","general","was-fuer"],
["Welchen {O9} {V} {S}?","أي {O9a} {Va} {Sa}؟","A2","shopping","welch-akk"],
["{S} {V} {O} seit {Tg}.","{Sa} {Va} {Oa} منذ {Tga}.","A2","general","seit-dauer"],
["{S} bleibt bis {Tg}.","{Sa} يبقى حتى {Tga}.","A1","travel","bis-zeit"],
["Von {P} bis {P2} dauert es eine Stunde.","من {Pa} إلى {Pa2} يستغرق ساعة.","A2","travel","von-bis"],
["{S} kommt aus {P2} und wohnt jetzt {P}.","{Sa} قادم من {Pa2} ويسكن الآن {Pa}.","A1","germany","herkunft-wohnen"],
["{S} spricht {A} Deutsch.","{Sa} يتحدث الألمانية {Aa}.","A1","study","adverb-art"],
["{S} lernt seit {Tg} Deutsch.","{Sa} يتعلم الألمانية منذ {Tga}.","A1","study","seit-lernen"],
["Deutschlernen macht {S3} Spaß.","تعلم الألمانية يمتع {S3a}.","A2","study","subjekt-satz"],
["{S} hat Lust auf {O4}.","لدى {Sa} رغبة في {O4a}.","A2","general","lust-auf"],
["{S} hat Angst vor {O5}.","{Sa} خائف من {O5a}.","A2","emotions","angst-vor"],
["{S} ist stolz auf {O4}.","{Sa} فخور بـ{O4a}.","A2","emotions","stolz-auf"],
["{S} ist zufrieden mit {O5}.","{Sa} راضٍ عن {O5a}.","A2","general","zufrieden-mit"],
["{S} beginnt mit {O5} {T}.","{Sa} يبدأ بـ{O5a} {Ta}.","A2","routine","beginnen-mit"],
["{S} hört mit {O5} auf.","{Sa} يتوقف عن {O5a}.","A2","general","aufhoeren-mit"],
["{S} wartet seit {Tg} auf {O4}.","{Sa} ينتظر {O4a} منذ {Tga}.","A2","general","warten-auf-seit"],
["{S} kümmert sich um {O4}.","{Sa} يعتني بـ{O4a}.","A2","health","kuemmern-um"],
["{S} bewirbt sich um {O4}.","{Sa} يتقدم لـ{O4a}.","A2","applications","bewerben-um"],
["{S} beschwert sich über {O4}.","{Sa} يشتكي من {O4a}.","A2","services","beschweren-ueber"],
["{S} informiert sich über {O4}.","{Sa} يستعلم عن {O4a}.","A2","services","informieren-ueber"],
["{S} freut sich auf {O4}.","{Sa} متشوق لـ{O4a}.","A2","emotions","freuen-auf"],
["{S} dankt {O6} für {O4}.","{Sa} يشكر {O6a} على {O4a}.","A2","polite","danken-fuer"],
["{S} gratuliert {O6} zum {N2}.","{Sa} يهنئ {O6a} بـ{Na2}.","A2","polite","gratulieren-zu"],
["{S} hilft {O6} bei {O5}.","{Sa} يساعد {O6a} في {O5a}.","A2","worktalk","helfen-dativ"],
["{S} gehört {O6}.","{Oa} يخص {O6a}.","A2","general","gehoeren"],
["{S} schmeckt {O6}.","{Oa} يعجب {O6a} طعمه.","A2","food","schmecken-dativ"],
["{S} gefällt {O6}.","{Oa} يعجب {O6a}.","A2","general","gefallen-dativ"],
["{S} passt {O6} gut.","{Oa} يناسب {O6a} جيدًا.","A2","clothing","passen-dativ"],
["{S} weh {O6} {O10}.","{O10a} يؤلم {O6a}.","A2","health","wehtun"],
["{S} trifft {O6} {T} {P}.","{Sa} يقابل {O6a} {Ta} {Pa}.","A1","relationships","treffen-akk"],
["{S} besucht {O6} {T}.","{Sa} يزور {O6a} {Ta}.","A1","family","besuchen"],
["{S} ruft {O6} {T} an.","{Sa} يتصل بـ{O6a} {Ta}.","A1","phones","anrufen"],
["{S} holt {O6} vom {P3} ab.","{Sa} يستقبل {O6a} من {Pa3}.","A2","travel","abholen"],
["{S} bringt {O6} zum {P3}.","{Sa} يوصل {O6a} إلى {Pa3}.","A2","dailylife","bringen-zu"],
["{S} begleitet {O6} zum {P3}.","{Sa} يرافق {O6a} إلى {Pa3}.","A2","relationships","begleiten"],
["{S} stellt {O6} {O5} vor.","{Sa} يقدم {O6a} لـ{O5a}.","A2","worktalk","vorstellen"],
["{S} erklärt {O6} {O4}.","{Sa} يشرح لـ{O6a} {O4a}.","A2","study","erklaeren"],
["{S} zeigt {O6} {O}.","{Sa} يُري {O6a} {Oa}.","A1","general","zeigen"],
["{S} wünscht {O6} viel {N4}.","{Sa} يتمنى لـ{O6a} الكثير من {Na4}.","A2","polite","wuenschen"],
["{S} kauft für {O6} {O} ein.","{Sa} يشتري لـ{O6a} {Oa}.","A2","shopping","einkaufen-fuer"],
["{S} kocht für {O6} {O}.","{Sa} يطبخ لـ{O6a} {Oa}.","A2","food","kochen-fuer"],
["{S} spart für {O4}.","{Sa} يدخر لـ{O4a}.","A2","money","sparen-fuer"],
["{S} zahlt {O} mit {O11}.","{Sa} يدفع {Oa} بـ{O11a}.","A2","money","zahlen-mit"],
["{S} bezahlt {O} bar.","{Sa} يدفع {Oa} نقدًا.","A1","money","bar-zahlen"],
["{S} kostet {O12}.","{Oa} يكلف {O12a}.","A1","shopping","kosten"],
["Das ist {A} für {O6}.","هذا {Aa} لـ{O6a}.","A1","general","sein-fuer"],
["Das ist {A} von {O6}.","هذا {Aa} من {O6a}.","A2","general","sein-von"],
["Bei {O5} ist es {A}.","عند {O5a} الجو {Aa}.","A2","weather","bei-wetter"],
["Vor {O5} hat {S} Angst.","أمام {O5a} يخاف {Sa}.","A2","emotions","vor-angst"],
["Nach {O5} {V} {Sl} {P}.","بعد {O5a} {Va} {Sa} {Pa}.","A2","routine","nach-zeit"],
["Ich freue mich, {S3} kennenzulernen.","سعيد بالتعرف عليك.","A1","polite","infinitiv-floskel"],
["Schön, {S3} zu sehen.","جميل أن أراك.","A1","polite","infinitiv-floskel-2"],
["Es ist wichtig, {Vi2}.","من المهم أن {Va2}.","A2","study","es-ist-wichtig-zu"],
["Es ist schwer, {Vi2}.","من الصعب أن {Va2}.","A2","study","es-ist-schwer-zu"],
["{S} hat keine Zeit, weil {S2} viel {V2-n}.","ليس لدى {Sa} وقت لأن {S2a} {V2a} كثيرًا.","A2","work","weil-kausal"],
["{S} bleibt zu Hause, denn {S2} ist krank.","{Sa} يبقى في البيت لأن {S2a} مريض.","A1","health","denn-kausal"],
["{S} lernt Deutsch, um in Deutschland zu arbeiten.","{Sa} يتعلم الألمانية ليعمل في ألمانيا.","A2","germany","um-zu-zweck"],
["{S} spart Geld, damit {S2} {V2} kann.","{Sa} يدخر المال لكي يستطيع {S2a} أن {V2a}.","A2","money","damit-final"],
["Obwohl es regnet, {V} {S} {P}.","رغم المطر {Va} {Sa} {Pa}.","A2","weather","obwohl-voran"],
["{S} geht trotz {Og} {P}.","{Sa} يذهب رغم {Oga} {Pa}.","A2","general","trotz-nominal"],
 ["Während {Sl} {V}, hört {S2} Musik.","أثناء {Va} {Sa} يستمع {S2a} للموسيقى.","A2","hobbies","waehrend-satz"],
["Bevor {S} {V}, trinkt {S2} einen Kaffee.","قبل أن {Va} {Sa} يشرب {S2a} قهوة.","A2","routine","bevor-satz"],
["Nachdem {S} {Vperf-a}, ruht {S2} sich aus.","بعد أن {Va-past} {Sa} يرتاح {S2a}.","A2","routine","nachdem-satz"],
["Sobald {S} {V}, {V} {S} {O}.","حالما {Va} {Sa} {Va2} {Sa} {Oa}.","A2","general","sobald"],
["Falls {S} {V}, {V} {S} mir Bescheid.","إن {Va} {Sa} أخبرني {Sa}.","A2","general","falls"],
["Je öfter {S} {V}, desto {Ac} wird {S3}.","كلما {Va} {Sa} أكثر صار {S3a} {Aca}.","A2","study","je-desto-2"]
];
if(typeof module!=="undefined")module.exports={STEMS,SUBJ,TIMES,PLACES,VG_TRAN,VG_INTRAN,VG_DITRAN,VG_MODAL,PATS};
