/* Transparent compounds: [head, "mod:ar:en,..."] — de=Mod+head, inherits head gender/plural.
   Only semantically transparent pairs (no lexicalized traps). Hand-written Arabic. */
"use strict";
const TRANSP=[
["Abend","Brot:خبز المساء:evening bread,Programm:برنامج المساء:evening program,Kleid:فستان السهرة:evening dress"],
["Abendessen","Familien:عشاء العائلة:family dinner,Weihnachts:عشاء الكريسماس:Christmas dinner"],
["Anruf","Kunden:مكالمة العميل:customer call,Not:مكالمة الطوارئ:emergency call,Rück:مكالمة الرد:return call"],
["Apotheke","Not:صيدلية الطوارئ:emergency pharmacy,Online:الصيدلية الإلكترونية:online pharmacy"],
["Arbeit","Team:العمل الجماعي:teamwork,Büro:العمل المكتبي:office work,Projekt:عمل المشروع:project work,Nacht:العمل الليلي:night work"],
["Arzt","Not:طبيب الطوارئ:emergency doctor,Haus:طبيب الأسرة:family doctor,Kinder:طبيب الأطفال:pediatrician"],
["Aufzug","Personen:مصعد الأشخاص:passenger lift,Lasten:مصعد البضائع:freight lift"],
["Ausflug","Tages:رحلة اليوم:day trip,Familien:رحلة العائلة:family outing,Schul:الرحلة المدرسية:school trip"],
["Ausweis","Studenten:بطاقة الطالب:student ID,Presse:بطاقة الصحافة:press card,Personal:بطاقة الهوية:ID card"],
["Bahnhof","Bus:محطة الحافلات:bus station,Haupt:المحطة الرئيسية:main station"],
["Balkon","Blumen:شرفة الزهور:flower balcony,Süd:الشرفة الجنوبية:south balcony"],
["Bank","Haus:البنك الرئيسي:main bank,Online:البنك الإلكتروني:online bank"],
["Bericht","Wetter:تقرير الطقس:weather report,Unfall:تقرير الحادث:accident report"],
["Beruf","Traum:مهنة الأحلام:dream job,Lehr:مهنة التدريب:apprenticeship trade"],
["Besuch","Familien:زيارة العائلة:family visit,Kurz:زيارة قصيرة:short visit"],
["Bett","Kinder:سرير الأطفال:kids bed,Gäste:سرير الضيوف:guest bed,Etagen:سرير الطوابق:bunk bed"],
["Bewerbung","Online:التقديم الإلكتروني:online application,Job:طلب الوظيفة:job application"],
["Bibliothek","Stadt:مكتبة المدينة:city library,Uni:مكتبة الجامعة:university library"],
["Bild","Familien:صورة العائلة:family picture,Urlaubs:صورة العطلة:holiday picture,Pass:صورة الجواز:passport photo"],
["Blume","Balkon:زهرة الشرفة:balcony flower,Garten:زهرة الحديقة:garden flower"],
["Brot","Toast:خبز التوست:toast bread,Misch:الخبز المشكل:mixed bread,Butter:شطيرة الزبدة:buttered bread"],
["Brötchen","Käse:شطيرة الجبن:cheese roll,Mohn:خبز الخشخاش:poppy roll"],
["Buch","Kinder:كتاب الأطفال:children book,Koch:كتاب الطبخ:cookbook,Notiz:دفتر الملاحظات:notebook"],
["Büro","Großraum:المكتب المفتوح:open-plan office,Home:المكتب المنزلي:home office"],
["Bus","Nacht:حافلة الليل:night bus,Schul:الحافلة المدرسية:school bus,Fern:الحافلة البعيدة:coach"],
["Café","Eis:مقهى الآيس كريم:ice-cream café,Internet:مقهى الإنترنت:internet café"],
["Computer","Büro:حاسوب المكتب:office computer,Arbeits:حاسوب العمل:work computer"],
["Dienst","Not:خدمة الطوارئ:emergency service,Kunden:خدمة العملاء:customer service"],
["Essen","Mittag:وجبة الغداء:lunch,Abend:وجبة العشاء:dinner,Fest:طعام الاحتفال:party food"],
["Fahrrad","Kinder:دراجة الأطفال:kids bike,E:الدراجة الكهربائية:e-bike,Lasten:دراجة الشحن:cargo bike"],
["Fahrt","Bus:رحلة الحافلة:bus ride,Zug:رحلة القطار:train ride,Tax:رحلة التاكسي:taxi ride"],
["Ferien","Sommer:العطلة الصيفية:summer holidays,Herbst:عطلة الخريف:autumn holidays"],
["Fernseher","Röhren:التلفاز القديم:tube TV,Flachbild:التلفاز المسطح:flat TV"],
["Fest","Schul:الاحتفال المدرسي:school festival,Sommer:مهرجان الصيف:summer festival,Musik:مهرجان الموسيقى:music festival"],
["Film","Kinder:فيلم الأطفال:kids film,Abenteuer:فيلم المغامرات:adventure film,Liebes:الفيلم الرومانسي:romance film"],
["Fisch","See:سمك البحيرة:lake fish,Meeres:سمك البحر:sea fish,Räucher:السمك المدخن:smoked fish"],
["Flasche","Glas:الزجاجة الزجاجية:glass bottle,Plastik:الزجاجة البلاستيكية:plastic bottle,Wasser:زجاجة الماء:water bottle"],
["Fleisch","Rind:لحم البقر:beef,Hähnchen:لحم الدجاج:chicken meat,Lamm:لحم الضأن:lamb"],
["Foto","Familien:صورة العائلة:family photo,Urlaubs:صورة العطلة:holiday photo,Bewerbungs:صورة التقديم:application photo"],
["Frage","Prüfungs:سؤال الامتحان:exam question,Umfrage:سؤال الاستطلاع:survey question"],
["Frühstück","Hotel:فطور الفندق:hotel breakfast,Sonntags:فطور الأحد:Sunday breakfast"],
["Garten","Gemüse:حديقة الخضار:vegetable garden,Blumen:حديقة الزهور:flower garden,Obst:بستان الفاكهة:orchard"],
["Geburtstag","Kinder:عيد ميلاد الأطفال:kids birthday,Runden:عيد الميلاد المستدير:milestone birthday"],
["Geld","Taschen:مصروف الجيب:pocket money,Urlaubs:مصروف العطلة:holiday money,Spiel:مال اللعب:play money"],
["Gemüse","Wurzel:الخضار الجذرية:root vegetables,Blatt:الخضار الورقية:leafy greens,Tiefkühl:الخضار المجمدة:frozen veg"],
["Gespräch","Kunden:حديث العميل:client talk,Mitarbeiter:حديث الموظف:staff talk,Feedback:حديث الملاحظات:feedback talk"],
["Getränk","Heiß:المشروب الساخن:hot drink,Kalt:المشروب البارد:cold drink,Sport:مشروب الرياضة:sports drink"],
["Gutschein","Buch:قسيمة الكتب:book voucher,Geschenk:قسيمة الهدية:gift voucher"],
["Handy","Dienst:هاتف العمل:work phone,Firmen:هاتف الشركة:company phone,Kinder:هاتف الأطفال:kids phone"],
["Haus","Reihen:بيت الصف:terraced house,Doppel:البيت المزدوج:semi-detached house,Land:البيت الريفي:country house"],
["Heft","Schreib:دفتر الكتابة:exercise book,Rechen:دفتر الحساب:maths book,Vokabel:دفتر المفردات:vocab book"],
["Hemd","Freizeit:قميص الكاجوال:casual shirt,Büro:قميص المكتب:office shirt"],
["Hotel","Strand:فندق الشاطئ:beach hotel,Business:فندق الأعمال:business hotel,Familien:فندق العائلة:family hotel"],
["Hund","Familien:كلب العائلة:family dog,Schäfer:كلب الراعي:shepherd dog"],
["Jacke","Winter:سترة الشتاء:winter jacket,Regen:سترة المطر:rain jacket,Leder:سترة الجلد:leather jacket"],
["Kaffee","Milch:قهوة بالحليب:milky coffee,Filter:القهوة المقطرة:filter coffee"],
["Karte","Geburtstags:بطاقة عيد الميلاد:birthday card,Weihnachts:بطاقة الكريسماس:Christmas card,Post:البطاقة البريدية:postcard"],
["Käse","Berg:جبن الجبل:mountain cheese,Frisch:الجبن الطازج:fresh cheese"],
["Kino","Autokino:سينما السيارات:drive-in cinema,Open:السينما المفتوحة:open-air cinema"],
["Kleid","Sommer:فستان الصيف:summer dress,Abend2:فستان السهرة:evening gown"],
["Kleidung","Sommer:ملابس الصيف:summer clothes,Winter:ملابس الشتاء:winter clothes,Sport:الملابس الرياضية:sportswear"],
["Konzert","Rock:حفل الروك:rock concert,Klassik:حفل الكلاسيك:classical concert,Open:الحفل المفتوح:open-air concert"],
["Konto","Giro:الحساب الجاري:current account,Spar:حساب التوفير:savings account,Online:الحساب الإلكتروني:online account"],
["Konzert2","Sommer:حفل الصيف:summer concert"],
["Kosten","Fahrt:تكاليف السفر:travel costs,Heiz:تكاليف التدفئة:heating costs"],
["Krankheit","Kinder:مرض الأطفال:childhood illness,Herz:مرض القلب:heart disease"],
["Kuchen","Apfel:كعكة التفاح:apple cake,Schoko:كعكة الشوكولاتة:chocolate cake,Käse:كعكة الجبن:cheesecake"],
["Kurs","Abend:دورة المساء:evening course,Online:الدورة الإلكترونية:online course,Intensiv:الدورة المكثفة:intensive course"],
["Lampe","Tisch:مصباح الطاولة:table lamp,Nacht:مصباح الليل:night lamp,Steh:المصباح الأرضي:floor lamp"],
["Lied","Kinder:أغنية الأطفال:kids song,Weihnachts:أغنية الكريسماس:Christmas carol"],
["Liste","Einkaufs:قائمة التسوق:shopping list,Wort:قائمة الكلمات:word list,Gäste:قائمة الضيوف:guest list"],
["Lohn","Mindest:الحد الأدنى للأجر:minimum wage,Stunden:الأجر بالساعة:hourly wage"],
["Markt","Wochen:السوق الأسبوعي:weekly market,Fisch:سوق السمك:fish market,Gemüse:سوق الخضار:veg market"],
["Medikament","Schmerz:دواء الألم:painkiller,Husten:دواء السعال:cough medicine"],
["Miete","Kalt:الإيجار البارد:base rent,Warm:الإيجار الشامل:warm rent"],
["Milch","Voll:الحليب الكامل:whole milk,Frisch:الحليب الطازج:fresh milk"],
 ["Mittagessen","Geschäfts:غداء العمل:business lunch"],
["Museum","Kunst:متحف الفن:art museum,Natur:متحف الطبيعة:natural history museum"],
["Musik","Pop:موسيقى البوب:pop music,Klassik:الموسيقى الكلاسيكية:classical music,Hintergrund:موسيقى الخلفية:background music"],
["Nachbar","Zimmer:جار الغرفة:room neighbour,Tisch:جار الطاولة:table neighbour"],
["Nacht","Arbeits:ليلة العمل:work night,Sommer:ليلة الصيف:summer night"],
["Nummer","Notfall:رقم الطوارئ:emergency number,Service:رقم الخدمة:service number"],
["Obst","Frisch:الفاكهة الطازجة:fresh fruit,Trocken:الفاكهة المجففة:dried fruit"],
["Öl","Oliven:زيت الزيتون:olive oil,Sonnenblumen:زيت دوار الشمس:sunflower oil"],
["Park","Stadt:منتزه المدينة:city park,Hunde:منتزه الكلاب:dog park"],
["Party","Geburtstags:حفلة عيد الميلاد:birthday party,Garten:حفلة الحديقة:garden party"],
["Pass","Reise:جواز السفر:passport,Impf:دفتر اللقاح:vaccine booklet"],
["Pause","Mittags:استراحة الغداء:lunch break,Kaffee:استراحة القهوة:coffee break,Hof:فسحة الساحة:yard break"],
["Pizza","Salami:بيتزا السلامي:salami pizza,Funghi:بيتزا الفطر:mushroom pizza"],
["Platz","Spiel:ملعب اللعب:playground,Sitz:المقعد:seat,Park:موقف السيارات:parking space"],
["Preis","Tages:سعر اليوم:daily price,Sonder:السعر الخاص:special price"],
["Programm","Abend:برنامج المساء:evening program,Ferien:برنامج العطلة:holiday program"],
["Prüfung","Zwischen:الامتحان النصفي:midterm exam,Abschluss:الامتحان النهائي:final exam,Nach:امتحان الإعادة:retake exam"],
["Pullover","Woll:كنزة الصوف:wool pullover,Strick:الكنزة المحبوكة:knitted pullover"],
["Quittung","Kassen:إيصال الصندوق:till receipt"],
["Radio","Auto:راديو السيارة:car radio,Küchen:راديو المطبخ:kitchen radio"],
["Rechnung","Strom:فاتورة الكهرباء:electricity bill,Telefon:فاتورة الهاتف:phone bill"],
["Regal","Bücher:رف الكتب:bookshelf,Gewürz:رف التوابل:spice rack"],
["Reise","Bus:رحلة الحافلة:coach trip,Flug:رحلة الطيران:flight trip,Tages:رحلة اليوم:day trip"],
["Restaurant","Fisch:مطعم السمك:fish restaurant,Italienisches:المطعم الإيطالي:Italian restaurant"],
["Rezept","Koch:وصفة الطبخ:cooking recipe,Back:وصفة الخبز:baking recipe"],
["Ring","Gold:الخاتم الذهبي:gold ring,Ehe:خاتم الزواج:wedding ring"],
["Rock","Jeans:تنورة الجينز:denim skirt,Sommer:تنورة الصيف:summer skirt"],
["Rucksack","Schul:حقيبة المدرسة:school backpack,Wander:حقيبة التنزه:hiking backpack"],
["Saal","Konzert:قاعة الحفلات:concert hall,Sport:القاعة الرياضية:sports hall"],
["Saft","Apfel:عصير التفاح:apple juice,Orangen:عصير البرتقال:orange juice"],
["Salat","Kartoffel:سلطة البطاطا:potato salad,Nudel:سلطة المعكرونة:pasta salad,Obst:سلطة الفاكهة:fruit salad"],
["Schinken","Koch:لحم الخبز المطبوخ:cooked ham,Roh:اللحم النيئ:raw ham"],
["Schlüssel","Zimmer:مفتاح الغرفة:room key,Fahrrad:مفتاح الدراجة:bike key"],
["Schmerz","Kopf:صداع الرأس:headache,Zahn:ألم الأسنان:toothache,Rücken:ألم الظهر:back pain"],
["Schrank","Kleider:خزانة الملابس:wardrobe,Bücher:خزانة الكتب:bookcase"],
["Schuh","Lauf:حذاء الجري:running shoe,Fußball:حذاء الكرة:football boot"],
["Schule","Grund:المدرسة الابتدائية:primary school,Musik:مدرسة الموسيقى:music school,Tanz:مدرسة الرقص:dance school"],
["Service","Kunden:خدمة العملاء:customer service,Zimmer:خدمة الغرف:room service"],
["Sitz","Fenster:مقعد النافذة:window seat,Gang:مقعد الممر:aisle seat,Kindersitz:مقعد الأطفال:child seat"],
["Sonne","Morgen:شمس الصباح:morning sun,Abend:شمس المساء:evening sun"],
["Spiel","Karten:لعب الورق:card game,Brett:اللعبة اللوحية:board game,Würfel:لعبة النرد:dice game"],
["Sport","Schul:الرياضة المدرسية:school sport,Vereins:رياضة النادي:club sport"],
["Stadt","Alt:المدينة القديمة:old town,Innen:وسط المدينة:city centre"],
["Stelle","Voll:وظيفة الدوام الكامل:full-time post,Teil:وظيفة الدوام الجزئي:part-time post"],
["Stift","Bunt:القلم الملون:coloured pencil,Blei:قلم الرصاص:pencil,Filz:قلم اللباد:felt pen"],
["Straße","Haupt:الشارع الرئيسي:main street,Seiten:الشارع الجانبي:side street,Einbahn:شارع الاتجاه الواحد:one-way street"],
["Strom","Öko:الكهرباء الخضراء:green electricity,Nacht:كهرباء الليل:night electricity"],
["Stunde","Schul:الحصة المدرسية:school lesson,Nachhilfe:حصة التقوية:tutoring lesson"],
["Suppe","Tomaten:شوربة الطماطم:tomato soup,Kürbis:شوربة اليقطين:pumpkin soup,Hühner:شوربة الدجاج:chicken soup"],
["Tag","Arbeits:يوم العمل:workday,Geburts:يوم الميلاد:birthday,Feier:يوم الاحتفال:bank holiday"],
["Tasche","Sport:حقيبة الرياضة:sports bag,Schul:الحقيبة المدرسية:school bag,Einkaufs:كيس التسوق:shopping bag"],
["Tasse","Kaffee:فنجان القهوة:coffee cup,Tee:كوب الشاي:tea cup"],
["Tee","Kräuter:شاي الأعشاب:herbal tea,Früchte:شاي الفواكه:fruit tea,Eis:الشاي المثلج:iced tea"],
["Termin","Arzt:موعد الطبيب:doctor appointment,Beratungs:موعد الاستشارة:consultation appointment,Online:الموعد الإلكتروني:online appointment"],
["Ticket","Kino:تذكرة السينما:cinema ticket,Zug:تذكرة القطار:train ticket,Flug:تذكرة الطيران:flight ticket"],
["Tier","Haus:الحيوان الأليف:pet,Wild:الحيوان البري:wild animal"],
["Tisch","Ess:طاولة الطعام:dining table,Schreib:مكتب الكتابة:writing desk,Nacht:الكومودينو:nightstand"],
["Training","Kraft:تدريب القوة:strength training,Ausdauer:تدريب التحمل:endurance training"],
["Treppe","Haus:درج البيت:house stairs,Keller:درج القبو:cellar stairs"],
["Trinken","Heiß:المشروب الساخن:hot drink2"],
["Tür","Zimmer:باب الغرفة:room door,Balkon:باب الشرفة:balcony door"],
["Uhr","Wand:ساعة الحائط:wall clock,Armband:ساعة اليد:wristwatch"],
["Urlaub","Sommer:العطلة الصيفية:summer holiday,Strand:عطلة الشاطئ:beach holiday,Ski:عطلة التزلج:ski holiday"],
["Versicherung","Hausrat:تأمين المحتويات:household insurance,Reise:تأمين السفر:travel insurance"],
["Vertrag","Miet:عقد الإيجار:rental contract,Arbeits:عقد العمل:work contract,Kauf:عقد الشراء:purchase contract"],
["Vogel","Zug:الطائر المهاجر:migratory bird,Garten:طائر الحديقة:garden bird"],
["Wasser","Mineral:الماء المعدني:mineral water,Leitungs:ماء الصنبور:tap water"],
["Weg","Rad:طريق الدراجات:cycle path,Wander:طريق التنزه:hiking trail,Fuß:ممر المشاة:footpath"],
["Wein","Rot:النبيذ الأحمر:red wine,Weiß:النبيذ الأبيض:white wine"],
["Wetter","Regen:طقس المطر:rainy weather,Urlaubs:طقس العطلة:holiday weather"],
["Woche","Arbeits:أسبوع العمل:working week,Ferien:أسبوع العطلة:holiday week"],
["Wohnung","Dach:شقة السطح:attic flat,Ferien:شقة العطلة:holiday flat"],
["Wurst","Leber:النقانق الكبدية:liver sausage,Blut:نقانق الدم:blood sausage"],
["Zeit","Arbeits:وقت العمل:working time,Freizeit:وقت الفراغ:free time,Schlafens:وقت النوم:bedtime"],
["Zeitung","Tages:الجريدة اليومية:daily paper,Wand:جريدة الحائط:wall newspaper"],
["Zimmer","Kinder:غرفة الأطفال:kids room,Gäste:غرفة الضيوف:guest room,Bade:الحمام:bathroom"],
["Zug","Nacht:قطار الليل:night train,Regional:القطار الإقليمي:regional train"],
["Supermarkt","Bio:السوبرماركت العضوي:organic supermarket"],
["Markt","Gemüse:سوق الخضار:veg market,Fisch2:سوق السمك:fish market"],
["Laden","Buch:محل الكتب:bookshop,Blumen:محل الزهور:flower shop"],
["Café2","Straßen:مقهى الشارع:street café"],
["Bäcker","Bio:المخبز العضوي:organic bakery"],
["Fleischer","Bio:الجزار العضوي:organic butcher"],
["Kiosk","Bahnhofs:كشك المحطة:station kiosk"],
["Tankstelle","Autobahn:محطة طريق السريع:motorway station"],
["Werkstatt","Fahrrad:ورشة الدراجات:bike workshop,Auto:ورشة السيارات:car workshop"],
["Fahrrad2","Stadt:دراجة المدينة:city bike"],
["Auto2","Miet:السيارة المستأجرة:rental car"],
["Reifen","Winter:إطار الشتاء:winter tyre,Sommer2:إطار الصيف:summer tyre"],
["Motor","Benzin:محرك البنزين:petrol engine,Diesel:محرك الديزل:diesel engine"],
["Sitz2","Auto:مقعد السيارة:car seat"],
["Spiegel","Seiten:المرآة الجانبية:side mirror"],
["Licht","Abblend:الضوء المنخفض:dipped headlight,Fern:الضوء العالي:full beam"],
["Bremse","Hand:فرامل اليد:handbrake,Not:فرامل الطوارئ:emergency brake"],
["Unfall","Auto:حادث السيارة:car accident,Arbeits:حادث العمل:work accident"],
["Schaden","Wasser:ضرر المياه:water damage,Sturm:ضرر العاصفة:storm damage"],
["Hilfe","Erste:الإسعافات الأولية:first aid,Nachbarschafts:مساعدة الجيران:neighbourhood help"],
["Notruf","Feuerwehr:نداء الإطفاء:fire call,Polizei:نداء الشرطة:police call"],
["Feuer","Lager:نار المخيم:campfire,Kerzen:ضوء الشموع:candlelight"],
["Wasser2","Ab:مياه الصرف:wastewater"],
["Müll","Rest:البقايا:residual waste,Gelb:كيس الأصفر:yellow bag"],
["Strom2","Solar:الكهرباء الشمسية:solar power"],
["Heizung","Zentral:التدفئة المركزية:central heating,Fußboden:تدفئة الأرضية:underfloor heating"],
["Fenster","Küchen:نافذة المطبخ:kitchen window,Dach:نافذة السطح:skylight"],
["Boden","Holz:الأرضية الخشبية:wooden floor,Fliesen:أرضية البلاط:tiled floor"],
["Wand","Trenn:الجدار الفاصل:partition wall,Außen:الجدار الخارجي:exterior wall"],
["Decke","Zimmer:سقف الغرفة:ceiling"],
["Dach","Flach:السطح المستوي:flat roof,Ziegel:سقف القرميد:tiled roof"],
["Keller","Wein:قبو النبيذ:wine cellar,Party:قبو الحفلات:party cellar"],
["Speicher","Dach:علية السطح:attic"],
["Flur","Eingangs:مدخل الشقة:entrance hall"],
["Küche","Wohn:المطبخ المعيشي:open kitchen,Einbau:المطبخ الجاهز:fitted kitchen"],
["Bad","Gäste:حمام الضيوف:guest bathroom,Familien:حمام العائلة:family bathroom"],
["WC","Gäste:مرحاض الضيوف:guest toilet"],
["Dusche","Regen:دش المطر:rain shower"],
["Badewanne","Eck:حوض الزاوية:corner bath"],
["Waschbecken","Gäste:مغسلة الضيوف:guest basin"],
["Spiegel2","Bad:مرآة الحمام:bathroom mirror"],
["Schrank2","Bad:خزانة الحمام:bathroom cabinet"],
["Teppich2","Bad:سجادة الحمام:bath mat"],
["Handtuch2","Gäste:منشفة الضيوف:guest towel"],
["Bademantel2","Sauna:روب الساونا:sauna robe"],
["Seife","Hand:صابون اليد:hand soap,Dusch:جل الاستحمام:shower gel"],
["Shampoo2","Anti:شامبو ضد القشرة:anti-dandruff shampoo"],
["Creme","Hand:كريم اليد:hand cream,Tages:كريم النهار:day cream"],
["Parfüm","Damen:عطر النساء:women perfume,Herren:عطر الرجال:men perfume"],
["Bürste","Haarbürste:فرشاة الشعر:hairbrush,Zahnbürste:فرشاة الأسنان:toothbrush"],
["Kamm","Taschen:مشط الجيب:pocket comb"],
["Föhn","Reise:مجفف السفر:travel dryer"],
["Rasierer","Elektrischer:ماكينة الحلاقة الكهربائية:electric shaver"],
["Schmuck","Gold:المجوهرات الذهبية:gold jewellery,Silber:المجوهرات الفضية:silver jewellery"],
["Uhr2","Damen:ساعة النساء:ladies watch"],
["Brille","Les:نظارة القراءة:reading glasses,Sonnen:نظارة الشمس:sunglasses"],
["Kontaktlinse","Tages:العدسة اليومية:daily lens,Monats:العدسة الشهرية:monthly lens"],
["Hörgerät","Hinter:سماعة خلف الأذن:behind-ear aid"],
["Rollstuhl","Elektrischer:الكرسي المتحرك الكهربائي:electric wheelchair"],
["Krücke","Unterarm:عكاز الساعد:forearm crutch"],
["Verband","Stütz:الضمادة الداعمة:support bandage"],
["Pflaster","Wund:اللاصق الطبي:adhesive plaster"],
["Tropfen","Augen:قطرة العين:eye drops,Nasen:قطرة الأنف:nose drops"],
["Hustensaft","Kinder:شراب السعال للأطفال:children cough syrup"],
["Schmerztablette","Kopf:قرص الصداع:headache tablet"],
["Vitamin","C:فيتامين سي:vitamin C,D:فيتامين د:vitamin D"],
["Impfung","Grippe:لقاح الإنفلونزا:flu jab,Corona:لقاح كورونا:covid jab"],
["Test","Corona:اختبار كورونا:covid test,Selbst:الاختبار الذاتي:self-test"],
["Maske","FFP2:كمامة FFP2:FFP2 mask,OP:الكمامة الطبية:surgical mask"],
["Desinfektion","Hände:مطهر اليدين:hand sanitiser"],
["Fieber","Hohes:الحمى المرتفعة:high fever"],
["Husten","Reiz:السعال الجاف:dry cough"],
["Schnupfen","Heu:زكام الحساسية:hay fever"],
["Allergie","Pollen:حساسية اللقاح:pollen allergy,Nuss:حساسية المكسرات:nut allergy"],
["Asthma","Bronchial:الربو القصبي:bronchial asthma"],
["Diabetes","Typ:سكري النوع:diabetes type"],
["Blutdruck","Hoher:ضغط الدم المرتفع:high blood pressure"],
["Puls","Ruhe:النبض وقت الراحة:resting pulse"],
["Operation","Knie:عملية الركبة:knee surgery,Not:عملية الطوارئ:emergency surgery"],
["Narbe","OP:ندبة العملية:operation scar"],
["Gips","Bein:جبيرة الساق:leg cast,Arm:جبيرة الذراع:arm cast"],
["Reha","Sport:التأهيل الرياضي:sports rehab"],
["Kur","Mutter:علاج الأمومة:mother-child cure"],
["Therapie","Physio:العلاج الطبيعي:physiotherapy,Ergo:العلاج المهني:occupational therapy"],
["Massage","Rücken:مساج الظهر:back massage"],
["Sauna","Finnische:الساونا الفنلندية:Finnish sauna"],
["Wellness","Wochenende:عطلة الاستجمام:wellness weekend"],
["Fitness","Studio:استوديو اللياقة:fitness studio"],
["Yoga","Morgen:يوغا الصباح:morning yoga"],
["Jogging","Morgen:هرولة الصباح:morning jog"],
["Spaziergang","Abend:نزهة المساء:evening walk,Sonntags:نزهة الأحد:Sunday walk"],
["Ausflug2","Familien:رحلة العائلة:family trip"],
["Picknick","Sommer:نزهة الصيف:summer picnic"],
["Grill","Garten:شواء الحديقة:garden barbecue"],
["Party2","Geburtstags:حفلة عيد الميلاد:birthday party"],
["Feier","Firmen:احتفال الشركة:company party,Weihnachts:احتفال الكريسماس:Christmas party"],
["Hochzeit","Standesamtliche:الزفاف المدني:civil wedding,Kirchen:الزفاف الكنسي:church wedding"],
["Taufe","Kinder:معمودية الأطفال:infant baptism"],
["Geburt","Haus:الولادة المنزلية:home birth"],
["Beerdigung","See:الدفن في البحر:burial at sea"],
["Grab","Familien:قبر العائلة:family grave"],
["Friedhof","Wald:مقبرة الغابة:forest cemetery"],
["Kirche","Dorf:كنيسة القرية:village church,Stadt:كنيسة المدينة:city church"],
["Gottesdienst","Sonntags:قداس الأحد:Sunday service,Weihnachts:قداس الكريسماس:Christmas service"],
["Gebet","Abend:صلاة المساء:evening prayer,Morgen:صلاة الصباح:morning prayer"],
["Fest2","Zucker:عيد الفطر:Sugar Feast"],
["Moschee","Zentral:المسجد المركزي:central mosque"],
["Feiertag2","Gesetzlicher:العطلة الرسمية:public holiday"],
["Tag","Brücken:يوم الجسر:bridge day"],
["Urlaubstag","Rest:يوم الإجازة المتبقي:remaining leave day"],
["Tag","Krankheits:يوم العجز عن العمل:sick day"],
["Überstunde","Bezahlte:الساعة الإضافية المدفوعة:paid overtime"],
["Schicht","Früh:الوردية الصباحية:early shift,Spät:الوردية المسائية:late shift,Nacht:الوردية الليلية:night shift"],
["Praktikum","Schüler:تدريب التلاميذ:pupil internship,Pflicht:التدريب الإلزامي:compulsory internship"],
["Azubi","Erst:متدرب السنة الأولى:first-year trainee"],
["Gehalt","Einstiegs:الراتب الابتدائي:starting salary,Brutto:الراتب الإجمالي:gross salary"],
["Foto","Bewerbungs:صورة التقديم:application photo"],
["Zeugnis","Arbeits:شهادة العمل:job reference"],
["Referenz","Arbeits:مرجع العمل:work reference"],
["Empfehlung","Schriftliche:التوصية المكتوبة:written recommendation"],
["Motivation","Eigen:الدافع الذاتي:self-motivation"],
["Team","Projekt:فريق المشروع:project team"],
["Abteilung","Personal:قسم الموارد البشرية:HR department,Finanz:القسم المالي:finance department"],
["Besprechung","Team:اجتماع الفريق:team meeting,Morgen:اجتماع الصباح:morning meeting"],
["Protokoll","Sitzungs:محضر الاجتماع:meeting minutes"],
["Präsentation","Kunden:عرض العميل:client presentation"],
["Vortrag","Abend:محاضرة المساء:evening lecture"],
["Workshop","Online:ورشة العمل الإلكترونية:online workshop"],
["Seminar","Wochenend:ندوة العطلة:weekend seminar"],
["Konferenz","Video:المؤتمر المرئي:video conference"],
["Messe","Buch:معرض الكتاب:book fair,Auto:معرض السيارات:motor show"],
["Stand","Messe:جناح المعرض:exhibition stand"],
["Besucher","Messe:زائر المعرض:fair visitor"],
["Aussteller","Haupt:العارض الرئيسي:main exhibitor"],
["Kunde","Stamm:الزبون الدائم:regular customer,Neu:الزبون الجديد:new customer"],
["Auftrag","Erst:الطلب الأول:first order,Groß:الطلب الكبير:large order"],
["Angebot","Sonder:العرض الخاص:special offer"],
["Rechnung2","Schluss:الفاتورة الختامية:final invoice"],
["Mahnung","Erste:الإنذار الأول:first reminder"],
["Zahlung","Raten:الدفع بالتقسيط:instalment payment,Voraus:الدفع المسبق:advance payment"],
["Rabatt","Mengen:خصم الكمية:bulk discount,Treue:خصم الولاء:loyalty discount"],
["Garantie","Hersteller:ضمان الشركة المصنعة:manufacturer warranty"],
["Retoure","Kostenlose:الإرجاع المجاني:free returns"],
["Lieferung","Express:التوصيل السريع:express delivery,Standard:التوصيل العادي:standard delivery"],
["Paket2","DHL:طرد DHL:DHL parcel"],
["Sendung","Verlorene:الشحنة المفقودة:lost shipment"],
["Empfänger","Paket:مستلم الطرد:parcel recipient"],
["Absender","Brief:مرسل الخطاب:letter sender"],
["Filiale","Post:مكتب البريد:post office"],
["Briefkasten","Gelbe:صندوق البريد الأصفر:yellow postbox"],
["Briefmarke","Sonder:الطابع الخاص:special stamp"],
["Postkarte","Urlaubs:البطاقة البريدية للعطلة:holiday postcard"],
["Päckchen","Weihnachts:طرد الكريسماس الصغير:small Christmas parcel"]
];
if(typeof module!=="undefined")module.exports={TRANSP};
