/* Verbs: inf|sep|reg|ar|en|cat|lvl|parts(prät,pp or -)|valid prefixed forms are separate list.
   sep: 0 inseparable/no-prefix, 1 separable base. reg: R regular, I irregular. */
"use strict";
const VERBS=[
"sein|0|I|يكون|be|verbs|A1|war,gewesen","haben|0|I|يمتلك / لديه|have|verbs|A1|hatte,gehabt",
"werden|0|I|يصبح|become|verbs|A1|wurde,geworden","können|0|I|يستطيع|can|verbs|A1|konnte,gekonnt",
"müssen|0|I|يجب|must|verbs|A1|musste,gemusst","dürfen|0|I|يسمح|may|verbs|A1|durfte,gedurft",
"sollen|0|I|ينبغي|should|verbs|A1|sollte,gesollt","wollen|0|I|يريد|want|verbs|A1|wollte,gewollt",
"möchten|0|I|يود|would like|verbs|A1|-,gemocht","wissen|0|I|يعرف (معلومة)|know|verbs|A1|wusste,gewusst",
"kennen|0|I|يعرف (شخص/مكان)|know|verbs|A1|kannte,gekannt","gehen|0|I|يذهب|go|verbs|A1|ging,gegangen",
"kommen|0|I|يأتي|come|verbs|A1|kam,gekommen","fahren|0|I|يسافر / يقود|drive|verbs|A1|fuhr,gefahren",
"laufen|0|I|يركض / يمشي|run|verbs|A1|lief,gelaufen","fliegen|0|I|يطير|fly|verbs|A1|flog,geflogen",
"sprechen|0|I|يتحدث|speak|verbs|A1|sprach,gesprochen","sehen|0|I|يرى|see|verbs|A1|sah,gesehen",
"lesen|0|I|يقرأ|read|verbs|A1|las,gelesen","schreiben|0|I|يكتب|write|verbs|A1|schrieb,geschrieben",
"essen|0|I|يأكل|eat|verbs|A1|aß,gegessen","trinken|0|I|يشرب|drink|verbs|A1|trank,getrunken",
"schlafen|0|I|ينام|sleep|verbs|A1|schlief,geschlafen","tragen|0|I|يحمل / يلبس|carry/wear|verbs|A1|trug,getragen",
"treffen|0|I|يقابل|meet|verbs|A1|traf,getroffen","helfen|0|I|يساعد|help|verbs|A1|half,geholfen",
"geben|0|I|يعطي|give|verbs|A1|gab,gegeben","nehmen|0|I|يأخذ|take|verbs|A1|nahm,genommen",
"finden|0|I|يجد|find|verbs|A1|fand,gefunden","bleiben|0|I|يبقى|stay|verbs|A1|blieb,geblieben",
"stehen|0|I|يقف|stand|verbs|A1|stand,gestanden","liegen|0|I|يستلقي|lie|verbs|A1|lag,gelegen",
"sitzen|0|I|يجلس|sit|verbs|A1|saß,gesessen","heißen|0|I|يُسمى|be called|verbs|A1|hieß,geheißen",
"waschen|0|I|يغسل|wash|verbs|A1|wusch,gewaschen","fallen|0|I|يسقط|fall|verbs|A1|fiel,gefallen",
"fangen|0|I|يمسك|catch|verbs|A1|fing,gefangen","halten|0|I|يمسك / يوقف|hold|verbs|A1|hielt,gehalten",
"schließen|0|I|يغلق|close|verbs|A1|schloss,geschlossen","verlieren|0|I|يخسر / يفقد|lose|verbs|A1|verlor,verloren",
"gewinnen|0|I|يفوز|win|verbs|A1|gewann,gewonnen","beginnen|0|I|يبدأ|begin|verbs|A1|begann,begonnen",
"gefallen|0|I|يعجب|please|verbs|A2|gefiel,gefallen","empfehlen|0|I|يوصي|recommend|verbs|A2|empfahl,empfohlen",
"bitten|0|I|يطلب (بأدب)|ask|verbs|A1|bat,gebeten","einladen|1|I|يدعو|invite|verbs|A1|-",
"anrufen|1|R|يتصل|call|verbs|A1|-","aufstehen|1|I|ينهض|get up|verbs|A1|stand auf,aufgestanden",
"einkaufen|1|R|يتسوق|shop|verbs|A1|-","mitbringen|1|I|يحضر معه|bring along|verbs|A1|brachte mit,mitgebracht",
"fernsehen|1|I|يشاهد التلفاز|watch TV|verbs|A1|sah fern,ferngesehen","stattfinden|1|I|يُقام / يحدث|take place|verbs|A2|fand statt,stattgefunden",
"teilnehmen|1|I|يشارك|participate|verbs|A2|nahm teil,teilgenommen","vorschlagen|1|I|يقترح|suggest|verbs|A2|schlug vor,vorgeschlagen",
"anbieten|1|I|يعرض|offer|verbs|A2|bot an,angeboten","absagen|1|R|يلغي|cancel|verbs|A2|-",
"zuhören|1|R|يستمع|listen|verbs|A1|-","aufhören|1|R|يتوقف|stop|verbs|A1|-",
"anfangen|1|I|يبدأ|start|verbs|A1|fing an,angefangen","mitkommen|1|I|يرافق|come along|verbs|A1|kam mit,mitgekommen",
"zurückkommen|1|I|يعود|come back|verbs|A1|kam zurück,zurückgekommen","einschlafen|1|I|يغفو|fall asleep|verbs|A2|schlief ein,eingeschlafen",
"aufwachen|1|R|يستيقظ|wake up|verbs|A1|-","sich waschen|0|I|يغتسل|wash oneself|routine|A1|wusch,gewaschen",
"sich duschen|0|R|يستحم|shower|routine|A1|-","sich anziehen|1|I|يلبس|get dressed|routine|A1|zog an,angezogen",
"sich ausziehen|1|I|يخلع ملابسه|undress|routine|A2|zog aus,ausgezogen","sich setzen|0|R|يجلس|sit down|routine|A1|-",
"sich freuen|0|R|يفرح|be glad|emotions|A1|-","sich ärgern|0|R|ينزعج|be annoyed|emotions|A2|-",
"sich beeilen|0|R|يستعجل|hurry|routine|A1|-","sich verspäten|0|R|يتأخر|be late|routine|A2|-",
"sich treffen|0|I|يلتقي|meet|communication|A1|traf,getroffen","sich verlieben|0|R|يقع في الحب|fall in love|relationships|A2|-",
"sich entschuldigen|0|R|يعتذر|apologize|polite|A1|-","sich bedanken|0|R|يشكر|thank|polite|A1|-",
"sich bewerben|0|I|يتقدم لوظيفة|apply|applications|A2|bewarb,beworben","sich kümmern|0|R|يعتني|take care|health|A2|-",
"arbeiten|0|R|يعمل|work|work|A1|-","lernen|0|R|يتعلم|learn|study|A1|-",
"studieren|0|R|يدرس جامعيًا|study|university|A1|-","lehren|0|R|يُدرّس|teach|education|A2|-",
"üben|0|R|يتدرب|practice|study|A1|-","prüfen|0|R|يفحص / يمتحن|check/examine|school|A2|-",
"bestehen|0|I|يجتاز / يتكون من|pass/consist|school|A2|bestand,bestanden","durchfallen|1|I|يرسب|fail|school|A2|fiel durch,durchgefallen",
"wohnen|0|R|يسكن|live|home|A1|-","leben|0|R|يعيش|live|general|A1|-",
"mieten|0|R|يستأجر|rent|home|A2|-","vermieten|0|R|يؤجر|rent out|home|A2|-",
"umziehen|1|I|ينتقل (سكن)|move|home|A2|zog um,umgezogen","einziehen|1|I|ينتقل إلى|move into|home|A2|zog ein,eingezogen",
"ausziehen|1|I|ينتقل من / يخلع|move out|home|A2|zog aus,ausgezogen","renovieren|0|R|يجدد (البيت)|renovate|home|A2|-",
"putzen|0|R|ينظف|clean|routine|A1|-","aufräumen|1|R|يرتب|tidy up|routine|A1|-",
"spülen|0|R|يغسل الصحون|rinse/dishes|routine|A1|-","waschen2|0|I|يغسل (ملابس)|wash|routine|A1|wusch,gewaschen",
"bügeln|0|R|يكوي|iron|routine|A2|-","kochen|0|R|يطبخ|cook|food|A1|-",
"backen|0|I|يخبز|bake|food|A1|buk,gebacken","braten|0|I|يقلي|fry|food|A2|briet,gebraten",
"schneiden|0|I|يقطع|cut|food|A1|schnitt,geschnitten","schmecken|0|R|يكون طعمه|taste|food|A1|-",
"probieren|0|R|يتذوق / يجرب|try/taste|food|A1|-","bestellen|0|R|يطلب (في مطعم)|order|restaurant|A1|-",
"bezahlen|0|R|يدفع|pay|money|A1|-","kosten|0|R|يكلّف|cost|shopping|A1|-",
"kaufen|0|R|يشتري|buy|shopping|A1|-","verkaufen|0|R|يبيع|sell|shopping|A1|-",
"suchen|0|R|يبحث|search|general|A1|-","brauchen|0|R|يحتاج|need|general|A1|-",
"wünschen|0|R|يتمنى|wish|general|A1|-","hoffen|0|R|يأمل|hope|emotions|A1|-",
"glauben|0|R|يعتقد|believe|general|A1|-","meinen|0|R|يعني / يرى|mean/think|general|A1|-",
"denken|0|I|يفكر|think|general|A1|dachte,gedacht","vergessen|0|I|ينسى|forget|general|A1|vergaß,vergessen",
"erinnern|0|R|يتذكر|remember|general|A2|-","verstehen|0|I|يفهم|understand|study|A1|verstand,verstanden",
"erklären|0|R|يشرح|explain|study|A1|-","fragen|0|R|يسأل|ask|communication|A1|-",
"antworten|0|R|يجيب|answer|communication|A1|-","sagen|0|R|يقول|say|communication|A1|-",
"erzählen|0|R|يروي|tell|communication|A1|-","diskutieren|0|R|يناقش|discuss|general|A2|-",
"versprechen|0|I|يعد|promise|general|A2|versprach,versprochen","vorschlagen2|1|I|يقترح|suggest|general|A2|schlug vor,vorgeschlagen",
"entscheiden|0|I|يقرر|decide|general|A1|entschied,entschieden","planen|0|R|يخطط|plan|general|A1|-",
"vorbereiten|0|R|يُحضّر|prepare|general|A2|-","organisieren|0|R|ينظم|organize|general|A2|-",
"reisen|0|R|يسافر|travel|travel|A1|-","fliegen2|0|I|يسافر جوًا|fly|airport|A1|flog,geflogen",
"buchen|0|R|يحجز|book|travel|A1|-","stornieren|0|R|يلغي الحجز|cancel booking|travel|A2|-",
"abfahren|1|I|يغادر (مواصلات)|depart|transport|A1|fuhr ab,abgefahren","ankommen|1|I|يصل|arrive|travel|A1|kam an,angekommen",
"abholen|1|R|يستقبل / يأخذ|pick up|travel|A1|-","einsteigen|1|I|يصعد (مواصلات)|board|transport|A1|stieg ein,eingestiegen",
"aussteigen|1|I|ينزل (مواصلات)|get off|transport|A1|stieg aus,ausgestiegen","umsteigen|1|I|يبدّل (مواصلات)|change|transport|A2|stieg um,umgestiegen",
"parken|0|R|يركن|park|transport|A1|-","tanken|0|R|يزوّد بالوقود|refuel|transport|A2|-",
"reparieren|0|R|يصلح|repair|services|A1|-","funktionieren|0|R|يعمل (جهاز)|function|tech|A1|-",
"klingeln|0|R|يرن|ring|phones|A1|-","wählen|0|R|يطلب الرقم|dial|phones|A2|-",
"auflegen|1|R|ينهي المكالمة|hang up|phones|A2|-","zurückrufen|1|I|يعاود الاتصال|call back|phones|A2|rief zurück,zurückgerufen",
"schicken|0|R|يرسل|send|communication|A1|-","empfangen|0|I|يستلم|receive|communication|A2|empfing,empfangen",
"drucken|0|R|يطبع|print|computers|A2|-","speichern|0|R|يحفظ (ملف)|save|computers|A1|-",
"löschen|0|R|يحذف|delete|computers|A1|-","installieren|0|R|يثبّت|install|tech|A2|-",
"spielen|0|R|يلعب|play|sports|A1|-","gewinnen2|0|I|يفوز|win|sports|A1|gewann,gewonnen",
"verlieren2|0|I|يخسر|lose|sports|A1|verlor,verloren","trainieren|0|R|يتدرب رياضيًا|train|sports|A2|-",
"schwimmen|0|I|يسبح|swim|sports|A1|schwamm,geschwommen","wandern|0|R|يتنزه مشيًا|hike|hobbies|A2|-",
"tanzen|0|R|يرقص|dance|hobbies|A1|-","singen|0|I|يغني|sing|hobbies|A1|sang,gesungen",
"malen|0|R|يرسم|paint|hobbies|A1|-","zeichnen|0|R|يرسم (خط)|draw|hobbies|A2|-",
"fotografieren|0|R|يصور|photograph|hobbies|A2|-","sammeln|0|R|يجمع|collect|hobbies|A2|-",
"lieben|0|R|يحب|love|emotions|A1|-","hassen|0|R|يكره|hate|emotions|A2|-",
"lachen|0|R|يضحك|laugh|emotions|A1|-","weinen|0|R|يبكي|cry|emotions|A1|-",
"lächeln|0|R|يبتسم|smile|emotions|A1|-","sich entspannen|0|R|يسترخي|relax|health|A2|-",
"rauchen|0|R|يدخن|smoke|health|A2|-","sich erkälten|0|R|يصاب بالزكام|catch cold|health|A2|-",
"sich verletzen|0|R|يصاب|injure oneself|health|A2|-","sich erholen|0|R|يتعافى|recover|health|A2|-",
"wehtun|1|I|يؤلم|hurt|health|A1|tat weh,wehgetan","untersuchen|0|R|يفحص طبيًا|examine|doctor|A2|-",
"verschreiben|0|I|يصف دواءً|prescribe|doctor|A2|verschrieb,verschrieben","heilen|0|R|يشفي|heal|health|A2|-",
"beginnen2|0|I|يبدأ|begin|general|A1|begann,begonnen","enden|0|R|ينتهي|end|general|A1|-",
"dauern|0|R|يستغرق|last|time|A1|-","warten|0|R|ينتظر|wait|general|A1|-",
"sich verspäten2|0|R|يتأخر|be late|routine|A2|-","pünktlich sein|0|I|يكون دقيقًا|be on time|worktalk|A1|war,gewesen",
"feiern|0|R|يحتفل|celebrate|hobbies|A1|-","gratulieren|0|R|يهنئ|congratulate|communication|A1|-",
"schenken|0|R|يهدي|gift|hobbies|A1|-","sich verabreden|0|R|يتواعد|make plans|communication|A2|-",
"klingeln2|0|R|يقرع الجرس|ring bell|home|A2|-","klopfen|0|R|يطرق الباب|knock|home|A1|-",
"öffnen|0|R|يفتح|open|general|A1|-","schließen2|0|I|يغلق|close|general|A1|schloss,geschlossen",
"wechseln|0|R|يبدّل / يصرف|change/exchange|money|A2|-","abheben|1|I|يسحب (نقود)|withdraw|banking|A2|hob ab,abgehoben",
"überweisen|0|I|يحوّل بنكيًا|transfer|banking|A2|überwies,überwiesen","sparen|0|R|يدّخر|save|money|A1|-",
"leihen|0|I|يُعير / يستعير|lend/borrow|general|A2|lieh,geliehen","zurückgeben|1|I|يُعيد|give back|general|A1|gab zurück,zurückgegeben",
"gehören|0|R|يخص / ينتمي|belong|general|A2|-","passieren|0|R|يحدث|happen|general|A1|-",
"stattfinden2|1|I|يُقام|take place|general|A2|fand statt,stattgefunden","gelingen|0|I|ينجح (الأمر)|succeed|general|A2|gelang,gelungen",
"scheitern|0|R|يفشل|fail|general|A2|-","wachsen|0|I|ينمو|grow|nature|A2|wuchs,gewachsen",
"blühen|0|R|يزهر|bloom|nature|A2|-","regnen|0|R|تمطر|rain|weather|A1|-",
"schneien|0|R|تثلج|snow|weather|A1|-","scheinen|0|I|تشرق / يبدو|shine/seem|weather|A1|schien,geschienen",
"gehören2|0|R|ينتمي|belong|general|A2|-","fehlen|0|R|ينقص / يغيب|miss/lack|general|A2|-",
"stimmen|0|R|يصح / يوافق|be correct/agree|general|A2|-","passen|0|R|يناسب|fit/suit|clothing|A1|-",
"stehen2|0|I|يليق (يناسب)|suit|clothing|A2|stand,gestanden","probieren2|0|R|يجرّب (ملابس)|try on|shopping|A2|-",
"anprobieren|1|R|يجرّب (قياس)|try on|shopping|A2|-","umtauschen|0|R|يستبدل|exchange|shopping|A2|-",
"reklamieren|0|R|يتظلم / يشتكي|complain|shopping|A2|-","reservieren|0|R|يحجز|reserve|hotel|A1|-",
"stornieren2|0|R|يلغي| cancel |travel|A2|-","einchecken|1|R|يسجل الوصول|check in|airport|A2|-",
"auschecken|1|R|يسجل المغادرة|check out|hotel|A2|-","versichern|0|R|يؤمّن|insure|services|A2|-",
"beantragen|0|R|يتقدم بطلب|apply for|services|A2|-","genehmigen|0|R|يوافق رسميًا|approve|services|A2|-",
"ablehnen|1|R|يرفض|decline|general|A2|-","annehmen|1|I|يقبل|accept|general|A2|nahm an,angenommen",
"zustimmen|1|R|يوافق|agree|general|A2|-","widersprechen|0|I|يعترض|object|general|A2|widersprach,widersprochen",
"lügen|0|I|يكذب|lie|general|A2|log,gelogen","gestehen|0|I|يعترف|confess|general|A2|gestand,gestanden",
"drohen|0|R|يهدد|threaten|general|A2|-","warnen|0|R|يحذر|warn|general|A2|-",
"retten|0|R|ينقذ|rescue|emergency|A2|-","rufen|0|I|ينادي / يتصل|cry/call|emergency|A1|rief,gerufen",
"fliehen|0|I|يهرب|flee|emergency|A2|floh,geflohen","verstecken|0|R|يختبئ|hide|general|A2|-",
"kämpfen|0|R|يكافح|fight|general|A2|-","siegen|0|R|ينتصر|triumph|sports|A2|-",
"schreien|0|I|يصرخ|shout|emotions|A2|schrie,geschrien","flüstern|0|R|يهمس|whisper|communication|A2|-",
"nicken|0|R|يومئ برأسه|nod|communication|A2|-"
];
/* Valid prefixed verbs: newinf|sep|reg|ar — all established real verbs. */
const PREFIXVERBS=[
"abfahren|1|I|يغادر","ankommen|1|I|يصل","mitkommen|1|I|يرافق","zurückkommen|1|I|يعود",
"einkaufen|1|R|يتسوق","verkaufen|0|R|يبيع","aufstehen|1|I|ينهض","verstehen|0|I|يفهم",
"beschreiben|0|I|يصف","unterschreiben|0|I|يوقّع","vorschlagen|1|I|يقترح","absagen|1|R|يلغي",
"zusagen|1|R|يوافق / يقبل","anzeigen|1|R|يبلّغ / يعرض","aufgeben|1|I|يستسلم / يسلّم","abgeben|1|I|يسلّم",
"angeben|1|I|يدّعي / يذكر","vorgeben|1|I|يتظاهر","umgehen|1|I|يتعامل مع","vergehen|0|I|يمضي (الوقت)",
"bestehen|0|I|يجتاز","verstehen2|0|I|يفهم","aussehen|1|I|يبدو","ansehen|1|I|يشاهد / ينظر إلى",
"nachsehen|1|I|يتحقق","wegsehen|1|I|يشيح بنظره","zusehen|1|I|يراقب","überlegen|0|R|يفكر مليًا",
"erleben|0|R|يعيش تجربة|","überleben|0|R|ينجو","ablehnen|1|R|يرفض","zunehmen|1|I|يزداد وزنًا",
"abnehmen|1|I|ينقص وزنًا","teilnehmen|1|I|يشارك","einnehmen|1|I|يتناول (دواء)","aufnehmen|1|I|يستقبل / يسجّل",
"ausgeben|1|I|ينفق","aufgehen|1|I|تشرق / يُفتح","untergehen|1|I|تغرب","weitergehen|1|I|يستمر",
"zurückgehen|1|I|يتراجع","vorbeigehen|1|I|يمر","eingehen|1|I|يدخل في / يذبل","auskommen|1|I|يتدبر أمره",
"nachkommen|1|I|يلحق / يفي بـ","vorkommen|1|I|يحدث / يوجد","aufkommen|1|I|ينشأ","bekommen|0|I|يحصل على",
"mitbekommen|1|I|يلاحظ / يحصل","vergessen2|0|I|ينسى","anfangen|1|I|يبدأ","empfangen|0|I|يستقبل",
"auffangen|1|I|يلتقط","weitermachen|1|R|يواصل","mitmachen|1|R|يشارك","ausmachen|1|R|يطفئ / يتفق",
"anmachen|1|R|يشغّل","zumachen|1|R|يغلق","aufmachen|1|R|يفتح","saubermachen|1|R|ينظف",
"mitnehmen|1|I|يأخذ معه","teilhaben|1|I|يشارك","vorhaben|1|I|يعتزم","anhaben|1|I|يرتدي",
"vortragen|1|I|يلقي / يقدم","beitragen|1|I|يساهم","auftragen|1|I|يكلّف","eintragen|1|I|يسجّل",
"austragen|1|I|يوزع / يحسم","nachtragen|1|I|يلحق (يسجل لاحقًا)","abtragen|1|I|يزيل"," davontragen|1|I|يخرج بـ",
"einladen|1|I|يدعو","ausladen|1|I|يفرغ / يلغي الدعوة","vorladen|1|I|يستدعي","aufladen|1|I|يشحن",
"herunterladen|1|I|يحمّل","hochladen|1|I|يرفع (ملف)","einzahlen|1|R|يودع (مال)","auszahlen|1|R|يصرف / يدفع",
"nachzahlen|1|R|يدفع لاحقًا","anzahlen|1|R|يدفع مقدمًا","erzählen|0|R|يروي","bestehlen|0|I|يسرق من",
"empfehlen|0|I|يوصي","anstellen|1|R|يوظّف / يصطف","ausstellen|1|R|يعرض / يصدر","bestellen|0|R|يطلب",
"vorstellen|1|R|يقدم / يتخيل","hinstellen|1|R|يضع","darstellen|1|R|يمثل / يعرض","feststellen|1|R|يثبت / يلاحظ",
"nachstellen|1|R|يعيد تمثيل","aufstellen|1|R|يضع / يرشح","abstellen|1|R|يوقف / يضع جانبًا","umstellen|1|R|يحوّل / يعيد ترتيب",
"einstellen|1|R|يوظف / يضبط","wiederholen|0|R|يكرر","abholen|1|R|يستقبل","ausholen|1|R|يستعد للضرب / يسهب",
"einholen|1|R|يلحق بـ","nachholen|1|R|يعوّض","wiederkommen|1|I|يعود مجددًا","heimkommen|1|I|يصل البيت",
"rauskommen|1|I|يخرج","reinkommen|1|I|يدخل","runterkommen|1|I|ينزل","raufkommen|1|I|يصعد",
"mitfahren|1|I|يرافق بالسيارة","weiterfahren|1|I|يواصل السير","losfahren|1|I|ينطلق","heimfahren|1|I|يقود عائدًا",
"vorfahren|1|I|يتقدم بالسيارة","zurückfahren|1|I|يعود بالسيارة","zusammenfahren|1|I|يصطدم","auseinandergehen|1|I|يتفرق",
"spazierengehen|1|I|يتنزه","einkaufen2|1|R|يتسوق","nachdenken|1|I|يتأمل","sich ausruhen|1|R|يرتاح",
"sich umziehen|1|I|يبدل ملابسه","sich vorstellen|1|R|يقدم نفسه","sich erkundigen|0|R|يستفسر","sich bewerben2|0|I|يتقدم لوظيفة",
"sich beschweren|0|R|يشتكي","sich benehmen|0|I|يتصرف","sich verirren|0|R|يضيع","sich verspäten3|0|R|يتأخر",
"sich verlieben2|0|R|يقع في الحب","sich verloben|0|R|يخطب","sich scheiden lassen|0|I|يتطلق","sich versöhnen|0|R|يتصالح"
];
if(typeof module!=="undefined")module.exports={VERBS,PREFIXVERBS};
